add_subdirectory(Ballistic)
add_subdirectory(DoubleIntegrator)
add_subdirectory(DubinsAirplane)
add_subdirectory(DubinsAirplane3D)
add_subdirectory(FixedWing6DOF)
add_subdirectory(HarmonicOscillator)
add_subdirectory(Multirotor)
add_subdirectory(RigidBody6DOF)
add_subdirectory(SimpleAircraft)
add_subdirectory(SimpleCar)
add_subdirectory(SimpleQuadrotor)
add_subdirectory(SingleIntegrator)
add_subdirectory(Unicycle)
add_subdirectory(Unicycle3D)
add_subdirectory(UUV6DOF)
if (JSBSIM_FOUND)
  add_subdirectory(JSBSimControl)
  add_subdirectory(JSBSimModel)
endif()


set(PROJECT_PLUGINS ${PROJECT_PLUGINS} PARENT_SCOPE)
