var annotated_dup =
[
    [ "anonymous_namespace{CSV.h}", "namespaceanonymous__namespace_02CSV_8h_03.html", [
      [ "StringifyVisitor", "structanonymous__namespace_02CSV_8h_03_1_1StringifyVisitor.html", "structanonymous__namespace_02CSV_8h_03_1_1StringifyVisitor" ]
    ] ],
    [ "anonymous_namespace{Topic.cpp}", "namespaceanonymous__namespace_02Topic_8cpp_03.html", [
      [ "Topic", "classanonymous__namespace_02Topic_8cpp_03_1_1Topic.html", "classanonymous__namespace_02Topic_8cpp_03_1_1Topic" ]
    ] ],
    [ "auction_assign", "namespaceauction__assign.html", [
      [ "AuctionAssign", "classauction__assign_1_1AuctionAssign.html", "classauction__assign_1_1AuctionAssign" ]
    ] ],
    [ "boost", "namespaceboost.html", [
      [ "geometry", "namespaceboost_1_1geometry.html", [
        [ "index", "namespaceboost_1_1geometry_1_1index.html", [
          [ "rtree", "classboost_1_1geometry_1_1index_1_1rtree.html", null ]
        ] ]
      ] ],
      [ "optional", "classboost_1_1optional.html", null ]
    ] ],
    [ "JSBSim", "namespaceJSBSim.html", [
      [ "FGOutputFGMod", "classJSBSim_1_1FGOutputFGMod.html", "classJSBSim_1_1FGOutputFGMod" ]
    ] ],
    [ "rapidxml", "namespacerapidxml.html", [
      [ "xml_node", "classrapidxml_1_1xml__node.html", null ]
    ] ],
    [ "scrimmage", "namespacescrimmage.html", [
      [ "autonomy", "namespacescrimmage_1_1autonomy.html", [
        [ "motor_schemas", "namespacescrimmage_1_1autonomy_1_1motor__schemas.html", [
          [ "AvoidEntityMS", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1AvoidEntityMS.html", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1AvoidEntityMS" ],
          [ "BehaviorBase", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1BehaviorBase.html", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1BehaviorBase" ],
          [ "MoveToGoalMS", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1MoveToGoalMS.html", "classscrimmage_1_1autonomy_1_1motor__schemas_1_1MoveToGoalMS" ]
        ] ],
        [ "APITester", "classscrimmage_1_1autonomy_1_1APITester.html", "classscrimmage_1_1autonomy_1_1APITester" ],
        [ "ArduPilot", "classscrimmage_1_1autonomy_1_1ArduPilot.html", "classscrimmage_1_1autonomy_1_1ArduPilot" ],
        [ "AuctionAssign", "classscrimmage_1_1autonomy_1_1AuctionAssign.html", "classscrimmage_1_1autonomy_1_1AuctionAssign" ],
        [ "AutonomyExecutor", "classscrimmage_1_1autonomy_1_1AutonomyExecutor.html", "classscrimmage_1_1autonomy_1_1AutonomyExecutor" ],
        [ "AvoidWalls", "classscrimmage_1_1autonomy_1_1AvoidWalls.html", "classscrimmage_1_1autonomy_1_1AvoidWalls" ],
        [ "Boids", "classscrimmage_1_1autonomy_1_1Boids.html", "classscrimmage_1_1autonomy_1_1Boids" ],
        [ "BoundaryDefense", "classscrimmage_1_1autonomy_1_1BoundaryDefense.html", "classscrimmage_1_1autonomy_1_1BoundaryDefense" ],
        [ "CommandStringRelay", "classscrimmage_1_1autonomy_1_1CommandStringRelay.html", "classscrimmage_1_1autonomy_1_1CommandStringRelay" ],
        [ "Control3D", "classscrimmage_1_1autonomy_1_1Control3D.html", "classscrimmage_1_1autonomy_1_1Control3D" ],
        [ "FlightGearMultiplayer", "classscrimmage_1_1autonomy_1_1FlightGearMultiplayer.html", "classscrimmage_1_1autonomy_1_1FlightGearMultiplayer" ],
        [ "Follow", "classscrimmage_1_1autonomy_1_1Follow.html", "classscrimmage_1_1autonomy_1_1Follow" ],
        [ "GoToWaypoint", "classscrimmage_1_1autonomy_1_1GoToWaypoint.html", "classscrimmage_1_1autonomy_1_1GoToWaypoint" ],
        [ "GraphvizFSM", "classscrimmage_1_1autonomy_1_1GraphvizFSM.html", "classscrimmage_1_1autonomy_1_1GraphvizFSM" ],
        [ "JoystickAutonomy", "classscrimmage_1_1autonomy_1_1JoystickAutonomy.html", "classscrimmage_1_1autonomy_1_1JoystickAutonomy" ],
        [ "MOOSAutonomy", "classscrimmage_1_1autonomy_1_1MOOSAutonomy.html", "classscrimmage_1_1autonomy_1_1MOOSAutonomy" ],
        [ "MOOSNode", "classscrimmage_1_1autonomy_1_1MOOSNode.html", "classscrimmage_1_1autonomy_1_1MOOSNode" ],
        [ "MotorSchemas", "classscrimmage_1_1autonomy_1_1MotorSchemas.html", "classscrimmage_1_1autonomy_1_1MotorSchemas" ],
        [ "Predator", "classscrimmage_1_1autonomy_1_1Predator.html", "classscrimmage_1_1autonomy_1_1Predator" ],
        [ "ROSAirSim", "classscrimmage_1_1autonomy_1_1ROSAirSim.html", "classscrimmage_1_1autonomy_1_1ROSAirSim" ],
        [ "ROSAutonomy", "classscrimmage_1_1autonomy_1_1ROSAutonomy.html", "classscrimmage_1_1autonomy_1_1ROSAutonomy" ],
        [ "ROSControl", "classscrimmage_1_1autonomy_1_1ROSControl.html", "classscrimmage_1_1autonomy_1_1ROSControl" ],
        [ "ShapeDraw", "classscrimmage_1_1autonomy_1_1ShapeDraw.html", "classscrimmage_1_1autonomy_1_1ShapeDraw" ],
        [ "SimplePubSub", "classscrimmage_1_1autonomy_1_1SimplePubSub.html", "classscrimmage_1_1autonomy_1_1SimplePubSub" ],
        [ "Straight", "classscrimmage_1_1autonomy_1_1Straight.html", "classscrimmage_1_1autonomy_1_1Straight" ],
        [ "TakeFlag", "classscrimmage_1_1autonomy_1_1TakeFlag.html", "classscrimmage_1_1autonomy_1_1TakeFlag" ],
        [ "TrailMS", "classscrimmage_1_1autonomy_1_1TrailMS.html", "classscrimmage_1_1autonomy_1_1TrailMS" ],
        [ "TrajectoryPoint", "classscrimmage_1_1autonomy_1_1TrajectoryPoint.html", "classscrimmage_1_1autonomy_1_1TrajectoryPoint" ],
        [ "TrajectoryRecordPlayback", "classscrimmage_1_1autonomy_1_1TrajectoryRecordPlayback.html", "classscrimmage_1_1autonomy_1_1TrajectoryRecordPlayback" ],
        [ "Waypoint", "classscrimmage_1_1autonomy_1_1Waypoint.html", "classscrimmage_1_1autonomy_1_1Waypoint" ],
        [ "WaypointDispatcher", "classscrimmage_1_1autonomy_1_1WaypointDispatcher.html", "classscrimmage_1_1autonomy_1_1WaypointDispatcher" ],
        [ "WaypointGenerator", "classscrimmage_1_1autonomy_1_1WaypointGenerator.html", "classscrimmage_1_1autonomy_1_1WaypointGenerator" ],
        [ "WaypointList", "classscrimmage_1_1autonomy_1_1WaypointList.html", "classscrimmage_1_1autonomy_1_1WaypointList" ],
        [ "WaypointListProcessor", "classscrimmage_1_1autonomy_1_1WaypointListProcessor.html", "classscrimmage_1_1autonomy_1_1WaypointListProcessor" ]
      ] ],
      [ "common", "namespacescrimmage_1_1common.html", [
        [ "FSMBehavior", "classscrimmage_1_1common_1_1FSMBehavior.html", "classscrimmage_1_1common_1_1FSMBehavior" ]
      ] ],
      [ "controller", "namespacescrimmage_1_1controller.html", [
        [ "AircraftPIDController", "classscrimmage_1_1controller_1_1AircraftPIDController.html", "classscrimmage_1_1controller_1_1AircraftPIDController" ],
        [ "AircraftToSingleIntegratorController", "classscrimmage_1_1controller_1_1AircraftToSingleIntegratorController.html", "classscrimmage_1_1controller_1_1AircraftToSingleIntegratorController" ],
        [ "AxisScale", "classscrimmage_1_1controller_1_1AxisScale.html", "classscrimmage_1_1controller_1_1AxisScale" ],
        [ "DirectController", "classscrimmage_1_1controller_1_1DirectController.html", "classscrimmage_1_1controller_1_1DirectController" ],
        [ "DoubleIntegratorControllerVelYaw", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerVelYaw.html", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerVelYaw" ],
        [ "DoubleIntegratorControllerWaypoint", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerWaypoint.html", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerWaypoint" ],
        [ "FixedWing6DOFControllerPID", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerPID.html", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerPID" ],
        [ "FixedWing6DOFControllerROS", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerROS.html", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerROS" ],
        [ "HarmonicOscillatorConstController", "classscrimmage_1_1controller_1_1HarmonicOscillatorConstController.html", "classscrimmage_1_1controller_1_1HarmonicOscillatorConstController" ],
        [ "Joystick", "classscrimmage_1_1controller_1_1Joystick.html", "classscrimmage_1_1controller_1_1Joystick" ],
        [ "JoystickController", "classscrimmage_1_1controller_1_1JoystickController.html", "classscrimmage_1_1controller_1_1JoystickController" ],
        [ "JSBSimControlControllerHeadingPID", "classscrimmage_1_1controller_1_1JSBSimControlControllerHeadingPID.html", "classscrimmage_1_1controller_1_1JSBSimControlControllerHeadingPID" ],
        [ "JSBSimModelControllerDirect", "classscrimmage_1_1controller_1_1JSBSimModelControllerDirect.html", "classscrimmage_1_1controller_1_1JSBSimModelControllerDirect" ],
        [ "JSBSimModelControllerHeadingPID", "classscrimmage_1_1controller_1_1JSBSimModelControllerHeadingPID.html", "classscrimmage_1_1controller_1_1JSBSimModelControllerHeadingPID" ],
        [ "MotionBattery", "classscrimmage_1_1controller_1_1MotionBattery.html", "classscrimmage_1_1controller_1_1MotionBattery" ],
        [ "MultirotorControllerOmega", "classscrimmage_1_1controller_1_1MultirotorControllerOmega.html", "classscrimmage_1_1controller_1_1MultirotorControllerOmega" ],
        [ "MultirotorControllerPID", "classscrimmage_1_1controller_1_1MultirotorControllerPID.html", "classscrimmage_1_1controller_1_1MultirotorControllerPID" ],
        [ "RigidBody6DOFControllerPID", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerPID.html", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerPID" ],
        [ "RigidBody6DOFControllerROS", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerROS.html", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerROS" ],
        [ "SimpleAircraftControllerPID", "classscrimmage_1_1controller_1_1SimpleAircraftControllerPID.html", "classscrimmage_1_1controller_1_1SimpleAircraftControllerPID" ],
        [ "SimpleCarControllerHeading", "classscrimmage_1_1controller_1_1SimpleCarControllerHeading.html", "classscrimmage_1_1controller_1_1SimpleCarControllerHeading" ],
        [ "SimpleQuadrotorControllerLQR", "classscrimmage_1_1controller_1_1SimpleQuadrotorControllerLQR.html", "classscrimmage_1_1controller_1_1SimpleQuadrotorControllerLQR" ],
        [ "SingleIntegratorControllerSimple", "classscrimmage_1_1controller_1_1SingleIntegratorControllerSimple.html", "classscrimmage_1_1controller_1_1SingleIntegratorControllerSimple" ],
        [ "SingleIntegratorControllerWaypoint", "classscrimmage_1_1controller_1_1SingleIntegratorControllerWaypoint.html", "classscrimmage_1_1controller_1_1SingleIntegratorControllerWaypoint" ],
        [ "UnicycleControllerPoint", "classscrimmage_1_1controller_1_1UnicycleControllerPoint.html", "classscrimmage_1_1controller_1_1UnicycleControllerPoint" ],
        [ "UnicyclePID", "classscrimmage_1_1controller_1_1UnicyclePID.html", "classscrimmage_1_1controller_1_1UnicyclePID" ],
        [ "UUV6DOFLinearEnergy", "classscrimmage_1_1controller_1_1UUV6DOFLinearEnergy.html", "classscrimmage_1_1controller_1_1UUV6DOFLinearEnergy" ],
        [ "UUV6DOFPIDController", "classscrimmage_1_1controller_1_1UUV6DOFPIDController.html", "classscrimmage_1_1controller_1_1UUV6DOFPIDController" ]
      ] ],
      [ "interaction", "namespacescrimmage_1_1interaction.html", [
        [ "Boundary", "classscrimmage_1_1interaction_1_1Boundary.html", "classscrimmage_1_1interaction_1_1Boundary" ],
        [ "BoundaryBase", "classscrimmage_1_1interaction_1_1BoundaryBase.html", "classscrimmage_1_1interaction_1_1BoundaryBase" ],
        [ "BulletCollision", "classscrimmage_1_1interaction_1_1BulletCollision.html", "classscrimmage_1_1interaction_1_1BulletCollision" ],
        [ "CaptureInBoundaryInteraction", "classscrimmage_1_1interaction_1_1CaptureInBoundaryInteraction.html", "classscrimmage_1_1interaction_1_1CaptureInBoundaryInteraction" ],
        [ "Cuboid", "classscrimmage_1_1interaction_1_1Cuboid.html", "classscrimmage_1_1interaction_1_1Cuboid" ],
        [ "EnforceBoundaryInteraction", "classscrimmage_1_1interaction_1_1EnforceBoundaryInteraction.html", "classscrimmage_1_1interaction_1_1EnforceBoundaryInteraction" ],
        [ "ExternalForceField", "classscrimmage_1_1interaction_1_1ExternalForceField.html", "classscrimmage_1_1interaction_1_1ExternalForceField" ],
        [ "FlagCaptureInteraction", "classscrimmage_1_1interaction_1_1FlagCaptureInteraction.html", "classscrimmage_1_1interaction_1_1FlagCaptureInteraction" ],
        [ "GraphInteraction", "classscrimmage_1_1interaction_1_1GraphInteraction.html", "classscrimmage_1_1interaction_1_1GraphInteraction" ],
        [ "GroundCollision", "classscrimmage_1_1interaction_1_1GroundCollision.html", "classscrimmage_1_1interaction_1_1GroundCollision" ],
        [ "GRPCCommandString", "classscrimmage_1_1interaction_1_1GRPCCommandString.html", "classscrimmage_1_1interaction_1_1GRPCCommandString" ],
        [ "Map2DInfo", "classscrimmage_1_1interaction_1_1Map2DInfo.html", "classscrimmage_1_1interaction_1_1Map2DInfo" ],
        [ "MapGen2D", "classscrimmage_1_1interaction_1_1MapGen2D.html", "classscrimmage_1_1interaction_1_1MapGen2D" ],
        [ "Plane", "classscrimmage_1_1interaction_1_1Plane.html", "classscrimmage_1_1interaction_1_1Plane" ],
        [ "Polyhedron", "classscrimmage_1_1interaction_1_1Polyhedron.html", "classscrimmage_1_1interaction_1_1Polyhedron" ],
        [ "RandomAttrit", "classscrimmage_1_1interaction_1_1RandomAttrit.html", "classscrimmage_1_1interaction_1_1RandomAttrit" ],
        [ "ROSClockServer", "classscrimmage_1_1interaction_1_1ROSClockServer.html", "classscrimmage_1_1interaction_1_1ROSClockServer" ],
        [ "ROSShapeViz", "classscrimmage_1_1interaction_1_1ROSShapeViz.html", "classscrimmage_1_1interaction_1_1ROSShapeViz" ],
        [ "SimpleCapture", "classscrimmage_1_1interaction_1_1SimpleCapture.html", "classscrimmage_1_1interaction_1_1SimpleCapture" ],
        [ "SimpleCollision", "classscrimmage_1_1interaction_1_1SimpleCollision.html", "classscrimmage_1_1interaction_1_1SimpleCollision" ],
        [ "Sphere", "classscrimmage_1_1interaction_1_1Sphere.html", "classscrimmage_1_1interaction_1_1Sphere" ],
        [ "TerrainGenerator", "classscrimmage_1_1interaction_1_1TerrainGenerator.html", "classscrimmage_1_1interaction_1_1TerrainGenerator" ],
        [ "TerrainMap", "classscrimmage_1_1interaction_1_1TerrainMap.html", "classscrimmage_1_1interaction_1_1TerrainMap" ]
      ] ],
      [ "metrics", "namespacescrimmage_1_1metrics.html", [
        [ "CPA", "classscrimmage_1_1metrics_1_1CPA.html", "classscrimmage_1_1metrics_1_1CPA" ],
        [ "CPAData", "classscrimmage_1_1metrics_1_1CPAData.html", "classscrimmage_1_1metrics_1_1CPAData" ],
        [ "FlagCaptureMetrics", "classscrimmage_1_1metrics_1_1FlagCaptureMetrics.html", "classscrimmage_1_1metrics_1_1FlagCaptureMetrics" ],
        [ "OpenAIRewards", "classscrimmage_1_1metrics_1_1OpenAIRewards.html", "classscrimmage_1_1metrics_1_1OpenAIRewards" ],
        [ "Score", "classscrimmage_1_1metrics_1_1Score.html", "classscrimmage_1_1metrics_1_1Score" ],
        [ "SimpleCaptureMetrics", "classscrimmage_1_1metrics_1_1SimpleCaptureMetrics.html", "classscrimmage_1_1metrics_1_1SimpleCaptureMetrics" ],
        [ "SimpleCollisionMetrics", "classscrimmage_1_1metrics_1_1SimpleCollisionMetrics.html", "classscrimmage_1_1metrics_1_1SimpleCollisionMetrics" ],
        [ "SimpleCollisionScore", "classscrimmage_1_1metrics_1_1SimpleCollisionScore.html", "classscrimmage_1_1metrics_1_1SimpleCollisionScore" ]
      ] ],
      [ "motion", "namespacescrimmage_1_1motion.html", [
        [ "Ballistic", "classscrimmage_1_1motion_1_1Ballistic.html", "classscrimmage_1_1motion_1_1Ballistic" ],
        [ "DoubleIntegrator", "classscrimmage_1_1motion_1_1DoubleIntegrator.html", "classscrimmage_1_1motion_1_1DoubleIntegrator" ],
        [ "DubinsAirplane", "classscrimmage_1_1motion_1_1DubinsAirplane.html", "classscrimmage_1_1motion_1_1DubinsAirplane" ],
        [ "DubinsAirplane3D", "classscrimmage_1_1motion_1_1DubinsAirplane3D.html", "classscrimmage_1_1motion_1_1DubinsAirplane3D" ],
        [ "FixedWing6DOF", "classscrimmage_1_1motion_1_1FixedWing6DOF.html", "classscrimmage_1_1motion_1_1FixedWing6DOF" ],
        [ "HarmonicOscillator", "classscrimmage_1_1motion_1_1HarmonicOscillator.html", "classscrimmage_1_1motion_1_1HarmonicOscillator" ],
        [ "JSBSimControl", "classscrimmage_1_1motion_1_1JSBSimControl.html", "classscrimmage_1_1motion_1_1JSBSimControl" ],
        [ "JSBSimModel", "classscrimmage_1_1motion_1_1JSBSimModel.html", "classscrimmage_1_1motion_1_1JSBSimModel" ],
        [ "Multirotor", "classscrimmage_1_1motion_1_1Multirotor.html", "classscrimmage_1_1motion_1_1Multirotor" ],
        [ "MultirotorState", "classscrimmage_1_1motion_1_1MultirotorState.html", "classscrimmage_1_1motion_1_1MultirotorState" ],
        [ "PwmState", "classscrimmage_1_1motion_1_1PwmState.html", "classscrimmage_1_1motion_1_1PwmState" ],
        [ "RigidBody6DOF", "classscrimmage_1_1motion_1_1RigidBody6DOF.html", "classscrimmage_1_1motion_1_1RigidBody6DOF" ],
        [ "RigidBody6DOFBase", "classscrimmage_1_1motion_1_1RigidBody6DOFBase.html", "classscrimmage_1_1motion_1_1RigidBody6DOFBase" ],
        [ "RigidBody6DOFState", "classscrimmage_1_1motion_1_1RigidBody6DOFState.html", "classscrimmage_1_1motion_1_1RigidBody6DOFState" ],
        [ "Rotor", "classscrimmage_1_1motion_1_1Rotor.html", "classscrimmage_1_1motion_1_1Rotor" ],
        [ "SimpleAircraft", "classscrimmage_1_1motion_1_1SimpleAircraft.html", "classscrimmage_1_1motion_1_1SimpleAircraft" ],
        [ "SimpleCar", "classscrimmage_1_1motion_1_1SimpleCar.html", "classscrimmage_1_1motion_1_1SimpleCar" ],
        [ "SimpleQuadrotor", "classscrimmage_1_1motion_1_1SimpleQuadrotor.html", "classscrimmage_1_1motion_1_1SimpleQuadrotor" ],
        [ "SingleIntegrator", "classscrimmage_1_1motion_1_1SingleIntegrator.html", "classscrimmage_1_1motion_1_1SingleIntegrator" ],
        [ "Unicycle", "classscrimmage_1_1motion_1_1Unicycle.html", "classscrimmage_1_1motion_1_1Unicycle" ],
        [ "Unicycle3D", "classscrimmage_1_1motion_1_1Unicycle3D.html", "classscrimmage_1_1motion_1_1Unicycle3D" ],
        [ "UUV6DOF", "classscrimmage_1_1motion_1_1UUV6DOF.html", "classscrimmage_1_1motion_1_1UUV6DOF" ]
      ] ],
      [ "network", "namespacescrimmage_1_1network.html", [
        [ "GlobalNetwork", "classscrimmage_1_1network_1_1GlobalNetwork.html", "classscrimmage_1_1network_1_1GlobalNetwork" ],
        [ "GPUSphereNetwork", "classscrimmage_1_1network_1_1GPUSphereNetwork.html", "classscrimmage_1_1network_1_1GPUSphereNetwork" ],
        [ "GPUSphereNetworkUtils", "classscrimmage_1_1network_1_1GPUSphereNetworkUtils.html", "classscrimmage_1_1network_1_1GPUSphereNetworkUtils" ],
        [ "LocalNetwork", "classscrimmage_1_1network_1_1LocalNetwork.html", "classscrimmage_1_1network_1_1LocalNetwork" ],
        [ "SphereNetwork", "classscrimmage_1_1network_1_1SphereNetwork.html", "classscrimmage_1_1network_1_1SphereNetwork" ]
      ] ],
      [ "sensor", "namespacescrimmage_1_1sensor.html", [
        [ "AirSimImageType", "classscrimmage_1_1sensor_1_1AirSimImageType.html", "classscrimmage_1_1sensor_1_1AirSimImageType" ],
        [ "AirSimImuType", "classscrimmage_1_1sensor_1_1AirSimImuType.html", "classscrimmage_1_1sensor_1_1AirSimImuType" ],
        [ "AirSimLidarType", "classscrimmage_1_1sensor_1_1AirSimLidarType.html", "classscrimmage_1_1sensor_1_1AirSimLidarType" ],
        [ "AirSimSensor", "classscrimmage_1_1sensor_1_1AirSimSensor.html", "classscrimmage_1_1sensor_1_1AirSimSensor" ],
        [ "AltitudeAboveTerrain", "classscrimmage_1_1sensor_1_1AltitudeAboveTerrain.html", "classscrimmage_1_1sensor_1_1AltitudeAboveTerrain" ],
        [ "CameraConfig", "classscrimmage_1_1sensor_1_1CameraConfig.html", "classscrimmage_1_1sensor_1_1CameraConfig" ],
        [ "ContactBlobCamera", "classscrimmage_1_1sensor_1_1ContactBlobCamera.html", "classscrimmage_1_1sensor_1_1ContactBlobCamera" ],
        [ "ContactBlobCameraType", "classscrimmage_1_1sensor_1_1ContactBlobCameraType.html", "classscrimmage_1_1sensor_1_1ContactBlobCameraType" ],
        [ "GPS", "classscrimmage_1_1sensor_1_1GPS.html", "classscrimmage_1_1sensor_1_1GPS" ],
        [ "LOSSensor", "classscrimmage_1_1sensor_1_1LOSSensor.html", "classscrimmage_1_1sensor_1_1LOSSensor" ],
        [ "NoisyContacts", "classscrimmage_1_1sensor_1_1NoisyContacts.html", "classscrimmage_1_1sensor_1_1NoisyContacts" ],
        [ "NoisyState", "classscrimmage_1_1sensor_1_1NoisyState.html", "classscrimmage_1_1sensor_1_1NoisyState" ],
        [ "RayTrace", "classscrimmage_1_1sensor_1_1RayTrace.html", "classscrimmage_1_1sensor_1_1RayTrace" ],
        [ "RigidBody6DOFStateSensor", "classscrimmage_1_1sensor_1_1RigidBody6DOFStateSensor.html", "classscrimmage_1_1sensor_1_1RigidBody6DOFStateSensor" ],
        [ "ROSAltimeter", "classscrimmage_1_1sensor_1_1ROSAltimeter.html", "classscrimmage_1_1sensor_1_1ROSAltimeter" ],
        [ "ROSCompass", "classscrimmage_1_1sensor_1_1ROSCompass.html", "classscrimmage_1_1sensor_1_1ROSCompass" ],
        [ "ROSIMUSensor", "classscrimmage_1_1sensor_1_1ROSIMUSensor.html", "classscrimmage_1_1sensor_1_1ROSIMUSensor" ],
        [ "SimpleINS", "classscrimmage_1_1sensor_1_1SimpleINS.html", "classscrimmage_1_1sensor_1_1SimpleINS" ]
      ] ],
      [ "ActorContact", "classscrimmage_1_1ActorContact.html", "classscrimmage_1_1ActorContact" ],
      [ "Angles", "classscrimmage_1_1Angles.html", "classscrimmage_1_1Angles" ],
      [ "Autonomy", "classscrimmage_1_1Autonomy.html", "classscrimmage_1_1Autonomy" ],
      [ "Battery", "classscrimmage_1_1Battery.html", "classscrimmage_1_1Battery" ],
      [ "CameraInterface", "classscrimmage_1_1CameraInterface.html", "classscrimmage_1_1CameraInterface" ],
      [ "CameraResetParams", "structscrimmage_1_1CameraResetParams.html", "structscrimmage_1_1CameraResetParams" ],
      [ "Color_t", "structscrimmage_1_1Color__t.html", "structscrimmage_1_1Color__t" ],
      [ "ConfigParse", "classscrimmage_1_1ConfigParse.html", "classscrimmage_1_1ConfigParse" ],
      [ "Contact", "classscrimmage_1_1Contact.html", "classscrimmage_1_1Contact" ],
      [ "Controller", "classscrimmage_1_1Controller.html", "classscrimmage_1_1Controller" ],
      [ "CSV", "classscrimmage_1_1CSV.html", "classscrimmage_1_1CSV" ],
      [ "DelayedTask", "classscrimmage_1_1DelayedTask.html", "classscrimmage_1_1DelayedTask" ],
      [ "Entity", "classscrimmage_1_1Entity.html", "classscrimmage_1_1Entity" ],
      [ "EntityInitParams", "structscrimmage_1_1EntityInitParams.html", "structscrimmage_1_1EntityInitParams" ],
      [ "EntityInteraction", "classscrimmage_1_1EntityInteraction.html", "classscrimmage_1_1EntityInteraction" ],
      [ "EntityPlugin", "classscrimmage_1_1EntityPlugin.html", "classscrimmage_1_1EntityPlugin" ],
      [ "ExponentialFilter", "classscrimmage_1_1ExponentialFilter.html", "classscrimmage_1_1ExponentialFilter" ],
      [ "External", "classscrimmage_1_1External.html", "classscrimmage_1_1External" ],
      [ "FileSearch", "classscrimmage_1_1FileSearch.html", "classscrimmage_1_1FileSearch" ],
      [ "Frame", "classscrimmage_1_1Frame.html", "classscrimmage_1_1Frame" ],
      [ "FrameUpdateClient", "classscrimmage_1_1FrameUpdateClient.html", "classscrimmage_1_1FrameUpdateClient" ],
      [ "GenerateInfo", "structscrimmage_1_1GenerateInfo.html", "structscrimmage_1_1GenerateInfo" ],
      [ "GlobalService", "classscrimmage_1_1GlobalService.html", "classscrimmage_1_1GlobalService" ],
      [ "GPUController", "classscrimmage_1_1GPUController.html", "classscrimmage_1_1GPUController" ],
      [ "GPUMapBuffer", "classscrimmage_1_1GPUMapBuffer.html", "classscrimmage_1_1GPUMapBuffer" ],
      [ "GPUMotionModel", "classscrimmage_1_1GPUMotionModel.html", "classscrimmage_1_1GPUMotionModel" ],
      [ "GPUMotionModelImplementation", "classscrimmage_1_1GPUMotionModelImplementation.html", "classscrimmage_1_1GPUMotionModelImplementation" ],
      [ "GPUPluginBuildParams", "structscrimmage_1_1GPUPluginBuildParams.html", "structscrimmage_1_1GPUPluginBuildParams" ],
      [ "GPUVariableIO", "classscrimmage_1_1GPUVariableIO.html", "classscrimmage_1_1GPUVariableIO" ],
      [ "Grid", "classscrimmage_1_1Grid.html", "classscrimmage_1_1Grid" ],
      [ "ID", "classscrimmage_1_1ID.html", "classscrimmage_1_1ID" ],
      [ "Interface", "classscrimmage_1_1Interface.html", "classscrimmage_1_1Interface" ],
      [ "KernelBuildOpts", "structscrimmage_1_1KernelBuildOpts.html", "structscrimmage_1_1KernelBuildOpts" ],
      [ "LibXML2ParserAttribute", "classscrimmage_1_1LibXML2ParserAttribute.html", "classscrimmage_1_1LibXML2ParserAttribute" ],
      [ "LibXML2ParserDocument", "classscrimmage_1_1LibXML2ParserDocument.html", "classscrimmage_1_1LibXML2ParserDocument" ],
      [ "LibXML2ParserNode", "classscrimmage_1_1LibXML2ParserNode.html", "classscrimmage_1_1LibXML2ParserNode" ],
      [ "Log", "classscrimmage_1_1Log.html", "classscrimmage_1_1Log" ],
      [ "Logger", "classscrimmage_1_1Logger.html", "classscrimmage_1_1Logger" ],
      [ "Message", "classscrimmage_1_1Message.html", "classscrimmage_1_1Message" ],
      [ "MessageBase", "classscrimmage_1_1MessageBase.html", "classscrimmage_1_1MessageBase" ],
      [ "Metrics", "classscrimmage_1_1Metrics.html", "classscrimmage_1_1Metrics" ],
      [ "MissionParse", "classscrimmage_1_1MissionParse.html", "classscrimmage_1_1MissionParse" ],
      [ "MotionModel", "classscrimmage_1_1MotionModel.html", "classscrimmage_1_1MotionModel" ],
      [ "Network", "classscrimmage_1_1Network.html", "classscrimmage_1_1Network" ],
      [ "NetworkDevice", "classscrimmage_1_1NetworkDevice.html", "classscrimmage_1_1NetworkDevice" ],
      [ "OriginAxes", "classscrimmage_1_1OriginAxes.html", "classscrimmage_1_1OriginAxes" ],
      [ "Parameter", "classscrimmage_1_1Parameter.html", "classscrimmage_1_1Parameter" ],
      [ "ParameterBase", "classscrimmage_1_1ParameterBase.html", "classscrimmage_1_1ParameterBase" ],
      [ "ParameterServer", "classscrimmage_1_1ParameterServer.html", "classscrimmage_1_1ParameterServer" ],
      [ "PID", "classscrimmage_1_1PID.html", "classscrimmage_1_1PID" ],
      [ "Plugin", "classscrimmage_1_1Plugin.html", "classscrimmage_1_1Plugin" ],
      [ "PluginAndConfig", "structscrimmage_1_1PluginAndConfig.html", "structscrimmage_1_1PluginAndConfig" ],
      [ "PluginInfo", "classscrimmage_1_1PluginInfo.html", "classscrimmage_1_1PluginInfo" ],
      [ "PluginManager", "classscrimmage_1_1PluginManager.html", "classscrimmage_1_1PluginManager" ],
      [ "PluginOverrides", "structscrimmage_1_1PluginOverrides.html", "structscrimmage_1_1PluginOverrides" ],
      [ "PluginStatus", "classscrimmage_1_1PluginStatus.html", "classscrimmage_1_1PluginStatus" ],
      [ "Publisher", "classscrimmage_1_1Publisher.html", "classscrimmage_1_1Publisher" ],
      [ "PubSub", "classscrimmage_1_1PubSub.html", "classscrimmage_1_1PubSub" ],
      [ "Quaternion", "classscrimmage_1_1Quaternion.html", "classscrimmage_1_1Quaternion" ],
      [ "Random", "classscrimmage_1_1Random.html", "classscrimmage_1_1Random" ],
      [ "RapidXMLParserAttribute", "classscrimmage_1_1RapidXMLParserAttribute.html", "classscrimmage_1_1RapidXMLParserAttribute" ],
      [ "RapidXMLParserDocument", "classscrimmage_1_1RapidXMLParserDocument.html", "classscrimmage_1_1RapidXMLParserDocument" ],
      [ "RapidXMLParserNode", "classscrimmage_1_1RapidXMLParserNode.html", "classscrimmage_1_1RapidXMLParserNode" ],
      [ "RTree", "classscrimmage_1_1RTree.html", "classscrimmage_1_1RTree" ],
      [ "ScrimmageMsgServiceImpl", "classscrimmage_1_1ScrimmageMsgServiceImpl.html", "classscrimmage_1_1ScrimmageMsgServiceImpl" ],
      [ "Sensor", "classscrimmage_1_1Sensor.html", "classscrimmage_1_1Sensor" ],
      [ "SimControl", "classscrimmage_1_1SimControl.html", "classscrimmage_1_1SimControl" ],
      [ "SimUtilsInfo", "structscrimmage_1_1SimUtilsInfo.html", "structscrimmage_1_1SimUtilsInfo" ],
      [ "State", "classscrimmage_1_1State.html", "classscrimmage_1_1State" ],
      [ "StateManager", "classscrimmage_1_1StateManager.html", "classscrimmage_1_1StateManager" ],
      [ "StateWithCovariance", "classscrimmage_1_1StateWithCovariance.html", "classscrimmage_1_1StateWithCovariance" ],
      [ "Subscriber", "classscrimmage_1_1Subscriber.html", "classscrimmage_1_1Subscriber" ],
      [ "SubscriberBase", "classscrimmage_1_1SubscriberBase.html", "classscrimmage_1_1SubscriberBase" ],
      [ "TeamInfo", "structscrimmage_1_1TeamInfo.html", "structscrimmage_1_1TeamInfo" ],
      [ "Time", "classscrimmage_1_1Time.html", "classscrimmage_1_1Time" ],
      [ "Timer", "classscrimmage_1_1Timer.html", "classscrimmage_1_1Timer" ],
      [ "Updater", "classscrimmage_1_1Updater.html", "classscrimmage_1_1Updater" ],
      [ "VariableIO", "classscrimmage_1_1VariableIO.html", "classscrimmage_1_1VariableIO" ],
      [ "Viewer", "classscrimmage_1_1Viewer.html", "classscrimmage_1_1Viewer" ],
      [ "XMLParserAttribute", "classscrimmage_1_1XMLParserAttribute.html", "classscrimmage_1_1XMLParserAttribute" ],
      [ "XMLParserDocument", "classscrimmage_1_1XMLParserDocument.html", "classscrimmage_1_1XMLParserDocument" ],
      [ "XMLParserNode", "classscrimmage_1_1XMLParserNode.html", "classscrimmage_1_1XMLParserNode" ],
      [ "XMLParserTraits", "structscrimmage_1_1XMLParserTraits.html", null ],
      [ "XMLParserTraits< class LibXML2ParserDocument >", "structscrimmage_1_1XMLParserTraits_3_01class_01LibXML2ParserDocument_01_4.html", "structscrimmage_1_1XMLParserTraits_3_01class_01LibXML2ParserDocument_01_4" ],
      [ "XMLParserTraits< class LibXML2ParserNode >", "structscrimmage_1_1XMLParserTraits_3_01class_01LibXML2ParserNode_01_4.html", "structscrimmage_1_1XMLParserTraits_3_01class_01LibXML2ParserNode_01_4" ],
      [ "XMLParserTraits< class RapidXMLParserDocument >", "structscrimmage_1_1XMLParserTraits_3_01class_01RapidXMLParserDocument_01_4.html", "structscrimmage_1_1XMLParserTraits_3_01class_01RapidXMLParserDocument_01_4" ],
      [ "XMLParserTraits< class RapidXMLParserNode >", "structscrimmage_1_1XMLParserTraits_3_01class_01RapidXMLParserNode_01_4.html", "structscrimmage_1_1XMLParserTraits_3_01class_01RapidXMLParserNode_01_4" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< scrimmage::ID >", "structstd_1_1hash_3_01scrimmage_1_1ID_01_4.html", "structstd_1_1hash_3_01scrimmage_1_1ID_01_4" ]
    ] ],
    [ "HG4930IMUBudget", "classHG4930IMUBudget.html", "classHG4930IMUBudget" ],
    [ "IMUErrorBudgetTemplate", "classIMUErrorBudgetTemplate.html", "classIMUErrorBudgetTemplate" ],
    [ "IMUErrorSimulator", "classIMUErrorSimulator.html", "classIMUErrorSimulator" ],
    [ "NoisyIMUData", "structNoisyIMUData.html", "structNoisyIMUData" ]
];