SCRIMMAGE: scrimmage::controller::JSBSimControlControllerHeadingPID Class Reference
scrimmage::controller::JSBSimControlControllerHeadingPID Class Reference
#include <JSBSimControlControllerHeadingPID.h>
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step (double t, double dt) override
Public Member Functions inherited from scrimmage::Controller
void set_state (StatePtr &state)
void set_desired_state (StatePtr &desired_state)
void close (double) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
scrimmage::Angles angles_to_jsbsim_
scrimmage::Angles angles_from_jsbsim_
scrimmage::PID heading_pid_
double prev_desired_yaw_
bool heading_lag_initialized_
scrimmage::PID roll_pid_
scrimmage::PID pitch_pid_
scrimmage::PID yaw_pid_
int throttle_idx_ = 0
int elevator_idx_ = 0
int aileron_idx_ = 0
int rudder_idx_ = 0
Protected Attributes inherited from scrimmage::Controller
StatePtr state_
StatePtr desired_state_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 45 of file JSBSimControlControllerHeadingPID.h.
Member Function Documentation
init()
void scrimmage::controller::JSBSimControlControllerHeadingPID::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Controller.
Definition at line 51 of file JSBSimControlControllerHeadingPID.cpp.
{
     angles_from_jsbsim_.set_input_clock_direction(ang::Rotate::CW);
     angles_from_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_Y);
     angles_from_jsbsim_.set_output_clock_direction(ang::Rotate::CCW);
     angles_from_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_input_clock_direction(ang::Rotate::CCW);
     angles_to_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_output_clock_direction(ang::Rotate::CW);
     angles_to_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_Y);
     if (!roll_pid_.init(params["roll_pid"], true)) {
         std::cout << "Failed to parse roll_pid." << std::endl;
     }
     if (!pitch_pid_.init(params["pitch_pid"], true)) {
         std::cout << "Failed to parse pitch_pid." << std::endl;
     }
     if (!yaw_pid_.init(params["yaw_pid"], true)) {
         std::cout << "Failed to parse yaw_pid." << std::endl;
     }
     // Setup variable index for controllers
     throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::Out);
     elevator_idx_ = vars_.declare(VariableIO::Type::elevator, VariableIO::Direction::Out);
     aileron_idx_ = vars_.declare(VariableIO::Type::aileron, VariableIO::Direction::Out);
     rudder_idx_ = vars_.declare(VariableIO::Type::rudder, VariableIO::Direction::Out);
 }
References scrimmage::VariableIO::aileron, aileron_idx_, angles_from_jsbsim_, angles_to_jsbsim_, scrimmage::Angles::CCW, scrimmage::Angles::CW, scrimmage::VariableIO::declare(), scrimmage::VariableIO::elevator, elevator_idx_, scrimmage::PID::init(), scrimmage::VariableIO::Out, pitch_pid_, scrimmage::Angles::Pos_X, scrimmage::Angles::Pos_Y, roll_pid_, scrimmage::VariableIO::rudder, rudder_idx_, scrimmage::Angles::set_input_clock_direction(), scrimmage::Angles::set_input_zero_axis(), scrimmage::Angles::set_output_clock_direction(), scrimmage::Angles::set_output_zero_axis(), scrimmage::VariableIO::throttle, throttle_idx_, scrimmage::EntityPlugin::vars_, and yaw_pid_.
step()
bool scrimmage::controller::JSBSimControlControllerHeadingPID::step (double t, double dt) override virtual
Reimplemented from scrimmage::Controller.
Definition at line 79 of file JSBSimControlControllerHeadingPID.cpp.
{
     // Roll stabilizer
     roll_pid_.set_setpoint(0);
     double u_roll = roll_pid_.step(dt, state_->quat().roll());
     vars_.output(aileron_idx_, ang::angle_pi(u_roll));
     // Pitch stabilizer
     pitch_pid_.set_setpoint(0);
     vars_.output(elevator_idx_, -pitch_pid_.step(dt, state_->quat().pitch()));
     // Yaw stabilizer
     double desired_yaw = desired_state_->quat().yaw();
     angles_to_jsbsim_.set_angle(ang::rad2deg(desired_yaw));
     yaw_pid_.set_setpoint(ang::deg2rad(angles_to_jsbsim_.angle()));
     vars_.output(rudder_idx_, -yaw_pid_.step(dt, state_->quat().yaw()));
     return true;
 }
References aileron_idx_, scrimmage::Angles::angle(), scrimmage::Angles::angle_pi(), angles_to_jsbsim_, scrimmage::Angles::deg2rad(), scrimmage::Controller::desired_state_, elevator_idx_, scrimmage::VariableIO::output(), pitch_pid_, scrimmage::Angles::rad2deg(), roll_pid_, rudder_idx_, scrimmage::Angles::set_angle(), scrimmage::PID::set_setpoint(), scrimmage::Controller::state_, scrimmage::PID::step(), scrimmage::EntityPlugin::vars_, and yaw_pid_.
Member Data Documentation
angles_to_jsbsim_
scrimmage::Angles scrimmage::controller::JSBSimControlControllerHeadingPID::angles_to_jsbsim_ protected
Definition at line 51 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
angles_from_jsbsim_
scrimmage::Angles scrimmage::controller::JSBSimControlControllerHeadingPID::angles_from_jsbsim_ protected
Definition at line 52 of file JSBSimControlControllerHeadingPID.h.
Referenced by init().
heading_pid_
scrimmage::PID scrimmage::controller::JSBSimControlControllerHeadingPID::heading_pid_ protected
Definition at line 54 of file JSBSimControlControllerHeadingPID.h.
prev_desired_yaw_
double scrimmage::controller::JSBSimControlControllerHeadingPID::prev_desired_yaw_ protected
Definition at line 55 of file JSBSimControlControllerHeadingPID.h.
heading_lag_initialized_
bool scrimmage::controller::JSBSimControlControllerHeadingPID::heading_lag_initialized_ protected
Definition at line 56 of file JSBSimControlControllerHeadingPID.h.
roll_pid_
scrimmage::PID scrimmage::controller::JSBSimControlControllerHeadingPID::roll_pid_ protected
Definition at line 58 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
pitch_pid_
scrimmage::PID scrimmage::controller::JSBSimControlControllerHeadingPID::pitch_pid_ protected
Definition at line 59 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
yaw_pid_
scrimmage::PID scrimmage::controller::JSBSimControlControllerHeadingPID::yaw_pid_ protected
Definition at line 60 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
throttle_idx_
int scrimmage::controller::JSBSimControlControllerHeadingPID::throttle_idx_ = 0 protected
Definition at line 62 of file JSBSimControlControllerHeadingPID.h.
Referenced by init().
elevator_idx_
int scrimmage::controller::JSBSimControlControllerHeadingPID::elevator_idx_ = 0 protected
Definition at line 63 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
aileron_idx_
int scrimmage::controller::JSBSimControlControllerHeadingPID::aileron_idx_ = 0 protected
Definition at line 64 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
rudder_idx_
int scrimmage::controller::JSBSimControlControllerHeadingPID::rudder_idx_ = 0 protected
Definition at line 65 of file JSBSimControlControllerHeadingPID.h.
Referenced by init(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/controller/JSBSimControlControllerHeadingPID/JSBSimControlControllerHeadingPID.h
/root/scrimmage/scrimmage/src/plugins/controller/JSBSimControlControllerHeadingPID/JSBSimControlControllerHeadingPID.cpp