SCRIMMAGE: scrimmage::ID Class Reference
scrimmage::ID Class Reference
#include <ID.h>
Public Member Functions
ID ()
ID (int id, int sub_swarm_id, int team_id)
void set_id (int id)
void set_sub_swarm_id (int sub_swarm_id)
void set_team_id (int team_id)
int id () const
int sub_swarm_id () const
int team_id () const
bool operator== (const ID &other) const
bool operator< (const ID &other) const
Protected Attributes
int id_
int sub_swarm_id_
int team_id_
Friends
std::ostream & operator<< (std::ostream &os, const scrimmage::ID &id)
Detailed Description
Definition at line 39 of file ID.h.
Constructor & Destructor Documentation
ID() [1/2]
scrimmage::ID::ID ()
Definition at line 39 of file ID.cpp.
 : id_(0), sub_swarm_id_(0), team_id_(0) {}
ID() [2/2]
scrimmage::ID::ID (int id, int sub_swarm_id, int team_id)
Definition at line 41 of file ID.cpp.
                                             :
     id_(id), sub_swarm_id_(sub_swarm_id), team_id_(team_id) {}
Member Function Documentation
set_id()
void scrimmage::ID::set_id (int id)
Definition at line 44 of file ID.cpp.
 { id_ = id; }
References id(), and id_.
Referenced by scrimmage::Entity::init().
set_sub_swarm_id()
void scrimmage::ID::set_sub_swarm_id (int sub_swarm_id)
Definition at line 46 of file ID.cpp.
 {sub_swarm_id_ = sub_swarm_id; }
References sub_swarm_id(), and sub_swarm_id_.
Referenced by scrimmage::Entity::init().
set_team_id()
void scrimmage::ID::set_team_id (int team_id)
Definition at line 48 of file ID.cpp.
 { team_id_ = team_id; }
References team_id(), and team_id_.
Referenced by scrimmage::Entity::init().
id()
int scrimmage::ID::id () const
Definition at line 50 of file ID.cpp.
 { return id_; }
References id_.
Referenced by scrimmage::create_frame(), scrimmage::Entity::parse_visual(), scrimmage::proto_2_contact(), REGISTER_PLUGIN(), set_id(), auction_assign.AuctionAssign::step_autonomy(), and scrimmage::External::update_ents().
sub_swarm_id()
int scrimmage::ID::sub_swarm_id () const
Definition at line 52 of file ID.cpp.
 { return sub_swarm_id_; }
References sub_swarm_id_.
Referenced by set_sub_swarm_id().
team_id()
int scrimmage::ID::team_id () const
Definition at line 54 of file ID.cpp.
 { return team_id_; }
References team_id_.
Referenced by scrimmage::Entity::parse_visual(), REGISTER_PLUGIN(), and set_team_id().
operator==()
bool scrimmage::ID::operator== (const ID & other) const
Definition at line 56 of file ID.cpp.
{
     return id_ == other.id_ &&
         sub_swarm_id_ == other.sub_swarm_id_ &&
         team_id_ == other.team_id_;
 }
References id_, sub_swarm_id_, and team_id_.
operator<()
bool scrimmage::ID::operator< (const ID & other) const
Definition at line 62 of file ID.cpp.
{
     if (id_ < other.id_) {
         return true;
     } else if (sub_swarm_id_ < other.sub_swarm_id_) {
         return true;
     } else if (team_id_ < other.team_id_) {
         return true;
     } else {
         return false;
     }
 }
References id_, sub_swarm_id_, and team_id_.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const scrimmage::ID & id) friend
Definition at line 74 of file ID.cpp.
{
     os << id.id_ << ", " << id.sub_swarm_id_ << ", " << id.team_id_;
     return os;
 }
Member Data Documentation
id_
int scrimmage::ID::id_ protected
Definition at line 59 of file ID.h.
Referenced by id(), operator<(), operator==(), and set_id().
sub_swarm_id_
int scrimmage::ID::sub_swarm_id_ protected
Definition at line 60 of file ID.h.
Referenced by operator<(), operator==(), set_sub_swarm_id(), and sub_swarm_id().
team_id_
int scrimmage::ID::team_id_ protected
Definition at line 61 of file ID.h.
Referenced by operator<(), operator==(), set_team_id(), and team_id().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/ID.h
/root/scrimmage/scrimmage/src/common/ID.cpp