SCRIMMAGE: scrimmage::VariableIO Class Reference
scrimmage::VariableIO Class Reference
#include <VariableIO.h>
Public Types
enum Direction { Direction::In = 0, Direction::Out }
enum Type {
Type::desired_altitude, Type::desired_speed, Type::desired_heading, Type::desired_roll,
Type::desired_pitch, Type::desired_turn_rate, Type::desired_pitch_rate, Type::desired_roll_rate,
Type::desired_glide_slope, Type::speed, Type::throttle, Type::elevator,
Type::aileron, Type::rudder, Type::turn_rate, Type::pitch_rate,
Type::roll_rate, Type::velocity_x, Type::velocity_y, Type::velocity_z,
Type::position_x, Type::position_y, Type::position_z, Type::acceleration_x,
Type::acceleration_y, Type::acceleration_z
}
Public Member Functions
VariableIO ()
std::map< std::string, int > & output_variable_index ()
std::map< std::string, int > & input_variable_index ()
int add_input_variable (const std::string &var)
int add_output_variable (const std::string &var)
int declare (std::string var, Direction dir)
int declare (Type type, Direction dir)
double input (int i)
void output (int i, double x)
double output (int i)
bool exists (std::string var, Direction dir)
bool exists (Type type, Direction dir)
std::set< std::string > declared_input_variables ()
std::set< std::string > declared_output_variables ()
const std::map< Type, std::string > & type_map () const
const std::shared_ptr< Eigen::VectorXd > & input ()
const std::shared_ptr< Eigen::VectorXd > & output ()
void set_input (const std::shared_ptr< Eigen::VectorXd > &input)
void set_output (const std::shared_ptr< Eigen::VectorXd > &output)
Protected Attributes
int next_input_variable_index_ = 0
std::map< std::string, int > input_variable_index_
std::map< std::string, int > output_variable_index_
std::shared_ptr< Eigen::VectorXd > input_
std::shared_ptr< Eigen::VectorXd > output_
std::set< std::string > declared_input_variables_
std::set< std::string > declared_output_variables_
Static Protected Attributes
static std::map< Type, std::string > type_map_
Friends
void connect (VariableIO &output, VariableIO &input)
Connect two VariableIO objects where writing to the output of the first object will transfer the data to the input of the second object.
Detailed Description
Definition at line 47 of file VariableIO.h.
Member Enumeration Documentation
Direction
enum scrimmage::VariableIO::Direction strong
Enumerator
In
Out
Definition at line 49 of file VariableIO.h.
 {In = 0, Out};
Type
enum scrimmage::VariableIO::Type strong
Enumerator
desired_altitude
desired_speed
desired_heading
desired_roll
desired_pitch
desired_turn_rate
desired_pitch_rate
desired_roll_rate
desired_glide_slope
speed
throttle
elevator
aileron
rudder
turn_rate
pitch_rate
roll_rate
velocity_x
velocity_y
velocity_z
position_x
position_y
position_z
acceleration_x
acceleration_y
acceleration_z
Definition at line 50 of file VariableIO.h.
                     {
         desired_altitude,
         desired_speed,
         desired_heading,
         desired_roll,
         desired_pitch,
         desired_turn_rate,
         desired_pitch_rate,
         desired_roll_rate,
         desired_glide_slope,  // Usually tan(z_vel / (sqrt(x_vel^2 + y_vel^2)))
         speed,
         throttle,
         elevator,
         aileron,
         rudder,
         turn_rate,
         pitch_rate,
         roll_rate,
         velocity_x,
         velocity_y,
         velocity_z,
         position_x,
         position_y,
         position_z,
         acceleration_x,
         acceleration_y,
         acceleration_z
     };
Constructor & Destructor Documentation
VariableIO()
scrimmage::VariableIO::VariableIO ()
Definition at line 80 of file VariableIO.cpp.
                        : input_(std::make_shared<Eigen::VectorXd>()),
                            output_(std::make_shared<Eigen::VectorXd>()) {
 }
Member Function Documentation
output_variable_index()
std::map< std::string, int > & scrimmage::VariableIO::output_variable_index ()
Definition at line 84 of file VariableIO.cpp.
{
     return output_variable_index_;
 }
References output_variable_index_.
Referenced by scrimmage::connect(), and REGISTER_PLUGIN().
input_variable_index()
std::map< std::string, int > & scrimmage::VariableIO::input_variable_index ()
Definition at line 88 of file VariableIO.cpp.
{
     return input_variable_index_;
 }
References input_variable_index_.
Referenced by scrimmage::connect(), scrimmage::External::create_entity(), and scrimmage::print_io_error().
add_input_variable()
int scrimmage::VariableIO::add_input_variable (const std::string & var)
Definition at line 92 of file VariableIO.cpp.
{
     // If the variable already exists, return its existing index
     declared_input_variables_.insert(var);
     auto it = input_variable_index_.find(var);
     if (it != input_variable_index_.end()) {
         return it->second;
     }
     // If it doesn't exist, add it to the map and resize input vector
     int idx = next_input_variable_index_;
     input_variable_index_[var] = idx;
     ++next_input_variable_index_;
     *input_ = Eigen::VectorXd::Zero(input_variable_index_.size());
     return idx;
 }
References declared_input_variables_, input_, input_variable_index_, and next_input_variable_index_.
Referenced by scrimmage::External::create_entity(), and declare().
add_output_variable()
int scrimmage::VariableIO::add_output_variable (const std::string & var)
Definition at line 108 of file VariableIO.cpp.
{
     // If the variable already exists, return its existing index
     declared_output_variables_.insert(var);
     int idx;
     auto it = output_variable_index_.find(var);
     if (it != output_variable_index_.end()) {
         idx = it->second;
     } else {
         // If it doesn't exist, it will be ignored by the next vector
         idx = output_variable_index_.size();
         output_variable_index_[var] = idx;
     }
     return idx;
 }
References declared_output_variables_, and output_variable_index_.
Referenced by declare().
declare() [1/2]
int scrimmage::VariableIO::declare (std::string var, Direction dir)
Definition at line 123 of file VariableIO.cpp.
{
     if (dir == VariableIO::Direction::In) {
         return add_input_variable(var);
     } else {
         return add_output_variable(var);
     }
 }
References add_input_variable(), add_output_variable(), and In.
Referenced by declare(), scrimmage::autonomy::Boids::init(), scrimmage::autonomy::Predator::init(), scrimmage::motion::Unicycle::init(), scrimmage::controller::DoubleIntegratorControllerWaypoint::init(), scrimmage::motion::SimpleCar::init(), scrimmage::motion::SingleIntegrator::init(), scrimmage::controller::JSBSimModelControllerDirect::init(), scrimmage::controller::SimpleCarControllerHeading::init(), scrimmage::autonomy::AuctionAssign::init(), scrimmage::controller::SingleIntegratorControllerSimple::init(), scrimmage::controller::DoubleIntegratorControllerVelYaw::init(), scrimmage::controller::SingleIntegratorControllerWaypoint::init(), scrimmage::autonomy::AvoidWalls::init(), scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), scrimmage::controller::UnicycleControllerPoint::init(), scrimmage::controller::FixedWing6DOFControllerROS::init(), scrimmage::autonomy::MOOSAutonomy::init(), scrimmage::motion::DubinsAirplane3D::init(), scrimmage::motion::Unicycle3D::init(), scrimmage::motion::DubinsAirplane::init(), scrimmage::motion::DoubleIntegrator::init(), scrimmage::controller::SimpleAircraftControllerPID::init(), scrimmage::autonomy::ROSAutonomy::init(), scrimmage::motion::SimpleAircraft::init(), scrimmage::controller::Joystick::init(), scrimmage::motion::JSBSimModel::init(), scrimmage::motion::JSBSimControl::init(), scrimmage::motion::FixedWing6DOF::init(), scrimmage::autonomy::RLSimple::init_helper(), and REGISTER_PLUGIN().
declare() [2/2]
int scrimmage::VariableIO::declare (Type type, Direction dir)
Definition at line 131 of file VariableIO.cpp.
{
     std::string var("");
     auto it = type_map_.find(type);
     if (it == type_map_.end()) {
         std::cout << "Warning: Use of invalid VariableIO::Type" << std::endl;
     } else {
         var = it->second;
     }
     return declare(var, dir);
 }
References declare(), and type_map_.
input() [1/2]
double scrimmage::VariableIO::input (int i)
Definition at line 142 of file VariableIO.cpp.
{
     return (*input_)(i);
 }
References input_.
Referenced by scrimmage::motion::SimpleCar::model(), scrimmage::motion::SimpleAircraft::model(), REGISTER_PLUGIN(), scrimmage::motion::SingleIntegrator::step(), scrimmage::controller::JSBSimModelControllerDirect::step(), scrimmage::controller::SimpleCarControllerHeading::step(), scrimmage::controller::DoubleIntegratorControllerVelYaw::step(), scrimmage::controller::SingleIntegratorControllerWaypoint::step(), scrimmage::motion::Unicycle::step(), scrimmage::controller::SingleIntegratorControllerSimple::step(), scrimmage::controller::UnicycleControllerPoint::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::motion::DubinsAirplane::step(), scrimmage::motion::Unicycle3D::step(), scrimmage::motion::DubinsAirplane3D::step(), scrimmage::motion::DoubleIntegrator::step(), scrimmage::controller::SimpleAircraftControllerPID::step(), scrimmage::motion::JSBSimControl::step(), scrimmage::motion::JSBSimModel::step(), and scrimmage::motion::FixedWing6DOF::step().
output() [1/3]
void scrimmage::VariableIO::output (int i, double x)
Definition at line 146 of file VariableIO.cpp.
{
     // The plugin writing to the output doesn't know if the index it is writing
     // to is within the bounds of the input of the next plugin. Connect is
     // called before output to assign the shared ptr output to point to the
     // shared pointer input of the next plugin.
     if (i < output_->size()) (*output_)(i) = x;
 }
Referenced by scrimmage::autonomy::AvoidWalls::init(), scrimmage::autonomy::ROSAutonomy::init(), scrimmage::autonomy::RLSimple::init_helper(), REGISTER_PLUGIN(), scrimmage::controller::DoubleIntegratorControllerWaypoint::step(), scrimmage::controller::JSBSimModelControllerDirect::step(), scrimmage::controller::SimpleCarControllerHeading::step(), scrimmage::controller::DoubleIntegratorControllerVelYaw::step(), scrimmage::controller::SingleIntegratorControllerSimple::step(), scrimmage::controller::SingleIntegratorControllerWaypoint::step(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::controller::UnicycleControllerPoint::step(), scrimmage::controller::FixedWing6DOFControllerROS::step(), scrimmage::controller::SimpleAircraftControllerPID::step(), scrimmage::controller::Joystick::step(), scrimmage::autonomy::Predator::step_autonomy(), scrimmage::autonomy::AvoidWalls::step_autonomy(), scrimmage::autonomy::MOOSAutonomy::step_autonomy(), scrimmage::autonomy::ROSAutonomy::step_autonomy(), scrimmage::autonomy::RLSimple::step_helper(), and scrimmage::autonomy::Boids::velocity_controller().
output() [2/3]
double scrimmage::VariableIO::output (int i)
Definition at line 154 of file VariableIO.cpp.
{
     return i < output_->size() ? (*output_)(i) : NAN;
 }
References output_.
exists() [1/2]
bool scrimmage::VariableIO::exists (std::string var, Direction dir)
Definition at line 163 of file VariableIO.cpp.
{
     if (dir == VariableIO::Direction::In) {
         return (input_variable_index_.count(var) > 0);
     } else {
         return (output_variable_index_.count(var) > 0);
     }
 }
References In, input_variable_index_, and output_variable_index_.
Referenced by exists(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), and REGISTER_PLUGIN().
exists() [2/2]
bool scrimmage::VariableIO::exists (Type type, Direction dir)
Definition at line 171 of file VariableIO.cpp.
{
     auto it = type_map_.find(type);
     if (it == type_map_.end()) {
         return false;
     }
     return exists(it->second, dir);
 }
References exists(), and type_map_.
declared_input_variables()
std::set< std::string > scrimmage::VariableIO::declared_input_variables ()
Definition at line 179 of file VariableIO.cpp.
{
     return declared_input_variables_;
 }
References declared_input_variables_.
Referenced by scrimmage::verify_io_connection().
declared_output_variables()
std::set< std::string > scrimmage::VariableIO::declared_output_variables ()
Definition at line 183 of file VariableIO.cpp.
{
     return declared_output_variables_;
 }
References declared_output_variables_.
Referenced by scrimmage::verify_io_connection().
type_map()
const std::map<Type, std::string>& scrimmage::VariableIO::type_map () const inline
Definition at line 99 of file VariableIO.h.
 { return type_map_; }
References type_map_.
Referenced by scrimmage::controller::JSBSimModelControllerDirect::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), scrimmage::controller::SimpleAircraftControllerPID::init(), scrimmage::motion::JSBSimModel::init(), and REGISTER_PLUGIN().
input() [2/2]
const std::shared_ptr<Eigen::VectorXd>& scrimmage::VariableIO::input () inline
Definition at line 101 of file VariableIO.h.
 { return input_; }
References input_.
Referenced by set_input().
output() [3/3]
const std::shared_ptr<Eigen::VectorXd>& scrimmage::VariableIO::output () inline
Definition at line 102 of file VariableIO.h.
 { return output_; }
References output_.
Referenced by set_output().
set_input()
void scrimmage::VariableIO::set_input (const std::shared_ptr< Eigen::VectorXd > & input)
Definition at line 187 of file VariableIO.cpp.
{
     input_ = input;
 }
References input(), and input_.
set_output()
void scrimmage::VariableIO::set_output (const std::shared_ptr< Eigen::VectorXd > & output)
Definition at line 190 of file VariableIO.cpp.
{
     output_ = output;
 }
References output(), and output_.
Friends And Related Function Documentation
connect
void connect (VariableIO & output, VariableIO & input) friend
Connect two VariableIO objects where writing to the output of the first object will transfer the data to the input of the second object.
Definition at line 158 of file VariableIO.cpp.
{
     output.output_variable_index() = input.input_variable_index();
     output.output_ = input.input_;
 }
Member Data Documentation
next_input_variable_index_
int scrimmage::VariableIO::next_input_variable_index_ = 0 protected
Definition at line 112 of file VariableIO.h.
Referenced by add_input_variable().
input_variable_index_
std::map<std::string, int> scrimmage::VariableIO::input_variable_index_ protected
Definition at line 113 of file VariableIO.h.
Referenced by add_input_variable(), exists(), and input_variable_index().
output_variable_index_
std::map<std::string, int> scrimmage::VariableIO::output_variable_index_ protected
Definition at line 114 of file VariableIO.h.
Referenced by add_output_variable(), exists(), and output_variable_index().
input_
std::shared_ptr<Eigen::VectorXd> scrimmage::VariableIO::input_ protected
Definition at line 115 of file VariableIO.h.
Referenced by add_input_variable(), scrimmage::connect(), input(), and set_input().
output_
std::shared_ptr<Eigen::VectorXd> scrimmage::VariableIO::output_ protected
Definition at line 116 of file VariableIO.h.
Referenced by scrimmage::connect(), output(), and set_output().
declared_input_variables_
std::set<std::string> scrimmage::VariableIO::declared_input_variables_ protected
Definition at line 117 of file VariableIO.h.
Referenced by add_input_variable(), and declared_input_variables().
declared_output_variables_
std::set<std::string> scrimmage::VariableIO::declared_output_variables_ protected
Definition at line 118 of file VariableIO.h.
Referenced by add_output_variable(), and declared_output_variables().
type_map_
std::map< VariableIO::Type, std::string > scrimmage::VariableIO::type_map_ static protected
Initial value:
= {
    {VariableIO::Type::desired_altitude, "desired_altitude"},
    {VariableIO::Type::desired_speed, "desired_speed"},
    {VariableIO::Type::desired_heading, "desired_heading"},
    {VariableIO::Type::desired_roll, "desired_roll"},
    {VariableIO::Type::desired_pitch, "desired_pitch"},
    {VariableIO::Type::desired_turn_rate, "desired_turn_rate"},
    {VariableIO::Type::desired_pitch_rate, "desired_pitch_rate"},
    {VariableIO::Type::desired_roll_rate, "desired_roll_rate"},
    {VariableIO::Type::desired_glide_slope, "desired_glide_slope"},
    {VariableIO::Type::speed, "speed"},
    {VariableIO::Type::throttle, "throttle"},
    {VariableIO::Type::elevator, "elevator"},
    {VariableIO::Type::aileron, "aileron"},
    {VariableIO::Type::rudder, "rudder"},
    {VariableIO::Type::turn_rate, "turn_rate"},
    {VariableIO::Type::pitch_rate, "pitch_rate"},
    {VariableIO::Type::roll_rate, "roll_rate"},
    {VariableIO::Type::velocity_x, "velocity_x"},
    {VariableIO::Type::velocity_y, "velocity_y"},
    {VariableIO::Type::velocity_z, "velocity_z"},
    {VariableIO::Type::position_x, "position_x"},
    {VariableIO::Type::position_y, "position_y"},
    {VariableIO::Type::position_z, "position_z"},
    {VariableIO::Type::acceleration_x, "acceleration_x"},
    {VariableIO::Type::acceleration_y, "acceleration_y"},
    {VariableIO::Type::acceleration_z, "acceleration_z"}
}
Definition at line 119 of file VariableIO.h.
Referenced by declare(), exists(), and type_map().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/VariableIO.h
/root/scrimmage/scrimmage/src/common/VariableIO.cpp