SCRIMMAGE: scrimmage::controller::MotionBattery Class Reference
scrimmage::controller::MotionBattery Class Reference
#include <MotionBattery.h>
Classes
class VarLimit
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step (double t, double dt) override
Public Member Functions inherited from scrimmage::Controller
void set_state (StatePtr &state)
void set_desired_state (StatePtr &desired_state)
void close (double) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Member Functions
bool get_battery_charge (scrimmage::MessageBasePtr request, scrimmage::MessageBasePtr &response)
double calculate_charge_usage (const double &throttle, const double &dt)
Protected Attributes
Battery battery_
std::map< std::string, std::unique_ptr< VarLimit > > io_map_
bool publish_charge_ = false
PublisherPtr pub_charge_percentage_
Protected Attributes inherited from scrimmage::Controller
StatePtr state_
StatePtr desired_state_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file MotionBattery.h.
Member Function Documentation
init()
void scrimmage::controller::MotionBattery::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Controller.
Referenced by REGISTER_PLUGIN().
step()
bool scrimmage::controller::MotionBattery::step (double t, double dt) override virtual
Reimplemented from scrimmage::Controller.
Referenced by REGISTER_PLUGIN().
get_battery_charge()
bool scrimmage::controller::MotionBattery::get_battery_charge (scrimmage::MessageBasePtr request, scrimmage::MessageBasePtr & response) protected
Referenced by REGISTER_PLUGIN().
calculate_charge_usage()
double scrimmage::controller::MotionBattery::calculate_charge_usage (const double & throttle, const double & dt) protected
Referenced by REGISTER_PLUGIN().
Member Data Documentation
battery_
Battery scrimmage::controller::MotionBattery::battery_ protected
Definition at line 58 of file MotionBattery.h.
Referenced by REGISTER_PLUGIN().
io_map_
std::map<std::string, std::unique_ptr<VarLimit> > scrimmage::controller::MotionBattery::io_map_ protected
Definition at line 78 of file MotionBattery.h.
Referenced by REGISTER_PLUGIN().
publish_charge_
bool scrimmage::controller::MotionBattery::publish_charge_ = false protected
Definition at line 80 of file MotionBattery.h.
Referenced by REGISTER_PLUGIN().
pub_charge_percentage_
PublisherPtr scrimmage::controller::MotionBattery::pub_charge_percentage_ protected
Definition at line 81 of file MotionBattery.h.
Referenced by REGISTER_PLUGIN().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/controller/MotionBattery/MotionBattery.h