SCRIMMAGE: scrimmage::PID Class Reference
scrimmage::PID Class Reference
#include <PID.h>
Public Member Functions
PID ()
void set_parameters (const double &kp, const double &ki, const double &kd)
void set_setpoint (const double &setpoint)
void set_integral_band (const double &integral_band)
void set_is_angle (const bool &is_angle)
void set_output_limits (const double &min, const double &max, const double &enable)
void reset ()
const double & setpoint ()
const double & kp ()
const double & ki ()
const double & kd ()
const double & integral_band ()
const double & integral ()
const double & error ()
const double & previous_error ()
const double & derivative ()
bool init (const std::string &str, const bool &is_angle)
double step (const double &dt, const double &measurement)
Protected Attributes
double kp_
double ki_
double kd_
double prev_error_
double integral_
double setpoint_
double integral_band_
bool is_angle_
double derivative_
double error_
double output_min_
double output_max_
bool enable_output_limits_
Detailed Description
Definition at line 39 of file PID.h.
Constructor & Destructor Documentation
PID()
scrimmage::PID::PID ()
Definition at line 47 of file PID.cpp.
          : kp_(0), ki_(0), kd_(0), prev_error_(0), integral_(0),
              setpoint_(0), integral_band_(0), is_angle_(false),
              derivative_(0), error_(0), output_min_(0), output_max_(0),
              enable_output_limits_(false) {}
Member Function Documentation
set_parameters()
void scrimmage::PID::set_parameters (const double & kp, const double & ki, const double & kd)
Definition at line 83 of file PID.cpp.
{
     kp_ = kp;
     ki_ = ki;
     kd_ = kd;
 }
References kd(), kd_, ki(), ki_, kp(), and kp_.
Referenced by scrimmage::controller::SimpleQuadrotorControllerLQR::init(), scrimmage::controller::SimpleCarControllerHeading::init(), init(), REGISTER_PLUGIN(), scrimmage::controller::set_pid(), and scrimmage::set_pid_gains().
set_setpoint()
void scrimmage::PID::set_setpoint (const double & setpoint)
Definition at line 89 of file PID.cpp.
{
     setpoint_ = setpoint;
 }
References setpoint(), and setpoint_.
Referenced by REGISTER_PLUGIN(), scrimmage::controller::SimpleQuadrotorControllerLQR::step(), scrimmage::controller::RigidBody6DOFControllerPID::step(), scrimmage::controller::SimpleCarControllerHeading::step(), scrimmage::controller::DoubleIntegratorControllerVelYaw::step(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), and scrimmage::controller::SimpleAircraftControllerPID::step().
set_integral_band()
void scrimmage::PID::set_integral_band (const double & integral_band)
Definition at line 93 of file PID.cpp.
{
     integral_band_ = integral_band;
 }
References integral_band(), and integral_band_.
Referenced by scrimmage::controller::SimpleQuadrotorControllerLQR::init(), scrimmage::controller::SimpleCarControllerHeading::init(), init(), REGISTER_PLUGIN(), scrimmage::controller::set_pid(), and scrimmage::set_pid_gains().
set_is_angle()
void scrimmage::PID::set_is_angle (const bool & is_angle)
Definition at line 103 of file PID.cpp.
 { is_angle_ = is_angle; }
References is_angle_.
Referenced by scrimmage::controller::SimpleCarControllerHeading::init(), init(), REGISTER_PLUGIN(), scrimmage::controller::set_pid(), and scrimmage::set_pid_gains().
set_output_limits()
void scrimmage::PID::set_output_limits (const double & min, const double & max, const double & enable)
Definition at line 76 of file PID.cpp.
{
     output_min_ = min;
     output_max_ = max;
     enable_output_limits_ = enable;
 }
References enable_output_limits_, output_max_, and output_min_.
reset()
void scrimmage::PID::reset ()
Definition at line 97 of file PID.cpp.
                 {
     integral_ = 0.0;
     prev_error_ = 0.0;
     derivative_ = 0.0;
 }
References derivative_, integral_, and prev_error_.
setpoint()
const double & scrimmage::PID::setpoint ()
Definition at line 105 of file PID.cpp.
 { return setpoint_; }
References setpoint_.
Referenced by set_setpoint().
kp()
const double & scrimmage::PID::kp ()
Definition at line 106 of file PID.cpp.
 { return kp_; }
References kp_.
Referenced by set_parameters().
ki()
const double & scrimmage::PID::ki ()
Definition at line 107 of file PID.cpp.
 { return ki_; }
References ki_.
Referenced by set_parameters().
kd()
const double & scrimmage::PID::kd ()
Definition at line 108 of file PID.cpp.
 { return kd_; }
References kd_.
Referenced by set_parameters().
integral_band()
const double & scrimmage::PID::integral_band ()
Definition at line 109 of file PID.cpp.
 { return integral_band_; }
References integral_band_.
Referenced by set_integral_band().
integral()
const double & scrimmage::PID::integral ()
Definition at line 110 of file PID.cpp.
 { return integral_; }
References integral_.
error()
const double & scrimmage::PID::error ()
Definition at line 111 of file PID.cpp.
 { return error_; }
References error_.
previous_error()
const double & scrimmage::PID::previous_error ()
Definition at line 112 of file PID.cpp.
 { return prev_error_; }
References prev_error_.
derivative()
const double & scrimmage::PID::derivative ()
Definition at line 113 of file PID.cpp.
 { return derivative_; }
References derivative_.
init()
bool scrimmage::PID::init (const std::string & str, const bool & is_angle)
Definition at line 52 of file PID.cpp.
{
     std::vector<std::string> str_vals;
     boost::split(str_vals, str, boost::is_any_of(","));
     if (str_vals.size() != 4) {
         return false;
     } else {
         double p = std::stod(str_vals[0]);
         double i = std::stod(str_vals[1]);
         double d = std::stod(str_vals[2]);
         set_parameters(p, i, d);
         set_is_angle(is_angle);
         if (is_angle) {
             double i_lim = Angles::deg2rad(std::stod(str_vals[3]));
             set_integral_band(i_lim);
         } else {
             double i_lim = std::stod(str_vals[3]);
             set_integral_band(i_lim);
         }
     }
     return true;
 }
References scrimmage::Angles::deg2rad(), set_integral_band(), set_is_angle(), set_parameters(), and scrimmage::split().
Referenced by scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), scrimmage::controller::SimpleAircraftControllerPID::init(), and REGISTER_PLUGIN().
step()
double scrimmage::PID::step (const double & dt, const double & measurement)
Definition at line 115 of file PID.cpp.
{
     error_ = setpoint_ - measurement;
     if (is_angle_) {
         error_ = Angles::angle_pi(error_);
     }
     if (std::abs(error_) > integral_band_) {
         integral_ = 0;
     } else {
         integral_ += error_ * dt;
     }
     derivative_ = (error_ - prev_error_) / std::max(1.0e-9, dt);
     double u = kp_*error_ + ki_*integral_ + kd_*derivative_;
     prev_error_ = error_;
     return enable_output_limits_ ? clamp(u, output_min_, output_max_) : u;
 }
References scrimmage::Angles::angle_pi(), derivative_, enable_output_limits_, error_, integral_, integral_band_, is_angle_, kd_, ki_, kp_, output_max_, output_min_, prev_error_, and setpoint_.
Referenced by REGISTER_PLUGIN(), scrimmage::controller::SimpleQuadrotorControllerLQR::step(), scrimmage::controller::SimpleCarControllerHeading::step(), scrimmage::controller::RigidBody6DOFControllerPID::step(), scrimmage::controller::DoubleIntegratorControllerVelYaw::step(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), and scrimmage::controller::SimpleAircraftControllerPID::step().
Member Data Documentation
kp_
double scrimmage::PID::kp_ protected
Definition at line 64 of file PID.h.
Referenced by kp(), set_parameters(), and step().
ki_
double scrimmage::PID::ki_ protected
Definition at line 65 of file PID.h.
Referenced by ki(), set_parameters(), and step().
kd_
double scrimmage::PID::kd_ protected
Definition at line 66 of file PID.h.
Referenced by kd(), set_parameters(), and step().
prev_error_
double scrimmage::PID::prev_error_ protected
Definition at line 68 of file PID.h.
Referenced by previous_error(), reset(), and step().
integral_
double scrimmage::PID::integral_ protected
Definition at line 69 of file PID.h.
Referenced by integral(), reset(), and step().
setpoint_
double scrimmage::PID::setpoint_ protected
Definition at line 71 of file PID.h.
Referenced by set_setpoint(), setpoint(), and step().
integral_band_
double scrimmage::PID::integral_band_ protected
Definition at line 73 of file PID.h.
Referenced by integral_band(), set_integral_band(), and step().
is_angle_
bool scrimmage::PID::is_angle_ protected
Definition at line 74 of file PID.h.
Referenced by set_is_angle(), and step().
derivative_
double scrimmage::PID::derivative_ protected
Definition at line 75 of file PID.h.
Referenced by derivative(), reset(), and step().
error_
double scrimmage::PID::error_ protected
Definition at line 76 of file PID.h.
Referenced by error(), and step().
output_min_
double scrimmage::PID::output_min_ protected
Definition at line 78 of file PID.h.
Referenced by set_output_limits(), and step().
output_max_
double scrimmage::PID::output_max_ protected
Definition at line 79 of file PID.h.
Referenced by set_output_limits(), and step().
enable_output_limits_
bool scrimmage::PID::enable_output_limits_ protected
Definition at line 80 of file PID.h.
Referenced by set_output_limits(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/PID.h
/root/scrimmage/scrimmage/src/common/PID.cpp