SCRIMMAGE: scrimmage::sensor::NoisyState Class Reference
scrimmage::sensor::NoisyState Class Reference
#include <NoisyState.h>
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step () override
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
std::vector< std::shared_ptr< std::normal_distribution< double > > > pos_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > vel_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > orient_noise_
PublisherPtr pub_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 45 of file NoisyState.h.
Member Function Documentation
void scrimmage::sensor::NoisyState::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 53 of file NoisyState.cpp.
References scrimmage::get_vec().
{
     auto add_noise = [&](std::string prefix, auto &noise_vec) {
         for (int i = 0; i < 3; i++) {
             std::string tag_name = prefix + "_" + std::to_string(i);
             std::vector<double> vec;
             double mean, stdev;
             std::tie(mean, stdev) = get_vec(tag_name, params, " ", vec, 2) ?
                 std::make_pair(vec[0], vec[1]) : std::make_pair(0.0, 1.0);
             noise_vec.push_back(parent_->random()->make_rng_normal(mean, stdev));
         }
     };
     add_noise("pos_noise", pos_noise_);
     add_noise("vel_noise", vel_noise_);
     add_noise("orient_noise", orient_noise_);
     pub_ = advertise("LocalNetwork", "StateWithCovariance");
     // Move the enity's state pointer to use the state instance provided by
     // this plugin.
     parent_->state() = std::make_shared<State>();
     *(parent_->state()) = *(parent_->state_truth());
     return;
 }
bool scrimmage::sensor::NoisyState::step () override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 79 of file NoisyState.cpp.
References scrimmage::State::pos(), scrimmage::State::quat(), and scrimmage::State::vel().
                       {
     auto gener = parent_->random()->gener();
     // Make a copy of the current ground truth state
     StateWithCovariance ns(*(parent_->state_truth()));
     auto msg = std::make_shared<Message<StateWithCovariance>>();
     for (int i = 0; i < 3; i++) {
         msg->data.pos()(i) = ns.pos()(i) + (*pos_noise_[i])(*gener);
         msg->data.vel()(i) = ns.vel()(i) + (*vel_noise_[i])(*gener);
     }
     // TODO: Test this math.
     // add noise in roll, pitch, yaw order
     msg->data.quat() = ns.quat()
         * Quaternion(Eigen::Vector3d::UnitX(), (*orient_noise_[0])(*gener))
         * Quaternion(Eigen::Vector3d::UnitY(), (*orient_noise_[1])(*gener))
         * Quaternion(Eigen::Vector3d::UnitZ(), (*orient_noise_[2])(*gener));
     pub_->publish(msg);
     // Update the entity's state.
     *(parent_->state()) = static_cast<sc::State>(msg->data);
     return true;
 }
Member Data Documentation
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyState::pos_noise_ protected
Definition at line 51 of file NoisyState.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyState::vel_noise_ protected
Definition at line 52 of file NoisyState.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyState::orient_noise_ protected
Definition at line 53 of file NoisyState.h.
PublisherPtr scrimmage::sensor::NoisyState::pub_ protected
Definition at line 55 of file NoisyState.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/NoisyState/NoisyState.h
/root/scrimmage/scrimmage/src/plugins/sensor/NoisyState/NoisyState.cpp