SCRIMMAGE: scrimmage::CSV Class Reference
scrimmage::CSV Class Reference
#include <CSV.h>
Public Types
typedef std::list< std::string > Headers
typedef std::list< std::pair< std::string, double > > Pairs
Public Member Functions
~CSV ()
void set_column_headers (const Headers &headers, bool write=true)
void set_column_headers (const std::string &headers, bool write=true)
bool append (const Pairs &pairs, bool write=true, bool keep_in_memory=false)
bool open_output (const std::string &filename, std::ios_base::openmode mode=(std::ios_base::out|std::ios_base::trunc))
bool output_is_open ()
bool close_output ()
bool to_csv (const std::string &filename)
bool read_csv (const std::string &filename, const bool &contains_header=true)
bool read_csv_from_string (const std::string &str, const bool &contains_header=true)
void set_no_value_string (const std::string &str)
std::string to_string () const
size_t rows ()
double at (int row, const std::string &header)
bool equals (const CSV &other)
Protected Member Functions
std::list< std::string > get_csv_line_elements (const std::string &str)
void write_headers ()
void write_row (const int &row)
Protected Attributes
std::map< std::string, int > column_headers_
std::map< int, std::map< int, double > > table_
int next_row_ = 0
std::ofstream file_out_
std::string no_value_str_ = "NaN"
Private Member Functions
std::string headers_to_string () const
std::string rows_to_string () const
std::string row_to_string (const int &i) const
Friends
std::ostream & operator<< (std::ostream &os, const CSV &csv)
Detailed Description
Definition at line 45 of file CSV.h.
Member Typedef Documentation
typedef std::list<std::string> scrimmage::CSV::Headers
Definition at line 47 of file CSV.h.
typedef std::list<std::pair<std::string, double> > scrimmage::CSV::Pairs
Definition at line 48 of file CSV.h.
Constructor & Destructor Documentation
scrimmage::CSV::~CSV ()
Definition at line 48 of file CSV.cpp.
References close_output().
           {
     this->close_output();
 }
Member Function Documentation
void scrimmage::CSV::set_column_headers (const Headers & headers, bool write = true)
Definition at line 52 of file CSV.cpp.
References column_headers_, file_out_, and write_headers().
Referenced by scrimmage::sensor::AirSimSensor::init(), scrimmage::Network::network_init(), and set_column_headers().
{
     column_headers_.clear();
     int i = 0;
     for (const std::string &header : headers) {
         column_headers_[header] = i;
         i++;
     }
     if (write) {
         if (!file_out_.is_open()) {
             cout << "File isn't open. Can't write CSV headers." << endl;
         } else {
             this->write_headers();
         }
     }
 }
void scrimmage::CSV::set_column_headers (const std::string & headers, bool write = true)
Definition at line 70 of file CSV.cpp.
References get_csv_line_elements(), and set_column_headers().
{
     std::list<std::string> headers_vec = get_csv_line_elements(headers);
     set_column_headers(headers_vec, write);
 }
bool scrimmage::CSV::append (const Pairs & pairs, bool write = true, bool keep_in_memory = false)
Definition at line 75 of file CSV.cpp.
References column_headers_, file_out_, next_row_, table_, and write_row().
Referenced by scrimmage::sensor::AirSimSensor::save_data(), and scrimmage::Network::step().
{
     for (std::pair<std::string, double> pair : pairs) {
         auto it = column_headers_.find(pair.first);
         if (it == column_headers_.end()) {
             cout << "Warning: column header doesn't exist: "
                  << pair.first << endl;
         }
         table_[next_row_][it->second] = pair.second;
     }
     if (write) {
         if (!file_out_.is_open()) {
             cout << "File isn't open. Can't write CSV" << endl;
             return false;
         }
         this->write_row(next_row_);
     }
     if (keep_in_memory) next_row_++;
     return true;
 }
bool scrimmage::CSV::open_output (const std::string & filename, std::ios_base::openmode mode = (std::ios_base::out | std::ios_base::trunc))
Definition at line 99 of file CSV.cpp.
References file_out_.
Referenced by scrimmage::sensor::AirSimSensor::init(), scrimmage::Network::network_init(), and to_csv().
{
     file_out_.open(filename, mode);
     return file_out_.is_open();
 }
bool scrimmage::CSV::output_is_open ()
Definition at line 104 of file CSV.cpp.
References file_out_.
Referenced by scrimmage::sensor::AirSimSensor::init(), and scrimmage::sensor::AirSimSensor::save_data().
{
     return file_out_.is_open();
 }
bool scrimmage::CSV::close_output ()
Definition at line 108 of file CSV.cpp.
References file_out_.
Referenced by scrimmage::sensor::AirSimSensor::close(), to_csv(), and ~CSV().
{
     if (file_out_.is_open()) {
         file_out_.close();
     }
     return !file_out_.is_open();
 }
bool scrimmage::CSV::to_csv (const std::string & filename)
Definition at line 186 of file CSV.cpp.
References close_output(), open_output(), table_, write_headers(), and write_row().
{
     if (not this->open_output(filename)) {
         cout << "CSV::to_csv: Failed to open file: " << filename << endl;
         return false;
     }
     // Write the headers out
     this->write_headers();
     // Write all the rows out
     for (unsigned int i = 0; i < table_.size(); i++) {
         this->write_row(i);
     }
     if (not this->close_output()) {
         cout << "Failed to close CSV file." << endl;
     }
     return true;
 }
bool scrimmage::CSV::read_csv (const std::string & filename, const bool & contains_header = true)
Definition at line 255 of file CSV.cpp.
References read_csv_from_string().
{
     std::ifstream file(filename);
     if (not file.is_open()) {
         cout << "Unable to open CSV file:" << filename << endl;
         return false;
     }
     // Read in the CSV file as a string and parse it
     std::string str((std::istreambuf_iterator<char>(file)),
                     std::istreambuf_iterator<char>());
     return read_csv_from_string(str, contains_header);
 }
bool scrimmage::CSV::read_csv_from_string (const std::string & str, const bool & contains_header = true)
Definition at line 205 of file CSV.cpp.
References column_headers_, get_csv_line_elements(), scrimmage::remove_whitespace(), scrimmage::split(), and table_.
Referenced by read_csv().
{
     table_.clear();
     column_headers_.clear();
     std::vector<std::string> line_tokens;
     boost::split(line_tokens, csv_str, boost::is_any_of("\n"));
     int row_num = 0;
     for (unsigned int line_num = 0; line_num < line_tokens.size(); line_num++) {
         // Strip "whitespace" characters.
         std::string line = remove_whitespace(line_tokens[line_num]);
         if (line == "") continue; // Ignore lines that are empty
         if (line_num == 0 && contains_header) {
             std::list<std::string> headers = get_csv_line_elements(line);
             int i = 0;
             for (auto &str : headers) {
                 column_headers_[str] = i;
                 i++;
             }
         } else {
             std::vector<std::string> tokens;
             boost::split(tokens, line, boost::is_any_of(","));
             for (unsigned int i = 0; i < tokens.size(); i++) {
                 table_[row_num][i] = std::stod(tokens[i]);
             }
             // If this is the first line and the file doesn't contain a header,
             // populate the column headers with indices based on the number of
             // comma separated values
             if (row_num == 0 && not contains_header) {
                 for (unsigned int i = 0; i < tokens.size(); i++) {
                     column_headers_[std::to_string(i)] = i;
                 }
             }
             // Print a warning if the number of comma separated values doesn't
             // match the number of columns
             if (column_headers_.size() != tokens.size()) {
                 cout << "Warning the number of values (" << tokens.size()
                      << ") on line number " << row_num
                      << " doesn't match the number of column headers: "
                      << column_headers_.size() << endl;
             }
             row_num++;
         }
     }
     return true;
 }
void scrimmage::CSV::set_no_value_string (const std::string & str)
Definition at line 268 of file CSV.cpp.
References no_value_str_.
 { no_value_str_ = str; }
std::string scrimmage::CSV::to_string () const
Definition at line 115 of file CSV.cpp.
References headers_to_string(), and rows_to_string().
Referenced by scrimmage::operator<<().
{
     return headers_to_string() + "\n" + rows_to_string();
 }
size_t scrimmage::CSV::rows ()
Definition at line 270 of file CSV.cpp.
References table_.
 { return table_.size(); }
double scrimmage::CSV::at (int row, const std::string & header)
Definition at line 272 of file CSV.cpp.
References column_headers_, and table_.
{
     const int column = column_headers_.at(header);
     return table_.at(row).at(column);
 }
bool scrimmage::CSV::equals (const CSV & other)
Definition at line 304 of file CSV.cpp.
References column_headers_, and table_.
{
     if (not std::equal(column_headers_.begin(), column_headers_.end(),
                        other.column_headers_.begin(),
                        other.column_headers_.end())) {
         return false;
     }
     if (not std::equal(table_.begin(), table_.end(),
                        other.table_.begin(),
                        other.table_.end())) {
         return false;
     }
     return true;
 }
std::list< std::string > scrimmage::CSV::get_csv_line_elements (const std::string & str) protected
Definition at line 277 of file CSV.cpp.
References scrimmage::remove_if(), and scrimmage::split().
Referenced by read_csv_from_string(), and set_column_headers().
{
     std::list<std::string> elems;
     std::vector<std::string> tokens;
     boost::split(tokens, str, boost::is_any_of(","));
     for (unsigned int i = 0; i < tokens.size(); i++) {
         // Remove whitespace
         tokens[i].erase(
             std::remove_if(tokens[i].begin(),
                            tokens[i].end(),
                            [](unsigned char x){return std::isspace(x);}),
             tokens[i].end());
         if (tokens[i] != "") {
             elems.push_back(tokens[i]);
         }
     }
     return elems;
 }
void scrimmage::CSV::write_headers () protected
Definition at line 296 of file CSV.cpp.
References file_out_, and headers_to_string().
Referenced by set_column_headers(), and to_csv().
{
     file_out_ << headers_to_string() << endl;
 }
void scrimmage::CSV::write_row (const int & row) protected
Definition at line 300 of file CSV.cpp.
References file_out_, and row_to_string().
Referenced by append(), and to_csv().
{
     file_out_ << row_to_string(row) << endl;
 }
std::string scrimmage::CSV::headers_to_string () const private
Definition at line 124 of file CSV.cpp.
References column_headers_.
Referenced by to_string(), and write_headers().
{
     std::string result = "";
     // Get an ordered vector of headers
     std::vector<std::string> headers(column_headers_.size());
     for (auto &kv : column_headers_) {
         headers[kv.second] = kv.first;
     }
     unsigned int i = 0;
     for (std::string header : headers) {
         result += header;
         if (i+1 < headers.size()) {
             result += ",";
         }
         i++;
     }
     return result;
 }
std::string scrimmage::CSV::rows_to_string () const private
Definition at line 145 of file CSV.cpp.
References row_to_string(), and table_.
Referenced by to_string().
{
     std::string result = "";
     // Write all the rows out
     for (unsigned int i = 0; i < table_.size(); i++) {
         result += this->row_to_string(i);
         if (i < table_.size() - 1) {
             result += "\n";
         }
     }
     return result;
 }
std::string scrimmage::CSV::row_to_string (const int & i) const private
Definition at line 157 of file CSV.cpp.
References column_headers_, no_value_str_, and table_.
Referenced by rows_to_string(), and write_row().
{
     std::string result = "";
     // Initialize a vector with no value string. Iterate over
     // column_headers, use column index to fill in columne for values.
     std::vector<std::string> values(column_headers_.size(), no_value_str_);
     auto it_row = table_.find(row);
     for (auto &kv : it_row->second) {
         if (static_cast<int64_t>(kv.second) == kv.second) {
             values[kv.first] = std::to_string(static_cast<int64_t>(kv.second));
         } else {
             values[kv.first] = std::to_string(kv.second);
         }
     }
     // Append the rows to the resultant string
     unsigned int i = 0;
     for (std::string str : values) {
         result += str;
         if (i+1 < values.size()) {
             result += ",";
         }
         i++;
     }
     return result;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CSV & csv) friend
Definition at line 119 of file CSV.cpp.
{
     os << csv.to_string();
     return os;
 }
Member Data Documentation
std::map<std::string, int> scrimmage::CSV::column_headers_ protected
Definition at line 93 of file CSV.h.
Referenced by append(), at(), equals(), headers_to_string(), read_csv_from_string(), row_to_string(), and set_column_headers().
std::map<int, std::map<int, double> > scrimmage::CSV::table_ protected
Definition at line 98 of file CSV.h.
Referenced by append(), at(), equals(), read_csv_from_string(), row_to_string(), rows(), rows_to_string(), and to_csv().
int scrimmage::CSV::next_row_ = 0 protected
Definition at line 99 of file CSV.h.
Referenced by append().
std::ofstream scrimmage::CSV::file_out_ protected
Definition at line 101 of file CSV.h.
Referenced by append(), close_output(), open_output(), output_is_open(), set_column_headers(), write_headers(), and write_row().
std::string scrimmage::CSV::no_value_str_ = "NaN" protected
Definition at line 102 of file CSV.h.
Referenced by row_to_string(), and set_no_value_string().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/CSV.h
/root/scrimmage/scrimmage/src/common/CSV.cpp