SCRIMMAGE: scrimmage::autonomy::PyAutonomy Class Reference
scrimmage::autonomy::PyAutonomy Class Reference
#include <PyAutonomy.h>
Public Member Functions
PyAutonomy ()
void init (std::map< std::string, std::string > &params) override
bool step_autonomy (double t, double dt) override
std::string type () override
void set_contacts (scrimmage::ContactMapPtr &contacts) override
void set_contacts_from_plugin (scrimmage::AutonomyPtr &ptr) override
void set_state (scrimmage::StatePtr &state) override
Public Member Functions inherited from scrimmage::Autonomy
Autonomy ()
virtual bool posthumous (double t)
virtual void init ()
bool ready () override
void close (double t) override
bool need_reset ()
StatePtr & desired_state ()
void set_desired_state (StatePtr desired_state)
ContactMapPtr & get_contacts ()
ContactMap & get_contacts_raw ()
virtual void set_projection (std::shared_ptr< GeographicLib::LocalCartesian > &proj)
scrimmage::RTreePtr & rtree ()
void set_rtree (scrimmage::RTreePtr &rtree)
StatePtr & state ()
std::string & logging_msg ()
bool get_is_controlling ()
void set_is_controlling (bool is_controlling)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
void cache_python_vars ()
pybind11::object get_py_obj (std::map< std::string, std::string > &params)
void init_py_obj (std::map< std::string, std::string > &params)
void print_py_traceback (pybind11::error_already_set &e)
pybind11::object state2py (scrimmage::StatePtr &state)
pybind11::object contact2py (scrimmage::Contact contact)
Static Protected Member Functions
static std::shared_ptr< scrimmage_proto::Shape > py2shape (const pybind11::handle &py_handle)
Protected Attributes
bool step_autonomy_called_ = false
pybind11::object py_obj_
pybind11::dict py_contacts_
pybind11::object py_state_class_
pybind11::object py_quat_class_
pybind11::object py_contact_class_
pybind11::object py_msg_class_
pybind11::object py_state_
pybind11::object py_id_class_
bool serialize_msgs_ = false
std::map< scrimmage::Contact::Type, pybind11::object > py_contact_types_
Protected Attributes inherited from scrimmage::Autonomy
std::shared_ptr< GeographicLib::LocalCartesian > proj_
StatePtr state_
StatePtr desired_state_
ContactMapPtr contacts_
scrimmage::RTreePtr rtree_
bool need_reset_
std::string logging_msg_
bool is_controlling_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 44 of file PyAutonomy.h.
Constructor & Destructor Documentation
scrimmage::autonomy::PyAutonomy::PyAutonomy ()
Definition at line 67 of file PyAutonomy.cpp.
{
     need_reset_ = true;
 }
Member Function Documentation
void scrimmage::autonomy::PyAutonomy::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 71 of file PyAutonomy.cpp.
{
     py_obj_ = get_py_obj(params);
     py_obj_.attr("id") = py::cast(parent_->id());
     init_py_obj(params);
 }
bool scrimmage::autonomy::PyAutonomy::step_autonomy (double t, double dt) override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 232 of file PyAutonomy.cpp.
References scrimmage::State::cast().
{
     cache_python_vars();
     py_state_ = state2py(state_);
     py_obj_.attr("contacts") = py_contacts_;
     py_obj_.attr("state") = py_state_;
     // sub_msgs_to_py_subs();
     py::object step_autonomy = py_obj_.attr("step_autonomy");
     bool out = step_autonomy(py::float_(t), py::float_(dt)).cast<bool>();
     // sync_topics();
     // py_pub_msgs_to_pubs();
     sc::State state = py_obj_.attr("desired_state").cast<sc::State>();
     *desired_state_ = state;
     py::list py_shapes = py_obj_.attr("shapes").cast<py::list>();
     std::list< std::shared_ptr<scrimmage_proto::Shape> > cpp_shapes;
     std::transform(py_shapes.begin(), py_shapes.end(), std::back_inserter(cpp_shapes), py2shape);
     // shapes_ = cpp_shapes; // SHAPES TODO
     step_autonomy_called_ = true;
     return out;
 }
std::string scrimmage::autonomy::PyAutonomy::type () inline override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 50 of file PyAutonomy.h.
 {return std::string("PyAutonomy");}
void scrimmage::autonomy::PyAutonomy::set_contacts (scrimmage::ContactMapPtr & contacts) inline override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 52 of file PyAutonomy.h.
References contact2py(), scrimmage::Autonomy::contacts_, and py_contacts_.
{
         contacts_ = contacts;
         py_contacts_.clear();
         for (auto &kv : *contacts) {
             py_contacts_[pybind11::int_(kv.second.id().id())] =
                 contact2py(kv.second);
         }
     }
void scrimmage::autonomy::PyAutonomy::set_contacts_from_plugin (scrimmage::AutonomyPtr & ptr) inline override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 61 of file PyAutonomy.h.
References scrimmage::Autonomy::contacts_, and py_contacts_.
{
         std::shared_ptr<PyAutonomy> py_ptr =
             std::static_pointer_cast<PyAutonomy>(ptr);
         contacts_ = py_ptr->contacts_;
         py_contacts_ = py_ptr->py_contacts_;
     }
void scrimmage::autonomy::PyAutonomy::set_state (scrimmage::StatePtr & state) inline override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 68 of file PyAutonomy.h.
References cache_python_vars(), get_py_obj(), init_py_obj(), print_py_traceback(), scrimmage::Autonomy::state(), and scrimmage::Autonomy::state_.
{
         state_ = state;
     }
void scrimmage::autonomy::PyAutonomy::cache_python_vars () protected
Definition at line 99 of file PyAutonomy.cpp.
Referenced by set_state().
{
     if (py_state_class_.ptr() == nullptr) {
         py::module py_scrimmage = py::module::import("scrimmage.bindings");
         py_state_class_ = py_scrimmage.attr("State");
         py_quat_class_ = py_scrimmage.attr("Quaternion");
         py_contact_class_ = py_scrimmage.attr("Contact");
         py_msg_class_ = py_scrimmage.attr("Message");
         py_contact_types_[sc::Contact::Type::AIRCRAFT] = py_contact_class_.attr("AIRCRAFT");
         py_contact_types_[sc::Contact::Type::QUADROTOR] = py_contact_class_.attr("QUADROTOR");
         py_contact_types_[sc::Contact::Type::SPHERE] = py_contact_class_.attr("SPHERE");
         py_contact_types_[sc::Contact::Type::MESH] = py_contact_class_.attr("MESH");
         py_contact_types_[sc::Contact::Type::UNKNOWN] = py_contact_class_.attr("UNKNOWN");
         py::module py_numpy = py::module::import("numpy");
         py_id_class_ = py_scrimmage.attr("ID");
     }
 }
py::object scrimmage::autonomy::PyAutonomy::get_py_obj (std::map< std::string, std::string > & params) protected
Definition at line 77 of file PyAutonomy.cpp.
Referenced by set_state().
{
     py::module module = py::module::import(params["module"].c_str());
     py::object py_obj_class = module.attr(params["class"].c_str());
     py_obj_ = py_obj_class();
     return py_obj_;
 }
void scrimmage::autonomy::PyAutonomy::init_py_obj (std::map< std::string, std::string > & params) protected
Definition at line 84 of file PyAutonomy.cpp.
Referenced by set_state().
{
     py::dict py_params;
     for (auto &kv : params) {
         if (kv.first != "module" && kv.first != "class" && kv.first != "library") {
             py_params[kv.first.c_str()] = py::str(kv.second);
         }
     }
     // py_obj_.attr("subs") = py::dict();
     // py_obj_.attr("pubs") = py::dict();
     py_obj_.attr("shapes") = py::list();
     py::object init = py_obj_.attr("init");
     init(py_params);
 }
void scrimmage::autonomy::PyAutonomy::print_py_traceback (pybind11::error_already_set & e) protected
Referenced by set_state().
py::object scrimmage::autonomy::PyAutonomy::state2py (scrimmage::StatePtr & state) protected
Definition at line 119 of file PyAutonomy.cpp.
{
     cache_python_vars();
     sc::Quaternion quat = state->quat();
     Eigen::Vector3d pos = state->pos();
     Eigen::Vector3d vel = state->vel();
     Eigen::Vector3d ang_vel = state->ang_vel();
     py::object py_quat = py_quat_class_(quat.w(), quat.x(), quat.y(), quat.z());
     py::object py_pos = py::cast(pos);
     py::object py_vel = py::cast(vel);
     py::object py_ang_vel = py::cast(ang_vel);
     py::object py_state = py_state_class_(py_pos, py_vel, py_ang_vel, py_quat);
     return py_state;
 }
py::object scrimmage::autonomy::PyAutonomy::contact2py (scrimmage::Contact contact) protected
Definition at line 136 of file PyAutonomy.cpp.
References scrimmage::Contact::id(), scrimmage::Contact::state(), and scrimmage::Contact::type().
Referenced by set_contacts().
{
     cache_python_vars();
     py::object py_contact = py_contact_class_();
     scrimmage::ID id = contact.id();
     py_contact.attr("state") = state2py(contact.state());
     py_contact.attr("id") = py_id_class_(id.id(), id.sub_swarm_id(), id.team_id());
     py_contact.attr("type") = py_contact_types_[contact.type()];
     return py_contact;
 }
std::shared_ptr< scrimmage_proto::Shape > scrimmage::autonomy::PyAutonomy::py2shape (const pybind11::handle & py_handle) static protected
Definition at line 148 of file PyAutonomy.cpp.
{
     // Convert python shape to c++ shape.
     py::object shape_obj = py_handle.cast<py::object>();
     py::function serialize_func = shape_obj.attr("SerializeToString").cast<py::function>();
     std::shared_ptr<scrimmage_proto::Shape> cpp_shape(new scrimmage_proto::Shape());
     cpp_shape->ParseFromString(serialize_func().cast<std::string>());
     return cpp_shape;
 }
Member Data Documentation
bool scrimmage::autonomy::PyAutonomy::step_autonomy_called_ = false protected
Definition at line 83 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_obj_ protected
Definition at line 89 of file PyAutonomy.h.
pybind11::dict scrimmage::autonomy::PyAutonomy::py_contacts_ protected
Definition at line 90 of file PyAutonomy.h.
Referenced by set_contacts(), and set_contacts_from_plugin().
pybind11::object scrimmage::autonomy::PyAutonomy::py_state_class_ protected
Definition at line 93 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_quat_class_ protected
Definition at line 94 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_contact_class_ protected
Definition at line 95 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_msg_class_ protected
Definition at line 96 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_state_ protected
Definition at line 97 of file PyAutonomy.h.
pybind11::object scrimmage::autonomy::PyAutonomy::py_id_class_ protected
Definition at line 98 of file PyAutonomy.h.
bool scrimmage::autonomy::PyAutonomy::serialize_msgs_ = false protected
Definition at line 100 of file PyAutonomy.h.
std::map<scrimmage::Contact::Type, pybind11::object> scrimmage::autonomy::PyAutonomy::py_contact_types_ protected
Definition at line 102 of file PyAutonomy.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/PyAutonomy/PyAutonomy.h
/root/scrimmage/scrimmage/src/plugins/autonomy/PyAutonomy/PyAutonomy.cpp