SCRIMMAGE: scrimmage::ParameterServer Class Reference
scrimmage::ParameterServer Class Reference
#include <ParameterServer.h>
Public Member Functions
void unregister_params (PluginPtr owner)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback, PluginPtr owner)
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name, PluginPtr owner)
Protected Member Functions
bool remove_if_owner (std::set< ParameterBasePtr > &param_set, PluginPtr owner)
boost::optional< std::set< ParameterBasePtr > & > find_name_type (const std::string &name, const std::string &type)
Protected Attributes
std::unordered_map< std::string, std::unordered_map< std::string, std::set< ParameterBasePtr > > > params_
Detailed Description
Definition at line 53 of file ParameterServer.h.
Member Function Documentation
unregister_params()
void scrimmage::ParameterServer::unregister_params (PluginPtr owner)
Definition at line 39 of file ParameterServer.cpp.
{
     // For all parameters, remove all parameters owned by this plugin
     for (auto &kv1 : params_) {
         for (auto &kv2 : kv1.second) {
             remove_if_owner(kv2.second, owner);
         }
     }
 }
References params_, and remove_if_owner().
register_param()
template<class T > bool scrimmage::ParameterServer::register_param (const std::string & name, T & variable, std::function< void(const T &value)> callback, PluginPtr owner) inline
Definition at line 58 of file ParameterServer.h.
{
         auto it = params_[name][typeid(T).name()].emplace(
             std::make_shared<Parameter<T>>(variable, callback, owner));
         return it.second; // return false if the param already exists
     }
References params_.
set_param()
template<class T > bool scrimmage::ParameterServer::set_param (const std::string & name, const T & value) inline
Definition at line 67 of file ParameterServer.h.
{
         auto param_set = find_name_type(name, typeid(T).name());
         if (param_set) {
             for (ParameterBasePtr param : *param_set) {
                 auto param_cast = std::dynamic_pointer_cast<Parameter<T>>(param);
                 param_cast->set_value(value);
             }
             return true;
         }
         return false;
     }
References find_name_type().
unregister_param()
template<class T > bool scrimmage::ParameterServer::unregister_param (const std::string & name, PluginPtr owner) inline
Definition at line 80 of file ParameterServer.h.
{
         auto param_set = find_name_type(name, typeid(T).name());
         if (param_set) {
             // Remove the parameter if this is the owner
             return remove_if_owner(*param_set, owner);
         }
         // Could not find the appropriate param name/type/plugin-owner
         return false;
     }
References find_name_type(), and remove_if_owner().
remove_if_owner()
bool scrimmage::ParameterServer::remove_if_owner (std::set< ParameterBasePtr > & param_set, PluginPtr owner) protected
Definition at line 48 of file ParameterServer.cpp.
{
     auto it_param = std::find_if(param_set.begin(),
                                  param_set.end(),
                                  [&](auto p) {
                                      return p->owner() == owner;
                                  });
     if (it_param != param_set.end()) {
         param_set.erase(it_param);
         return true;
     }
     return false;
 }
Referenced by unregister_param(), and unregister_params().
find_name_type()
boost::optional<std::set<ParameterBasePtr>&> scrimmage::ParameterServer::find_name_type (const std::string & name, const std::string & type) inline protected
Definition at line 95 of file ParameterServer.h.
{
         // Search for the parameter name
         auto it_name = params_.find(name);
         if (it_name != params_.end()) {
             // Search for the parameter type
             auto it_type = it_name->second.find(type);
             if (it_type != it_name->second.end()) {
                 return boost::optional<std::set<ParameterBasePtr>&>
                     (it_type->second);
             }
         }
         return boost::none;
     }
References params_.
Referenced by set_param(), and unregister_param().
Member Data Documentation
params_
std::unordered_map<std::string, std::unordered_map<std::string, std::set<ParameterBasePtr> > > scrimmage::ParameterServer::params_ protected
Definition at line 113 of file ParameterServer.h.
Referenced by find_name_type(), register_param(), and unregister_params().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/ParameterServer.h
/root/scrimmage/scrimmage/src/common/ParameterServer.cpp