SCRIMMAGE: scrimmage::Time Class Reference
scrimmage::Time Class Reference
#include <Time.h>
Public Member Functions
Time ()
double t () const
double dt () const
double time_warp () const
void set_t (double t)
void set_dt (double dt)
void set_time_warp (double time_warp)
Protected Attributes
double t_
double dt_
double time_warp_
Detailed Description
Definition at line 40 of file Time.h.
Constructor & Destructor Documentation
Time()
scrimmage::Time::Time () inline
Definition at line 42 of file Time.h.
            : t_(-1), dt_(-1), time_warp_(-1) {
     }
Member Function Documentation
t()
double scrimmage::Time::t () const inline
Definition at line 45 of file Time.h.
                      {
         return t_;
     }
References t_.
Referenced by set_t().
dt()
double scrimmage::Time::dt () const inline
Definition at line 48 of file Time.h.
                       {
         return dt_;
     }
References dt_.
Referenced by set_dt().
time_warp()
double scrimmage::Time::time_warp () const inline
Definition at line 51 of file Time.h.
{
         return time_warp_;
     }
References time_warp_.
Referenced by set_time_warp().
set_t()
void scrimmage::Time::set_t (double t) inline
Definition at line 55 of file Time.h.
{
         t_ = t;
     }
References t(), and t_.
set_dt()
void scrimmage::Time::set_dt (double dt) inline
Definition at line 58 of file Time.h.
{
         dt_ = dt;
     }
References dt(), and dt_.
set_time_warp()
void scrimmage::Time::set_time_warp (double time_warp) inline
Definition at line 61 of file Time.h.
{
         time_warp_ = time_warp;
     }
References time_warp(), and time_warp_.
Member Data Documentation
t_
double scrimmage::Time::t_ protected
Definition at line 66 of file Time.h.
Referenced by set_t(), and t().
dt_
double scrimmage::Time::dt_ protected
Definition at line 67 of file Time.h.
Referenced by dt(), and set_dt().
time_warp_
double scrimmage::Time::time_warp_ protected
Definition at line 68 of file Time.h.
Referenced by set_time_warp(), and time_warp().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/common/Time.h