SCRIMMAGE: scrimmage::Entity Class Reference
scrimmage::Entity Class Reference
#include <Entity.h>
Public Member Functions
utilities
bool init (AttributeMap &overrides, std::map< std::string, std::string > &info, std::shared_ptr< std::unordered_map< int, int >> &id_to_team_map, std::shared_ptr< std::unordered_map< int, EntityPtr >> &id_to_ent_map, ContactMapPtr &contacts, MissionParsePtr mp, const std::shared_ptr< GeographicLib::LocalCartesian > &proj, int id, int ent_desc_id, PluginManagerPtr plugin_manager, FileSearchPtr &file_search, RTreePtr &rtree, PubSubPtr &pubsub, TimePtr &time, const ParameterServerPtr &param_server, const GlobalServicePtr &global_services, const std::set< std::string > &plugin_tags, std::function< void(std::map< std::string, std::string > &)> param_override_func, const int &debug_level=0)
void print_plugins (std::ostream &out) const
bool parse_visual (std::map< std::string, std::string > &info, MissionParsePtr mp, std::map< std::string, std::string > &overrides)
void close (double t)
void collision ()
void hit ()
bool is_alive ()
bool posthumous (double t)
void setup_desired_state ()
bool ready ()
bool call_service (MessageBasePtr req, MessageBasePtr &res, const std::string &service_name)
bool call_service (MessageBasePtr &res, const std::string &service_name)
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type>
bool call_service (MessageBasePtr req, T &res, const std::string &service_name)
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type>
bool call_service (T &res, const std::string &service_name)
getters/setters
StatePtr & state ()
StatePtr & state_truth ()
std::vector< AutonomyPtr > & autonomies ()
MotionModelPtr & motion ()
std::vector< ControllerPtr > & controllers ()
void set_id (ID &id)
ID & id ()
void set_health_points (int health_points)
int health_points ()
std::shared_ptr< GeographicLib::LocalCartesian > projection ()
void set_projection (const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
void set_mp (MissionParsePtr mp)
MissionParsePtr mp ()
void set_random (RandomPtr random)
RandomPtr random ()
Contact::Type type ()
void set_visual_changed (bool visual_changed)
bool visual_changed ()
scrimmage_proto::ContactVisualPtr & contact_visual ()
std::unordered_map< std::string, SensorPtr > & sensors ()
std::unordered_map< std::string, SensorPtr > sensors (const std::string &sensor_name)
SensorPtr sensor (const std::string &sensor_name)
std::unordered_map< std::string, Service > & services ()
std::unordered_map< std::string, Service > & global_services ()
void set_global_services (const GlobalServicePtr &global_services)
std::unordered_map< std::string, MessageBasePtr > & properties ()
void set_active (bool active)
bool active ()
ContactMapPtr & contacts ()
RTreePtr & rtree ()
PluginManagerPtr & plugin_manager ()
FileSearchPtr & file_search ()
PubSubPtr & pubsub ()
const ParameterServerPtr & param_server ()
double radius ()
void set_time_ptr (TimePtr t)
Protected Member Functions
void print (const std::string &msg)
Protected Attributes
ID id_
scrimmage_proto::ContactVisualPtr visual_
std::vector< ControllerPtr > controllers_
MotionModelPtr motion_model_
std::vector< AutonomyPtr > autonomies_
MissionParsePtr mp_
int health_points_ = 1
int max_hits_ = -1
Contact::Type type_ = Contact::Type::AIRCRAFT
std::shared_ptr< GeographicLib::LocalCartesian > proj_
RandomPtr random_
StatePtr state_
StatePtr state_truth_
std::unordered_map< std::string, MessageBasePtr > properties_
std::unordered_map< std::string, SensorPtr > sensors_
bool active_ = true
bool visual_changed_ = false
std::unordered_map< std::string, Service > services_
ContactMapPtr contacts_
RTreePtr rtree_
double radius_ = 1
PluginManagerPtr plugin_manager_
FileSearchPtr file_search_
PubSubPtr pubsub_
GlobalServicePtr global_services_
ParameterServerPtr param_server_
TimePtr time_
Detailed Description
Definition at line 63 of file Entity.h.
Member Function Documentation
bool scrimmage::Entity::init (AttributeMap & overrides, std::map< std::string, std::string > & info, std::shared_ptr< std::unordered_map< int, int >> & id_to_team_map, std::shared_ptr< std::unordered_map< int, EntityPtr >> & id_to_ent_map, ContactMapPtr & contacts, MissionParsePtr mp, const std::shared_ptr< GeographicLib::LocalCartesian > & proj, int id, int ent_desc_id, PluginManagerPtr plugin_manager, FileSearchPtr & file_search, RTreePtr & rtree, PubSubPtr & pubsub, TimePtr & time, const ParameterServerPtr & param_server, const GlobalServicePtr & global_services, const std::set< std::string > & plugin_tags, std::function< void(std::map< std::string, std::string > &)> param_override_func, const int & debug_level = 0)
Definition at line 70 of file Entity.cpp.
References autonomies_, scrimmage::connect(), contacts(), contacts_, controllers_, scrimmage::Angles::deg2rad(), file_search(), file_search_, global_services(), global_services_, health_points_, id(), id_, scrimmage::Controller::init(), scrimmage::Sensor::init(), motion_model_, mp(), mp_, param_server(), param_server_, parse_visual(), scrimmage::PluginStatus< T >::plugin, plugin_manager(), plugin_manager_, scrimmage::print_io_error(), proj_, pubsub(), pubsub_, radius_, rtree(), rtree_, sensor(), sensors_, scrimmage::ID::set_id(), scrimmage::ID::set_sub_swarm_id(), scrimmage::ID::set_team_id(), state_, state_truth_, scrimmage::PluginStatus< T >::status, scrimmage::str2container(), time_, and scrimmage::verify_io_connection().
{
     pubsub_ = pubsub;
     global_services_ = global_services;
     time_ = time;
     file_search_ = file_search;
     plugin_manager_ = plugin_manager;
     contacts_ = contacts;
     rtree_ = rtree;
     proj_ = proj;
     param_server_ = param_server;
     id_.set_id(id);
     id_.set_sub_swarm_id(ent_desc_id);
     id_.set_team_id(std::stoi(info["team_id"]));
     if (mp == nullptr) {
         mp_ = std::make_shared<MissionParse>();
     } else {
         mp_ = mp;
         parse_visual(info, mp_, overrides["visual_model"]);
     }
     if (info.count("health") > 0) {
         health_points_ = std::stoi(info["health"]);
     }
     radius_ = get<double>("radius", info, 1.0);
     // set state
     if (!state_) {
         state_ = std::make_shared<State>();
     }
     state_truth_ = state_;
     double x = get("x", info, 0.0);
     double y = get("y", info, 0.0);
     double z = get("z", info, 0.0);
     state_->pos() << x, y, z;
     double vx = get("vx", info, 0.0);
     double vy = get("vy", info, 0.0);
     double vz = get("vz", info, 0.0);
     state_->vel() << vx, vy, vz;
     double sp = get("speed", info, 0.0);
     if (sp > 0 && vx == 0 && vy == 0 && vz == 0) {
       Eigen::Vector3d relative_vel_vector = Eigen::Vector3d::UnitX()*sp;
       Eigen::Vector3d vel_vector = state_->quat().rotate(relative_vel_vector);
       state_->vel() << vel_vector[0], vel_vector[1], vel_vector[2];
     }
     double roll = Angles::deg2rad(get("roll", info, 0.0));
     double pitch = Angles::deg2rad(get("pitch", info, 0.0));
     double yaw = Angles::deg2rad(get("heading", info, 0.0));
     state_->quat().set(roll, pitch, yaw);
     EntityPtr parent = shared_from_this();
     // Save entity specific params in mp reference for later use
     mp_->entity_params()[id] = info;
     mp_->ent_id_to_block_id()[id] = ent_desc_id;
     // sensor
     // The MissionParser appends the order number to the sensor (e.g., sensor0,
     // sensor1, etc.)
     int sensor_ct = 0;
     std::string sensor_order_name = std::string("sensor") +
         std::to_string(sensor_ct);
     while (info.count(sensor_order_name) > 0) {
         ConfigParse config_parse;
         std::string sensor_name = info[sensor_order_name];
         PluginStatus<Sensor> status =
             plugin_manager->make_plugin<Sensor>("scrimmage::Sensor",
                                                 sensor_name, *file_search,
                                                 config_parse,
                                                 overrides[sensor_order_name],
                                                 plugin_tags);
         if (status.status == PluginStatus<Sensor>::cast_failed) {
             std::cout << "Failed to open sensor plugin: " << sensor_name
                       << std::endl;
             return false;
         } else if (status.status == PluginStatus<Sensor>::parse_failed) {
             return false;
         } else if (status.status == PluginStatus<Sensor>::loaded) {
             SensorPtr sensor = status.plugin;
             // Get sensor's offset from entity origin
             std::vector<double> tf_xyz = {0.0, 0.0, 0.0};
             auto it_xyz = overrides[sensor_order_name].find("xyz");
             if (it_xyz != overrides[sensor_order_name].end()) {
                 str2container(it_xyz->second, " ", tf_xyz, 3);
             }
             sensor->transform()->pos() << tf_xyz[0], tf_xyz[1], tf_xyz[2];
             // Get sensor's orientation relative to entity's coordinate frame
             std::vector<double> tf_rpy = {0.0, 0.0, 0.0};
             auto it_rpy = overrides[sensor_order_name].find("rpy");
             if (it_rpy != overrides[sensor_order_name].end()) {
                 str2container(it_rpy->second, " ", tf_rpy, 3);
             }
             sensor->transform()->quat().set(Angles::deg2rad(tf_rpy[0]),
                                             Angles::deg2rad(tf_rpy[1]),
                                             Angles::deg2rad(tf_rpy[2]));
             sensor->set_parent(parent);
             sensor->set_pubsub(pubsub);
             sensor->set_time(time);
             sensor->set_id_to_team_map(id_to_team_map);
             sensor->set_id_to_ent_map(id_to_ent_map);
             sensor->set_param_server(param_server);
             param_override_func(config_parse.params());
             // get loop rate from plugin's params
             auto it_loop_rate = config_parse.params().find("loop_rate");
             if (it_loop_rate != config_parse.params().end()) {
               const double loop_rate = std::stod(it_loop_rate->second);
               sensor->set_loop_rate(loop_rate);
             }
             std::string given_name = sensor_name + std::to_string(sensor_ct);
             sensor->set_name(given_name);
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Sensor plugin params: " << given_name << endl;
                 cout << config_parse;
             }
             sensor->init(config_parse.params());
             sensors_[given_name] = sensor;
         }
         sensor_order_name = std::string("sensor") + std::to_string(++sensor_ct);
     }
     // motion model
     bool init_empty_motion_model = true;
     if (info.count("motion_model") > 0) {
         ConfigParse config_parse;
         PluginStatus<MotionModel> status =
             plugin_manager->make_plugin<MotionModel>("scrimmage::MotionModel",
                                                      info["motion_model"],
                                                      *file_search,
                                                      config_parse,
                                                      overrides["motion_model"],
                                                      plugin_tags);
         if (status.status == PluginStatus<MotionModel>::cast_failed) {
             cout << "Failed to open motion model plugin: " << info["motion_model"] << endl;
             return false;
         } else if (status.status == PluginStatus<MotionModel>::parse_failed) {
             return false;
         } else if (status.status == PluginStatus<MotionModel>::loaded) {
             // We have created a valid motion model
             init_empty_motion_model = false;
             motion_model_ = status.plugin;
             motion_model_->set_state(state_truth_);
             motion_model_->set_parent(parent);
             motion_model_->set_pubsub(pubsub);
             motion_model_->set_time(time);
             motion_model_->set_id_to_team_map(id_to_team_map);
             motion_model_->set_id_to_ent_map(id_to_ent_map);
             motion_model_->set_param_server(param_server);
             motion_model_->set_name(info["motion_model"]);
             param_override_func(config_parse.params());
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Motion plugin params: " << info["motion_model"] << endl;
                 cout << config_parse;
             }
             motion_model_->init(info, config_parse.params());
         }
     }
     if (init_empty_motion_model) {
         motion_model_ = std::make_shared<MotionModel>();
         motion_model_->set_state(state_truth_);
         motion_model_->set_parent(parent);
         motion_model_->set_pubsub(pubsub);
         motion_model_->set_param_server(param_server);
         motion_model_->set_time(time);
         motion_model_->set_id_to_team_map(id_to_team_map);
         motion_model_->set_id_to_ent_map(id_to_ent_map);
         motion_model_->set_name("BLANK");
     }
     // controller
     // Create a list of controller names (from XML top-down order)
     std::list<std::string> controller_names;
     int controller_ct = 0;
     std::string controller_name = std::string("controller") + std::to_string(controller_ct);
     bool valid_controller_name = true;
     do {
         if (info.count(controller_name) > 0) {
             controller_names.push_back(controller_name);
         } else {
             valid_controller_name = false;
         }
         controller_name = std::string("controller") + std::to_string(++controller_ct);
     } while (valid_controller_name);
     // Reverse iterate over controllers, so that the VariableIO can be setup
     // correctly. Last controller connects to motion model, second to last
     // controller connects to the last controller.
     for (std::list<std::string>::reverse_iterator rit = controller_names.rbegin();
          rit != controller_names.rend(); ++rit) {
         std::string controller_name = *rit;
         ConfigParse config_parse;
         PluginStatus<Controller> status =
             plugin_manager_->make_plugin<Controller>("scrimmage::Controller",
                                                      info[controller_name],
                                                      *file_search,
                                                      config_parse,
                                                      overrides[controller_name],
                                                      plugin_tags);
         if (status.status == PluginStatus<Controller>::cast_failed) {
             std::cout << "Failed to open controller plugin: "
                       << controller_name << std::endl;
             return false;
         } else if (status.status == PluginStatus<Controller>::parse_failed) {
             return false;
         } else if (status.status == PluginStatus<Controller>::loaded) {
             ControllerPtr controller = status.plugin;
             controller->set_state(state_);
             controller->set_parent(shared_from_this());
             controller->set_time(time_);
             controller->set_id_to_team_map(id_to_team_map);
             controller->set_id_to_ent_map(id_to_ent_map);
             controller->set_param_server(param_server);
             controller->set_pubsub(pubsub_);
             controller->set_name(info[controller_name]);
             param_override_func(config_parse.params());
             // get loop rate from plugin's params
             auto it_loop_rate = config_parse.params().find("loop_rate");
             if (it_loop_rate != config_parse.params().end()) {
               const double loop_rate = std::stod(it_loop_rate->second);
               controller->set_loop_rate(loop_rate);
             }
             // Connect this controller to the motion model if it is the last
             // controller in XML top-down order (i.e., first in the reverse
             // list). If it is not the last controller, connect it to the next
             // controller.
             bool connect_to_motion_model = (controllers_.size() == 0);
             if (connect_to_motion_model) {
                 connect(controller->vars(), motion_model_->vars());
             } else {
                 connect(controller->vars(), controllers_.back()->vars());
             }
             // Initialize this controller.
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Controller plugin params: " << info[controller_name] << endl;
                 cout << config_parse;
             }
             controller->init(config_parse.params());
             // Verify the VariableIO connection
             if (connect_to_motion_model) {
                 if (!verify_io_connection(controller->vars(), motion_model_->vars())) {
                     std::cout << "VariableIO Error: "
                               << std::quoted(controller->name())
                               << " does not provide inputs required by motion model "
                               << std::quoted(motion_model_->name())
                               << ": ";
                     print_io_error(motion_model_->name(), motion_model_->vars());
                     return false;
                 }
             } else if (not connect_to_motion_model) {
                 if (!verify_io_connection(controller->vars(), controllers_.back()->vars())) {
                     std::cout << "VariableIO Error: "
                               << std::quoted(controller->name())
                               << " does not provide inputs required by next controller "
                               << std::quoted(controllers_.back()->name())
                               << ": ";
                     print_io_error(controllers_.back()->name(), controllers_.back()->vars());
                     return false;
                 }
             }
             // Save this controller instance
             controllers_.push_back(controller);
         }
     }
     // Since the controllers_ list was constructed in reverse XML order, we
     // need to reverse it to ensure that the controllers are executed in the
     // correct order
     std::reverse(controllers_.begin(), controllers_.end());
     // If the motion model requires any inputs and there are no controllers,
     // this is a VariableIO error.
     if (motion_model_->vars().input_variable_index().size() > 0 &&
         controllers_.size() == 0) {
         std::cout << "VariableIO Error: There are not any controllers that "
                   << "provide the inputs required by "
                   << std::quoted(motion_model_->name()) << std::endl;
         print_io_error(motion_model_->name(), motion_model_->vars());
         std::cout << "If you want to directly pass the outputs from the "
                   << "autonomy to the motion_model, see the DirectController "
                   << "controller plugin." << std::endl;
         return false;
     }
     // autonomy
     // Create a list of autonomy names
     std::list<std::string> autonomy_names;
     int autonomy_ct = 0;
     std::string autonomy_name = std::string("autonomy") + std::to_string(autonomy_ct);
     while (info.count(autonomy_name) > 0) {
         autonomy_names.push_back(autonomy_name);
         autonomy_name = std::string("autonomy") + std::to_string(++autonomy_ct);
     }
     // Create the autonomy plugins from the autonomy_names list.
     for (auto autonomy_name : autonomy_names) {
         auto autonomy = make_autonomy<Autonomy>(
             info[autonomy_name], plugin_manager, overrides[autonomy_name],
             parent, state_, id_to_team_map, id_to_ent_map, proj_, contacts,
             file_search, rtree, pubsub, time, param_server, plugin_tags,
             param_override_func, controllers_,
             debug_level);
         if (autonomy) {
             autonomies_.push_back(*autonomy);
         }
     }
     bool connect_entity = true;
     if (info.count("connect_entity") > 0) {
         connect_entity = boost::lexical_cast<bool>(info["connect_entity"]);
     }
     // Verify that at least one autonomy provides the inputs to the first
     // controller if the first controller requires some VariableIO input.
     if (connect_entity && not controllers_.empty() &&
         controllers_.front()->vars().input_variable_index().size() > 0) {
         auto verify_io = [&](auto &autonomy) {
             return verify_io_connection(autonomy->vars(),
                                         controllers_.front()->vars());};
         if (boost::algorithm::none_of(autonomies_, verify_io)) {
             auto out_it = std::ostream_iterator<std::string>(std::cout, ", ");
             std::cout << "VariableIO Error: "
                       << "no autonomies provide inputs required by Controller "
                       << std::quoted(controllers_.front()->name())
                       << ". Add VariableIO output declarations in ";
             auto get_name = [&](auto &p) {return p->name();};
             br::copy(autonomies_ | ba::transformed(get_name), out_it);
             std::cout << "as follows " << std::endl;
             print_io_error(controllers_.front()->name(), controllers_.front()->vars());
             return false;
         }
     }
     if (not controllers_.empty()) {
         if (autonomies_.empty()) {
             controllers_.front()->set_desired_state(state_);
         } else {
             controllers_.front()->set_desired_state(autonomies_.front()->desired_state());
         }
     }
     return true;
 }
void scrimmage::Entity::print_plugins (std::ostream & out) const
Definition at line 710 of file Entity.cpp.
References autonomies_, controllers_, motion_model_, and sensors_.
{
     out << "----------- Sensor -------------" << endl;
     for (auto &kv : sensors_) {
         out << kv.second->name() << endl;
     }
     out << "---------- Autonomy ------------" << endl;
     for (AutonomyPtr a : autonomies_) {
         out << a->name() << endl;
     }
     out << "---------- Controller ----------" << endl;
     for (ControllerPtr c : controllers_) {
         out << c->name() << endl;
     }
     out << "----------- Motion -------------" << endl;
     if (motion_model_->name() != "BLANK") {
         out << motion_model_->name() << endl;
     }
 }
bool scrimmage::Entity::parse_visual (std::map< std::string, std::string > & info, MissionParsePtr mp, std::map< std::string, std::string > & overrides)
Definition at line 466 of file Entity.cpp.
References scrimmage::Contact::AIRCRAFT, file_search_, scrimmage::find_model_properties(), scrimmage::ID::id(), id_, scrimmage::Contact::MESH, scrimmage::Contact::QUADROTOR, scrimmage::Contact::SPHERE, scrimmage::str2container(), scrimmage::ID::team_id(), type_, and visual_.
Referenced by init().
{
     visual_->set_id(id_.id());
     visual_->set_opacity(1.0);
     ConfigParse cv_parse;
     bool mesh_found, texture_found;
     auto it = info.find("visual_model");
     if (it == info.end()) {
         return true;
     }
     find_model_properties(it->second, cv_parse,
                           *file_search_, overrides, visual_,
                           mesh_found, texture_found);
     // Set the entity color. Use the team color by default
     std::vector<int> color;
     auto it_color = info.find("color");
     if (it_color != info.end() and
         str2container(it_color->second, ", ", color, 3)) {
     } else {
         set(color, mp->team_info()[id_.team_id()].color);
     }
     set(visual_->mutable_color(), color[0], color[1], color[2]);
     std::string visual_model = boost::to_upper_copy(info["visual_model"]);
     if (mesh_found) {
         type_ = Contact::Type::MESH;
         visual_->set_visual_mode(texture_found ? scrimmage_proto::ContactVisual::TEXTURE : scrimmage_proto::ContactVisual::COLOR);
     } else if (visual_model == std::string("QUADROTOR")) {
         type_ = Contact::Type::QUADROTOR;
         visual_->set_visual_mode(scrimmage_proto::ContactVisual::COLOR);
     } else if (visual_model == std::string("AIRCRAFT")) {
         type_ = Contact::Type::AIRCRAFT;
         visual_->set_visual_mode(scrimmage_proto::ContactVisual::COLOR);
     } else if (visual_model == std::string("SPHERE")) {
         type_ = Contact::Type::SPHERE;
         visual_->set_visual_mode(scrimmage_proto::ContactVisual::COLOR);
     } else {
         type_ = Contact::Type::SPHERE;
         visual_->set_visual_mode(scrimmage_proto::ContactVisual::COLOR);
     }
     return true;
 }
void scrimmage::Entity::close (double t)
Definition at line 662 of file Entity.cpp.
References autonomies_, contacts_, controllers_, file_search_, global_services_, motion_model_, mp_, plugin_manager_, proj_, properties_, pubsub_, random_, rtree_, sensors_, services_, state_, state_truth_, time_, and visual_.
{
     for (AutonomyPtr autonomy : autonomies_) {
         autonomy->close_plugin(t);
     }
     for (auto &kv : sensors_) {
         kv.second->close_plugin(t);
     }
     for (ControllerPtr controller : controllers_) {
         controller->close_plugin(t);
     }
     if (motion_model_) {
         motion_model_->close_plugin(t);
     }
     visual_ = nullptr;
     controllers_.clear();
     autonomies_.clear();
     mp_ = nullptr;
     proj_ = nullptr;
     random_ = nullptr;
     state_ = nullptr;
     state_truth_ = nullptr;
     properties_.clear();
     sensors_.clear();
     services_.clear();
     contacts_ = nullptr;
     rtree_ = nullptr;
     plugin_manager_ = nullptr;
     file_search_ = nullptr;
     pubsub_ = nullptr;
     global_services_ = nullptr;
     time_ = nullptr;
 }
void scrimmage::Entity::collision ()
Definition at line 543 of file Entity.cpp.
References health_points_.
 { health_points_ -= 1e9; }
void scrimmage::Entity::hit ()
Definition at line 545 of file Entity.cpp.
References health_points_.
 { health_points_--; }
bool scrimmage::Entity::is_alive ()
Definition at line 552 of file Entity.cpp.
References health_points_.
                       {
     return (health_points_ > 0);
 }
bool scrimmage::Entity::posthumous (double t)
Definition at line 556 of file Entity.cpp.
References autonomies_, and motion_model_.
{
     bool any_autonomies =
         std::any_of(autonomies_.begin(), autonomies_.end(),
                     [t](AutonomyPtr &a) {return a->posthumous(t);});
     return any_autonomies && motion_model_->posthumous(t);
 }
void scrimmage::Entity::setup_desired_state ()
Definition at line 606 of file Entity.cpp.
References autonomies_, and controllers_.
{
     if (controllers_.empty()) return;
     auto it = std::find_if(autonomies_.rbegin(), autonomies_.rend(),
         [&](auto autonomy) {return autonomy->get_is_controlling();});
     if (it != autonomies_.rend()) {
         controllers_.front()->set_desired_state((*it)->desired_state());
     }
 }
bool scrimmage::Entity::ready ()
Definition at line 514 of file Entity.cpp.
References autonomies_, controllers_, motion_model_, and sensors_.
                    {
     auto all_ready = [&](auto &rng, auto &func) {
         return std::all_of(rng.begin(), rng.end(), func);
     };
     auto single_ready = [&](auto &plugin) {return plugin->ready();};
     auto values_single_ready = [&](auto &kv) {return kv.second->ready();};
     return all_ready(autonomies_, single_ready)
         && all_ready(controllers_, single_ready)
         && all_ready(sensors_, values_single_ready)
         && motion_model_->ready();
 }
bool scrimmage::Entity::call_service (scrimmage::MessageBasePtr req, scrimmage::MessageBasePtr & res, const std::string & service_name)
Definition at line 626 of file Entity.cpp.
References global_services_, and services_.
{
     auto it = services_.find(service_name);
     if (it == services_.end()) {
         // First check for a global service of this name
         bool found = global_services_->call_service(req, res, service_name);
         if (!found) {
             std::cout << "request for service ("
                 << service_name
                 << ") that does not exist" << std::endl;
             std::cout << "services are: ";
             for (auto &kv : services_) {
                 std::cout << kv.first << ", ";
             }
             std::cout << std::endl;
             return false;
         } else {
             return true;
         }
     }
     Service &service = it->second;
     bool success = service(req, res);
     if (!success) {
         std::cout << "call to " << service_name << " failed" << std::endl;
         return false;
     } else {
         return true;
     }
 }
bool scrimmage::Entity::call_service (MessageBasePtr & res, const std::string & service_name) inline
Definition at line 104 of file Entity.h.
{
         return call_service(std::make_shared<MessageBase>(), res, service_name);
     }
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type> bool scrimmage::Entity::call_service (MessageBasePtr req, T & res, const std::string & service_name) inline
Definition at line 110 of file Entity.h.
{
         MessageBasePtr res_base;
         if (call_service(req, res_base, service_name)) {
             res = std::dynamic_pointer_cast<typename T::element_type>(res_base);
             if (res == nullptr) {
                 print(std::string("could not cast for service ") + service_name);
                 return false;
             } else {
                 return true;
             }
         } else {
             return false;
         }
     }
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type> bool scrimmage::Entity::call_service (T & res, const std::string & service_name) inline
Definition at line 127 of file Entity.h.
{
         return call_service(std::make_shared<MessageBase>(), res, service_name);
     }
StatePtr & scrimmage::Entity::state ()
Definition at line 528 of file Entity.cpp.
References state_.
 {return state_;}
StatePtr & scrimmage::Entity::state_truth ()
Definition at line 529 of file Entity.cpp.
References state_truth_.
 {return state_truth_;}
std::vector< AutonomyPtr > & scrimmage::Entity::autonomies ()
Definition at line 531 of file Entity.cpp.
References autonomies_.
 {return autonomies_;}
MotionModelPtr & scrimmage::Entity::motion ()
Definition at line 533 of file Entity.cpp.
References motion_model_.
 {return motion_model_;}
std::vector< ControllerPtr > & scrimmage::Entity::controllers ()
Definition at line 535 of file Entity.cpp.
References controllers_.
{
     return controllers_;
 }
void scrimmage::Entity::set_id (ID & id)
Definition at line 539 of file Entity.cpp.
References id(), and id_.
 { id_ = id; }
ID & scrimmage::Entity::id ()
Definition at line 541 of file Entity.cpp.
References id_.
Referenced by init(), and set_id().
 { return id_; }
void scrimmage::Entity::set_health_points (int health_points)
Definition at line 547 of file Entity.cpp.
References health_points(), and health_points_.
 { health_points_ = health_points; }
int scrimmage::Entity::health_points ()
Definition at line 550 of file Entity.cpp.
References health_points_.
Referenced by set_health_points().
 { return health_points_; }
std::shared_ptr< GeographicLib::LocalCartesian > scrimmage::Entity::projection ()
Definition at line 563 of file Entity.cpp.
References proj_.
 { return proj_; }
void scrimmage::Entity::set_projection (const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 706 of file Entity.cpp.
References proj_.
{
     proj_ = proj;
 }
void scrimmage::Entity::set_mp (MissionParsePtr mp)
Definition at line 568 of file Entity.cpp.
References mp(), and mp_.
 { mp_ = mp; }
MissionParsePtr scrimmage::Entity::mp ()
Definition at line 566 of file Entity.cpp.
References mp_.
Referenced by init(), and set_mp().
 { return mp_; }
void scrimmage::Entity::set_random (RandomPtr random)
Definition at line 569 of file Entity.cpp.
References random(), and random_.
 { random_ = random; }
RandomPtr scrimmage::Entity::random ()
Definition at line 571 of file Entity.cpp.
References random_.
Referenced by set_random().
 { return random_; }
Contact::Type scrimmage::Entity::type ()
Definition at line 573 of file Entity.cpp.
References type_.
 { return type_; }
void scrimmage::Entity::set_visual_changed (bool visual_changed)
Definition at line 575 of file Entity.cpp.
References visual_changed(), and visual_changed_.
 { visual_changed_ = visual_changed; }
bool scrimmage::Entity::visual_changed ()
Definition at line 578 of file Entity.cpp.
References visual_changed_.
Referenced by set_visual_changed().
 { return visual_changed_; }
scrimmage_proto::ContactVisualPtr & scrimmage::Entity::contact_visual ()
Definition at line 580 of file Entity.cpp.
References visual_.
 { return visual_; }
std::unordered_map< std::string, SensorPtr > & scrimmage::Entity::sensors ()
Definition at line 583 of file Entity.cpp.
References sensors_.
Referenced by sensor().
{
     return sensors_;
 }
std::unordered_map< std::string, SensorPtr > scrimmage::Entity::sensors (const std::string & sensor_name)
Definition at line 587 of file Entity.cpp.
References sensors_.
{
     std::unordered_map<std::string, SensorPtr> out;
     for (auto &kv : sensors_) {
         if (kv.first.find(sensor_name) != std::string::npos) {
             out[kv.first] = kv.second;
         }
     }
     return out;
 }
SensorPtr scrimmage::Entity::sensor (const std::string & sensor_name)
Definition at line 597 of file Entity.cpp.
References sensors().
Referenced by init().
{
     std::unordered_map<std::string, SensorPtr> out = sensors(sensor_name);
     return out.empty() ? nullptr : out.begin()->second;
 }
std::unordered_map< std::string, Service > & scrimmage::Entity::services ()
Definition at line 617 of file Entity.cpp.
References services_.
 {return services_;}
std::unordered_map< std::string, Service > & scrimmage::Entity::global_services ()
Definition at line 618 of file Entity.cpp.
References global_services_.
Referenced by init(), and set_global_services().
{
     return global_services_->services();
 }
void scrimmage::Entity::set_global_services (const GlobalServicePtr & global_services)
Definition at line 622 of file Entity.cpp.
References global_services(), and global_services_.
{
     global_services_ = global_services;
 }
std::unordered_map< std::string, MessageBasePtr > & scrimmage::Entity::properties ()
Definition at line 699 of file Entity.cpp.
References properties_.
{
     return properties_;
 }
void scrimmage::Entity::set_active (bool active)
Definition at line 602 of file Entity.cpp.
References active(), and active_.
 { active_ = active; }
bool scrimmage::Entity::active ()
Definition at line 604 of file Entity.cpp.
References active_.
Referenced by set_active().
 { return active_; }
ContactMapPtr& scrimmage::Entity::contacts () inline
Definition at line 178 of file Entity.h.
Referenced by init().
 { return contacts_; }
RTreePtr& scrimmage::Entity::rtree () inline
Definition at line 179 of file Entity.h.
Referenced by init().
 { return rtree_; }
PluginManagerPtr& scrimmage::Entity::plugin_manager () inline
Definition at line 181 of file Entity.h.
Referenced by init().
{
         return plugin_manager_;
     }
FileSearchPtr& scrimmage::Entity::file_search () inline
Definition at line 185 of file Entity.h.
Referenced by init().
{
         return file_search_;
     }
PubSubPtr& scrimmage::Entity::pubsub () inline
Definition at line 189 of file Entity.h.
Referenced by init().
{
         return pubsub_;
     }
const ParameterServerPtr& scrimmage::Entity::param_server () inline
Definition at line 193 of file Entity.h.
Referenced by init().
{
         return param_server_;
     }
double scrimmage::Entity::radius () inline
Definition at line 197 of file Entity.h.
 { return radius_; }
void scrimmage::Entity::set_time_ptr (TimePtr t)
Definition at line 703 of file Entity.cpp.
References time_.
 {time_ = t;}
void scrimmage::Entity::print (const std::string & msg) protected
Definition at line 658 of file Entity.cpp.
{
     std::cout << msg << std::endl;
 }
Member Data Documentation
ID scrimmage::Entity::id_ protected
Definition at line 203 of file Entity.h.
Referenced by id(), init(), parse_visual(), and set_id().
scrimmage_proto::ContactVisualPtr scrimmage::Entity::visual_ protected
Initial value:
=
        std::make_shared<scrimmage_proto::ContactVisual>()
Definition at line 205 of file Entity.h.
Referenced by close(), contact_visual(), and parse_visual().
std::vector<ControllerPtr> scrimmage::Entity::controllers_ protected
Definition at line 208 of file Entity.h.
Referenced by close(), controllers(), init(), print_plugins(), ready(), and setup_desired_state().
MotionModelPtr scrimmage::Entity::motion_model_ protected
Definition at line 209 of file Entity.h.
Referenced by close(), init(), motion(), posthumous(), print_plugins(), and ready().
std::vector<AutonomyPtr> scrimmage::Entity::autonomies_ protected
Definition at line 210 of file Entity.h.
Referenced by autonomies(), close(), init(), posthumous(), print_plugins(), ready(), and setup_desired_state().
MissionParsePtr scrimmage::Entity::mp_ protected
Definition at line 211 of file Entity.h.
Referenced by close(), init(), mp(), and set_mp().
int scrimmage::Entity::health_points_ = 1 protected
Definition at line 213 of file Entity.h.
Referenced by collision(), health_points(), hit(), init(), is_alive(), and set_health_points().
int scrimmage::Entity::max_hits_ = -1 protected
Definition at line 215 of file Entity.h.
Contact::Type scrimmage::Entity::type_ = Contact::Type::AIRCRAFT protected
Definition at line 217 of file Entity.h.
Referenced by parse_visual(), and type().
std::shared_ptr<GeographicLib::LocalCartesian> scrimmage::Entity::proj_ protected
Definition at line 219 of file Entity.h.
Referenced by close(), init(), projection(), and set_projection().
RandomPtr scrimmage::Entity::random_ protected
Definition at line 221 of file Entity.h.
Referenced by close(), random(), and set_random().
StatePtr scrimmage::Entity::state_ protected
Definition at line 223 of file Entity.h.
Referenced by close(), init(), and state().
StatePtr scrimmage::Entity::state_truth_ protected
Definition at line 224 of file Entity.h.
Referenced by close(), init(), and state_truth().
std::unordered_map<std::string, MessageBasePtr> scrimmage::Entity::properties_ protected
Definition at line 225 of file Entity.h.
Referenced by close(), and properties().
std::unordered_map<std::string, SensorPtr> scrimmage::Entity::sensors_ protected
Definition at line 226 of file Entity.h.
Referenced by close(), init(), print_plugins(), ready(), and sensors().
bool scrimmage::Entity::active_ = true protected
Definition at line 228 of file Entity.h.
Referenced by active(), and set_active().
bool scrimmage::Entity::visual_changed_ = false protected
Definition at line 229 of file Entity.h.
Referenced by set_visual_changed(), and visual_changed().
std::unordered_map<std::string, Service> scrimmage::Entity::services_ protected
Definition at line 230 of file Entity.h.
Referenced by call_service(), close(), and services().
ContactMapPtr scrimmage::Entity::contacts_ protected
Definition at line 232 of file Entity.h.
Referenced by close(), and init().
RTreePtr scrimmage::Entity::rtree_ protected
Definition at line 233 of file Entity.h.
Referenced by close(), and init().
double scrimmage::Entity::radius_ = 1 protected
Definition at line 235 of file Entity.h.
Referenced by init().
PluginManagerPtr scrimmage::Entity::plugin_manager_ protected
Definition at line 238 of file Entity.h.
Referenced by close(), and init().
FileSearchPtr scrimmage::Entity::file_search_ protected
Definition at line 239 of file Entity.h.
Referenced by close(), init(), and parse_visual().
PubSubPtr scrimmage::Entity::pubsub_ protected
Definition at line 240 of file Entity.h.
Referenced by close(), and init().
GlobalServicePtr scrimmage::Entity::global_services_ protected
Definition at line 241 of file Entity.h.
Referenced by call_service(), close(), global_services(), init(), and set_global_services().
ParameterServerPtr scrimmage::Entity::param_server_ protected
Definition at line 242 of file Entity.h.
Referenced by init().
TimePtr scrimmage::Entity::time_ protected
Definition at line 243 of file Entity.h.
Referenced by close(), init(), and set_time_ptr().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/entity/Entity.h
/root/scrimmage/scrimmage/src/entity/Entity.cpp