SCRIMMAGE: scrimmage::Sensor Class Reference
scrimmage::Sensor Class Reference
#include <Sensor.h>
Public Member Functions
virtual void init (std::map< std::string, std::string > &params)
std::string type () override
virtual bool step ()
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Detailed Description
Definition at line 46 of file Sensor.h.
Member Function Documentation
void scrimmage::Sensor::init (std::map< std::string, std::string > & params) virtual
Reimplemented in scrimmage::sensor::AirSimSensor, scrimmage::sensor::RayTrace, scrimmage::sensor::ROSIMUSensor, scrimmage::sensor::ContactBlobCamera, scrimmage::sensor::GPS, scrimmage::sensor::AltitudeAboveTerrain, scrimmage::sensor::RigidBody6DOFStateSensor, scrimmage::sensor::ROSAltimeter, scrimmage::sensor::ROSCompass, scrimmage::sensor::LOSSensor, scrimmage::sensor::NoisyContacts, scrimmage::sensor::SimpleINS, and scrimmage::sensor::NoisyState.
Definition at line 37 of file Sensor.cpp.
Referenced by scrimmage::Entity::init().
 {return;}
std::string scrimmage::Sensor::type () override virtual
Reimplemented from scrimmage::Plugin.
Definition at line 39 of file Sensor.cpp.
 {return std::string("Sensor");}
virtual bool scrimmage::Sensor::step () inline virtual
Reimplemented in scrimmage::sensor::AirSimSensor, scrimmage::sensor::RayTrace, scrimmage::sensor::ROSIMUSensor, scrimmage::sensor::ContactBlobCamera, scrimmage::sensor::GPS, scrimmage::sensor::AltitudeAboveTerrain, scrimmage::sensor::RigidBody6DOFStateSensor, scrimmage::sensor::ROSAltimeter, scrimmage::sensor::ROSCompass, scrimmage::sensor::LOSSensor, scrimmage::sensor::NoisyContacts, scrimmage::sensor::SimpleINS, and scrimmage::sensor::NoisyState.
Definition at line 52 of file Sensor.h.
References sensor_msg().
 {return true;}
scrimmage::MessageBasePtr scrimmage::Sensor::sensor_msg (double t) virtual
Definition at line 41 of file Sensor.cpp.
Referenced by sense(), and step().
{
     return nullptr;
 }
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>> MessageBasePtr scrimmage::Sensor::sense (double t) inline
version when T = MessageBase (calls sensor_msg without casting)
Definition at line 59 of file Sensor.h.
References sensor_msg().
{
         return sensor_msg(t);
     }
template<class T > std::shared_ptr<scrimmage::Message<T> > scrimmage::Sensor::sense (double t) inline
default version
Definition at line 66 of file Sensor.h.
References sensor_msg().
{
         auto msg = sensor_msg(t);
         if (msg) {
             auto msg_cast = std::dynamic_pointer_cast<scrimmage::Message<T>>(msg);
             return msg_cast ?
                 std::shared_ptr<scrimmage::Message<T>>(msg_cast) : nullptr;
         } else {
             return nullptr;
         }
     }
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/sensor/Sensor.h
/root/scrimmage/scrimmage/src/sensor/Sensor.cpp