SCRIMMAGE: scrimmage::motion::JSBSimModel Class Reference
scrimmage::motion::JSBSimModel Class Reference
#include <JSBSimModel.h>
Public Member Functions
virtual std::tuple< int, int, int > version ()
virtual bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params)
virtual bool step (double time, double dt)
virtual void teleport (StatePtr &state)
bool use_pitch ()
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
bool use_pitch_ = false
int speed_idx_ = 0
int roll_idx_ = 0
int alt_or_pitch_idx_ = 0
bool fg_out_enable_ = false
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
virtual void model (const vector_t &x, vector_t &dxdt, double t)
Detailed Description
Definition at line 63 of file JSBSimModel.h.
Member Function Documentation
std::tuple< int, int, int > scrimmage::motion::JSBSimModel::version () virtual
Definition at line 68 of file JSBSimModel.cpp.
{
     return std::tuple<int, int, int>(0, 0, 1);
 }
bool scrimmage::motion::JSBSimModel::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 72 of file JSBSimModel.cpp.
References scrimmage::Angles::deg2rad(), feet2meters, meters2feet, scrimmage::Angles::rad2deg(), and scrimmage::str2bool().
{
     angles_from_jsbsim_ = Angles(0, Angles::Type::GPS, Angles::Type::EUCLIDEAN);
     angles_to_jsbsim_ = Angles(0, Angles::Type::EUCLIDEAN, Angles::Type::GPS);
     use_pitch_ = str2bool(params.at("use_pitch"));
     std::string z_name =  use_pitch_ ?
         vars_.type_map().at(VariableIO::Type::desired_pitch) :
         vars_.type_map().at(VariableIO::Type::desired_altitude);
     speed_idx_ = vars_.declare(VariableIO::Type::desired_speed, VariableIO::Direction::In);
     roll_idx_ = vars_.declare(VariableIO::Type::desired_roll, VariableIO::Direction::In);
     alt_or_pitch_idx_ = vars_.declare(z_name, VariableIO::Direction::In);
     JSBSim::FGJSBBase base;
     base.debug_lvl = 0;
     exec_ = std::make_shared<JSBSim::FGFDMExec>();
     fg_out_enable_ = get<bool>("flightgear_output_enable", params, false);
     if (fg_out_enable_) {
         output_fg_ = new JSBSim::FGOutputFGMod(&(*exec_));
         std::string ip = get<std::string>("flightgear_ip", params, "localhost");
         std::string port = get<std::string>("flightgear_port", params, "5600");
         std::string protocol = get<std::string>("flightgear_protocol", params, "UDP");
         std::string name = ip + ":" + protocol + "/" + port; // localhost:UDP/5600
         output_fg_->SetIdx(0);
         output_fg_->SetOutputName(name);
         output_fg_->SetRateHz(60);
         output_fg_->InitModel();
     }
     exec_->SetDebugLevel(0);
     std::string jsbsim_root_dir = get<std::string>("jsbsim_root", params, info["JSBSIM_ROOT"]);
     if (jsbsim_root_dir == "") {
         exec_->SetRootDir(SGPath(info["JSBSIM_ROOT"]));
     } else {
         exec_->SetRootDir(SGPath(jsbsim_root_dir));
     }
     exec_->SetAircraftPath(SGPath("aircraft"));
     exec_->SetEnginePath(SGPath("engine"));
     exec_->SetSystemsPath(SGPath("systems"));
     exec_->LoadScript(SGPath("scripts/"+info["script_name"]));
     JSBSim::FGInitialCondition *ic = exec_->GetIC();
     if (info.count("latitude") > 0) {
         ic->SetLatitudeDegIC(std::stod(info["latitude"]));
     }
     if (info.count("longitude") > 0) {
         ic->SetLongitudeDegIC(std::stod(info["longitude"]));
     }
     if (info.count("heading") > 0) {
         angles_to_jsbsim_.set_angle(std::stod(info["heading"]));
         ic->SetPsiDegIC(angles_to_jsbsim_.angle());
     }
     if (info.count("altitude") > 0) {
         double alt_asl_meters = std::stod(info["altitude"]);
         ic->SetAltitudeASLFtIC(alt_asl_meters * meters2feet);
     }
     if (info.count("dt")) {
         dt_ = std::stod(info["dt"]);
         if (info.count("motion_multiplier")) {
             double motion_multiplier = std::stod(info["motion_multiplier"]);
             dt_ /= motion_multiplier;
         }
     } else {
         dt_ = 0.0083333;
     }
     exec_->RunIC();
     exec_->Setdt(dt_);
     exec_->Run();
     // If we need to trim programmatically later
     // if (exec_->GetIC()->NeedTrim()) {
     //     cout << "Trimming..." << endl;
     //     JSBSim::FGTrim* trimmer = new JSBSim::FGTrim( &*exec_ );
     //     try {
     //          trimmer->DoTrim();
     //          delete trimmer;
     //     } catch (string& msg) {
     //          std::cerr << endl << msg << endl << endl;
     //          exit(1);
     //     }
     //}
     // Get references to each of the nodes that hold properties that we
     // care about
     JSBSim::FGPropertyManager* mgr = exec_->GetPropertyManager();
     longitude_node_ = mgr->GetNode("position/long-gc-deg");
     latitude_node_ = mgr->GetNode("position/lat-gc-deg");
     altitude_node_ = mgr->GetNode("position/h-sl-ft");
     roll_node_ = mgr->GetNode("attitude/roll-rad");
     pitch_node_ = mgr->GetNode("attitude/pitch-rad");
     yaw_node_ = mgr->GetNode("attitude/heading-true-rad");
     // desired_heading_node_ = mgr->GetNode("guidance/specified-heading-rad");
     desired_altitude_node_ = mgr->GetNode("ap/altitude_setpoint");
     desired_velocity_node_ = mgr->GetNode("ap/airspeed_setpoint");
     bank_setpoint_node_ = mgr->GetNode("ap/bank_setpoint");
     fcs_elevator_cmd_node_ = mgr->GetNode("fcs/elevator-cmd-norm");
     vel_north_node_ = mgr->GetNode("velocities/v-north-fps");
     vel_east_node_ = mgr->GetNode("velocities/v-east-fps");
     vel_down_node_ = mgr->GetNode("velocities/v-down-fps");
     // angular velocity in ECEF frame
     p_node_ = mgr->GetNode("velocities/p-rad_sec");
     q_node_ = mgr->GetNode("velocities/q-rad_sec");
     r_node_ = mgr->GetNode("velocities/r-rad_sec");
     // acceleration at pilot location in body frame
     ax_pilot_node_ = mgr->GetNode("accelerations/a-pilot-x-ft_sec2");
     ax_pilot_node_ = mgr->GetNode("accelerations/a-pilot-y-ft_sec2");
     ax_pilot_node_ = mgr->GetNode("accelerations/a-pilot-z-ft_sec2");
     // Save state
     parent_->projection()->Forward(latitude_node_->getDoubleValue(),
                                   longitude_node_->getDoubleValue(),
                                   altitude_node_->getDoubleValue() * feet2meters,
                                   state_->pos()(0), state_->pos()(1), state_->pos()(2));
     angles_from_jsbsim_.set_angle(ang::rad2deg(yaw_node_->getDoubleValue()));
     state_->quat().set(roll_node_->getDoubleValue(),
                       -pitch_node_->getDoubleValue(),
                       ang::deg2rad(angles_from_jsbsim_.angle()));
     state_->vel() << vel_east_node_->getDoubleValue() * feet2meters,
                     vel_north_node_->getDoubleValue() * feet2meters,
                     -vel_down_node_->getDoubleValue() * feet2meters;
     state_->ang_vel() << p_node_->getDoubleValue(),
                          q_node_->getDoubleValue(),
                          p_node_->getDoubleValue();
     return true;
 }
bool scrimmage::motion::JSBSimModel::step (double time, double dt) virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 216 of file JSBSimModel.cpp.
References scrimmage::Angles::deg2rad(), feet2meters, meters2feet, mps2knts, and scrimmage::Angles::rad2deg().
{
     double desired_velocity = vars_.input(speed_idx_);
     double roll_cmd = vars_.input(roll_idx_);
     // + : roll right, - : roll left
     bank_setpoint_node_->setDoubleValue(roll_cmd);
     if (use_pitch_) {
         double elevator_cmd = vars_.input(alt_or_pitch_idx_);
         // Negate altitude PID from the elevator control
         elevator_cmd -= exec_->GetPropertyValue("ap/elevator_cmd");
         fcs_elevator_cmd_node_->setDoubleValue(elevator_cmd);
         // Try to remove altitude control by putting setpoint to current altitude
         desired_altitude_node_->setDoubleValue(state_->pos()(2) * meters2feet);
     } else {
         double desired_alt = vars_.input(alt_or_pitch_idx_);
         // Set desired altitude (we just need the desired altitude, use the current
         // x,y as placeholders).
         double lat_curr, lon_curr, alt_result;
         parent_->projection()->Reverse(state_->pos()(0), state_->pos()(1), desired_alt,
                                        lat_curr, lon_curr, alt_result);
         desired_altitude_node_->setDoubleValue(alt_result * meters2feet);
     }
     // set desired velocity
     desired_velocity_node_->setDoubleValue(desired_velocity * mps2knts);
     exec_->Setdt(dt);
     exec_->Run();
     // Save state
     if (fg_out_enable_) {
         output_fg_->Print();
     }
     parent_->projection()->Forward(latitude_node_->getDoubleValue(),
                                    longitude_node_->getDoubleValue(),
                                    altitude_node_->getDoubleValue() * feet2meters,
                                    state_->pos()(0), state_->pos()(1), state_->pos()(2));
     angles_from_jsbsim_.set_angle(ang::rad2deg(yaw_node_->getDoubleValue()));
     state_->quat().set(roll_node_->getDoubleValue(),
                       -pitch_node_->getDoubleValue(),
                       ang::deg2rad(angles_from_jsbsim_.angle()));
     state_->vel() << vel_east_node_->getDoubleValue() * feet2meters,
                     vel_north_node_->getDoubleValue() * feet2meters,
                     -vel_down_node_->getDoubleValue() * feet2meters;
     // save what was used as the input
     return true;
 }
void scrimmage::motion::JSBSimModel::teleport (StatePtr & state) virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 272 of file JSBSimModel.cpp.
References meters2feet, and scrimmage::Angles::rad2deg().
{
     double lat, lon, alt;
     parent_->projection()->Reverse(state->pos()(0),
                                    state->pos()(1),
                                    state->pos()(2),
                                    lat, lon, alt);
     JSBSim::FGInitialCondition *ic = exec_->GetIC();
     ic->SetLatitudeDegIC(lat);
     ic->SetLongitudeDegIC(lon);
     ic->SetAltitudeASLFtIC(alt * meters2feet);
     angles_to_jsbsim_.set_angle(ang::rad2deg(state->quat().yaw()));
     ic->SetPsiDegIC(angles_to_jsbsim_.angle());
     exec_->RunIC();
     exec_->Setdt(dt_);
     exec_->Run();
 }
bool scrimmage::motion::JSBSimModel::use_pitch () inline
Definition at line 73 of file JSBSimModel.h.
References use_pitch_.
 { return use_pitch_; }
Member Data Documentation
bool scrimmage::motion::JSBSimModel::use_pitch_ = false protected
Definition at line 117 of file JSBSimModel.h.
Referenced by use_pitch().
int scrimmage::motion::JSBSimModel::speed_idx_ = 0 protected
Definition at line 119 of file JSBSimModel.h.
int scrimmage::motion::JSBSimModel::roll_idx_ = 0 protected
Definition at line 120 of file JSBSimModel.h.
int scrimmage::motion::JSBSimModel::alt_or_pitch_idx_ = 0 protected
Definition at line 121 of file JSBSimModel.h.
bool scrimmage::motion::JSBSimModel::fg_out_enable_ = false protected
Definition at line 123 of file JSBSimModel.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/JSBSimModel/JSBSimModel.h
/root/scrimmage/scrimmage/src/plugins/motion/JSBSimModel/JSBSimModel.cpp