SCRIMMAGE: scrimmage::Battery Class Reference
scrimmage::Battery Class Reference
#include <Battery.h>
Public Member Functions
Battery ()
Battery (const double &min, const double &max, const double &current)
void add_charge (const double &amount)
bool deplete (const double &amount)
bool is_full ()
bool has_charge ()
const double & current_charge ()
double charge_percentage ()
Protected Attributes
double min_charge_ = 0
double max_charge_ = 1
double current_charge_ = 1
Detailed Description
Definition at line 37 of file Battery.h.
Constructor & Destructor Documentation
scrimmage::Battery::Battery () inline
Definition at line 39 of file Battery.h.
References add_charge(), charge_percentage(), current_charge(), deplete(), has_charge(), and is_full().
 {}
scrimmage::Battery::Battery (const double & min, const double & max, const double & current)
Definition at line 38 of file Battery.cpp.
References current_charge_, max_charge_, and min_charge_.
     : min_charge_(min), max_charge_(max), current_charge_(current) {
     if (current_charge_ > max_charge_) {
         current_charge_ = max_charge_;
     }
     if (current_charge_ < min_charge_) {
         current_charge_ = min_charge_;
     }
 }
Member Function Documentation
void scrimmage::Battery::add_charge (const double & amount)
Definition at line 47 of file Battery.cpp.
References current_charge_, and max_charge_.
Referenced by Battery().
{
     current_charge_ += amount;
     if (current_charge_ > max_charge_) {
         current_charge_ = max_charge_;
     }
 }
bool scrimmage::Battery::deplete (const double & amount)
Definition at line 54 of file Battery.cpp.
References current_charge_, and min_charge_.
Referenced by Battery().
{
     current_charge_ -= amount;
     if (current_charge_ < min_charge_) {
         current_charge_ = min_charge_;
         return false;
     }
     return true;
 }
bool scrimmage::Battery::is_full ()
Definition at line 64 of file Battery.cpp.
References current_charge_, and max_charge_.
Referenced by Battery().
                       {
     return std::abs(current_charge_ - max_charge_) <
         std::numeric_limits<double>::epsilon();
 }
bool scrimmage::Battery::has_charge ()
Definition at line 69 of file Battery.cpp.
References current_charge_, and min_charge_.
Referenced by Battery().
{
     return current_charge_ > min_charge_;
 }
const double & scrimmage::Battery::current_charge ()
Definition at line 73 of file Battery.cpp.
References current_charge_.
Referenced by Battery().
{
     return current_charge_;
 }
double scrimmage::Battery::charge_percentage ()
Definition at line 77 of file Battery.cpp.
References current_charge_, max_charge_, and min_charge_.
Referenced by Battery().
{
     return 100.0 * (current_charge_ - min_charge_) / (max_charge_ - min_charge_);
 }
Member Data Documentation
double scrimmage::Battery::min_charge_ = 0 protected
Definition at line 49 of file Battery.h.
Referenced by Battery(), charge_percentage(), deplete(), and has_charge().
double scrimmage::Battery::max_charge_ = 1 protected
Definition at line 50 of file Battery.h.
Referenced by add_charge(), Battery(), charge_percentage(), and is_full().
double scrimmage::Battery::current_charge_ = 1 protected
Definition at line 51 of file Battery.h.
Referenced by add_charge(), Battery(), charge_percentage(), current_charge(), deplete(), has_charge(), and is_full().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/Battery.h
/root/scrimmage/scrimmage/src/common/Battery.cpp