SCRIMMAGE: scrimmage::State Class Reference
scrimmage::State Class Reference
#include <State.h>
Public Member Functions
State ()
State (Eigen::Vector3d _pos, Eigen::Vector3d _vel, Eigen::Vector3d _ang_vel, Quaternion _quat)
virtual ~State ()
Eigen::Vector3d & pos ()
Eigen::Vector3d & vel ()
Eigen::Vector3d & ang_vel ()
const Eigen::Vector3d & pos () const
const Eigen::Vector3d & vel () const
const Eigen::Vector3d & ang_vel () const
Quaternion & quat ()
const Quaternion & quat () const
const Eigen::Vector3d & pos_const () const
const Eigen::Vector3d & vel_const () const
const Eigen::Vector3d & ang_vel_const () const
const Quaternion & quat_const () const
void set_pos (const Eigen::Vector3d &pos)
void set_vel (const Eigen::Vector3d &vel)
void set_ang_vel (const Eigen::Vector3d &ang_vel)
void set_quat (const Quaternion &quat)
bool InFieldOfView (State &other, double fov_width, double fov_height) const
Returns true if other state is in field-of-view.
Eigen::Vector3d rel_pos_local_frame (Eigen::Vector3d &other) const
convert the relative position to the local frame (the output vector will point to the other state)
Eigen::Vector3d pos_offset (double distance, bool offset_with_velocity=true) const
return position offset by trailing_distance in the direction of velocity or orientation
Eigen::Vector3d orient_global_frame () const
returns the vector extending forward
double rel_az (const Eigen::Vector3d &other) const
Eigen::Matrix4d tf_matrix (bool enable_translate=true)
Static Public Member Functions
template<class T , class = std::enable_if_t< !std::is_same<T, scrimmage::State>::value && std::is_base_of<scrimmage::State, T>::value, void>>
static std::shared_ptr< T > cast (std::shared_ptr< scrimmage::State > state)
Downcast a scrimmage::State to a subclassed type, returing nullptr if not successful.
Public Attributes
uint8_t output_precision = 2
Protected Attributes
Eigen::Vector3d pos_
Eigen::Vector3d vel_
Eigen::Vector3d ang_vel_
Quaternion quat_
Friends
std::ostream & operator<< (std::ostream &os, const State &s)
Detailed Description
Definition at line 46 of file State.h.
Constructor & Destructor Documentation
State() [1/2]
scrimmage::State::State ()
Definition at line 42 of file State.cpp.
 : pos_(0, 0, 0), vel_(0, 0, 0), ang_vel_(0, 0, 0) {}
State() [2/2]
scrimmage::State::State (Eigen::Vector3d _pos, Eigen::Vector3d _vel, Eigen::Vector3d _ang_vel, Quaternion _quat)
Definition at line 44 of file State.cpp.
                                                        :
     pos_(_pos), vel_(_vel), ang_vel_(_ang_vel), quat_(_quat) {}
~State()
scrimmage::State::~State () virtual
Definition at line 48 of file State.cpp.
 {}
Member Function Documentation
pos() [1/2]
const Eigen::Vector3d & scrimmage::State::pos ()
Definition at line 50 of file State.cpp.
 {return pos_;}
References pos_.
Referenced by scrimmage::sensor::ContactBlobCamera::contacts_to_bounding_boxes(), InFieldOfView(), scrimmage::autonomy::MOOSNode::OnNewMail(), scrimmage::proto_2_state(), REGISTER_PLUGIN(), scrimmage::set(), set_pos(), scrimmage::sensor::NoisyState::step(), scrimmage::sensor::SimpleINS::step(), scrimmage::sensor::GPS::step(), scrimmage::sensor::ContactBlobCamera::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
vel() [1/2]
const Eigen::Vector3d & scrimmage::State::vel ()
Definition at line 51 of file State.cpp.
 {return vel_;}
References vel_.
Referenced by scrimmage::autonomy::MOOSNode::OnNewMail(), scrimmage::proto_2_state(), scrimmage::set(), set_vel(), scrimmage::sensor::NoisyState::step(), scrimmage::sensor::SimpleINS::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
ang_vel() [1/2]
const Eigen::Vector3d & scrimmage::State::ang_vel ()
Definition at line 52 of file State.cpp.
 {return ang_vel_;}
References ang_vel_.
Referenced by scrimmage::proto_2_state(), scrimmage::set(), and set_ang_vel().
pos() [2/2]
const Eigen::Vector3d& scrimmage::State::pos () const
vel() [2/2]
const Eigen::Vector3d& scrimmage::State::vel () const
ang_vel() [2/2]
const Eigen::Vector3d& scrimmage::State::ang_vel () const
quat() [1/2]
const Quaternion & scrimmage::State::quat ()
Definition at line 53 of file State.cpp.
 {return quat_;}
References quat_.
Referenced by scrimmage::autonomy::MOOSNode::OnNewMail(), scrimmage::operator<<(), scrimmage::proto_2_state(), scrimmage::set(), set_quat(), scrimmage::sensor::NoisyState::step(), scrimmage::sensor::SimpleINS::step(), scrimmage::sensor::ContactBlobCamera::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
quat() [2/2]
const Quaternion& scrimmage::State::quat () const
pos_const()
const Eigen::Vector3d & scrimmage::State::pos_const () const
Definition at line 60 of file State.cpp.
 {return pos_;}
References pos_.
Referenced by scrimmage::set().
vel_const()
const Eigen::Vector3d & scrimmage::State::vel_const () const
Definition at line 61 of file State.cpp.
 {return vel_;}
References vel_.
Referenced by scrimmage::set().
ang_vel_const()
const Eigen::Vector3d & scrimmage::State::ang_vel_const () const
Definition at line 62 of file State.cpp.
 {return ang_vel_;}
References ang_vel_.
Referenced by scrimmage::set().
quat_const()
const Quaternion & scrimmage::State::quat_const () const
Definition at line 63 of file State.cpp.
 {return quat_;}
References quat_.
Referenced by scrimmage::set().
set_pos()
void scrimmage::State::set_pos (const Eigen::Vector3d & pos)
Definition at line 64 of file State.cpp.
 {pos_ = pos;}
References pos(), and pos_.
set_vel()
void scrimmage::State::set_vel (const Eigen::Vector3d & vel)
Definition at line 65 of file State.cpp.
 {vel_ = vel;}
References vel(), and vel_.
set_ang_vel()
void scrimmage::State::set_ang_vel (const Eigen::Vector3d & ang_vel)
Definition at line 66 of file State.cpp.
 {ang_vel_ = ang_vel;}
References ang_vel(), and ang_vel_.
set_quat()
void scrimmage::State::set_quat (const Quaternion & quat)
Definition at line 67 of file State.cpp.
 {quat_ = quat;}
References quat(), and quat_.
InFieldOfView()
bool scrimmage::State::InFieldOfView (State & other, double fov_width, double fov_height) const
Returns true if other state is in field-of-view.
Definition at line 69 of file State.cpp.
{
     Eigen::Vector3d rel_pos = this->rel_pos_local_frame(other.pos());
     double az = atan2(rel_pos(1), rel_pos(0));
     double norm_xy = sqrt(pow(rel_pos(0), 2) + pow(rel_pos(1), 2));
     double el = atan2(rel_pos(2), norm_xy);
     return std::abs(az) < fov_width / 2 && std::abs(el) < fov_height / 2;
 }
References pos(), and rel_pos_local_frame().
rel_pos_local_frame()
Eigen::Vector3d scrimmage::State::rel_pos_local_frame (Eigen::Vector3d & other) const
convert the relative position to the local frame (the output vector will point to the other state)
Definition at line 77 of file State.cpp.
{
     return quat_.rotate_reverse(other - pos_);
 }
References pos_, quat_, and scrimmage::Quaternion::rotate_reverse().
Referenced by scrimmage::sensor::ContactBlobCamera::contacts_to_bounding_boxes(), and InFieldOfView().
pos_offset()
Eigen::Vector3d scrimmage::State::pos_offset (double distance, bool offset_with_velocity = true) const
return position offset by trailing_distance in the direction of velocity or orientation
Definition at line 81 of file State.cpp.
{
     if (offset_with_velocity) {
         return pos_ + vel_.normalized() * distance;
     } else {
         return pos_ + orient_global_frame() * distance;
     }
 }
References orient_global_frame(), pos_, and vel_.
orient_global_frame()
Eigen::Vector3d scrimmage::State::orient_global_frame () const
returns the vector extending forward
Definition at line 89 of file State.cpp.
{
     return quat_.rotate(Eigen::Vector3d::UnitX());
 }
References quat_, and scrimmage::Quaternion::rotate().
Referenced by pos_offset().
rel_az()
double scrimmage::State::rel_az (const Eigen::Vector3d & other) const
Definition at line 93 of file State.cpp.
{
     Eigen::Vector3d diff = other - pos_;
     double az = atan2(diff(1), diff(0));
     return Angles::angle_diff_rad(az, quat_.yaw());
 }
References scrimmage::Angles::angle_diff_rad(), pos_, quat_, and scrimmage::Quaternion::yaw().
tf_matrix()
Eigen::Matrix4d scrimmage::State::tf_matrix (bool enable_translate = true)
Definition at line 99 of file State.cpp.
{
     // Construct 4x4 matrix of the form:
     // |rot|rot|rot| sx |
     // |rot|rot|rot| sy |
     // |rot|rot|rot| sz |
     // | x | y | z |  1 |
     // scales are zero (sx, sy, sz)
     Eigen::Matrix4d mat4 = Eigen::Matrix4d::Identity();
     mat4.block(0, 0, 3, 3) = quat_.toRotationMatrix();
     if (enable_translate) {
         mat4.block(3, 0, 1, 3) = pos_;
     }
     return mat4;
 }
References pos_, and quat_.
cast()
template<class T , class = std::enable_if_t< !std::is_same<T, scrimmage::State>::value && std::is_base_of<scrimmage::State, T>::value, void>> static std::shared_ptr<T> scrimmage::State::cast (std::shared_ptr< scrimmage::State > state) inline static
Downcast a scrimmage::State to a subclassed type, returing nullptr if not successful.
Definition at line 105 of file State.h.
{
         std::shared_ptr<T> result = std::dynamic_pointer_cast<T>(state);
         try {
             if (typeid(*result).name()) {
                 // Do nothing. The if-statement is to remove the unused variable
                 // warning. typeid will throw an exception if the underlying object
                 // is only of the base-type and not the subclassed type.
             }
         } catch (const std::bad_typeid &e) {
             return nullptr;
         }
         return std::shared_ptr<T>(result);
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const State & s) friend
Definition at line 115 of file State.cpp.
{
     const Quaternion &q = s.quat();
     os << "(" << eigen_str(s.pos_, s.output_precision)
         << "), (" << eigen_str(s.vel_, s.output_precision)
         << "), (" << eigen_str(s.ang_vel_, s.output_precision)
         << "), ("
         << std::setprecision(s.output_precision) << q.roll() << ", "
         << std::setprecision(s.output_precision) << q.pitch() << ", "
         << std::setprecision(s.output_precision) << q.yaw() << ")";
     return os;
 }
Member Data Documentation
output_precision
uint8_t scrimmage::State::output_precision = 2
Definition at line 96 of file State.h.
Referenced by scrimmage::operator<<().
pos_
Eigen::Vector3d scrimmage::State::pos_ protected
Definition at line 121 of file State.h.
Referenced by scrimmage::operator<<(), pos(), pos_const(), pos_offset(), rel_az(), rel_pos_local_frame(), set_pos(), and tf_matrix().
vel_
Eigen::Vector3d scrimmage::State::vel_ protected
Definition at line 122 of file State.h.
Referenced by scrimmage::operator<<(), pos_offset(), set_vel(), vel(), and vel_const().
ang_vel_
Eigen::Vector3d scrimmage::State::ang_vel_ protected
Definition at line 123 of file State.h.
Referenced by ang_vel(), ang_vel_const(), scrimmage::operator<<(), and set_ang_vel().
quat_
Quaternion scrimmage::State::quat_ protected
Definition at line 124 of file State.h.
Referenced by orient_global_frame(), quat(), quat_const(), rel_az(), rel_pos_local_frame(), set_quat(), and tf_matrix().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/math/State.h
/root/scrimmage/scrimmage/src/math/State.cpp