SCRIMMAGE: scrimmage::metrics::OpenAIRewards Class Reference
scrimmage::metrics::OpenAIRewards Class Reference
#include <OpenAIRewards.h>
Public Member Functions
OpenAIRewards ()
void init (std::map< std::string, std::string > &params) override
bool step_metrics (double, double) override
void print_team_summaries () override
void calc_team_scores () override
Public Member Functions inherited from scrimmage::Metrics
Metrics ()
virtual ~Metrics ()
virtual void init ()
virtual std::map< int, std::map< std::string, double > > & team_metrics ()
virtual std::list< std::string > & headers ()
virtual std::map< int, double > & team_scores ()
bool get_print_team_summary ()
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
std::map< std::string, std::string > params_
std::map< size_t, double > rewards_
Protected Attributes inherited from scrimmage::Metrics
std::string weights_file_
std::map< int, std::map< std::string, double > > team_metrics_
std::map< int, double > team_scores_
std::list< std::string > headers_
bool print_team_summary_ = true
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 44 of file OpenAIRewards.h.
Constructor & Destructor Documentation
OpenAIRewards()
scrimmage::metrics::OpenAIRewards::OpenAIRewards ()
Referenced by REGISTER_PLUGIN().
Member Function Documentation
init()
void scrimmage::metrics::OpenAIRewards::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Metrics.
step_metrics()
bool scrimmage::metrics::OpenAIRewards::step_metrics (double , double) inline override virtual
Reimplemented from scrimmage::Metrics.
Definition at line 48 of file OpenAIRewards.h.
 {return true;}
print_team_summaries()
void scrimmage::metrics::OpenAIRewards::print_team_summaries () override virtual
Reimplemented from scrimmage::Metrics.
Referenced by REGISTER_PLUGIN().
calc_team_scores()
void scrimmage::metrics::OpenAIRewards::calc_team_scores () override virtual
Reimplemented from scrimmage::Metrics.
Referenced by REGISTER_PLUGIN().
Member Data Documentation
params_
std::map<std::string, std::string> scrimmage::metrics::OpenAIRewards::params_ protected
Definition at line 53 of file OpenAIRewards.h.
rewards_
std::map<size_t, double> scrimmage::metrics::OpenAIRewards::rewards_ protected
Definition at line 54 of file OpenAIRewards.h.
Referenced by REGISTER_PLUGIN().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/metrics/OpenAIRewards/OpenAIRewards.h