SCRIMMAGE: scrimmage::motion::DoubleIntegrator Class Reference
scrimmage::motion::DoubleIntegrator Class Reference
#include <DoubleIntegrator.h>
Public Member Functions
DoubleIntegrator ()
bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params) override
bool step (double t, double dt) override
void model (const vector_t &x, vector_t &dxdt, double t) override
void teleport (scrimmage::StatePtr &state) override
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
double update_dvdt (double vel, double max_vel, double acc)
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
Protected Attributes
double max_vel_ = std::numeric_limits<double>::infinity()
double max_acc_ = std::numeric_limits<double>::infinity()
double max_yaw_vel_ = std::numeric_limits<double>::infinity()
double max_yaw_acc_ = std::numeric_limits<double>::infinity()
bool motion_model_sets_yaw_ = true
bool sim_copter_orientation_ = false
double sim_copter_max_roll_ = 1.0
double sim_copter_max_pitch_ = 1.0
int acc_x_idx_ = 0
int acc_y_idx_ = 0
int acc_z_idx_ = 0
int turn_rate_idx_ = 0
Eigen::Vector3d acc_vec_
double turn_rate_ = 0
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 47 of file DoubleIntegrator.h.
Constructor & Destructor Documentation
scrimmage::motion::DoubleIntegrator::DoubleIntegrator ()
Definition at line 53 of file DoubleIntegrator.cpp.
References scrimmage::MotionModel::x_.
                                    : motion_model_sets_yaw_(false) {
     x_.resize(STATE_SIZE);
 }
Member Function Documentation
bool scrimmage::motion::DoubleIntegrator::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 57 of file DoubleIntegrator.cpp.
References acc_x_idx_, acc_y_idx_, acc_z_idx_, scrimmage::VariableIO::acceleration_x, scrimmage::VariableIO::acceleration_y, scrimmage::VariableIO::acceleration_z, scrimmage::VariableIO::declare(), scrimmage::Angles::deg2rad(), scrimmage::VariableIO::In, max_acc_, max_vel_, max_yaw_acc_, max_yaw_vel_, motion_model_sets_yaw_, sim_copter_max_pitch_, sim_copter_max_roll_, sim_copter_orientation_, scrimmage::MotionModel::state_, scrimmage::str2bool(), scrimmage::VariableIO::turn_rate, turn_rate_idx_, scrimmage::EntityPlugin::vars_, scrimmage::motion::VX, scrimmage::motion::VY, scrimmage::motion::VZ, scrimmage::motion::X, scrimmage::MotionModel::x_, scrimmage::motion::Y, scrimmage::motion::YAW, scrimmage::motion::YAW_DOT, and scrimmage::motion::Z.
{
     max_vel_ = std::stod(params.at("max_vel"));
     max_acc_ = std::stod(params.at("max_acc"));
     motion_model_sets_yaw_ = sc::str2bool(params.at("motion_model_sets_yaw"));
     sim_copter_orientation_ = sc::get<bool>("sim_copter_orientation", params, false);
     sim_copter_max_roll_ = sc::Angles::deg2rad(sc::get<double>("sim_copter_max_roll", params, 30));
     sim_copter_max_pitch_ = sc::Angles::deg2rad(sc::get<double>("sim_copter_max_pitch", params, 30));
     max_yaw_vel_ = sc::get<double>("max_yaw_vel", params, 1.0);
     max_yaw_acc_ = sc::get<double>("max_yaw_acc", params, 1.0);
     x_[X] = state_->pos()(0);
     x_[Y] = state_->pos()(1);
     x_[Z] = state_->pos()(2);
     x_[YAW] = state_->quat().yaw();
     x_[VX] = clamp(state_->vel()(0), -max_vel_, max_vel_);
     x_[VY] = clamp(state_->vel()(1), -max_vel_, max_vel_);
     x_[VZ] = clamp(state_->vel()(2), -max_vel_, max_vel_);
     x_[YAW_DOT] = 0;
     state_->pos() << x_[X], x_[Y], x_[Z];
     state_->quat().set(0, 0, x_[YAW]);
     acc_x_idx_ = vars_.declare(VariableIO::Type::acceleration_x, VariableIO::Direction::In);
     acc_y_idx_ = vars_.declare(VariableIO::Type::acceleration_y, VariableIO::Direction::In);
     acc_z_idx_ = vars_.declare(VariableIO::Type::acceleration_z, VariableIO::Direction::In);
     turn_rate_idx_ = vars_.declare(VariableIO::Type::turn_rate, VariableIO::Direction::In);
     return true;
 }
bool scrimmage::motion::DoubleIntegrator::step (double t, double dt) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 89 of file DoubleIntegrator.cpp.
References acc_vec_, acc_x_idx_, acc_y_idx_, acc_z_idx_, scrimmage::VariableIO::input(), max_acc_, max_vel_, max_yaw_acc_, motion_model_sets_yaw_, scrimmage::MotionModel::ode_step(), sim_copter_max_pitch_, sim_copter_max_roll_, sim_copter_orientation_, scrimmage::MotionModel::state_, turn_rate_, turn_rate_idx_, scrimmage::EntityPlugin::vars_, scrimmage::motion::VX, scrimmage::motion::VY, scrimmage::motion::VZ, scrimmage::motion::X, scrimmage::MotionModel::x_, scrimmage::motion::Y, scrimmage::motion::YAW, and scrimmage::motion::Z.
{
     acc_vec_(0) = vars_.input(acc_x_idx_);
     acc_vec_(1) = vars_.input(acc_y_idx_);
     acc_vec_(2) = vars_.input(acc_z_idx_);
     // Maintain direction when clamping acceleration
     if (acc_vec_.norm() > max_acc_) {
         acc_vec_ = acc_vec_.normalized() * max_acc_;
     }
     turn_rate_ = clamp(vars_.input(turn_rate_idx_), -max_yaw_acc_, max_yaw_acc_);
     ode_step(dt);
     // Maintain direction when clamping velocity
     Eigen::Vector3d vel_;
     vel_ << x_[VX], x_[VY], x_[VZ];
     if (vel_.norm() > max_vel_) {
         vel_ = vel_.normalized() * max_vel_;
     }
     x_[VX] = vel_[0];
     x_[VY] = vel_[1];
     x_[VZ] = vel_[2];
     state_->pos() << x_[X], x_[Y], x_[Z];
     state_->vel() << x_[VX], x_[VY], x_[VZ];
     if (motion_model_sets_yaw_) {
         if (x_[VY] != 0 || x_[VX] != 0) {
             state_->quat().set(0, 0, atan2(x_[VY], x_[VX]));
         }
     } else if (sim_copter_orientation_) {
         // Get global velocity vector into local coordinate frame
         Eigen::Vector3d vel_global(x_[VX], x_[VY], x_[VZ]);
         Eigen::Vector3d vel_local = state_->quat().rotate_reverse(vel_global);
         double pitch = vel_local(0) / max_vel_ * sim_copter_max_pitch_;
         double roll = vel_local(1) / max_vel_ * sim_copter_max_roll_;
         state_->quat().set(-roll, pitch, x_[YAW]);
     } else {
         state_->quat().set(0, 0, turn_rate_);
     }
     return true;
 }
void scrimmage::motion::DoubleIntegrator::model (const vector_t & x, vector_t & dxdt, double t) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 141 of file DoubleIntegrator.cpp.
References acc_vec_, max_vel_, max_yaw_vel_, turn_rate_, update_dvdt(), scrimmage::motion::VX, scrimmage::motion::VY, scrimmage::motion::VZ, scrimmage::motion::X, scrimmage::MotionModel::x_, scrimmage::motion::Y, scrimmage::motion::YAW, scrimmage::motion::YAW_DOT, and scrimmage::motion::Z.
{
     dxdt[X] = clamp(x_[VX], -max_vel_, max_vel_);
     dxdt[Y] = clamp(x_[VY], -max_vel_, max_vel_);
     dxdt[Z] = clamp(x_[VZ], -max_vel_, max_vel_);
     dxdt[YAW] = clamp(turn_rate_, -max_yaw_vel_, max_yaw_vel_);
     dxdt[VX] = update_dvdt(x[VX], max_vel_, acc_vec_(0));
     dxdt[VY] = update_dvdt(x[VY], max_vel_, acc_vec_(1));
     dxdt[VZ] = update_dvdt(x[VZ], max_vel_, acc_vec_(2));
     dxdt[YAW_DOT] = 0;
 }
void scrimmage::motion::DoubleIntegrator::teleport (scrimmage::StatePtr & state) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 153 of file DoubleIntegrator.cpp.
References scrimmage::motion::VX, scrimmage::motion::VY, scrimmage::motion::VZ, scrimmage::motion::X, scrimmage::MotionModel::x_, scrimmage::motion::Y, scrimmage::motion::YAW, scrimmage::motion::YAW_DOT, and scrimmage::motion::Z.
{
     x_[X] = state->pos()[0];
     x_[Y] = state->pos()[1];
     x_[Z] = state->pos()[2];
     x_[VX] = state->vel()[0];
     x_[VY] = state->vel()[1];
     x_[VZ] = state->vel()[2];
     x_[YAW] = state->quat().yaw();
     x_[YAW_DOT] = 0;
 }
double scrimmage::motion::DoubleIntegrator::update_dvdt (double vel, double max_vel, double acc) protected
Definition at line 131 of file DoubleIntegrator.cpp.
Referenced by model().
{
     if (vel >= max_vel && acc > 0) {
         return 0;
     } else if (vel <= -max_vel && acc < 0) {
         return 0;
     } else {
         return acc;
     }
 }
Member Data Documentation
double scrimmage::motion::DoubleIntegrator::max_vel_ = std::numeric_limits<double>::infinity() protected
Definition at line 62 of file DoubleIntegrator.h.
Referenced by init(), model(), and step().
double scrimmage::motion::DoubleIntegrator::max_acc_ = std::numeric_limits<double>::infinity() protected
Definition at line 63 of file DoubleIntegrator.h.
Referenced by init(), and step().
double scrimmage::motion::DoubleIntegrator::max_yaw_vel_ = std::numeric_limits<double>::infinity() protected
Definition at line 64 of file DoubleIntegrator.h.
Referenced by init(), and model().
double scrimmage::motion::DoubleIntegrator::max_yaw_acc_ = std::numeric_limits<double>::infinity() protected
Definition at line 65 of file DoubleIntegrator.h.
Referenced by init(), and step().
bool scrimmage::motion::DoubleIntegrator::motion_model_sets_yaw_ = true protected
Definition at line 66 of file DoubleIntegrator.h.
Referenced by init(), and step().
bool scrimmage::motion::DoubleIntegrator::sim_copter_orientation_ = false protected
Definition at line 67 of file DoubleIntegrator.h.
Referenced by init(), and step().
double scrimmage::motion::DoubleIntegrator::sim_copter_max_roll_ = 1.0 protected
Definition at line 68 of file DoubleIntegrator.h.
Referenced by init(), and step().
double scrimmage::motion::DoubleIntegrator::sim_copter_max_pitch_ = 1.0 protected
Definition at line 69 of file DoubleIntegrator.h.
Referenced by init(), and step().
int scrimmage::motion::DoubleIntegrator::acc_x_idx_ = 0 protected
Definition at line 71 of file DoubleIntegrator.h.
Referenced by init(), and step().
int scrimmage::motion::DoubleIntegrator::acc_y_idx_ = 0 protected
Definition at line 72 of file DoubleIntegrator.h.
Referenced by init(), and step().
int scrimmage::motion::DoubleIntegrator::acc_z_idx_ = 0 protected
Definition at line 73 of file DoubleIntegrator.h.
Referenced by init(), and step().
int scrimmage::motion::DoubleIntegrator::turn_rate_idx_ = 0 protected
Definition at line 74 of file DoubleIntegrator.h.
Referenced by init(), and step().
Eigen::Vector3d scrimmage::motion::DoubleIntegrator::acc_vec_ protected
Definition at line 76 of file DoubleIntegrator.h.
Referenced by model(), and step().
double scrimmage::motion::DoubleIntegrator::turn_rate_ = 0 protected
Definition at line 77 of file DoubleIntegrator.h.
Referenced by model(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/DoubleIntegrator/DoubleIntegrator.h
/root/scrimmage/scrimmage/src/plugins/motion/DoubleIntegrator/DoubleIntegrator.cpp