SCRIMMAGE: scrimmage::Quaternion Class Reference
scrimmage::Quaternion Class Reference
#include <Quaternion.h>
Public Member Functions
constructors
Quaternion ()
set the quaternion to rotate an object around the given vector at given angle
Quaternion (const Quaternion &other)
Quaternion (const Eigen::Quaternion< double, Eigen::DontAlign > &other)
Quaternion & operator= (const Quaternion &other)
Quaternion & operator= (const Eigen::Quaternion< double, Eigen::DontAlign > &other)
Quaternion (const double &w, const double &x, const double &y, const double &z)
Quaternion (double &w, double &x, double &y, double &z)
Quaternion (const Eigen::Vector3d &vector, double angle_radians)
Quaternion (double roll, double pitch, double yaw)
set quaternion from euler angles
void set (double w_coeff, double x_coeff, double y_coeff, double z_coeff)
setters
void set (const Eigen::Vector3d &vector, double angle_radians)
set the quaternion to rotate an object around the given vector at given angle
void set (double roll, double pitch, double yaw)
set quaternion from euler angles
utilities
double roll () const
return euler angle roll
double pitch () const
return euler angle pitch
double yaw () const
return euler angle yaw
double rotation_angle () const
return the angle an input vector would be rotated by this quaternion
Eigen::Vector3d rotate (const Eigen::Vector3d &vec) const
rotate the input vector around the vec axis by an angle given by RotationAngle(). This can also be used to convert a vector in the local frame to a vector in the global frame.
Eigen::Vector3d rotate_reverse (const Eigen::Vector3d &vec) const
rotate the input vector around the vec axis by an angle given by RotationAngle(). This can also be used to convert a vector in the local frame to a vector in the global frame.
Public Attributes
uint8_t output_precision = 2
Friends
std::ostream & operator<< (std::ostream &os, const Quaternion &q)
Detailed Description
Definition at line 41 of file Quaternion.h.
Constructor & Destructor Documentation
Quaternion() [1/7]
scrimmage::Quaternion::Quaternion ()
set the quaternion to rotate an object around the given vector at given angle
Definition at line 40 of file Quaternion.cpp.
 : Eigen::Quaternion<double, Eigen::DontAlign>(1, 0, 0, 0) {}
Quaternion() [2/7]
scrimmage::Quaternion::Quaternion (const Quaternion & other)
Definition at line 42 of file Quaternion.cpp.
 : Eigen::Quaternion<double, Eigen::DontAlign>(other) {}
Quaternion() [3/7]
scrimmage::Quaternion::Quaternion (const Eigen::Quaternion< double, Eigen::DontAlign > & other) explicit
Definition at line 44 of file Quaternion.cpp.
 : Eigen::Quaternion<double, Eigen::DontAlign>(other) {}
Quaternion() [4/7]
scrimmage::Quaternion::Quaternion (const double & w, const double & x, const double & y, const double & z)
Definition at line 46 of file Quaternion.cpp.
     : Eigen::Quaternion<double, Eigen::DontAlign>(w, x, y, z) {}
Quaternion() [5/7]
scrimmage::Quaternion::Quaternion (double & w, double & x, double & y, double & z)
Definition at line 49 of file Quaternion.cpp.
     : Eigen::Quaternion<double, Eigen::DontAlign>(w, x, y, z) {}
Quaternion() [6/7]
scrimmage::Quaternion::Quaternion (const Eigen::Vector3d & vector, double angle_radians)
Definition at line 52 of file Quaternion.cpp.
{
     set(vector, angle_radians);
 }
References set().
Quaternion() [7/7]
scrimmage::Quaternion::Quaternion (double roll, double pitch, double yaw)
set quaternion from euler angles
Definition at line 56 of file Quaternion.cpp.
{
     set(roll, pitch, yaw);
 }
References pitch(), roll(), set(), and yaw().
Member Function Documentation
operator=() [1/2]
Quaternion & scrimmage::Quaternion::operator= (const Quaternion & other)
Definition at line 60 of file Quaternion.cpp.
{
     if (this != &other) {
         set(other.w(), other.x(), other.y(), other.z());
     }
     return *this;
 }
References set().
operator=() [2/2]
Quaternion & scrimmage::Quaternion::operator= (const Eigen::Quaternion< double, Eigen::DontAlign > & other)
Definition at line 67 of file Quaternion.cpp.
{
     if (this != &other) {
         set(other.w(), other.x(), other.y(), other.z());
     }
     return *this;
 }
References set().
set() [1/3]
void scrimmage::Quaternion::set (double w_coeff, double x_coeff, double y_coeff, double z_coeff)
Definition at line 74 of file Quaternion.cpp.
{
     w() = w_coeff;
     x() = x_coeff;
     y() = y_coeff;
     z() = z_coeff;
 }
Referenced by scrimmage::motion::FixedWing6DOF::init(), scrimmage::autonomy::MOOSNode::OnNewMail(), operator=(), Quaternion(), REGISTER_PLUGIN(), scrimmage::set(), scrimmage::motion::FixedWing6DOF::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
set() [2/3]
void scrimmage::Quaternion::set (const Eigen::Vector3d & vector, double angle_radians)
set the quaternion to rotate an object around the given vector at given angle
Definition at line 81 of file Quaternion.cpp.
{
     w() = cos(angle_radians / 2.0);
     Eigen::Vector3d unit_vec = vector.normalized() * sin(angle_radians / 2.0);
     x() = unit_vec.x();
     y() = unit_vec.y();
     z() = unit_vec.z();
 }
set() [3/3]
void scrimmage::Quaternion::set (double roll, double pitch, double yaw)
set quaternion from euler angles
Definition at line 89 of file Quaternion.cpp.
{
     double sr = sin(roll / 2);
     double cr = cos(roll / 2);
     double sy = sin(yaw / 2);
     double cy = cos(yaw / 2);
     double sp = sin(pitch / 2);
     double cp = cos(pitch / 2);
     w() = cr * cp * cy + sr * sp * sy;
     x() = sr * cp * cy - cr * sp * sy;
     y() = cr * sp * cy + sr * cp * sy;
     z() = cr * cp * sy - sr * sp * cy;
 }
References pitch(), roll(), and yaw().
roll()
double scrimmage::Quaternion::roll () const
return euler angle roll
Definition at line 103 of file Quaternion.cpp.
{
     return atan2(2 * (w() * x() + y() * z()),
                  1 - 2 * (pow(x(), 2) + pow(y(), 2)));
 }
Referenced by scrimmage::motion::SimpleAircraft::init(), scrimmage::motion::JSBSimControl::init(), scrimmage::motion::FixedWing6DOF::init(), scrimmage::operator<<(), scrimmage::Updater::quat_2_transform(), Quaternion(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), set(), scrimmage::SimControl::start(), scrimmage::sensor::ContactBlobCamera::step(), scrimmage::motion::FixedWing6DOF::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
pitch()
double scrimmage::Quaternion::pitch () const
return euler angle pitch
Definition at line 108 of file Quaternion.cpp.
{
     return asin(2 * (w() * y() - z() * x()));
 }
Referenced by scrimmage::motion::SimpleAircraft::init(), scrimmage::motion::JSBSimControl::init(), scrimmage::motion::FixedWing6DOF::init(), scrimmage::operator<<(), scrimmage::Updater::quat_2_transform(), Quaternion(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), set(), scrimmage::SimControl::start(), scrimmage::sensor::ContactBlobCamera::step(), scrimmage::motion::FixedWing6DOF::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
yaw()
double scrimmage::Quaternion::yaw () const
return euler angle yaw
Definition at line 112 of file Quaternion.cpp.
{
     return atan2(2 * (w() * z() + x() * y()),
                  1 - 2 * (pow(y(), 2) + pow(z(), 2)));
 }
Referenced by scrimmage::motion::SimpleAircraft::init(), scrimmage::motion::JSBSimControl::init(), scrimmage::motion::FixedWing6DOF::init(), scrimmage::operator<<(), scrimmage::Updater::quat_2_transform(), Quaternion(), REGISTER_PLUGIN(), scrimmage::State::rel_az(), scrimmage::FrameUpdateClient::send_frame(), set(), scrimmage::SimControl::start(), scrimmage::sensor::ContactBlobCamera::step(), scrimmage::motion::FixedWing6DOF::step(), scrimmage::autonomy::MOOSAutonomy::step_autonomy(), and scrimmage::Updater::update_text_display().
rotation_angle()
double scrimmage::Quaternion::rotation_angle () const
return the angle an input vector would be rotated by this quaternion
Definition at line 117 of file Quaternion.cpp.
{
     return 2 * acos(w());
 }
rotate()
Eigen::Vector3d scrimmage::Quaternion::rotate (const Eigen::Vector3d & vec) const
rotate the input vector around the vec axis by an angle given by RotationAngle(). This can also be used to convert a vector in the local frame to a vector in the global frame.
Definition at line 121 of file Quaternion.cpp.
{
     Eigen::Quaternion<double, Eigen::DontAlign> pure_quat(0, vec.x(), vec.y(), vec.z());
     return (*this * pure_quat * inverse()).vec();
 }
Referenced by scrimmage::Updater::draw_arc(), scrimmage::Updater::draw_plane(), scrimmage::interaction::BulletCollision::get_ray_tracing(), scrimmage::interaction::BulletCollision::init(), scrimmage::motion::FixedWing6DOF::model(), scrimmage::State::orient_global_frame(), REGISTER_PLUGIN(), scrimmage::motion::FixedWing6DOF::step(), and scrimmage::Updater::update_camera().
rotate_reverse()
Eigen::Vector3d scrimmage::Quaternion::rotate_reverse (const Eigen::Vector3d & vec) const
rotate the input vector around the vec axis by an angle given by RotationAngle(). This can also be used to convert a vector in the local frame to a vector in the global frame.
Definition at line 126 of file Quaternion.cpp.
{
     Eigen::Quaternion<double, Eigen::DontAlign> pure_quat(0, vec.x(), vec.y(), vec.z());
     return (inverse() * pure_quat * *this).vec();
 }
Referenced by scrimmage::motion::FixedWing6DOF::init(), scrimmage::motion::FixedWing6DOF::model(), REGISTER_PLUGIN(), scrimmage::State::rel_pos_local_frame(), scrimmage::motion::DubinsAirplane3D::step(), scrimmage::motion::Unicycle3D::step(), and scrimmage::motion::FixedWing6DOF::step().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Quaternion & q) friend
Definition at line 131 of file Quaternion.cpp.
{
     os << "w: " << std::setprecision(q.output_precision) << q.w()
        << ", x: " << std::setprecision(q.output_precision) << q.x()
        << ", y: " << std::setprecision(q.output_precision) << q.y()
        << ", z: " << std::setprecision(q.output_precision) << q.z();
     return os;
 }
Member Data Documentation
output_precision
uint8_t scrimmage::Quaternion::output_precision = 2
Definition at line 111 of file Quaternion.h.
Referenced by scrimmage::operator<<().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/math/Quaternion.h
/root/scrimmage/scrimmage/src/math/Quaternion.cpp