SCRIMMAGE: scrimmage::interaction::TerrainMap Class Reference
scrimmage::interaction::TerrainMap Class Reference
#include <TerrainMap.h>
Classes
class Node
Public Types
enum Technique { Technique::RANDOM_WALK, Technique::LINEAR, Technique::LINEAR_WALK }
Public Member Functions
TerrainMap ()
TerrainMap (std::shared_ptr< std::normal_distribution< double >> rng, std::shared_ptr< std::default_random_engine > gener, const Technique &technique, const Eigen::Vector3d &center, const double &x_length, const double &y_length, const double &x_resolution, const double &y_resolution, const double &z_min, const double &z_max, const Eigen::Vector3d &color)
TerrainMap (const scrimmage_msgs::Terrain &terrain)
scrimmage::ShapePtr shape ()
scrimmage_msgs::Terrain proto ()
boost::optional< double > height_at (const double &x, const double &y)
Protected Member Functions
bool generate ()
bool generate_random_walk ()
bool generate_linear ()
bool generate_linear_walk ()
void center_height_adjust ()
void clamp_height ()
double get_neighbor_avg (const int &row, const int &col)
Protected Attributes
std::shared_ptr< std::normal_distribution< double > > rng_
std::shared_ptr< std::default_random_engine > gener_
Technique technique_ = Technique::RANDOM_WALK
Eigen::Vector3d center_ = Eigen::Vector3d::Zero()
double x_length_ = 10
double y_length_ = 10
double x_resolution_ = 1.0
double y_resolution_ = 1.0
double z_min_ = -std::numeric_limits<double>::infinity()
double z_max_ = +std::numeric_limits<double>::infinity()
Eigen::Vector3d color_ = Eigen::Vector3d::Zero()
unsigned int num_x_cols_ = x_length_ / x_resolution_
unsigned int num_y_rows_ = y_length_ / y_resolution_
std::vector< std::vector< Node > > grid_
Detailed Description
Definition at line 52 of file TerrainMap.h.
Member Enumeration Documentation
Technique
enum scrimmage::interaction::TerrainMap::Technique strong
Enumerator
RANDOM_WALK
LINEAR
LINEAR_WALK
Definition at line 54 of file TerrainMap.h.
 { RANDOM_WALK, LINEAR, LINEAR_WALK };
Constructor & Destructor Documentation
TerrainMap() [1/3]
scrimmage::interaction::TerrainMap::TerrainMap ()
Definition at line 49 of file TerrainMap.cpp.
 {}
TerrainMap() [2/3]
scrimmage::interaction::TerrainMap::TerrainMap (std::shared_ptr< std::normal_distribution< double >> rng, std::shared_ptr< std::default_random_engine > gener, const Technique & technique, const Eigen::Vector3d & center, const double & x_length, const double & y_length, const double & x_resolution, const double & y_resolution, const double & z_min, const double & z_max, const Eigen::Vector3d & color)
Definition at line 51 of file TerrainMap.cpp.
                                                    :
         rng_(rng), gener_(gener), technique_(technique), center_(center),
         x_length_(x_length),
         y_length_(y_length),
         x_resolution_(x_resolution),
         y_resolution_(y_resolution), z_min_(z_min), z_max_(z_max),
         color_(color),
         num_x_cols_(x_length_ / x_resolution_),
         num_y_rows_(y_length_ / y_resolution_),
         grid_(std::vector<std::vector<Node>>(num_y_rows_, std::vector<Node>(num_x_cols_))) {
     generate();
 }
References generate().
TerrainMap() [3/3]
scrimmage::interaction::TerrainMap::TerrainMap (const scrimmage_msgs::Terrain & terrain) explicit
Definition at line 71 of file TerrainMap.cpp.
                                                            :
         rng_(nullptr), gener_(nullptr), center_(Eigen::Vector3d(0, 0, 0)),
         x_length_(terrain.x_length()), y_length_(terrain.y_length()),
         x_resolution_(terrain.x_resolution()),
         y_resolution_(terrain.y_resolution()), z_min_(terrain.z_min()),
         z_max_(terrain.z_max()), num_x_cols_(x_length_ / x_resolution_),
         num_y_rows_(y_length_ / y_resolution_),
         grid_(std::vector<std::vector<Node>>(num_y_rows_, std::vector<Node>(num_x_cols_))) {
     sc::set(center_, terrain.center());
     // Populate the grid
     for (int r = 0; r < terrain.map().row_size(); ++r) {
         for (int c = 0; c < terrain.map().row(r).col_size(); ++c) {
             grid_[r][c].height = terrain.map().row(r).col(c);
             grid_[r][c].is_set = true;
         }
     }
 }
References center_, grid_, and scrimmage::set().
Member Function Documentation
shape()
scrimmage::ShapePtr scrimmage::interaction::TerrainMap::shape ()
Definition at line 216 of file TerrainMap.cpp.
{
     // Create the shape associated with this terrain
     sc::ShapePtr shape = std::make_shared<sp::Shape>();
     shape->set_persistent(true);
     sc::set(shape->mutable_color(), color_(0), color_(1), color_(2));
     shape->mutable_pointcloud()->set_size(3);
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         double y = center_(1)-y_length_ / 2.0 + row * y_resolution_;
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             sp::Vector3d *p = shape->mutable_pointcloud()->add_point();
             double x = center_(0)-x_length_ / 2.0 + col * x_resolution_;
             sc::set(p, x, y, grid_[row][col].height);
         }
     }
     return shape;
 }
References center_, color_, grid_, num_x_cols_, num_y_rows_, scrimmage::set(), x_length_, x_resolution_, y_length_, and y_resolution_.
Referenced by REGISTER_PLUGIN().
proto()
scrimmage_msgs::Terrain scrimmage::interaction::TerrainMap::proto ()
Definition at line 234 of file TerrainMap.cpp.
{
     scrimmage_msgs::Terrain terrain;
     sc::set(terrain.mutable_center(), center_);
     terrain.set_x_length(x_length_);
     terrain.set_y_length(y_length_);
     terrain.set_x_resolution(x_resolution_);
     terrain.set_y_resolution(y_resolution_);
     terrain.set_z_min(z_min_);
     terrain.set_z_max(z_max_);
     for (unsigned int r = 0; r < num_y_rows_; ++r) {
         scrimmage_msgs::Array1D *row = terrain.mutable_map()->add_row();
         for (unsigned int c = 0; c < num_x_cols_; ++c) {
             row->add_col(grid_[r][c].height);
         }
     }
     return terrain;
 }
References center_, grid_, num_x_cols_, num_y_rows_, scrimmage::set(), x_length_, x_resolution_, y_length_, y_resolution_, z_max_, and z_min_.
Referenced by REGISTER_PLUGIN().
height_at()
boost::optional< double > scrimmage::interaction::TerrainMap::height_at (const double & x, const double & y)
Definition at line 254 of file TerrainMap.cpp.
{
     int row = std::floor((y + y_length_/2.0 - center_(1)) / y_resolution_);
     int col = std::floor((x + x_length_/2.0 - center_(0)) / x_resolution_);
     if (row < 0 || row >= static_cast<int>(num_y_rows_) ||
         col < 0 || col >= static_cast<int>(num_x_cols_) ||
         not grid_[row][col].is_set) {
         return boost::optional<double>{};
     }
     return grid_[row][col].height;
 }
References center_, grid_, num_x_cols_, num_y_rows_, x_length_, x_resolution_, y_length_, and y_resolution_.
generate()
bool scrimmage::interaction::TerrainMap::generate () protected
Definition at line 90 of file TerrainMap.cpp.
{
     if (gener_ == nullptr || rng_ == nullptr) {
         cout << "default_random_enginer is nullptr" << endl;
         return false;
     }
     if (technique_ == Technique::LINEAR) {
         return generate_linear();
     } else if (technique_ == Technique::LINEAR_WALK) {
         return generate_linear_walk();
     }
     return generate_random_walk();
 }
References gener_, generate_linear(), generate_linear_walk(), generate_random_walk(), LINEAR, LINEAR_WALK, rng_, and technique_.
Referenced by TerrainMap().
generate_random_walk()
bool scrimmage::interaction::TerrainMap::generate_random_walk () protected
Definition at line 125 of file TerrainMap.cpp.
{
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             // If this node is already set, skip (continue)
             if (grid_[row][col].is_set) {
                 continue;
             }
             // Get the average of the neighbors that are already set
             double height_avg = get_neighbor_avg(row, col);
             grid_[row][col].height = height_avg + (*rng_)(*gener_);
             grid_[row][col].is_set = true;
         }
     }
     center_height_adjust();
     clamp_height();
     return true;
 }
References center_height_adjust(), clamp_height(), get_neighbor_avg(), grid_, num_x_cols_, and num_y_rows_.
Referenced by generate().
generate_linear()
bool scrimmage::interaction::TerrainMap::generate_linear () protected
Definition at line 104 of file TerrainMap.cpp.
{
     // Force the altitude center to be at the midpoint between z_max and z_min
     center_(2) = (z_max_ + z_min_) / 2.0;
     // Initialize the map, such that row 0 is at z_min and the last row is at
     // z_max, with a linear interpolation across the rows. Also, add noise to
     // each height value.
     double z_step = (z_max_ - z_min_) / num_y_rows_;
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         double height = z_step * row;
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             grid_[row][col].height = height + (*rng_)(*gener_);
             grid_[row][col].is_set = true;
         }
     }
     center_height_adjust();
     clamp_height();
     return true;
 }
References center_, center_height_adjust(), clamp_height(), grid_, num_x_cols_, num_y_rows_, z_max_, and z_min_.
Referenced by generate().
generate_linear_walk()
bool scrimmage::interaction::TerrainMap::generate_linear_walk () protected
Definition at line 143 of file TerrainMap.cpp.
{
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             // If this node is already set, skip (continue)
             if (grid_[row][col].is_set) {
                 continue;
             }
             // Get the average of the neighbors that are already set
             double height_avg = get_neighbor_avg(row, col);
             grid_[row][col].height = height_avg + (*rng_)(*gener_);
             grid_[row][col].is_set = true;
         }
     }
     center_height_adjust();
     clamp_height();
      // Force the altitude center to be at the midpoint between z_max and z_min
     center_(2) = (z_max_ + z_min_) / 2.0;
     // Initialize the map, such that row 0 is at z_min and the last row is at
     // z_max, with a linear interpolation across the rows. Also, add noise to
     // each height value.
     double z_step = (z_max_ - z_min_) / num_y_rows_;
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         double height_l = z_step * row;
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             grid_[row][col].height = grid_[row][col].height + height_l;
         }
     }
     center_height_adjust();
     clamp_height();
     return true;
 }
References center_, center_height_adjust(), clamp_height(), get_neighbor_avg(), grid_, num_x_cols_, num_y_rows_, z_max_, and z_min_.
Referenced by generate().
center_height_adjust()
void scrimmage::interaction::TerrainMap::center_height_adjust () protected
Definition at line 177 of file TerrainMap.cpp.
{
     // Make sure the grid's center is located at the appropriate height.
     double offset = center_(2) - grid_[std::round(num_y_rows_/2.0)][std::round(num_x_cols_/2.0)].height;
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             grid_[row][col].height += offset;
         }
     }
 }
References center_, grid_, num_x_cols_, and num_y_rows_.
Referenced by generate_linear(), generate_linear_walk(), and generate_random_walk().
clamp_height()
void scrimmage::interaction::TerrainMap::clamp_height () protected
Definition at line 187 of file TerrainMap.cpp.
{
     // Ensure all height values fall within z_min and z_max
     for (unsigned int row = 0; row < num_y_rows_; ++row) {
         for (unsigned int col = 0; col < num_x_cols_; ++col) {
             grid_[row][col].height = clamp(grid_[row][col].height, z_min_, z_max_);
         }
     }
 }
References grid_, num_x_cols_, num_y_rows_, z_max_, and z_min_.
Referenced by generate_linear(), generate_linear_walk(), and generate_random_walk().
get_neighbor_avg()
double scrimmage::interaction::TerrainMap::get_neighbor_avg (const int & row, const int & col) protected
Definition at line 196 of file TerrainMap.cpp.
{
     unsigned int neighbors = 0;
     double height_sum = 0;
     if (row > 0) {
         height_sum += grid_[row-1][col].height;
         ++neighbors;
     }
     if (col > 0) {
         height_sum += grid_[row][col-1].height;
         ++neighbors;
     }
     if (row > 0 && col > 0) {
         height_sum += grid_[row-1][col-1].height;
         ++neighbors;
     }
     return (neighbors == 0) ? 0 : height_sum / neighbors;
 }
References grid_.
Referenced by generate_linear_walk(), and generate_random_walk().
Member Data Documentation
rng_
std::shared_ptr<std::normal_distribution<double> > scrimmage::interaction::TerrainMap::rng_ protected
Definition at line 78 of file TerrainMap.h.
Referenced by generate().
gener_
std::shared_ptr<std::default_random_engine> scrimmage::interaction::TerrainMap::gener_ protected
Definition at line 79 of file TerrainMap.h.
Referenced by generate().
technique_
Technique scrimmage::interaction::TerrainMap::technique_ = Technique::RANDOM_WALK protected
Definition at line 80 of file TerrainMap.h.
Referenced by generate().
center_
Eigen::Vector3d scrimmage::interaction::TerrainMap::center_ = Eigen::Vector3d::Zero() protected
Definition at line 82 of file TerrainMap.h.
Referenced by center_height_adjust(), generate_linear(), generate_linear_walk(), height_at(), proto(), shape(), and TerrainMap().
x_length_
double scrimmage::interaction::TerrainMap::x_length_ = 10 protected
Definition at line 83 of file TerrainMap.h.
Referenced by height_at(), proto(), and shape().
y_length_
double scrimmage::interaction::TerrainMap::y_length_ = 10 protected
Definition at line 84 of file TerrainMap.h.
Referenced by height_at(), proto(), and shape().
x_resolution_
double scrimmage::interaction::TerrainMap::x_resolution_ = 1.0 protected
Definition at line 85 of file TerrainMap.h.
Referenced by height_at(), proto(), and shape().
y_resolution_
double scrimmage::interaction::TerrainMap::y_resolution_ = 1.0 protected
Definition at line 86 of file TerrainMap.h.
Referenced by height_at(), proto(), and shape().
z_min_
double scrimmage::interaction::TerrainMap::z_min_ = -std::numeric_limits<double>::infinity() protected
Definition at line 87 of file TerrainMap.h.
Referenced by clamp_height(), generate_linear(), generate_linear_walk(), and proto().
z_max_
double scrimmage::interaction::TerrainMap::z_max_ = +std::numeric_limits<double>::infinity() protected
Definition at line 88 of file TerrainMap.h.
Referenced by clamp_height(), generate_linear(), generate_linear_walk(), and proto().
color_
Eigen::Vector3d scrimmage::interaction::TerrainMap::color_ = Eigen::Vector3d::Zero() protected
Definition at line 89 of file TerrainMap.h.
Referenced by shape().
num_x_cols_
unsigned int scrimmage::interaction::TerrainMap::num_x_cols_ = x_length_ / x_resolution_ protected
Definition at line 91 of file TerrainMap.h.
Referenced by center_height_adjust(), clamp_height(), generate_linear(), generate_linear_walk(), generate_random_walk(), height_at(), proto(), and shape().
num_y_rows_
unsigned int scrimmage::interaction::TerrainMap::num_y_rows_ = y_length_ / y_resolution_ protected
Definition at line 92 of file TerrainMap.h.
Referenced by center_height_adjust(), clamp_height(), generate_linear(), generate_linear_walk(), generate_random_walk(), height_at(), proto(), and shape().
grid_
std::vector<std::vector<Node> > scrimmage::interaction::TerrainMap::grid_ protected
Definition at line 100 of file TerrainMap.h.
Referenced by center_height_adjust(), clamp_height(), generate_linear(), generate_linear_walk(), generate_random_walk(), get_neighbor_avg(), height_at(), proto(), shape(), and TerrainMap().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/interaction/TerrainGenerator/TerrainMap.h
/root/scrimmage/scrimmage/src/plugins/interaction/TerrainGenerator/TerrainMap.cpp