SCRIMMAGE: scrimmage::autonomy::OpenAIActions Class Reference
scrimmage::autonomy::OpenAIActions Class Reference
#include <OpenAIActions.h>
Public Member Functions
OpenAIActions ()
std::vector< std::shared_ptr< ScrimmageOpenAIAutonomy > > & ext_ctrl_vec ()
void create_action_space (bool combine_actors)
void distribute_action (pybind11::object action, bool combine_actors)
Public Attributes
pybind11::object action_space
Protected Attributes
std::vector< std::shared_ptr< ScrimmageOpenAIAutonomy > > ext_ctrl_vec_
pybind11::object tuple_space_
pybind11::object box_space_
pybind11::object asarray_
Detailed Description
Definition at line 48 of file OpenAIActions.h.
Constructor & Destructor Documentation
OpenAIActions()
scrimmage::autonomy::OpenAIActions::OpenAIActions ()
Definition at line 50 of file OpenAIActions.cpp.
                              :
     tuple_space_(get_gym_space("Tuple")),
     box_space_(get_gym_space("Box")),
     asarray_(py::module::import("numpy").attr("asarray")) {}
Member Function Documentation
ext_ctrl_vec()
std::vector< std::shared_ptr< ScrimmageOpenAIAutonomy > > & scrimmage::autonomy::OpenAIActions::ext_ctrl_vec ()
Definition at line 55 of file OpenAIActions.cpp.
{
     return ext_ctrl_vec_;
 }
References ext_ctrl_vec_.
Referenced by scrimmage::autonomy::init_actor_func().
create_action_space()
void scrimmage::autonomy::OpenAIActions::create_action_space (bool combine_actors)
Definition at line 59 of file OpenAIActions.cpp.
{
     if (ext_ctrl_vec_.empty()) {
         std::cout << "OpenAIActions::create_action_space called "
                   << "with 0 actors" << std::endl;
     } else if ((ext_ctrl_vec_.size() == 1 || combine_actors)) {
         py::list discrete_count;
         py::list continuous_minima;
         py::list continuous_maxima;
         for (auto &a : ext_ctrl_vec_) {
             a->set_environment();
             to_discrete(a->action_space.discrete_count, discrete_count);
             to_continuous(a->action_space.continuous_extrema, continuous_minima, continuous_maxima);
         }
         action_space =
             create_space(discrete_count, continuous_minima, continuous_maxima);
     } else {
         py::list action_spaces;
         for (auto &a : ext_ctrl_vec_) {
             py::list discrete_count;
             py::list continuous_minima;
             py::list continuous_maxima;
             a->set_environment();
             to_discrete(a->action_space.discrete_count, discrete_count);
             to_continuous(a->action_space.continuous_extrema, continuous_minima, continuous_maxima);
             auto space =
                 create_space(discrete_count, continuous_minima, continuous_maxima);
             action_spaces.append(space);
         }
         py::object tuple_space = get_gym_space("Tuple");
         action_space = tuple_space(action_spaces);
     }
 }
References action_space, scrimmage::autonomy::create_space(), ext_ctrl_vec_, scrimmage::autonomy::get_gym_space(), scrimmage::autonomy::to_continuous(), and scrimmage::autonomy::to_discrete().
Referenced by scrimmage::autonomy::init_actor_func().
distribute_action()
void scrimmage::autonomy::OpenAIActions::distribute_action (pybind11::object action, bool combine_actors)
Definition at line 100 of file OpenAIActions.cpp.
{
     py::array_t<int> disc_actions;
     py::array_t<double> cont_actions;
     int* disc_action_data = nullptr;
     double* cont_action_data = nullptr;
     auto update_action_lists = [&](py::object space, py::object act) {
         disc_actions = py::list();
         cont_actions = py::list();
         if (PyObject_IsInstance(space.ptr(), tuple_space_.ptr())) {
             py::tuple action_list = act.cast<py::list>();
             disc_actions = asarray_(action_list[0], py::str("int"));
             cont_actions = asarray_(action_list[1], py::str("float"));
             disc_action_data = static_cast<int*>(disc_actions.request().ptr);
             cont_action_data = static_cast<double*>(cont_actions.request().ptr);
         } else if (PyObject_IsInstance(space.ptr(), box_space_.ptr())) {
             cont_actions = asarray_(act);
             cont_action_data = static_cast<double*>(cont_actions.request().ptr);
         } else {
             disc_actions = asarray_(act);
             disc_action_data = static_cast<int*>(disc_actions.request().ptr);
         }
     };
     auto put_action = [&](int &idx, size_t from_sz, auto *from_data, auto &to_vec) {
         if (to_vec.size() != from_sz) {
             to_vec.resize(from_sz);
         }
         if (from_data == nullptr && from_sz > 0) {
             std::cout << "Error: disc_action_data not set correctly" << std::endl;
             return;
         } else {
             for (size_t i = 0; i < from_sz; i++) {
                 to_vec[i] = from_data[idx++];
             }
         }
     };
     auto put_actions = [&](auto a, int &disc_action_idx, int &cont_action_idx) {
         put_action(disc_action_idx, a->action_space.discrete_count.size(),
                    disc_action_data, a->action.discrete);
         put_action(cont_action_idx, a->action_space.continuous_extrema.size(),
                    cont_action_data, a->action.continuous);
     };
     if ((ext_ctrl_vec_.size() == 1 || combine_actors)) {
         update_action_lists(action_space, action);
         int disc_action_idx = 0;
         int cont_action_idx = 0;
         for (auto &a : ext_ctrl_vec_) {
             put_actions(a, disc_action_idx, cont_action_idx);
         }
     } else {
         py::list action_space_list = action_space.attr("spaces").cast<py::list>();
         py::list action_list = action.cast<py::list>();
         for (size_t i = 0; i < ext_ctrl_vec_.size(); i++) {
             py::object indiv_action_space = action_space_list[i];
             py::object indiv_action = action_list[i];
             update_action_lists(indiv_action_space, indiv_action);
             int disc_action_idx = 0;
             int cont_action_idx = 0;
             put_actions(ext_ctrl_vec_[i], disc_action_idx, cont_action_idx);
         }
     }
 }
References action_space, asarray_, box_space_, ext_ctrl_vec_, and tuple_space_.
Referenced by scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy().
Member Data Documentation
action_space
pybind11::object scrimmage::autonomy::OpenAIActions::action_space
Definition at line 55 of file OpenAIActions.h.
Referenced by create_action_space(), distribute_action(), and scrimmage::autonomy::init_actor_func().
ext_ctrl_vec_
std::vector<std::shared_ptr<ScrimmageOpenAIAutonomy> > scrimmage::autonomy::OpenAIActions::ext_ctrl_vec_ protected
Definition at line 58 of file OpenAIActions.h.
Referenced by create_action_space(), distribute_action(), and ext_ctrl_vec().
tuple_space_
pybind11::object scrimmage::autonomy::OpenAIActions::tuple_space_ protected
Definition at line 59 of file OpenAIActions.h.
Referenced by distribute_action().
box_space_
pybind11::object scrimmage::autonomy::OpenAIActions::box_space_ protected
Definition at line 60 of file OpenAIActions.h.
Referenced by distribute_action().
asarray_
pybind11::object scrimmage::autonomy::OpenAIActions::asarray_ protected
Definition at line 61 of file OpenAIActions.h.
Referenced by distribute_action().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIActions.h
/root/scrimmage/scrimmage/src/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIActions.cpp