SCRIMMAGE: scrimmage::Log Class Reference
scrimmage::Log Class Reference
#include <Log.h>
Public Types
enum FileType {
FRAMES = 0, SHAPES = 1, UTMTERRAIN = 2, SIMINFO = 3,
CONTACTVISUAL = 4, GUIMSG = 5, MSG = 6
}
enum Mode { READ = 0, WRITE = 1, NONE }
using ZeroCopyInputStreamPtr = std::shared_ptr< google::protobuf::io::ZeroCopyInputStream >
using ZeroCopyOutputStreamPtr = std::shared_ptr< google::protobuf::io::ZeroCopyOutputStream >
Public Member Functions
Log ()
bool init (const std::string &dir, Mode mode)
bool parse (std::string dir)
bool parse (std::string filename, FileType type)
bool parse_frames (std::string filename, ZeroCopyInputStreamPtr input)
bool parse_shapes (std::string filename, ZeroCopyInputStreamPtr input)
bool parse_utm_terrain (std::string filename, ZeroCopyInputStreamPtr input)
bool parse_contact_visual (std::string filename, ZeroCopyInputStreamPtr input)
bool close_log ()
std::list< Frame > & scrimmage_frames ()
std::list< std::shared_ptr< scrimmage_proto::Frame > > & frames ()
std::list< std::shared_ptr< scrimmage_proto::Shapes > > & shapes ()
std::list< std::shared_ptr< scrimmage_proto::UTMTerrain > > & utm_terrain ()
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > & contact_visual ()
std::string log_dir ()
bool write_ascii (const std::string &str)
bool save_frame (const std::shared_ptr< scrimmage_proto::Frame > &frame)
bool save_shapes (const scrimmage_proto::Shapes &shapes)
bool save_utm_terrain (const std::shared_ptr< scrimmage_proto::UTMTerrain > &utm_terrain)
bool save_contact_visual (const std::shared_ptr< scrimmage_proto::ContactVisual > &contact_visual)
std::string frames_filename ()
std::string shapes_filename ()
std::string utm_terrain_filename ()
std::string contact_visual_filename ()
std::string msgs_filename ()
void set_enable_log (bool enable)
void init_network (NetworkPtr network)
Protected Types
using MessageLitePtr = std::shared_ptr< google::protobuf::MessageLite >
Protected Member Functions
bool open_file (std::string name, int &fd)
bool writeDelimitedTo (const google::protobuf::MessageLite &message, ZeroCopyOutputStreamPtr rawOutput)
bool readDelimitedFrom (const std::string &filename, ZeroCopyInputStreamPtr rawInput, MessageLitePtr message, bool &clean_eof)
Protected Attributes
bool enable_log_ = true
Mode mode_ = Mode::READ
std::string frames_name_ = "frames.bin"
std::string shapes_name_ = "shapes.bin"
std::string utm_terrain_name_ = "utm_terrain.bin"
std::string contact_visual_name_ = "contact_visual.bin"
std::string msgs_name_ = "msgs.bin"
int frames_fd_
int shapes_fd_
int utm_terrain_fd_
int contact_visual_fd_
int msgs_fd_
std::string log_dir_
std::string ascii_filename_ = "log.txt"
std::ofstream ascii_output_
ZeroCopyOutputStreamPtr frames_output_
ZeroCopyOutputStreamPtr shapes_output_
ZeroCopyOutputStreamPtr utm_terrain_output_
ZeroCopyOutputStreamPtr contact_visual_output_
ZeroCopyOutputStreamPtr msgs_output_
std::list< Frame > scrimmage_frames_
std::list< std::shared_ptr< scrimmage_proto::Frame > > frames_
std::list< std::shared_ptr< scrimmage_proto::Shapes > > shapes_
std::list< std::shared_ptr< scrimmage_proto::UTMTerrain > > utm_terrain_
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > contact_visual_
Detailed Description
Definition at line 60 of file Log.h.
Member Typedef Documentation
ZeroCopyInputStreamPtr
using scrimmage::Log::ZeroCopyInputStreamPtr = std::shared_ptr<google::protobuf::io::ZeroCopyInputStream>
Definition at line 62 of file Log.h.
ZeroCopyOutputStreamPtr
using scrimmage::Log::ZeroCopyOutputStreamPtr = std::shared_ptr<google::protobuf::io::ZeroCopyOutputStream>
Definition at line 63 of file Log.h.
MessageLitePtr
using scrimmage::Log::MessageLitePtr = std::shared_ptr<google::protobuf::MessageLite> protected
Definition at line 134 of file Log.h.
Member Enumeration Documentation
FileType
enum scrimmage::Log::FileType
Enumerator
FRAMES
SHAPES
UTMTERRAIN
SIMINFO
CONTACTVISUAL
GUIMSG
MSG
Definition at line 67 of file Log.h.
                   {
         FRAMES = 0,
         SHAPES = 1,
         UTMTERRAIN = 2,
         SIMINFO = 3,
         CONTACTVISUAL = 4,
         GUIMSG = 5,
         MSG = 6
     };
Mode
enum scrimmage::Log::Mode
Enumerator
READ
WRITE
NONE
Definition at line 77 of file Log.h.
               {
         READ = 0,
         WRITE = 1,
         NONE
     };
Constructor & Destructor Documentation
Log()
scrimmage::Log::Log ()
Definition at line 64 of file Log.cpp.
          : frames_output_(), shapes_output_(), utm_terrain_output_(),
              contact_visual_output_() {
     // Verify that the version of the library that we linked against is
     // compatible with the version of the headers we compiled against.
     GOOGLE_PROTOBUF_VERIFY_VERSION;
     frames_fd_ = -1;
     shapes_fd_ = -1;
     utm_terrain_fd_ = -1;
     contact_visual_fd_ = -1;
     msgs_fd_ = -1;
 }
References contact_visual_fd_, frames_fd_, msgs_fd_, shapes_fd_, and utm_terrain_fd_.
Member Function Documentation
init()
bool scrimmage::Log::init (const std::string & dir, Log::Mode mode)
Definition at line 87 of file Log.cpp.
{
     mode_ = mode;
     log_dir_ = dir;
     ascii_filename_ = log_dir_ + "/" + ascii_filename_;
     frames_name_ = log_dir_ + "/" + frames_name_;
     shapes_name_ = log_dir_ + "/" + shapes_name_;
     utm_terrain_name_ = log_dir_ + "/" + utm_terrain_name_;
     contact_visual_name_ = log_dir_ + "/" + contact_visual_name_;
     msgs_name_ = log_dir_ + "/" + msgs_name_;
     if (mode_ == WRITE) {
         if (open_file(frames_name_, frames_fd_)) {
             frames_output_ = std::make_shared<google::protobuf::io::FileOutputStream>(frames_fd_);
         }
         if (open_file(shapes_name_, shapes_fd_)) {
             shapes_output_ = std::make_shared<google::protobuf::io::FileOutputStream>(shapes_fd_);
         }
         if (open_file(utm_terrain_name_, utm_terrain_fd_)) {
             utm_terrain_output_ = std::make_shared<google::protobuf::io::FileOutputStream>(utm_terrain_fd_);
         }
         if (open_file(contact_visual_name_, contact_visual_fd_)) {
             contact_visual_output_ = std::make_shared<google::protobuf::io::FileOutputStream>(contact_visual_fd_);
         }
     } else if (mode_ == READ) {
         parse(dir);
     }
     return true;
 }
References ascii_filename_, contact_visual_fd_, contact_visual_name_, contact_visual_output_, frames_fd_, frames_name_, frames_output_, log_dir_, mode_, msgs_name_, open_file(), parse(), READ, shapes_fd_, shapes_name_, shapes_output_, utm_terrain_fd_, utm_terrain_name_, utm_terrain_output_, and WRITE.
parse() [1/2]
bool scrimmage::Log::parse (std::string dir)
Definition at line 164 of file Log.cpp.
{
     if (!fs::is_directory(dir)) {
         cout << "Log directory doesn't exist: " << dir << endl;
         return false;
     }
     if (!fs::exists(fs::path(frames_name_))) {
         cout << "Frames file doesn't exist: " << frames_name_ << endl;
     } else {
         parse(frames_name_, FRAMES);
     }
     if (!fs::exists(fs::path(shapes_name_))) {
         cout << "Shapes file doesn't exist: " << shapes_name_ << endl;
     } else {
         parse(shapes_name_, SHAPES);
     }
     if (!fs::exists(fs::path(utm_terrain_name_))) {
         cout << "UTM Terrain file doesn't exist: " << utm_terrain_name_ << endl;
     } else {
         parse(utm_terrain_name_, UTMTERRAIN);
     }
     if (!fs::exists(fs::path(contact_visual_name_))) {
         cout << "Contact Visual file doesn't exist: " << contact_visual_name_ << endl;
     } else {
         parse(contact_visual_name_, CONTACTVISUAL);
     }
     return true;
 }
References contact_visual_name_, CONTACTVISUAL, FRAMES, frames_name_, SHAPES, shapes_name_, utm_terrain_name_, and UTMTERRAIN.
Referenced by init().
parse() [2/2]
bool scrimmage::Log::parse (std::string filename, Log::FileType type)
Definition at line 197 of file Log.cpp.
{
     int input_fd = open(filename.c_str(), O_RDONLY);
     if (input_fd == -1) {
         cout << "Failed to open file: " << filename.c_str() << endl;
         return false;
     }
     ZeroCopyInputStreamPtr input = std::make_shared<google::protobuf::io::FileInputStream>(input_fd);
     if (!input) {
         cout << "Failed to open FileInputStream. Filename: "
              << filename.c_str() << endl;
     }
     if (type == FRAMES) {
         parse_frames(filename, input);
     } else if (type == SHAPES) {
         parse_shapes(filename, input);
     } else if (type == UTMTERRAIN) {
         parse_utm_terrain(filename, input);
     } else if (type == CONTACTVISUAL) {
         parse_contact_visual(filename, input);
     } else if (type == MSG) {
         // parse_contact_visual(filename, input);
         cout << "No parser for messages yet. " << type << endl;
     } else {
         cout << "Log parse(): Invalid parse type: " << type << endl;
     }
     close(input_fd);
     return true;
 }
References CONTACTVISUAL, FRAMES, MSG, parse_contact_visual(), parse_frames(), parse_shapes(), parse_utm_terrain(), SHAPES, and UTMTERRAIN.
parse_frames()
bool scrimmage::Log::parse_frames (std::string filename, ZeroCopyInputStreamPtr input)
Definition at line 230 of file Log.cpp.
{
     frames_.clear();
     scrimmage_frames_.clear();
     bool success = false, clean_eof = false;
     do {
         std::shared_ptr<scrimmage_proto::Frame> frame = std::make_shared<scrimmage_proto::Frame>();
         success = this->readDelimitedFrom(filename, input, frame, clean_eof);
         if (clean_eof || !success) break;
         frames_.push_back(frame);
         scrimmage_frames_.push_back(proto_2_frame(*frame));
     } while (success);
     if (!clean_eof) {
         cout << "Frames - WARNING: Clean end-of-file not detected." << endl;
     }
     return true;
 }
References frames_, scrimmage::proto_2_frame(), readDelimitedFrom(), and scrimmage_frames_.
Referenced by parse().
parse_shapes()
bool scrimmage::Log::parse_shapes (std::string filename, ZeroCopyInputStreamPtr input)
Definition at line 249 of file Log.cpp.
{
     shapes_.clear();
     bool success = false, clean_eof = false;
     do {
         std::shared_ptr<scrimmage_proto::Shapes> shapes = std::make_shared<scrimmage_proto::Shapes>();
         success = this->readDelimitedFrom(filename, input, shapes, clean_eof);
         if (clean_eof || !success) break;
         shapes_.push_back(shapes);
     } while (success);
     if (!clean_eof) {
         cout << "Shapes - WARNING: Clean end-of-file not detected." << endl;
     }
     return true;
 }
References readDelimitedFrom(), shapes(), and shapes_.
Referenced by parse().
parse_utm_terrain()
bool scrimmage::Log::parse_utm_terrain (std::string filename, ZeroCopyInputStreamPtr input)
Definition at line 266 of file Log.cpp.
{
     utm_terrain_.clear();
     bool success = false, clean_eof = false;
     do {
         std::shared_ptr<scrimmage_proto::UTMTerrain> utm_terrain = std::make_shared<scrimmage_proto::UTMTerrain>();
         success = this->readDelimitedFrom(filename, input, utm_terrain, clean_eof);
         if (clean_eof || !success) break;
         utm_terrain_.push_back(utm_terrain);
     } while (success);
     if (!clean_eof) {
         cout << "UTMTerrain - WARNING: Clean end-of-file not detected." << endl;
     }
     return true;
 }
References readDelimitedFrom(), utm_terrain(), and utm_terrain_.
Referenced by parse().
parse_contact_visual()
bool scrimmage::Log::parse_contact_visual (std::string filename, ZeroCopyInputStreamPtr input)
Definition at line 283 of file Log.cpp.
{
     contact_visual_.clear();
     bool success = false, clean_eof = false;
     do {
         std::shared_ptr<scrimmage_proto::ContactVisual> contact_visual = std::make_shared<scrimmage_proto::ContactVisual>();
         success = this->readDelimitedFrom(filename, input, contact_visual, clean_eof);
         if (clean_eof || !success) break;
         contact_visual_.push_back(contact_visual);
     } while (success);
     if (!clean_eof) {
         cout << "ContactVisual - WARNING: Clean end-of-file not detected." << endl;
     }
     return true;
 }
References contact_visual(), contact_visual_, and readDelimitedFrom().
Referenced by parse().
close_log()
bool scrimmage::Log::close_log ()
Definition at line 370 of file Log.cpp.
                     {
     if (ascii_output_.is_open()) {
         ascii_output_.close();
     }
     google::protobuf::ShutdownProtobufLibrary();
     frames_output_.reset();
     shapes_output_.reset();
     utm_terrain_output_.reset();
     contact_visual_output_.reset();
     return true;
 }
References ascii_output_, contact_visual_output_, frames_output_, shapes_output_, and utm_terrain_output_.
scrimmage_frames()
std::list< Frame > & scrimmage::Log::scrimmage_frames ()
Definition at line 384 of file Log.cpp.
 { return scrimmage_frames_; }
References scrimmage_frames_.
frames()
std::list< std::shared_ptr< scrimmage_proto::Frame > > & scrimmage::Log::frames ()
Definition at line 386 of file Log.cpp.
 { return frames_; }
References frames_.
shapes()
std::list< std::shared_ptr< scrimmage_proto::Shapes > > & scrimmage::Log::shapes ()
Definition at line 388 of file Log.cpp.
 { return shapes_; }
References shapes_.
Referenced by parse_shapes(), and save_shapes().
utm_terrain()
std::list< std::shared_ptr< scrimmage_proto::UTMTerrain > > & scrimmage::Log::utm_terrain ()
Definition at line 390 of file Log.cpp.
 { return utm_terrain_; }
References utm_terrain_.
Referenced by parse_utm_terrain(), and save_utm_terrain().
contact_visual()
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > & scrimmage::Log::contact_visual ()
Definition at line 392 of file Log.cpp.
 { return contact_visual_; }
References contact_visual_.
Referenced by parse_contact_visual(), and save_contact_visual().
log_dir()
std::string scrimmage::Log::log_dir ()
Definition at line 394 of file Log.cpp.
 { return log_dir_; }
References log_dir_.
write_ascii()
bool scrimmage::Log::write_ascii (const std::string & str)
Definition at line 119 of file Log.cpp.
{
     if (!enable_log_) return true;
     if (!ascii_output_.is_open()) {
         ascii_output_.open(ascii_filename_.c_str(),
                            std::ios::out | std::ios::in | std::ios::trunc);
     }
     if (!ascii_output_.is_open()) {
         cout << "Failed to open file for writing: " << ascii_filename_ << endl;
         return false;
     }
     ascii_output_ << str << endl;
     return true;
 }
References ascii_filename_, ascii_output_, and enable_log_.
save_frame()
bool scrimmage::Log::save_frame (const std::shared_ptr< scrimmage_proto::Frame > & frame)
Definition at line 136 of file Log.cpp.
{
     return writeDelimitedTo(*frame, frames_output_);
 }
References frames_output_, and writeDelimitedTo().
save_shapes()
bool scrimmage::Log::save_shapes (const scrimmage_proto::Shapes & shapes)
Definition at line 140 of file Log.cpp.
{
     return writeDelimitedTo(shapes, shapes_output_);
 }
References shapes(), shapes_output_, and writeDelimitedTo().
save_utm_terrain()
bool scrimmage::Log::save_utm_terrain (const std::shared_ptr< scrimmage_proto::UTMTerrain > & utm_terrain)
Definition at line 144 of file Log.cpp.
{
     return writeDelimitedTo(*utm_terrain, utm_terrain_output_);
 }
References utm_terrain(), utm_terrain_output_, and writeDelimitedTo().
save_contact_visual()
bool scrimmage::Log::save_contact_visual (const std::shared_ptr< scrimmage_proto::ContactVisual > & contact_visual)
Definition at line 148 of file Log.cpp.
{
     return writeDelimitedTo(*contact_visual, contact_visual_output_);
 }
References contact_visual(), contact_visual_output_, and writeDelimitedTo().
frames_filename()
std::string scrimmage::Log::frames_filename ()
Definition at line 152 of file Log.cpp.
 { return frames_name_; }
References frames_name_.
shapes_filename()
std::string scrimmage::Log::shapes_filename ()
Definition at line 154 of file Log.cpp.
 { return shapes_name_; }
References shapes_name_.
utm_terrain_filename()
std::string scrimmage::Log::utm_terrain_filename ()
Definition at line 156 of file Log.cpp.
 { return utm_terrain_name_; }
References utm_terrain_name_.
contact_visual_filename()
std::string scrimmage::Log::contact_visual_filename ()
Definition at line 158 of file Log.cpp.
 { return contact_visual_name_; }
References contact_visual_name_.
msgs_filename()
std::string scrimmage::Log::msgs_filename ()
Definition at line 160 of file Log.cpp.
 { return msgs_name_; }
References msgs_name_.
set_enable_log()
void scrimmage::Log::set_enable_log (bool enable)
Definition at line 162 of file Log.cpp.
 { enable_log_ = enable; }
References enable_log_.
init_network()
void scrimmage::Log::init_network (NetworkPtr network)
open_file()
bool scrimmage::Log::open_file (std::string name, int & fd) protected
Definition at line 77 of file Log.cpp.
{
     fd = open(filename.c_str(), O_CREAT | O_RDWR | O_TRUNC, 0644);
     if (fd == -1) {
         cout << "Failed to open file for writing: "
              << filename << endl;
         return false;
     }
     return true;
 }
Referenced by init().
writeDelimitedTo()
bool scrimmage::Log::writeDelimitedTo (const google::protobuf::MessageLite & message, ZeroCopyOutputStreamPtr rawOutput) protected
Definition at line 300 of file Log.cpp.
{
     if (mode_ == READ || !enable_log_) {
         return true;
     }
     // We create a new coded stream for each message.  Don't worry, this is fast.
     google::protobuf::io::CodedOutputStream output(rawOutput.get());
     // Write the size.
     const int size = message.ByteSize();
     output.WriteVarint32(size);
     // cout << "Writing message of size: " << size << endl;
     uint8_t* buffer = output.GetDirectBufferForNBytesAndAdvance(size);
     if (buffer != NULL) {
         // Optimization:  The message fits in one buffer, so use the faster
         // direct-to-array serialization path.
         message.SerializeWithCachedSizesToArray(buffer);
     } else {
         // Slightly-slower path when the message is multiple buffers.
         message.SerializeWithCachedSizes(&output);
         if (output.HadError()) {
             return false;
         }
     }
     return true;
 }
References enable_log_, mode_, and READ.
Referenced by save_contact_visual(), save_frame(), save_shapes(), and save_utm_terrain().
readDelimitedFrom()
bool scrimmage::Log::readDelimitedFrom (const std::string & filename, ZeroCopyInputStreamPtr rawInput, MessageLitePtr message, bool & clean_eof) protected
Definition at line 331 of file Log.cpp.
{
     // see here for the implementation: http://stackoverflow.com/a/22927149
     // We create a new coded stream for each message.  Don't worry, this is fast,
     // and it makes sure the 64MB total size limit is imposed per-message rather
     // than on the whole stream.  (See the CodedInputStream interface for more
     // info on this limit.)
     google::protobuf::io::CodedInputStream input(rawInput.get());
     const int start = input.CurrentPosition();
     clean_eof = false;
     // Read the size.
     uint32_t size;
     if (!input.ReadVarint32(&size)) {
         clean_eof = (input.CurrentPosition() == start);
         return false;
     }
     // Tell the stream not to read beyond that size.
     google::protobuf::io::CodedInputStream::Limit limit = input.PushLimit(size);
     // Parse the message.
     if (!message->MergeFromCodedStream(&input)) {
         cout << "Error: MergeFromCodedStream failed: " << filename << endl;
         return false;
     }
     if (!input.ConsumedEntireMessage()) {
         cout << "Error: ConsumedEntireMessage() failed: " << filename << endl;
         return false;
     }
     // Release the limit.
     input.PopLimit(limit);
     return true;
 }
Referenced by parse_contact_visual(), parse_frames(), parse_shapes(), and parse_utm_terrain().
Member Data Documentation
enable_log_
bool scrimmage::Log::enable_log_ = true protected
Definition at line 136 of file Log.h.
Referenced by set_enable_log(), write_ascii(), and writeDelimitedTo().
mode_
Mode scrimmage::Log::mode_ = Mode::READ protected
Definition at line 137 of file Log.h.
Referenced by init(), and writeDelimitedTo().
frames_name_
std::string scrimmage::Log::frames_name_ = "frames.bin" protected
Definition at line 141 of file Log.h.
Referenced by frames_filename(), init(), and parse().
shapes_name_
std::string scrimmage::Log::shapes_name_ = "shapes.bin" protected
Definition at line 142 of file Log.h.
Referenced by init(), parse(), and shapes_filename().
utm_terrain_name_
std::string scrimmage::Log::utm_terrain_name_ = "utm_terrain.bin" protected
Definition at line 143 of file Log.h.
Referenced by init(), parse(), and utm_terrain_filename().
contact_visual_name_
std::string scrimmage::Log::contact_visual_name_ = "contact_visual.bin" protected
Definition at line 144 of file Log.h.
Referenced by contact_visual_filename(), init(), and parse().
msgs_name_
std::string scrimmage::Log::msgs_name_ = "msgs.bin" protected
Definition at line 145 of file Log.h.
Referenced by init(), and msgs_filename().
frames_fd_
int scrimmage::Log::frames_fd_ protected
Definition at line 147 of file Log.h.
Referenced by init(), and Log().
shapes_fd_
int scrimmage::Log::shapes_fd_ protected
Definition at line 148 of file Log.h.
Referenced by init(), and Log().
utm_terrain_fd_
int scrimmage::Log::utm_terrain_fd_ protected
Definition at line 149 of file Log.h.
Referenced by init(), and Log().
contact_visual_fd_
int scrimmage::Log::contact_visual_fd_ protected
Definition at line 150 of file Log.h.
Referenced by init(), and Log().
msgs_fd_
int scrimmage::Log::msgs_fd_ protected
Definition at line 151 of file Log.h.
Referenced by Log().
log_dir_
std::string scrimmage::Log::log_dir_ protected
Definition at line 153 of file Log.h.
Referenced by init(), and log_dir().
ascii_filename_
std::string scrimmage::Log::ascii_filename_ = "log.txt" protected
Definition at line 155 of file Log.h.
Referenced by init(), and write_ascii().
ascii_output_
std::ofstream scrimmage::Log::ascii_output_ protected
Definition at line 156 of file Log.h.
Referenced by close_log(), and write_ascii().
frames_output_
ZeroCopyOutputStreamPtr scrimmage::Log::frames_output_ protected
Definition at line 158 of file Log.h.
Referenced by close_log(), init(), and save_frame().
shapes_output_
ZeroCopyOutputStreamPtr scrimmage::Log::shapes_output_ protected
Definition at line 159 of file Log.h.
Referenced by close_log(), init(), and save_shapes().
utm_terrain_output_
ZeroCopyOutputStreamPtr scrimmage::Log::utm_terrain_output_ protected
Definition at line 160 of file Log.h.
Referenced by close_log(), init(), and save_utm_terrain().
contact_visual_output_
ZeroCopyOutputStreamPtr scrimmage::Log::contact_visual_output_ protected
Definition at line 161 of file Log.h.
Referenced by close_log(), init(), and save_contact_visual().
msgs_output_
ZeroCopyOutputStreamPtr scrimmage::Log::msgs_output_ protected
Definition at line 162 of file Log.h.
scrimmage_frames_
std::list<Frame> scrimmage::Log::scrimmage_frames_ protected
Definition at line 164 of file Log.h.
Referenced by parse_frames(), and scrimmage_frames().
frames_
std::list<std::shared_ptr<scrimmage_proto::Frame> > scrimmage::Log::frames_ protected
Definition at line 165 of file Log.h.
Referenced by frames(), and parse_frames().
shapes_
std::list<std::shared_ptr<scrimmage_proto::Shapes> > scrimmage::Log::shapes_ protected
Definition at line 166 of file Log.h.
Referenced by parse_shapes(), and shapes().
utm_terrain_
std::list<std::shared_ptr<scrimmage_proto::UTMTerrain> > scrimmage::Log::utm_terrain_ protected
Definition at line 167 of file Log.h.
Referenced by parse_utm_terrain(), and utm_terrain().
contact_visual_
std::list<std::shared_ptr<scrimmage_proto::ContactVisual> > scrimmage::Log::contact_visual_ protected
Definition at line 168 of file Log.h.
Referenced by contact_visual(), and parse_contact_visual().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/log/Log.h
/root/scrimmage/scrimmage/src/log/Log.cpp