SCRIMMAGE: scrimmage::sensor::NoisyContacts Class Reference
scrimmage::sensor::NoisyContacts Class Reference
#include <NoisyContacts.h>
Public Member Functions
NoisyContacts ()
void init (std::map< std::string, std::string > &params) override
bool step () override
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
std::shared_ptr< const Time > getTime ()
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
std::vector< std::shared_ptr< std::normal_distribution< double > > > pos_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > vel_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > orient_noise_
PublisherPtr pub_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file NoisyContacts.h.
Constructor & Destructor Documentation
NoisyContacts()
scrimmage::sensor::NoisyContacts::NoisyContacts ()
Referenced by REGISTER_PLUGIN().
Member Function Documentation
init()
void scrimmage::sensor::NoisyContacts::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Sensor.
Referenced by REGISTER_PLUGIN().
step()
bool scrimmage::sensor::NoisyContacts::step () override virtual
Reimplemented from scrimmage::Sensor.
Referenced by REGISTER_PLUGIN().
Member Data Documentation
pos_noise_
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyContacts::pos_noise_ protected
Definition at line 53 of file NoisyContacts.h.
Referenced by REGISTER_PLUGIN().
vel_noise_
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyContacts::vel_noise_ protected
Definition at line 54 of file NoisyContacts.h.
Referenced by REGISTER_PLUGIN().
orient_noise_
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::NoisyContacts::orient_noise_ protected
Definition at line 55 of file NoisyContacts.h.
Referenced by REGISTER_PLUGIN().
pub_
PublisherPtr scrimmage::sensor::NoisyContacts::pub_ protected
Definition at line 56 of file NoisyContacts.h.
Referenced by REGISTER_PLUGIN().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/NoisyContacts/NoisyContacts.h