SCRIMMAGE: scrimmage::controller::JSBSimModelControllerHeadingPID Class Reference
scrimmage::controller::JSBSimModelControllerHeadingPID Class Reference
#include <JSBSimModelControllerHeadingPID.h>
Public Member Functions
virtual void init (std::map< std::string, std::string > &params)
virtual bool step (double t, double dt)
Public Member Functions inherited from scrimmage::Controller
void set_state (StatePtr &state)
void set_desired_state (StatePtr &desired_state)
void close (double) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
std::shared_ptr< const Time > getTime ()
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
Angles angles_to_jsbsim_
Angles angles_from_jsbsim_
PID heading_pid_
double prev_desired_yaw_
bool heading_lag_initialized_
double max_bank_
int input_vel_idx_ = 0
int input_heading_idx_ = 0
int input_alt_idx_ = 0
int output_vel_idx_ = 0
int output_bank_idx_ = 0
int output_alt_idx_ = 0
Protected Attributes inherited from scrimmage::Controller
StatePtr state_
StatePtr desired_state_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file JSBSimModelControllerHeadingPID.h.
Member Function Documentation
init()
void scrimmage::controller::JSBSimModelControllerHeadingPID::init (std::map< std::string, std::string > & params) virtual
Reimplemented from scrimmage::Controller.
Definition at line 47 of file JSBSimModelControllerHeadingPID.cpp.
{
     angles_from_jsbsim_.set_input_clock_direction(ang::Rotate::CW);
     angles_from_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_Y);
     angles_from_jsbsim_.set_output_clock_direction(ang::Rotate::CCW);
     angles_from_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_input_clock_direction(ang::Rotate::CCW);
     angles_to_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_output_clock_direction(ang::Rotate::CW);
     angles_to_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_Y);
     std::string pid_gains_ = scrimmage::get("heading_pid", params, "1.0, 0.5, 0.0, 4.5");
     heading_pid_.init(pid_gains_, true);
     heading_lag_initialized_ = false;
     max_bank_ = ang::deg2rad(std::stod(params.at("max_bank")));
     input_vel_idx_ = vars_.declare(VariableIO::Type::desired_speed, VariableIO::Direction::In);
     input_heading_idx_ = vars_.declare(VariableIO::Type::desired_heading, VariableIO::Direction::In);
     input_alt_idx_ = vars_.declare(VariableIO::Type::desired_altitude, VariableIO::Direction::In);
     output_vel_idx_ = vars_.declare(VariableIO::Type::desired_speed, VariableIO::Direction::Out);
     output_bank_idx_ = vars_.declare(VariableIO::Type::desired_roll, VariableIO::Direction::Out);
     // Is the motion model using pitch or altitude control
     std::string z_name = vars_.exists(VariableIO::Type::desired_pitch, VariableIO::Direction::Out) ?
         vars_.type_map().at(VariableIO::Type::desired_pitch) :
         vars_.type_map().at(VariableIO::Type::desired_altitude);
     output_alt_idx_ = vars_.declare(z_name, VariableIO::Direction::Out);
 }
References angles_from_jsbsim_, angles_to_jsbsim_, scrimmage::Angles::CCW, scrimmage::Angles::CW, scrimmage::VariableIO::declare(), scrimmage::Angles::deg2rad(), scrimmage::VariableIO::desired_altitude, scrimmage::VariableIO::desired_heading, scrimmage::VariableIO::desired_pitch, scrimmage::VariableIO::desired_roll, scrimmage::VariableIO::desired_speed, scrimmage::VariableIO::exists(), scrimmage::get(), heading_lag_initialized_, heading_pid_, scrimmage::VariableIO::In, scrimmage::PID::init(), input_alt_idx_, input_heading_idx_, input_vel_idx_, max_bank_, scrimmage::VariableIO::Out, output_alt_idx_, output_bank_idx_, output_vel_idx_, scrimmage::Angles::Pos_X, scrimmage::Angles::Pos_Y, scrimmage::Angles::set_input_clock_direction(), scrimmage::Angles::set_input_zero_axis(), scrimmage::Angles::set_output_clock_direction(), scrimmage::Angles::set_output_zero_axis(), scrimmage::VariableIO::type_map(), and scrimmage::EntityPlugin::vars_.
step()
bool scrimmage::controller::JSBSimModelControllerHeadingPID::step (double t, double dt) virtual
Reimplemented from scrimmage::Controller.
Definition at line 80 of file JSBSimModelControllerHeadingPID.cpp.
{
     double desired_yaw = vars_.input(input_heading_idx_);
     angles_to_jsbsim_.set_angle(ang::rad2deg(desired_yaw));
     desired_yaw = ang::deg2rad(angles_to_jsbsim_.angle());
     desired_yaw = ang::angle_pi(desired_yaw);
     double yaw = state_->quat().yaw();
     angles_to_jsbsim_.set_angle(ang::rad2deg(yaw));
     yaw = ang::deg2rad(angles_to_jsbsim_.angle());
     yaw = ang::angle_pi(yaw);
     // TODO: Chatter occurs when a command heading changes by 180 degrees
     // Might have to use the lag
     double desired_yaw_lag;
     if (heading_lag_initialized_) {
         double k = 1.00; // disable lag
         if (ang::angle_pi(std::abs(desired_yaw - yaw)) > 2.35619) {
             k = dt * 0.75;
         }
         desired_yaw_lag = desired_yaw * k + (1.0 - k) * prev_desired_yaw_;
     } else {
         desired_yaw_lag = desired_yaw;
         if (!std::isnan(desired_yaw_lag)) {
             heading_lag_initialized_ = true;
         }
     }
     prev_desired_yaw_ = desired_yaw_lag;
     // Convert desired heading to bank angle:
     heading_pid_.set_setpoint(desired_yaw_lag);
     double bank_cmd = heading_pid_.step(dt, yaw);
     bank_cmd = boost::algorithm::clamp(bank_cmd, -max_bank_, max_bank_);
     // save what was used as the input
     vars_.output(output_vel_idx_, vars_.input(input_vel_idx_));
     vars_.output(output_bank_idx_, bank_cmd);
     vars_.output(output_alt_idx_, vars_.input(input_alt_idx_));
     return true;
 }
References scrimmage::Angles::angle(), scrimmage::Angles::angle_pi(), angles_to_jsbsim_, scrimmage::Angles::deg2rad(), heading_lag_initialized_, heading_pid_, scrimmage::VariableIO::input(), input_alt_idx_, input_heading_idx_, input_vel_idx_, max_bank_, scrimmage::VariableIO::output(), output_alt_idx_, output_bank_idx_, output_vel_idx_, prev_desired_yaw_, scrimmage::Angles::rad2deg(), scrimmage::Angles::set_angle(), scrimmage::PID::set_setpoint(), scrimmage::Controller::state_, scrimmage::PID::step(), and scrimmage::EntityPlugin::vars_.
Member Data Documentation
angles_to_jsbsim_
Angles scrimmage::controller::JSBSimModelControllerHeadingPID::angles_to_jsbsim_ protected
Definition at line 52 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
angles_from_jsbsim_
Angles scrimmage::controller::JSBSimModelControllerHeadingPID::angles_from_jsbsim_ protected
Definition at line 53 of file JSBSimModelControllerHeadingPID.h.
Referenced by init().
heading_pid_
PID scrimmage::controller::JSBSimModelControllerHeadingPID::heading_pid_ protected
Definition at line 55 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
prev_desired_yaw_
double scrimmage::controller::JSBSimModelControllerHeadingPID::prev_desired_yaw_ protected
Definition at line 56 of file JSBSimModelControllerHeadingPID.h.
Referenced by step().
heading_lag_initialized_
bool scrimmage::controller::JSBSimModelControllerHeadingPID::heading_lag_initialized_ protected
Definition at line 57 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
max_bank_
double scrimmage::controller::JSBSimModelControllerHeadingPID::max_bank_ protected
Definition at line 58 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
input_vel_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::input_vel_idx_ = 0 protected
Definition at line 60 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
input_heading_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::input_heading_idx_ = 0 protected
Definition at line 61 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
input_alt_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::input_alt_idx_ = 0 protected
Definition at line 62 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
output_vel_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::output_vel_idx_ = 0 protected
Definition at line 64 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
output_bank_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::output_bank_idx_ = 0 protected
Definition at line 65 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
output_alt_idx_
int scrimmage::controller::JSBSimModelControllerHeadingPID::output_alt_idx_ = 0 protected
Definition at line 66 of file JSBSimModelControllerHeadingPID.h.
Referenced by init(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/controller/JSBSimModelControllerHeadingPID/JSBSimModelControllerHeadingPID.h
/root/scrimmage/scrimmage/src/plugins/controller/JSBSimModelControllerHeadingPID/JSBSimModelControllerHeadingPID.cpp