SCRIMMAGE: scrimmage::PluginManager Class Reference
scrimmage::PluginManager Class Reference
#include <PluginManager.h>
Public Types
typedef const char *(* plugin_name_t) ()
typedef const char *(* plugin_type_t) ()
Public Member Functions
PluginManager ()
void print_plugins (const std::string &plugin_type, const std::string &title, FileSearch &file_search, const std::string &env_var_name="SCRIMMAGE_PLUGIN_PATH")
void print_returned_plugins ()
void find_matching_plugins (const std::string &plugin_name_so, std::unordered_map< std::string, std::list< std::string >> &so_files, std::list< std::string > &plugins)
template<class T >
PluginStatus< T > make_plugin (std::string plugin_type, const std::string &plugin_name_xml, FileSearch &file_search, ConfigParse &config_parse, const std::map< std::string, std::string > &overrides, const std::set< std::string > &plugin_tags, const std::string &env_var_name="SCRIMMAGE_PLUGIN_PATH")
std::map< std::string, std::unordered_set< std::string > > get_commits ()
void set_reload (bool reload)
bool get_reload ()
Protected Member Functions
int check_library (std::string lib_path)
PluginPtr make_plugin_helper (std::string &plugin_type, std::string &plugin_name)
Protected Attributes
std::map< std::string, std::map< std::string, PluginInfo > > plugins_info_
std::unordered_map< std::string, std::list< std::string > > so_files_
bool files_checked_ = false
bool reload_
Detailed Description
Definition at line 78 of file PluginManager.h.
Member Typedef Documentation
typedef const char*(* scrimmage::PluginManager::plugin_name_t) ()
Definition at line 80 of file PluginManager.h.
typedef const char*(* scrimmage::PluginManager::plugin_type_t) ()
Definition at line 81 of file PluginManager.h.
Constructor & Destructor Documentation
scrimmage::PluginManager::PluginManager ()
Definition at line 109 of file PluginManager.cpp.
 : reload_(false) {}
Member Function Documentation
void scrimmage::PluginManager::print_plugins (const std::string & plugin_type, const std::string & title, FileSearch & file_search, const std::string & env_var_name = "SCRIMMAGE_PLUGIN_PATH")
Definition at line 111 of file PluginManager.cpp.
References check_library(), files_checked_, scrimmage::FileSearch::find_files(), LIB_EXT, plugins_info_, and so_files_.
{
     // make sure all files are loaded
     if (!files_checked_) {
         file_search.find_files(env_var_name, LIB_EXT, so_files_);
         files_checked_ = true;
     }
     for (auto &kv : so_files_) {
         for (std::string &full_path : kv.second) {
             check_library(full_path);
         }
     }
     std::cout << "------------------------------" << std::endl;
     std::cout << title << ": " << std::endl;
     std::cout << "------------------------------" << std::endl;
     if (plugins_info_.count(plugin_type) > 0) {
         for (auto &kv : plugins_info_[plugin_type]) {
             std::cout << kv.first << std::endl;
         }
     } else {
         std::cout << "Plugin type doesn't exist: " << plugin_type << std::endl;
     }
     std::cout << "------------------------------" << std::endl;
 }
void scrimmage::PluginManager::print_returned_plugins ()
Definition at line 140 of file PluginManager.cpp.
References plugins_info_.
{
     std::cout << "using the following plugins:" << std::endl;
     for (auto &kv : plugins_info_) {
         for (auto &kv2 : kv.second) {
             if (kv2.second.returned) {
                 std::cout << kv.first << "::" << kv2.first << std::endl;
             }
         }
     }
 }
void scrimmage::PluginManager::find_matching_plugins (const std::string & plugin_name_so, std::unordered_map< std::string, std::list< std::string >> & so_files, std::list< std::string > & plugins)
Definition at line 196 of file PluginManager.cpp.
References check_library(), and LIB_EXT.
{
     auto it = so_files.find(std::string("lib") + plugin_name_so + LIB_EXT);
     if (it != so_files.end()) {
         for (std::string &full_fname : it->second) {
             if (check_library(full_fname) == 0) {
                 plugins.push_back(full_fname);
             }
         }
         if (plugins.size() > 0) {
             so_files.erase(it);
         }
     }
 }
template<class T > PluginStatus<T> scrimmage::PluginManager::make_plugin (std::string plugin_type, const std::string & plugin_name_xml, FileSearch & file_search, ConfigParse & config_parse, const std::map< std::string, std::string > & overrides, const std::set< std::string > & plugin_tags, const std::string & env_var_name = "SCRIMMAGE_PLUGIN_PATH") inline
Definition at line 97 of file PluginManager.h.
References scrimmage::FileSearch::find_files(), LIB_EXT, scrimmage::ConfigParse::params(), scrimmage::ConfigParse::parse(), scrimmage::PluginStatus< T >::plugin, scrimmage::ConfigParse::set_required(), and scrimmage::PluginStatus< T >::status.
{
         PluginStatus<T> status;
         std::string plugin_name = plugin_name_xml;
         auto it_orig_plugin_name = overrides.find("ORIGINAL_PLUGIN_NAME");
         if (it_orig_plugin_name != overrides.end()) {
             plugin_name = it_orig_plugin_name->second;
         }
         config_parse.set_required("library");
         if (!config_parse.parse(overrides, plugin_name, env_var_name, file_search)) {
             std::cout << "Failed to parse: " << plugin_name << ".xml for type " << plugin_type << std::endl;
             std::cout << "Check that you have sourced ~/.scrimmage/setup.bash "
                       << "(this sets the environment variable " << env_var_name << " to a directory including "
                       << plugin_name << ".xml)" << std::endl;
             status.status = PluginStatus<T>::parse_failed;
             return status;
         }
         // If the plugin_tags aren't empty, then we filter based on plugin_tags
         if (not plugin_tags.empty()) {
             // Does this plugin have a plugin "tags" attribute
             bool valid_tag = false;
             auto it_tags = overrides.find("tags");
             if (it_tags != overrides.end()) {
                 // Break up the plugin's tags attribute into a set of strings
                 auto tags = str2container<std::set<std::string>>(it_tags->second, ", ");
                 // If the plugin_tags contains any tag in tags, this plugin
                 // should be loaded
                 valid_tag = std::any_of(tags.begin(), tags.end(),
                                         [&](const std::string &tag) {
                                             return (plugin_tags.find(tag) !=
                                                     plugin_tags.end());
                                         });
             }
             if (not valid_tag) {
                 status.status = PluginStatus<T>::invalid_tag;
                 return status;
             }
         }
         std::string plugin_name_so = config_parse.params()["library"];
         // first, if this has already been processed, return it
         PluginPtr plugin = make_plugin_helper(plugin_type, plugin_name_so);
         if (plugin != nullptr) {
             status.plugin = std::dynamic_pointer_cast<T>(plugin);
             if (status.plugin == nullptr) {
                 status.status = PluginStatus<T>::cast_failed;
             } else {
                 status.status = PluginStatus<T>::loaded;
             }
             return status;
         }
         if (!files_checked_ && so_files_.empty()) {
             file_search.find_files(env_var_name, LIB_EXT, so_files_);
             files_checked_ = true;
         }
         // Find the shared libraries / plugins that match this name.
         std::list<std::string> matching_plugins;
         find_matching_plugins(plugin_name_so, so_files_, matching_plugins);
         // Warn the user if multiple plugin libraries were found
         if (matching_plugins.size() > 1) {
             std::cout << "WARNING: Multiple paths found for plugin:"
                       << plugin_name_so << std::endl;
             for (const std::string &plugin_path : matching_plugins) {
                 std::cout << plugin_path << std::endl;
             }
         }
         if (matching_plugins.size() > 0) {
             // A matching plugin was found. Create one using make_plugin_helper
             PluginPtr plugin = make_plugin_helper(plugin_type, plugin_name_so);
             status.plugin = std::dynamic_pointer_cast<T>(plugin);
             if (status.plugin == nullptr) {
                 status.status = PluginStatus<T>::cast_failed;
             } else {
                 status.status = PluginStatus<T>::loaded;
             }
             return status;
         }
         std::cout << "ERROR: Could not locate " << plugin_type << "::"
                   << plugin_name_so << std::endl;
         status.status = PluginStatus<T>::missing;
         return status;
     }
std::map< std::string, std::unordered_set< std::string > > scrimmage::PluginManager::get_commits ()
Definition at line 177 of file PluginManager.cpp.
References scrimmage::get_sha(), scrimmage::PluginInfo::name, scrimmage::PluginInfo::path, plugins_info_, and scrimmage::PluginInfo::returned.
{
     std::map<std::string, std::unordered_set<std::string>> commits;
     std::string sha;
     for (auto &kv : plugins_info_) {
         for (auto &kv2 : kv.second) {
             scrimmage::PluginInfo &plugin_info = kv2.second;
             if (!plugin_info.returned) continue;
             std::string path =
                 boost::filesystem::path(plugin_info.path).parent_path().string();
             if ((sha = scrimmage::get_sha(path)) != "") {
                 commits[sha].insert(plugin_info.name);
             }
         }
     }
     return commits;
 }
void scrimmage::PluginManager::set_reload (bool reload)
Definition at line 214 of file PluginManager.cpp.
References reload_.
 {reload_ = reload;}
bool scrimmage::PluginManager::get_reload ()
Definition at line 216 of file PluginManager.cpp.
References reload_.
 {return reload_;}
int scrimmage::PluginManager::check_library (std::string lib_path) protected
Definition at line 49 of file PluginManager.cpp.
References scrimmage::PluginInfo::handle, scrimmage::PluginInfo::name, scrimmage::PluginInfo::path, plugins_info_, and scrimmage::PluginInfo::type.
Referenced by find_matching_plugins(), and print_plugins().
{
     void *lib_handle;
 #ifdef __APPLE__
     lib_handle = dlopen(lib_path.c_str(), RTLD_LAZY | RTLD_GLOBAL);
 #else
     lib_handle = dlopen(lib_path.c_str(), RTLD_LAZY | RTLD_LOCAL);
 #endif
     if (!lib_handle) {
         std::cout << "Trying to open " << lib_path;
         fprintf(stdout, ", dlopen failed: %s\n", dlerror());
         std::cout << std::endl;
         return -1;
     }
     char * error;
     // Extract the plugin type
     plugin_type_t type_func;
     type_func = (plugin_type_t)dlsym(lib_handle, "plugin_type");
     if ((error = dlerror()) != NULL)  {
         // fputs(error, stderr);
         std::cout << lib_path << " doesn't contain 'plugin_type'" << std::endl;
         dlclose(lib_handle);
         return 1;
     }
     std::string plugin_type((*type_func)());
     // Extract the plugin name
     plugin_name_t name_func;
     name_func = (plugin_name_t)dlsym(lib_handle, "plugin_name");
     if ((error = dlerror()) != NULL)  {
         // fputs(error, stderr);
         std::cout << lib_path << " doesn't contain 'plugin_name'" << std::endl;
         dlclose(lib_handle);
         return 3;
     }
     std::string plugin_name((*name_func)());
     // Ensure the maker function exists, but we don't need to call it
     dlsym(lib_handle, "maker");
     if ((error = dlerror()) != NULL)  {
         fputs(error, stderr);
         std::cout << lib_path << " doesn't contain 'maker'" << std::endl;
         dlclose(lib_handle);
         return 4;
     }
     PluginInfo info;
     info.name = plugin_name;
     info.type = plugin_type;
     info.path = lib_path;
     info.handle = lib_handle;
     plugins_info_[plugin_type][plugin_name] = info;
     // dlclose(lib_handle);
     return 0;
 }
PluginPtr scrimmage::PluginManager::make_plugin_helper (std::string & plugin_type, std::string & plugin_name) protected
Definition at line 151 of file PluginManager.cpp.
References plugins_info_, and reload_.
{
     auto it = plugins_info_.find(plugin_type);
     if (it != plugins_info_.end()) {
         auto it2 = it->second.find(plugin_name);
         if (it2 != it->second.end()) {
             it2->second.returned = true;
             if (reload_ && it2->second.handle) {
                 dlclose(it2->second.handle);
             }
             PluginPtr (*maker_func)(void);
             // cppcheck-suppress cstyleCast
             maker_func = (PluginPtr (*)(void))dlsym(it2->second.handle, "maker");
             char * error;
             if ((error = dlerror()) != NULL)  {
                 fputs(error, stderr);
                 return nullptr;
             } else {
                 return (*maker_func)();
             }
         }
     }
     return nullptr;
 }
Member Data Documentation
std::map<std::string, std::map<std::string, PluginInfo> > scrimmage::PluginManager::plugins_info_ protected
Definition at line 203 of file PluginManager.h.
Referenced by check_library(), get_commits(), make_plugin_helper(), print_plugins(), and print_returned_plugins().
std::unordered_map<std::string, std::list<std::string> > scrimmage::PluginManager::so_files_ protected
Definition at line 205 of file PluginManager.h.
Referenced by print_plugins().
bool scrimmage::PluginManager::files_checked_ = false protected
Definition at line 206 of file PluginManager.h.
Referenced by print_plugins().
bool scrimmage::PluginManager::reload_ protected
Definition at line 210 of file PluginManager.h.
Referenced by get_reload(), make_plugin_helper(), and set_reload().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugin_manager/PluginManager.h
/root/scrimmage/scrimmage/src/plugin_manager/PluginManager.cpp