SCRIMMAGE: scrimmage::FrameUpdateClient Class Reference
scrimmage::FrameUpdateClient Class Reference
#include <FrameUpdateClient.h>
Public Member Functions
FrameUpdateClient (const std::string &ip, int port)
bool send_frame (scrimmage_proto::Frame &frame)
void set_projection (const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
Private Attributes
std::shared_ptr< GeographicLib::LocalCartesian > proj_
Angles angles_to_gps_
Detailed Description
Definition at line 48 of file FrameUpdateClient.h.
Constructor & Destructor Documentation
scrimmage::FrameUpdateClient::FrameUpdateClient (const std::string & ip, int port)
Definition at line 60 of file FrameUpdateClient.cpp.
                                                                   :
     angles_to_gps_(0, Angles::Type::EUCLIDEAN, Angles::Type::GPS) {}
Member Function Documentation
bool scrimmage::FrameUpdateClient::send_frame (scrimmage_proto::Frame & frame)
Definition at line 63 of file FrameUpdateClient.cpp.
References scrimmage::Angles::angle(), angles_to_gps_, scrimmage::Angles::deg2rad(), proj_, scrimmage::Angles::rad2deg(), scrimmage::Angles::set_angle(), and scrimmage::Quaternion::yaw().
{
     // Change from local x, y, z to GPS coordinates:
     for (int i = 0; i < frame.contact_size(); i++) {
         // frame.contacts_[frame.contact(i).id().id()] = proto_2_contact(proto_frame.contact(i));
         double x = frame.contact(i).state().position().x();
         double y = frame.contact(i).state().position().y();
         double z = frame.contact(i).state().position().z();
         double lat, lon, h;
         proj_->Reverse(x, y, z, lat, lon, h);
         frame.mutable_contact(i)->mutable_state()->mutable_position()->set_x(lon);
         frame.mutable_contact(i)->mutable_state()->mutable_position()->set_y(lat);
         frame.mutable_contact(i)->mutable_state()->mutable_position()->set_z(h);
         x = frame.contact(i).state().orientation().x();
         y = frame.contact(i).state().orientation().y();
         z = frame.contact(i).state().orientation().z();
         double w = frame.contact(i).state().orientation().w();
         // scrimmage::Quaternion q(Eigen::Vector3d(x,y,z), w);
         scrimmage::Quaternion q(w, x, y, z);
         double yaw = q.yaw();
         angles_to_gps_.set_angle(Angles::rad2deg(yaw));
         yaw = Angles::deg2rad(angles_to_gps_.angle());
         q = scrimmage::Quaternion(q.roll(), q.pitch(), yaw);
         frame.mutable_contact(i)->mutable_state()->mutable_orientation()->set_x(q.x());
         frame.mutable_contact(i)->mutable_state()->mutable_orientation()->set_y(q.y());
         frame.mutable_contact(i)->mutable_state()->mutable_orientation()->set_z(q.z());
         frame.mutable_contact(i)->mutable_state()->mutable_orientation()->set_w(q.w());
         frame.mutable_contact(i)->set_type(scrimmage_proto::AIRCRAFT);
     }
 #if ENABLE_GRPC == 1
     scrimmage_proto::BlankReply reply;
     // Context for the client. It could be used to convey extra information to
     // the server and/or tweak certain RPC behaviors.
     grpc::ClientContext context;
     // The actual RPC.
     grpc::Status status;
     status = stub_->SendFrame(&context, frame, &reply);
     // Act upon its status.
     if (status.ok()) {
         return true;
     } else {
         cout << "Error code: " << status.error_code() << endl;
         cout << status.error_message() << endl;
         return false;
     }
 #endif
     return true;
 }
void scrimmage::FrameUpdateClient::set_projection (const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 122 of file FrameUpdateClient.cpp.
References proj_.
{
     proj_ = proj;
 }
Member Data Documentation
std::shared_ptr<GeographicLib::LocalCartesian> scrimmage::FrameUpdateClient::proj_ private
Definition at line 58 of file FrameUpdateClient.h.
Referenced by send_frame(), and set_projection().
Angles scrimmage::FrameUpdateClient::angles_to_gps_ private
Definition at line 59 of file FrameUpdateClient.h.
Referenced by send_frame().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/log/FrameUpdateClient.h
/root/scrimmage/scrimmage/src/log/FrameUpdateClient.cpp