SCRIMMAGE: scrimmage::MotionModel Class Reference
scrimmage::MotionModel Class Reference
#include <MotionModel.h>
Public Types
typedef std::vector< double > vector_t
Public Member Functions
MotionModel ()
std::string type () override
virtual bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params)
virtual bool step (double time, double dt)
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void teleport (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
void ode_step (double dt)
virtual void model (const vector_t &x, vector_t &dxdt, double t)
Protected Attributes
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 48 of file MotionModel.h.
Member Typedef Documentation
typedef std::vector<double> scrimmage::MotionModel::vector_t
Definition at line 50 of file MotionModel.h.
Constructor & Destructor Documentation
scrimmage::MotionModel::MotionModel ()
Definition at line 41 of file MotionModel.cpp.
                          : ext_force_(0, 0, 0), ext_moment_(0, 0, 0),
                              mass_(1.0), g_(9.81) {}
Member Function Documentation
std::string scrimmage::MotionModel::type () override virtual
Reimplemented from scrimmage::Plugin.
Definition at line 44 of file MotionModel.cpp.
 { return std::string("MotionModel"); }
bool scrimmage::MotionModel::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) virtual
Reimplemented in scrimmage::motion::FixedWing6DOF, scrimmage::motion::UUV6DOF, scrimmage::motion::Multirotor, scrimmage::motion::JSBSimControl, scrimmage::motion::JSBSimModel, scrimmage::motion::SimpleAircraft, scrimmage::motion::DoubleIntegrator, scrimmage::motion::RigidBody6DOF, scrimmage::motion::DubinsAirplane, scrimmage::motion::DubinsAirplane3D, scrimmage::motion::Unicycle3D, scrimmage::motion::SimpleQuadrotor, scrimmage::motion::SimpleCar, scrimmage::motion::SingleIntegrator, scrimmage::motion::Unicycle, scrimmage::motion::Ballistic, and scrimmage::motion::HarmonicOscillator.
Definition at line 46 of file MotionModel.cpp.
 { return false; }
bool scrimmage::MotionModel::step (double time, double dt) virtual
Reimplemented in scrimmage::motion::FixedWing6DOF, scrimmage::motion::UUV6DOF, scrimmage::motion::Multirotor, scrimmage::motion::JSBSimControl, scrimmage::motion::JSBSimModel, scrimmage::motion::SimpleAircraft, scrimmage::motion::DoubleIntegrator, scrimmage::motion::RigidBody6DOF, scrimmage::motion::DubinsAirplane, scrimmage::motion::DubinsAirplane3D, scrimmage::motion::Unicycle3D, scrimmage::motion::SimpleQuadrotor, scrimmage::motion::Unicycle, scrimmage::motion::SimpleCar, scrimmage::motion::SingleIntegrator, scrimmage::motion::Ballistic, and scrimmage::motion::HarmonicOscillator.
Definition at line 49 of file MotionModel.cpp.
 { return true; }
bool scrimmage::MotionModel::posthumous (double t) virtual
Definition at line 51 of file MotionModel.cpp.
 { return true; }
StatePtr & scrimmage::MotionModel::state () virtual
Definition at line 53 of file MotionModel.cpp.
References state_.
Referenced by set_state(), and teleport().
 {return state_;}
void scrimmage::MotionModel::set_state (StatePtr & state) virtual
Definition at line 55 of file MotionModel.cpp.
References state(), and state_.
 {state_ = state;}
void scrimmage::MotionModel::teleport (StatePtr & state) virtual
Reimplemented in scrimmage::motion::FixedWing6DOF, scrimmage::motion::JSBSimModel, scrimmage::motion::SimpleAircraft, scrimmage::motion::DoubleIntegrator, and scrimmage::motion::RigidBody6DOF.
Definition at line 57 of file MotionModel.cpp.
References state(), and state_.
 {state_ = state;}
void scrimmage::MotionModel::set_external_force (const Eigen::Vector3d & force) virtual
Definition at line 67 of file MotionModel.cpp.
References ext_force_.
{
     ext_force_ = force;
 }
void scrimmage::MotionModel::set_external_moment (const Eigen::Vector3d & moment) virtual
Definition at line 71 of file MotionModel.cpp.
References ext_moment_.
{
     ext_moment_ = moment;
 }
virtual void scrimmage::MotionModel::set_mass (double mass) inline virtual
Definition at line 65 of file MotionModel.h.
References mass(), and mass_.
 { mass_ = mass; }
virtual double scrimmage::MotionModel::mass () inline virtual
Definition at line 66 of file MotionModel.h.
References mass_.
Referenced by set_mass().
 { return mass_; }
virtual double scrimmage::MotionModel::gravity_magnitude () inline virtual
Definition at line 67 of file MotionModel.h.
References g_.
 { return g_; }
virtual std::vector<double>& scrimmage::MotionModel::full_state_vector () inline virtual
Definition at line 68 of file MotionModel.h.
References close(), model(), ode_step(), and x_.
{
         return x_;
     }
void scrimmage::MotionModel::close (double t) override virtual
Reimplemented from scrimmage::EntityPlugin.
Definition at line 75 of file MotionModel.cpp.
References state_.
Referenced by full_state_vector().
{
     state_ = nullptr;
 }
void scrimmage::MotionModel::ode_step (double dt) protected
Definition at line 59 of file MotionModel.cpp.
References model(), and x_.
Referenced by full_state_vector(), scrimmage::motion::Unicycle::step(), and scrimmage::motion::DoubleIntegrator::step().
{
     auto sys = std::bind(&MotionModel::model, this, pl::_1, pl::_2, pl::_3);
     boost::numeric::odeint::runge_kutta4<std::vector<double>> stepper;
     stepper.do_step(sys, x_, 0, dt);
 }
void scrimmage::MotionModel::model (const vector_t & x, MotionModel::vector_t & dxdt, double t) protected virtual
Reimplemented in scrimmage::motion::FixedWing6DOF, scrimmage::motion::UUV6DOF, scrimmage::motion::Multirotor, scrimmage::motion::SimpleAircraft, scrimmage::motion::DoubleIntegrator, scrimmage::motion::RigidBody6DOF, scrimmage::motion::DubinsAirplane, scrimmage::motion::DubinsAirplane3D, scrimmage::motion::Unicycle3D, scrimmage::motion::SimpleQuadrotor, scrimmage::motion::Unicycle, scrimmage::motion::SimpleCar, scrimmage::motion::Ballistic, and scrimmage::motion::HarmonicOscillator.
Definition at line 65 of file MotionModel.cpp.
Referenced by full_state_vector(), and ode_step().
 {}
Member Data Documentation
StatePtr scrimmage::MotionModel::state_ protected
Definition at line 77 of file MotionModel.h.
Referenced by close(), scrimmage::motion::Unicycle::init(), scrimmage::motion::DoubleIntegrator::init(), set_state(), state(), scrimmage::motion::Unicycle::step(), scrimmage::motion::DoubleIntegrator::step(), and teleport().
vector_t scrimmage::MotionModel::x_ protected
Definition at line 78 of file MotionModel.h.
Referenced by scrimmage::motion::DoubleIntegrator::DoubleIntegrator(), full_state_vector(), scrimmage::motion::Unicycle::init(), scrimmage::motion::DoubleIntegrator::init(), scrimmage::motion::DoubleIntegrator::model(), ode_step(), scrimmage::motion::Unicycle::step(), scrimmage::motion::DoubleIntegrator::step(), and scrimmage::motion::DoubleIntegrator::teleport().
Eigen::Vector3d scrimmage::MotionModel::ext_force_ protected
Definition at line 80 of file MotionModel.h.
Referenced by set_external_force().
Eigen::Vector3d scrimmage::MotionModel::ext_moment_ protected
Definition at line 81 of file MotionModel.h.
Referenced by set_external_moment().
double scrimmage::MotionModel::mass_ protected
Definition at line 82 of file MotionModel.h.
Referenced by mass(), and set_mass().
double scrimmage::MotionModel::g_ protected
Definition at line 83 of file MotionModel.h.
Referenced by gravity_magnitude(), and scrimmage::motion::Unicycle::step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/motion/MotionModel.h
/root/scrimmage/scrimmage/src/plugin_manager/MotionModel.cpp