SCRIMMAGE: scrimmage::motion::MultirotorState Class Reference
scrimmage::motion::MultirotorState Class Reference
#include <MultirotorState.h>
Public Types
enum InputType { OMEGA = 0, PWM }
Public Member Functions
void set_input_type (InputType input_type)
void set_prop_input (Eigen::VectorXd prop_input)
InputType & input_type ()
Eigen::VectorXd & prop_input ()
Public Member Functions inherited from scrimmage::State
State ()
State (Eigen::Vector3d _pos, Eigen::Vector3d _vel, Eigen::Vector3d _ang_vel, Quaternion _quat)
virtual ~State ()
Eigen::Vector3d & pos ()
Eigen::Vector3d & vel ()
Eigen::Vector3d & ang_vel ()
const Eigen::Vector3d & pos () const
const Eigen::Vector3d & vel () const
const Eigen::Vector3d & ang_vel () const
Quaternion & quat ()
const Quaternion & quat () const
const Eigen::Vector3d & pos_const () const
const Eigen::Vector3d & vel_const () const
const Eigen::Vector3d & ang_vel_const () const
const Quaternion & quat_const () const
void set_pos (const Eigen::Vector3d &pos)
void set_vel (const Eigen::Vector3d &vel)
void set_ang_vel (const Eigen::Vector3d &ang_vel)
void set_quat (const Quaternion &quat)
bool InFieldOfView (State &other, double fov_width, double fov_height) const
Returns true if other state is in field-of-view.
Eigen::Vector3d rel_pos_local_frame (Eigen::Vector3d &other) const
convert the relative position to the local frame (the output vector will point to the other state)
Eigen::Vector3d pos_offset (double distance, bool offset_with_velocity=true) const
return position offset by trailing_distance in the direction of velocity or orientation
Eigen::Vector3d orient_global_frame () const
returns the vector extending forward
double rel_az (const Eigen::Vector3d &other) const
Eigen::Matrix4d tf_matrix (bool enable_translate=true)
Protected Attributes
Eigen::VectorXd prop_input_
InputType input_type_
Protected Attributes inherited from scrimmage::State
Eigen::Vector3d pos_
Eigen::Vector3d vel_
Eigen::Vector3d ang_vel_
Quaternion quat_
Additional Inherited Members
Static Public Member Functions inherited from scrimmage::State
template<class T , class = std::enable_if_t< !std::is_same<T, scrimmage::State>::value && std::is_base_of<scrimmage::State, T>::value, void>>
static std::shared_ptr< T > cast (std::shared_ptr< scrimmage::State > state)
Downcast a scrimmage::State to a subclassed type, returing nullptr if not successful.
Public Attributes inherited from scrimmage::State
uint8_t output_precision = 2
Detailed Description
Definition at line 45 of file MultirotorState.h.
Member Enumeration Documentation
InputType
enum scrimmage::motion::MultirotorState::InputType
Enumerator
OMEGA
PWM
Definition at line 47 of file MultirotorState.h.
                    {
         OMEGA = 0,
         PWM
     };
Member Function Documentation
set_input_type()
void scrimmage::motion::MultirotorState::set_input_type (InputType input_type) inline
Definition at line 52 of file MultirotorState.h.
{
         input_type_ = input_type;
     }
References input_type(), and input_type_.
set_prop_input()
void scrimmage::motion::MultirotorState::set_prop_input (Eigen::VectorXd prop_input) inline
Definition at line 56 of file MultirotorState.h.
{
         prop_input_ = prop_input;
     }
References prop_input(), and prop_input_.
input_type()
InputType& scrimmage::motion::MultirotorState::input_type () inline
Definition at line 60 of file MultirotorState.h.
{
         return input_type_;
     }
References input_type_.
Referenced by set_input_type().
prop_input()
Eigen::VectorXd& scrimmage::motion::MultirotorState::prop_input () inline
Definition at line 64 of file MultirotorState.h.
{
         return prop_input_;
     }
References prop_input_.
Referenced by set_prop_input().
Member Data Documentation
prop_input_
Eigen::VectorXd scrimmage::motion::MultirotorState::prop_input_ protected
Definition at line 69 of file MultirotorState.h.
Referenced by prop_input(), and set_prop_input().
input_type_
InputType scrimmage::motion::MultirotorState::input_type_ protected
Definition at line 70 of file MultirotorState.h.
Referenced by input_type(), and set_input_type().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/Multirotor/MultirotorState.h