SCRIMMAGE: scrimmage::autonomy::Waypoint Class Reference
scrimmage::autonomy::Waypoint Class Reference
#include <Waypoint.h>
Public Member Functions
Waypoint ()=default
Waypoint (const double &latitude, const double &longitude, const double &altitude)
Waypoint (const double &x, const double &y, const double &z, const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
Waypoint (const Eigen::Vector3d &xyz, const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
Waypoint (const scrimmage_msgs::Waypoint &wp)
void set_id (const size_t &id)
void set_time (const double &time)
void set_latitude (const double &latitude)
void set_longitude (const double &longitude)
void set_altitude (const double &altitude)
void set_quat (const scrimmage::Quaternion &quat)
void set_position_tolerance (const double &pos_tol)
void set_quat_tolerance (const double &quat_tol)
scrimmage_msgs::Waypoint lla_proto ()
const size_t & id () const
const double & time () const
const double & latitude () const
const double & longitude () const
const double & altitude () const
const scrimmage::Quaternion & quat () const
const double & position_tolerance () const
const double & quat_tolerance () const
Eigen::Vector3d xyz (const std::shared_ptr< GeographicLib::LocalCartesian > &proj) const
bool is_within_tolerance (const scrimmage::StatePtr &state, const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
Protected Attributes
size_t id_ = 0
double time_ = 0.0
double latitude_ = 0.0
double longitude_ = 0.0
double altitude_ = 0.0
scrimmage::Quaternion quat_
double position_tolerance_ = 100.0
double quat_tolerance_ = 100.0
bool tolerance_in_2d_ = false
Friends
std::ostream & operator<< (std::ostream &os, Waypoint &wp)
bool operator== (const Waypoint &lhs, const Waypoint &rhs)
Detailed Description
Definition at line 50 of file Waypoint.h.
Constructor & Destructor Documentation
Waypoint() [1/5]
scrimmage::autonomy::Waypoint::Waypoint () default
Waypoint() [2/5]
scrimmage::autonomy::Waypoint::Waypoint (const double & latitude, const double & longitude, const double & altitude)
Definition at line 48 of file Waypoint.cpp.
     : latitude_(latitude), longitude_(longitude), altitude_(altitude) {}
Waypoint() [3/5]
scrimmage::autonomy::Waypoint::Waypoint (const double & x, const double & y, const double & z, const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 52 of file Waypoint.cpp.
{
     proj->Reverse(x, y, z, latitude_, longitude_, altitude_);
 }
References altitude_, latitude_, and longitude_.
Waypoint() [4/5]
scrimmage::autonomy::Waypoint::Waypoint (const Eigen::Vector3d & xyz, const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 57 of file Waypoint.cpp.
{
     proj->Reverse(xyz(0), xyz(1), xyz(2), latitude_, longitude_, altitude_);
 }
References altitude_, latitude_, longitude_, and xyz().
Waypoint() [5/5]
scrimmage::autonomy::Waypoint::Waypoint (const scrimmage_msgs::Waypoint & wp) explicit
Definition at line 62 of file Waypoint.cpp.
         : id_(wp.id()), time_(wp.time()),
           position_tolerance_(wp.position_tolerance()),
           quat_tolerance_(wp.quat_tolerance()),
           tolerance_in_2d_(wp.tolerance_in_2d()) {
     sc::set(quat_, wp.quat());
     auto get_alt = [] (const sc_msgs::PositionLLA &lla) {
         double alt = 0;
         if (lla.alt_oneof_case() == sc_msgs::PositionLLA::kAltMsl) {
             alt = lla.alt_msl();
         } else {
             std::cout << "Waypoints only support alt_msl()!" << std::endl;
         }
         return alt;
     };
     if (wp.pos_oneof_case() == sc_msgs::Waypoint::kLla) {
         latitude_ = wp.lla().latitude();
         longitude_ = wp.lla().longitude();
         altitude_ = get_alt(wp.lla());
     } else if (wp.pos_oneof_case() == sc_msgs::Waypoint::kXyz) {
         // Convert to lat/lon/alt given origin
         GeographicLib::LocalCartesian proj(wp.xyz().origin().latitude(),
                                            wp.xyz().origin().longitude(),
                                            get_alt(wp.xyz().origin()));
         proj.Reverse(wp.xyz().xyz().x(), wp.xyz().xyz().y(), wp.xyz().xyz().z(),
                      latitude_, longitude_, altitude_);
     }
 }
References altitude_, latitude_, longitude_, quat_, and scrimmage::set().
Member Function Documentation
set_id()
void scrimmage::autonomy::Waypoint::set_id (const size_t & id) inline
Definition at line 61 of file Waypoint.h.
 {id_ = id;}
References id(), and id_.
set_time()
void scrimmage::autonomy::Waypoint::set_time (const double & time) inline
Definition at line 62 of file Waypoint.h.
 { time_ = time; }
References time(), and time_.
Referenced by REGISTER_PLUGIN().
set_latitude()
void scrimmage::autonomy::Waypoint::set_latitude (const double & latitude) inline
Definition at line 63 of file Waypoint.h.
 { latitude_ = latitude; }
References latitude(), and latitude_.
set_longitude()
void scrimmage::autonomy::Waypoint::set_longitude (const double & longitude) inline
Definition at line 64 of file Waypoint.h.
 { longitude_ = longitude; }
References longitude(), and longitude_.
set_altitude()
void scrimmage::autonomy::Waypoint::set_altitude (const double & altitude) inline
Definition at line 65 of file Waypoint.h.
 { altitude_ = altitude; }
References altitude(), and altitude_.
set_quat()
void scrimmage::autonomy::Waypoint::set_quat (const scrimmage::Quaternion & quat) inline
Definition at line 66 of file Waypoint.h.
 { quat_ = quat; }
References quat(), and quat_.
Referenced by REGISTER_PLUGIN().
set_position_tolerance()
void scrimmage::autonomy::Waypoint::set_position_tolerance (const double & pos_tol)
Definition at line 119 of file Waypoint.cpp.
{
     position_tolerance_ = pos_tol >= 0 ? pos_tol : std::numeric_limits<double>::max();
 }
References position_tolerance_.
Referenced by REGISTER_PLUGIN().
set_quat_tolerance()
void scrimmage::autonomy::Waypoint::set_quat_tolerance (const double & quat_tol)
Definition at line 123 of file Waypoint.cpp.
{
     quat_tolerance_ = quat_tol >= 0 ? quat_tol : std::numeric_limits<double>::max();
 }
References quat_tolerance_.
Referenced by REGISTER_PLUGIN().
lla_proto()
scrimmage_msgs::Waypoint scrimmage::autonomy::Waypoint::lla_proto ()
Definition at line 93 of file Waypoint.cpp.
{
     scrimmage_msgs::Waypoint wp;
     wp.set_id(id_);
     wp.set_time(time_);
     sc::set(wp.mutable_quat(), quat_);
     wp.mutable_lla()->set_latitude(latitude_);
     wp.mutable_lla()->set_longitude(longitude_);
     wp.mutable_lla()->set_alt_msl(altitude_);
     wp.set_position_tolerance(position_tolerance_);
     wp.set_quat_tolerance(quat_tolerance_);
     wp.set_tolerance_in_2d(tolerance_in_2d_);
     return wp;
 }
References altitude_, id_, latitude_, longitude_, position_tolerance_, quat_, quat_tolerance_, scrimmage::set(), time_, and tolerance_in_2d_.
id()
const size_t& scrimmage::autonomy::Waypoint::id () const inline
Definition at line 72 of file Waypoint.h.
 { return id_; }
References id_.
Referenced by set_id(), and auction_assign.AuctionAssign::step_autonomy().
time()
const double& scrimmage::autonomy::Waypoint::time () const inline
Definition at line 73 of file Waypoint.h.
 { return time_; }
References time_.
Referenced by scrimmage::autonomy::operator<<(), and set_time().
latitude()
const double& scrimmage::autonomy::Waypoint::latitude () const inline
Definition at line 74 of file Waypoint.h.
 { return latitude_; }
References latitude_.
Referenced by scrimmage::autonomy::operator<<(), scrimmage::autonomy::operator==(), REGISTER_PLUGIN(), and set_latitude().
longitude()
const double& scrimmage::autonomy::Waypoint::longitude () const inline
Definition at line 75 of file Waypoint.h.
 { return longitude_; }
References longitude_.
Referenced by scrimmage::autonomy::operator<<(), scrimmage::autonomy::operator==(), REGISTER_PLUGIN(), and set_longitude().
altitude()
const double& scrimmage::autonomy::Waypoint::altitude () const inline
Definition at line 76 of file Waypoint.h.
 { return altitude_; }
References altitude_.
Referenced by scrimmage::autonomy::operator<<(), scrimmage::autonomy::operator==(), REGISTER_PLUGIN(), and set_altitude().
quat()
const scrimmage::Quaternion& scrimmage::autonomy::Waypoint::quat () const inline
Definition at line 77 of file Waypoint.h.
 { return quat_; }
References quat_.
Referenced by scrimmage::autonomy::operator<<(), and set_quat().
position_tolerance()
const double& scrimmage::autonomy::Waypoint::position_tolerance () const inline
Definition at line 78 of file Waypoint.h.
 { return position_tolerance_; }
References position_tolerance_.
Referenced by scrimmage::autonomy::operator<<().
quat_tolerance()
const double& scrimmage::autonomy::Waypoint::quat_tolerance () const inline
Definition at line 79 of file Waypoint.h.
 { return quat_tolerance_; }
References quat_tolerance_.
Referenced by scrimmage::autonomy::operator<<().
xyz()
Eigen::Vector3d scrimmage::autonomy::Waypoint::xyz (const std::shared_ptr< GeographicLib::LocalCartesian > & proj) const
Definition at line 145 of file Waypoint.cpp.
{
     Eigen::Vector3d p;
     proj->Forward(latitude_, longitude_, altitude_, p(0), p(1), p(2));
     return p;
 }
References altitude_, latitude_, and longitude_.
Referenced by Waypoint().
is_within_tolerance()
bool scrimmage::autonomy::Waypoint::is_within_tolerance (const scrimmage::StatePtr & state, const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 107 of file Waypoint.cpp.
{
     Eigen::Vector3d pos;
     proj->Forward(latitude_, longitude_, altitude_, pos(0), pos(1), pos(2));
     double dist = tolerance_in_2d_ ?
             (state->pos().head<2>() - pos.head<2>()).norm() :
             (state->pos() - pos).norm();
     return dist <= position_tolerance_;
 }
References altitude_, latitude_, longitude_, position_tolerance_, and tolerance_in_2d_.
Referenced by scrimmage::autonomy::WaypointListProcessor::process().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, Waypoint & wp) friend
Definition at line 127 of file Waypoint.cpp.
{
     os << std::setprecision(10)
        << wp.time() << ", "
        << wp.latitude() << ", " << wp.longitude() << ", " << wp.altitude()
        << wp.quat() << ", "
        << wp.position_tolerance() << ", "
        << wp.quat_tolerance();
     return os;
 }
operator==
bool operator== (const Waypoint & lhs, const Waypoint & rhs) friend
Definition at line 137 of file Waypoint.cpp.
{
     auto far = [&](double a, double b) {return std::abs(a - b) > 1.0e-6;};
     return !far(lhs.altitude(), rhs.latitude()) &&
            !far(lhs.longitude(), rhs.longitude()) &&
            !far(lhs.altitude(), rhs.altitude());
 }
Member Data Documentation
id_
size_t scrimmage::autonomy::Waypoint::id_ = 0 protected
Definition at line 93 of file Waypoint.h.
Referenced by id(), lla_proto(), and set_id().
time_
double scrimmage::autonomy::Waypoint::time_ = 0.0 protected
Definition at line 94 of file Waypoint.h.
Referenced by lla_proto(), set_time(), and time().
latitude_
double scrimmage::autonomy::Waypoint::latitude_ = 0.0 protected
Definition at line 95 of file Waypoint.h.
Referenced by is_within_tolerance(), latitude(), lla_proto(), set_latitude(), Waypoint(), and xyz().
longitude_
double scrimmage::autonomy::Waypoint::longitude_ = 0.0 protected
Definition at line 96 of file Waypoint.h.
Referenced by is_within_tolerance(), lla_proto(), longitude(), set_longitude(), Waypoint(), and xyz().
altitude_
double scrimmage::autonomy::Waypoint::altitude_ = 0.0 protected
Definition at line 97 of file Waypoint.h.
Referenced by altitude(), is_within_tolerance(), lla_proto(), set_altitude(), Waypoint(), and xyz().
quat_
scrimmage::Quaternion scrimmage::autonomy::Waypoint::quat_ protected
Definition at line 98 of file Waypoint.h.
Referenced by lla_proto(), quat(), set_quat(), and Waypoint().
position_tolerance_
double scrimmage::autonomy::Waypoint::position_tolerance_ = 100.0 protected
Definition at line 100 of file Waypoint.h.
Referenced by is_within_tolerance(), lla_proto(), position_tolerance(), and set_position_tolerance().
quat_tolerance_
double scrimmage::autonomy::Waypoint::quat_tolerance_ = 100.0 protected
Definition at line 101 of file Waypoint.h.
Referenced by lla_proto(), quat_tolerance(), and set_quat_tolerance().
tolerance_in_2d_
bool scrimmage::autonomy::Waypoint::tolerance_in_2d_ = false protected
Definition at line 103 of file Waypoint.h.
Referenced by is_within_tolerance(), and lla_proto().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/Waypoint.h
/root/scrimmage/scrimmage/src/common/Waypoint.cpp