SCRIMMAGE: scrimmage::autonomy::ScrimmageOpenAIAutonomy Class Reference
scrimmage::autonomy::ScrimmageOpenAIAutonomy Class Reference
#include <ScrimmageOpenAIAutonomy.h>
Public Member Functions
ScrimmageOpenAIAutonomy ()
void init (std::map< std::string, std::string > &params) final
bool step_autonomy (double t, double dt) final
virtual void init_helper (std::map< std::string, std::string > &)
virtual bool step_helper ()
virtual void set_environment ()
virtual std::tuple< bool, double, pybind11::dict > calc_reward ()
int self_id ()
Public Member Functions inherited from scrimmage::Autonomy
Autonomy ()
std::string type () override
virtual bool posthumous (double t)
virtual void init ()
bool ready () override
void close (double t) override
bool need_reset ()
StatePtr & desired_state ()
void set_desired_state (StatePtr desired_state)
ContactMapPtr & get_contacts ()
ContactMap & get_contacts_raw ()
virtual void set_contacts (ContactMapPtr &contacts)
virtual void set_contacts_from_plugin (AutonomyPtr &ptr)
virtual void set_projection (std::shared_ptr< GeographicLib::LocalCartesian > &proj)
scrimmage::RTreePtr & rtree ()
void set_rtree (scrimmage::RTreePtr &rtree)
StatePtr & state ()
virtual void set_state (StatePtr &state)
std::string & logging_msg ()
bool get_is_controlling ()
void set_is_controlling (bool is_controlling)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Public Attributes
std::pair< double, double > reward_range
EnvParams action_space
EnvValues action
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Attributes
std::map< std::string, std::string > params_
pybind11::object tuple_space_
pybind11::object box_space_
int self_id_ = 0
bool first_step_ = true
PublisherPtr pub_reward_ = nullptr
pybind11::object actor_func_ = pybind11::none()
bool nonlearning_mode_ = false
OpenAIObservations observations_
OpenAIActions actions_
bool grpc_mode_ = false
Protected Attributes inherited from scrimmage::Autonomy
std::shared_ptr< GeographicLib::LocalCartesian > proj_
StatePtr state_
StatePtr desired_state_
ContactMapPtr contacts_
scrimmage::RTreePtr rtree_
bool need_reset_
std::string logging_msg_
bool is_controlling_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Detailed Description
Definition at line 71 of file ScrimmageOpenAIAutonomy.h.
Constructor & Destructor Documentation
scrimmage::autonomy::ScrimmageOpenAIAutonomy::ScrimmageOpenAIAutonomy ()
Definition at line 66 of file ScrimmageOpenAIAutonomy.cpp.
                                                  :
     reward_range(-std::numeric_limits<double>::infinity(),
                  std::numeric_limits<double>::infinity()),
     tuple_space_(get_gym_space("Tuple")),
     box_space_(get_gym_space("Box")),
     nonlearning_mode_(false) {}
Member Function Documentation
void scrimmage::autonomy::ScrimmageOpenAIAutonomy::init (std::map< std::string, std::string > & params) final virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 73 of file ScrimmageOpenAIAutonomy.cpp.
References grpc_mode_, init_helper(), nonlearning_mode_, params_, scrimmage::EntityPlugin::parent_, and self_id_.
{
     init_helper(params);
     nonlearning_mode_ = get("nonlearning_mode_openai_plugin", params, true);
     self_id_ = parent_->id().id();
     #if ENABLE_GRPC
     // In case we have multiple agents, add the id to the port number
     grpc_mode_ = get("grpc_mode", params, grpc_mode_);
     std::string module = get("module", params, "my_module");
     std::string actor_func_str = get("actor_init_func", params, "my_func");
     if (grpc_mode_) {
         const size_t port = get("port", params, 50050);
         const std::string grpc_address_ = get("grpc_address", params, "127.0.0.1");
         const std::string port_str = std::to_string(port + parent_->id().id());
         const std::string address = grpc_address_ + ":" + port_str;
         python_cmd_ = std::string("openai_grpc_link.py") + " --port " + port_str
             + " --actor " + module + ":" + actor_func_str
             + " --ip " + grpc_address_;
         auto channel = grpc::CreateChannel(address, grpc::InsecureChannelCredentials());
         openai_stub_ = sp::OpenAI::NewStub(channel);
     }
     #endif
     params_ = params;
 }
bool scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy (double t, double dt) final virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 100 of file ScrimmageOpenAIAutonomy.cpp.
References action, scrimmage::autonomy::OpenAIActions::action_space, action_space, actions_, actor_func_, scrimmage::EntityPlugin::advertise(), box_space_, calc_reward(), scrimmage::EnvParams::continuous_extrema, scrimmage::EnvParams::discrete_count, scrimmage::autonomy::OpenAIActions::distribute_action(), scrimmage::autonomy::OpenAIObservations::ext_sensor_vec(), first_step_, grpc_mode_, scrimmage::autonomy::init_actor_func(), scrimmage::autonomy::NO, nonlearning_mode_, scrimmage::autonomy::OpenAIObservations::observation, scrimmage::autonomy::OpenAIObservations::observation_space, observations_, params_, scrimmage::EntityPlugin::parent_, pub_reward_, step_helper(), tuple_space_, and scrimmage::autonomy::OpenAIObservations::update_observation().
{
     if (nonlearning_mode_) {
         if (pub_reward_ == nullptr) {
             // need contacts size to be set before calling init
             auto p = std::dynamic_pointer_cast<ScrimmageOpenAIAutonomy>(shared_from_this());
             std::tie(actions_, observations_, actor_func_) =
                 init_actor_func({p}, params_, CombineActors::NO, UseGlobalSensor::NO,
                 grpc_mode_);
             pub_reward_ = advertise("GlobalNetwork", "reward");
             #if ENABLE_GRPC
             if (grpc_mode_) {
                 int attempts = 0;
                 bool done = false;
                 while (attempts++ < 10 && !done) {
                     std::cout << "Connecting to gRPC Server attempt: " << attempts << "/10" << std::endl;
                     done = send_env();
                 }
                 // Return an exception saying we could not connect to grpc
                 if (!done) {
                     const std::string err_msg =
                         std::string("Didn't connect to the grpc server. Make sure")
                         + " the grpc client is running and your python"
                         + " bindings are up to date."
                         + "You can start a grpc server with the followning command: "
                         + python_cmd_;
                     throw std::runtime_error(err_msg);
                 }
             }
             #endif
         }
         const size_t num_entities = 1;
         observations_.update_observation(num_entities);
         py::object temp_action;
         if (grpc_mode_) {
             #if ENABLE_GRPC
             boost::optional<sp::Action> proto_act;
             // Convert observation to proto message
             sp::Obs proto_obs = obs_to_proto();
             // Send over GRPC
             proto_act = get_action(proto_obs);
             // Convert proto action back to python action
             if (proto_act) {
                 temp_action = convert_proto_action(*proto_act);
             } else {
                 std::cout << "Bad Action received!" << std::endl;
             }
             #endif
         } else {
             // Get action from actor function called through pybind
             temp_action = actor_func_(observations_.observation);
         }
         bool combine_actors = false;
         actions_.distribute_action(temp_action, combine_actors);
         if (first_step_) {
             // there is no reward on the first step
             first_step_ = false;
         } else {
             bool done;
             double reward;
             py::dict info;
             std::tie(done, reward, info) = calc_reward();
             if (done) {
                 return false;
             }
             if (reward != 0) {
                 auto msg = std::make_shared<Message<std::pair<size_t, double>>>();
                 msg->data.first = parent_->id().id();
                 msg->data.second = reward;
                 pub_reward_->publish(msg);
             }
         }
     }
     return step_helper();
 }
virtual void scrimmage::autonomy::ScrimmageOpenAIAutonomy::init_helper (std::map< std::string, std::string > &) inline virtual
Reimplemented in scrimmage::autonomy::RLSimple.
Definition at line 80 of file ScrimmageOpenAIAutonomy.h.
Referenced by init().
 {}
virtual bool scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_helper () inline virtual
Reimplemented in scrimmage::autonomy::RLSimple.
Definition at line 81 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
 {return true;}
virtual void scrimmage::autonomy::ScrimmageOpenAIAutonomy::set_environment () inline virtual
Reimplemented in scrimmage::autonomy::RLSimple, and scrimmage::autonomy::RLConsensus.
Definition at line 83 of file ScrimmageOpenAIAutonomy.h.
 {}
std::tuple< bool, double, pybind11::dict > scrimmage::autonomy::ScrimmageOpenAIAutonomy::calc_reward () virtual
Reimplemented in scrimmage::autonomy::RLSimple, and scrimmage::autonomy::RLConsensus.
Definition at line 299 of file ScrimmageOpenAIAutonomy.cpp.
Referenced by step_autonomy().
{
     return std::make_tuple(false, 0.0, pybind11::dict());
 }
int scrimmage::autonomy::ScrimmageOpenAIAutonomy::self_id () inline
Definition at line 88 of file ScrimmageOpenAIAutonomy.h.
 {return self_id_;}
Member Data Documentation
std::pair<double, double> scrimmage::autonomy::ScrimmageOpenAIAutonomy::reward_range
Definition at line 85 of file ScrimmageOpenAIAutonomy.h.
EnvParams scrimmage::autonomy::ScrimmageOpenAIAutonomy::action_space
Definition at line 86 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
EnvValues scrimmage::autonomy::ScrimmageOpenAIAutonomy::action
Definition at line 87 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
std::map<std::string, std::string> scrimmage::autonomy::ScrimmageOpenAIAutonomy::params_ protected
Definition at line 101 of file ScrimmageOpenAIAutonomy.h.
Referenced by init(), and step_autonomy().
pybind11::object scrimmage::autonomy::ScrimmageOpenAIAutonomy::tuple_space_ protected
Definition at line 102 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
pybind11::object scrimmage::autonomy::ScrimmageOpenAIAutonomy::box_space_ protected
Definition at line 102 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
int scrimmage::autonomy::ScrimmageOpenAIAutonomy::self_id_ = 0 protected
Definition at line 103 of file ScrimmageOpenAIAutonomy.h.
Referenced by init().
bool scrimmage::autonomy::ScrimmageOpenAIAutonomy::first_step_ = true protected
Definition at line 104 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
PublisherPtr scrimmage::autonomy::ScrimmageOpenAIAutonomy::pub_reward_ = nullptr protected
Definition at line 105 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
pybind11::object scrimmage::autonomy::ScrimmageOpenAIAutonomy::actor_func_ = pybind11::none() protected
Definition at line 106 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
bool scrimmage::autonomy::ScrimmageOpenAIAutonomy::nonlearning_mode_ = false protected
Definition at line 107 of file ScrimmageOpenAIAutonomy.h.
Referenced by init(), and step_autonomy().
OpenAIObservations scrimmage::autonomy::ScrimmageOpenAIAutonomy::observations_ protected
Definition at line 108 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
OpenAIActions scrimmage::autonomy::ScrimmageOpenAIAutonomy::actions_ protected
Definition at line 109 of file ScrimmageOpenAIAutonomy.h.
Referenced by step_autonomy().
bool scrimmage::autonomy::ScrimmageOpenAIAutonomy::grpc_mode_ = false protected
Definition at line 113 of file ScrimmageOpenAIAutonomy.h.
Referenced by init(), and step_autonomy().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.h
/root/scrimmage/scrimmage/src/plugins/autonomy/ScrimmageOpenAIAutonomy/ScrimmageOpenAIAutonomy.cpp