SCRIMMAGE: scrimmage::controller::SimpleQuadrotorControllerLQR Class Reference
scrimmage::controller::SimpleQuadrotorControllerLQR Class Reference
#include <SimpleQuadrotorControllerLQR.h>
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step (double t, double dt) override
Eigen::Vector4d & u () override
Public Member Functions inherited from scrimmage::Controller
void set_state (StatePtr &state)
void set_desired_state (StatePtr &desired_state)
void close (double) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
Eigen::Vector4d u_
scrimmage::PID vel_pid_
double prev_yaw_ = NAN
double max_vel_
Protected Attributes inherited from scrimmage::Controller
StatePtr state_
StatePtr desired_state_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 43 of file SimpleQuadrotorControllerLQR.h.
Member Function Documentation
void scrimmage::controller::SimpleQuadrotorControllerLQR::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Controller.
Definition at line 48 of file SimpleQuadrotorControllerLQR.cpp.
References scrimmage::get().
{
     double p_gain = sc::get("vel_p_gain", params, 1.0);
     double i_gain = sc::get("vel_i_gain", params, 1.0);
     double d_gain = sc::get("vel_d_gain", params, 1.0);
     double i_lim = sc::get("i_lim", params, 1.0);
     vel_pid_.set_parameters(p_gain, i_gain, d_gain);
     vel_pid_.set_integral_band(i_lim);
     max_vel_ = std::stod(params["max_vel"]);
 }
bool scrimmage::controller::SimpleQuadrotorControllerLQR::step (double t, double dt) override virtual
Reimplemented from scrimmage::Controller.
Definition at line 59 of file SimpleQuadrotorControllerLQR.cpp.
References scrimmage::Angles::angle_diff_rad(), scrimmage::Angles::angle_pi(), scrimmage::motion::q1, and scrimmage::motion::q2.
{
     Eigen::Vector3d &des_pos = desired_state_->pos();
     double des_yaw = desired_state_->quat().yaw();
     Eigen::Vector3d &pos = state_->pos();
     Eigen::Vector3d &vel = state_->vel();
     double yaw = state_->quat().yaw();
     double xy_speed = vel.head<2>().norm();
     double yaw_dot =
         std::isnan(prev_yaw_) ? 0 : sc::Angles::angle_diff_rad(yaw, prev_yaw_) / dt;
     prev_yaw_ = yaw;
     // LQR Altitude Controller:
     double q1 = 1;
     double z_thrust = -1.0 / q1 * (pos(2) - des_pos(2)) - sqrt(2.0/q1) * vel(2);
     // LQR Heading Controller:
     double q2 = 1;
     double turn_force = -1.0 / q2 * sc::Angles::angle_pi(yaw - des_yaw) - sqrt(2.0/q2) * yaw_dot;
     // If not close to x/y position, use forward velocity:
     double dist = (des_pos - pos).head<2>().norm();
     vel_pid_.set_setpoint((dist < 10) ? 0 : dist / 10);
     double ctrl_vel = vel_pid_.step(dt, xy_speed);
     u_(0) = boost::algorithm::clamp(ctrl_vel, -max_vel_, max_vel_);
     u_(1) = 0;
     u_(2) = z_thrust;
     u_(3) = turn_force;
     return true;
 }
Eigen::Vector4d& scrimmage::controller::SimpleQuadrotorControllerLQR::u () inline override virtual
Implements scrimmage::motion::SimpleQuadrotor::Controller.
Definition at line 47 of file SimpleQuadrotorControllerLQR.h.
References u_.
 {return u_;}
Member Data Documentation
Eigen::Vector4d scrimmage::controller::SimpleQuadrotorControllerLQR::u_ protected
Definition at line 50 of file SimpleQuadrotorControllerLQR.h.
Referenced by u().
scrimmage::PID scrimmage::controller::SimpleQuadrotorControllerLQR::vel_pid_ protected
Definition at line 51 of file SimpleQuadrotorControllerLQR.h.
double scrimmage::controller::SimpleQuadrotorControllerLQR::prev_yaw_ = NAN protected
Definition at line 52 of file SimpleQuadrotorControllerLQR.h.
double scrimmage::controller::SimpleQuadrotorControllerLQR::max_vel_ protected
Definition at line 53 of file SimpleQuadrotorControllerLQR.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/controller/SimpleQuadrotorControllerLQR/SimpleQuadrotorControllerLQR.h
/root/scrimmage/scrimmage/src/plugins/controller/SimpleQuadrotorControllerLQR/SimpleQuadrotorControllerLQR.cpp