SCRIMMAGE: scrimmage::Angles Class Reference
scrimmage::Angles Class Reference
#include <Angles.h>
Public Types
enum Type { Type::GPS, Type::EUCLIDEAN }
enum Rotate { Rotate::CCW = 0, Rotate::CW }
enum HeadingZero { HeadingZero::Pos_X = 1, HeadingZero::Pos_Y = 2, HeadingZero::Neg_X = 3, HeadingZero::Neg_Y = 4 }
Public Member Functions
Angles ()
Angles (double angle, Type input_type, Type output_type)
void set_input_clock_direction (Rotate direction)
void set_input_zero_axis (HeadingZero zero)
void set_output_clock_direction (Rotate direction)
void set_output_zero_axis (HeadingZero zero)
bool is_angle_360 (double angle)
void set_angle (double angle)
double angle ()
Static Public Member Functions
static double deg2rad (double deg)
static double rad2deg (double rad)
static double angle_360 (double angle)
static double angle_2pi (double angle)
static double angle_180 (double angle)
static double angle_pi (double angle)
static double angle_diff (double ang1, double ang2)
shortest angle from ang2 to ang1
static double angle_diff_rad (double ang1, double ang2)
shortest angle from ang2 to ang1 (radians)
static bool angle_within (double ang1, double ang2, double ang)
returns whether ang is within the wedge between ang1 and ang2 where the wedge is less than 180 degrees
static bool angle_within_rad (double ang1, double ang2, double ang)
returns whether ang is within the wedge between ang1 and ang2 where the wedge is less than PI radians
static double angle_avg (double ang1, double ang2)
static double angle_avg_rad (double ang1, double ang2)
Protected Attributes
double angle_ = 0
Rotate in_direction_ = Rotate::CCW
HeadingZero in_zero_ = HeadingZero::Pos_X
Rotate out_direction_ = Rotate::CCW
HeadingZero out_zero_ = HeadingZero::Pos_X
Detailed Description
Definition at line 37 of file Angles.h.
Member Enumeration Documentation
Type
enum scrimmage::Angles::Type strong
Enumerator
GPS
EUCLIDEAN
Definition at line 41 of file Angles.h.
 {GPS, EUCLIDEAN};
Rotate
enum scrimmage::Angles::Rotate strong
Enumerator
CCW
CW
Definition at line 44 of file Angles.h.
                       {
         CCW = 0,
         CW
     };
HeadingZero
enum scrimmage::Angles::HeadingZero strong
Pos_Y | | Neg_X — 0 — Pos_X | | Neg_Y
Enumerator
Pos_X
Pos_Y
Neg_X
Neg_Y
Definition at line 57 of file Angles.h.
{
         Pos_X = 1,
         Pos_Y = 2,
         Neg_X = 3,
         Neg_Y = 4
     };
Constructor & Destructor Documentation
Angles() [1/2]
scrimmage::Angles::Angles ()
Definition at line 41 of file Angles.cpp.
 {}
Angles() [2/2]
scrimmage::Angles::Angles (double angle, Type input_type, Type output_type)
Definition at line 43 of file Angles.cpp.
{
     if (input_type == Type::GPS) {
         in_zero_ = HeadingZero::Pos_Y;
         in_direction_ = Rotate::CW;
     } else if (input_type == Type::EUCLIDEAN) {
         in_zero_ = HeadingZero::Pos_X;
         in_direction_ = Rotate::CCW;
     }
     if (output_type == Type::GPS) {
         out_zero_ = HeadingZero::Pos_Y;
         out_direction_ = Rotate::CW;
     } else if (output_type == Type::EUCLIDEAN) {
         out_zero_ = HeadingZero::Pos_X;
         out_direction_ = Rotate::CCW;
     }
     set_angle(angle);
 }
References angle(), CCW, CW, EUCLIDEAN, GPS, in_direction_, in_zero_, out_direction_, out_zero_, Pos_X, Pos_Y, and set_angle().
Member Function Documentation
deg2rad()
double scrimmage::Angles::deg2rad (double deg) static
Definition at line 64 of file Angles.cpp.
 {return deg * M_PI / 180.0;}
Referenced by scrimmage::sensor::ROSIMUSensor::ecef_to_ned_rotation(), scrimmage::Updater::get_model_texture(), scrimmage::sensor::ROSIMUSensor::gravity_ned_from_lla(), scrimmage::motion::SimpleCar::init(), scrimmage::motion::SingleIntegrator::init(), scrimmage::autonomy::Boids::init(), scrimmage::motion::SimpleQuadrotor::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), scrimmage::motion::DubinsAirplane::init(), scrimmage::motion::RigidBody6DOF::init(), scrimmage::motion::DoubleIntegrator::init(), scrimmage::motion::SimpleAircraft::init(), scrimmage::sensor::ContactBlobCamera::init(), scrimmage::PID::init(), scrimmage::motion::JSBSimModel::init(), scrimmage::motion::JSBSimControl::init(), scrimmage::Entity::init(), scrimmage::sensor::RayTrace::init(), scrimmage::autonomy::MOOSNode::OnNewMail(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), scrimmage::controller::set_pid(), scrimmage::set_pid_gains(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::motion::JSBSimControl::step(), scrimmage::motion::JSBSimModel::step(), scrimmage::sensor::AirSimSensor::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
rad2deg()
double scrimmage::Angles::rad2deg (double rad) static
Definition at line 66 of file Angles.cpp.
 {return rad * 180.0 / M_PI;}
Referenced by scrimmage::Updater::draw_arc(), scrimmage::motion::JSBSimControl::init(), scrimmage::motion::JSBSimModel::init(), scrimmage::Updater::quat_2_transform(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), scrimmage::Updater::set_quat(), scrimmage::SimControl::start(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::sensor::ContactBlobCamera::step(), scrimmage::motion::JSBSimModel::step(), scrimmage::motion::JSBSimControl::step(), scrimmage::sensor::AirSimSensor::step(), scrimmage::autonomy::MOOSAutonomy::step_autonomy(), scrimmage::motion::JSBSimModel::teleport(), and scrimmage::Updater::update_text_display().
set_input_clock_direction()
void scrimmage::Angles::set_input_clock_direction (Angles::Rotate direction)
Definition at line 68 of file Angles.cpp.
{
     in_direction_ = direction;
 }
References in_direction_.
Referenced by scrimmage::sensor::AirSimSensor::AirSimSensor(), scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), and scrimmage::autonomy::MOOSAutonomy::MOOSAutonomy().
set_input_zero_axis()
void scrimmage::Angles::set_input_zero_axis (Angles::HeadingZero zero)
Definition at line 72 of file Angles.cpp.
{
     in_zero_ = zero;
 }
References in_zero_.
Referenced by scrimmage::sensor::AirSimSensor::AirSimSensor(), scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), and scrimmage::autonomy::MOOSAutonomy::MOOSAutonomy().
set_output_clock_direction()
void scrimmage::Angles::set_output_clock_direction (Angles::Rotate direction)
Definition at line 76 of file Angles.cpp.
{
     out_direction_ = direction;
 }
References out_direction_.
Referenced by scrimmage::sensor::AirSimSensor::AirSimSensor(), scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), and scrimmage::autonomy::MOOSAutonomy::MOOSAutonomy().
set_output_zero_axis()
void scrimmage::Angles::set_output_zero_axis (Angles::HeadingZero zero)
Definition at line 80 of file Angles.cpp.
{
     out_zero_ = zero;
 }
References out_zero_.
Referenced by scrimmage::sensor::AirSimSensor::AirSimSensor(), scrimmage::controller::JSBSimControlControllerHeadingPID::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), and scrimmage::autonomy::MOOSAutonomy::MOOSAutonomy().
is_angle_360()
bool scrimmage::Angles::is_angle_360 (double angle)
Definition at line 84 of file Angles.cpp.
{
     if (angle >= 0 && angle < 360) {
         return true;
     } else {
         return false;
     }
 }
References angle().
angle_360()
double scrimmage::Angles::angle_360 (double angle) static
Definition at line 92 of file Angles.cpp.
{
     if (angle >= 360) {
         angle -= 360*floor(angle/360.0);
     }
     if (angle < 0) {
         angle += 360*ceil(std::abs(angle)/360.0);
     }
     return angle;
 }
References angle().
Referenced by angle_180(), angle_diff(), and set_angle().
angle_2pi()
double scrimmage::Angles::angle_2pi (double angle) static
Definition at line 103 of file Angles.cpp.
{
     double pi2 = 2 * M_PI;
     if (angle >= pi2) {
         angle -= pi2 * floor(angle / pi2);
     }
     if (angle < 0) {
         angle += pi2 * ceil(std::abs(angle)/ pi2);
     }
     return angle;
 }
References angle().
Referenced by angle_pi(), and REGISTER_PLUGIN().
angle_180()
double scrimmage::Angles::angle_180 (double angle) static
Definition at line 116 of file Angles.cpp.
{
     angle = angle_360(angle);
     if (angle > 180) {
         angle -= 360.0;
     }
     return angle;
 }
References angle(), and angle_360().
Referenced by angle_avg().
angle_pi()
double scrimmage::Angles::angle_pi (double angle) static
Definition at line 124 of file Angles.cpp.
{
     angle = angle_2pi(angle);
     if (angle > M_PI) {
         angle -= 2 * M_PI;
     }
     return angle;
 }
References angle(), and angle_2pi().
Referenced by angle_avg_rad(), angle_diff_rad(), scrimmage::motion::FixedWing6DOF::init(), REGISTER_PLUGIN(), scrimmage::controller::SimpleQuadrotorControllerLQR::step(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::PID::step(), scrimmage::motion::FixedWing6DOF::step(), scrimmage::autonomy::Predator::step_autonomy(), and scrimmage::autonomy::Boids::velocity_controller().
angle_diff()
double scrimmage::Angles::angle_diff (double ang1, double ang2) static
shortest angle from ang2 to ang1
Definition at line 132 of file Angles.cpp.
{
     double diff = angle_360(angle_360(ang1) - angle_360(ang2));
     if (diff > 180) {
         diff -= 360;
     }
     return diff;
 }
References angle_360().
Referenced by angle_avg(), and angle_within().
angle_diff_rad()
double scrimmage::Angles::angle_diff_rad (double ang1, double ang2) static
shortest angle from ang2 to ang1 (radians)
Definition at line 140 of file Angles.cpp.
{
     return angle_pi(angle_pi(ang1) - angle_pi(ang2));
 }
References angle_pi().
Referenced by angle_avg_rad(), angle_within_rad(), scrimmage::State::rel_az(), and scrimmage::controller::SimpleQuadrotorControllerLQR::step().
angle_within()
bool scrimmage::Angles::angle_within (double ang1, double ang2, double ang) static
returns whether ang is within the wedge between ang1 and ang2 where the wedge is less than 180 degrees
Definition at line 187 of file Angles.cpp.
{
     double diff = angle_diff(ang1, ang2);
     double diff1 = angle_diff(ang, ang2);
     return boost::math::sign(diff) == boost::math::sign(diff1) &&
         std::abs(diff) > std::abs(diff1);
 }
References angle_diff().
angle_within_rad()
bool scrimmage::Angles::angle_within_rad (double ang1, double ang2, double ang) static
returns whether ang is within the wedge between ang1 and ang2 where the wedge is less than PI radians
Definition at line 194 of file Angles.cpp.
{
     double diff = angle_diff_rad(ang1, ang2);
     double diff1 = angle_diff_rad(ang, ang2);
     return boost::math::sign(diff) == boost::math::sign(diff1) &&
         std::abs(diff) > std::abs(diff1);
 }
References angle_diff_rad().
angle_avg()
double scrimmage::Angles::angle_avg (double ang1, double ang2) static
Definition at line 144 of file Angles.cpp.
{
     return angle_180(ang2 + angle_diff(ang1, ang2) / 2.0);
 }
References angle_180(), and angle_diff().
angle_avg_rad()
double scrimmage::Angles::angle_avg_rad (double ang1, double ang2) static
Definition at line 148 of file Angles.cpp.
{
     return angle_pi(ang2 + angle_diff_rad(ang1, ang2) / 2.0);
 }
References angle_diff_rad(), and angle_pi().
set_angle()
void scrimmage::Angles::set_angle (double angle)
Definition at line 152 of file Angles.cpp.
{
     // Norm the angle
     angle = angle_360(angle);
     if (in_direction_ == out_direction_) {
         // If the angle increase is in the same direction
         // Just add or subtract a specific offset
         int rots = static_cast<int>(in_zero_) - static_cast<int>(out_zero_);
         angle_ = angle_360(angle + rots*90);
     } else {
         // If the coordinates are in different CW / CCW frames
         // Determine number of rotations
         // The sign is different depending on if the in-direction is
         // CW or CCW
         int rots;
         if (in_direction_ == Rotate::CW) {
             rots = static_cast<int>(in_zero_) - static_cast<int>(out_zero_);
         } else {
             rots = static_cast<int>(out_zero_) - static_cast<int>(in_zero_);
         }
         // If the coordinates are different CW/CCW, but the zero is on
         // the same axis, need to set rotations to 4 to get (90*4 = 360)
         if (rots == 0) {
             rots = 4;
         }
         angle_ = angle_360(rots*90 - angle);
     }
 }
References angle(), angle_, angle_360(), CW, in_direction_, in_zero_, out_direction_, and out_zero_.
Referenced by Angles(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::sensor::AirSimSensor::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
angle()
double scrimmage::Angles::angle ()
Definition at line 183 of file Angles.cpp.
                      {
     return angle_;
 }
References angle_.
Referenced by angle_180(), angle_2pi(), angle_360(), angle_pi(), Angles(), is_angle_360(), REGISTER_PLUGIN(), scrimmage::FrameUpdateClient::send_frame(), set_angle(), scrimmage::controller::JSBSimControlControllerHeadingPID::step(), scrimmage::controller::JSBSimModelControllerHeadingPID::step(), scrimmage::sensor::AirSimSensor::step(), and scrimmage::autonomy::MOOSAutonomy::step_autonomy().
Member Data Documentation
angle_
double scrimmage::Angles::angle_ = 0 protected
Definition at line 118 of file Angles.h.
Referenced by angle(), and set_angle().
in_direction_
Rotate scrimmage::Angles::in_direction_ = Rotate::CCW protected
Definition at line 120 of file Angles.h.
Referenced by Angles(), set_angle(), and set_input_clock_direction().
in_zero_
HeadingZero scrimmage::Angles::in_zero_ = HeadingZero::Pos_X protected
Definition at line 121 of file Angles.h.
Referenced by Angles(), set_angle(), and set_input_zero_axis().
out_direction_
Rotate scrimmage::Angles::out_direction_ = Rotate::CCW protected
Definition at line 123 of file Angles.h.
Referenced by Angles(), set_angle(), and set_output_clock_direction().
out_zero_
HeadingZero scrimmage::Angles::out_zero_ = HeadingZero::Pos_X protected
Definition at line 124 of file Angles.h.
Referenced by Angles(), set_angle(), and set_output_zero_axis().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/math/Angles.h
/root/scrimmage/scrimmage/src/math/Angles.cpp