SCRIMMAGE: scrimmage::motion::RigidBody6DOF Class Reference
scrimmage::motion::RigidBody6DOF Class Reference
#include <RigidBody6DOF.h>
Classes
class Controller
Public Member Functions
virtual std::tuple< int, int, int > version ()
bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params) override
bool step (double time, double dt) override
void model (const vector_t &x, vector_t &dxdt, double t) override
void teleport (scrimmage::StatePtr &state) override
void set_u (std::shared_ptr< Eigen::Vector4d > u)
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
scrimmage::PID heading_pid_
scrimmage::PID alt_pid_
scrimmage::PID vel_pid_
double length_
std::shared_ptr< Eigen::Vector4d > ctrl_u_
double min_velocity_
double max_velocity_
double max_roll_
double max_pitch_
scrimmage::Quaternion quat_world_
scrimmage::Quaternion quat_local_
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
Detailed Description
Definition at line 47 of file RigidBody6DOF.h.
Member Function Documentation
std::tuple< int, int, int > scrimmage::motion::RigidBody6DOF::version () virtual
Definition at line 80 of file RigidBody6DOF.cpp.
{
     return std::tuple<int, int, int>(0, 0, 1);
 }
bool scrimmage::motion::RigidBody6DOF::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 84 of file RigidBody6DOF.cpp.
References scrimmage::Angles::deg2rad(), scrimmage::get(), scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::motion::U, scrimmage::motion::Uw, scrimmage::motion::V, scrimmage::motion::Vw, scrimmage::motion::W, scrimmage::motion::Ww, scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     x_.resize(MODEL_NUM_ITEMS);
     Eigen::Vector3d &pos = state_->pos();
     quat_world_ = state_->quat();
     min_velocity_ = sc::get("min_velocity", params, 15.0);
     max_velocity_ = sc::get("max_velocity", params, 40.0);
     max_roll_ = sc::Angles::deg2rad(sc::get("max_roll", params, 30.0));
     max_pitch_ = sc::Angles::deg2rad(sc::get("max_pitch", params, 30.0));
     x_[U] = 0;
     x_[V] = 0;
     x_[W] = 0;
     x_[P] = 0;
     x_[Q] = 0;
     x_[R] = 0;
     x_[Uw] = 0;
     x_[Vw] = 0;
     x_[Ww] = 0;
     x_[Xw] = pos(0);
     x_[Yw] = pos(1);
     x_[Zw] = pos(2);
     // Initial Local orientation (no rotation)
     x_[q0] = 1;
     x_[q1] = 0;
     x_[q2] = 0;
     x_[q3] = 0;
     return true;
 }
bool scrimmage::motion::RigidBody6DOF::step (double time, double dt) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 120 of file RigidBody6DOF.cpp.
References scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::motion::U, scrimmage::motion::RigidBody6DOF::Controller::u(), scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     if (ctrl_u_ == nullptr) {
         std::shared_ptr<Controller> ctrl =
             std::dynamic_pointer_cast<Controller>(parent_->controllers().back());
         if (ctrl) {
             ctrl_u_ = ctrl->u();
         }
     }
     if (ctrl_u_ == nullptr) {
         return false;
     }
     // Need to saturate state variables before model runs
     x_[U] = clamp(x_[U], min_velocity_, max_velocity_);
     x_[P] = clamp(x_[U], -0.001, 0.001);
     x_[Q] = clamp(x_[U], -0.001, 0.001);
     x_[R] = clamp(x_[U], -0.001, 0.001);
     ode_step(dt);
     // Normalize quaternion
     quat_local_.w() = x_[q0];
     quat_local_.x() = x_[q1];
     quat_local_.y() = x_[q2];
     quat_local_.z() = x_[q3];
     quat_local_.normalize();
     x_[q0] = quat_local_.w();
     x_[q1] = quat_local_.x();
     x_[q2] = quat_local_.y();
     x_[q3] = quat_local_.z();
     // Convert local coordinates to world coordinates
     state_->quat() = quat_world_ * quat_local_;
     state_->pos() << x_[Xw], x_[Yw], x_[Zw];
     return true;
 }
void scrimmage::motion::RigidBody6DOF::model (const vector_t & x, vector_t & dxdt, double t) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 161 of file RigidBody6DOF.cpp.
References scrimmage::motion::AILERON, scrimmage::motion::ELEVATOR, scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::motion::RUDDER, scrimmage::motion::THRUST, scrimmage::motion::U, scrimmage::motion::Uw, scrimmage::motion::V, scrimmage::motion::Vw, scrimmage::motion::W, scrimmage::motion::Ww, scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     double thrust = (*ctrl_u_)(THRUST);
     double elevator = (*ctrl_u_)(ELEVATOR);
     double aileron = (*ctrl_u_)(AILERON);
     double rudder = (*ctrl_u_)(RUDDER);
     double F_thrust = thrust;
     double F_x = F_thrust;
     double m = 1.0;
     double g = 0; // -9.8; no gravity
     double theta = 0;
     double Ixx = 1;
     double Iyy = 1;
     double Izz = 1;
     double Ixz = 0;
     // TODO: Should these be cached from previous run or should the current dxdt
     // versions be used?
     double U_dot = dxdt[U];
     double V_dot = dxdt[V];
     double W_dot = dxdt[W];
     double P_dot = dxdt[P];
     double Q_dot = dxdt[Q];
     double R_dot = dxdt[R];
     dxdt[U] = x[V]*x[R] - x[W]*x[Q] - g*sin(theta) + F_x / m;
     dxdt[V] = 0; // x[W]*x[P] - x[U]*x[R] + g*sin(phi)*cos(theta) + F_y / m;
     dxdt[W] = 0; // x[U]*x[Q] - x[V]*x[P] + g*cos(phi)*cos(theta) + F_z / m;
     double L = aileron + Ixx*P_dot - Ixz*R_dot - Ixz*x[P]*x[Q] + (Izz - Iyy)*x[R]*x[Q];
     double M = elevator + Iyy*Q_dot + (Ixx-Izz)*x[P]*x[R] + (Ixz*(pow(x[P], 2) - pow(x[R], 2)));
     double N = rudder + Izz*R_dot - Ixz*P_dot + (Iyy-Ixx)*x[P]*x[Q] + Ixz*x[Q]*x[R];
     double L_tic = L + Ixz*x[P]*x[Q] - (Izz-Iyy)*x[R]*x[Q];
     double N_tic = N - (Iyy-Ixx)*x[P]*x[Q] - Ixz*x[R]*x[Q];
     dxdt[P] = (L_tic*Izz-N_tic*Ixz) / (Ixx*Izz - pow(Ixz, 2));
     dxdt[Q] = (M - (Ixx - Izz)*x[P]*x[R]) - Ixz*(pow(x[P], 2)-pow(x[R], 2))/Iyy;
     dxdt[R] = (N_tic*Ixx+L_tic*Ixz) / (Ixx*Izz - pow(Ixz, 2));
     double lambda = 1 - (pow(x[q0], 2) + pow(x[q1], 2) + pow(x[q2], 2) + pow(x[q3], 2));
     dxdt[q0] = -0.5 * (x[q1]*x[P] + x[q2]*x[Q] + x[q3]*x[R]) + lambda * x[q0];
     dxdt[q1] = +0.5 * (x[q0]*x[P] + x[q2]*x[R] - x[q3]*x[Q]) + lambda * x[q1];
     dxdt[q2] = +0.5 * (x[q0]*x[Q] + x[q3]*x[P] - x[q1]*x[R]) + lambda * x[q2];
     dxdt[q3] = +0.5 * (x[q0]*x[R] + x[q1]*x[Q] - x[q2]*x[P]) + lambda * x[q3];
     // Local position / velocity to global
     // Normalize quaternion
     sc::Quaternion quat(x[q0], x[q1], x[q2], x[q3]);
     quat.w() = x[q0];
     quat.x() = x[q1];
     quat.y() = x[q2];
     quat.z() = x[q3];
     quat = quat_world_ * quat;
     quat.normalize();
     // Convert local positions and velocities into global coordinates
     Eigen::Matrix3d rot = quat.toRotationMatrix();
     Eigen::Vector3d vel_local(x[U], x[V], x[W]);
     Eigen::Vector3d vel_world = rot * vel_local;
     dxdt[Xw] = vel_world(0);
     dxdt[Yw] = vel_world(1);
     dxdt[Zw] = vel_world(2);
     Eigen::Vector3d acc_local(U_dot, V_dot, W_dot);
     Eigen::Vector3d acc_world = rot * acc_local;
     dxdt[Uw] = acc_world(0);
     dxdt[Vw] = acc_world(1);
     dxdt[Ww] = acc_world(2);
 }
void scrimmage::motion::RigidBody6DOF::teleport (scrimmage::StatePtr & state) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 237 of file RigidBody6DOF.cpp.
{
     // x_[X] = state->pos()[0];
     // x_[Y] = state->pos()[1];
     // x_[Z] = state->pos()[2];
     // x_[ROLL] = state->quat().roll();
     // x_[PITCH] = state->quat().pitch();
     // x_[YAW] = state->quat().yaw();
     // x_[SPEED] = state->vel()[0];
 }
void scrimmage::motion::RigidBody6DOF::set_u (std::shared_ptr< Eigen::Vector4d > u) inline
Definition at line 65 of file RigidBody6DOF.h.
References ctrl_u_, and scrimmage::motion::RigidBody6DOF::Controller::u().
 {ctrl_u_ = u;}
Member Data Documentation
scrimmage::PID scrimmage::motion::RigidBody6DOF::heading_pid_ protected
Definition at line 68 of file RigidBody6DOF.h.
scrimmage::PID scrimmage::motion::RigidBody6DOF::alt_pid_ protected
Definition at line 69 of file RigidBody6DOF.h.
scrimmage::PID scrimmage::motion::RigidBody6DOF::vel_pid_ protected
Definition at line 70 of file RigidBody6DOF.h.
double scrimmage::motion::RigidBody6DOF::length_ protected
Definition at line 72 of file RigidBody6DOF.h.
std::shared_ptr<Eigen::Vector4d> scrimmage::motion::RigidBody6DOF::ctrl_u_ protected
Definition at line 73 of file RigidBody6DOF.h.
Referenced by set_u().
double scrimmage::motion::RigidBody6DOF::min_velocity_ protected
Definition at line 75 of file RigidBody6DOF.h.
double scrimmage::motion::RigidBody6DOF::max_velocity_ protected
Definition at line 76 of file RigidBody6DOF.h.
double scrimmage::motion::RigidBody6DOF::max_roll_ protected
Definition at line 77 of file RigidBody6DOF.h.
double scrimmage::motion::RigidBody6DOF::max_pitch_ protected
Definition at line 78 of file RigidBody6DOF.h.
scrimmage::Quaternion scrimmage::motion::RigidBody6DOF::quat_world_ protected
Definition at line 80 of file RigidBody6DOF.h.
scrimmage::Quaternion scrimmage::motion::RigidBody6DOF::quat_local_ protected
Definition at line 81 of file RigidBody6DOF.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/RigidBody6DOF/RigidBody6DOF.h
/root/scrimmage/scrimmage/src/plugins/motion/RigidBody6DOF/RigidBody6DOF.cpp