SCRIMMAGE: scrimmage::StateWithCovariance Class Reference
scrimmage::StateWithCovariance Class Reference
#include <StateWithCovariance.h>
Public Member Functions
StateWithCovariance ()
StateWithCovariance (const scrimmage::State &state)
StateWithCovariance (const scrimmage::State &state, const int &cov_num_rows, const int &cov_num_cols, const double &cov_diag)
void set_covariance (const Eigen::MatrixXd &covariance)
const Eigen::MatrixXd & covariance ()
Public Member Functions inherited from scrimmage::State
State ()
State (Eigen::Vector3d _pos, Eigen::Vector3d _vel, Eigen::Vector3d _ang_vel, Quaternion _quat)
virtual ~State ()
Eigen::Vector3d & pos ()
Eigen::Vector3d & vel ()
Eigen::Vector3d & ang_vel ()
const Eigen::Vector3d & pos () const
const Eigen::Vector3d & vel () const
const Eigen::Vector3d & ang_vel () const
Quaternion & quat ()
const Quaternion & quat () const
const Eigen::Vector3d & pos_const () const
const Eigen::Vector3d & vel_const () const
const Eigen::Vector3d & ang_vel_const () const
const Quaternion & quat_const () const
void set_pos (const Eigen::Vector3d &pos)
void set_vel (const Eigen::Vector3d &vel)
void set_ang_vel (const Eigen::Vector3d &ang_vel)
void set_quat (const Quaternion &quat)
bool InFieldOfView (State &other, double fov_width, double fov_height) const
Returns true if other state is in field-of-view.
Eigen::Vector3d rel_pos_local_frame (Eigen::Vector3d &other) const
convert the relative position to the local frame (the output vector will point to the other state)
Eigen::Vector3d pos_offset (double distance, bool offset_with_velocity=true) const
return position offset by trailing_distance in the direction of velocity or orientation
Eigen::Vector3d orient_global_frame () const
returns the vector extending forward
double rel_az (const Eigen::Vector3d &other) const
Eigen::Matrix4d tf_matrix (bool enable_translate=true)
Protected Attributes
Eigen::MatrixXd covariance_
Protected Attributes inherited from scrimmage::State
Eigen::Vector3d pos_
Eigen::Vector3d vel_
Eigen::Vector3d ang_vel_
Quaternion quat_
Additional Inherited Members
Static Public Member Functions inherited from scrimmage::State
template<class T , class = std::enable_if_t< !std::is_same<T, scrimmage::State>::value && std::is_base_of<scrimmage::State, T>::value, void>>
static std::shared_ptr< T > cast (std::shared_ptr< scrimmage::State > state)
Downcast a scrimmage::State to a subclassed type, returing nullptr if not successful.
Public Attributes inherited from scrimmage::State
uint8_t output_precision = 2
Detailed Description
Definition at line 41 of file StateWithCovariance.h.
Constructor & Destructor Documentation
StateWithCovariance() [1/3]
scrimmage::StateWithCovariance::StateWithCovariance ()
Definition at line 35 of file StateWithCovariance.cpp.
                                          :
     covariance_(Eigen::MatrixXd::Identity(3, 3)) {
 }
StateWithCovariance() [2/3]
scrimmage::StateWithCovariance::StateWithCovariance (const scrimmage::State & state) explicit
Definition at line 39 of file StateWithCovariance.cpp.
                                                                     :
     StateWithCovariance(state, 3, 3, 1.0) {
 }
StateWithCovariance() [3/3]
scrimmage::StateWithCovariance::StateWithCovariance (const scrimmage::State & state, const int & cov_num_rows, const int & cov_num_cols, const double & cov_diag)
Definition at line 43 of file StateWithCovariance.cpp.
                                                                  :
     State(state.pos(), state.vel(), state.ang_vel(),
           state.quat()),
     covariance_(cov_diag * Eigen::MatrixXd::Identity(cov_num_rows, cov_num_cols)) {
 }
Member Function Documentation
set_covariance()
void scrimmage::StateWithCovariance::set_covariance (const Eigen::MatrixXd & covariance)
Definition at line 52 of file StateWithCovariance.cpp.
{
     covariance_ = covariance;
 }
References covariance(), and covariance_.
covariance()
const Eigen::MatrixXd & scrimmage::StateWithCovariance::covariance ()
Definition at line 56 of file StateWithCovariance.cpp.
{
     return covariance_;
 }
References covariance_.
Referenced by set_covariance(), and scrimmage::sensor::SimpleINS::step().
Member Data Documentation
covariance_
Eigen::MatrixXd scrimmage::StateWithCovariance::covariance_ protected
Definition at line 53 of file StateWithCovariance.h.
Referenced by covariance(), and set_covariance().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/math/StateWithCovariance.h
/root/scrimmage/scrimmage/src/math/StateWithCovariance.cpp