SCRIMMAGE: scrimmage::sensor::ContactBlobCamera Class Reference
scrimmage::sensor::ContactBlobCamera Class Reference
#include <ContactBlobCamera.h>
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step () override
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
void contacts_to_bounding_boxes (const scrimmage::State &sensor_frame, scrimmage::ContactMap &contacts, std::shared_ptr< scrimmage::Message< ContactBlobCameraType >> &msg)
void add_false_positives (std::shared_ptr< scrimmage::Message< ContactBlobCameraType >> &msg)
Eigen::Vector2d project_rel_3d_to_2d (Eigen::Vector3d rel_pos)
bool in_field_of_view (Eigen::Vector3d rel_pos)
void draw_object_with_bounding_box (cv::Mat &frame, const int &id, const cv::Rect &rect, const Eigen::Vector2d &center, const double &radius)
void set_plugin_params (std::map< std::string, double > params)
void draw_frustum (const std::vector< scrimmage_proto::ShapePtr > &frustum, double x_rot, double y_rot, double z_rot)
Protected Attributes
std::ofstream parameters_file_
std::ofstream detections_file_
std::shared_ptr< std::default_random_engine > gener_
std::vector< std::shared_ptr< std::normal_distribution< double > > > pos_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > orient_noise_
std::map< std::string, double > plugin_params_
int camera_id_ = 0
int img_width_
int img_height_
double max_detect_range_
double focal_length_
double fps_
double az_thresh_
double el_thresh_
double fn_prob_
double fp_prob_
int max_false_positives_
int std_dev_w_
int std_dev_h_
double canvas_width_
double canvas_height_
cv::Mat frame_
double last_frame_t_
PublisherPtr pub_
bool ignore_real_entities_ = false
bool show_image_ = false
bool show_frustum_ = false
bool log_detections_ = false
bool show_sim_contacts_ = false
double last_contact_send_time_ = 0.0
double contact_send_dt_ = 1.0
std::string window_name_ = "ContactBlobCamera"
std::vector< scrimmage_proto::ShapePtr > frustum_shapes_
scrimmage_proto::ShapePtr sim_tgt_sphere_ = std::make_shared<scrimmage_proto::Shape>()
scrimmage::ContactMap sim_contacts_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 55 of file ContactBlobCamera.h.
Member Function Documentation
void scrimmage::sensor::ContactBlobCamera::init (std::map< std::string, std::string > & params) override virtual
Allow for updating plugin parameters in real-time.
Allow for updating camera's roll, pitch, and yaw in real-time.
Reimplemented from scrimmage::Sensor.
Definition at line 71 of file ContactBlobCamera.cpp.
References scrimmage::Angles::deg2rad(), scrimmage::get_vec(), scrimmage::get_vec_of_vecs(), and scrimmage::set().
{
     std::stringstream ss;
     ss << parent_->id().id();
     parameters_file_.open(parent_->mp()->log_dir() + "/blob_sensor_parameters_" + ss.str() + ".txt");
     gener_ = parent_->random()->gener();
     window_name_ = sc::get<std::string>("window_name", params, window_name_);
     ignore_real_entities_ = sc::get<bool>("ignore_real_entities", params, ignore_real_entities_);
     show_image_ = sc::get<bool>("show_image", params, show_image_);
     show_frustum_ = sc::get<bool>("show_frustum", params, show_frustum_);
     log_detections_ = sc::get<bool>("log_detections", params, log_detections_);
     show_sim_contacts_ = sc::get<bool>("show_sim_contacts", params, true);
     // Parse the simulated detections
     std::string sim_det_str = sc::get<std::string>("simulated_detections", params, "");
     std::vector<std::vector<std::string>> vecs;
     if (get_vec_of_vecs(sim_det_str, vecs, ", ")) {
         int i = 0;
         for (auto &vec : vecs) {
             // First, assume the description is in XYZ
             int id = std::stoi(vec[1]);
             double radius = std::stod(vec[2]);
             double x = std::stod(vec[3]);
             double y = std::stod(vec[4]);
             double z = std::stod(vec[5]);
             if (vec[0] == "GPS") {
                 // If the description is in GPS, convert to local cartesian
                 parent_->projection()->Forward(x, y, z, x, y, z);
             }
             sc::Quaternion quat(std::stod(vec[6]), std::stod(vec[7]),
                                 std::stod(vec[8]));
             sc::StatePtr cnt_state = std::make_shared<sc::State>(
                 Eigen::Vector3d(x, y, z), Eigen::Vector3d(0, 0, 0),
                 Eigen::Vector3d(0, 0, 0), quat);
             sc::Contact cnt(sc::ID(id, 0, 0), cnt_state);
             cnt.set_type(sc::Contact::Type::MESH);
             cnt.set_radius(radius);
             cnt.set_active(true);
             // Allow multiple simulated contacts to have the same ID
             sim_contacts_[i++] = cnt;
         }
     }
     // override default parameters
     plugin_params_["senderId"] = parent_->id().id();
     plugin_params_["camera_id"] = sc::get<int>("camera_id", params, camera_id_);
     plugin_params_["img_width"] = sc::get<int>("img_width", params, 800);
     plugin_params_["img_height"] = sc::get<int>("img_height", params, 600);
     plugin_params_["max_detect_range"] = sc::get<double>("max_detect_range", params, 1000);
     plugin_params_["focal_length"] = sc::get<double>("focal_length", params, 1.0);
     plugin_params_["fps"] = sc::get<double>("frames_per_second", params, 10);
     plugin_params_["az_thresh"] = sc::Angles::deg2rad(sc::get<double>("azimuth_fov", params, 360));
     plugin_params_["el_thresh"] = sc::Angles::deg2rad(sc::get<double>("elevation_fov", params, 360));
     plugin_params_["fn_prob"] = sc::get<double>("false_negative_probability", params, 0.1);
     plugin_params_["fp_prob"] = sc::get<double>("false_positive_probability", params, 0.1);
     plugin_params_["max_false_positives"] = sc::get<int>("max_false_positives_per_frame", params, 10);
     plugin_params_["std_dev_w"] = sc::get<int>("std_dev_width", params, 10);
     plugin_params_["std_dev_h"] = sc::get<int>("std_dev_height", params, 10);
     set_plugin_params(plugin_params_);
     if (log_detections_) {
         detections_file_.open(parent_->mp()->log_dir() + "/blob_sensor_detections_" + std::to_string(camera_id_) + ".txt");
     }
     for (int i = 0; i < 3; i++) {
         std::string tag_name = "pos_noise_" + std::to_string(i);
         std::vector<double> vec;
         bool status = sc::get_vec(tag_name, params, " ", vec, 2);
         if (status) {
             pos_noise_.push_back(parent_->random()->make_rng_normal(vec[0], vec[1]));
         } else {
             pos_noise_.push_back(parent_->random()->make_rng_normal(0, 1));
         }
     }
     for (int i = 0; i < 3; i++) {
         std::string tag_name = "orient_noise_" + std::to_string(i);
         std::vector<double> vec;
         bool status = sc::get_vec(tag_name, params, " ", vec, 2);
         if (status) {
             orient_noise_.push_back(parent_->random()->make_rng_normal(vec[0], vec[1]));
         } else {
             orient_noise_.push_back(parent_->random()->make_rng_normal(0, 1));
         }
     }
     auto params_cb = [&](sc::MessagePtr<std::map<std::string, double>> msg) {set_plugin_params(msg->data);};
     subscribe<std::map<std::string, double>>("LocalNetwork", "BlobPluginParams", params_cb);
     auto rpy_cb = [&](sc::MessagePtr<std::vector<double>> msg) {
         double roll = sc::Angles::deg2rad(msg->data[0]);
         double pitch = sc::Angles::deg2rad(msg->data[1]);
         double yaw = sc::Angles::deg2rad(msg->data[2]);
         this->transform()->quat().set(roll, pitch, yaw);
     };
     subscribe<std::vector<double>>("LocalNetwork", "BlobPluginRPY", rpy_cb);
     // Publish the resulting bounding boxes
     pub_ = advertise("LocalNetwork", "ContactBlobCamera");
     // Initialize frustum shapes
     frustum_shapes_.resize(8);
     for (auto&& shape : frustum_shapes_) {
         shape = std::make_shared<scrimmage_proto::Shape>();
         sc::set(shape->mutable_color(), 0, 255, 0);
         shape->set_opacity(1.0);
         shape->set_persistent(false);
         shape->set_persist_duration(0.0);
     }
 }
bool scrimmage::sensor::ContactBlobCamera::step () override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 367 of file ContactBlobCamera.cpp.
References scrimmage::Quaternion::pitch(), scrimmage::State::pos(), scrimmage::State::quat(), scrimmage::Angles::rad2deg(), scrimmage::Quaternion::roll(), scrimmage::set(), and scrimmage::Quaternion::yaw().
{
     if ((time_->t() - last_frame_t_) < 1.0 / fps_) return true;
     sc::State sensor_frame;
     sensor_frame.quat() =
             static_cast<sc::Quaternion>(parent_->state_truth()->quat() *
                                         this->transform()->quat());
     sensor_frame.pos() = this->transform()->pos() + parent_->state_truth()->pos();
     if (show_frustum_) {
         draw_frustum(frustum_shapes_, sensor_frame.quat().roll(), sensor_frame.quat().pitch(), sensor_frame.quat().yaw());
     }
     auto msg = std::make_shared<sc::Message<ContactBlobCameraType>>();
     msg->data.roll = sc::Angles::rad2deg(this->transform()->quat().roll());
     msg->data.pitch = sc::Angles::rad2deg(this->transform()->quat().pitch());
     msg->data.yaw = sc::Angles::rad2deg(this->transform()->quat().yaw());
     msg->data.camera_id = camera_id_;
     msg->data.img_width = img_width_;
     msg->data.img_height = img_height_;
     msg->data.max_detect_range = max_detect_range_;
     msg->data.focal_length = focal_length_;
     msg->data.fps = fps_;
     msg->data.az_thresh = az_thresh_;
     msg->data.el_thresh = el_thresh_;
     msg->data.fn_prob = fn_prob_;
     msg->data.fp_prob = fp_prob_;
     msg->data.max_false_positives = max_false_positives_;
     msg->data.frame = cv::Mat::zeros(img_height_, img_width_, CV_8UC3);
     if (not ignore_real_entities_) {
         // Compute bounding boxes for real contacts
         contacts_to_bounding_boxes(sensor_frame, *(parent_->contacts()), msg);
     }
     // Compute bounding boxes for added "simulated" contacts
     contacts_to_bounding_boxes(sensor_frame, sim_contacts_, msg);
     if (show_sim_contacts_ &&
         time_->t() > last_contact_send_time_ + contact_send_dt_) {
         // draw_sim_contacts(sim_contacts_);
         for (auto &kv : sim_contacts_) {
             // Draw a sphere at the expected commanded state
             Eigen::Vector3d sphere_center(kv.second.state()->pos().x(),
                                           kv.second.state()->pos().y(),
                                           kv.second.state()->pos().z());
             sc::set(sim_tgt_sphere_->mutable_sphere()->mutable_center(), sphere_center);
             sc::set(sim_tgt_sphere_->mutable_color(), 0, 255, 255);
             sim_tgt_sphere_->mutable_sphere()->set_radius(kv.second.radius());
             sim_tgt_sphere_->set_opacity(0.7);
             sim_tgt_sphere_->set_persistent(false);
             draw_shape(sim_tgt_sphere_);
         }
         last_contact_send_time_ = time_->t();
     }
     // Add false positives
     add_false_positives(msg);
     frame_ = msg->data.frame;
     last_frame_t_ = time_->t();
     if (show_image_) {
         std::string window_name = window_name_ + "-" +
                 std::to_string(parent_->id().id()) + "-" +
                 std::to_string(camera_id_);
         cv::imshow(window_name.c_str(), msg->data.frame);
         cv::waitKey(1);
     }
     // Log any detections
     if (log_detections_) {
         detections_file_ << time_->t();
         for (auto elem : msg->data.bounding_boxes) {
             detections_file_ << ", " << elem.first;
         }
         detections_file_ << std::endl;
     }
     pub_->publish(msg);
     return true;
 }
void scrimmage::sensor::ContactBlobCamera::contacts_to_bounding_boxes (const scrimmage::State & sensor_frame, scrimmage::ContactMap & contacts, std::shared_ptr< scrimmage::Message< ContactBlobCameraType >> & msg) protected
Definition at line 253 of file ContactBlobCamera.cpp.
References scrimmage::State::pos(), and scrimmage::State::rel_pos_local_frame().
{
     for (auto &kv : contacts) {
         // Filter out (skip) own contact
         if (kv.second.id().id() == parent_->id().id()) continue;
         // Filter out contacts out of range, should use RTree, but rtree still
         // requires querying of ID from contact lists. (TODO)
         if ((kv.second.state()->pos() - sensor_frame.pos()).norm() >
             max_detect_range_) {
             continue;
         }
         // Don't "detect" current contact relative to false negative probability
         double r = parent_->random()->rng_uniform(0.0, 1.0);
         if (r < fn_prob_) continue;
         // Transform contact into "camera" coordinate system
         Eigen::Vector3d rel_pos = sensor_frame.rel_pos_local_frame(kv.second.state()->pos());
         if (!in_field_of_view(rel_pos)) continue;
         // Convert 3D relative position to 2d image plane position
         Eigen::Vector2d raster_center = project_rel_3d_to_2d(rel_pos);
         double object_radius = kv.second.radius();
         // Get angle between (vector between camera and object center) and
         // (vector between object center and line tangent to object circle)
         double beta = acos(object_radius / rel_pos.norm());
         // Get vector pointing from contact to camera
         Eigen::Vector2d v_r(-rel_pos(0), -rel_pos(1));
         // Normalize to unit vector and Make length equal to object radius
         v_r = v_r.normalized() * object_radius;
         // Rotate one direction and add circle's center point
         Eigen::Vector2d v_r_1 = v_r, v_r_2 = v_r;
         Eigen::Rotation2D<double> rot1(beta);
         Eigen::Rotation2D<double> rot2(-beta);
         v_r_1 = rot1.toRotationMatrix() * v_r_1;
         v_r_2 = rot2.toRotationMatrix() * v_r_2;
         // Get 3D relative position of rotated vectors
         Eigen::Vector3d p1(rel_pos(0) + v_r_1(0),
                            rel_pos(1) + v_r_1(1),
                            rel_pos(2));
         Eigen::Vector3d p2(rel_pos(0) + v_r_2(0),
                            rel_pos(1) + v_r_2(1),
                            rel_pos(2));
         // Get 2D position of object boundaries
         Eigen::Vector2d r1 = project_rel_3d_to_2d(p1);
         Eigen::Vector2d r2 = project_rel_3d_to_2d(p2);
         // Calculate image radius using distance between object boundaries
         double object_img_radius = (r1 - r2).norm() / 2.0;
         // Add noise to position in 2D image plane
         raster_center(0) += (*pos_noise_[0])(*gener_);
         raster_center(1) += (*pos_noise_[1])(*gener_);
         // Add bounding box to frame around object
         cv::Rect rect(std::floor(raster_center(0))-std::floor(object_img_radius),
                       std::floor(raster_center(1))-std::floor(object_img_radius),
                       std::floor(object_img_radius*2) + 1,
                       std::floor(object_img_radius*2) + 1);
         if (object_img_radius > 0) {
             draw_object_with_bounding_box(msg->data.frame, kv.second.id().id(),
                                           rect, raster_center, object_img_radius);
         }
         // Collect all bounding boxes for current detected object
         msg->data.bounding_boxes[kv.second.id().id()].push_back(rect);
     }
 }
void scrimmage::sensor::ContactBlobCamera::add_false_positives (std::shared_ptr< scrimmage::Message< ContactBlobCameraType >> & msg) protected
Definition at line 336 of file ContactBlobCamera.cpp.
{
     for (int i = 0; i < max_false_positives_; i++) {
         double r = parent_->random()->rng_uniform(0.0, 1.0);
         if (r > fp_prob_) continue;
         // Generate random center position in frame
         Eigen::Vector2d raster_center(
             parent_->random()->rng_uniform_int(0, img_width_),
             parent_->random()->rng_uniform_int(0, img_height_));
         double object_img_radius = parent_->random()->rng_uniform(0.1, 20.0);
         // Add bounding box to frame around object
         cv::Rect rect(std::floor(raster_center(0))-std::floor(object_img_radius),
                       std::floor(raster_center(1))-std::floor(object_img_radius),
                       std::floor(object_img_radius*2) + 1,
                       std::floor(object_img_radius*2) + 1);
         // Generate a random ID
         int id = parent_->random()->rng_uniform_int(1, 100);
         if (object_img_radius > 0) {
             draw_object_with_bounding_box(msg->data.frame, id, rect,
                                           raster_center, object_img_radius);
         }
         msg->data.bounding_boxes[id].push_back(rect);
     }
 }
Eigen::Vector2d scrimmage::sensor::ContactBlobCamera::project_rel_3d_to_2d (Eigen::Vector3d rel_pos) protected
Definition at line 454 of file ContactBlobCamera.cpp.
{
     // 3D to 2D transforms are described here:
     // http://www.scratchapixel.com/lessons/3d-basic-rendering/computing-pixel-coordinates-of-3d-point/mathematics-computing-2d-coordinates-of-3d-points
     // Convert relative position of contact into computer vision coordinates
     // for relative coordinates:
     Eigen::Vector3d pos(rel_pos(1), rel_pos(2), rel_pos(0));
     // Transform to screen / canvas space
     Eigen::Vector2d s(focal_length_ * -pos(0) / pos(2),
                       focal_length_ * pos(1) / pos(2));
     // Transform to Normalized Device Coordinate (NDC) space
     Eigen::Vector2d ndc((s(0) + canvas_width_/2.0) / canvas_width_,
                         (s(1) + canvas_height_/2.0) / canvas_height_);
     // Tranform to raster space
     Eigen::Vector2d r(ndc(0) * img_width_,
                       (1-ndc(1)) * img_height_);
     return r;
 }
bool scrimmage::sensor::ContactBlobCamera::in_field_of_view (Eigen::Vector3d rel_pos) protected
Definition at line 476 of file ContactBlobCamera.cpp.
{
     double az = atan2(rel_pos(1), rel_pos(0));
     double norm_xy = sqrt(pow(rel_pos(0), 2) + pow(rel_pos(1), 2));
     double el = atan2(rel_pos(2), norm_xy);
     if (std::abs(az) > (az_thresh_ / 2) ||
         std::abs(el) > (el_thresh_ / 2)) {
         return false;
     }
     return true;
 }
void scrimmage::sensor::ContactBlobCamera::draw_object_with_bounding_box (cv::Mat & frame, const int & id, const cv::Rect & rect, const Eigen::Vector2d & center, const double & radius) protected
Definition at line 487 of file ContactBlobCamera.cpp.
{
     Eigen::Vector2i c(std::floor(center(0)),
                       std::floor(center(1)));
     cv::circle(frame, cv::Point(c(0), c(1)),
                std::floor(radius), cv::Scalar(255, 255, 255),
                -1, 8, 0);
     cv::rectangle(frame, rect, cv::Scalar(0, 0, 255), 1, 8, 0);
     cv::Point top_left(rect.x + rect.width, rect.y + rect.height);
     cv::putText(frame, std::to_string(id), top_left,  cv::FONT_HERSHEY_SIMPLEX,
                 1.0, cv::Scalar(8, 100, 22), 1, 8, false);
 }
void scrimmage::sensor::ContactBlobCamera::set_plugin_params (std::map< std::string, double > params) protected
Definition at line 505 of file ContactBlobCamera.cpp.
{
     if (params["senderId"] != parent_->id().id()) { return; }
     camera_id_ = static_cast<int>(params["camera_id"]);
     img_width_ = static_cast<int>(params["img_width"]);
     img_height_ = static_cast<int>(params["img_height"]);
     max_detect_range_ = params["max_detect_range"];
     focal_length_ = params["focal_length"];
     fps_ = params["fps"];
     az_thresh_ = params["az_thresh"];
     el_thresh_ = params["el_thresh"];
     fn_prob_ = params["fn_prob"];
     fp_prob_ = params["fp_prob"];
     max_false_positives_ = params["max_false_positives"];
     std_dev_w_ = params["std_dev_w"];
     std_dev_h_ = params["std_dev_h"];
     if (std_dev_w_ > img_width_) { std_dev_w_ = 10; } // TODO: use standard deviation values to inform the false positives
     if (std_dev_h_ > img_height_) { std_dev_h_ = 10; }
     canvas_width_ = 2 * focal_length_ * tan(az_thresh_ / 2.0);
     canvas_height_ = 2 * focal_length_ * tan(el_thresh_ / 2.0);
     // keep track of values of the parameters
     char buf[100];
     snprintf(buf, sizeof(buf), "\n===================================\n");
     parameters_file_ << buf << std::endl;
     for (const auto &kv : params) {
         snprintf(buf, sizeof(buf), "%s: %f", kv.first.c_str(), kv.second);
         parameters_file_ << buf << std::endl;
     }
 }
void scrimmage::sensor::ContactBlobCamera::draw_frustum (const std::vector< scrimmage_proto::ShapePtr > & frustum, double x_rot, double y_rot, double z_rot) protected
Definition at line 195 of file ContactBlobCamera.cpp.
References scrimmage::path_to_lines(), and scrimmage::set().
{
     if (frustum_shapes.size() != 8) {
         std::cerr << "ContactBlobCamera::draw_frustum: ERROR: input shape vector must be size 8" << std::endl;
         return;
     }
     double sensor_footprint_height = max_detect_range_ * tan(el_thresh_ / 2) * 2;
     double sensor_footprint_width = max_detect_range_ * tan(az_thresh_ / 2) * 2;
     Eigen::Vector3d sensor_UL(max_detect_range_,  sensor_footprint_width / 2, -sensor_footprint_height / 2);
     Eigen::Vector3d sensor_UR(max_detect_range_,  sensor_footprint_width / 2,  sensor_footprint_height / 2);
     Eigen::Vector3d sensor_LR(max_detect_range_, -sensor_footprint_width / 2,  sensor_footprint_height / 2);
     Eigen::Vector3d sensor_LL(max_detect_range_, -sensor_footprint_width / 2, -sensor_footprint_height / 2);
     std::vector<Eigen::Vector3d> sensor_scene_bb = {sensor_UL, sensor_UR, sensor_LR, sensor_LL, sensor_UL};
     // Rotate into sensor frame
     auto x_rotation = Eigen::AngleAxisd(x_rot, Eigen::Vector3d::UnitX());
     auto y_rotation = Eigen::AngleAxisd(y_rot, Eigen::Vector3d::UnitY());
     auto z_rotation = Eigen::AngleAxisd(z_rot, Eigen::Vector3d::UnitZ());
     auto A = Eigen::Translation3d(parent_->state_truth()->pos()) * z_rotation * y_rotation * x_rotation;
     for (size_t i = 0; i < sensor_scene_bb.size(); i++) {
         sensor_scene_bb[i] = A * sensor_scene_bb[i];
     }
     // Draw scene box
     auto scene_bb_line = std::make_shared<sp::Shape>();
     scene_bb_line->set_opacity(1.0);
     scene_bb_line->set_persistent(false);
     scene_bb_line->set_persist_duration(0.0);
     sc::set(scene_bb_line->mutable_color(), 0, 255, 0);
     sc::path_to_lines(sensor_scene_bb, scene_bb_line,
                       std::static_pointer_cast<EntityPlugin>(shared_from_this()));
     // draw 8 lines for the 4 points
     const Eigen::Vector3d fov_edge_start = parent_->state_truth()->pos();
     for (int idx_bb = 0; idx_bb != 4; ++idx_bb) {
         // box edges are idx 0-3 in frustum, fov edges are 4-7
         const size_t idx_fov_edge = idx_bb + 4;
         // set box line
         Eigen::Vector3d box_edge_start;
         const Eigen::Vector3d box_edge_end = sensor_scene_bb.at(idx_bb);
         if (idx_bb == 0) {
             box_edge_start = sensor_scene_bb.back();
         } else {
             box_edge_start = sensor_scene_bb.at(idx_bb-1);
         }
         scrimmage::set(frustum_shapes.at(idx_bb)->mutable_line()->mutable_start(), box_edge_start);
         scrimmage::set(frustum_shapes.at(idx_bb)->mutable_line()->mutable_end(), box_edge_end);
         // set fov line
         scrimmage::set(frustum_shapes.at(idx_fov_edge)->mutable_line()->mutable_start(), fov_edge_start);
         scrimmage::set(frustum_shapes.at(idx_fov_edge)->mutable_line()->mutable_end(), box_edge_end);
     }
     // draw all lines
     for (auto&& shape : frustum_shapes) {
         draw_shape(shape);
     }
 }
Member Data Documentation
std::ofstream scrimmage::sensor::ContactBlobCamera::parameters_file_ protected
Definition at line 61 of file ContactBlobCamera.h.
std::ofstream scrimmage::sensor::ContactBlobCamera::detections_file_ protected
Definition at line 61 of file ContactBlobCamera.h.
std::shared_ptr<std::default_random_engine> scrimmage::sensor::ContactBlobCamera::gener_ protected
Definition at line 63 of file ContactBlobCamera.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::ContactBlobCamera::pos_noise_ protected
Definition at line 64 of file ContactBlobCamera.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::ContactBlobCamera::orient_noise_ protected
Definition at line 65 of file ContactBlobCamera.h.
std::map<std::string, double> scrimmage::sensor::ContactBlobCamera::plugin_params_ protected
Definition at line 85 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::camera_id_ = 0 protected
Definition at line 86 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::img_width_ protected
Definition at line 87 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::img_height_ protected
Definition at line 88 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::max_detect_range_ protected
Definition at line 89 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::focal_length_ protected
Definition at line 90 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::fps_ protected
Definition at line 91 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::az_thresh_ protected
Definition at line 92 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::el_thresh_ protected
Definition at line 93 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::fn_prob_ protected
Definition at line 94 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::fp_prob_ protected
Definition at line 95 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::max_false_positives_ protected
Definition at line 96 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::std_dev_w_ protected
Definition at line 97 of file ContactBlobCamera.h.
int scrimmage::sensor::ContactBlobCamera::std_dev_h_ protected
Definition at line 98 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::canvas_width_ protected
Definition at line 99 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::canvas_height_ protected
Definition at line 100 of file ContactBlobCamera.h.
cv::Mat scrimmage::sensor::ContactBlobCamera::frame_ protected
Definition at line 102 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::last_frame_t_ protected
Definition at line 103 of file ContactBlobCamera.h.
PublisherPtr scrimmage::sensor::ContactBlobCamera::pub_ protected
Definition at line 105 of file ContactBlobCamera.h.
bool scrimmage::sensor::ContactBlobCamera::ignore_real_entities_ = false protected
Definition at line 107 of file ContactBlobCamera.h.
bool scrimmage::sensor::ContactBlobCamera::show_image_ = false protected
Definition at line 108 of file ContactBlobCamera.h.
bool scrimmage::sensor::ContactBlobCamera::show_frustum_ = false protected
Definition at line 109 of file ContactBlobCamera.h.
bool scrimmage::sensor::ContactBlobCamera::log_detections_ = false protected
Definition at line 110 of file ContactBlobCamera.h.
bool scrimmage::sensor::ContactBlobCamera::show_sim_contacts_ = false protected
Definition at line 111 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::last_contact_send_time_ = 0.0 protected
Definition at line 113 of file ContactBlobCamera.h.
double scrimmage::sensor::ContactBlobCamera::contact_send_dt_ = 1.0 protected
Definition at line 114 of file ContactBlobCamera.h.
std::string scrimmage::sensor::ContactBlobCamera::window_name_ = "ContactBlobCamera" protected
Definition at line 116 of file ContactBlobCamera.h.
std::vector<scrimmage_proto::ShapePtr> scrimmage::sensor::ContactBlobCamera::frustum_shapes_ protected
Definition at line 117 of file ContactBlobCamera.h.
scrimmage_proto::ShapePtr scrimmage::sensor::ContactBlobCamera::sim_tgt_sphere_ = std::make_shared<scrimmage_proto::Shape>() protected
Definition at line 118 of file ContactBlobCamera.h.
scrimmage::ContactMap scrimmage::sensor::ContactBlobCamera::sim_contacts_ protected
Definition at line 120 of file ContactBlobCamera.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/ContactBlobCamera/ContactBlobCamera.h
/root/scrimmage/scrimmage/src/plugins/sensor/ContactBlobCamera/ContactBlobCamera.cpp