SCRIMMAGE: straight.Straight Class Reference
straight.Straight Class Reference
Public Member Functions
def init (self, params)
def step_autonomy (self, t, dt)
def init (self, params)
def step_autonomy (self, t, dt)
Public Attributes
speed
state
desired_state
contacts
Detailed Description
Definition at line 5 of file straight.py.
Member Function Documentation
init() [1/2]
def straight.Straight.init (self, params)
Definition at line 6 of file straight.py.
     def init(self, params):
         self.speed = float(params['speed'])
         self.state = sc.State()
         self.desired_state = sc.State()
         self.contacts = dict()
Referenced by straight.Straight.init().
step_autonomy() [1/2]
def straight.Straight.step_autonomy (self, t, dt)
Definition at line 11 of file straight.py.
     def step_autonomy(self, t, dt):
         # Move in the forward direction.
         desired = sc.State()
         desired.vel = np.array([self.speed, 0, 0])
         self.desired_state = desired
         return True
References straight.Straight.desired_state, and straight.Straight.speed.
Referenced by straight.Straight.step_autonomy().
init() [2/2]
def straight.Straight.init (self, params)
Definition at line 6 of file straight.py.
     def init(self, params):
         self.speed = float(params['speed'])
         self.state = sc.State()
         self.desired_state = sc.State()
         self.contacts = dict()
References straight.Straight.contacts, straight.Straight.desired_state, straight.Straight.init(), straight.Straight.speed, and straight.Straight.state.
step_autonomy() [2/2]
def straight.Straight.step_autonomy (self, t, dt)
Definition at line 11 of file straight.py.
     def step_autonomy(self, t, dt):
         # Move in the forward direction.
         desired = sc.State()
         desired.vel = np.array([self.speed, 0, 0])
         desired.pos = self.state.pos
         self.desired_state = desired
         return True
References straight.Straight.desired_state, straight.Straight.speed, straight.Straight.state, and straight.Straight.step_autonomy().
Member Data Documentation
speed
straight.Straight.speed
Definition at line 7 of file straight.py.
Referenced by straight.Straight.init(), and straight.Straight.step_autonomy().
state
straight.Straight.state
Definition at line 8 of file straight.py.
Referenced by straight.Straight.init(), and straight.Straight.step_autonomy().
desired_state
straight.Straight.desired_state
Definition at line 9 of file straight.py.
Referenced by straight.Straight.init(), and straight.Straight.step_autonomy().
contacts
straight.Straight.contacts
Definition at line 10 of file straight.py.
Referenced by straight.Straight.init().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/python/straight.py