SCRIMMAGE: scrimmage::autonomy::MOOSNode Class Reference
scrimmage::autonomy::MOOSNode Class Reference
#include <MOOSNode.h>
Public Types
enum NodeReportType { OWNSHIP = 0, TRUTH_CONTACT, SENSOR_CONTACT }
typedef enum scrimmage::autonomy::MOOSNode::NodeReportType NodeReportType_t
Public Member Functions
MOOSNode ()
virtual ~MOOSNode ()
bool ready ()
scrimmage::State desired_state ()
void set_time_warp (double warp)
bool PublishNodeReport (NodeReportType_t report_type, std::string id, std::string sensor_id, double nav_x, double nav_y, double speed, double heading, double depth, std::string type, std::string mode, double time, std::string frame_number)
Protected Member Functions
bool OnNewMail (MOOSMSG_LIST &NewMail)
bool Iterate ()
bool OnConnectToServer ()
bool OnStartUp ()
void DoRegistrations ()
Protected Attributes
double appTick_
double commsTick_
double time_warp_
bool deployed_
std::mutex deployed_mutex_
std::mutex desired_mutex_
scrimmage::State desired_
Detailed Description
Definition at line 45 of file MOOSNode.h.
Member Typedef Documentation
typedef enum scrimmage::autonomy::MOOSNode::NodeReportType scrimmage::autonomy::MOOSNode::NodeReportType_t
Member Enumeration Documentation
enum scrimmage::autonomy::MOOSNode::NodeReportType
Enumerator
OWNSHIP
TRUTH_CONTACT
SENSOR_CONTACT
Definition at line 55 of file MOOSNode.h.
{
         OWNSHIP = 0,
         TRUTH_CONTACT,
         SENSOR_CONTACT
     } NodeReportType_t;
Constructor & Destructor Documentation
scrimmage::autonomy::MOOSNode::MOOSNode ()
Definition at line 47 of file MOOSNode.cpp.
                    : appTick_(1), commsTick_(1), time_warp_(1),
                        deployed_(false) {
 }
scrimmage::autonomy::MOOSNode::~MOOSNode () virtual
Definition at line 51 of file MOOSNode.cpp.
 {}
Member Function Documentation
bool scrimmage::autonomy::MOOSNode::ready ()
Definition at line 53 of file MOOSNode.cpp.
References deployed_, and deployed_mutex_.
                      {
     deployed_mutex_.lock();
     bool ready = deployed_;
     deployed_mutex_.unlock();
     return ready;
 }
sc::State scrimmage::autonomy::MOOSNode::desired_state ()
Definition at line 60 of file MOOSNode.cpp.
References desired_, and desired_mutex_.
{
     desired_mutex_.lock();
     sc::State s = desired_;
     desired_mutex_.unlock();
     return s;
 }
void scrimmage::autonomy::MOOSNode::set_time_warp (double warp)
Definition at line 67 of file MOOSNode.cpp.
References time_warp_.
{
     time_warp_ = warp;
 }
bool scrimmage::autonomy::MOOSNode::PublishNodeReport (NodeReportType_t report_type, std::string id, std::string sensor_id, double nav_x, double nav_y, double speed, double heading, double depth, std::string type, std::string mode, double time, std::string frame_number)
Definition at line 155 of file MOOSNode.cpp.
References OWNSHIP, SENSOR_CONTACT, and TRUTH_CONTACT.
{
     NodeRecord record;
     record.setName(id);
     record.setX(nav_x);
     record.setY(nav_y);
     record.setSpeed(speed);
     record.setHeading(heading);
     record.setDepth(depth);
     record.setType(type);
     record.setTimeStamp(MOOSTime());
     record.setProperty("FRAMENUM", frame_number);
     std::string moos_var;
     switch (report_type) {
     case OWNSHIP:
         moos_var = "NODE_REPORT_LOCAL";
         Notify("NAV_X", nav_x);
         Notify("NAV_Y", nav_y);
         Notify("NAV_HEADING", heading);
         Notify("NAV_SPEED", speed);
         Notify("NAV_DEPTH", depth);
         break;
     case TRUTH_CONTACT:
         moos_var = "NODE_REPORT";
         Notify(moos_var, record.getSpec());
         break;
     case SENSOR_CONTACT:
         record.setProperty("SENSOR_ID", sensor_id);
         moos_var = "SENSOR_CONTACT";
         Notify(moos_var, record.getSpec());
         break;
     default:
         break;
     }
     return true;
 }
bool scrimmage::autonomy::MOOSNode::OnNewMail (MOOSMSG_LIST & NewMail) protected
Definition at line 71 of file MOOSNode.cpp.
References scrimmage::Angles::deg2rad(), deployed_, deployed_mutex_, desired_, desired_mutex_, scrimmage::State::pos(), scrimmage::State::quat(), scrimmage::Quaternion::set(), and scrimmage::State::vel().
{
     MOOSMSG_LIST::iterator q;
     for (q = Mail.begin(); q != Mail.end(); ++q) {
         CMOOSMsg &msg = *q;
         std::string key = msg.GetKey();
         double dval = msg.GetDouble();
         if (key == "DESIRED_HEADING") {
             desired_mutex_.lock();
             desired_.quat().set(0, 0, sc::Angles::deg2rad(dval));
             desired_mutex_.unlock();
         } else if (key == "DESIRED_SPEED") {
             desired_mutex_.lock();
             desired_.vel() = Eigen::Vector3d::UnitX()*dval;
             desired_mutex_.unlock();
         } else if (key == "DESIRED_DEPTH") {
             desired_mutex_.lock();
             desired_.pos() = -Eigen::Vector3d::UnitZ()*dval;
             desired_mutex_.unlock();
         }  else if (key == "IVPHELM_STATE") {
             if (!deployed_) {
                 Notify("DEPLOY", "true");
                 Notify("RETURN", "false");
                 Notify("MOOS_MANUAL_OVERRIDE", "false");
                 deployed_mutex_.lock();
                 deployed_ = true;
                 deployed_mutex_.unlock();
             }
         }
     }
     return(true);
 }
bool scrimmage::autonomy::MOOSNode::Iterate () protected
Definition at line 119 of file MOOSNode.cpp.
{
     return true;
 }
bool scrimmage::autonomy::MOOSNode::OnConnectToServer () protected
Definition at line 109 of file MOOSNode.cpp.
References DoRegistrations(), and time_warp_.
{
     DoRegistrations();
     SetMOOSTimeWarp(time_warp_);
     return true;
 }
bool scrimmage::autonomy::MOOSNode::OnStartUp () protected
Definition at line 128 of file MOOSNode.cpp.
References appTick_, commsTick_, and DoRegistrations().
{
     appTick_ = 1;
     commsTick_ = 1;
     if (!m_MissionReader.GetConfigurationParam("AppTick", appTick_)) {
         MOOSTrace("Warning, AppTick not set.\n");
     }
     if (!m_MissionReader.GetConfigurationParam("CommsTick", commsTick_)) {
         MOOSTrace("Warning, CommsTick not set.\n");
     }
     SetAppFreq(appTick_);
     SetCommsFreq(commsTick_);
     DoRegistrations();
     return true;
 }
void scrimmage::autonomy::MOOSNode::DoRegistrations () protected
Definition at line 148 of file MOOSNode.cpp.
Referenced by OnConnectToServer(), and OnStartUp().
{
     Register("DESIRED_HEADING", 0.0);
     Register("DESIRED_SPEED", 0.0);
     Register("DESIRED_DEPTH", 0.0);
     Register("IVPHELM_STATE", 0.0);
 }
Member Data Documentation
double scrimmage::autonomy::MOOSNode::appTick_ protected
Definition at line 71 of file MOOSNode.h.
Referenced by OnStartUp().
double scrimmage::autonomy::MOOSNode::commsTick_ protected
Definition at line 72 of file MOOSNode.h.
Referenced by OnStartUp().
double scrimmage::autonomy::MOOSNode::time_warp_ protected
Definition at line 73 of file MOOSNode.h.
Referenced by OnConnectToServer(), and set_time_warp().
bool scrimmage::autonomy::MOOSNode::deployed_ protected
Definition at line 75 of file MOOSNode.h.
Referenced by OnNewMail(), and ready().
std::mutex scrimmage::autonomy::MOOSNode::deployed_mutex_ protected
Definition at line 76 of file MOOSNode.h.
Referenced by OnNewMail(), and ready().
std::mutex scrimmage::autonomy::MOOSNode::desired_mutex_ protected
Definition at line 92 of file MOOSNode.h.
Referenced by desired_state(), and OnNewMail().
scrimmage::State scrimmage::autonomy::MOOSNode::desired_ protected
Definition at line 93 of file MOOSNode.h.
Referenced by desired_state(), and OnNewMail().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/MOOSAutonomy/MOOSNode.h
/root/scrimmage/scrimmage/src/plugins/autonomy/MOOSAutonomy/MOOSNode.cpp