SCRIMMAGE: scrimmage::autonomy::WaypointList Class Reference
scrimmage::autonomy::WaypointList Class Reference
#include <WaypointList.h>
Public Types
enum WaypointMode { WaypointMode::follow_once = 0, WaypointMode::back_and_forth = 1, WaypointMode::loiter = 2, WaypointMode::racetrack = 3 }
Public Member Functions
WaypointList ()
std::list< Waypoint > & waypoints ()
void set_mode (WaypointMode mode)
WaypointMode mode ()
void set_cycles (unsigned int cycles)
unsigned int cycles ()
unsigned int size ()
Protected Attributes
std::list< Waypoint > waypoints_
WaypointMode mode_ = WaypointMode::follow_once
unsigned int cycles_ = 1
Friends
std::ostream & operator<< (std::ostream &os, WaypointList &wp_list)
Detailed Description
Definition at line 43 of file WaypointList.h.
Member Enumeration Documentation
enum scrimmage::autonomy::WaypointList::WaypointMode strong
Enumerator
follow_once
back_and_forth
loiter
racetrack
Definition at line 45 of file WaypointList.h.
{
         follow_once = 0,
         back_and_forth = 1,
         loiter = 2,
         racetrack = 3
     };
Constructor & Destructor Documentation
scrimmage::autonomy::WaypointList::WaypointList () inline
Definition at line 52 of file WaypointList.h.
                    {
     }
Member Function Documentation
std::list<Waypoint>& scrimmage::autonomy::WaypointList::waypoints () inline
Definition at line 55 of file WaypointList.h.
References waypoints_.
 { return waypoints_; }
void scrimmage::autonomy::WaypointList::set_mode (WaypointMode mode) inline
Definition at line 56 of file WaypointList.h.
References mode(), and mode_.
 { mode_ = mode; }
WaypointMode scrimmage::autonomy::WaypointList::mode () inline
Definition at line 57 of file WaypointList.h.
References mode_.
Referenced by set_mode().
 { return mode_; }
void scrimmage::autonomy::WaypointList::set_cycles (unsigned int cycles) inline
Definition at line 66 of file WaypointList.h.
References cycles(), and cycles_.
{
         cycles_ = cycles;
     }
unsigned int scrimmage::autonomy::WaypointList::cycles () inline
Definition at line 70 of file WaypointList.h.
References cycles_.
Referenced by set_cycles().
{
         return cycles_;
     }
unsigned int scrimmage::autonomy::WaypointList::size () inline
Definition at line 74 of file WaypointList.h.
References waypoints_.
{
         return waypoints_.size();
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, WaypointList & wp_list) friend
Definition at line 59 of file WaypointList.h.
{
         for (Waypoint wp : wp_list.waypoints()) {
             os << wp << std::endl;
         }
         return os;
     }
Member Data Documentation
std::list<Waypoint> scrimmage::autonomy::WaypointList::waypoints_ protected
Definition at line 79 of file WaypointList.h.
Referenced by size(), and waypoints().
WaypointMode scrimmage::autonomy::WaypointList::mode_ = WaypointMode::follow_once protected
Definition at line 80 of file WaypointList.h.
Referenced by mode(), and set_mode().
unsigned int scrimmage::autonomy::WaypointList::cycles_ = 1 protected
Definition at line 81 of file WaypointList.h.
Referenced by cycles(), and set_cycles().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/WaypointGenerator/WaypointList.h