SCRIMMAGE: scrimmage::sensor::SimpleINS Class Reference
scrimmage::sensor::SimpleINS Class Reference
#include <SimpleINS.h>
Public Member Functions
void init (std::map< std::string, std::string > &params) override
bool step () override
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
bool gps_fix_
PublisherPtr pub_
PublisherPtr pub_cep_
PublisherPtr pub_seastate_
std::vector< std::shared_ptr< std::normal_distribution< double > > > pos_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > vel_noise_
std::vector< std::shared_ptr< std::normal_distribution< double > > > orient_noise_
Eigen::Vector3d pos_error_accum_ = Eigen::Vector3d::Zero()
Eigen::Vector3d vel_Nminus1 = Eigen::Vector3d::Zero()
Eigen::Vector3d accel_ = Eigen::Vector3d::Zero()
Eigen::MatrixXd m_
bool init_m_ = true
double surface_timer_ = 0
double prev_time_ = 0
double sea_state_gps_
double SeaState_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file SimpleINS.h.
Member Function Documentation
void scrimmage::sensor::SimpleINS::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 56 of file SimpleINS.cpp.
References scrimmage::get_vec().
{
     // Noise params information
     auto add_noise = [&](std::string prefix, auto &noise_vec) {
         for (int i = 0; i < 3; i++) {
             std::string tag_name = prefix + "_" + std::to_string(i);
             std::vector<double> vec;
             double mean, stdev;
             std::tie(mean, stdev) = get_vec(tag_name, params, " ", vec, 2) ?
                 std::make_pair(vec[0], vec[1]) : std::make_pair(0.0, 1.0);
             noise_vec.push_back(parent_->random()->make_rng_normal(mean, stdev));
         }
     };
     add_noise("pos_noise", pos_noise_);
     add_noise("vel_noise", vel_noise_);
     add_noise("orient_noise", orient_noise_);
     pub_ = advertise("LocalNetwork", "StateWithCovariance");
     pub_cep_ = advertise("LocalNetwork", "INS_CEP");
     pub_seastate_ = advertise("LocalNetwork", "INS_SS");
     // get xml info
     sea_state_gps_ = sc::get<double>("sea_state_gps", params, 99);
     // GPS information
     auto gps_cb = [&](auto &msg) {
         gps_fix_ = msg->data.fixed();
     };
     subscribe<sm::GPSStatus>("GlobalNetwork", "GPSStatus", gps_cb);
     surface_timer_ = sc::get<double>("surface_timer", params, 10);
     parent_->state() = std::make_shared<State>();
     *(parent_->state()) = *(parent_->state_truth());
 }
bool scrimmage::sensor::SimpleINS::step () override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 96 of file SimpleINS.cpp.
References scrimmage::StateWithCovariance::covariance(), scrimmage::State::pos(), scrimmage::State::quat(), and scrimmage::State::vel().
                      {
     auto gener = parent_->random()->gener();
     auto msg_SS = std::make_shared<sc::Message<double>>();
     msg_SS->data = sea_state_gps_;
     pub_seastate_->publish(msg_SS);
     // Make a copy of the current state
     StateWithCovariance ns(*(parent_->state_truth()));
     auto msg = std::make_shared<Message<StateWithCovariance>>();
     if (init_m_) {
         m_ = Eigen::MatrixXd::Identity(ns.covariance().rows(), ns.covariance().cols());
         init_m_ = false;
     }
       // Acceleration
         accel_ = ns.vel() - vel_Nminus1;
         vel_Nminus1 = ns.vel();
     for (int i = 0; i < 3; i++) {
         accel_(i) = abs(accel_(i) / .01);
         if (accel_(i) > 1) {
             accel_(i) = 1;
             }
     }
     // Use gen in order to create a growing covariance
     double pos_noise_0 = (*pos_noise_[0])(*gener) * (accel_(0));
     double pos_noise_1 = (*pos_noise_[1])(*gener) * (accel_(1));
     const int arrayNum[4] = {15, 30, 45, 60};
     if (!gps_fix_) {
         m_(0, 0) += (pos_noise_0 < 0 ? -1*pos_noise_0 : pos_noise_0);
         m_(1, 1) += (pos_noise_1 < 0 ? -1*pos_noise_1 : pos_noise_1);
         prev_time_ = time_->t();
         int randIdx = rand() % 4;
         surface_timer_ = arrayNum[randIdx];
         if (sea_state_gps_ > 1) {
             surface_timer_ += 60;
         }
     } else {
         // GPS fix on - wait on surface timer and snap back to an identity matrix
         m_(0, 0) += (pos_noise_0 < 0 ? -1*pos_noise_0 : pos_noise_0);
         m_(1, 1) += (pos_noise_1 < 0 ? -1*pos_noise_1 : pos_noise_1);
         // GPS fix on - wait on surface timer and snap back to an identity matrix
         if (time_->t() - prev_time_ > surface_timer_) {
            m_ = Eigen::MatrixXd::Identity(ns.covariance().rows(), ns.covariance().cols());
            // Reset the position error accumulator
            pos_error_accum_ = Eigen::Vector3d::Zero();
         }
     }
     // Create noisy position / velocity
     for (int i = 0; i < 3; i++) {
          // std::cout << "Accelration for " << i << ", is: " << (accel_(i)) << std::endl;
          pos_error_accum_(i) += (*pos_noise_[i])(*gener) * (accel_(i));
          // msg->data.pos()(i) = ns.pos()(i) + (*pos_noise_[i])(*gener);
         msg->data.vel()(i) = ns.vel()(i) + (*vel_noise_[i])(*gener);
     }
       msg->data.pos() = ns.pos() + pos_error_accum_;
     msg->data.quat() = ns.quat()
     * Quaternion(Eigen::Vector3d::UnitX(), (*orient_noise_[0])(*gener))
     * Quaternion(Eigen::Vector3d::UnitY(), (*orient_noise_[1])(*gener))
     * Quaternion(Eigen::Vector3d::UnitZ(), (*orient_noise_[2])(*gener));
     msg->data.set_covariance(m_);
     double sig_L;
     double sig_S;
     if (m_(0, 0) < m_(1, 1)) {
         sig_L = sqrt(m_(1, 1));
         sig_S = sqrt(m_(0, 0));
     } else {
         sig_L = sqrt(m_(0, 0));
         sig_S = sqrt(m_(1, 1));
     }
     double sig_w = sig_S / sig_L;
     double CEP;
     if (sig_w < 0.5) {
         CEP = sig_L * (0.67 + 0.8 * sig_w * sig_w);
     } else {
         CEP = 0.59 * sig_L * (1 + sig_w);
     }
     auto msg_cep = std::make_shared<sc::Message<double>>();
         msg_cep->data = CEP;
         pub_cep_->publish(msg_cep);
     // Publish StateWCovariance msg
     pub_->publish(msg);
     // Update the entity's state.
     *(parent_->state()) = static_cast<sc::State>(msg->data);
     return true;
 }
Member Data Documentation
bool scrimmage::sensor::SimpleINS::gps_fix_ protected
Definition at line 52 of file SimpleINS.h.
PublisherPtr scrimmage::sensor::SimpleINS::pub_ protected
Definition at line 54 of file SimpleINS.h.
PublisherPtr scrimmage::sensor::SimpleINS::pub_cep_ protected
Definition at line 55 of file SimpleINS.h.
PublisherPtr scrimmage::sensor::SimpleINS::pub_seastate_ protected
Definition at line 56 of file SimpleINS.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::SimpleINS::pos_noise_ protected
Definition at line 58 of file SimpleINS.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::SimpleINS::vel_noise_ protected
Definition at line 59 of file SimpleINS.h.
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::SimpleINS::orient_noise_ protected
Definition at line 60 of file SimpleINS.h.
Eigen::Vector3d scrimmage::sensor::SimpleINS::pos_error_accum_ = Eigen::Vector3d::Zero() protected
Definition at line 62 of file SimpleINS.h.
Eigen::Vector3d scrimmage::sensor::SimpleINS::vel_Nminus1 = Eigen::Vector3d::Zero() protected
Definition at line 63 of file SimpleINS.h.
Eigen::Vector3d scrimmage::sensor::SimpleINS::accel_ = Eigen::Vector3d::Zero() protected
Definition at line 64 of file SimpleINS.h.
Eigen::MatrixXd scrimmage::sensor::SimpleINS::m_ protected
Definition at line 66 of file SimpleINS.h.
bool scrimmage::sensor::SimpleINS::init_m_ = true protected
Definition at line 67 of file SimpleINS.h.
double scrimmage::sensor::SimpleINS::surface_timer_ = 0 protected
Definition at line 69 of file SimpleINS.h.
double scrimmage::sensor::SimpleINS::prev_time_ = 0 protected
Definition at line 70 of file SimpleINS.h.
double scrimmage::sensor::SimpleINS::sea_state_gps_ protected
Definition at line 71 of file SimpleINS.h.
double scrimmage::sensor::SimpleINS::SeaState_ protected
Definition at line 72 of file SimpleINS.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/SimpleINS/SimpleINS.h
/root/scrimmage/scrimmage/src/plugins/sensor/SimpleINS/SimpleINS.cpp