SCRIMMAGE: scrimmage::network::LocalNetwork Class Reference
scrimmage::network::LocalNetwork Class Reference
#include <LocalNetwork.h>
Public Member Functions
LocalNetwork ()
bool init (std::map< std::string, std::string > &mission_params, std::map< std::string, std::string > &plugin_params) override
Public Member Functions inherited from scrimmage::Network
Network ()
virtual bool step (std::map< std::string, std::list< NetworkDevicePtr >> &pubs, std::map< std::string, std::list< NetworkDevicePtr >> &subs)
std::string type () override
void set_rtree (const RTreePtr &rtree)
void set_random (RandomPtr random)
void close (double t) override
virtual void set_mission_parse (MissionParsePtr mp)
double comm_delay ()
void set_comm_delay (double del)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
std::shared_ptr< const Time > getTime ()
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
bool is_reachable (const scrimmage::EntityPluginPtr &pub_plugin, const scrimmage::EntityPluginPtr &sub_plugin) override
bool is_successful_transmission (const scrimmage::EntityPluginPtr &pub_plugin, const scrimmage::EntityPluginPtr &sub_plugin) override
Protected Member Functions inherited from scrimmage::Network
virtual double get_transmission_delay ()
bool network_init (std::map< std::string, std::string > &, std::map< std::string, std::string > &)
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Attributes inherited from scrimmage::Network
RTreePtr rtree_
RandomPtr random_
MissionParsePtr mp_
double comm_delay_ = -1
bool is_stochastic_delay_ = false
std::unordered_map< int, std::unordered_map< int, bool > > reachable_map_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Detailed Description
Definition at line 46 of file LocalNetwork.h.
Constructor & Destructor Documentation
LocalNetwork()
scrimmage::network::LocalNetwork::LocalNetwork ()
Referenced by REGISTER_PLUGIN().
Member Function Documentation
init()
bool scrimmage::network::LocalNetwork::init (std::map< std::string, std::string > & mission_params, std::map< std::string, std::string > & plugin_params) override virtual
Reimplemented from scrimmage::Network.
Referenced by REGISTER_PLUGIN().
is_reachable()
bool scrimmage::network::LocalNetwork::is_reachable (const scrimmage::EntityPluginPtr & pub_plugin, const scrimmage::EntityPluginPtr & sub_plugin) override protected virtual
Reimplemented from scrimmage::Network.
Referenced by REGISTER_PLUGIN().
is_successful_transmission()
bool scrimmage::network::LocalNetwork::is_successful_transmission (const scrimmage::EntityPluginPtr & pub_plugin, const scrimmage::EntityPluginPtr & sub_plugin) override protected virtual
Reimplemented from scrimmage::Network.
Referenced by REGISTER_PLUGIN().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/network/LocalNetwork/LocalNetwork.h