SCRIMMAGE: scrimmage::motion::SimpleAircraft Class Reference
scrimmage::motion::SimpleAircraft Class Reference
#include <SimpleAircraft.h>
Public Member Functions
virtual std::tuple< int, int, int > version ()
bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params) override
bool step (double time, double dt) override
void model (const vector_t &x, vector_t &dxdt, double t) override
void teleport (scrimmage::StatePtr &state) override
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
scrimmage::PID heading_pid_
scrimmage::PID alt_pid_
scrimmage::PID vel_pid_
double length_ {50.0}
double speedTarget_ {50.0}
double lengthSlopePerSpeed_ {0.0}
double min_velocity_ {15.0}
double max_velocity_ {40.0}
double max_roll_ {30.0}
double max_pitch_ {30.0}
double max_pitch_rate_ {57.3}
double max_roll_rate_ {57.3}
uint8_t throttle_idx_ {0}
uint8_t roll_rate_idx_ {0}
uint8_t pitch_rate_idx_ {0}
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
Detailed Description
Definition at line 52 of file SimpleAircraft.h.
Member Function Documentation
std::tuple< int, int, int > scrimmage::motion::SimpleAircraft::version () virtual
Definition at line 68 of file SimpleAircraft.cpp.
{
     return std::tuple<int, int, int>(0, 0, 1);
 }
bool scrimmage::motion::SimpleAircraft::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 72 of file SimpleAircraft.cpp.
References PITCH, scrimmage::Quaternion::pitch(), scrimmage::motion::ROLL, scrimmage::Quaternion::roll(), scrimmage::motion::SPEED, X, Y, YAW, scrimmage::Quaternion::yaw(), and Z.
{
     x_.resize(MODEL_NUM_ITEMS);
     Eigen::Vector3d &pos = state_->pos();
     Quaternion &quat = state_->quat();
     min_velocity_ = get("min_velocity", params, 15.0);
     max_velocity_ = get("max_velocity", params, 40.0);
     max_roll_ = Angles::deg2rad(get("max_roll", params, 30.0));
     max_pitch_ = Angles::deg2rad(get("max_pitch", params, 30.0));
     max_pitch_rate_ = Angles::deg2rad(get("max_pitch_rate", params, 57.3));
     max_roll_rate_ = Angles::deg2rad(get("max_roll_rate", params, 57.3));
     x_[X] = pos(0);
     x_[Y] = pos(1);
     x_[Z] = pos(2);
     x_[ROLL] = clamp(quat.roll(), -max_roll_, max_roll_);
     x_[PITCH] = clamp(quat.pitch(), -max_pitch_, max_pitch_);
     x_[YAW] = quat.yaw();
     x_[SPEED] = clamp(state_->vel().norm(), min_velocity_, max_velocity_);
     length_ = get("turning_radius", params, 50.0);
     speedTarget_ = get("speed_target", params, 50.0);  // The "0" speed for adjusting the turning radius
     lengthSlopePerSpeed_ = get("radius_slope_per_speed", params, 0.0);  // Enables adjusting the turning radius based on speed
     state_->pos() << x_[X], x_[Y], x_[Z];
     state_->quat().set(-x_[ROLL], x_[PITCH], x_[YAW]);
     state_->vel() << x_[SPEED] * cos(x_[5]), x_[SPEED] * sin(x_[5]), 0;
     throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::In);
     roll_rate_idx_ = vars_.declare(VariableIO::Type::roll_rate, VariableIO::Direction::In);
     pitch_rate_idx_ = vars_.declare(VariableIO::Type::pitch_rate, VariableIO::Direction::In);
     return true;
 }
bool scrimmage::motion::SimpleAircraft::step (double time, double dt) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 109 of file SimpleAircraft.cpp.
References PITCH, scrimmage::motion::ROLL, scrimmage::motion::SPEED, X, Y, YAW, and Z.
{
     // Need to saturate state variables before model runs
     x_[ROLL] = clamp(x_[ROLL], -max_roll_, max_roll_);
     x_[PITCH] = clamp(x_[PITCH], -max_pitch_, max_pitch_);
     x_[SPEED] = clamp(x_[SPEED], min_velocity_, max_velocity_);
     ode_step(dt);
     state_->pos() << x_[X], x_[Y], x_[Z];
     state_->quat().set(-x_[ROLL], x_[PITCH], x_[YAW]);
     state_->vel() << x_[SPEED] * cos(x_[YAW]) * cos(x_[PITCH]), x_[SPEED] * sin(x_[YAW]) * cos(x_[PITCH]), x_[SPEED] * sin(x_[PITCH]);
     return true;
 }
void scrimmage::motion::SimpleAircraft::model (const vector_t & x, vector_t & dxdt, double t) override virtual
0 : x-position 1 : y-position 2 : z-position 3 : roll 4 : pitch 5 : yaw 6 : speed
Reimplemented from scrimmage::MotionModel.
Definition at line 124 of file SimpleAircraft.cpp.
References PITCH, scrimmage::motion::ROLL, scrimmage::motion::SPEED, X, Y, YAW, and Z.
{
     double throttle = vars_.input(throttle_idx_);
     double roll_rate = vars_.input(roll_rate_idx_);
     double pitch_rate = vars_.input(pitch_rate_idx_);
     // Saturate control inputs
     throttle = clamp(throttle, -100.0, 100.0);
     roll_rate = clamp(roll_rate, -max_roll_rate_, max_roll_rate_);
     pitch_rate = clamp(pitch_rate, -max_pitch_rate_, max_pitch_rate_);
     double xy_speed = x[SPEED] * cos(x[PITCH]);
     dxdt[X] = xy_speed*cos(x[YAW]);
     dxdt[Y] = xy_speed*sin(x[YAW]);
     dxdt[Z] = -sin(x[PITCH])*x[SPEED];
     dxdt[ROLL] = roll_rate;
     dxdt[PITCH] = pitch_rate;
     // Adjust the length based on the speed
     double currentLength = length_ + lengthSlopePerSpeed_ * (x[SPEED] - speedTarget_);
     dxdt[YAW] = x[SPEED]/currentLength*tan(x[ROLL]);
     dxdt[SPEED] = throttle/5;
 }
void scrimmage::motion::SimpleAircraft::teleport (scrimmage::StatePtr & state) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 154 of file SimpleAircraft.cpp.
References PITCH, scrimmage::motion::ROLL, scrimmage::motion::SPEED, X, Y, YAW, and Z.
{
     x_[X] = state->pos()[0];
     x_[Y] = state->pos()[1];
     x_[Z] = state->pos()[2];
     x_[ROLL] = state->quat().roll();
     x_[PITCH] = state->quat().pitch();
     x_[YAW] = state->quat().yaw();
     x_[SPEED] = state->vel()[0];
 }
Member Data Documentation
scrimmage::PID scrimmage::motion::SimpleAircraft::heading_pid_ protected
Definition at line 65 of file SimpleAircraft.h.
scrimmage::PID scrimmage::motion::SimpleAircraft::alt_pid_ protected
Definition at line 66 of file SimpleAircraft.h.
scrimmage::PID scrimmage::motion::SimpleAircraft::vel_pid_ protected
Definition at line 67 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::length_ {50.0} protected
Definition at line 69 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::speedTarget_ {50.0} protected
Definition at line 70 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::lengthSlopePerSpeed_ {0.0} protected
Definition at line 72 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::min_velocity_ {15.0} protected
Definition at line 74 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::max_velocity_ {40.0} protected
Definition at line 75 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::max_roll_ {30.0} protected
Definition at line 76 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::max_pitch_ {30.0} protected
Definition at line 77 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::max_pitch_rate_ {57.3} protected
Definition at line 78 of file SimpleAircraft.h.
double scrimmage::motion::SimpleAircraft::max_roll_rate_ {57.3} protected
Definition at line 79 of file SimpleAircraft.h.
uint8_t scrimmage::motion::SimpleAircraft::throttle_idx_ {0} protected
Definition at line 81 of file SimpleAircraft.h.
uint8_t scrimmage::motion::SimpleAircraft::roll_rate_idx_ {0} protected
Definition at line 82 of file SimpleAircraft.h.
uint8_t scrimmage::motion::SimpleAircraft::pitch_rate_idx_ {0} protected
Definition at line 83 of file SimpleAircraft.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/SimpleAircraft/SimpleAircraft.h
/root/scrimmage/scrimmage/src/plugins/motion/SimpleAircraft/SimpleAircraft.cpp