SCRIMMAGE: scrimmage::sensor::ROSIMUSensor Class Reference
scrimmage::sensor::ROSIMUSensor Class Reference
#include <ROSIMUSensor.h>
Public Member Functions
ROSIMUSensor ()
void init (std::map< std::string, std::string > &params) override
bool step () override
void close (double t) override
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
std::string ros_namespace_
std::shared_ptr< ros::NodeHandle > nh_
ros::Publisher imu_pub_
Eigen::Vector3d prev_vel_
Quaternion prev_quat_
double prev_time_ = 0.0
scrimmage::CSV csv
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 52 of file ROSIMUSensor.h.
Constructor & Destructor Documentation
scrimmage::sensor::ROSIMUSensor::ROSIMUSensor ()
Definition at line 60 of file ROSIMUSensor.cpp.
 {}
Member Function Documentation
void scrimmage::sensor::ROSIMUSensor::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 62 of file ROSIMUSensor.cpp.
{
     if (!ros::isInitialized()) {
         int argc = 0;
         // scrimmage handles it's own SIGINT/SIGTERM shutdown in main.cpp
         ros::init(argc, NULL, "scrimmage", ros::init_options::NoSigintHandler);
     }
     nh_ = std::make_shared<ros::NodeHandle>();
     // Setup robot namespace
     ros_namespace_ = sc::get<std::string>("ros_namespace_prefix", params, "robot");
     ros_namespace_ += std::to_string(parent_->id().id());
     // Create Publisher
     imu_pub_ = nh_->advertise<sensor_msgs::Imu>(ros_namespace_ + "/imu", 1);
     // Open imu_data CSV for append (app) and set column headers
     std::string csv_filename = parent_->mp()->log_dir() + "/imu_data.csv";
     if (!csv.open_output(csv_filename, std::ios_base::app)) std::cout << "Couldn't create csv file" << endl;
     if (!csv.output_is_open()) cout << "File isn't open. Can't write to CSV" << endl;
     csv.set_column_headers("time, dt, ENU_POSX, ENU_POSY, ENU_POSZ, ENU_VELX, ENU_VELY, ENU_VELZ, BodytoNED_roll, BodytoNED_pitch, BodytoNED_yaw");
     prev_vel_ = parent_->state_truth()->vel();
     prev_quat_ = parent_->state_truth()->quat();
     prev_time_ = time_->t();
 }
bool scrimmage::sensor::ROSIMUSensor::step () override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 89 of file ROSIMUSensor.cpp.
References scrimmage::Quaternion::pitch(), scrimmage::Quaternion::roll(), scrimmage::Quaternion::set(), and scrimmage::Quaternion::yaw().
{
     // Obtain current state information
     sc::StatePtr &state = parent_->state_truth();
     double time_now = time_->t();
     double dt = time_now - prev_time_;
     // cout << " " << endl;
     // cout << "Current Vel: \n" << state->vel() << endl;
     // cout << "Prev Vel: \n" << prev_vel_ << endl;
     // cout << "dt: " << dt << endl;
     // Fill IMU Message
     sensor_msgs::Imu imu_msg;
     // Header
     std_msgs::Header header; // empty header
     // TODO: header.frame = ? // No system for ROS Frame ID's yet
     header.stamp = ros::Time::now(); // time
     imu_msg.header = header;
     // Orientation
     imu_msg.orientation.x = state->quat().x();
     imu_msg.orientation.y = state->quat().y();
     imu_msg.orientation.z = state->quat().z();
     imu_msg.orientation.w = state->quat().w();
     // Angular Velocity
     // cout << "D Theta X: " << (state->quat().roll() - prev_quat_.roll()) / dt << endl;
     imu_msg.angular_velocity.x = (state->quat().roll() - prev_quat_.roll()) / dt;
     imu_msg.angular_velocity.y = (state->quat().pitch() - prev_quat_.pitch()) / dt;
     imu_msg.angular_velocity.z = (state->quat().yaw() - prev_quat_.yaw()) / dt;
     // Linear Acceleration
     // cout << "D Vel X: " << (state->vel().x() - prev_vel_.x()) / dt << endl;
     imu_msg.linear_acceleration.x = (state->vel().x() - prev_vel_.x()) / dt;
     imu_msg.linear_acceleration.y = (state->vel().y() - prev_vel_.y()) / dt;
     imu_msg.linear_acceleration.z = (state->vel().z() - prev_vel_.z()) / dt;
     // Publish Compass information
     imu_pub_.publish(imu_msg);
     // Update prev_state_
     prev_vel_ = state->vel();
     prev_quat_ = state->quat();
     prev_time_ = time_now;
     // Convert RPY_ENUtoBody to RPYBodytoNED
     // ENU to NED: +PI/2 rotation about Z (Up) followed by a +PI rotation about X (old East/new North)
     // Convert ENUtoBody to NED
     // Angles to rotate by
     double zTo = 90 * (M_PI / 180); // +PI/2 rotation about Z (Up)
     double yTo = 180 * (M_PI / 180); // +PI rotation about X (Y = new X after Z rotation)
     // Normalize entity quaternion
     Eigen::Quaterniond ENU_quat = state->quat();
     // Testing with different initial quaternions
     // Eigen::Quaterniond ENU_quat = Eigen::Quaterniond(0.0, 0.0, 0.0, 0.0); // RPY init = 0,0,0 final = 180,0,90
     // Eigen::Quaterniond ENU_quat = Eigen::Quaterniond(0.0, 0.7071068, -0.7071068, 0.0); // RPY init = 180,0,90 final = 0,0,180
     ENU_quat.normalize();
     // cout << " " << endl;
     // cout << "ENUtoBody_quat: \n" << ENU_quat.w() << "\n" <<  ENU_quat.vec() << endl;
     // Rotate ENU Quaternion to NED, Order matters
     Eigen::Quaterniond NED_quat;
     NED_quat = Eigen::AngleAxisd(zTo, Eigen::Vector3d::UnitZ()) * ENU_quat; // +PI/2 rotation about Z (Up)
     NED_quat = Eigen::AngleAxisd(yTo, Eigen::Vector3d::UnitY()) * NED_quat; // +PI rotation about new X (Y = new X after Z rotation)
     // Take Inverse
     Eigen::Quaterniond BodytoNED_quat = NED_quat.inverse();
     // cout << "BodytoNED_quat: \n" << BodytoNED_quat.w() << "\n" << BodytoNED_quat.vec() << endl;
     // Get RPY
     Quaternion ned;
     ned.set(BodytoNED_quat.w(),
             BodytoNED_quat.vec().x(),
             BodytoNED_quat.vec().y(),
             BodytoNED_quat.vec().z());
     // cout << "BodytoNED RPY (rad): " << ned.roll() << " " << ned.pitch() << " " << ned.yaw() << endl;
     // cout << "BodytoNED RPY (deg): " << ned.roll()*(180 / M_PI) << " " << ned.pitch()*(180 / M_PI) << " " << ned.yaw()*(180 / M_PI) << endl;
     // cout << " " << endl;
     // cout << " " << endl;
     // cout << " " << endl;
     // cout << " " << endl;
     // Write IMU data to CSV
     // Write the CSV file to the root log directory file name = imu_data.csv
     if (!csv.output_is_open()) {
             cout << "File isn't open. Can't append to CSV" << endl;
             }
     csv.append(sc::CSV::Pairs{
     {"time", time_now},
     {"dt", dt},
     {"ENU_POSX", state->pos()(0)},
     {"ENU_POSY", state->pos()(1)},
     {"ENU_POSZ", state->pos()(2)},
     {"ENU_VELX", state->vel()(0)},
     {"ENU_VELY", state->vel()(1)},
     {"ENU_VELZ", state->vel()(2)},
     {"BodytoNED_roll", ned.roll()},
     {"BodytoNED_pitch", ned.pitch()},
     {"BodytoNED_yaw", ned.yaw()}}, true, true);
     return true;
 }
void scrimmage::sensor::ROSIMUSensor::close (double t) override virtual
Reimplemented from scrimmage::EntityPlugin.
Definition at line 192 of file ROSIMUSensor.cpp.
{
     csv.close_output();
 }
Member Data Documentation
std::string scrimmage::sensor::ROSIMUSensor::ros_namespace_ protected
Definition at line 60 of file ROSIMUSensor.h.
std::shared_ptr<ros::NodeHandle> scrimmage::sensor::ROSIMUSensor::nh_ protected
Definition at line 61 of file ROSIMUSensor.h.
ros::Publisher scrimmage::sensor::ROSIMUSensor::imu_pub_ protected
Definition at line 62 of file ROSIMUSensor.h.
Eigen::Vector3d scrimmage::sensor::ROSIMUSensor::prev_vel_ protected
Definition at line 64 of file ROSIMUSensor.h.
Quaternion scrimmage::sensor::ROSIMUSensor::prev_quat_ protected
Definition at line 65 of file ROSIMUSensor.h.
double scrimmage::sensor::ROSIMUSensor::prev_time_ = 0.0 protected
Definition at line 66 of file ROSIMUSensor.h.
scrimmage::CSV scrimmage::sensor::ROSIMUSensor::csv protected
Definition at line 68 of file ROSIMUSensor.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/ROSIMUSensor/ROSIMUSensor.h
/root/scrimmage/scrimmage/src/plugins/sensor/ROSIMUSensor/ROSIMUSensor.cpp