SCRIMMAGE: scrimmage::autonomy::OpenAIObservations Class Reference
scrimmage::autonomy::OpenAIObservations Class Reference
#include <OpenAIObservations.h>
Public Member Functions
OpenAIObservations ()
void create_observation_space (size_t num_entities, bool static_obs_space)
pybind11::object update_observation (size_t num_entities, bool static_obs_space)
std::vector< std::vector< std::shared_ptr< sensor::ScrimmageOpenAISensor > > > & ext_sensor_vec ()
void add_sensors (const std::unordered_map< std::string, SensorPtr > &sensors)
void set_global_sensor (bool global_sensor)
bool get_global_sensor () const
void set_combine_actors (bool combine_actors)
bool get_combine_actors () const
Public Attributes
pybind11::object observation_space
pybind11::object observation
Protected Attributes
std::vector< std::vector< std::shared_ptr< sensor::ScrimmageOpenAISensor > > > ext_sensor_vec_
pybind11::object tuple_space_
pybind11::object box_space_
bool combine_actors_ = false
bool global_sensor_ = false
Detailed Description
Definition at line 56 of file OpenAIObservations.h.
Constructor & Destructor Documentation
OpenAIObservations()
scrimmage::autonomy::OpenAIObservations::OpenAIObservations ()
Definition at line 54 of file OpenAIObservations.cpp.
                                        :
     tuple_space_(get_gym_space("Tuple")),
     box_space_(get_gym_space("Box")) {}
Member Function Documentation
create_observation_space()
void scrimmage::autonomy::OpenAIObservations::create_observation_space (size_t num_entities, bool static_obs_space)
Definition at line 144 of file OpenAIObservations.cpp.
{
     auto create_obs = [&](py::list &discrete_count,
                           py::list &continuous_maxima) -> py::object {
         int len_discrete = py::len(discrete_count);
         int len_continuous = py::len(continuous_maxima);
         py::array_t<int> discrete_array(len_discrete);
         py::array_t<double> continuous_array(len_continuous);
         // Return by move to fix this warning from clang: warning: local
         // variable 'obs' will be copied despite being returned by name
         // [-Wreturn-std-move]
         if (len_discrete > 0 && len_continuous > 0) {
             py::list obs;
             obs.append(discrete_array);
             obs.append(continuous_array);
             return std::move(obs);
         } else if (len_continuous > 0) {
             return std::move(continuous_array);
         } else {
             return std::move(discrete_array);
         }
     };
     if (static_obs_space && (num_entities == 1 || combine_actors_)) {
         py::list discrete_count;
         py::list continuous_minima;
         py::list continuous_maxima;
         bool done = false;
         for (auto &v : ext_sensor_vec_) {
             if (done) break;
             for (auto &s : v) {
                 s->set_observation_space();
                 to_discrete(s->observation_space.discrete_count, discrete_count);
                 to_continuous(s->observation_space.continuous_extrema, continuous_minima, continuous_maxima);
                 if (num_entities > 1 && global_sensor_) {
                     done = true;
                     break;
                 }
             }
         }
         observation_space =
             create_space(discrete_count, continuous_minima, continuous_maxima);
         observation = create_obs(discrete_count, continuous_maxima);
     } else {
         py::list observation_spaces;
         py::list obs;
         for (auto &v : ext_sensor_vec_) {
             for (auto &s : v) {
                 py::list discrete_count;
                 py::list continuous_minima;
                 py::list continuous_maxima;
                 s->set_observation_space();
                 to_discrete(s->observation_space.discrete_count, discrete_count);
                 to_continuous(s->observation_space.continuous_extrema, continuous_minima, continuous_maxima);
                 auto space = create_space(discrete_count, continuous_minima,
                                           continuous_maxima);
                 observation_spaces.append(space);
                 obs.append(create_obs(discrete_count, continuous_maxima));
             }
         }
         py::object tuple_space = get_gym_space("Tuple");
         observation_space = tuple_space(observation_spaces);
         observation = obs;
         py::list observation_space_list =
                 observation_space.attr("spaces").cast<py::list>();
     }
 }
References combine_actors_, scrimmage::autonomy::create_space(), ext_sensor_vec_, scrimmage::autonomy::get_gym_space(), global_sensor_, observation, observation_space, scrimmage::autonomy::to_continuous(), and scrimmage::autonomy::to_discrete().
Referenced by scrimmage::autonomy::init_actor_func().
update_observation()
pybind11::object scrimmage::autonomy::OpenAIObservations::update_observation (size_t num_entities, bool static_obs_space)
Definition at line 58 of file OpenAIObservations.cpp.
{
     auto call_get_obs = [&](auto *data, uint32_t &beg_idx, auto sensor, int obs_size) {
         if (sensor->parent() == nullptr) {
             return;
         }
         uint32_t end_idx = beg_idx + obs_size;
         if (end_idx != beg_idx) {
             sensor->get_observation(data, beg_idx, end_idx);
             beg_idx = end_idx;
         }
     };
     auto init_arrays = [&](py::object obs_space, py::object obs) {
         py::array_t<int> disc_obs;
         py::array_t<double> cont_obs;
         if (PyObject_IsInstance(obs_space.ptr(), tuple_space_.ptr())) {
             py::list obs_list = obs.cast<py::list>();
             disc_obs = obs_list[0].cast<py::array_t<int>>();
             cont_obs = obs_list[1].cast<py::array_t<double>>();
         } else if (PyObject_IsInstance(obs_space.ptr(), box_space_.ptr())) {
             cont_obs = obs.cast<py::array_t<double>>();
         } else {
             disc_obs = obs.cast<py::array_t<int>>();
         }
         return std::make_tuple(disc_obs, cont_obs);
     };
     py::array_t<int> disc_obs;
     py::array_t<double> cont_obs;
     if (static_obs_space && (num_entities == 1 || combine_actors_)) {
         std::tie(disc_obs, cont_obs) = init_arrays(observation_space, observation);
         uint32_t disc_beg_idx = 0;
         uint32_t cont_beg_idx = 0;
         int* r_disc = static_cast<int *>(disc_obs.request().ptr);
         double* r_cont = static_cast<double *>(cont_obs.request().ptr);
         bool done = false;
         for (auto &v : ext_sensor_vec_) {
             if (done) break;
             for (auto &s : v) {
                 auto obs_space = s->observation_space;
                 call_get_obs(r_disc, disc_beg_idx, s, obs_space.discrete_count.size());
                 call_get_obs(r_cont, cont_beg_idx, s, obs_space.continuous_extrema.size());
                 if (num_entities > 1 && global_sensor_) {
                     done = true;
                     break;
                 }
             }
         }
     } else {
         py::list observation_space_list =
                 observation_space.attr("spaces").cast<py::list>();
         py::list observation_list = observation.cast<py::list>();
         // Number of entities has shrunk
         while (py::len(observation_list) > ext_sensor_vec_.size()) {
             // Shrink observation_list to the number of sensors
             for (size_t i = py::len(observation_list); i > ext_sensor_vec_.size(); i--) {
                 observation_list.attr("pop")(-1);
             }
         }
         for (size_t i = 0; i < ext_sensor_vec_.size(); i++) {
             py::object indiv_space = observation_space_list[i];
             py::object indiv_obs = observation_list[i];
             std::tie(disc_obs, cont_obs) = init_arrays(indiv_space, indiv_obs);
             uint32_t disc_beg_idx = 0;
             uint32_t cont_beg_idx = 0;
             int* r_disc = static_cast<int *>(disc_obs.request().ptr);
             double* r_cont = static_cast<double *>(cont_obs.request().ptr);
             for (auto &s : ext_sensor_vec_[i]) {
                 auto obs_space = s->observation_space;
                 call_get_obs(r_disc, disc_beg_idx, s, obs_space.discrete_count.size());
                 call_get_obs(r_cont, cont_beg_idx, s, obs_space.continuous_extrema.size());
             }
         }
     }
     return observation;
 }
References box_space_, combine_actors_, ext_sensor_vec_, global_sensor_, observation, observation_space, and tuple_space_.
Referenced by scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy().
ext_sensor_vec()
std::vector<std::vector<std::shared_ptr<sensor::ScrimmageOpenAISensor> > >& scrimmage::autonomy::OpenAIObservations::ext_sensor_vec () inline
Definition at line 65 of file OpenAIObservations.h.
 {return ext_sensor_vec_;}
add_sensors()
void scrimmage::autonomy::OpenAIObservations::add_sensors (const std::unordered_map< std::string, SensorPtr > & sensors)
Definition at line 225 of file OpenAIObservations.cpp.
{
     std::vector<std::shared_ptr<sensor::ScrimmageOpenAISensor>> vec;
     auto cast = [&](auto &p) {return std::dynamic_pointer_cast<sensor::ScrimmageOpenAISensor>(p);};
     auto good_ptr = [&](auto &p) {return cast(p) != nullptr;};
     br::transform(sensors | ba::map_values | ba::filtered(good_ptr), std::back_inserter(vec), cast);
     ext_sensor_vec_.push_back(vec);
 }
References ext_sensor_vec_.
Referenced by scrimmage::autonomy::init_actor_func().
set_global_sensor()
void scrimmage::autonomy::OpenAIObservations::set_global_sensor (bool global_sensor) inline
Definition at line 72 of file OpenAIObservations.h.
 {global_sensor_ = global_sensor;}
Referenced by scrimmage::autonomy::init_actor_func().
get_global_sensor()
bool scrimmage::autonomy::OpenAIObservations::get_global_sensor () const inline
Definition at line 73 of file OpenAIObservations.h.
 {return global_sensor_;}
set_combine_actors()
void scrimmage::autonomy::OpenAIObservations::set_combine_actors (bool combine_actors) inline
Definition at line 75 of file OpenAIObservations.h.
 {combine_actors_ = combine_actors;}
Referenced by scrimmage::autonomy::init_actor_func().
get_combine_actors()
bool scrimmage::autonomy::OpenAIObservations::get_combine_actors () const inline
Definition at line 76 of file OpenAIObservations.h.
 {return combine_actors_;}
Referenced by scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy().
Member Data Documentation
observation_space
pybind11::object scrimmage::autonomy::OpenAIObservations::observation_space
Definition at line 69 of file OpenAIObservations.h.
Referenced by create_observation_space(), and update_observation().
observation
pybind11::object scrimmage::autonomy::OpenAIObservations::observation
Definition at line 70 of file OpenAIObservations.h.
Referenced by create_observation_space(), scrimmage::autonomy::init_actor_func(), scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy(), and update_observation().
ext_sensor_vec_
std::vector<std::vector<std::shared_ptr<sensor::ScrimmageOpenAISensor> > > scrimmage::autonomy::OpenAIObservations::ext_sensor_vec_ protected
Definition at line 80 of file OpenAIObservations.h.
Referenced by add_sensors(), create_observation_space(), and update_observation().
tuple_space_
pybind11::object scrimmage::autonomy::OpenAIObservations::tuple_space_ protected
Definition at line 82 of file OpenAIObservations.h.
Referenced by update_observation().
box_space_
pybind11::object scrimmage::autonomy::OpenAIObservations::box_space_ protected
Definition at line 83 of file OpenAIObservations.h.
Referenced by update_observation().
combine_actors_
bool scrimmage::autonomy::OpenAIObservations::combine_actors_ = false protected
Definition at line 85 of file OpenAIObservations.h.
Referenced by create_observation_space(), and update_observation().
global_sensor_
bool scrimmage::autonomy::OpenAIObservations::global_sensor_ = false protected
Definition at line 86 of file OpenAIObservations.h.
Referenced by create_observation_space(), and update_observation().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIObservations.h
/root/scrimmage/scrimmage/src/plugins/autonomy/ScrimmageOpenAIAutonomy/OpenAIObservations.cpp