SCRIMMAGE: scrimmage::Timer Class Reference
scrimmage::Timer Class Reference
#include <Timer.h>
Public Member Functions
void start_overall_timer ()
boost::posix_time::time_duration elapsed_time ()
void start_loop_timer ()
boost::posix_time::time_duration loop_wait ()
void set_iterate_rate (double iterate_rate)
void set_time_warp (double time_warp)
void update_time_config ()
void inc_warp ()
void dec_warp ()
double time_warp ()
Static Public Member Functions
static uint64_t getnanotime ()
Protected Attributes
double time_warp_ = NAN
boost::posix_time::ptime start_time_
boost::posix_time::ptime actual_time_
boost::posix_time::time_duration actual_elapsed_time_
boost::posix_time::ptime sim_time_
boost::posix_time::time_duration sim_elapsed_time_
boost::posix_time::ptime loop_timer_
boost::posix_time::time_duration iterate_period_
double iterate_rate_
Detailed Description
Definition at line 40 of file Timer.h.
Member Function Documentation
start_overall_timer()
void scrimmage::Timer::start_overall_timer ()
Definition at line 41 of file Timer.cpp.
{
     start_time_ = boost::posix_time::microsec_clock::local_time();
     actual_time_ = start_time_;
     actual_elapsed_time_ = start_time_ - start_time_; // 0
     sim_time_ = start_time_;
     sim_elapsed_time_ = start_time_ - start_time_; // 0
 }
References actual_elapsed_time_, actual_time_, sim_elapsed_time_, sim_time_, and start_time_.
Referenced by scrimmage::SimControl::start_overall_timer().
elapsed_time()
boost::posix_time::time_duration scrimmage::Timer::elapsed_time ()
Definition at line 49 of file Timer.cpp.
{
     return boost::posix_time::microsec_clock::local_time() - start_time_;
 }
References start_time_.
Referenced by scrimmage::SimControl::output_runtime().
start_loop_timer()
void scrimmage::Timer::start_loop_timer ()
Definition at line 53 of file Timer.cpp.
{
     loop_timer_ = boost::posix_time::microsec_clock::local_time();
     boost::posix_time::time_duration time_diff = loop_timer_ - actual_time_;
     actual_time_ = loop_timer_;
     actual_elapsed_time_ += time_diff;
     boost::posix_time::time_duration sim_time_diff = time_diff * time_warp_;
     sim_time_ += sim_time_diff;
     sim_elapsed_time_ += sim_time_diff;
 }
References actual_elapsed_time_, actual_time_, loop_timer_, sim_elapsed_time_, sim_time_, and time_warp_.
Referenced by scrimmage::SimControl::start_loop_timer().
loop_wait()
boost::posix_time::time_duration scrimmage::Timer::loop_wait ()
Definition at line 66 of file Timer.cpp.
{
     boost::posix_time::ptime time = boost::posix_time::microsec_clock::local_time();
     boost::posix_time::time_duration time_diff = time - loop_timer_;
     boost::posix_time::time_duration remainder = iterate_period_ - time_diff;
     if (time_diff < iterate_period_) {
         boost::this_thread::sleep(remainder);
     }
     return remainder;
 }
References iterate_period_, and loop_timer_.
Referenced by scrimmage::SimControl::loop_wait().
set_iterate_rate()
void scrimmage::Timer::set_iterate_rate (double iterate_rate)
Definition at line 77 of file Timer.cpp.
{
     iterate_rate_ = iterate_rate;
 }
References iterate_rate_.
Referenced by scrimmage::SimControl::setup_timer().
set_time_warp()
void scrimmage::Timer::set_time_warp (double time_warp)
Definition at line 81 of file Timer.cpp.
{
     time_warp_ = time_warp;
 }
References time_warp(), and time_warp_.
Referenced by scrimmage::SimControl::setup_timer().
update_time_config()
void scrimmage::Timer::update_time_config ()
Definition at line 85 of file Timer.cpp.
{
     if (iterate_rate_ > 0 && time_warp_ > 0) {
         uint64_t milli = (1.0 / iterate_rate_ * 1000000.0) / time_warp_;
         iterate_period_ = boost::posix_time::time_duration(0, 0, 0, milli);
     } else {
         iterate_period_ = boost::posix_time::time_duration(0, 0, 0, 0);
     }
 }
References iterate_period_, iterate_rate_, and time_warp_.
Referenced by dec_warp(), inc_warp(), and scrimmage::SimControl::setup_timer().
getnanotime()
uint64_t scrimmage::Timer::getnanotime () static
Definition at line 94 of file Timer.cpp.
{
     uint64_t nano = 0;
     timespec ts;
     // clock_gettime(CLOCK_MONOTONIC, &ts); // Works on FreeBSD
     clock_gettime(CLOCK_REALTIME, &ts); // Works on Linux
     nano = ts.tv_sec * 1e9 + ts.tv_nsec;
     return nano;
 }
inc_warp()
void scrimmage::Timer::inc_warp ()
Definition at line 104 of file Timer.cpp.
                      {
     if (time_warp_ == 0) {
         time_warp_ = 1;
     } else if (time_warp_ < 2) {
         time_warp_ *= 2;
     } else {
         time_warp_ += 1.0;
     }
     update_time_config();
 }
References time_warp_, and update_time_config().
Referenced by scrimmage::SimControl::inc_warp().
dec_warp()
void scrimmage::Timer::dec_warp ()
Definition at line 115 of file Timer.cpp.
                      {
     if (time_warp_ == 0) {
         time_warp_ = 1;
     } else if (time_warp_ < 2) {
         time_warp_ /= 2;
     } else {
         time_warp_ -= 1.0;
     }
     update_time_config();
 }
References time_warp_, and update_time_config().
Referenced by scrimmage::SimControl::dec_warp().
time_warp()
double scrimmage::Timer::time_warp ()
Definition at line 126 of file Timer.cpp.
{
     return time_warp_;
 }
References time_warp_.
Referenced by set_time_warp(), and scrimmage::SimControl::time_warp().
Member Data Documentation
time_warp_
double scrimmage::Timer::time_warp_ = NAN protected
Definition at line 65 of file Timer.h.
Referenced by dec_warp(), inc_warp(), set_time_warp(), start_loop_timer(), time_warp(), and update_time_config().
start_time_
boost::posix_time::ptime scrimmage::Timer::start_time_ protected
Definition at line 66 of file Timer.h.
Referenced by elapsed_time(), and start_overall_timer().
actual_time_
boost::posix_time::ptime scrimmage::Timer::actual_time_ protected
Definition at line 68 of file Timer.h.
Referenced by start_loop_timer(), and start_overall_timer().
actual_elapsed_time_
boost::posix_time::time_duration scrimmage::Timer::actual_elapsed_time_ protected
Definition at line 69 of file Timer.h.
Referenced by start_loop_timer(), and start_overall_timer().
sim_time_
boost::posix_time::ptime scrimmage::Timer::sim_time_ protected
Definition at line 71 of file Timer.h.
Referenced by start_loop_timer(), and start_overall_timer().
sim_elapsed_time_
boost::posix_time::time_duration scrimmage::Timer::sim_elapsed_time_ protected
Definition at line 72 of file Timer.h.
Referenced by start_loop_timer(), and start_overall_timer().
loop_timer_
boost::posix_time::ptime scrimmage::Timer::loop_timer_ protected
Definition at line 74 of file Timer.h.
Referenced by loop_wait(), and start_loop_timer().
iterate_period_
boost::posix_time::time_duration scrimmage::Timer::iterate_period_ protected
Definition at line 75 of file Timer.h.
Referenced by loop_wait(), and update_time_config().
iterate_rate_
double scrimmage::Timer::iterate_rate_ protected
Definition at line 76 of file Timer.h.
Referenced by set_iterate_rate(), and update_time_config().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/Timer.h
/root/scrimmage/scrimmage/src/common/Timer.cpp