SCRIMMAGE: scrimmage::autonomy::MOOSAutonomy Class Reference
scrimmage::autonomy::MOOSAutonomy Class Reference
#include <MOOSAutonomy.h>
Public Member Functions
MOOSAutonomy ()
void init (std::map< std::string, std::string > &params) override
bool ready () override
bool step_autonomy (double t, double dt) override
Public Member Functions inherited from scrimmage::Autonomy
Autonomy ()
std::string type () override
virtual bool posthumous (double t)
virtual void init ()
void close (double t) override
bool need_reset ()
StatePtr & desired_state ()
void set_desired_state (StatePtr desired_state)
ContactMapPtr & get_contacts ()
ContactMap & get_contacts_raw ()
virtual void set_contacts (ContactMapPtr &contacts)
virtual void set_contacts_from_plugin (AutonomyPtr &ptr)
virtual void set_projection (std::shared_ptr< GeographicLib::LocalCartesian > &proj)
scrimmage::RTreePtr & rtree ()
void set_rtree (scrimmage::RTreePtr &rtree)
StatePtr & state ()
virtual void set_state (StatePtr &state)
std::string & logging_msg ()
bool get_is_controlling ()
void set_is_controlling (bool is_controlling)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Member Functions
void run_moos_node ()
Protected Attributes
std::thread moos_node_thread_
std::thread ivp_thread_
MOOSNode moos_node_
std::string moos_app_name_
std::string moos_script_
std::string moos_mission_file_
scrimmage::Angles angles_to_moos_
scrimmage::Angles angles_from_moos_
int desired_heading_idx_ = 0
int desired_alt_idx_ = 0
int desired_speed_idx_ = 0
Protected Attributes inherited from scrimmage::Autonomy
std::shared_ptr< GeographicLib::LocalCartesian > proj_
StatePtr state_
StatePtr desired_state_
ContactMapPtr contacts_
scrimmage::RTreePtr rtree_
bool need_reset_
std::string logging_msg_
bool is_controlling_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 47 of file MOOSAutonomy.h.
Constructor & Destructor Documentation
scrimmage::autonomy::MOOSAutonomy::MOOSAutonomy ()
Definition at line 50 of file MOOSAutonomy.cpp.
References scrimmage::Angles::CCW, scrimmage::Angles::CW, scrimmage::Angles::Pos_X, and scrimmage::Angles::Pos_Y.
{
     angles_from_moos_.set_input_clock_direction(ang::Rotate::CW);
     angles_from_moos_.set_input_zero_axis(ang::HeadingZero::Pos_Y);
     angles_from_moos_.set_output_clock_direction(ang::Rotate::CCW);
     angles_from_moos_.set_output_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_moos_.set_input_clock_direction(ang::Rotate::CCW);
     angles_to_moos_.set_input_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_moos_.set_output_clock_direction(ang::Rotate::CW);
     angles_to_moos_.set_output_zero_axis(ang::HeadingZero::Pos_Y);
 }
Member Function Documentation
void scrimmage::autonomy::MOOSAutonomy::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 62 of file MOOSAutonomy.cpp.
References scrimmage::expand_user().
{
     moos_app_name_ = sc::get<std::string>("moos_app_name", params, "scrimmage");
     moos_app_name_ += std::string("_") + std::to_string(parent_->id().id());
     moos_script_ = sc::expand_user(sc::get<std::string>("moos_script", params, "launch.sh"));
     moos_mission_file_ = sc::expand_user(sc::get<std::string>("moos_mission_file", params, "alpha.moos"));
     desired_state_->vel() = Eigen::Vector3d::UnitX()*21;
     desired_state_->quat().set(0, 0, state_->quat().yaw());
     desired_state_->pos() = Eigen::Vector3d::UnitZ()*state_->pos()(2);
     desired_alt_idx_ = vars_.declare(VariableIO::Type::desired_altitude, VariableIO::Direction::Out);
     desired_speed_idx_ = vars_.declare(VariableIO::Type::desired_speed, VariableIO::Direction::Out);
     desired_heading_idx_ = vars_.declare(VariableIO::Type::desired_heading, VariableIO::Direction::Out);
     // Kick off moos node thread
     moos_node_.set_time_warp(parent_->mp()->time_warp());
     moos_node_thread_ = std::thread(&MOOSAutonomy::run_moos_node, this);
 }
bool scrimmage::autonomy::MOOSAutonomy::ready () override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 82 of file MOOSAutonomy.cpp.
{
     return moos_node_.ready();
 }
bool scrimmage::autonomy::MOOSAutonomy::step_autonomy (double t, double dt) override virtual
Reimplemented from scrimmage::Autonomy.
Definition at line 86 of file MOOSAutonomy.cpp.
References scrimmage::Angles::deg2rad(), scrimmage::Quaternion::pitch(), scrimmage::State::pos(), scrimmage::State::quat(), scrimmage::Angles::rad2deg(), scrimmage::Quaternion::roll(), scrimmage::Quaternion::set(), scrimmage::State::vel(), and scrimmage::Quaternion::yaw().
{
     // Provide contact locations:
     for (auto &kv : *contacts_) {
         MOOSNode::NodeReportType type;
         if (parent_->id().id() == kv.first) {
             type = MOOSNode::OWNSHIP;
         } else {
             type = MOOSNode::TRUTH_CONTACT;
         }
         // Convert heading to local cartesian
         sc::StatePtr &s = kv.second.state();
         angles_to_moos_.set_angle(ang::rad2deg(s->quat().yaw()));
         double heading = angles_to_moos_.angle();
         moos_node_.PublishNodeReport(type,
                                      std::to_string(kv.first), "",
                                      s->pos()(0), s->pos()(1),
                                      s->vel().norm(), heading,
                                      -s->pos()(2), "kayak", "none",
                                      t, "0");
     }
     // Get desired state from moos
     sc::State s = moos_node_.desired_state();
     // Convert heading to local cartesian
     angles_from_moos_.set_angle(ang::rad2deg(s.quat().yaw()));
     s.quat().set(s.quat().roll(), s.quat().pitch(),
                  ang::deg2rad(angles_from_moos_.angle()));
     desired_state_->vel() = s.vel();
     desired_state_->quat() = s.quat();
     desired_state_->pos() = s.pos();
     // Set the VariableIO output for controller
     vars_.output(desired_alt_idx_, desired_state_->pos()(2));
     vars_.output(desired_speed_idx_, desired_state_->vel()(0));
     vars_.output(desired_heading_idx_, desired_state_->quat().yaw());
     return true;
 }
void scrimmage::autonomy::MOOSAutonomy::run_moos_node () protected
Definition at line 130 of file MOOSAutonomy.cpp.
{
     moos_node_.Run(moos_app_name_.c_str(), moos_mission_file_.c_str());
 }
Member Data Documentation
std::thread scrimmage::autonomy::MOOSAutonomy::moos_node_thread_ protected
Definition at line 57 of file MOOSAutonomy.h.
std::thread scrimmage::autonomy::MOOSAutonomy::ivp_thread_ protected
Definition at line 58 of file MOOSAutonomy.h.
MOOSNode scrimmage::autonomy::MOOSAutonomy::moos_node_ protected
Definition at line 59 of file MOOSAutonomy.h.
std::string scrimmage::autonomy::MOOSAutonomy::moos_app_name_ protected
Definition at line 61 of file MOOSAutonomy.h.
std::string scrimmage::autonomy::MOOSAutonomy::moos_script_ protected
Definition at line 62 of file MOOSAutonomy.h.
std::string scrimmage::autonomy::MOOSAutonomy::moos_mission_file_ protected
Definition at line 63 of file MOOSAutonomy.h.
scrimmage::Angles scrimmage::autonomy::MOOSAutonomy::angles_to_moos_ protected
Definition at line 65 of file MOOSAutonomy.h.
scrimmage::Angles scrimmage::autonomy::MOOSAutonomy::angles_from_moos_ protected
Definition at line 66 of file MOOSAutonomy.h.
int scrimmage::autonomy::MOOSAutonomy::desired_heading_idx_ = 0 protected
Definition at line 68 of file MOOSAutonomy.h.
int scrimmage::autonomy::MOOSAutonomy::desired_alt_idx_ = 0 protected
Definition at line 69 of file MOOSAutonomy.h.
int scrimmage::autonomy::MOOSAutonomy::desired_speed_idx_ = 0 protected
Definition at line 70 of file MOOSAutonomy.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/MOOSAutonomy/MOOSAutonomy.h
/root/scrimmage/scrimmage/src/plugins/autonomy/MOOSAutonomy/MOOSAutonomy.cpp