SCRIMMAGE: scrimmage::motion::PwmState Class Reference
scrimmage::motion::PwmState Class Reference
#include <PwmState.h>
Public Member Functions
void set_pwm_input (Eigen::VectorXd pwm_input)
Eigen::VectorXd & pwm_input ()
void set_pwm_min (double pwm_min)
void set_pwm_max (double pwm_max)
double & pwm_min ()
double & pwm_max ()
Public Member Functions inherited from scrimmage::State
State ()
State (Eigen::Vector3d _pos, Eigen::Vector3d _vel, Eigen::Vector3d _ang_vel, Quaternion _quat)
virtual ~State ()
Eigen::Vector3d & pos ()
Eigen::Vector3d & vel ()
Eigen::Vector3d & ang_vel ()
const Eigen::Vector3d & pos () const
const Eigen::Vector3d & vel () const
const Eigen::Vector3d & ang_vel () const
Quaternion & quat ()
const Quaternion & quat () const
const Eigen::Vector3d & pos_const () const
const Eigen::Vector3d & vel_const () const
const Eigen::Vector3d & ang_vel_const () const
const Quaternion & quat_const () const
void set_pos (const Eigen::Vector3d &pos)
void set_vel (const Eigen::Vector3d &vel)
void set_ang_vel (const Eigen::Vector3d &ang_vel)
void set_quat (const Quaternion &quat)
bool InFieldOfView (State &other, double fov_width, double fov_height) const
Returns true if other state is in field-of-view.
Eigen::Vector3d rel_pos_local_frame (Eigen::Vector3d &other) const
convert the relative position to the local frame (the output vector will point to the other state)
Eigen::Vector3d pos_offset (double distance, bool offset_with_velocity=true) const
return position offset by trailing_distance in the direction of velocity or orientation
Eigen::Vector3d orient_global_frame () const
returns the vector extending forward
double rel_az (const Eigen::Vector3d &other) const
Eigen::Matrix4d tf_matrix (bool enable_translate=true)
Protected Attributes
Eigen::VectorXd pwm_input_
double pwm_min_ = 1000
double pwm_max_ = 2000
Protected Attributes inherited from scrimmage::State
Eigen::Vector3d pos_
Eigen::Vector3d vel_
Eigen::Vector3d ang_vel_
Quaternion quat_
Additional Inherited Members
Static Public Member Functions inherited from scrimmage::State
template<class T , class = std::enable_if_t< !std::is_same<T, scrimmage::State>::value && std::is_base_of<scrimmage::State, T>::value, void>>
static std::shared_ptr< T > cast (std::shared_ptr< scrimmage::State > state)
Downcast a scrimmage::State to a subclassed type, returing nullptr if not successful.
Public Attributes inherited from scrimmage::State
uint8_t output_precision = 2
Detailed Description
Definition at line 45 of file PwmState.h.
Member Function Documentation
set_pwm_input()
void scrimmage::motion::PwmState::set_pwm_input (Eigen::VectorXd pwm_input) inline
Definition at line 47 of file PwmState.h.
{
         pwm_input_ = pwm_input;
     }
References pwm_input(), and pwm_input_.
pwm_input()
Eigen::VectorXd& scrimmage::motion::PwmState::pwm_input () inline
Definition at line 51 of file PwmState.h.
{
         return pwm_input_;
     }
References pwm_input_.
Referenced by set_pwm_input().
set_pwm_min()
void scrimmage::motion::PwmState::set_pwm_min (double pwm_min) inline
Definition at line 55 of file PwmState.h.
{
         pwm_min_ = pwm_min;
     }
References pwm_min(), and pwm_min_.
set_pwm_max()
void scrimmage::motion::PwmState::set_pwm_max (double pwm_max) inline
Definition at line 58 of file PwmState.h.
{
         pwm_max_ = pwm_max;
     }
References pwm_max(), and pwm_max_.
pwm_min()
double& scrimmage::motion::PwmState::pwm_min () inline
Definition at line 61 of file PwmState.h.
                       {
         return pwm_min_;
     }
References pwm_min_.
Referenced by set_pwm_min().
pwm_max()
double& scrimmage::motion::PwmState::pwm_max () inline
Definition at line 64 of file PwmState.h.
                       {
         return pwm_max_;
     }
References pwm_max_.
Referenced by set_pwm_max().
Member Data Documentation
pwm_input_
Eigen::VectorXd scrimmage::motion::PwmState::pwm_input_ protected
Definition at line 69 of file PwmState.h.
Referenced by pwm_input(), and set_pwm_input().
pwm_min_
double scrimmage::motion::PwmState::pwm_min_ = 1000 protected
Definition at line 70 of file PwmState.h.
Referenced by pwm_min(), and set_pwm_min().
pwm_max_
double scrimmage::motion::PwmState::pwm_max_ = 2000 protected
Definition at line 71 of file PwmState.h.
Referenced by pwm_max(), and set_pwm_max().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/ArduPilot/PwmState.h