SCRIMMAGE: scrimmage::Interface Class Reference
scrimmage::Interface Class Reference
#include <Interface.h>
Public Types
enum Mode { shared = 0, client = 1, server = 2 }
typedef enum scrimmage::Interface::Mode Mode_t
Public Member Functions
void set_mode (Mode_t mode)
void set_ip (std::string &ip)
void set_port (int port)
bool init_network (Mode_t mode, const std::string &ip, int port)
bool frames_update (double t)
bool utm_terrain_update ()
bool contact_visual_update ()
bool gui_msg_update ()
bool world_point_clicked_msg_update ()
bool sim_info_update ()
bool shapes_update ()
bool send_frame (double time, ContactMapPtr &contacts)
bool send_frame (std::shared_ptr< scrimmage_proto::Frame > &frame)
bool send_utm_terrain (std::shared_ptr< scrimmage_proto::UTMTerrain > &utm_terrain)
bool send_contact_visual (std::shared_ptr< scrimmage_proto::ContactVisual > &cv)
bool push_frame (std::shared_ptr< scrimmage_proto::Frame > &frame)
bool push_utm_terrain (std::shared_ptr< scrimmage_proto::UTMTerrain > &utm_terrain)
bool push_contact_visual (std::shared_ptr< scrimmage_proto::ContactVisual > &cv)
bool send_gui_msg (scrimmage_proto::GUIMsg &gui_msg)
bool push_gui_msg (scrimmage_proto::GUIMsg &gui_msg)
bool send_world_point_clicked_msg (scrimmage_proto::WorldPointClicked &msg)
bool push_world_point_clicked_msg (scrimmage_proto::WorldPointClicked &msg)
bool send_sim_info (scrimmage_proto::SimInfo &sim_info)
bool push_sim_info (scrimmage_proto::SimInfo &sim_info)
bool send_shapes (scrimmage_proto::Shapes &shapes)
bool push_shapes (scrimmage_proto::Shapes &shapes)
std::list< std::shared_ptr< scrimmage_proto::Frame > > & frames ()
std::list< std::shared_ptr< scrimmage_proto::UTMTerrain > > & utm_terrain ()
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > & contact_visual ()
std::list< scrimmage_proto::GUIMsg > & gui_msg ()
std::list< scrimmage_proto::WorldPointClicked > & world_point_clicked_msg ()
std::list< scrimmage_proto::SimInfo > & sim_info ()
std::list< scrimmage_proto::Shapes > & shapes ()
void send_cached ()
bool check_ready ()
Public Attributes
std::mutex frames_mutex
std::mutex utm_terrain_mutex
std::mutex gui_msg_mutex
std::mutex world_point_clicked_msg_mutex
std::mutex sim_info_mutex
std::mutex shapes_mutex
std::mutex contact_visual_mutex
Protected Member Functions
void start_server ()
Protected Attributes
Mode_t mode_ = shared
int port_ = 50051
std::string ip_
std::list< std::shared_ptr< scrimmage_proto::Frame > > frames_list_
std::list< std::shared_ptr< scrimmage_proto::UTMTerrain > > utm_terrain_list_
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > contact_visual_list_
std::list< scrimmage_proto::GUIMsg > gui_msg_list_
std::list< scrimmage_proto::WorldPointClicked > world_point_clicked_msg_list_
std::list< scrimmage_proto::SimInfo > sim_info_list_
std::list< scrimmage_proto::Shapes > shapes_list_
unsigned int max_queue_size_ = 100
unsigned int client_timeout_ = 1
bool caching_enabled_ = true
std::shared_ptr< scrimmage_proto::UTMTerrain > utm_terrain_cache_
std::list< std::shared_ptr< scrimmage_proto::ContactVisual > > contact_visual_cache_
Detailed Description
Definition at line 54 of file Interface.h.
Member Typedef Documentation
typedef enum scrimmage::Interface::Mode scrimmage::Interface::Mode_t
Member Enumeration Documentation
enum scrimmage::Interface::Mode
Enumerator
shared
client
server
Definition at line 56 of file Interface.h.
                       {
         shared = 0,
         client = 1,
         server = 2
     } Mode_t;
Member Function Documentation
void scrimmage::Interface::set_mode (Mode_t mode) inline
Definition at line 62 of file Interface.h.
References mode_.
 { mode_ = mode; }
void scrimmage::Interface::set_ip (std::string & ip) inline
Definition at line 63 of file Interface.h.
References ip_.
 { ip_ = ip; }
void scrimmage::Interface::set_port (int port) inline
Definition at line 64 of file Interface.h.
References contact_visual_update(), frames_update(), gui_msg(), gui_msg_update(), init_network(), port_, push_contact_visual(), push_frame(), push_gui_msg(), push_shapes(), push_sim_info(), push_utm_terrain(), push_world_point_clicked_msg(), send_contact_visual(), send_frame(), send_gui_msg(), send_shapes(), send_sim_info(), send_utm_terrain(), send_world_point_clicked_msg(), shapes(), shapes_update(), sim_info(), sim_info_update(), utm_terrain(), utm_terrain_update(), and world_point_clicked_msg_update().
 { port_ = port; }
bool scrimmage::Interface::init_network (Interface::Mode_t mode, const std::string & ip, int port)
Definition at line 62 of file Interface.cpp.
References client, ip_, mode_, port_, server, and start_server().
Referenced by scrimmage::Viewer::run(), set_port(), and scrimmage::SimControl::start().
{
     mode_ = mode;
     ip_ = ip;
     port_ = port;
     if (mode_ == server) {
 #if ENABLE_GRPC == 1
         std::string result = ip_ + ":" + std::to_string(port_);
         ScrimmageServiceImpl frame_service(this);
         grpc::ServerBuilder builder;
         builder.AddListeningPort(result, grpc::InsecureServerCredentials());
         builder.RegisterService(&frame_service);
         server_ = builder.BuildAndStart();
         std::cout << "Server listening on " << result << std::endl;
         // start thread with shutdown option
         // https://stackoverflow.com/a/36182429
         auto serving_thread = std::thread(&Interface::start_server, this);
         auto future = frame_service.exit_requested.get_future();
         future.wait();
         server_->Shutdown();
         serving_thread.join();
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         std::string result = ip_ + ":" + std::to_string(port_);
         std::shared_ptr<Channel> channel(
             grpc::CreateChannel(result, grpc::InsecureChannelCredentials())
         );
         std::unique_ptr<scrimmage_proto::ScrimmageService::Stub> frame_temp(scrimmage_proto::ScrimmageService::NewStub(channel));
         scrimmage_stub_ = std::move(frame_temp);
         cout << "Client connecting to " << result << endl;
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::frames_update (double t)
Definition at line 453 of file Interface.cpp.
References frames_list_, and frames_mutex.
Referenced by set_port().
{
     frames_mutex.lock();
     bool status = !frames_list_.empty();
     frames_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::utm_terrain_update ()
Definition at line 460 of file Interface.cpp.
References utm_terrain_list_, and utm_terrain_mutex.
Referenced by set_port().
{
     utm_terrain_mutex.lock();
     bool status = !utm_terrain_list_.empty();
     utm_terrain_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::contact_visual_update ()
Definition at line 467 of file Interface.cpp.
References contact_visual_list_, and contact_visual_mutex.
Referenced by set_port().
{
     contact_visual_mutex.lock();
     bool status = !contact_visual_list_.empty();
     contact_visual_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::gui_msg_update ()
Definition at line 474 of file Interface.cpp.
References gui_msg_list_, and gui_msg_mutex.
Referenced by set_port().
{
     gui_msg_mutex.lock();
     bool status = !gui_msg_list_.empty();
     gui_msg_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::world_point_clicked_msg_update ()
Definition at line 481 of file Interface.cpp.
References world_point_clicked_msg_list_, and world_point_clicked_msg_mutex.
Referenced by set_port().
{
     world_point_clicked_msg_mutex.lock();
     bool status = !world_point_clicked_msg_list_.empty();
     world_point_clicked_msg_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::sim_info_update ()
Definition at line 488 of file Interface.cpp.
References sim_info_list_, and sim_info_mutex.
Referenced by set_port().
{
     sim_info_mutex.lock();
     bool status = !sim_info_list_.empty();
     sim_info_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::shapes_update ()
Definition at line 495 of file Interface.cpp.
References shapes_list_, and shapes_mutex.
Referenced by set_port().
{
     shapes_mutex.lock();
     bool status = !shapes_list_.empty();
     shapes_mutex.unlock();
     return status;
 }
bool scrimmage::Interface::send_frame (double time, ContactMapPtr & contacts)
Referenced by send_frame(), and set_port().
bool scrimmage::Interface::send_frame (std::shared_ptr< scrimmage_proto::Frame > & frame)
Definition at line 129 of file Interface.cpp.
References client, client_timeout_, scrimmage::create_frame(), mode_, push_frame(), send_frame(), and shared.
{
     if (mode_ == shared) {
         push_frame(frame);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendFrame(&context, *frame, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_frame: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::send_utm_terrain (std::shared_ptr< scrimmage_proto::UTMTerrain > & utm_terrain)
Definition at line 170 of file Interface.cpp.
References caching_enabled_, client, client_timeout_, mode_, push_utm_terrain(), shared, utm_terrain(), and utm_terrain_cache_.
Referenced by send_cached(), and set_port().
{
     if (caching_enabled_) {
         utm_terrain_cache_ = utm_terrain;
     }
     if (mode_ == shared) {
         push_utm_terrain(utm_terrain);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendUTMTerrain(&context, *utm_terrain, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_utm_terrain: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::send_contact_visual (std::shared_ptr< scrimmage_proto::ContactVisual > & cv)
Definition at line 207 of file Interface.cpp.
References caching_enabled_, client, client_timeout_, contact_visual_cache_, mode_, push_contact_visual(), and shared.
Referenced by send_cached(), and set_port().
{
     if (caching_enabled_) {
         contact_visual_cache_.push_back(cv);
     }
     if (mode_ == shared) {
         push_contact_visual(cv);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendContactVisual(&context, *cv, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_contact_visual: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::push_frame (std::shared_ptr< scrimmage_proto::Frame > & frame)
Definition at line 401 of file Interface.cpp.
References frames_list_, frames_mutex, and max_queue_size_.
Referenced by send_frame(), and set_port().
{
     frames_mutex.lock();
     frames_list_.push_back(frame);
     if (frames_list_.size() > max_queue_size_) {
         frames_list_.pop_front();
     }
     frames_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::push_utm_terrain (std::shared_ptr< scrimmage_proto::UTMTerrain > & utm_terrain)
Definition at line 411 of file Interface.cpp.
References utm_terrain_list_, and utm_terrain_mutex.
Referenced by send_utm_terrain(), and set_port().
{
     utm_terrain_mutex.lock();
     utm_terrain_list_.push_back(utm_terrain);
     utm_terrain_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::push_contact_visual (std::shared_ptr< scrimmage_proto::ContactVisual > & cv)
Definition at line 394 of file Interface.cpp.
References contact_visual_list_, and contact_visual_mutex.
Referenced by send_contact_visual(), and set_port().
{
     contact_visual_mutex.lock();
     contact_visual_list_.push_back(cv);
     contact_visual_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::send_gui_msg (scrimmage_proto::GUIMsg & gui_msg)
Definition at line 244 of file Interface.cpp.
References client, client_timeout_, mode_, push_gui_msg(), and shared.
Referenced by set_port().
{
     if (mode_ == shared) {
         push_gui_msg(gui_msg);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendGUIMsg(&context, gui_msg, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_gui_msg: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::push_gui_msg (scrimmage_proto::GUIMsg & gui_msg)
Definition at line 418 of file Interface.cpp.
References gui_msg_list_, and gui_msg_mutex.
Referenced by send_gui_msg(), and set_port().
{
     gui_msg_mutex.lock();
     gui_msg_list_.push_back(gui_msg);
     gui_msg_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::send_world_point_clicked_msg (scrimmage_proto::WorldPointClicked & msg)
Definition at line 277 of file Interface.cpp.
References client, client_timeout_, mode_, push_world_point_clicked_msg(), and shared.
Referenced by set_port().
{
     if (mode_ == shared) {
         push_world_point_clicked_msg(msg);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendWorldPointClicked(&context, msg, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_world_point_clicked_msg: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::push_world_point_clicked_msg (scrimmage_proto::WorldPointClicked & msg)
Definition at line 425 of file Interface.cpp.
References world_point_clicked_msg_list_, and world_point_clicked_msg_mutex.
Referenced by send_world_point_clicked_msg(), and set_port().
{
     world_point_clicked_msg_mutex.lock();
     world_point_clicked_msg_list_.push_back(msg);
     world_point_clicked_msg_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::send_sim_info (scrimmage_proto::SimInfo & sim_info)
Definition at line 311 of file Interface.cpp.
References client, client_timeout_, mode_, push_sim_info(), and shared.
Referenced by set_port().
{
     if (mode_ == shared) {
         push_sim_info(sim_info);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendSimInfo(&context, sim_info, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_sim_info: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::push_sim_info (scrimmage_proto::SimInfo & sim_info)
Definition at line 432 of file Interface.cpp.
References max_queue_size_, sim_info_list_, and sim_info_mutex.
Referenced by send_sim_info(), and set_port().
{
     sim_info_mutex.lock();
     sim_info_list_.push_back(sim_info);
     if (sim_info_list_.size() > max_queue_size_) {
         sim_info_list_.pop_front();
     }
     sim_info_mutex.unlock();
     return true;
 }
bool scrimmage::Interface::send_shapes (scrimmage_proto::Shapes & shapes)
Definition at line 344 of file Interface.cpp.
References client, client_timeout_, mode_, push_shapes(), and shared.
Referenced by set_port().
{
     if (mode_ == shared) {
         push_shapes(shapes);
     } else if (mode_ == client) {
 #if ENABLE_GRPC
         scrimmage_proto::BlankReply reply;
         // Context for the client. It could be used to convey extra information to
         // the server and/or tweak certain RPC behaviors.
         grpc::ClientContext context;
         // Set timeout for API
         std::chrono::system_clock::time_point deadline =
             std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
         context.set_deadline(deadline);
         grpc::Status status;
         status = scrimmage_stub_->SendShapes(&context, shapes, &reply);
         if (status.ok()) {
             return true;
         } else {
             cout << "send_shapes: Error code: " << status.error_code() << endl;
             cout << status.error_message() << endl;
             return false;
         }
 #else
         cout << "WARNING: GRPC DISABLED!" << endl;
 #endif
     }
     return true;
 }
bool scrimmage::Interface::push_shapes (scrimmage_proto::Shapes & shapes)
Definition at line 442 of file Interface.cpp.
References max_queue_size_, shapes_list_, and shapes_mutex.
Referenced by send_shapes(), and set_port().
{
     shapes_mutex.lock();
     shapes_list_.push_back(shapes);
     if (shapes_list_.size() > max_queue_size_) {
         shapes_list_.pop_front();
     }
     shapes_mutex.unlock();
     return true;
 }
std::list<std::shared_ptr<scrimmage_proto::Frame> >& scrimmage::Interface::frames () inline
Definition at line 107 of file Interface.h.
References frames_list_.
     { return frames_list_; }
std::list<std::shared_ptr<scrimmage_proto::UTMTerrain> >& scrimmage::Interface::utm_terrain () inline
Definition at line 110 of file Interface.h.
References utm_terrain_list_.
Referenced by send_utm_terrain(), and set_port().
     { return utm_terrain_list_; }
std::list<std::shared_ptr<scrimmage_proto::ContactVisual> >& scrimmage::Interface::contact_visual () inline
Definition at line 113 of file Interface.h.
References contact_visual_list_.
     { return contact_visual_list_; }
std::list<scrimmage_proto::GUIMsg>& scrimmage::Interface::gui_msg () inline
Definition at line 116 of file Interface.h.
References gui_msg_list_.
Referenced by set_port().
     { return gui_msg_list_; }
std::list<scrimmage_proto::WorldPointClicked>& scrimmage::Interface::world_point_clicked_msg () inline
Definition at line 119 of file Interface.h.
References world_point_clicked_msg_list_.
     { return world_point_clicked_msg_list_; }
std::list<scrimmage_proto::SimInfo>& scrimmage::Interface::sim_info () inline
Definition at line 122 of file Interface.h.
References sim_info_list_.
Referenced by set_port().
     { return sim_info_list_; }
std::list<scrimmage_proto::Shapes>& scrimmage::Interface::shapes () inline
Definition at line 125 of file Interface.h.
References check_ready(), send_cached(), shapes_list_, and start_server().
Referenced by set_port().
     { return shapes_list_; }
void scrimmage::Interface::send_cached ()
Definition at line 377 of file Interface.cpp.
References caching_enabled_, contact_visual_cache_, send_contact_visual(), send_utm_terrain(), and utm_terrain_cache_.
Referenced by shapes().
{
     // Disable caching during retransmission, so we don't double save
     // cached data
     caching_enabled_ = false;
     // Resend terrain data...
     send_utm_terrain(utm_terrain_cache_);
     // Resend contact visual data...
     for (auto cv : contact_visual_cache_) {
         send_contact_visual(cv);
     }
     // Back to normal caching mode
     caching_enabled_ = true;
 }
bool scrimmage::Interface::check_ready ()
Definition at line 103 of file Interface.cpp.
References client_timeout_, ip_, mode_, port_, server, and shared.
Referenced by shapes().
{
 #if ENABLE_GRPC == 1
     if (mode_ == server || mode_ == shared) return true;
     grpc::ClientContext context;
     std::chrono::system_clock::time_point deadline =
         std::chrono::system_clock::now() + std::chrono::seconds(client_timeout_);
     context.set_deadline(deadline);
     // recreate the channel because using the cached version will keep
     // the non-connection
     std::string result = ip_ + ":" + std::to_string(port_);
     std::shared_ptr<Channel> channel(
         grpc::CreateChannel(result, grpc::InsecureChannelCredentials())
     );
     std::unique_ptr<scrimmage_proto::ScrimmageService::Stub> stub(scrimmage_proto::ScrimmageService::NewStub(channel));
     google::protobuf::Empty req;
     scrimmage_proto::BlankReply reply;
     grpc::Status status = stub->Ready(&context, req, &reply);
     return status.ok();
 #else
     return true;
 #endif
 }
void scrimmage::Interface::start_server () protected
Referenced by init_network(), and shapes().
Member Data Documentation
std::mutex scrimmage::Interface::frames_mutex
Definition at line 99 of file Interface.h.
Referenced by frames_update(), and push_frame().
std::mutex scrimmage::Interface::utm_terrain_mutex
Definition at line 100 of file Interface.h.
Referenced by push_utm_terrain(), and utm_terrain_update().
std::mutex scrimmage::Interface::gui_msg_mutex
Definition at line 101 of file Interface.h.
Referenced by gui_msg_update(), and push_gui_msg().
std::mutex scrimmage::Interface::world_point_clicked_msg_mutex
Definition at line 102 of file Interface.h.
Referenced by push_world_point_clicked_msg(), and world_point_clicked_msg_update().
std::mutex scrimmage::Interface::sim_info_mutex
Definition at line 103 of file Interface.h.
Referenced by push_sim_info(), and sim_info_update().
std::mutex scrimmage::Interface::shapes_mutex
Definition at line 104 of file Interface.h.
Referenced by push_shapes(), and shapes_update().
std::mutex scrimmage::Interface::contact_visual_mutex
Definition at line 105 of file Interface.h.
Referenced by contact_visual_update(), and push_contact_visual().
Mode_t scrimmage::Interface::mode_ = shared protected
Definition at line 134 of file Interface.h.
Referenced by check_ready(), init_network(), send_contact_visual(), send_frame(), send_gui_msg(), send_shapes(), send_sim_info(), send_utm_terrain(), send_world_point_clicked_msg(), and set_mode().
int scrimmage::Interface::port_ = 50051 protected
Definition at line 135 of file Interface.h.
Referenced by check_ready(), init_network(), and set_port().
std::string scrimmage::Interface::ip_ protected
Definition at line 136 of file Interface.h.
Referenced by check_ready(), init_network(), and set_ip().
std::list<std::shared_ptr<scrimmage_proto::Frame> > scrimmage::Interface::frames_list_ protected
Definition at line 138 of file Interface.h.
Referenced by frames(), frames_update(), and push_frame().
std::list<std::shared_ptr<scrimmage_proto::UTMTerrain> > scrimmage::Interface::utm_terrain_list_ protected
Definition at line 139 of file Interface.h.
Referenced by push_utm_terrain(), utm_terrain(), and utm_terrain_update().
std::list<std::shared_ptr<scrimmage_proto::ContactVisual> > scrimmage::Interface::contact_visual_list_ protected
Definition at line 140 of file Interface.h.
Referenced by contact_visual(), contact_visual_update(), and push_contact_visual().
std::list<scrimmage_proto::GUIMsg> scrimmage::Interface::gui_msg_list_ protected
Definition at line 142 of file Interface.h.
Referenced by gui_msg(), gui_msg_update(), and push_gui_msg().
std::list<scrimmage_proto::WorldPointClicked> scrimmage::Interface::world_point_clicked_msg_list_ protected
Definition at line 143 of file Interface.h.
Referenced by push_world_point_clicked_msg(), world_point_clicked_msg(), and world_point_clicked_msg_update().
std::list<scrimmage_proto::SimInfo> scrimmage::Interface::sim_info_list_ protected
Definition at line 144 of file Interface.h.
Referenced by push_sim_info(), sim_info(), and sim_info_update().
std::list<scrimmage_proto::Shapes> scrimmage::Interface::shapes_list_ protected
Definition at line 145 of file Interface.h.
Referenced by push_shapes(), shapes(), and shapes_update().
unsigned int scrimmage::Interface::max_queue_size_ = 100 protected
Definition at line 147 of file Interface.h.
Referenced by push_frame(), push_shapes(), and push_sim_info().
unsigned int scrimmage::Interface::client_timeout_ = 1 protected
Definition at line 155 of file Interface.h.
Referenced by check_ready(), send_contact_visual(), send_frame(), send_gui_msg(), send_shapes(), send_sim_info(), send_utm_terrain(), and send_world_point_clicked_msg().
bool scrimmage::Interface::caching_enabled_ = true protected
Definition at line 158 of file Interface.h.
Referenced by send_cached(), send_contact_visual(), and send_utm_terrain().
std::shared_ptr<scrimmage_proto::UTMTerrain> scrimmage::Interface::utm_terrain_cache_ protected
Definition at line 159 of file Interface.h.
Referenced by send_cached(), and send_utm_terrain().
std::list<std::shared_ptr<scrimmage_proto::ContactVisual> > scrimmage::Interface::contact_visual_cache_ protected
Definition at line 160 of file Interface.h.
Referenced by send_cached(), and send_contact_visual().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/network/Interface.h
/root/scrimmage/scrimmage/src/network/Interface.cpp