SCRIMMAGE: scrimmage::ConfigParse Class Reference
scrimmage::ConfigParse Class Reference
#include <ConfigParse.h>
Public Member Functions
ConfigParse ()
void set_required (std::string node_name)
bool parse (const std::map< std::string, std::string > &overrides, std::string filename, std::string env_var, FileSearch &file_search, bool verbose=false)
std::map< std::string, std::string > & params ()
std::string filename ()
std::string directory ()
std::string extension ()
std::string stem ()
void print_params ()
Protected Member Functions
void recursive_params (rapidxml::xml_node< char > *root, const std::map< std::string, std::string > &overrides, std::map< std::string, std::string > &params, const std::string &prev)
Protected Attributes
std::map< std::string, std::string > params_
std::vector< std::string > required_
std::string filename_
Friends
std::ostream & operator<< (std::ostream &os, ConfigParse &cp)
Detailed Description
Definition at line 48 of file ConfigParse.h.
Constructor & Destructor Documentation
ConfigParse()
scrimmage::ConfigParse::ConfigParse ()
Definition at line 57 of file ConfigParse.cpp.
 {}
Member Function Documentation
set_required()
void scrimmage::ConfigParse::set_required (std::string node_name)
Definition at line 59 of file ConfigParse.cpp.
{
     required_.push_back(node_name);
 }
References required_.
Referenced by scrimmage::find_model_properties(), scrimmage::find_terrain_files(), scrimmage::interaction::MapGen2D::init(), and scrimmage::PluginManager::make_plugin().
parse()
bool scrimmage::ConfigParse::parse (const std::map< std::string, std::string > & overrides, std::string filename, std::string env_var, FileSearch & file_search, bool verbose = false)
Definition at line 105 of file ConfigParse.cpp.
{
     std::string result = "";
     bool status = file_search.find_file(filename, "xml", env_var, result, verbose);
     if (!status) {
         if (boost::algorithm::to_lower_copy(filename) != "sphere") {
             // sphere does not have a filename so we do not
             // need a warning message for this
             cout << "Failed to find configuration: " << filename << endl;
         }
         return false;
     } else if (verbose) {
         cout << "ConfigParse: found " << result << std::endl;
     }
     filename_ = result;
     rx::xml_document<> doc;
     std::ifstream file(filename_.c_str());
     std::stringstream buffer;
     buffer << file.rdbuf();
     file.close();
     std::string content(buffer.str());
     doc.parse<0>(&content[0]);
     rx::xml_node<> *config_node = doc.first_node("params");
     if (config_node == 0) {
         cout << "Missing tag: params" << endl;
         return false;
     }
     params_.clear();
     params_["XML_DIR"] = this->directory() + "/";
     params_["XML_FILENAME"] = filename_;
     recursive_params(config_node->first_node(), overrides, params_, "");
     // Determine if there were any overrides (XML attributes) specified in the
     // mission file that weren't declared in the Plugin's XML
     // file. Automatically add these overrides to the params block.
     for (auto &kv : overrides) {
         if (params_.count(kv.first) == 0) {
             params_[kv.first] = kv.second;
         }
     }
     for (std::string &node_name : required_) {
         if (params_.count(node_name) == 0) {
             cout << "Config file is missing XML tag: " << node_name << endl;
             return false;
         }
     }
     return true;
 }
References directory(), filename(), filename_, scrimmage::FileSearch::find_file(), params_, recursive_params(), and required_.
Referenced by scrimmage::Updater::draw_plane(), scrimmage::find_model_properties(), scrimmage::find_terrain_files(), scrimmage::Updater::get_model_texture(), scrimmage::interaction::MapGen2D::init(), scrimmage::PluginManager::make_plugin(), and scrimmage::parse_autonomy_data().
params()
std::map< std::string, std::string > & scrimmage::ConfigParse::params ()
Definition at line 161 of file ConfigParse.cpp.
 { return params_; }
References params_.
Referenced by scrimmage::create_ent_inters(), scrimmage::create_metrics(), scrimmage::create_networks(), scrimmage::Updater::draw_plane(), scrimmage::find_model_properties(), scrimmage::find_terrain_files(), scrimmage::Updater::get_model_texture(), scrimmage::interaction::MapGen2D::init(), scrimmage::PluginManager::make_plugin(), scrimmage::operator<<(), scrimmage::parse_autonomy_data(), scrimmage::MissionParse::parse_terrain(), recursive_params(), and REGISTER_PLUGIN().
filename()
std::string scrimmage::ConfigParse::filename ()
Definition at line 163 of file ConfigParse.cpp.
 { return filename_; }
References filename_.
Referenced by parse().
directory()
std::string scrimmage::ConfigParse::directory ()
Definition at line 165 of file ConfigParse.cpp.
{
     if (fs::exists(filename_)) {
         return fs::path(filename_).parent_path().string();
     }
     return "";
 }
References filename_.
Referenced by scrimmage::Updater::draw_plane(), scrimmage::find_model_properties(), scrimmage::find_terrain_files(), scrimmage::Updater::get_model_texture(), and parse().
extension()
std::string scrimmage::ConfigParse::extension ()
Definition at line 172 of file ConfigParse.cpp.
{
     if (fs::exists(filename_)) {
         return fs::path(filename_).extension().string();
     }
     return "";
 }
References filename_.
stem()
std::string scrimmage::ConfigParse::stem ()
Definition at line 179 of file ConfigParse.cpp.
{
     if (fs::exists(filename_)) {
         return fs::path(filename_).stem().string();
     }
     return "";
 }
References filename_.
print_params()
void scrimmage::ConfigParse::print_params ()
Definition at line 186 of file ConfigParse.cpp.
{
     for (auto &kv : params_) {
         cout << kv.first << "=" << kv.second << endl;
     }
 }
References params_.
recursive_params()
void scrimmage::ConfigParse::recursive_params (rapidxml::xml_node< char > * root, const std::map< std::string, std::string > & overrides, std::map< std::string, std::string > & params, const std::string & prev) protected
Definition at line 63 of file ConfigParse.cpp.
{
     // End condition
     if (root == 0 || root->name() == std::string("")
         || root->name() == std::string(" ")) {
         return;
     }
     // Process this node
     std::string name = root->name();
     if (prev != "") {
         name = prev + "/" + name;
     }
     if (params.count(name) > 0) {
         // Name already exists, consider this a list. Does the size
         // parameter exist yet?
         std::string name_size = name + ":size";
         int size = 2;
         if (params.count(name_size) > 0) {
             // It does exist, grab the current size and increment.
             size = std::stoi(params[name_size]) + 1;
         }
         name = name + "_" + std::to_string(size-1);
         params[name_size] = std::to_string(size);
     }
     if (overrides.count(name)) {
         params[name] = overrides.at(name);
     } else {
         params[name] = root->value();
     }
     // Recurse (depth-first)
     recursive_params(root->first_node(), overrides, params, name);
     // Recurse (sibling node)
     recursive_params(root->next_sibling(), overrides, params, prev);
 }
References params().
Referenced by parse().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, ConfigParse & cp) friend
Definition at line 192 of file ConfigParse.cpp.
{
     for (auto &kv : cp.params()) {
         os << kv.first << "=" << kv.second << endl;
     }
     return os;
 }
Member Data Documentation
params_
std::map<std::string, std::string> scrimmage::ConfigParse::params_ protected
Definition at line 65 of file ConfigParse.h.
Referenced by params(), parse(), and print_params().
required_
std::vector<std::string> scrimmage::ConfigParse::required_ protected
Definition at line 66 of file ConfigParse.h.
Referenced by parse(), and set_required().
filename_
std::string scrimmage::ConfigParse::filename_ protected
Definition at line 67 of file ConfigParse.h.
Referenced by directory(), extension(), filename(), parse(), and stem().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/parse/ConfigParse.h
/root/scrimmage/scrimmage/src/parse/ConfigParse.cpp