SCRIMMAGE: scrimmage::GlobalService Class Reference
scrimmage::GlobalService Class Reference
#include <GlobalService.h>
Public Member Functions
GlobalService ()
~GlobalService ()
std::unordered_map< std::string, Service > & services ()
bool call_service (MessageBasePtr req, MessageBasePtr &res, const std::string &service_name)
bool call_service (MessageBasePtr &res, const std::string &service_name)
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type>
bool call_service (MessageBasePtr req, T &res, const std::string &service_name)
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type>
bool call_service (T &res, const std::string &service_name)
Protected Attributes
std::unordered_map< std::string, Service > services_
Detailed Description
Definition at line 50 of file GlobalService.h.
Constructor & Destructor Documentation
GlobalService()
scrimmage::GlobalService::GlobalService ()
Definition at line 39 of file GlobalService.cpp.
{
     // No-op
 }
~GlobalService()
scrimmage::GlobalService::~GlobalService ()
Definition at line 43 of file GlobalService.cpp.
{
     // Clean up the services
     services_.clear();
 }
References services_.
Member Function Documentation
services()
std::unordered_map< std::string, Service > & scrimmage::GlobalService::services ()
Definition at line 48 of file GlobalService.cpp.
 {return services_;}
References services_.
call_service() [1/4]
bool scrimmage::GlobalService::call_service (scrimmage::MessageBasePtr req, scrimmage::MessageBasePtr & res, const std::string & service_name)
Definition at line 50 of file GlobalService.cpp.
{
     auto it = services_.find(service_name);
     if (it == services_.end()) {
         std::cout << "request for global service ("
             << service_name
             << ") that does not exist" << std::endl;
         std::cout << "Global services are: ";
         for (auto &kv : services_) {
             std::cout << kv.first << ", ";
         }
         std::cout << std::endl;
         return false;
     }
     Service &service = it->second;
     bool success = service(req, res);
     if (!success) {
         std::cout << "call to " << service_name << " failed" << std::endl;
         return false;
     } else {
         return true;
     }
 }
References services_.
Referenced by call_service().
call_service() [2/4]
bool scrimmage::GlobalService::call_service (MessageBasePtr & res, const std::string & service_name) inline
Definition at line 61 of file GlobalService.h.
{
         return call_service(std::make_shared<MessageBase>(), res, service_name);
     }
References call_service().
call_service() [3/4]
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type> bool scrimmage::GlobalService::call_service (MessageBasePtr req, T & res, const std::string & service_name) inline
Definition at line 67 of file GlobalService.h.
{
         MessageBasePtr res_base;
         if (call_service(req, res_base, service_name)) {
             res = std::dynamic_pointer_cast<typename T::element_type>(res_base);
             if (res == nullptr) {
                 std::cout << "could not cast for global service " << service_name.c_str() << std::endl;
                 return false;
             } else {
                 return true;
             }
         } else {
             return false;
         }
     }
References call_service().
call_service() [4/4]
template<class T = MessageBasePtr, class = typename std::enable_if<!std::is_same<T, MessageBasePtr>::value, void>::type> bool scrimmage::GlobalService::call_service (T & res, const std::string & service_name) inline
Definition at line 84 of file GlobalService.h.
{
         return call_service(std::make_shared<MessageBase>(), res, service_name);
     }
References call_service().
Member Data Documentation
services_
std::unordered_map<std::string, Service> scrimmage::GlobalService::services_ protected
Definition at line 89 of file GlobalService.h.
Referenced by call_service(), services(), and ~GlobalService().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/GlobalService.h
/root/scrimmage/scrimmage/src/common/GlobalService.cpp