SCRIMMAGE: scrimmage::autonomy::WaypointListProcessor Class Reference
scrimmage::autonomy::WaypointListProcessor Class Reference
#include <WaypointListProcessor.h>
Public Types
enum Status { Status::Empty, Status::Invalid, Status::Changed, Status::Unchanged }
Public Member Functions
void set_waypoint_list (const scrimmage_msgs::WaypointList &wp_list)
Status process (const scrimmage::StatePtr &state, const std::shared_ptr< GeographicLib::LocalCartesian > &proj)
boost::optional< const Waypoint & > previous_waypoint ()
boost::optional< const Waypoint & > current_waypoint ()
boost::optional< const Waypoint & > next_waypoint ()
Protected Member Functions
std::list< Waypoint >::iterator next_waypoint (const std::list< Waypoint >::iterator &it_wp)
Protected Attributes
std::shared_ptr< GeographicLib::LocalCartesian > proj_
std::list< Waypoint > wp_list_
std::list< Waypoint >::iterator prev_wp_it_ = wp_list_.end()
std::list< Waypoint >::iterator curr_wp_it_ = wp_list_.end()
std::list< Waypoint >::iterator next_wp_it_ = wp_list_.end()
scrimmage_msgs::WaypointList proto_wp_list_
scrimmage_msgs::WaypointList::Mode mode_
bool returning_stage_ = false
Detailed Description
Definition at line 48 of file WaypointListProcessor.h.
Member Enumeration Documentation
enum scrimmage::autonomy::WaypointListProcessor::Status strong
Enumerator
Empty
Invalid
Changed
Unchanged
Definition at line 50 of file WaypointListProcessor.h.
 { Empty, Invalid, Changed, Unchanged  };
Member Function Documentation
void scrimmage::autonomy::WaypointListProcessor::set_waypoint_list (const scrimmage_msgs::WaypointList & wp_list)
Definition at line 43 of file WaypointListProcessor.cpp.
References curr_wp_it_, next_waypoint(), next_wp_it_, returning_stage_, and wp_list_.
{
     returning_stage_ = false;
     // Construct a list of Waypoints from protobuf waypoint list
     wp_list_.clear();
     for (int i = 0; i < wp_list.waypoints().size(); i++) {
         wp_list_.push_back(Waypoint(wp_list.waypoints(i)));
     }
     // Filter the waypoint list to ensure that two waypoints in succession
     // are not equal. Some planners generate duplicate waypoints.
     auto wps_are_close = [] (auto &wp0, auto &wp1) {
         auto numbers_are_close = [] (const double &a, const double &b) {
             return std::abs(a - b) < std::numeric_limits<double>::epsilon();
         };
         return numbers_are_close(wp0.latitude(), wp1.latitude())
                 && numbers_are_close(wp0.longitude(), wp1.longitude())
                 && numbers_are_close(wp0.altitude(), wp1.altitude());
     };
     wp_list_.unique(wps_are_close);
     // Set the wp iterator to point to the beginning of the list
     // prev_wp_it_ = wp_list_.begin();
     curr_wp_it_ = wp_list_.begin();
     next_wp_it_ = next_waypoint(curr_wp_it_);
 }
WaypointListProcessor::Status scrimmage::autonomy::WaypointListProcessor::process (const scrimmage::StatePtr & state, const std::shared_ptr< GeographicLib::LocalCartesian > & proj)
Definition at line 72 of file WaypointListProcessor.cpp.
References Changed, curr_wp_it_, Empty, scrimmage::autonomy::Waypoint::is_within_tolerance(), next_waypoint(), next_wp_it_, prev_wp_it_, Unchanged, and wp_list_.
{
     if (wp_list_.size() == 0) {
         return Status::Empty;
     }
     Waypoint &curr_wp_lla = *curr_wp_it_;
     // If the current state isn't within tolerance, the waypoint is unchanged
     if (not curr_wp_lla.is_within_tolerance(state, proj)) {
         return Status::Unchanged;
     }
     prev_wp_it_ = curr_wp_it_;
     curr_wp_it_ = next_waypoint(curr_wp_it_);
     next_wp_it_ = next_waypoint(curr_wp_it_);
     return Status::Changed;
 }
boost::optional< const Waypoint & > scrimmage::autonomy::WaypointListProcessor::previous_waypoint ()
Definition at line 133 of file WaypointListProcessor.cpp.
References prev_wp_it_, and wp_list_.
{
     return prev_wp_it_ != wp_list_.end() ?
             boost::optional<const Waypoint&>{*prev_wp_it_} :
             boost::optional<const Waypoint&>{};
 }
boost::optional< const Waypoint & > scrimmage::autonomy::WaypointListProcessor::current_waypoint ()
Definition at line 140 of file WaypointListProcessor.cpp.
References curr_wp_it_, and wp_list_.
{
     return curr_wp_it_ != wp_list_.end() ?
             boost::optional<const Waypoint&>{*curr_wp_it_} :
             boost::optional<const Waypoint&>{};
 }
boost::optional< const Waypoint & > scrimmage::autonomy::WaypointListProcessor::next_waypoint ()
Definition at line 147 of file WaypointListProcessor.cpp.
References next_wp_it_, and wp_list_.
Referenced by process(), and set_waypoint_list().
{
     return next_wp_it_ != wp_list_.end() ?
             boost::optional<const Waypoint&>{*next_wp_it_} :
             boost::optional<const Waypoint&>{};
 }
std::list< Waypoint >::iterator scrimmage::autonomy::WaypointListProcessor::next_waypoint (const std::list< Waypoint >::iterator & it_wp) protected
Definition at line 94 of file WaypointListProcessor.cpp.
References curr_wp_it_, mode_, returning_stage_, and wp_list_.
{
     std::list<Waypoint>::iterator it_next;
     switch (mode_) {
         case scrimmage_msgs::WaypointList::FOLLOW_ONCE:
             it_next = std::next(it_wp);
             break;
         case scrimmage_msgs::WaypointList::BACK_AND_FORTH:
             it_next = returning_stage_ ? std::prev(it_wp): std::next(it_wp);
             if (it_next == wp_list_.begin()) {
                 returning_stage_ = false;
             } else if (it_next == wp_list_.end()) {
                 it_next = it_wp;
                 returning_stage_ = true;
             }
             break;
         case scrimmage_msgs::WaypointList::LOITER:
             // TODO : Not implemented yet
             break;
         case scrimmage_msgs::WaypointList::LOOP:
             // Continuous repeat of waypoints
             it_next = std::next(curr_wp_it_);
             if (it_next == wp_list_.end()) {
                 it_next = wp_list_.begin();
             }
             break;
         default :
             std::string msg = "Waypoint mode not defined yet.";
             throw std::runtime_error(msg);
     }
     return it_next;
 }
Member Data Documentation
std::shared_ptr<GeographicLib::LocalCartesian> scrimmage::autonomy::WaypointListProcessor::proj_ protected
Definition at line 60 of file WaypointListProcessor.h.
std::list<Waypoint> scrimmage::autonomy::WaypointListProcessor::wp_list_ protected
Definition at line 61 of file WaypointListProcessor.h.
Referenced by current_waypoint(), next_waypoint(), previous_waypoint(), process(), and set_waypoint_list().
std::list<Waypoint>::iterator scrimmage::autonomy::WaypointListProcessor::prev_wp_it_ = wp_list_.end() protected
Definition at line 63 of file WaypointListProcessor.h.
Referenced by previous_waypoint(), and process().
std::list<Waypoint>::iterator scrimmage::autonomy::WaypointListProcessor::curr_wp_it_ = wp_list_.end() protected
Definition at line 64 of file WaypointListProcessor.h.
Referenced by current_waypoint(), next_waypoint(), process(), and set_waypoint_list().
std::list<Waypoint>::iterator scrimmage::autonomy::WaypointListProcessor::next_wp_it_ = wp_list_.end() protected
Definition at line 65 of file WaypointListProcessor.h.
Referenced by next_waypoint(), process(), and set_waypoint_list().
scrimmage_msgs::WaypointList scrimmage::autonomy::WaypointListProcessor::proto_wp_list_ protected
Definition at line 66 of file WaypointListProcessor.h.
scrimmage_msgs::WaypointList::Mode scrimmage::autonomy::WaypointListProcessor::mode_ protected
Definition at line 67 of file WaypointListProcessor.h.
Referenced by next_waypoint().
bool scrimmage::autonomy::WaypointListProcessor::returning_stage_ = false protected
Definition at line 68 of file WaypointListProcessor.h.
Referenced by next_waypoint(), and set_waypoint_list().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/WaypointListProcessor.h
/root/scrimmage/scrimmage/src/common/WaypointListProcessor.cpp