SCRIMMAGE: scrimmage::SimControl Class Reference
scrimmage::SimControl Class Reference
#include <SimControl.h>
Classes
struct Task
Public Member Functions
SimControl ()
SimControl default constructor.
bool init (const std::string &mission_file, const bool &init_python=true)
Initialize a scrimmage simulation.
bool start ()
Starts the mission by generating entities and setting up logging.
bool run ()
Runs the scrimmage simulation in the current thread.
void run_threaded ()
Runs the scrimmage simulation in a separate thread.
bool run_single_step (const int &loop_number)
Runs the scrimmage simulation by a single time step.
bool shutdown (const bool &shutdown_python=true)
Finalizes the simulation, closes logs, closes plugins.
void force_exit ()
Force a threaded simulation to exit.
void join ()
Waits for the threaded simulation to exit.
EntityPluginPtr plugin ()
void get_contacts (std::unordered_map< int, Contact > &contacts)
Provides access to the simulated contacts.
void get_contact_visuals (std::map< int, ContactVisualPtr > &contact_visuals)
Provides access to the simulated contacts visualization information.
bool generate_entities (const double &t)
Generate entities based on the current time.
bool generate_entity (const int &ent_desc_id)
Generate an entity given the entity description ID.
bool generate_entity (const int &ent_desc_id, std::map< std::string, std::string > &params)
Generate an entity given the entity description ID and parameters.
MissionParsePtr mp ()
Get the pointer to the MissionParser instance.
void set_time (const double &t)
Set the simulation time.
double t ()
Get the current simulation time.
void pause (const bool &pause)
Pause (true) or unpause (false) the simulation.
bool paused ()
Get the paused (true) or unpaused (false) state of the simulation.
double time_warp ()
Get the desired time warp of the simulation.
double actual_time_warp ()
Get the actual time warp of the simulation.
bool enable_gui ()
Returns true if mission file requests a GUI.
bool end_condition_reached ()
Returns true if a simulation end condition has been met.
Timer & timer ()
Access the simulation timer instance.
std::list< MetricsPtr > & metrics ()
Access the metrics plugins.
PluginManagerPtr & plugin_manager ()
Access the PluginManager instance.
FileSearchPtr & file_search ()
Access the FileSearch instance.
void set_incoming_interface (InterfacePtr &incoming_interface)
Set the incoming interface for communication from external visualizers.
InterfacePtr incoming_interface ()
Get the incoming interface.
void set_outgoing_interface (InterfacePtr &outgoing_interface)
Set the outgoing interface for communication to external visualizers.
InterfacePtr outgoing_interface ()
Get the outgoing interface.
std::list< EntityPtr > & ents ()
Access the entities in the simulation.
void send_terrain ()
Sends terrain to visualizers and log files.
void run_send_shapes ()
Sends simulation shapes to visualizers and log files.
void display_progress (const bool &enable)
Enables/disable displaying the current progress in the terminal.
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_entity_map ()
Protected Member Functions
void worker ()
bool run_entities ()
bool add_tasks (Task::Type type, double t, double dt)
bool run_sensors ()
bool run_motion (EntityPtr &ent, double t, double dt)
bool reset_autonomies ()
bool collision_exists (Eigen::Vector3d &p)
void request_screenshot ()
void create_rtree (const unsigned int &additional_size)
void run_autonomy ()
void set_autonomy_contacts ()
void run_dynamics ()
bool run_interaction_detection ()
bool run_logging ()
bool run_metrics ()
void run_remove_inactive ()
void run_check_network_msgs ()
void run_send_contact_visuals ()
bool run_networks ()
Protected Attributes
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
InterfacePtr incoming_interface_
InterfacePtr outgoing_interface_
std::thread network_thread_
MissionParsePtr mp_
std::list< EntityPtr > ents_
ContactMapPtr contacts_
std::map< int, std::list< scrimmage_proto::ShapePtr > > shapes_
std::map< int, ContactVisualPtr > contact_visuals_
std::thread thread_
bool display_progress_ = false
std::string jsbsim_root_
TimePtr time_
ParameterServerPtr param_server_
GlobalServicePtr global_services_
double t0_ = 0
double tend_ = 0
double dt_ = 0
double t_ = 0
bool paused_
bool single_step_
bool take_step_ = false
Timer timer_
bool finished_ = false
bool exit_ = false
std::mutex finished_mutex_
std::mutex contacts_mutex_
std::mutex exit_mutex_
std::mutex timer_mutex_
std::mutex paused_mutex_
std::mutex single_step_mutex_
std::mutex take_step_mutex_
std::mutex time_mutex_
std::mutex time_warp_mutex_
std::mutex entity_pool_mutex_
std::set< Task::Type > entity_thread_types_
int num_entity_threads_ = 0
bool entity_pool_stop_ = false
std::deque< std::shared_ptr< Task > > entity_pool_queue_
std::condition_variable_any entity_pool_condition_var_
std::vector< std::thread > entity_worker_threads_
std::shared_ptr< Log > log_
std::set< EndConditionFlags > end_conditions_ = {EndConditionFlags::NONE}
RandomPtr random_
PluginManagerPtr plugin_manager_
std::shared_ptr< GeographicLib::LocalCartesian > proj_
std::list< EntityInteractionPtr > ent_inters_
std::list< MetricsPtr > metrics_
NetworkMapPtr networks_
PubSubPtr pubsub_
std::set< int > ids_used_ = {0}
FileSearchPtr file_search_
RTreePtr rtree_
bool send_shutdown_msg_ = true
EntityPluginPtr sim_plugin_
PublisherPtr pub_end_time_
PublisherPtr pub_ent_gen_
PublisherPtr pub_ent_rm_
PublisherPtr pub_ent_pres_end_
PublisherPtr pub_ent_int_exit_
PublisherPtr pub_no_teams_
PublisherPtr pub_one_team_
PublisherPtr pub_world_point_clicked_
PublisherPtr pub_custom_key_
std::list< EntityPtr > not_ready_
DelayedTask screenshot_task_
bool prev_paused_
DelayedTask reseed_task_
bool limited_verbosity_
Private Member Functions
bool take_step ()
void single_step (const bool &value)
bool single_step ()
void set_finished (bool finished)
bool output_summary ()
bool output_runtime ()
bool output_git_summary ()
void setup_timer (double rate, double time_warp)
void start_overall_timer ()
void start_loop_timer ()
void loop_wait ()
void inc_warp ()
void dec_warp ()
bool wait_for_ready ()
bool check_output (const std::string &output_type, const std::string &desired_output)
bool setup_logging ()
bool logging_logic (const std::string &s)
void end_of_simulation ()
void cleanup ()
bool finalize ()
bool reset_pointers ()
int find_available_id (const std::map< std::string, std::string > &params)
Private Attributes
bool finalized_called_ = false
bool running_in_thread_ = false
bool python_enabled_ = false
Detailed Description
Definition at line 65 of file SimControl.h.
Constructor & Destructor Documentation
scrimmage::SimControl::SimControl ()
SimControl default constructor.
Definition at line 111 of file SimControl.cpp.
References contacts_, contacts_mutex_, pause(), prev_paused_, and single_step().
                        :
     id_to_team_map_(std::make_shared<std::unordered_map<int, int>>()),
     id_to_ent_map_(std::make_shared<std::unordered_map<int, EntityPtr>>()),
     incoming_interface_(std::make_shared<Interface>()),
     outgoing_interface_(std::make_shared<Interface>()),
     mp_(std::make_shared<MissionParse>()),
     time_(std::make_shared<Time>()),
     param_server_(std::make_shared<ParameterServer>()),
     global_services_(std::make_shared<GlobalService>()),
     timer_(Timer()),
     log_(std::make_shared<Log>()),
     random_(std::make_shared<Random>()),
     plugin_manager_(std::make_shared<PluginManager>()),
     networks_(std::make_shared<std::map<std::string, NetworkPtr>>()),
     pubsub_(std::make_shared<PubSub>()),
     file_search_(std::make_shared<FileSearch>()),
     rtree_(std::make_shared<scrimmage::RTree>()),
     sim_plugin_(std::make_shared<EntityPlugin>()),
     limited_verbosity_(false) {
     pause(false);
     prev_paused_ = false;
     single_step(false);
     contacts_mutex_.lock();
     contacts_ = std::make_shared<ContactMap>();
     contacts_mutex_.unlock();
 }
Member Function Documentation
bool scrimmage::SimControl::init (const std::string & mission_file, const bool & init_python = true)
Initialize a scrimmage simulation.
Parameters
[in] mission_file The scrimmage mission file for the simulation. The mission_file can be a relative path, absolute path, or a scrimmage mission file that is already on the SCRIMMAGE_MISSION_PATH.
[in] init_python If true, will call Py_Initialize() and initialize the Python interface. Py_Initialize() should only be called once per process.
When using SimControl to run a scrimmage mission, this init() function must always be called with a mission_file to properly initialize the simulation. After calling init(), the API supports running scrimmage in its own thread (e.g., using the run_threaded() function) or the controlling program can step the simulation manually (e.g., using the run_single_step() function).
Definition at line 161 of file SimControl.cpp.
References contact_visuals_, contacts_, ent_inters_, ents_, jsbsim_root_, metrics_, mp_, networks_, pause(), pubsub_, python_enabled_, and shapes_.
Referenced by scrimmage::run_test().
{
 #if ENABLE_PYTHON_BINDINGS == 1
     if (init_python) {
         Py_Initialize();
         python_enabled_ = true;
     }
 #endif
     ents_.clear();
     ent_inters_.clear();
     metrics_.clear();
     contacts_->clear();
     shapes_.clear();
     contact_visuals_.clear();
     networks_->clear();
     pubsub_->pubs().clear();
     pubsub_->subs().clear();
     if (!mp_->parse(mission_file)) {
         cout << "Failed to parse file: " << mission_file << endl;
         return false;
     }
     // Start with the simulation paused? Can be overriden by
     // SimControl::pause()
     if (mp_->start_paused()) {
         pause(true);
     }
 #if ENABLE_JSBSIM == 1
     jsbsim_root_ = "./";
     if (const char* env_p = std::getenv("JSBSIM_ROOT")) {
         jsbsim_root_ = std::string(env_p);
     } else {
         cout << "Missing JSBSIM_ROOT env variable, using ./" << endl;
     }
 #endif
     return true;
 }
bool scrimmage::SimControl::start ()
Starts the mission by generating entities and setting up logging.
Initializes entities, sets up logging, initializes the time.
Definition at line 668 of file SimControl.cpp.
References scrimmage::ALL_DEAD, scrimmage::SimControl::Task::AUTONOMY, scrimmage::Interface::client, contacts_, contacts_mutex_, scrimmage::SimControl::Task::CONTROLLER, scrimmage::create_ent_inters(), scrimmage::create_metrics(), scrimmage::create_networks(), create_rtree(), scrimmage::DelayedTask::delay, scrimmage::DelayedTask::disable, display_progress_, dt_, enable_gui(), end_conditions_, scrimmage::DelayedTask::end_time, ent_inters_, entity_pool_stop_, entity_thread_types_, entity_worker_threads_, scrimmage::DelayedTask::eps, scrimmage::SimUtilsInfo::file_search, file_search_, generate_entities(), generate_entity(), global_services_, scrimmage::SimUtilsInfo::id_to_ent_map, id_to_ent_map_, scrimmage::SimUtilsInfo::id_to_team_map, id_to_team_map_, incoming_interface_, scrimmage::Interface::init_network(), scrimmage::DelayedTask::last_updated_time, log_, metrics_, scrimmage::SimControl::Task::MOTION, scrimmage::SimUtilsInfo::mp, mp_, network_thread_, networks_, scrimmage::NONE, num_entity_threads_, scrimmage::ONE_TEAM, outgoing_interface_, scrimmage::SimUtilsInfo::param_server, param_server_, paused(), scrimmage::SimUtilsInfo::plugin_manager, plugin_manager_, prev_paused_, proj_, pub_custom_key_, pub_end_time_, pub_ent_gen_, pub_ent_int_exit_, pub_ent_pres_end_, pub_ent_rm_, pub_no_teams_, pub_one_team_, pub_world_point_clicked_, scrimmage::SimUtilsInfo::pubsub, pubsub_, python_enabled_, scrimmage::Angles::rad2deg(), scrimmage::SimUtilsInfo::random, random_, request_screenshot(), reseed_task_, scrimmage::SimUtilsInfo::rtree, rtree_, run_interaction_detection(), screenshot_task_, scrimmage::SimControl::Task::SENSOR, scrimmage::Interface::server, scrimmage::set(), scrimmage::DelayedTask::set_repeat_infinitely(), set_time(), setup_logging(), setup_timer(), shapes_, scrimmage::Interface::shared, sim_plugin_, start_overall_timer(), scrimmage::str2bool(), t(), t0_, t_, scrimmage::DelayedTask::task, tend_, scrimmage::SimUtilsInfo::time, scrimmage::TIME, time_, scrimmage::DelayedTask::update(), and worker().
Referenced by run().
{
     setup_logging();
     // Set the time parameters based on the mission file input
     t0_ = mp_->t0();
     tend_ = mp_->tend();
     dt_ = mp_->dt();
     time_->set_t(t0_);
     time_->set_dt(dt_);
     time_->set_time_warp(mp_->time_warp());
     display_progress_ = get("display_progress", mp_->params(), true);
     proj_ = mp_->projection(); // get projection (origin) from mission
     if (get("show_plugins", mp_->params(), false)) {
         plugin_manager_->print_plugins("scrimmage::Autonomy", "Autonomy Plugins", *file_search_);
         plugin_manager_->print_plugins("scrimmage::MotionModel", "Motion Plugins", *file_search_);
         plugin_manager_->print_plugins("scrimmage::Controller", "Controller Plugins", *file_search_);
         plugin_manager_->print_plugins("scrimmage::EntityInteraction", "Entity Interaction Plugins", *file_search_);
         plugin_manager_->print_plugins("scrimmage::Sensor", "Sensor Plugins", *file_search_);
         plugin_manager_->print_plugins("scrimmage::Metrics", "Metrics Plugins", *file_search_);
     }
         // Setup random seed
     if (mp_->params().count("seed") > 0) {
         auto seed = std::stoul(mp_->params()["seed"]);
         random_->seed(seed);
 #if ENABLE_PYTHON_BINDINGS == 1
         if (python_enabled_) {
             pybind11::module::import("random").attr("seed")(seed);
             try {
                 pybind11::module::import("numpy.random").attr("seed")(seed);
             } catch (pybind11::error_already_set) {
                 // ignore. numpy not installed
             }
         }
 #endif
     } else {
         random_->seed();
     }
     log_->write_ascii("Seed: " + std::to_string(random_->get_seed()));
     auto get_count = [&](auto &kv) {return kv.second.total_count;};
     int max_num_entities =
         boost::accumulate(mp_->gen_info() | ba::transformed(get_count), 0);
     // What is the end condition?
     if (mp_->params().count("end_condition") > 0) {
         std::string cond = mp_->params()["end_condition"];
         auto add_cond = [&](auto nm, auto flag) {
             if (cond.find(nm) != std::string::npos) {
                 end_conditions_.insert(flag);
             }
         };
         add_cond("time", EndConditionFlags::TIME);
         add_cond("one_team", EndConditionFlags::ONE_TEAM);
         add_cond("none", EndConditionFlags::NONE);
         add_cond("all_dead", EndConditionFlags::ALL_DEAD);
     } else {
         end_conditions_.insert(EndConditionFlags::TIME);
     }
     if (mp_->params().count("stream_port") > 0 &&
         mp_->params().count("stream_ip") > 0) {
         if (mp_->network_gui()) {
             outgoing_interface_->init_network(Interface::client,
                                               mp_->params()["stream_ip"],
                                               std::stoi(mp_->params()["stream_port"]));
             network_thread_ = std::thread(&Interface::init_network, &(*incoming_interface_),
                                           Interface::server,
                                           "localhost",
                                           std::stoi(mp_->params()["stream_port"])+1);
             network_thread_.detach();
         } else {
             outgoing_interface_->set_mode(Interface::shared);
             incoming_interface_->set_mode(Interface::shared);
         }
     } else {
         outgoing_interface_->set_mode(Interface::shared);
         incoming_interface_->set_mode(Interface::shared);
     }
     // If the GlobalNetwork doesn't exist, add it.
     auto it_global_network = std::find(mp_->network_names().begin(),
                                        mp_->network_names().end(),
                                        "GlobalNetwork");
     if (it_global_network == mp_->network_names().end()) {
         mp_->network_names().push_back("GlobalNetwork");
     }
     // setup sim_plugin
     sim_plugin_->parent()->set_random(random_);
     sim_plugin_->set_time(time_);
     sim_plugin_->set_pubsub(pubsub_);
     // Create base shape objects
     for (auto &kv : mp_->team_info()) {
         int i = 0;
         for (Eigen::Vector3d &base_pos : kv.second.bases) {
             auto base = std::make_shared<scrimmage_proto::Shape>();
             base->mutable_sphere()->set_radius(kv.second.radii[i]);
             sc::set(base->mutable_sphere()->mutable_center(), base_pos);
             base->set_opacity(kv.second.opacities[i]);
             sc::set(base->mutable_color(), kv.second.color);
             base->set_persistent(true);
             sim_plugin_->draw_shape(base);
             i++;
         }
     }
     // Get the list of "metrics" plugins
     SimUtilsInfo info;
     info.mp = mp_;
     info.plugin_manager = plugin_manager_;
     info.file_search = file_search_;
     info.rtree = rtree_;
     info.pubsub = pubsub_;
     info.time = time_;
     info.param_server = param_server_;
     info.random = random_;
     info.id_to_team_map = id_to_team_map_;
     info.id_to_ent_map = id_to_ent_map_;
     networks_ = std::make_shared<NetworkMap>();
     if (!create_networks(info, *networks_)) return false;
     if (!create_metrics(info, contacts_, metrics_)) return false;
     if (!create_ent_inters(info, contacts_, shapes_[0], ent_inters_, global_services_)) return false;
     // Setup simcontrol's pubsub plugin
     pub_end_time_ = sim_plugin_->advertise("GlobalNetwork", "EndTime");
     pub_ent_gen_ = sim_plugin_->advertise("GlobalNetwork", "EntityGenerated");
     pub_ent_rm_ = sim_plugin_->advertise("GlobalNetwork", "EntityRemoved");
     pub_ent_pres_end_ = sim_plugin_->advertise("GlobalNetwork", "EntityPresentAtEnd");
     pub_ent_int_exit_ = sim_plugin_->advertise("GlobalNetwork", "EntityInteractionExit");
     pub_no_teams_ = sim_plugin_->advertise("GlobalNetwork", "NoTeamsPresent");
     pub_one_team_ = sim_plugin_->advertise("GlobalNetwork", "OneTeamPresent");
     pub_world_point_clicked_ = sim_plugin_->advertise("GlobalNetwork", "WorldPointClicked");
     pub_custom_key_ = sim_plugin_->advertise("GlobalNetwork", "CustomKeyPress");
     // Set subscriber / callback that allows plugins to generate entities
     auto gen_ent_cb = [&] (auto &msg) {
         auto it_ent_desc_id = mp_->entity_tag_to_id().find(msg->data.entity_tag());
         if (it_ent_desc_id == mp_->entity_tag_to_id().end()) {
             cout << "ERROR: Failed to find entity_tag, "
                  << msg->data.entity_tag() << ", in mission file." << endl;
             return;
         }
         // Get the vehicle's params block:
         auto it_params = mp_->entity_descriptions().find(it_ent_desc_id->second);
         if (it_params == mp_->entity_descriptions().end()) {
             cout << "ERROR: Failed to find entity block id, "
                  << it_ent_desc_id->second << ", for entity_tag: "
                  << msg->data.entity_tag() << ", in mission file." << endl;
             return;
         }
         // Overwrite the vehicle's state in the "params" block
         std::map<std::string, std::string> params = it_params->second;
         params["x0"] = std::to_string(msg->data.state().position().x());
         params["y0"] = std::to_string(msg->data.state().position().y());
         params["z0"] = std::to_string(msg->data.state().position().z());
         params["vx"] = std::to_string(msg->data.state().linear_velocity().x());
         params["vy"] = std::to_string(msg->data.state().linear_velocity().y());
         params["vz"] = std::to_string(msg->data.state().linear_velocity().z());
         sc::Quaternion quat;
         sc::set(quat, msg->data.state().orientation());
         params["roll"] = std::to_string(sc::Angles::rad2deg(quat.roll()));
         params["pitch"] = std::to_string(sc::Angles::rad2deg(quat.pitch()));
         params["heading"] = std::to_string(sc::Angles::rad2deg(quat.yaw()));
         // Assign the ID based on the protobuf message
         params["id"] = std::to_string(msg->data.entity_id());
         // Override any manually specified entity_params
         for (int i = 0; i < msg->data.entity_param().size(); i++) {
             params[msg->data.entity_param(i).key()] = msg->data.entity_param(i).value();
         }
         // Recreate the rtree with one additional size for this entity.
         this->create_rtree(1);
         if (not this->generate_entity(it_ent_desc_id->second, params)) {
             cout << "Failed to generate entity with tag: "
                  << msg->data.entity_tag() << endl;
             return;
         }
     };
     sim_plugin_->subscribe<sm::GenerateEntity>("GlobalNetwork",
                                                "GenerateEntity", gen_ent_cb);
     contacts_mutex_.lock();
     contacts_->reserve(max_num_entities+1);
     contacts_mutex_.unlock();
     if (get("show_plugins", mp_->params(), false)) {
         plugin_manager_->print_returned_plugins();
     }
     if (get("multi_threaded", mp_->params(), false)) {
         auto it = mp_->attributes().find("multi_threaded");
         if (it != mp_->attributes().end()) {
             auto &attr_map = it->second;
             auto add = [&](auto attr_str, auto attr_type) {
                 if (str2bool(get(attr_str, attr_map, "true"))) {
                     entity_thread_types_.insert(attr_type);
                 }
             };
             add("autonomy", Task::Type::AUTONOMY);
             add("controller", Task::Type::CONTROLLER);
             add("motion", Task::Type::MOTION);
             add("sensor", Task::Type::SENSOR);
         }
         if (!entity_thread_types_.empty()) {
             entity_pool_stop_ = false;
             num_entity_threads_ = get("num_threads", mp_->attributes()["multi_threaded"], 1);
             entity_worker_threads_.clear();
             entity_worker_threads_.reserve(num_entity_threads_);
             for (int i = 0; i < num_entity_threads_; i++) {
                 entity_worker_threads_.push_back(std::thread(&SimControl::worker, this));
             }
         }
     }
     // screenshots
     if (enable_gui() && get<bool>("enable_screenshots", mp_->params(), false) && mp_) {
         auto it = mp_->attributes().find("enable_screenshots");
         std::map<std::string, std::string> attr;
         if (it != mp_->attributes().end()) {
             attr = it->second;
         }
         screenshot_task_.disable = false;
         screenshot_task_.delay = get<double>("min_period", attr, 0.0);
         screenshot_task_.set_repeat_infinitely(true);
         screenshot_task_.last_updated_time =
             get<double>("start", attr, 0.0) - screenshot_task_.delay;
         screenshot_task_.end_time =
             get<double>("end", attr, std::numeric_limits<double>::infinity());
         screenshot_task_.eps = dt_ / 4;
         if (screenshot_task_.update(t_).first) {
             request_screenshot();
         }
     } else {
         screenshot_task_.disable = true;
     }
     prev_paused_ = paused();
     // reseeding
     auto it = mp_->attributes().find("seed");
     if (it != mp_->attributes().end()) {
         auto it2 = it->second.find("reseed_time");
         if (it2 != it->second.end()) {
             auto it3 = it->second.find("reseed");
             uint32_t reseed = 0;
             bool has_reseed = it3 != it->second.end();
             if (has_reseed) {
                 reseed = std::stoul(it3->second);
             }
             reseed_task_ = DelayedTask(std::stod(it2->second), 0);
             reseed_task_.last_updated_time = 0;
             reseed_task_.task = [&, has_reseed, reseed](double t) {
                 if (has_reseed) {
                     random_->seed(reseed);
                 } else {
                     random_->seed();
                 }
                 log_->write_ascii("ReSeed: " + std::to_string(random_->get_seed()));
                 return true;
             };
         }
     }
     setup_timer(1.0 / dt_, mp_->time_warp());
     start_overall_timer();
     // Simulate over the time range
     set_time(t0_ - dt_);
     // Initialize entities before simulation begings
     if (!generate_entities(t0_ - dt_)) {
         cout << "Failed to generate entity" << endl;
         return false;
     }
     // Run the interaction plugins before the simulation begins
     if (!run_interaction_detection()) {
         auto msg = std::make_shared<Message<sm::EntityInteractionExit>>();
         pub_ent_int_exit_->publish(msg);
         return false;
     }
     set_time(t0_);
     return true;
 }
bool scrimmage::SimControl::run ()
Runs the scrimmage simulation in the current thread.
Example API usage:
SimControl simcontrol;
simcontrol.init("./missions/straight.xml");
simcontrol.run();
simcontrol.shutdown();
Definition at line 974 of file SimControl.cpp.
References finalize(), run_single_step(), and start().
Referenced by scrimmage::run_test(), run_threaded(), and worker().
                      {
     if (not start()) {
         return false;
     }
     int loop_number = 0;
     while (run_single_step(loop_number++)) {}
     return finalize();
 }
void scrimmage::SimControl::run_threaded ()
Runs the scrimmage simulation in a separate thread.
Example API usage:
SimControl simcontrol;
simcontrol.init("./missions/straight.xml");
simcontrol.run_threaded();
... Do other work ...
simcontrol.force_exit();
simcontrol.join();
simcontrol.shutdown();
Definition at line 663 of file SimControl.cpp.
References run(), running_in_thread_, and thread_.
{
     running_in_thread_ = true;
     thread_ = std::thread(&SimControl::run, this);
 }
bool scrimmage::SimControl::run_single_step (const int & loop_number)
Runs the scrimmage simulation by a single time step.
Example API usage:
SimControl simcontrol;
simcontrol.init("./missions/straight.xml");
simcontrol.start();
for (int i = 0; i < 100; i++) {
    simcontrol.run_single_step(i);
}
simcontrol.shutdown();
Definition at line 547 of file SimControl.cpp.
References actual_time_warp(), scrimmage::display_progress(), display_progress_, dt_, end_condition_reached(), exit_, exit_mutex_, generate_entities(), limited_verbosity_, loop_wait(), outgoing_interface_, pause(), paused(), paused_, prev_paused_, pub_ent_int_exit_, request_screenshot(), reseed_task_, scrimmage::run_callbacks(), run_check_network_msgs(), run_entities(), run_interaction_detection(), run_logging(), run_metrics(), run_networks(), run_remove_inactive(), run_send_contact_visuals(), run_send_shapes(), run_sensors(), screenshot_task_, set_autonomy_contacts(), set_time(), sim_plugin_, single_step(), start_loop_timer(), t(), t_, take_step_, take_step_mutex_, tend_, time_warp(), scrimmage::DelayedTask::update(), and wait_for_ready().
Referenced by run().
{
     double t = this->t();
     reseed_task_.update(t);
     start_loop_timer();
     if (!generate_entities(t)) {
         cout << "Failed to generate entity" << endl;
         return false;
     }
     run_callbacks(sim_plugin_);
     if (screenshot_task_.update(t_).first) {
         request_screenshot();
     }
     if (!run_logging()) {
         if (!limited_verbosity_) {
             std::cout << "Exiting due to logging exception" << std::endl;
         }
         return false;
     }
     // Wait loop timer.
     // Stay in loop if currently paused.
     bool exit_loop = false;
     do {
         // Were we told to exit, externally?
         exit_mutex_.lock();
         if (exit_) {
             exit_loop = true;
         }
         exit_mutex_.unlock();
         if (single_step()) {
             single_step(false);
             take_step_mutex_.lock();
             take_step_ = true;
             take_step_mutex_.unlock();
             pause(prev_paused_);
             break;
         }
         run_check_network_msgs();
         scrimmage_proto::SimInfo info;
         info.set_time(this->t());
         info.set_desired_warp(this->time_warp());
         info.set_actual_warp(this->actual_time_warp());
         info.set_shutting_down(false);
         outgoing_interface_->send_sim_info(info);
         if (paused()) {
             std::this_thread::sleep_for(std::chrono::milliseconds(1));
         }
     } while (paused() && !exit_loop);
     if (!wait_for_ready()) {
         return false;
     }
     set_autonomy_contacts();
     if (!run_entities()) {
         if (!limited_verbosity_) {
             std::cout << "Exiting due to plugin request." << std::endl;
         }
         return false;
     }
     if (!run_sensors()) {
         if (!limited_verbosity_) {
             std::cout << "Exiting due to plugin request." << std::endl;
         }
         return false;
     }
     if (!run_interaction_detection()) {
         auto msg = std::make_shared<Message<sm::EntityInteractionExit>>();
         pub_ent_int_exit_->publish(msg);
         return false;
     }
     // The networks are run before the metrics, so that messages that are
     // published on the final time stamp can be processed by the metrics.
     if (!run_networks()) {
         if (!limited_verbosity_) {
             std::cout << "Exiting due to network plugin request." << std::endl;
         }
         return false;
     }
     if (!run_metrics()) {
         if (!limited_verbosity_) {
             std::cout << "Exiting due to metrics plugin exception" << std::endl;
         }
         return false;
     }
     run_remove_inactive();
     run_send_shapes();
     run_send_contact_visuals(); // send updated visuals
     if (display_progress_) {
         if (loop_number % 100 == 0) {
             sc::display_progress((tend_ == 0) ? 1.0 : t / tend_);
         }
     }
     // Increment time and loop counter
     loop_wait();
     set_time(t + dt_);
     prev_paused_ = paused_;
     return not (end_condition_reached() || exit_loop);
 }
bool scrimmage::SimControl::shutdown (const bool & shutdown_python = true)
Finalizes the simulation, closes logs, closes plugins.
Parameters
[in] shutdown_python If true, will call Py_Finalize() and shutdown the Python interface. Py_Finalize() should only be called once per process and after Py_Initialize() was called.
The shutdown() function should be called after the simulation is complete.
Definition at line 1038 of file SimControl.cpp.
References ent_inters_, ents_, finalize(), networks_, python_enabled_, reset_pointers(), running_in_thread_, and t().
Referenced by scrimmage::run_test().
{
     finalize();
     // Close all plugins
     for (EntityPtr &ent : ents_) {
         ent->close(t());
     }
     for (EntityInteractionPtr ent_inter : ent_inters_) {
         ent_inter->close_plugin(t());
     }
     for (auto &kv : *networks_) {
         kv.second->close_plugin(t());
     }
     bool status = reset_pointers();
 #if ENABLE_PYTHON_BINDINGS == 1
     // When running the GUI in a separate thread, Python throws the following
     // exception during the Py_Finalize call:
     //
     // Exception KeyError: KeyError(140466908776576,) in <module 'threading'
     // from '/usr/lib/python2.7/threading.pyc'> ignored
     //
     // To disable this warning, dont call Py_Finalize if running in a thread.
     if (not running_in_thread_ && shutdown_python) {
         Py_Finalize();
         python_enabled_ = false;
     }
 #endif
     return status;
 }
void scrimmage::SimControl::force_exit ()
Force a threaded simulation to exit.
When running the simulation in a separate thread, this function sends a signal to the main simulation loop to exit.
Definition at line 1252 of file SimControl.cpp.
References exit_, and exit_mutex_.
Referenced by run_check_network_msgs(), and scrimmage::run_test().
{
     exit_mutex_.lock();
     exit_ = true;
     exit_mutex_.unlock();
 }
void scrimmage::SimControl::join ()
Waits for the threaded simulation to exit.
Definition at line 406 of file SimControl.cpp.
References thread_.
                       {
     thread_.join();
 }
EntityPluginPtr scrimmage::SimControl::plugin ()
Definition at line 1758 of file SimControl.cpp.
References sim_plugin_.
{
     return sim_plugin_;
 }
void scrimmage::SimControl::get_contacts (std::unordered_map< int, Contact > & contacts)
Provides access to the simulated contacts.
The contact map is indexed by contact ID.
Definition at line 1273 of file SimControl.cpp.
References contacts_, and contacts_mutex_.
{
     // The Viewer GUI also looks at the contacts
     contacts_mutex_.lock();
     contacts = *contacts_;
     for (auto &kv : contacts) {
         sc::State state = *kv.second.state();
         *kv.second.state() = state;
     }
     contacts_mutex_.unlock();
 }
void scrimmage::SimControl::get_contact_visuals (std::map< int, ContactVisualPtr > & contact_visuals)
Provides access to the simulated contacts visualization information.
The contact visuals map is indexed by contact ID.
Definition at line 1284 of file SimControl.cpp.
References contact_visuals_.
{
     contact_visuals = contact_visuals_;
 }
bool scrimmage::SimControl::generate_entities (const double & t)
Generate entities based on the current time.
Parameters
[in] t Current simulation time.
Determines the entities that should be generated at the given time and generates the entities.
Definition at line 211 of file SimControl.cpp.
References create_rtree(), scrimmage::GenerateInfo::gen_count, generate_entity(), mp_, random_, scrimmage::GenerateInfo::rate, scrimmage::remove_if(), scrimmage::GenerateInfo::time_variance, and scrimmage::GenerateInfo::total_count.
Referenced by run_single_step(), and start().
{
     // Construct a list of entities to generate based on the time and generate
     // rate properties. pair consists of entity description ID and
     // first_in_group.
     std::list<int> ents_to_gen;
     for (auto &kv : mp_->entity_descriptions()) {
         int ent_desc_id = kv.first;
         // Skip this entity description if all of its entities have already
         // been generated (i.e., it no longer has gen_info information)
         if (mp_->gen_info().count(ent_desc_id) == 0) {
             continue;
         }
         // Generate entities in this entity description block if time has been
         // reached
         int gen_count = 0;
         for (double &gen_time : mp_->next_gen_times()[ent_desc_id]) {
             GenerateInfo &gen_info = mp_->gen_info()[ent_desc_id];
             if (t < gen_time || gen_info.total_count <= 0) {
                 continue;
             }
             // Add this entity ID to the list of entities to generate
             ents_to_gen.push_back(ent_desc_id);
             gen_info.total_count--;
             // Is rate generation enabled?
             if (gen_info.rate > 0) {
                 NormDistribution norm_dist(t + 1.0 / gen_info.rate, gen_info.time_variance);
                 // save next gen time to pointer to next gen time
                 gen_time = norm_dist(*random_->gener());
                 if (gen_time <= t) {
                     cout << "Next generation time less than current time. "
                          << "generate_time_variance is too large." << endl;
                     gen_time = t + (1.0 / gen_info.rate);
                 }
             }
             // Break if we have reached the generate count
             if (++gen_count >= gen_info.gen_count) {
                 break;
             }
         }
     }
     // Delete gen_info's that don't have ents remaining (count==0)
     remove_if(mp_->gen_info(), [&](auto &kv) {return kv.second.total_count <= 0;});
     // Create a new rtree from the existing entity map and provide additional
     // space in the rtree for the new entities that will be generated.
     create_rtree(ents_to_gen.size());
     // Call generate_entity on each entity description id.
     auto gen_ent = [&] (const int &ent_desc_id) -> bool {
         return generate_entity(ent_desc_id);
     };
     bool status = std::all_of(ents_to_gen.begin(), ents_to_gen.end(), gen_ent);
     return status;
 }
bool scrimmage::SimControl::generate_entity (const int & ent_desc_id)
Generate an entity given the entity description ID.
Definition at line 273 of file SimControl.cpp.
References mp_.
Referenced by generate_entities(), and start().
{
     // Get the entity's params
     auto it_params = mp_->entity_descriptions().find(ent_desc_id);
     if (it_params == mp_->entity_descriptions().end()) {
         return false;
     }
     return generate_entity(ent_desc_id, it_params->second);
 }
bool scrimmage::SimControl::generate_entity (const int & ent_desc_id, std::map< std::string, std::string > & params)
Generate an entity given the entity description ID and parameters.
Definition at line 282 of file SimControl.cpp.
References collision_exists(), contact_visuals_, contacts_, contacts_mutex_, dt_, ents_, exit_, file_search_, find_available_id(), scrimmage::get(), global_services_, id_to_ent_map_, id_to_team_map_, jsbsim_root_, log_, mp_, not_ready_, outgoing_interface_, param_server_, plugin_manager_, proj_, pub_ent_gen_, pubsub_, random_, rtree_, and time_.
{
 #if ENABLE_JSBSIM == 1
     params["JSBSIM_ROOT"] = jsbsim_root_;
 #endif
     params["dt"] = std::to_string(dt_);
     params["motion_multiplier"] = std::to_string(mp_->motion_multiplier());
     double x0 = scrimmage::get("x0", params, 0.0);
     double y0 = scrimmage::get("y0", params, 0.0);
     double z0 = scrimmage::get("z0", params, 0.0);
     double heading = scrimmage::get("heading", params, 0.0);
     Eigen::Vector3d pos(x0, y0, z0);
     auto gener = random_->gener();
     NormDistribution x_normal_dist(x0, pow(get("variance_x", params, 100.0), 0.5));
     NormDistribution y_normal_dist(y0, pow(get("variance_y", params, 100.0), 0.5));
     NormDistribution z_normal_dist(z0, pow(get("variance_z", params, 0.0), 0.5));
     NormDistribution heading_normal_dist(heading, pow(get("variance_heading", params, 0.0), 0.5));
     params["heading"] = std::to_string(heading_normal_dist(*gener));
     bool use_variance_all_ents = scrimmage::get("use_variance_all_ents", params, false);
     // Use variance if a collision exists (This happens when you place <entity>
     // tags" at the same location). Or, if use_variance_all_ents is specified
     // as true in the entity block.
     if (collision_exists(pos) || use_variance_all_ents) {
         // Use the uniform distribution to place aircraft
         // within the x/y variance
         int ct = 0;
         const int max_ct = 1e6;
         bool reselect_pos = collision_exists(pos) || use_variance_all_ents;
         while (ct++ < max_ct && !exit_ && reselect_pos) {
             pos(0) = x_normal_dist(*gener);
             pos(1) = y_normal_dist(*gener);
             pos(2) = z_normal_dist(*gener);
             reselect_pos = collision_exists(pos);
         }
         if (ct >= max_ct) {
             cout << "----------------------------------" << endl;
             cout << "ERROR: Having difficulty finding collision-free location for entity at: "
                  << "(" << x0 << "," << y0 << "," << z0 << ")" << endl
                  << "With variance: (" << pos(0) << "," << pos(1) << "," << pos(2) << ")" << endl;
             return false;
         } else if (exit_) {
             return false;
         }
     }
     params["x"] = std::to_string(pos(0));
     params["y"] = std::to_string(pos(1));
     params["z"] = std::to_string(pos(2));
     // Fill in the ent's lat/lon/alt value
     double lat, lon, alt;
     proj_->Reverse(pos(0), pos(1), pos(2), lat, lon, alt);
     params["latitude"] = std::to_string(lat);
     params["longitude"] = std::to_string(lon);
     params["altitude"] = std::to_string(alt);
     std::shared_ptr<Entity> ent = std::make_shared<Entity>();
     ent->set_random(random_);
     contacts_mutex_.lock();
     AttributeMap &attr_map = mp_->entity_attributes()[ent_desc_id];
     int id = find_available_id(params);
     bool ent_status = ent->init(attr_map, params, id_to_team_map_,
                                 id_to_ent_map_,
                                 contacts_, mp_, proj_, id, ent_desc_id,
                                 plugin_manager_, file_search_, rtree_, pubsub_, time_,
                                 param_server_, global_services_,
                                 std::set<std::string>{},
                                 [](std::map<std::string, std::string>&){});
     contacts_mutex_.unlock();
     if (!ent_status) {
         cout << "Failed to parse entity at start position: "
              << "x=" << x0 << ", y=" << y0 << endl;
         return false;
     }
     (*id_to_team_map_)[ent->id().id()] = ent->id().team_id();
     (*id_to_ent_map_)[ent->id().id()] = ent;
     contact_visuals_[ent->id().id()] = ent->contact_visual();
     // Send the visual information to the viewer
     outgoing_interface_->send_contact_visual(ent->contact_visual());
     log_->save_contact_visual(ent->contact_visual());
     // Store pointer to entities that aren't ready yet
     if (!ent->ready()) {
         not_ready_.push_back(ent);
     }
     ents_.push_back(ent);
     rtree_->add(ent->state()->pos(), ent->id());
     contacts_mutex_.lock();
     (*contacts_)[ent->id().id()] =
             Contact(ent->id(), ent->radius(), ent->state_truth(),
                     ent->type(), ent->contact_visual(), ent->properties());
     contacts_mutex_.unlock();
     auto msg = std::make_shared<Message<sm::EntityGenerated>>();
     msg->data.set_entity_id(ent->id().id());
     pub_ent_gen_->publish(msg);
     return true;
 }
MissionParsePtr scrimmage::SimControl::mp ()
Get the pointer to the MissionParser instance.
Definition at line 396 of file SimControl.cpp.
References mp_.
Referenced by scrimmage::run_test().
 { return mp_; }
void scrimmage::SimControl::set_time (const double & t)
Set the simulation time.
Parameters
[in] t The simulation time
Definition at line 1324 of file SimControl.cpp.
References t(), t_, time_, and time_mutex_.
Referenced by finalize(), run_single_step(), and start().
{
     time_mutex_.lock();
     t_ = t;
     time_->set_t(t_);
     time_mutex_.unlock();
 }
double scrimmage::SimControl::t ()
Get the current simulation time.
Definition at line 1331 of file SimControl.cpp.
References t_, and time_mutex_.
Referenced by add_tasks(), end_condition_reached(), finalize(), output_runtime(), reset_pointers(), run_interaction_detection(), run_remove_inactive(), run_send_shapes(), run_single_step(), send_terrain(), set_finished(), set_time(), shutdown(), and start().
                      {
     double t;
     time_mutex_.lock();
     t = t_;
     time_mutex_.unlock();
     return t;
 }
void scrimmage::SimControl::pause (const bool & pause)
Pause (true) or unpause (false) the simulation.
Definition at line 1300 of file SimControl.cpp.
References paused_, and paused_mutex_.
Referenced by init(), request_screenshot(), run_check_network_msgs(), run_single_step(), scrimmage::run_test(), and SimControl().
{
     paused_mutex_.lock();
     paused_ = pause;
     paused_mutex_.unlock();
 }
bool scrimmage::SimControl::paused ()
Get the paused (true) or unpaused (false) state of the simulation.
Definition at line 1306 of file SimControl.cpp.
References paused_, and paused_mutex_.
Referenced by request_screenshot(), run_check_network_msgs(), run_single_step(), and start().
{
     bool result;
     paused_mutex_.lock();
     result = paused_;
     paused_mutex_.unlock();
     return result;
 }
double scrimmage::SimControl::time_warp ()
Get the desired time warp of the simulation.
Definition at line 1314 of file SimControl.cpp.
References scrimmage::Timer::time_warp(), timer_, and timer_mutex_.
Referenced by run_single_step(), and set_finished().
{
     double warp;
     timer_mutex_.lock();
     warp = timer_.time_warp();
     timer_mutex_.unlock();
     return warp;
 }
double scrimmage::SimControl::actual_time_warp ()
Get the actual time warp of the simulation.
The simulator will attempt to achieve the desired time warp provided by the time_warp() function. This function returns the actual time warp being used. (WARNING: Not implemented yet. For future use).
Definition at line 1322 of file SimControl.cpp.
Referenced by run_single_step(), and set_finished().
 { return -1; }
bool scrimmage::SimControl::enable_gui ()
Returns true if mission file requests a GUI.
Definition at line 398 of file SimControl.cpp.
References mp_.
Referenced by start().
{
     return mp_->enable_gui();
 }
bool scrimmage::SimControl::end_condition_reached ()
Returns true if a simulation end condition has been met.
Definition at line 1149 of file SimControl.cpp.
References scrimmage::ALL_DEAD, dt_, end_conditions_, ents_, mp_, scrimmage::ONE_TEAM, pub_end_time_, pub_no_teams_, pub_one_team_, t(), and scrimmage::TIME.
Referenced by run_single_step().
{
     if (end_conditions_.count(EndConditionFlags::TIME) && t() > mp_->tend() - dt_ / 2.0) {
         auto msg = std::make_shared<Message<sm::EndTime>>();
         pub_end_time_->publish(msg);
         return true;
     }
     if (ents_.empty()) {
         auto msg = std::make_shared<Message<sm::NoTeamsPresent>>();
         pub_no_teams_->publish(msg);
         if (end_conditions_.count(EndConditionFlags::ALL_DEAD) ||
             end_conditions_.count(EndConditionFlags::ONE_TEAM)) {
             std::cout << std::endl << "End of Simulation: No Entities Remaining" << std::endl;
             return true;
         }
     } else if (end_conditions_.count(EndConditionFlags::ONE_TEAM)) {
         const int team1_id = ents_.front()->id().team_id();
         const bool all_same_team = std::all_of(ents_.rbegin(), ents_.rend(),
             [&](EntityPtr &ent) {return team1_id == ent->id().team_id();});
         if (all_same_team) {
             auto msg = std::make_shared<Message<sm::OneTeamPresent>>();
             pub_one_team_->publish(msg);
             std::cout << std::endl << "End of Simulation: One Team (" << team1_id << ")" << std::endl;
             return true;
         }
     }
     return false;
 }
Timer & scrimmage::SimControl::timer ()
Access the simulation timer instance.
Definition at line 1180 of file SimControl.cpp.
References timer_.
 {return timer_;}
std::list< MetricsPtr > & scrimmage::SimControl::metrics ()
Access the metrics plugins.
Definition at line 1182 of file SimControl.cpp.
References metrics_.
Referenced by output_summary().
 { return metrics_; }
PluginManagerPtr & scrimmage::SimControl::plugin_manager ()
Access the PluginManager instance.
Definition at line 1184 of file SimControl.cpp.
References plugin_manager_.
 {return plugin_manager_;}
FileSearchPtr & scrimmage::SimControl::file_search ()
Access the FileSearch instance.
Definition at line 1186 of file SimControl.cpp.
References file_search_.
 {return file_search_;}
void scrimmage::SimControl::set_incoming_interface (InterfacePtr & incoming_interface)
Set the incoming interface for communication from external visualizers.
Definition at line 1195 of file SimControl.cpp.
References incoming_interface(), and incoming_interface_.
 { incoming_interface_ = incoming_interface; }
InterfacePtr scrimmage::SimControl::incoming_interface ()
Get the incoming interface.
Definition at line 1746 of file SimControl.cpp.
References incoming_interface_.
Referenced by set_incoming_interface().
{
     return incoming_interface_;
 }
void scrimmage::SimControl::set_outgoing_interface (InterfacePtr & outgoing_interface)
Set the outgoing interface for communication to external visualizers.
Definition at line 1198 of file SimControl.cpp.
References outgoing_interface(), and outgoing_interface_.
 { outgoing_interface_ = outgoing_interface; }
InterfacePtr scrimmage::SimControl::outgoing_interface ()
Get the outgoing interface.
Definition at line 1750 of file SimControl.cpp.
References outgoing_interface_.
Referenced by set_outgoing_interface().
{
     return outgoing_interface_;
 }
std::list< EntityPtr > & scrimmage::SimControl::ents ()
Access the entities in the simulation.
Definition at line 1754 of file SimControl.cpp.
References ents_.
{
     return ents_;
 }
void scrimmage::SimControl::send_terrain ()
Sends terrain to visualizers and log files.
Definition at line 139 of file SimControl.cpp.
References log_, mp_, outgoing_interface_, and t().
{
     // Send initial gui information through GUI interface
     mp_->utm_terrain()->set_time(this->t());
     outgoing_interface_->send_utm_terrain(mp_->utm_terrain());
     log_->save_utm_terrain(mp_->utm_terrain());
 }
void scrimmage::SimControl::run_send_shapes ()
Sends simulation shapes to visualizers and log files.
Definition at line 1597 of file SimControl.cpp.
References log_, outgoing_interface_, shapes_, and t().
Referenced by run_single_step().
{
     // Convert map of shapes to sp::Shapes type
     scrimmage_proto::Shapes shapes;
     shapes.set_time(this->t());
     for (auto &kv : shapes_) {
         for (auto &shape : kv.second) {
             scrimmage_proto::Shape *s = shapes.add_shape();
             *s = *shape;
         }
     }
     outgoing_interface_->send_shapes(shapes);
     log_->save_shapes(shapes);
     shapes_.clear();
 }
void scrimmage::SimControl::display_progress (const bool & enable)
Enables/disable displaying the current progress in the terminal.
Definition at line 402 of file SimControl.cpp.
References display_progress_.
{
     display_progress_ = enable;
 }
std::shared_ptr< std::unordered_map< int, EntityPtr > > scrimmage::SimControl::id_to_entity_map ()
Definition at line 1763 of file SimControl.cpp.
References id_to_ent_map_.
{
     return id_to_ent_map_;
 }
void scrimmage::SimControl::worker () protected
Definition at line 1379 of file SimControl.cpp.
References scrimmage::SimControl::Task::AUTONOMY, scrimmage::SimControl::Task::CONTROLLER, entity_pool_condition_var_, entity_pool_mutex_, entity_pool_queue_, entity_pool_stop_, scrimmage::SimControl::Task::MOTION, run(), scrimmage::run_callbacks(), and scrimmage::SimControl::Task::SENSOR.
Referenced by start().
{
     while (true) {
         entity_pool_mutex_.lock();
         entity_pool_condition_var_.wait(entity_pool_mutex_);
         entity_pool_mutex_.unlock();
         if (entity_pool_stop_) {
             break;
         }
         while (true) {
             entity_pool_mutex_.lock();
             if (entity_pool_queue_.empty()) {
                 entity_pool_mutex_.unlock();
                 break;
             }
             std::shared_ptr<Task> task = entity_pool_queue_.front();
             EntityPtr ent = task->ent;
             Task::Type task_type = task->type;
             double temp_t = task->t;
             double temp_dt = task->dt;
             entity_pool_queue_.pop_front();
             entity_pool_mutex_.unlock();
             bool success = false;
             if (task_type == Task::Type::AUTONOMY) {
                 auto &autonomies = ent->autonomies();
                 br::for_each(autonomies, run_callbacks);
                 auto run = [&](auto &a) {
                   return a->step_loop_timer(temp_dt) ?
                     a->step_autonomy(temp_t, temp_dt) : true;};
                 success = std::all_of(autonomies.begin(), autonomies.end(), run);
             } else if (task_type == Task::Type::CONTROLLER) {
                 auto &controllers = ent->controllers();
                 br::for_each(controllers, run_callbacks);
                 auto run = [&](auto &c) {
                   return c->step_loop_timer(temp_dt) ?
                     c->step(temp_t, temp_dt) : true;};
                 success = std::all_of(controllers.begin(), controllers.end(), run);
             } else if (task_type == Task::Type::MOTION) {
                 success = ent->motion()->step(temp_t, temp_dt);
             } else if (task_type == Task::Type::SENSOR) {
                 auto sensors = ent->sensors() | ba::map_values;
                 br::for_each(sensors, run_callbacks);
                 auto run = [&](auto &s) {
                   return s->step_loop_timer(temp_dt) ?
                     s->step() : true;};
                 success = std::all_of(sensors.begin(), sensors.end(), run);
             }
             entity_pool_mutex_.lock();
             task->prom.set_value(success);
             entity_pool_mutex_.unlock();
         }
     }
 }
bool scrimmage::SimControl::run_entities () protected
Definition at line 1502 of file SimControl.cpp.
References add_tasks(), scrimmage::SimControl::Task::AUTONOMY, contacts_mutex_, dt_, entity_thread_types_, ents_, scrimmage::SimControl::Task::MOTION, mp_, scrimmage::print_err(), scrimmage::run_callbacks(), shapes_, and t_.
Referenced by run_single_step().
{
     contacts_mutex_.lock();
     bool success = true;
     auto exec_step = [&](auto p, auto step_func) {
         run_callbacks(p);
         if (!step_func(p)) {
             print_err(p);
             return false;
         } else {
             return true;
         }
     };
     // run autonomies threaded or in a single thread
     if (entity_thread_types_.count(Task::Type::AUTONOMY)) {
         success &= add_tasks(Task::Type::AUTONOMY, t_, dt_);
     } else {
         for (EntityPtr &ent : ents_) {
             for (auto a : ent->autonomies()) {
                 success &= exec_step(a, [&](auto a){
                   return a->step_loop_timer(dt_) ?
                     a->step_autonomy(t_, dt_) : true;});
             }
         }
     }
     double motion_dt = dt_ / mp_->motion_multiplier();
     double temp_t = t_;
     for (int i = 0; i < mp_->motion_multiplier(); i++) {
         // run controllers in a single thread since they are serially connected
         for (EntityPtr &ent : ents_) {
             for (auto c : ent->controllers()) {
                 success &= exec_step(c, [&](auto c){
                   return c->step_loop_timer(dt_) ?
                     c->step(t_, dt_) : true;});
             }
         }
         // run motion model
         auto step_all = [&](Task::Type type, auto getter) {
             if (entity_thread_types_.count(type)) {
                 success &= add_tasks(type, temp_t, motion_dt);
             } else {
                 for (EntityPtr &ent : ents_) {
                     auto step = [&](auto p){return p->step(temp_t, motion_dt);};
                     success &= exec_step(getter(ent), step);
                 }
             }
         };
         step_all(Task::Type::MOTION, [&](auto ent){return ent->motion();});
         temp_t += motion_dt;
     }
     // Check if any entity has NaN in its state
     for (EntityPtr &ent : ents_) {
         if (ent->state()->pos().hasNaN()) {
             cout << "WARNING: Entity with motion model, "
                  << ent->motion()->name() << ", contains a NaN value." << endl
                  << "Check your time step values and for NaN values coming "
                  << "from Autonomy and Controller plugins."
                  << endl;
             cout << "Removing entity ID: " << ent->id().id() << endl;
             ent->collision();
         }
     }
     for (EntityPtr &ent : ents_) {
         ent->setup_desired_state();
     }
     for (EntityPtr &ent : ents_) {
         for (AutonomyPtr &autonomy : ent->autonomies()) {
             if (autonomy->need_reset()) {
                 autonomy->set_state(ent->motion()->state());
             }
         }
     }
     contacts_mutex_.unlock();
     for (EntityPtr &ent : ents_) {
         auto &shapes = shapes_[ent->id().id()];
         auto add_shapes = [&](const auto &p) {
             shapes.insert(shapes.end(), p->shapes().begin(), p->shapes().end());
             p->shapes().clear();
         };
         br::for_each(ent->autonomies(), add_shapes);
         br::for_each(ent->controllers(), add_shapes);
         add_shapes(ent->motion());
     }
     return success;
 }
bool scrimmage::SimControl::add_tasks (Task::Type type, double t, double dt) protected
Definition at line 1472 of file SimControl.cpp.
References entity_pool_condition_var_, entity_pool_mutex_, entity_pool_queue_, ents_, and t().
Referenced by run_entities(), and run_sensors().
{
     // FIXME: this will be much simpler once there is a
     // step function in EntityPlugin.h
     // In particular, we can get rid of Task::Type and
     // more easily do entity_interaction/network plugins in multiple threads.
     // put tasks on queue
     std::vector<std::future<bool>> futures;
     futures.reserve(ents_.size());
     entity_pool_mutex_.lock();
     for (EntityPtr &ent : ents_) {
         std::shared_ptr<Task> task = std::make_shared<Task>();
         task->ent = ent;
         task->type = type;
         task->t = t;
         task->dt = dt;
         entity_pool_queue_.push_back(task);
         futures.push_back(task->prom.get_future());
     }
     entity_pool_mutex_.unlock();
     // tell the threads to run
     entity_pool_condition_var_.notify_all();
     // wait for results
     auto get = [&](auto &future) {return future.get();};
     return std::all_of(futures.begin(), futures.end(), get);
 }
bool scrimmage::SimControl::run_sensors () protected
Definition at line 1444 of file SimControl.cpp.
References add_tasks(), dt_, entity_thread_types_, ents_, scrimmage::print_err(), scrimmage::run_callbacks(), scrimmage::SimControl::Task::SENSOR, shapes_, and t_.
Referenced by run_single_step().
{
     bool success = true;
     if (entity_thread_types_.count(Task::Type::SENSOR)) {
         success &= add_tasks(Task::Type::SENSOR, t_, dt_);
     } else {
         for (EntityPtr &ent : ents_) {
             br::for_each(ent->sensors() | ba::map_values, run_callbacks);
             for (auto &sensor : ent->sensors() | ba::map_values) {
                 if (sensor->step_loop_timer(dt_)) {
                     if (!sensor->step()) {
                         print_err(sensor);
                         success = false;
                     }
                 }
             }
         }
     }
     for (EntityPtr &ent : ents_) {
         auto &shapes = shapes_[ent->id().id()];
         for (auto &sensor : ent->sensors() | ba::map_values) {
             shapes.insert(shapes.end(), sensor->shapes().begin(), sensor->shapes().end());
             sensor->shapes().clear();
         }
     }
     return success;
 }
bool scrimmage::SimControl::run_motion (EntityPtr & ent, double t, double dt) protected
bool scrimmage::SimControl::reset_autonomies () protected
bool scrimmage::SimControl::collision_exists (Eigen::Vector3d & p) protected
Definition at line 1247 of file SimControl.cpp.
References ent_inters_, and ents_.
Referenced by generate_entity().
{
     return std::any_of(ent_inters_.begin(), ent_inters_.end(),
         [&](auto ent_inter) {return ent_inter->collision_exists(ents_, p);});
 }
void scrimmage::SimControl::request_screenshot () protected
Definition at line 202 of file SimControl.cpp.
References dt_, outgoing_interface_, pause(), paused(), prev_paused_, and t_.
Referenced by run_single_step(), and start().
{
     prev_paused_ = paused();
     pause(true);
     scrimmage_proto::GUIMsg gui_msg;
     gui_msg.set_time(t_ + dt_);
     gui_msg.set_single_step(true);
     outgoing_interface_->push_gui_msg(gui_msg);
 }
void scrimmage::SimControl::create_rtree (const unsigned int & additional_size) protected
Definition at line 410 of file SimControl.cpp.
References ents_, and rtree_.
Referenced by generate_entities(), and start().
{
     rtree_->init(ents_.size() + additional_size);
     for (EntityPtr &ent: ents_) {
         rtree_->add(ent->state()->pos(), ent->id());
     }
 }
void scrimmage::SimControl::run_autonomy () protected
void scrimmage::SimControl::set_autonomy_contacts () protected
Definition at line 417 of file SimControl.cpp.
References contacts_, contacts_mutex_, and ents_.
Referenced by run_single_step().
{
     std::map<std::string, AutonomyPtr> autonomy_map;
     for (EntityPtr &ent : ents_) {
         for (AutonomyPtr &autonomy : ent->autonomies()) {
             if (autonomy->need_reset()) {
                 std::string type = autonomy->type();
                 auto it = autonomy_map.find(type);
                 if (it == autonomy_map.end()) {
                     contacts_mutex_.lock();
                     autonomy->set_contacts(contacts_);
                     contacts_mutex_.unlock();
                     autonomy_map[type] = autonomy;
                 } else {
                     contacts_mutex_.lock();
                     autonomy->set_contacts_from_plugin(it->second);
                     contacts_mutex_.unlock();
                 }
             }
         }
     }
 }
void scrimmage::SimControl::run_dynamics () protected
bool scrimmage::SimControl::run_interaction_detection () protected
Definition at line 457 of file SimControl.cpp.
References contacts_, dt_, ent_inters_, ents_, pub_ent_rm_, scrimmage::run_callbacks(), shapes_, t(), and t_.
Referenced by run_single_step(), and start().
{
     auto run_interaction = [&](auto ent_inter) {
         bool result = ent_inter->step_entity_interaction(ents_, t_, dt_);
         if (!result && ent_inter->print_err_on_exit) {
             cout << "Entity interaction requested simulation termination: "
                  << ent_inter->name() << endl;
         }
         return result;
     };
     auto handle_shapes = [&](auto ent_inter) {
         shapes_[0].insert(shapes_[0].end(), ent_inter->shapes().begin(),
                           ent_inter->shapes().end());
         ent_inter->shapes().clear();
     };
     br::for_each(ent_inters_, run_callbacks);
     bool success = std::all_of(ent_inters_.begin(), ent_inters_.end(), run_interaction);
     br::for_each(ent_inters_, handle_shapes);
     // Determine if entities need to be removed
     for (auto &ent : ents_) {
         if (!ent->is_alive() && ent->posthumous(this->t())) {
             int id = ent->id().id();
             auto msg = std::make_shared<Message<sm::EntityRemoved>>();
             msg->data.set_entity_id(id);
             pub_ent_rm_->publish(msg);
             // Set the entity and contact to inactive to remove from
             // simulation
             ent->set_active(false);
             auto it_cnt = contacts_->find(id);
             if (it_cnt != contacts_->end()) {
                 it_cnt->second.set_active(false);
             } else {
                 cout << "Failed to find contact to set inactive." << endl;
             }
         }
     }
     return success;
 }
bool scrimmage::SimControl::run_logging () protected
Definition at line 507 of file SimControl.cpp.
References contacts_, contacts_mutex_, scrimmage::create_frame(), dt_, log_, outgoing_interface_, and t_.
Referenced by finalize(), and run_single_step().
{
     contacts_mutex_.lock();
     std::shared_ptr<scrimmage_proto::Frame> frame =
         create_frame(t_ + dt_, contacts_);
     outgoing_interface_->send_frame(frame);
     log_->save_frame(frame);
     contacts_mutex_.unlock();
     return true;
 }
bool scrimmage::SimControl::run_metrics () protected
Definition at line 501 of file SimControl.cpp.
References dt_, metrics_, scrimmage::run_callbacks(), and t_.
Referenced by run_single_step().
{
     br::for_each(metrics_, run_callbacks);
     auto run_metric = [&](auto &metric) {return metric->step_metrics(t_, dt_);};
     return std::all_of(metrics_.begin(), metrics_.end(), run_metric);
 }
void scrimmage::SimControl::run_remove_inactive () protected
Definition at line 520 of file SimControl.cpp.
References contacts_, contacts_mutex_, ents_, id_to_ent_map_, and t().
Referenced by run_single_step().
{
     auto it = ents_.begin();
     while (it != ents_.end()) {
         if (!(*it)->active()) {
             int id = (*it)->id().id();
             (*it)->close(t());
             it = ents_.erase(it);
             contacts_mutex_.lock();
             contacts_->erase(id);
             contacts_mutex_.unlock();
             // Remove the entity from the ID to entity map. Don't remove the
             // entity from the id_to_team_map.
             auto it_id_ent = id_to_ent_map_->find(id);
             if (it_id_ent == id_to_ent_map_->end()) {
                 cout << "WARNING: Failed to remove entity ID ("
                      << id << ") from id_to_ent_map" << endl;
             } else {
                 id_to_ent_map_->erase(it_id_ent);
             }
         } else {
             ++it;
         }
     }
 }
void scrimmage::SimControl::run_check_network_msgs () protected
Definition at line 1201 of file SimControl.cpp.
References dec_warp(), force_exit(), inc_warp(), incoming_interface_, outgoing_interface_, pause(), paused(), prev_paused_, pub_custom_key_, pub_world_point_clicked_, send_shutdown_msg_, and single_step().
Referenced by run_single_step().
{
     // Do we have any simcontrol message updates from GUI?
     if (incoming_interface_->gui_msg_update()) {
         incoming_interface_->gui_msg_mutex.lock();
         auto &control = incoming_interface_->gui_msg();
         auto it = control.begin();
         while (it != control.end()) {
             if (it->inc_warp()) {
                 this->inc_warp();
             } else if (it->dec_warp()) {
                 this->dec_warp();
             } else if (it->toggle_pause()) {
                 this->pause(!this->paused());
                 prev_paused_ = paused();
             } else if (it->single_step()) {
                 this->single_step(true);
             } else if (it->shutting_down()) {
                 send_shutdown_msg_ = false;
                 this->force_exit();
             } else if (it->request_cached()) {
                 outgoing_interface_->send_cached();
             } else if (it->custom_key() != "") {
                 auto msg = std::make_shared<Message<std::string>>();
                 std::string key(it->custom_key());
                 msg->data = key;
                 pub_custom_key_->publish(msg);
             }
             control.erase(it++);
         }
         incoming_interface_->gui_msg_mutex.unlock();
     }
     if (incoming_interface_->world_point_clicked_msg_update()) {
         incoming_interface_->world_point_clicked_msg_mutex.lock();
         auto &msg_list = incoming_interface_->world_point_clicked_msg();
         auto it = msg_list.begin();
         while (it != msg_list.end()) {
             auto msg = std::make_shared<Message<sp::WorldPointClicked>>();
             msg->data = *it;
             pub_world_point_clicked_->publish(msg);
             msg_list.erase(it++);
         }
         incoming_interface_->world_point_clicked_msg_mutex.unlock();
     }
 }
void scrimmage::SimControl::run_send_contact_visuals () protected
Definition at line 1612 of file SimControl.cpp.
References ents_, log_, and outgoing_interface_.
Referenced by run_single_step().
{
     for (EntityPtr &ent : ents_) {
         if (ent->visual_changed()) {
             outgoing_interface_->send_contact_visual(ent->contact_visual());
             log_->save_contact_visual(ent->contact_visual());
             ent->set_visual_changed(false);
         }
     }
 }
bool scrimmage::SimControl::run_networks () protected
Definition at line 439 of file SimControl.cpp.
References networks_, pubsub_, and shapes_.
Referenced by run_single_step().
{
     bool all_true = true;
     for (auto &kv : *networks_) {
         bool result = kv.second->step(pubsub_->pubs()[kv.second->name()],
                                       pubsub_->subs()[kv.second->name()]);
         if (!result && kv.second->print_err_on_exit) {
             cout << "Network requested simulation termination: "
                  << kv.second->name() << endl;
         }
         all_true &= result;
         shapes_[0].insert(shapes_[0].end(), kv.second->shapes().begin(),
                           kv.second->shapes().end());
         kv.second->shapes().clear();
     }
     return all_true;
 }
bool scrimmage::SimControl::take_step () private
Definition at line 1188 of file SimControl.cpp.
References take_step_, and take_step_mutex_.
{
     take_step_mutex_.lock();
     bool value = take_step_;
     take_step_mutex_.unlock();
     return value;
 }
void scrimmage::SimControl::single_step (const bool & value) private
Definition at line 1366 of file SimControl.cpp.
References single_step_, and single_step_mutex_.
{
     single_step_mutex_.lock();
     single_step_ = value;
     single_step_mutex_.unlock();
 }
bool scrimmage::SimControl::single_step () private
Definition at line 1372 of file SimControl.cpp.
References single_step_, and single_step_mutex_.
Referenced by run_check_network_msgs(), run_single_step(), and SimControl().
{
     single_step_mutex_.lock();
     bool value = single_step_;
     single_step_mutex_.unlock();
     return value;
 }
void scrimmage::SimControl::set_finished (bool finished) private
Definition at line 1258 of file SimControl.cpp.
References actual_time_warp(), finished_, finished_mutex_, outgoing_interface_, send_shutdown_msg_, t(), and time_warp().
Referenced by finalize().
{
     scrimmage_proto::SimInfo info;
     info.set_time(this->t());
     info.set_desired_warp(this->time_warp());
     info.set_actual_warp(this->actual_time_warp());
     info.set_shutting_down(true);
     if (send_shutdown_msg_) {
         outgoing_interface_->send_sim_info(info);
     }
     finished_mutex_.lock();
     finished_ = finished;
     finished_mutex_.unlock();
 }
bool scrimmage::SimControl::output_summary () private
Definition at line 1654 of file SimControl.cpp.
References scrimmage::generate_chars(), metrics(), metrics_, and mp_.
Referenced by finalize().
{
     std::map<int, double> team_scores;
     std::map<int, std::map<std::string, double>> team_metrics;
     std::list<std::string> headers;
     bool metrics_empty = true;
     // Loop through each of the metrics plugins.
     for (auto metrics : metrics_) {
         if (metrics->get_print_team_summary()) {
             cout << sc::generate_chars("=", 80) << endl;
             cout << metrics->name() << endl;
             cout << sc::generate_chars("=", 80) << endl;
             metrics->calc_team_scores();
             metrics->print_team_summaries();
         }
         // Add all elements from individual metrics plugin to overall
         // metrics data structure
         for (auto const &team_str_double : metrics->team_metrics()) {
             team_metrics[team_str_double.first].insert(team_str_double.second.begin(),
                                                        team_str_double.second.end());
             metrics_empty = false;
         }
         // Calculate aggregated team scores:
         for (auto const &team_score : metrics->team_scores()) {
             if (team_scores.count(team_score.first) == 0) {
                 team_scores[team_score.first] = 0;
             }
             team_scores[team_score.first] += team_score.second;
         }
         // Create list of all csv headers
         headers.insert(headers.end(), metrics->headers().begin(),
                        metrics->headers().end());
     }
     // Create headers string
     std::string csv_str = "team_id,score";
     for (std::string header : headers) {
         csv_str += "," + header;
     }
     csv_str += "\n";
     // Loop over each team and generate csv output
     for (auto const &team_str_double : team_metrics) {
         // Each line starts with team_id,score
         csv_str += std::to_string(team_str_double.first);
         csv_str += "," + std::to_string(team_scores[team_str_double.first]);
         // Loop over all possible headers, if the header doesn't exist for
         // a specific team, default the value for that header to zero.
         for (std::string header : headers) {
             csv_str += ",";
             auto it = team_str_double.second.find(header);
             if (it != team_str_double.second.end()) {
                 csv_str += std::to_string(it->second);
             } else {
                 csv_str += std::to_string(0.0);
             }
         }
         csv_str += "\n";
     }
     // Write CSV string to file
     std::string out_file = mp_->log_dir() + "/summary.csv";
     std::ofstream summary_file(out_file);
     if (!summary_file.is_open()) {
         std::cout << "could not open " << out_file
                   << " for writing metrics" << std::endl;
         return false;
     }
     summary_file << csv_str << std::flush;
     summary_file.close();
     // Print Overall Scores
     if (!metrics_empty) {
         cout << sc::generate_chars("=", 80) << endl;
         cout << "Overall Scores" << endl;
         cout << sc::generate_chars("=", 80) << endl;
         for (auto const &team_score : team_scores) {
             cout << "Team ID: " << team_score.first << endl;
             cout << "Score: " << team_score.second << endl;
             cout << sc::generate_chars("-", 80) << endl;
         }
     }
     return true;
 }
bool scrimmage::SimControl::output_runtime () private
Definition at line 1622 of file SimControl.cpp.
References scrimmage::Timer::elapsed_time(), mp_, t(), time_, and timer_.
Referenced by finalize().
{
     std::ofstream runtime_file(mp_->log_dir() + "/runtime_seconds.txt");
     if (!runtime_file.is_open()) return false;
     double t = timer_.elapsed_time().total_milliseconds() / 1000.0;
     double sim_t = time_->t();
     runtime_file << "wall: " << t << std::endl;
     runtime_file << "sim: " << sim_t << std::endl;
     runtime_file.close();
     return true;
 }
bool scrimmage::SimControl::output_git_summary () private
Definition at line 1634 of file SimControl.cpp.
References scrimmage::get_version(), log_, and plugin_manager_.
Referenced by finalize().
{
     std::map<std::string, std::unordered_set<std::string>> commits =
             plugin_manager_->get_commits();
     std::string scrimmage_version = get_version();
     if (scrimmage_version != "") {
         commits[scrimmage_version].insert("scrimmage");
     }
     for (auto &kv : commits) {
         std::string output = kv.first + ":";
         for (const std::string &plugin_name : kv.second) {
             output += plugin_name + ",";
         }
         output.pop_back();
         log_->write_ascii(output);
     }
     return true;
 }
void scrimmage::SimControl::setup_timer (double rate, double time_warp) private
Definition at line 1339 of file SimControl.cpp.
References scrimmage::Timer::set_iterate_rate(), scrimmage::Timer::set_time_warp(), timer_, timer_mutex_, and scrimmage::Timer::update_time_config().
Referenced by start().
{
     // dt_ is a period, 1 / dt_ is a rate (Hz)
     timer_mutex_.lock();
     timer_.set_iterate_rate(rate);
     timer_.set_time_warp(time_warp);
     timer_.update_time_config();
     timer_mutex_.unlock();
 }
void scrimmage::SimControl::start_overall_timer () private
Definition at line 1348 of file SimControl.cpp.
References scrimmage::Timer::start_overall_timer(), timer_, and timer_mutex_.
Referenced by start().
{
     timer_mutex_.lock();
     timer_.start_overall_timer();
     timer_mutex_.unlock();
 }
void scrimmage::SimControl::start_loop_timer () private
Definition at line 1354 of file SimControl.cpp.
References scrimmage::Timer::start_loop_timer(), timer_, and timer_mutex_.
Referenced by run_single_step().
{
     timer_mutex_.lock();
     timer_.start_loop_timer();
     timer_mutex_.unlock();
 }
void scrimmage::SimControl::loop_wait () private
Definition at line 1360 of file SimControl.cpp.
References scrimmage::Timer::loop_wait(), timer_, and timer_mutex_.
Referenced by run_single_step().
{
     timer_mutex_.lock();
     timer_.loop_wait();
     timer_mutex_.unlock();
 }
void scrimmage::SimControl::inc_warp () private
Definition at line 1288 of file SimControl.cpp.
References scrimmage::Timer::inc_warp(), timer_, and timer_mutex_.
Referenced by run_check_network_msgs().
{
     timer_mutex_.lock();
     timer_.inc_warp();
     timer_mutex_.unlock();
 }
void scrimmage::SimControl::dec_warp () private
Definition at line 1294 of file SimControl.cpp.
References scrimmage::Timer::dec_warp(), timer_, and timer_mutex_.
Referenced by run_check_network_msgs().
{
     timer_mutex_.lock();
     timer_.dec_warp();
     timer_mutex_.unlock();
 }
bool scrimmage::SimControl::wait_for_ready () private
Definition at line 1112 of file SimControl.cpp.
References exit_, exit_mutex_, and not_ready_.
Referenced by run_single_step().
{
     // Wait for all entities to be ready
     int not_ready_loop = 0;
     while (!not_ready_.empty()) {
         for (std::list<EntityPtr>::iterator it = not_ready_.begin();
              it != not_ready_.end(); /* No increment */) {
             if ((*it)->ready()) {
                 // Remove references to entities that are ready
                 it = not_ready_.erase(it);
             } else {
                 ++it;
             }
         }
         // Check to see if we were told to exit
         exit_mutex_.lock();
         bool exit = exit_;
         exit_mutex_.unlock();
         if (exit) {
             cout << "Simulation ended waiting for entity to be ready" << endl;
             return false;
         }
         // Give other possible threads (MOOS, ROS, etc) a chance to
         // run.
         if (!not_ready_.empty()) {
             boost::this_thread::sleep_for(boost::chrono::milliseconds(10));
         }
         if (not_ready_loop > 1e4) {
             cout << "Warning: Entities taking a long time to be ready" << endl;
             not_ready_loop = 0;
         }
         not_ready_loop++;
     }
     return true;
 }
bool scrimmage::SimControl::check_output (const std::string & output_type, const std::string & desired_output) private
bool scrimmage::SimControl::setup_logging () private
Definition at line 146 of file SimControl.cpp.
References limited_verbosity_, log_, mp_, scrimmage::Log::NONE, and scrimmage::Log::WRITE.
Referenced by start().
{
     limited_verbosity_ = mp_->output_required();
     // Setup the log directory if it is required
     if (mp_->output_required()) {
         mp_->create_log_dir();
         log_->set_enable_log(true);
         log_->init(mp_->log_dir(), Log::WRITE);
     } else {
         log_->set_enable_log(false);
         log_->init(mp_->log_dir(), Log::NONE);
     }
     return true;
 }
bool scrimmage::SimControl::logging_logic (const std::string & s) private
void scrimmage::SimControl::end_of_simulation () private
void scrimmage::SimControl::cleanup () private
bool scrimmage::SimControl::finalize () private
Definition at line 983 of file SimControl.cpp.
References display_progress_, dt_, entity_pool_condition_var_, entity_pool_stop_, entity_thread_types_, entity_worker_threads_, ents_, finalized_called_, limited_verbosity_, log_, mp_, output_git_summary(), output_runtime(), output_summary(), pub_ent_pres_end_, run_logging(), set_finished(), set_time(), and t().
Referenced by run(), and shutdown().
{
     // Finalize can only be called once per instance
     if (finalized_called_) {
         return true;
     }
     finalized_called_ = true;
     if (!entity_thread_types_.empty()) {
         entity_pool_stop_ = true;
         entity_pool_condition_var_.notify_all();
         for (std::thread &t : entity_worker_threads_) {
             t.join();
         }
     }
     // account for last step
     set_time(t() - dt_);
     // Save EntityPresentAtEnd messages
     for (EntityPtr &ent : ents_) {
         auto msg = std::make_shared<Message<sm::EntityPresentAtEnd>>();
         msg->data.set_entity_id(ent->id().id());
         pub_ent_pres_end_->publish(msg);
     }
     run_logging();
     if (display_progress_) cout << endl;
     // Tell the visualizers that the simulation is complete
     set_finished(true);
     if (mp_->output_required()) {
         output_runtime();
     }
     if (mp_->output_type_required("summary")) {
         if (not output_summary()) {
             cout << "Failed to write Metrics summary" << endl;
         }
     }
     if (mp_->output_type_required("git_commits")) {
         output_git_summary();
     }
     // Close the log file
     log_->close_log();
     if (not limited_verbosity_) {
         cout << "Simulation Complete" << endl;
     }
     return true;
 }
bool scrimmage::SimControl::reset_pointers () private
Definition at line 1073 of file SimControl.cpp.
References contact_visuals_, contacts_, ent_inters_, entity_pool_queue_, ents_, file_search_, id_to_ent_map_, incoming_interface_, log_, metrics_, mp_, networks_, not_ready_, outgoing_interface_, plugin_manager_, proj_, pub_custom_key_, pub_end_time_, pub_ent_gen_, pub_ent_int_exit_, pub_ent_pres_end_, pub_ent_rm_, pub_no_teams_, pub_one_team_, pub_world_point_clicked_, pubsub_, random_, rtree_, shapes_, sim_plugin_, t(), and time_.
Referenced by shutdown().
{
     id_to_ent_map_ = nullptr;
     incoming_interface_ = nullptr;
     outgoing_interface_ = nullptr;
     mp_ = nullptr;
     ents_.clear();
     contacts_ = nullptr;
     shapes_.clear();
     contact_visuals_.clear();
     time_ = nullptr;
     entity_pool_queue_.clear();
     log_ = nullptr;
     random_ = nullptr;
     plugin_manager_ = nullptr;
     proj_ = nullptr;
     ent_inters_.clear();
     metrics_.clear();
     networks_->clear();
     pubsub_->pubs().clear();
     pubsub_->subs().clear();
     pubsub_ = nullptr;
     file_search_ = nullptr;
     rtree_ = nullptr;
     sim_plugin_->close_plugin(t());
     pub_end_time_ = nullptr;
     pub_ent_gen_ = nullptr;
     pub_ent_rm_ = nullptr;
     pub_ent_pres_end_ = nullptr;
     pub_ent_int_exit_ = nullptr;
     pub_no_teams_ = nullptr;
     pub_one_team_ = nullptr;
     pub_world_point_clicked_ = nullptr;
     pub_custom_key_ = nullptr;
     not_ready_.clear();
     return true;
 }
int scrimmage::SimControl::find_available_id (const std::map< std::string, std::string > & params) private
Definition at line 1767 of file SimControl.cpp.
References ids_used_.
Referenced by generate_entity().
{
     // Use the mission file specified ID, if it exists, otherwise, find the
     // next available ID from the back of the ids_used_ std::set.
     int id = 0;
     auto it_id = params.find("id");
     if (it_id != params.end()) {
         try {
             id = std::stoi(it_id->second);
         } catch (...) {
             cout << "Failed to convert the following <id> tag into an integer: "
                  << it_id->second << endl;
             id = 0;
         }
     }
     std::pair<std::set<int>::const_iterator, bool> ret;
     do {
         ret = ids_used_.emplace(id);
         if (not ret.second) {
             id = *(ids_used_.rbegin()) + 1;
         }
     } while (not ret.second);
     return id;
 }
Member Data Documentation
std::shared_ptr<std::unordered_map<int, int> > scrimmage::SimControl::id_to_team_map_ protected
Definition at line 324 of file SimControl.h.
Referenced by generate_entity(), and start().
std::shared_ptr<std::unordered_map<int, EntityPtr> > scrimmage::SimControl::id_to_ent_map_ protected
Definition at line 325 of file SimControl.h.
Referenced by generate_entity(), id_to_entity_map(), reset_pointers(), run_remove_inactive(), and start().
InterfacePtr scrimmage::SimControl::incoming_interface_ protected
Definition at line 327 of file SimControl.h.
Referenced by incoming_interface(), reset_pointers(), run_check_network_msgs(), set_incoming_interface(), and start().
InterfacePtr scrimmage::SimControl::outgoing_interface_ protected
Definition at line 328 of file SimControl.h.
Referenced by generate_entity(), outgoing_interface(), request_screenshot(), reset_pointers(), run_check_network_msgs(), run_logging(), run_send_contact_visuals(), run_send_shapes(), run_single_step(), send_terrain(), set_finished(), set_outgoing_interface(), and start().
std::thread scrimmage::SimControl::network_thread_ protected
Definition at line 330 of file SimControl.h.
Referenced by start().
MissionParsePtr scrimmage::SimControl::mp_ protected
Definition at line 332 of file SimControl.h.
Referenced by enable_gui(), end_condition_reached(), finalize(), generate_entities(), generate_entity(), init(), mp(), output_runtime(), output_summary(), reset_pointers(), run_entities(), send_terrain(), setup_logging(), and start().
std::list<EntityPtr> scrimmage::SimControl::ents_ protected
Definition at line 334 of file SimControl.h.
Referenced by add_tasks(), collision_exists(), create_rtree(), end_condition_reached(), ents(), finalize(), generate_entity(), init(), reset_pointers(), run_entities(), run_interaction_detection(), run_remove_inactive(), run_send_contact_visuals(), run_sensors(), set_autonomy_contacts(), and shutdown().
ContactMapPtr scrimmage::SimControl::contacts_ protected
Definition at line 336 of file SimControl.h.
Referenced by generate_entity(), get_contacts(), init(), reset_pointers(), run_interaction_detection(), run_logging(), run_remove_inactive(), set_autonomy_contacts(), SimControl(), and start().
std::map<int, std::list<scrimmage_proto::ShapePtr> > scrimmage::SimControl::shapes_ protected
Definition at line 338 of file SimControl.h.
Referenced by init(), reset_pointers(), run_entities(), run_interaction_detection(), run_networks(), run_send_shapes(), run_sensors(), and start().
std::map<int, ContactVisualPtr> scrimmage::SimControl::contact_visuals_ protected
Definition at line 340 of file SimControl.h.
Referenced by generate_entity(), get_contact_visuals(), init(), and reset_pointers().
std::thread scrimmage::SimControl::thread_ protected
Definition at line 342 of file SimControl.h.
Referenced by join(), and run_threaded().
bool scrimmage::SimControl::display_progress_ = false protected
Definition at line 343 of file SimControl.h.
Referenced by display_progress(), finalize(), run_single_step(), and start().
std::string scrimmage::SimControl::jsbsim_root_ protected
Definition at line 345 of file SimControl.h.
Referenced by generate_entity(), and init().
TimePtr scrimmage::SimControl::time_ protected
Definition at line 347 of file SimControl.h.
Referenced by generate_entity(), output_runtime(), reset_pointers(), set_time(), and start().
ParameterServerPtr scrimmage::SimControl::param_server_ protected
Definition at line 348 of file SimControl.h.
Referenced by generate_entity(), and start().
GlobalServicePtr scrimmage::SimControl::global_services_ protected
Definition at line 349 of file SimControl.h.
Referenced by generate_entity(), and start().
double scrimmage::SimControl::t0_ = 0 protected
Definition at line 351 of file SimControl.h.
Referenced by start().
double scrimmage::SimControl::tend_ = 0 protected
Definition at line 352 of file SimControl.h.
Referenced by run_single_step(), and start().
double scrimmage::SimControl::dt_ = 0 protected
Definition at line 353 of file SimControl.h.
Referenced by end_condition_reached(), finalize(), generate_entity(), request_screenshot(), run_entities(), run_interaction_detection(), run_logging(), run_metrics(), run_sensors(), run_single_step(), and start().
double scrimmage::SimControl::t_ = 0 protected
Definition at line 354 of file SimControl.h.
Referenced by request_screenshot(), run_entities(), run_interaction_detection(), run_logging(), run_metrics(), run_sensors(), run_single_step(), set_time(), start(), and t().
bool scrimmage::SimControl::paused_ protected
Definition at line 355 of file SimControl.h.
Referenced by pause(), paused(), and run_single_step().
bool scrimmage::SimControl::single_step_ protected
Definition at line 356 of file SimControl.h.
Referenced by single_step().
bool scrimmage::SimControl::take_step_ = false protected
Definition at line 358 of file SimControl.h.
Referenced by run_single_step(), and take_step().
Timer scrimmage::SimControl::timer_ protected
Definition at line 360 of file SimControl.h.
Referenced by dec_warp(), inc_warp(), loop_wait(), output_runtime(), setup_timer(), start_loop_timer(), start_overall_timer(), time_warp(), and timer().
bool scrimmage::SimControl::finished_ = false protected
Definition at line 362 of file SimControl.h.
Referenced by set_finished().
bool scrimmage::SimControl::exit_ = false protected
Definition at line 363 of file SimControl.h.
Referenced by force_exit(), generate_entity(), run_single_step(), and wait_for_ready().
std::mutex scrimmage::SimControl::finished_mutex_ protected
Definition at line 365 of file SimControl.h.
Referenced by set_finished().
std::mutex scrimmage::SimControl::contacts_mutex_ protected
Definition at line 366 of file SimControl.h.
Referenced by generate_entity(), get_contacts(), run_entities(), run_logging(), run_remove_inactive(), set_autonomy_contacts(), SimControl(), and start().
std::mutex scrimmage::SimControl::exit_mutex_ protected
Definition at line 367 of file SimControl.h.
Referenced by force_exit(), run_single_step(), and wait_for_ready().
std::mutex scrimmage::SimControl::timer_mutex_ protected
Definition at line 368 of file SimControl.h.
Referenced by dec_warp(), inc_warp(), loop_wait(), setup_timer(), start_loop_timer(), start_overall_timer(), and time_warp().
std::mutex scrimmage::SimControl::paused_mutex_ protected
Definition at line 369 of file SimControl.h.
Referenced by pause(), and paused().
std::mutex scrimmage::SimControl::single_step_mutex_ protected
Definition at line 370 of file SimControl.h.
Referenced by single_step().
std::mutex scrimmage::SimControl::take_step_mutex_ protected
Definition at line 371 of file SimControl.h.
Referenced by run_single_step(), and take_step().
std::mutex scrimmage::SimControl::time_mutex_ protected
Definition at line 372 of file SimControl.h.
Referenced by set_time(), and t().
std::mutex scrimmage::SimControl::time_warp_mutex_ protected
Definition at line 373 of file SimControl.h.
std::mutex scrimmage::SimControl::entity_pool_mutex_ protected
Definition at line 374 of file SimControl.h.
Referenced by add_tasks(), and worker().
std::set<Task::Type> scrimmage::SimControl::entity_thread_types_ protected
Definition at line 376 of file SimControl.h.
Referenced by finalize(), run_entities(), run_sensors(), and start().
int scrimmage::SimControl::num_entity_threads_ = 0 protected
Definition at line 377 of file SimControl.h.
Referenced by start().
bool scrimmage::SimControl::entity_pool_stop_ = false protected
Definition at line 378 of file SimControl.h.
Referenced by finalize(), start(), and worker().
std::deque<std::shared_ptr<Task> > scrimmage::SimControl::entity_pool_queue_ protected
Definition at line 379 of file SimControl.h.
Referenced by add_tasks(), reset_pointers(), and worker().
std::condition_variable_any scrimmage::SimControl::entity_pool_condition_var_ protected
Definition at line 380 of file SimControl.h.
Referenced by add_tasks(), finalize(), and worker().
std::vector<std::thread> scrimmage::SimControl::entity_worker_threads_ protected
Definition at line 381 of file SimControl.h.
Referenced by finalize(), and start().
std::shared_ptr<Log> scrimmage::SimControl::log_ protected
Definition at line 391 of file SimControl.h.
Referenced by finalize(), generate_entity(), output_git_summary(), reset_pointers(), run_logging(), run_send_contact_visuals(), run_send_shapes(), send_terrain(), setup_logging(), and start().
std::set<EndConditionFlags> scrimmage::SimControl::end_conditions_ = {EndConditionFlags::NONE} protected
Definition at line 393 of file SimControl.h.
Referenced by end_condition_reached(), and start().
RandomPtr scrimmage::SimControl::random_ protected
Definition at line 395 of file SimControl.h.
Referenced by generate_entities(), generate_entity(), reset_pointers(), and start().
PluginManagerPtr scrimmage::SimControl::plugin_manager_ protected
Definition at line 397 of file SimControl.h.
Referenced by generate_entity(), output_git_summary(), plugin_manager(), reset_pointers(), and start().
std::shared_ptr<GeographicLib::LocalCartesian> scrimmage::SimControl::proj_ protected
Definition at line 401 of file SimControl.h.
Referenced by generate_entity(), reset_pointers(), and start().
std::list<EntityInteractionPtr> scrimmage::SimControl::ent_inters_ protected
Definition at line 403 of file SimControl.h.
Referenced by collision_exists(), init(), reset_pointers(), run_interaction_detection(), shutdown(), and start().
std::list<MetricsPtr> scrimmage::SimControl::metrics_ protected
Definition at line 404 of file SimControl.h.
Referenced by init(), metrics(), output_summary(), reset_pointers(), run_metrics(), and start().
NetworkMapPtr scrimmage::SimControl::networks_ protected
Definition at line 405 of file SimControl.h.
Referenced by init(), reset_pointers(), run_networks(), shutdown(), and start().
PubSubPtr scrimmage::SimControl::pubsub_ protected
Definition at line 406 of file SimControl.h.
Referenced by generate_entity(), init(), reset_pointers(), run_networks(), and start().
std::set<int> scrimmage::SimControl::ids_used_ = {0} protected
Definition at line 408 of file SimControl.h.
Referenced by find_available_id().
FileSearchPtr scrimmage::SimControl::file_search_ protected
Definition at line 409 of file SimControl.h.
Referenced by file_search(), generate_entity(), reset_pointers(), and start().
RTreePtr scrimmage::SimControl::rtree_ protected
Definition at line 410 of file SimControl.h.
Referenced by create_rtree(), generate_entity(), reset_pointers(), and start().
bool scrimmage::SimControl::send_shutdown_msg_ = true protected
Definition at line 425 of file SimControl.h.
Referenced by run_check_network_msgs(), and set_finished().
EntityPluginPtr scrimmage::SimControl::sim_plugin_ protected
Definition at line 427 of file SimControl.h.
Referenced by plugin(), reset_pointers(), run_single_step(), and start().
PublisherPtr scrimmage::SimControl::pub_end_time_ protected
Definition at line 428 of file SimControl.h.
Referenced by end_condition_reached(), reset_pointers(), and start().
PublisherPtr scrimmage::SimControl::pub_ent_gen_ protected
Definition at line 429 of file SimControl.h.
Referenced by generate_entity(), reset_pointers(), and start().
PublisherPtr scrimmage::SimControl::pub_ent_rm_ protected
Definition at line 430 of file SimControl.h.
Referenced by reset_pointers(), run_interaction_detection(), and start().
PublisherPtr scrimmage::SimControl::pub_ent_pres_end_ protected
Definition at line 431 of file SimControl.h.
Referenced by finalize(), reset_pointers(), and start().
PublisherPtr scrimmage::SimControl::pub_ent_int_exit_ protected
Definition at line 432 of file SimControl.h.
Referenced by reset_pointers(), run_single_step(), and start().
PublisherPtr scrimmage::SimControl::pub_no_teams_ protected
Definition at line 433 of file SimControl.h.
Referenced by end_condition_reached(), reset_pointers(), and start().
PublisherPtr scrimmage::SimControl::pub_one_team_ protected
Definition at line 434 of file SimControl.h.
Referenced by end_condition_reached(), reset_pointers(), and start().
PublisherPtr scrimmage::SimControl::pub_world_point_clicked_ protected
Definition at line 435 of file SimControl.h.
Referenced by reset_pointers(), run_check_network_msgs(), and start().
PublisherPtr scrimmage::SimControl::pub_custom_key_ protected
Definition at line 436 of file SimControl.h.
Referenced by reset_pointers(), run_check_network_msgs(), and start().
std::list<EntityPtr> scrimmage::SimControl::not_ready_ protected
Definition at line 438 of file SimControl.h.
Referenced by generate_entity(), reset_pointers(), and wait_for_ready().
DelayedTask scrimmage::SimControl::screenshot_task_ protected
Definition at line 439 of file SimControl.h.
Referenced by run_single_step(), and start().
bool scrimmage::SimControl::prev_paused_ protected
Definition at line 440 of file SimControl.h.
Referenced by request_screenshot(), run_check_network_msgs(), run_single_step(), SimControl(), and start().
DelayedTask scrimmage::SimControl::reseed_task_ protected
Definition at line 442 of file SimControl.h.
Referenced by run_single_step(), and start().
bool scrimmage::SimControl::limited_verbosity_ protected
Definition at line 443 of file SimControl.h.
Referenced by finalize(), run_single_step(), and setup_logging().
bool scrimmage::SimControl::finalized_called_ = false private
Definition at line 471 of file SimControl.h.
Referenced by finalize().
bool scrimmage::SimControl::running_in_thread_ = false private
Definition at line 472 of file SimControl.h.
Referenced by run_threaded(), and shutdown().
bool scrimmage::SimControl::python_enabled_ = false private
Definition at line 474 of file SimControl.h.
Referenced by init(), shutdown(), and start().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/simcontrol/SimControl.h
/root/scrimmage/scrimmage/src/simcontrol/SimControl.cpp