SCRIMMAGE: scrimmage::autonomy::TrajectoryPoint Class Reference
scrimmage::autonomy::TrajectoryPoint Class Reference
#include <TrajectoryPoint.h>
Public Member Functions
TrajectoryPoint ()
TrajectoryPoint (double t, scrimmage::State &state, scrimmage::State &desired)
double t ()
scrimmage::State & state ()
scrimmage::State & desired_state ()
void set_t (double t)
void set_state (scrimmage::State &state)
void set_desired_state (scrimmage::State &state)
Protected Attributes
double t_
scrimmage::State state_
scrimmage::State desired_state_
Detailed Description
Definition at line 41 of file TrajectoryPoint.h.
Constructor & Destructor Documentation
TrajectoryPoint() [1/2]
scrimmage::autonomy::TrajectoryPoint::TrajectoryPoint () inline
Definition at line 43 of file TrajectoryPoint.h.
 : t_(0) {}
TrajectoryPoint() [2/2]
scrimmage::autonomy::TrajectoryPoint::TrajectoryPoint (double t, scrimmage::State & state, scrimmage::State & desired) inline
Definition at line 44 of file TrajectoryPoint.h.
         : t_(t), state_(state), desired_state_(desired) { }
Member Function Documentation
t()
double scrimmage::autonomy::TrajectoryPoint::t () inline
Definition at line 47 of file TrajectoryPoint.h.
 { return t_; }
References t_.
Referenced by set_t().
state()
scrimmage::State& scrimmage::autonomy::TrajectoryPoint::state () inline
Definition at line 48 of file TrajectoryPoint.h.
 { return state_; }
References state_.
Referenced by set_desired_state(), and set_state().
desired_state()
scrimmage::State& scrimmage::autonomy::TrajectoryPoint::desired_state () inline
Definition at line 49 of file TrajectoryPoint.h.
 { return desired_state_; }
References desired_state_.
set_t()
void scrimmage::autonomy::TrajectoryPoint::set_t (double t) inline
Definition at line 51 of file TrajectoryPoint.h.
 { t_ = t; }
References t(), and t_.
set_state()
void scrimmage::autonomy::TrajectoryPoint::set_state (scrimmage::State & state) inline
Definition at line 52 of file TrajectoryPoint.h.
 { state_ = state; }
References state(), and state_.
set_desired_state()
void scrimmage::autonomy::TrajectoryPoint::set_desired_state (scrimmage::State & state) inline
Definition at line 53 of file TrajectoryPoint.h.
 { desired_state_ = state; }
References desired_state_, and state().
Member Data Documentation
t_
double scrimmage::autonomy::TrajectoryPoint::t_ protected
Definition at line 56 of file TrajectoryPoint.h.
Referenced by set_t(), and t().
state_
scrimmage::State scrimmage::autonomy::TrajectoryPoint::state_ protected
Definition at line 57 of file TrajectoryPoint.h.
Referenced by set_state(), and state().
desired_state_
scrimmage::State scrimmage::autonomy::TrajectoryPoint::desired_state_ protected
Definition at line 58 of file TrajectoryPoint.h.
Referenced by desired_state(), and set_desired_state().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/autonomy/TrajectoryRecordPlayback/TrajectoryPoint.h