SCRIMMAGE: scrimmage::Print Class Reference
scrimmage::Print Class Reference
#include <Print.h>
Public Member Functions
Print ()
void init (TimePtr &time, std::string log_dir)
void init (TimePtr &time, std::string log_dir, PrintEnums::WRITE_TO flag)
void close ()
void flush ()
void printDev (PrintData &data, std::string outmessage)
void printInfo (PrintData &data, std::string outmessage)
void printWarning (PrintData &data, std::string outmessage)
void printError (PrintData &data, std::string outmessage)
void printDev (EntityPlugin &caller, std::string outmessage)
void printInfo (EntityPlugin &caller, std::string outmessage)
void printWarning (EntityPlugin &caller, std::string outmessage)
void printError (EntityPlugin &caller, std::string outmessage)
Protected Member Functions
void print (std::ostream &stream, PrintEnums::WARN_LEVEL level, EntityPlugin &caller, std::string msg)
void print (std::ostream &stream, PrintEnums::WARN_LEVEL level, PrintData &data, std::string msg)
Static Protected Member Functions
static const char * getWarningLevel (PrintEnums::WARN_LEVEL e)
static std::string formatTime (double time)
static std::string formatMsg (PrintEnums::WARN_LEVEL level, PrintData &data, std::string msg)
Private Member Functions
bool write_file ()
bool write_console ()
Private Attributes
TimePtr time_
std::string log_dir_
std::ofstream log_stream_
PrintEnums::WRITE_TO output_flag_
Detailed Description
Definition at line 78 of file Print.h.
Constructor & Destructor Documentation
Print()
scrimmage::Print::Print () inline
Definition at line 80 of file Print.h.
 : time_(nullptr), log_dir_(""), output_flag_(PrintEnums::WRITE_TO::BOTH) {}
Member Function Documentation
init() [1/2]
void scrimmage::Print::init (TimePtr & time, std::string log_dir)
Definition at line 83 of file Print.cpp.
{
       init(time, log_dir, PrintEnums::WRITE_TO::BOTH);
   }
References scrimmage::PrintEnums::BOTH.
init() [2/2]
void scrimmage::Print::init (TimePtr & time, std::string log_dir, PrintEnums::WRITE_TO flag)
Definition at line 86 of file Print.cpp.
{
       time_ = time;
       log_dir_ = log_dir;
       output_flag_ = flag;
       if ( write_file() ) {
           std::ostringstream filename;
           filename << log_dir_ << '/' << "console.log";
            log_stream_.open(filename.str());
       }
   }
References log_dir_, log_stream_, output_flag_, time_, and write_file().
close()
void scrimmage::Print::close ()
Definition at line 97 of file Print.cpp.
                     {
       if ( log_stream_ ) {
           log_stream_.close();
       }
       time_ = nullptr;
   }
References log_stream_, and time_.
flush()
void scrimmage::Print::flush ()
Definition at line 103 of file Print.cpp.
                     {
       if (log_stream_) {
           log_stream_.flush();
       }
   }
References log_stream_.
printDev() [1/2]
void scrimmage::Print::printDev (PrintData & data, std::string outmessage)
Definition at line 113 of file Print.cpp.
{
       print(std::cout, PrintEnums::WARN_LEVEL::DEV, data, outmessage);
   }
References scrimmage::PrintEnums::DEV, and print().
printInfo() [1/2]
void scrimmage::Print::printInfo (PrintData & data, std::string outmessage)
Definition at line 116 of file Print.cpp.
{
       print(std::cout, PrintEnums::WARN_LEVEL::INFO, data, outmessage);
   }
References scrimmage::PrintEnums::INFO, and print().
printWarning() [1/2]
void scrimmage::Print::printWarning (PrintData & data, std::string outmessage)
Definition at line 119 of file Print.cpp.
{
       print(std::cout, PrintEnums::WARN_LEVEL::WARNING, data, outmessage);
   }
References print(), and scrimmage::PrintEnums::WARNING.
printError() [1/2]
void scrimmage::Print::printError (PrintData & data, std::string outmessage)
Definition at line 122 of file Print.cpp.
{
       print(std::cerr, PrintEnums::WARN_LEVEL::ERROR, data, outmessage);
   }
References scrimmage::PrintEnums::ERROR, and print().
printDev() [2/2]
void scrimmage::Print::printDev (EntityPlugin & caller, std::string outmessage)
Definition at line 127 of file Print.cpp.
{
       print(std::cout, PrintEnums::WARN_LEVEL::DEV, caller, outmessage);
   }
References scrimmage::PrintEnums::DEV, and print().
printInfo() [2/2]
void scrimmage::Print::printInfo (EntityPlugin & caller, std::string outmessage)
Definition at line 130 of file Print.cpp.
{
       print(std::cout, PrintEnums::WARN_LEVEL::INFO, caller, outmessage);
   }
References scrimmage::PrintEnums::INFO, and print().
printWarning() [2/2]
void scrimmage::Print::printWarning (EntityPlugin & caller, std::string outmessage)
Definition at line 133 of file Print.cpp.
{
       print(std::cerr, PrintEnums::WARN_LEVEL::WARNING, caller, outmessage);
   }
References print(), and scrimmage::PrintEnums::WARNING.
printError() [2/2]
void scrimmage::Print::printError (EntityPlugin & caller, std::string outmessage)
Definition at line 136 of file Print.cpp.
{
       print(std::cerr, PrintEnums::WARN_LEVEL::ERROR, caller, outmessage);
   }
References scrimmage::PrintEnums::ERROR, and print().
getWarningLevel()
const char * scrimmage::Print::getWarningLevel (PrintEnums::WARN_LEVEL e) static protected
Definition at line 144 of file Print.cpp.
   {
       const std::map<PrintEnums::WARN_LEVEL, const char*> GetAsStrings {
           { PrintEnums::WARN_LEVEL::DEV,     "DEV" },
           { PrintEnums::WARN_LEVEL::INFO,    "INFO" },
           { PrintEnums::WARN_LEVEL::WARNING, "WARN" },
           { PrintEnums::WARN_LEVEL::ERROR,   "ERROR" }
       };
       auto   it  = GetAsStrings.find(e);
       return it == GetAsStrings.end() ? GetAsStrings.begin()->second : it->second;
   }
References scrimmage::PrintEnums::DEV, scrimmage::PrintEnums::ERROR, scrimmage::PrintEnums::INFO, and scrimmage::PrintEnums::WARNING.
Referenced by formatMsg().
formatTime()
std::string scrimmage::Print::formatTime (double time) static protected
Definition at line 168 of file Print.cpp.
{
       if (std::isnan( time )) {
           return "-----.---";
       }
       else {
           std::ostringstream o;
           o << std::internal << std::fixed << std::setprecision(3)
             << std::setw(9) << std::setfill('0') << time;
           return o.str();
       }
   }
Referenced by formatMsg().
formatMsg()
std::string scrimmage::Print::formatMsg (PrintEnums::WARN_LEVEL level, PrintData & data, std::string msg) static protected
Definition at line 181 of file Print.cpp.
{
       std::ostringstream pre;
       std::ostringstream formattedmsg;
       std::string entitySection = "";
       // add entity_id if available
       if (data.entity_id_ > 0) {
           entitySection = "[Entity: " + std::to_string(data.entity_id_) + "]";
       }
       // create our prefix
       pre << formatTime(data.time_) << "s [" << data.name_ << "]" << entitySection << "[" << Print::getWarningLevel(level) << "]: ";
       // remove last character if it's a newline
       if (msg.back() == '\n') {
           msg.pop_back();
       }
       // iterate and place the prefix at the beginning of each newline
       formattedmsg << pre.str();
       for (auto i = msg.cbegin() ; i != msg.cend() ; ++i) {
           formattedmsg << *i;
           // add prefix after each newline
           if (*i == '\n') {
               formattedmsg << pre.str();
           }
       }
       return formattedmsg.str();
   }
References scrimmage::PrintData::entity_id_, formatTime(), getWarningLevel(), scrimmage::PrintData::name_, and scrimmage::PrintData::time_.
Referenced by print().
print() [1/2]
void scrimmage::Print::print (std::ostream & stream, PrintEnums::WARN_LEVEL level, EntityPlugin & caller, std::string msg) protected
Definition at line 218 of file Print.cpp.
{
       PrintData pd;
       pd.time_ = caller.getTime()->t();
       pd.name_ = caller.name();
       pd.entity_id_ = caller.parent()->id().id();
       print(stream, level, pd, msg);
   }
References scrimmage::PrintData::entity_id_, scrimmage::EntityPlugin::getTime(), scrimmage::Plugin::name(), scrimmage::PrintData::name_, scrimmage::EntityPlugin::parent(), and scrimmage::PrintData::time_.
Referenced by printDev(), printError(), printInfo(), and printWarning().
print() [2/2]
void scrimmage::Print::print (std::ostream & stream, PrintEnums::WARN_LEVEL level, PrintData & data, std::string msg) protected
Definition at line 226 of file Print.cpp.
{
       std::ostringstream o;
       o << formatMsg(level, data, msg) << std::endl;
       if ( write_file() ) { log_stream_ << o.str(); } // write to log file
       if ( write_console() ) { stream << o.str(); } // write to console
  }
References formatMsg(), log_stream_, write_console(), and write_file().
write_file()
bool scrimmage::Print::write_file () private
Definition at line 155 of file Print.cpp.
{
     return ( (output_flag_ == PrintEnums::WRITE_TO::BOTH) || (output_flag_ == PrintEnums::WRITE_TO::FILE_ONLY) );
   }
References scrimmage::PrintEnums::BOTH, scrimmage::PrintEnums::FILE_ONLY, and output_flag_.
Referenced by init(), and print().
write_console()
bool scrimmage::Print::write_console () private
Definition at line 158 of file Print.cpp.
{
     return ( (output_flag_ == PrintEnums::WRITE_TO::BOTH) || (output_flag_ == PrintEnums::WRITE_TO::CONSOLE_ONLY) );
   }
References scrimmage::PrintEnums::BOTH, scrimmage::PrintEnums::CONSOLE_ONLY, and output_flag_.
Referenced by print().
Member Data Documentation
time_
TimePtr scrimmage::Print::time_ private
Definition at line 107 of file Print.h.
Referenced by close(), and init().
log_dir_
std::string scrimmage::Print::log_dir_ private
Definition at line 108 of file Print.h.
Referenced by init().
log_stream_
std::ofstream scrimmage::Print::log_stream_ private
Definition at line 109 of file Print.h.
Referenced by close(), flush(), init(), and print().
output_flag_
PrintEnums::WRITE_TO scrimmage::Print::output_flag_ private
Definition at line 110 of file Print.h.
Referenced by init(), write_console(), and write_file().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/log/Print.h
/root/scrimmage/scrimmage/src/log/Print.cpp