SCRIMMAGE: scrimmage::Plugin Class Reference
scrimmage::Plugin Class Reference
#include <Plugin.h>
Public Member Functions
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
std::string name_ = "Unset"
bool name_set_ = false
Detailed Description
Definition at line 40 of file Plugin.h.
Constructor & Destructor Documentation
scrimmage::Plugin::Plugin ()
Definition at line 39 of file Plugin.cpp.
 : name_("Plugin") {}
scrimmage::Plugin::~Plugin () virtual
Definition at line 40 of file Plugin.cpp.
 {}
Member Function Documentation
void scrimmage::Plugin::set_name (std::string name)
Definition at line 44 of file Plugin.cpp.
References name(), name_, and name_set_.
{
     if (name_set_ == true) {
         std::cout << "WARNING: Plugin name, " << name << ", being reset. "
                   << "Should only be set once." << std::endl;
     }
     name_ = name;
     name_set_ = true;  // Set only once before warning.
 }
std::string scrimmage::Plugin::name ()
Definition at line 41 of file Plugin.cpp.
References name_.
Referenced by scrimmage::EntityPlugin::draw_shape(), scrimmage::EntityPlugin::get_scoped_property_helper(), scrimmage::interaction::BulletCollision::init(), set_name(), scrimmage::EntityPlugin::set_scoped_property(), and scrimmage::sensor::LOSSensor::step().
 { return name_; }
std::string scrimmage::Plugin::type () virtual
Reimplemented in scrimmage::sensor::RayTrace, scrimmage::Network, scrimmage::MotionModel, scrimmage::Autonomy, scrimmage::autonomy::PyAutonomy, and scrimmage::Sensor.
Definition at line 42 of file Plugin.cpp.
 { return std::string("Plugin"); }
Member Data Documentation
std::string scrimmage::Plugin::name_ = "Unset" protected
Definition at line 48 of file Plugin.h.
Referenced by name(), and set_name().
bool scrimmage::Plugin::name_set_ = false protected
Definition at line 49 of file Plugin.h.
Referenced by set_name().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugin_manager/Plugin.h
/root/scrimmage/scrimmage/src/plugin_manager/Plugin.cpp