SCRIMMAGE: scrimmage::Autonomy Class Reference
scrimmage::Autonomy Class Reference
#include <Autonomy.h>
Public Member Functions
Autonomy ()
std::string type () override
virtual bool step_autonomy (double t, double dt)
virtual bool posthumous (double t)
virtual void init ()
bool ready () override
virtual void init (std::map< std::string, std::string > &params)
void close (double t) override
bool need_reset ()
StatePtr & desired_state ()
void set_desired_state (StatePtr desired_state)
ContactMapPtr & get_contacts ()
ContactMap & get_contacts_raw ()
virtual void set_contacts (ContactMapPtr &contacts)
virtual void set_contacts_from_plugin (AutonomyPtr &ptr)
virtual void set_projection (std::shared_ptr< GeographicLib::LocalCartesian > &proj)
scrimmage::RTreePtr & rtree ()
void set_rtree (scrimmage::RTreePtr &rtree)
StatePtr & state ()
virtual void set_state (StatePtr &state)
std::string & logging_msg ()
bool get_is_controlling ()
void set_is_controlling (bool is_controlling)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
std::shared_ptr< GeographicLib::LocalCartesian > proj_
StatePtr state_
StatePtr desired_state_
ContactMapPtr contacts_
scrimmage::RTreePtr rtree_
bool need_reset_
std::string logging_msg_
bool is_controlling_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file Autonomy.h.
Constructor & Destructor Documentation
scrimmage::Autonomy::Autonomy ()
Definition at line 44 of file Autonomy.cpp.
                    : state_(std::make_shared<State>()),
     desired_state_(std::make_shared<State>()), need_reset_(false), is_controlling_(false) {}
Member Function Documentation
std::string scrimmage::Autonomy::type () override virtual
Reimplemented from scrimmage::Plugin.
Reimplemented in scrimmage::autonomy::PyAutonomy.
Definition at line 73 of file Autonomy.cpp.
 { return std::string("Autonomy"); }
bool scrimmage::Autonomy::step_autonomy (double t, double dt) virtual
Reimplemented in scrimmage::autonomy::ArduPilot, scrimmage::autonomy::ScrimmageOpenAIAutonomy, scrimmage::autonomy::GraphvizFSM, scrimmage::autonomy::ROSAirSim, scrimmage::autonomy::ROSControl, scrimmage::autonomy::ROSAutonomy, scrimmage::autonomy::TakeFlag, scrimmage::autonomy::FlightGearMultiplayer, scrimmage::autonomy::Straight, scrimmage::autonomy::MOOSAutonomy, scrimmage::autonomy::TrajectoryRecordPlayback, scrimmage::autonomy::motor_schemas::MoveToGoalMS, scrimmage::autonomy::motor_schemas::AvoidEntityMS, scrimmage::autonomy::BoundaryDefense, scrimmage::autonomy::Follow, scrimmage::autonomy::MotorSchemas, scrimmage::autonomy::AutonomyExecutor, scrimmage::autonomy::WaypointDispatcher, scrimmage::autonomy::WaypointGenerator, scrimmage::autonomy::AvoidWalls, scrimmage::autonomy::PyAutonomy, scrimmage::autonomy::AuctionAssign, scrimmage::autonomy::Control3D, scrimmage::autonomy::GoToWaypoint, scrimmage::autonomy::JoystickAutonomy, scrimmage::autonomy::APITester, scrimmage::autonomy::Boids, scrimmage::autonomy::CommandStringRelay, scrimmage::autonomy::Predator, scrimmage::autonomy::ShapeDraw, and scrimmage::autonomy::TrailMS.
Definition at line 75 of file Autonomy.cpp.
 { return true; }
bool scrimmage::Autonomy::posthumous (double t) virtual
Definition at line 76 of file Autonomy.cpp.
 { return true; }
void scrimmage::Autonomy::init () virtual
Definition at line 77 of file Autonomy.cpp.
Referenced by auction_assign.AuctionAssign::init(), and ready().
 {}
bool scrimmage::Autonomy::ready () inline override virtual
Reimplemented from scrimmage::EntityPlugin.
Reimplemented in scrimmage::autonomy::MOOSAutonomy.
Definition at line 54 of file Autonomy.h.
References close(), desired_state(), get_contacts(), get_contacts_raw(), get_is_controlling(), init(), logging_msg(), need_reset(), rtree(), set_contacts(), set_contacts_from_plugin(), set_desired_state(), set_is_controlling(), set_projection(), set_rtree(), set_state(), and state().
 { return true; }
void scrimmage::Autonomy::init (std::map< std::string, std::string > & params) virtual
Reimplemented in scrimmage::autonomy::ArduPilot, scrimmage::autonomy::ScrimmageOpenAIAutonomy, scrimmage::autonomy::GraphvizFSM, scrimmage::autonomy::ROSAirSim, scrimmage::autonomy::ROSControl, scrimmage::autonomy::ROSAutonomy, scrimmage::autonomy::TakeFlag, scrimmage::autonomy::FlightGearMultiplayer, scrimmage::autonomy::Straight, scrimmage::autonomy::TrajectoryRecordPlayback, scrimmage::autonomy::MOOSAutonomy, scrimmage::autonomy::motor_schemas::MoveToGoalMS, scrimmage::autonomy::motor_schemas::AvoidEntityMS, scrimmage::autonomy::BoundaryDefense, scrimmage::autonomy::Follow, scrimmage::autonomy::MotorSchemas, scrimmage::autonomy::AutonomyExecutor, scrimmage::autonomy::WaypointDispatcher, scrimmage::autonomy::WaypointGenerator, scrimmage::autonomy::AvoidWalls, scrimmage::autonomy::PyAutonomy, scrimmage::autonomy::AuctionAssign, scrimmage::autonomy::Control3D, scrimmage::autonomy::GoToWaypoint, scrimmage::autonomy::JoystickAutonomy, scrimmage::autonomy::APITester, scrimmage::autonomy::Boids, scrimmage::autonomy::CommandStringRelay, scrimmage::autonomy::Predator, scrimmage::autonomy::ShapeDraw, and scrimmage::autonomy::TrailMS.
Definition at line 78 of file Autonomy.cpp.
 {}
void scrimmage::Autonomy::close (double t) override virtual
Reimplemented from scrimmage::EntityPlugin.
Reimplemented in scrimmage::autonomy::ArduPilot.
Definition at line 89 of file Autonomy.cpp.
References contacts_, desired_state_, proj_, rtree_, and state_.
Referenced by ready().
{
     proj_ = nullptr;
     state_ = nullptr;
     desired_state_ = nullptr;
     contacts_ = nullptr;
     rtree_ = nullptr;
 }
bool scrimmage::Autonomy::need_reset ()
Definition at line 79 of file Autonomy.cpp.
References need_reset_.
Referenced by ready().
 {return need_reset_;}
StatePtr & scrimmage::Autonomy::desired_state ()
Definition at line 81 of file Autonomy.cpp.
References desired_state_.
Referenced by ready(), and set_desired_state().
 {return desired_state_;}
void scrimmage::Autonomy::set_desired_state (StatePtr desired_state)
Definition at line 83 of file Autonomy.cpp.
References desired_state(), and desired_state_.
Referenced by ready().
 {desired_state_ = desired_state;}
ContactMapPtr & scrimmage::Autonomy::get_contacts ()
Definition at line 85 of file Autonomy.cpp.
References contacts_.
Referenced by ready().
 {return contacts_;}
ContactMap & scrimmage::Autonomy::get_contacts_raw ()
Definition at line 87 of file Autonomy.cpp.
References contacts_.
Referenced by ready().
 {return *contacts_;}
void scrimmage::Autonomy::set_contacts (ContactMapPtr & contacts) virtual
Reimplemented in scrimmage::autonomy::PyAutonomy.
Definition at line 47 of file Autonomy.cpp.
References contacts_.
Referenced by ready().
{
     contacts_ = contacts;
 }
void scrimmage::Autonomy::set_contacts_from_plugin (AutonomyPtr & ptr) virtual
Reimplemented in scrimmage::autonomy::PyAutonomy.
Definition at line 51 of file Autonomy.cpp.
References contacts_.
Referenced by ready().
{
     contacts_ = ptr->contacts_;
 }
void scrimmage::Autonomy::set_projection (std::shared_ptr< GeographicLib::LocalCartesian > & proj) virtual
Definition at line 63 of file Autonomy.cpp.
References proj_.
Referenced by ready().
{
     proj_ = proj;
 }
RTreePtr & scrimmage::Autonomy::rtree ()
Definition at line 55 of file Autonomy.cpp.
References rtree_.
Referenced by ready(), and set_rtree().
 {return rtree_;}
void scrimmage::Autonomy::set_rtree (scrimmage::RTreePtr & rtree)
Definition at line 57 of file Autonomy.cpp.
References rtree(), and rtree_.
Referenced by ready().
 {rtree_ = rtree;}
StatePtr & scrimmage::Autonomy::state ()
Definition at line 59 of file Autonomy.cpp.
References state_.
Referenced by ready(), scrimmage::autonomy::PyAutonomy::set_state(), and set_state().
 {return state_;}
void scrimmage::Autonomy::set_state (StatePtr & state) virtual
Reimplemented in scrimmage::autonomy::PyAutonomy.
Definition at line 61 of file Autonomy.cpp.
References state(), and state_.
Referenced by ready().
 {state_ = state;}
std::string & scrimmage::Autonomy::logging_msg ()
Definition at line 67 of file Autonomy.cpp.
References logging_msg_.
Referenced by ready().
 {return logging_msg_;}
bool scrimmage::Autonomy::get_is_controlling ()
Definition at line 69 of file Autonomy.cpp.
References is_controlling_.
Referenced by ready().
 {return is_controlling_;}
void scrimmage::Autonomy::set_is_controlling (bool is_controlling)
Definition at line 71 of file Autonomy.cpp.
References is_controlling_.
Referenced by ready().
 {is_controlling_ = is_controlling;}
Member Data Documentation
std::shared_ptr<GeographicLib::LocalCartesian> scrimmage::Autonomy::proj_ protected
Definition at line 81 of file Autonomy.h.
Referenced by close(), and set_projection().
StatePtr scrimmage::Autonomy::state_ protected
Definition at line 83 of file Autonomy.h.
Referenced by close(), scrimmage::autonomy::PyAutonomy::set_state(), set_state(), and state().
StatePtr scrimmage::Autonomy::desired_state_ protected
Definition at line 84 of file Autonomy.h.
Referenced by close(), desired_state(), and set_desired_state().
ContactMapPtr scrimmage::Autonomy::contacts_ protected
Definition at line 85 of file Autonomy.h.
Referenced by close(), get_contacts(), get_contacts_raw(), scrimmage::autonomy::PyAutonomy::set_contacts(), set_contacts(), scrimmage::autonomy::PyAutonomy::set_contacts_from_plugin(), and set_contacts_from_plugin().
scrimmage::RTreePtr scrimmage::Autonomy::rtree_ protected
Definition at line 86 of file Autonomy.h.
Referenced by close(), rtree(), and set_rtree().
bool scrimmage::Autonomy::need_reset_ protected
Definition at line 88 of file Autonomy.h.
Referenced by need_reset().
std::string scrimmage::Autonomy::logging_msg_ protected
Definition at line 89 of file Autonomy.h.
Referenced by logging_msg().
bool scrimmage::Autonomy::is_controlling_ protected
Definition at line 91 of file Autonomy.h.
Referenced by get_is_controlling(), and set_is_controlling().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/autonomy/Autonomy.h
/root/scrimmage/scrimmage/src/autonomy/Autonomy.cpp