SCRIMMAGE: IMUErrorSimulator Class Reference
IMUErrorSimulator Class Reference
#include <IMUErrorSimulator.h>
Public Member Functions
IMUErrorSimulator (IMUErrorBudgetTemplate &errorBudget)
Eigen::Vector3d RandomVector (std::normal_distribution< double > &distribution, std::mt19937 &generator)
void PerformInitialRandomDraws (IMUErrorBudgetTemplate &errorBudget)
void CalculateParametersForFixedDeltaT (IMUErrorBudgetTemplate &errorBudget)
NoisyIMUData EachCycle (IMUErrorBudgetTemplate &errorBudget, Eigen::Vector3d InputDeltaVBodyWRTInertialInBody, Eigen::Vector3d InputDeltaThetaBodyWRTInertialInBody)
Public Attributes
bool InRunBiasOption
double InitRandomNumberSeed = 1
int RandomNumberSeedsPerInstance = 20
double NominalDeltaT
Eigen::Matrix3d Ma
Eigen::Vector3d AccelScaleFactorErr
Eigen::Vector3d AccelBiasTurnOn
Eigen::Vector3d AccelBiasInRun
Eigen::Vector3d AccelBiasPhi
Eigen::Vector3d AccelBiasInRunStdDev
Eigen::Vector3d TotalAccelBias
Eigen::Vector3d AccelVRWMSStdDev
Eigen::Vector3d AccelVRWMSDraws
Eigen::Vector3d AccelQuantizationResiduals = Eigen::Vector3d(0, 0, 0)
Eigen::Matrix3d Mg
Eigen::Vector3d GyroScaleFactorErr
Eigen::Vector3d GyroBiasTurnOn
Eigen::Vector3d GyroBiasInRun
Eigen::Vector3d GyroBiasPhi
Eigen::Vector3d GyroBiasInRunStdDev
Eigen::Vector3d TotalGyroBias
Eigen::Vector3d GyroARWRadStdDev
Eigen::Vector3d GyroARWRadDraws
Eigen::Vector3d GyroQuantizationResiduals
std::mt19937 InitRNG = std::mt19937(1)
std::mt19937 AccelBiasRNG = std::mt19937(2)
std::mt19937 AccelVRWRNG = std::mt19937(3)
std::mt19937 GyroBiasRNG = std::mt19937(4)
std::mt19937 GyroARWRNG = std::mt19937(5)
std::normal_distribution< double > InitDist = std::normal_distribution<double>(0, 1)
std::normal_distribution< double > AccelBiasDist = std::normal_distribution<double>(0, 1)
std::normal_distribution< double > AccelVRWDist = std::normal_distribution<double>(0, 1)
std::normal_distribution< double > GyroBiasDist = std::normal_distribution<double>(0, 1)
std::normal_distribution< double > GyroARWDist = std::normal_distribution<double>(0, 1)
Detailed Description
Definition at line 46 of file IMUErrorSimulator.h.
Constructor & Destructor Documentation
IMUErrorSimulator()
IMUErrorSimulator::IMUErrorSimulator (IMUErrorBudgetTemplate & errorBudget) explicit
Definition at line 34 of file IMUErrorSimulator.cpp.
{
     InRunBiasOption = false;
     PerformInitialRandomDraws(errorBudget);
     CalculateParametersForFixedDeltaT(errorBudget);
 }
References CalculateParametersForFixedDeltaT(), InRunBiasOption, and PerformInitialRandomDraws().
Member Function Documentation
RandomVector()
Eigen::Vector3d IMUErrorSimulator::RandomVector (std::normal_distribution< double > & distribution, std::mt19937 & generator)
Definition at line 41 of file IMUErrorSimulator.cpp.
{
     Eigen::Vector3d newVec;
     newVec << distribution(generator), distribution(generator), distribution(generator);
     return newVec;
 }
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
PerformInitialRandomDraws()
void IMUErrorSimulator::PerformInitialRandomDraws (IMUErrorBudgetTemplate & errorBudget)
Definition at line 47 of file IMUErrorSimulator.cpp.
{
     // Accel Error Terms
     // Get random draws for accel scale factor errors:
     AccelScaleFactorErr.x() = (1e-6) * errorBudget.XAccelAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     AccelScaleFactorErr.y() = (1e-6) * errorBudget.YAccelAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     AccelScaleFactorErr.z() = (1e-6) * errorBudget.ZAccelAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     // Put scale factor errors in the matrix Ma:
     Ma = AccelScaleFactorErr.asDiagonal();
     // Do initial random draws for accel turn-on bias:
     AccelBiasTurnOn.x() = errorBudget.XAccelAxisTurnOnBiasMPS2StdDev * InitDist(InitRNG);
     AccelBiasTurnOn.y() = errorBudget.YAccelAxisTurnOnBiasMPS2StdDev * InitDist(InitRNG);
     AccelBiasTurnOn.z() = errorBudget.ZAccelAxisTurnOnBiasMPS2StdDev * InitDist(InitRNG);
     // Gyro Error Terms
     // Get random draws for gyro scale factor errors:
     GyroScaleFactorErr.x() = (1e-6) * errorBudget.XGyroAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     GyroScaleFactorErr.y() = (1e-6) * errorBudget.YGyroAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     GyroScaleFactorErr.z() = (1e-6) * errorBudget.ZGyroAxisScaleFactorPPMStdDev * InitDist(InitRNG);
     // Place gyro scale factor errors in matrix Mg:
     Mg = GyroScaleFactorErr.asDiagonal();
     // Get random draws for gyro turn-on biases
     GyroBiasTurnOn.x() = errorBudget.XGyroAxisTurnOnBiasRadPerSecStdDev * InitDist(InitRNG);
     GyroBiasTurnOn.y() = errorBudget.YGyroAxisTurnOnBiasRadPerSecStdDev * InitDist(InitRNG);
     GyroBiasTurnOn.z() = errorBudget.ZGyroAxisTurnOnBiasRadPerSecStdDev * InitDist(InitRNG);
 }
References AccelBiasTurnOn, AccelScaleFactorErr, GyroBiasTurnOn, GyroScaleFactorErr, InitDist, InitRNG, Ma, Mg, IMUErrorBudgetTemplate::XAccelAxisScaleFactorPPMStdDev, IMUErrorBudgetTemplate::XAccelAxisTurnOnBiasMPS2StdDev, IMUErrorBudgetTemplate::XGyroAxisScaleFactorPPMStdDev, IMUErrorBudgetTemplate::XGyroAxisTurnOnBiasRadPerSecStdDev, IMUErrorBudgetTemplate::YAccelAxisScaleFactorPPMStdDev, IMUErrorBudgetTemplate::YAccelAxisTurnOnBiasMPS2StdDev, IMUErrorBudgetTemplate::YGyroAxisScaleFactorPPMStdDev, IMUErrorBudgetTemplate::YGyroAxisTurnOnBiasRadPerSecStdDev, IMUErrorBudgetTemplate::ZAccelAxisScaleFactorPPMStdDev, IMUErrorBudgetTemplate::ZAccelAxisTurnOnBiasMPS2StdDev, IMUErrorBudgetTemplate::ZGyroAxisScaleFactorPPMStdDev, and IMUErrorBudgetTemplate::ZGyroAxisTurnOnBiasRadPerSecStdDev.
Referenced by IMUErrorSimulator().
CalculateParametersForFixedDeltaT()
void IMUErrorSimulator::CalculateParametersForFixedDeltaT (IMUErrorBudgetTemplate & errorBudget)
Definition at line 75 of file IMUErrorSimulator.cpp.
{
     // Calculate sample interval
     NominalDeltaT = 1.0 / errorBudget.SampleFrequency;
     // Accel Error Terms:
     // The parameters below are for the accel in-run bias error
     if (InRunBiasOption == false) {
         AccelBiasPhi.x() = exp(-NominalDeltaT / errorBudget.XAccelAxisInRunBiasTimeConstantSec);
         AccelBiasPhi.y() = exp(-NominalDeltaT / errorBudget.YAccelAxisInRunBiasTimeConstantSec);
         AccelBiasPhi.z() = exp(-NominalDeltaT / errorBudget.ZAccelAxisInRunBiasTimeConstantSec);
         AccelBiasInRunStdDev.x() = errorBudget.XAccelAxisInRunBiasMPS2StdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.XAccelAxisInRunBiasTimeConstantSec));
         AccelBiasInRunStdDev.y() = errorBudget.YAccelAxisInRunBiasMPS2StdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.YAccelAxisInRunBiasTimeConstantSec));
         AccelBiasInRunStdDev.z() = errorBudget.ZAccelAxisInRunBiasMPS2StdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.ZAccelAxisInRunBiasTimeConstantSec));
         // do initial draw for in-run bias
         //                AccelBiasInRun = diag([errorBudget.XAccelAxisInRunBiasMPS2StdDev;errorBudget.YAccelAxisInRunBiasMPS2StdDev;errorBudget.ZAccelAxisInRunBiasMPS2StdDev])*randn(AccelBiasInRunRandomNumberStreamPtr,3,1);;
         AccelBiasInRun = Eigen::Vector3d(errorBudget.XAccelAxisInRunBiasMPS2StdDev, errorBudget.YAccelAxisInRunBiasMPS2StdDev, errorBudget.ZAccelAxisInRunBiasMPS2StdDev).asDiagonal() * RandomVector(AccelBiasDist, AccelBiasRNG);
     }
     // Following is the standard deviation of the velocity random walk noise
     AccelVRWMSStdDev = sqrt(NominalDeltaT) * Eigen::Vector3d(errorBudget.XAccelVRWMPS2PerRtHzStdDev, errorBudget.YAccelVRWMPS2PerRtHzStdDev, errorBudget.ZAccelVRWMPS2PerRtHzStdDev);
     // Gyro Error Terms:
     // The parameters below are for the gyro in-run bias error
     if (InRunBiasOption == false) {
         GyroBiasPhi.x() = exp(-NominalDeltaT / errorBudget.XGyroAxisInRunBiasTimeConstantSec);
         GyroBiasPhi.y() = exp(-NominalDeltaT / errorBudget.YGyroAxisInRunBiasTimeConstantSec);
         GyroBiasPhi.z() = exp(-NominalDeltaT / errorBudget.ZGyroAxisInRunBiasTimeConstantSec);
         GyroBiasInRunStdDev.x() = errorBudget.XGyroAxisInRunBiasRadPerSecStdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.XGyroAxisInRunBiasTimeConstantSec));
         GyroBiasInRunStdDev.y() = errorBudget.YGyroAxisInRunBiasRadPerSecStdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.YGyroAxisInRunBiasTimeConstantSec));
         GyroBiasInRunStdDev.z() = errorBudget.ZGyroAxisInRunBiasRadPerSecStdDev * sqrt(1 - exp(-2 * NominalDeltaT / errorBudget.ZGyroAxisInRunBiasTimeConstantSec));
         // do initial draw for in-run bias
         //                GyroBiasInRun = diag([errorBudget.XGyroAxisInRunBiasRadPerSecStdDev;errorBudget.YGyroAxisInRunBiasRadPerSecStdDev;errorBudget.ZGyroAxisInRunBiasRadPerSecStdDev])*randn(GyroBiasInRunRandomNumberStreamPtr,3,1);
         GyroBiasInRun = Eigen::Vector3d(errorBudget.XGyroAxisInRunBiasRadPerSecStdDev, errorBudget.YGyroAxisInRunBiasRadPerSecStdDev, errorBudget.ZGyroAxisInRunBiasRadPerSecStdDev).asDiagonal() * RandomVector(GyroBiasDist, GyroBiasRNG);
     }
     // Following is the standard deviation of the angular random walk noise
     GyroARWRadStdDev = sqrt(NominalDeltaT) * Eigen::Vector3d(errorBudget.XGyroARWRadPerSecPerRtHzStdDev, errorBudget.YGyroARWRadPerSecPerRtHzStdDev, errorBudget.ZGyroARWRadPerSecPerRtHzStdDev);
 }
References AccelBiasDist, AccelBiasInRun, AccelBiasInRunStdDev, AccelBiasPhi, AccelBiasRNG, AccelVRWMSStdDev, GyroARWRadStdDev, GyroBiasDist, GyroBiasInRun, GyroBiasInRunStdDev, GyroBiasPhi, GyroBiasRNG, InRunBiasOption, NominalDeltaT, RandomVector(), IMUErrorBudgetTemplate::SampleFrequency, IMUErrorBudgetTemplate::XAccelAxisInRunBiasMPS2StdDev, IMUErrorBudgetTemplate::XAccelAxisInRunBiasTimeConstantSec, IMUErrorBudgetTemplate::XAccelVRWMPS2PerRtHzStdDev, IMUErrorBudgetTemplate::XGyroARWRadPerSecPerRtHzStdDev, IMUErrorBudgetTemplate::XGyroAxisInRunBiasRadPerSecStdDev, IMUErrorBudgetTemplate::XGyroAxisInRunBiasTimeConstantSec, IMUErrorBudgetTemplate::YAccelAxisInRunBiasMPS2StdDev, IMUErrorBudgetTemplate::YAccelAxisInRunBiasTimeConstantSec, IMUErrorBudgetTemplate::YAccelVRWMPS2PerRtHzStdDev, IMUErrorBudgetTemplate::YGyroARWRadPerSecPerRtHzStdDev, IMUErrorBudgetTemplate::YGyroAxisInRunBiasRadPerSecStdDev, IMUErrorBudgetTemplate::YGyroAxisInRunBiasTimeConstantSec, IMUErrorBudgetTemplate::ZAccelAxisInRunBiasMPS2StdDev, IMUErrorBudgetTemplate::ZAccelAxisInRunBiasTimeConstantSec, IMUErrorBudgetTemplate::ZAccelVRWMPS2PerRtHzStdDev, IMUErrorBudgetTemplate::ZGyroARWRadPerSecPerRtHzStdDev, IMUErrorBudgetTemplate::ZGyroAxisInRunBiasRadPerSecStdDev, and IMUErrorBudgetTemplate::ZGyroAxisInRunBiasTimeConstantSec.
Referenced by IMUErrorSimulator().
EachCycle()
NoisyIMUData IMUErrorSimulator::EachCycle (IMUErrorBudgetTemplate & errorBudget, Eigen::Vector3d InputDeltaVBodyWRTInertialInBody, Eigen::Vector3d InputDeltaThetaBodyWRTInertialInBody)
Definition at line 115 of file IMUErrorSimulator.cpp.
{
     Eigen::Vector3d quantizedAccelOutput, OutputBodyFrameAccelErrors, quantizedGyroOutput, OutputBodyFrameRateGyroErrors;
     NoisyIMUData returnValue;
     if (!InRunBiasOption) {
         TotalAccelBias = AccelBiasTurnOn + AccelBiasInRun;
         AccelBiasInRun = AccelBiasPhi.array() * AccelBiasInRun.array() + AccelBiasInRunStdDev.array() * RandomVector(AccelBiasDist, AccelBiasRNG).array();
     }
     AccelVRWMSDraws = AccelVRWMSStdDev.array() * RandomVector(AccelVRWDist, AccelVRWRNG).array();
     // Calculate errors to be added to the accel data
     OutputBodyFrameAccelErrors = TotalAccelBias + errorBudget.SampleFrequency * AccelVRWMSDraws + errorBudget.SampleFrequency * Ma * InputDeltaVBodyWRTInertialInBody;
     // Add errors to accel data
     Eigen::Vector3d OutputNoisyDeltaVBodyWRTInertialInBody = InputDeltaVBodyWRTInertialInBody + NominalDeltaT * OutputBodyFrameAccelErrors;
     // Take the noisy delta-V's calculated above in double precision
     // and quantize them based on the accel spec.
     quantizedAccelOutput = errorBudget.AccelDeltaVQuantizationMPS * ((OutputNoisyDeltaVBodyWRTInertialInBody + AccelQuantizationResiduals).array() / errorBudget.AccelDeltaVQuantizationMPS).round();
     // Calculate residuals from quantization process and later add them to
     // the next accel measurements to be quantized
     AccelQuantizationResiduals = OutputNoisyDeltaVBodyWRTInertialInBody + AccelQuantizationResiduals - quantizedAccelOutput;
     // Calculate totality of errors added to accel data:
     OutputBodyFrameAccelErrors = errorBudget.SampleFrequency * (quantizedAccelOutput - InputDeltaVBodyWRTInertialInBody).array();
     // Gyro
     // Calculate the total gyro bias, i.e. turn-on + in-run
     if (InRunBiasOption == false) {
         TotalGyroBias = GyroBiasTurnOn + GyroBiasInRun;
         // create the next in-run gyro bias error
         GyroBiasInRun = GyroBiasPhi.array() * GyroBiasInRun.array() + GyroBiasInRunStdDev.array() * RandomVector(GyroBiasDist, GyroBiasRNG).array();
     }
     // do random draw for gyro angel random walk:
     GyroARWRadDraws = GyroARWRadStdDev.array() * RandomVector(GyroARWDist, GyroARWRNG).array();
     // Calculate errors to be added to the gyro data
     OutputBodyFrameRateGyroErrors = TotalGyroBias.array() + errorBudget.SampleFrequency * GyroARWRadDraws.array() + errorBudget.SampleFrequency * (Mg * InputDeltaThetaBodyWRTInertialInBody).array();
     // Add errors to gyro data
     Eigen::Vector3d OutputNoisyDeltaThetaBodyWRTInertialInBody = InputDeltaThetaBodyWRTInertialInBody.array() + NominalDeltaT * OutputBodyFrameRateGyroErrors.array();
     // Take the noisy delta-theta's calculated above in double precision
     // and quantize them based on the gyro spec.
     quantizedGyroOutput = errorBudget.GyroDeltaThetaQuantizationRadians * ((OutputNoisyDeltaThetaBodyWRTInertialInBody + GyroQuantizationResiduals).array() / errorBudget.GyroDeltaThetaQuantizationRadians).round();
     // Calculate residuals from quantization process and later add them to
     // the next gyro measurements to be quantized
     GyroQuantizationResiduals = OutputNoisyDeltaThetaBodyWRTInertialInBody + GyroQuantizationResiduals - quantizedGyroOutput;
     // Calculate totality of errors added to gyro data:
     OutputBodyFrameRateGyroErrors = errorBudget.SampleFrequency * (quantizedGyroOutput - InputDeltaThetaBodyWRTInertialInBody).array();
     returnValue.noisyDeltaV = quantizedAccelOutput;
     returnValue.noisyDeltaTheta = quantizedGyroOutput;
     returnValue.deltaVErrors = OutputBodyFrameAccelErrors;
     returnValue.deltaThetaErrors = OutputBodyFrameRateGyroErrors;
     return returnValue;
 }
References AccelBiasDist, AccelBiasInRun, AccelBiasInRunStdDev, AccelBiasPhi, AccelBiasRNG, AccelBiasTurnOn, IMUErrorBudgetTemplate::AccelDeltaVQuantizationMPS, AccelQuantizationResiduals, AccelVRWDist, AccelVRWMSDraws, AccelVRWMSStdDev, AccelVRWRNG, NoisyIMUData::deltaThetaErrors, NoisyIMUData::deltaVErrors, GyroARWDist, GyroARWRadDraws, GyroARWRadStdDev, GyroARWRNG, GyroBiasDist, GyroBiasInRun, GyroBiasInRunStdDev, GyroBiasPhi, GyroBiasRNG, GyroBiasTurnOn, IMUErrorBudgetTemplate::GyroDeltaThetaQuantizationRadians, GyroQuantizationResiduals, InRunBiasOption, Ma, Mg, NoisyIMUData::noisyDeltaTheta, NoisyIMUData::noisyDeltaV, NominalDeltaT, RandomVector(), IMUErrorBudgetTemplate::SampleFrequency, TotalAccelBias, and TotalGyroBias.
Referenced by scrimmage::sensor::ROSIMUSensor::step().
Member Data Documentation
InRunBiasOption
bool IMUErrorSimulator::InRunBiasOption
Definition at line 48 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), EachCycle(), and IMUErrorSimulator().
InitRandomNumberSeed
double IMUErrorSimulator::InitRandomNumberSeed = 1
Definition at line 49 of file IMUErrorSimulator.h.
RandomNumberSeedsPerInstance
int IMUErrorSimulator::RandomNumberSeedsPerInstance = 20
Definition at line 50 of file IMUErrorSimulator.h.
NominalDeltaT
double IMUErrorSimulator::NominalDeltaT
Definition at line 51 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
Ma
Eigen::Matrix3d IMUErrorSimulator::Ma
Definition at line 52 of file IMUErrorSimulator.h.
Referenced by EachCycle(), and PerformInitialRandomDraws().
AccelScaleFactorErr
Eigen::Vector3d IMUErrorSimulator::AccelScaleFactorErr
Definition at line 53 of file IMUErrorSimulator.h.
Referenced by PerformInitialRandomDraws().
AccelBiasTurnOn
Eigen::Vector3d IMUErrorSimulator::AccelBiasTurnOn
Definition at line 54 of file IMUErrorSimulator.h.
Referenced by EachCycle(), and PerformInitialRandomDraws().
AccelBiasInRun
Eigen::Vector3d IMUErrorSimulator::AccelBiasInRun
Definition at line 55 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
AccelBiasPhi
Eigen::Vector3d IMUErrorSimulator::AccelBiasPhi
Definition at line 56 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
AccelBiasInRunStdDev
Eigen::Vector3d IMUErrorSimulator::AccelBiasInRunStdDev
Definition at line 57 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
TotalAccelBias
Eigen::Vector3d IMUErrorSimulator::TotalAccelBias
Definition at line 58 of file IMUErrorSimulator.h.
Referenced by EachCycle().
AccelVRWMSStdDev
Eigen::Vector3d IMUErrorSimulator::AccelVRWMSStdDev
Definition at line 59 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
AccelVRWMSDraws
Eigen::Vector3d IMUErrorSimulator::AccelVRWMSDraws
Definition at line 60 of file IMUErrorSimulator.h.
Referenced by EachCycle().
AccelQuantizationResiduals
Eigen::Vector3d IMUErrorSimulator::AccelQuantizationResiduals = Eigen::Vector3d(0, 0, 0)
Definition at line 61 of file IMUErrorSimulator.h.
Referenced by EachCycle().
Mg
Eigen::Matrix3d IMUErrorSimulator::Mg
Definition at line 63 of file IMUErrorSimulator.h.
Referenced by EachCycle(), and PerformInitialRandomDraws().
GyroScaleFactorErr
Eigen::Vector3d IMUErrorSimulator::GyroScaleFactorErr
Definition at line 64 of file IMUErrorSimulator.h.
Referenced by PerformInitialRandomDraws().
GyroBiasTurnOn
Eigen::Vector3d IMUErrorSimulator::GyroBiasTurnOn
Definition at line 65 of file IMUErrorSimulator.h.
Referenced by EachCycle(), and PerformInitialRandomDraws().
GyroBiasInRun
Eigen::Vector3d IMUErrorSimulator::GyroBiasInRun
Definition at line 66 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
GyroBiasPhi
Eigen::Vector3d IMUErrorSimulator::GyroBiasPhi
Definition at line 67 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
GyroBiasInRunStdDev
Eigen::Vector3d IMUErrorSimulator::GyroBiasInRunStdDev
Definition at line 68 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
TotalGyroBias
Eigen::Vector3d IMUErrorSimulator::TotalGyroBias
Definition at line 69 of file IMUErrorSimulator.h.
Referenced by EachCycle().
GyroARWRadStdDev
Eigen::Vector3d IMUErrorSimulator::GyroARWRadStdDev
Definition at line 70 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
GyroARWRadDraws
Eigen::Vector3d IMUErrorSimulator::GyroARWRadDraws
Definition at line 71 of file IMUErrorSimulator.h.
Referenced by EachCycle().
GyroQuantizationResiduals
Eigen::Vector3d IMUErrorSimulator::GyroQuantizationResiduals
Definition at line 72 of file IMUErrorSimulator.h.
Referenced by EachCycle().
InitRNG
std::mt19937 IMUErrorSimulator::InitRNG = std::mt19937(1)
Definition at line 75 of file IMUErrorSimulator.h.
Referenced by PerformInitialRandomDraws().
AccelBiasRNG
std::mt19937 IMUErrorSimulator::AccelBiasRNG = std::mt19937(2)
Definition at line 76 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
AccelVRWRNG
std::mt19937 IMUErrorSimulator::AccelVRWRNG = std::mt19937(3)
Definition at line 77 of file IMUErrorSimulator.h.
Referenced by EachCycle().
GyroBiasRNG
std::mt19937 IMUErrorSimulator::GyroBiasRNG = std::mt19937(4)
Definition at line 78 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
GyroARWRNG
std::mt19937 IMUErrorSimulator::GyroARWRNG = std::mt19937(5)
Definition at line 79 of file IMUErrorSimulator.h.
Referenced by EachCycle().
InitDist
std::normal_distribution<double> IMUErrorSimulator::InitDist = std::normal_distribution<double>(0, 1)
Definition at line 81 of file IMUErrorSimulator.h.
Referenced by PerformInitialRandomDraws().
AccelBiasDist
std::normal_distribution<double> IMUErrorSimulator::AccelBiasDist = std::normal_distribution<double>(0, 1)
Definition at line 82 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
AccelVRWDist
std::normal_distribution<double> IMUErrorSimulator::AccelVRWDist = std::normal_distribution<double>(0, 1)
Definition at line 83 of file IMUErrorSimulator.h.
Referenced by EachCycle().
GyroBiasDist
std::normal_distribution<double> IMUErrorSimulator::GyroBiasDist = std::normal_distribution<double>(0, 1)
Definition at line 84 of file IMUErrorSimulator.h.
Referenced by CalculateParametersForFixedDeltaT(), and EachCycle().
GyroARWDist
std::normal_distribution<double> IMUErrorSimulator::GyroARWDist = std::normal_distribution<double>(0, 1)
Definition at line 85 of file IMUErrorSimulator.h.
Referenced by EachCycle().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/ROSIMUSensor/IMUErrorSimulator.h
/root/scrimmage/scrimmage/src/plugins/sensor/ROSIMUSensor/IMUErrorSimulator.cpp