SCRIMMAGE: scrimmage::motion::FixedWing6DOF Class Reference
scrimmage::motion::FixedWing6DOF Class Reference
#include <FixedWing6DOF.h>
Public Types
enum ModelParams {
U = 0, V, W, P,
Q, R, U_dot, V_dot,
W_dot, P_dot, Q_dot, R_dot,
Uw, Vw, Ww, Xw,
Yw, Zw, q0, q1,
q2, q3, MODEL_NUM_ITEMS
}
enum LaunchState { PRELAUNCH = 0, LAUNCH, POSTLAUNCH }
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Member Functions
FixedWing6DOF ()
virtual std::tuple< int, int, int > version ()
bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params) override
bool step (double time, double dt) override
void teleport (StatePtr &state) override
void model (const vector_t &x, vector_t &dxdt, double t) override
Public Member Functions inherited from scrimmage::motion::RigidBody6DOFBase
RigidBody6DOFBase ()
Eigen::Vector3d & linear_vel_body ()
Eigen::Vector3d & ang_vel_body ()
Eigen::Vector3d & linear_accel_body ()
Eigen::Vector3d & ang_accel_body ()
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
int throttle_idx_ = 0
int elevator_idx_ = 0
int aileron_idx_ = 0
int rudder_idx_ = 0
scrimmage::PID heading_pid_
scrimmage::PID alt_pid_
scrimmage::PID vel_pid_
Eigen::VectorXd ctrl_u_
Eigen::Matrix3d I_
Eigen::Matrix3d I_inv_
bool draw_vel_ = false
bool draw_ang_vel_ = false
bool write_csv_ = false
CSV csv_
scrimmage::Quaternion quat_body_
Eigen::Vector3d force_ext_body_
double thrust_ = 0
double throttle_ = 0
double delta_elevator_ = 0
double delta_aileron_ = 0
double delta_rudder_ = 0
double launch_command_ = 0
double alpha_ = 0
double alpha_dot_ = 0
double rho_ = 1.2250
double throttle_input_min_ = 0.0
double throttle_input_max_ = 1.0
double thrust_min_ = -100.0e3
double thrust_max_ = 100.0e3
double delta_elevator_min_ = -0.5236
double delta_elevator_max_ = 0.5236
double delta_aileron_min_ = -0.5236
double delta_aileron_max_ = 0.5236
double delta_rudder_min_ = -0.2618
double delta_rudder_max_ = 0.2618
double b_ = 8.382
double S_ = 24.1548
double c_ = 3.29184
double e_ = .995
double AR_ = 2.5
double C_D0_ = 0.03
double C_D_alpha_ = 0.3
double C_D_delta_elevator_ = 0.01
double C_L0_ = 0.28
double C_L_alpha_ = 3.45
double C_LQ_ = 0.0
double C_L_alpha_dot_ = 0.72
double C_L_delta_elevator_ = 0.36
double C_M0_ = 0.0
double C_MQ_ = -3.6
double C_M_alpha_ = -0.38
double C_M_alpha_dot_ = -1.1
double C_M_delta_elevator_ = -0.5
double C_Y_beta_ = -0.98
double C_Y_delta_rudder_ = 0.17
double C_L_beta_ = -0.12
double C_LP_ = -0.26
double C_LR_ = 0.14
double C_L_delta_aileron_ = 0.08
double C_L_delta_rudder_ = -0.105
double C_N_beta_ = 0.25
double C_NP_ = 0.022
double C_NR_ = -0.35
double C_N_delta_aileron_ = 0.06
double C_N_delta_rudder_ = 0.032
double launch_accel_ = 200
double launch_speed_ = 20
double launch_start_t_ = 0
double launch_time_ = 30
LaunchState launch_state_ = POSTLAUNCH
Eigen::Vector3d launch_dir_NED_
bool use_ground_model_ = true
Eigen::Quaterniond rot_180_x_axis_
Protected Attributes inherited from scrimmage::motion::RigidBody6DOFBase
Eigen::Vector3d linear_vel_body_
Eigen::Vector3d ang_vel_body_
Eigen::Vector3d linear_accel_body_
Eigen::Vector3d ang_accel_body_
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
Detailed Description
Definition at line 49 of file FixedWing6DOF.h.
Member Enumeration Documentation
enum scrimmage::motion::FixedWing6DOF::ModelParams
Enumerator
U
V
W
P
Q
R
U_dot
V_dot
W_dot
P_dot
Q_dot
R_dot
Uw
Vw
Ww
Xw
Yw
Zw
q0
q1
q2
q3
MODEL_NUM_ITEMS
Definition at line 51 of file FixedWing6DOF.h.
                      {
         U = 0,
         V,
         W,
         P,
         Q,
         R,
         U_dot,
         V_dot,
         W_dot,
         P_dot,
         Q_dot,
         R_dot,
         Uw,
         Vw,
         Ww,
         Xw,
         Yw,
         Zw,
         q0,
         q1,
         q2,
         q3,
         MODEL_NUM_ITEMS
     };
enum scrimmage::motion::FixedWing6DOF::LaunchState
Enumerator
PRELAUNCH
LAUNCH
POSTLAUNCH
Definition at line 89 of file FixedWing6DOF.h.
                      {
         PRELAUNCH = 0,
         LAUNCH,
         POSTLAUNCH
     };
Constructor & Destructor Documentation
scrimmage::motion::FixedWing6DOF::FixedWing6DOF ()
Definition at line 64 of file FixedWing6DOF.cpp.
{
     Eigen::AngleAxisd aa(M_PI, Eigen::Vector3d::UnitX());
     rot_180_x_axis_ = Eigen::Quaterniond(aa);
 }
Member Function Documentation
std::tuple< int, int, int > scrimmage::motion::FixedWing6DOF::version () virtual
Definition at line 69 of file FixedWing6DOF.cpp.
{
     return std::tuple<int, int, int>(0, 0, 1);
 }
bool scrimmage::motion::FixedWing6DOF::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 73 of file FixedWing6DOF.cpp.
References scrimmage::Angles::angle_pi(), scrimmage::get_vec_of_vecs(), MODEL_NUM_ITEMS, scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::motion::U, scrimmage::motion::Uw, scrimmage::motion::V, scrimmage::motion::Vw, scrimmage::motion::W, scrimmage::motion::Ww, scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     // Setup variable index for controllers
     throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::In);
     elevator_idx_ = vars_.declare(VariableIO::Type::elevator, VariableIO::Direction::In);
     aileron_idx_ = vars_.declare(VariableIO::Type::aileron, VariableIO::Direction::In);
     rudder_idx_ = vars_.declare(VariableIO::Type::rudder, VariableIO::Direction::In);
     x_.resize(MODEL_NUM_ITEMS);
     // Need to rotate axes by 180 degrees around X-axis SCRIMMAGE's global
     // frame uses Z-axis pointing up. Many aircraft equations of motion are
     // specified with Z-axis pointing down.
     quat_body_ = rot_180_x_axis_ * state_->quat();
     quat_body_.set(sc::Angles::angle_pi(quat_body_.roll()+M_PI),
                    quat_body_.pitch(), quat_body_.yaw());
     quat_body_.normalize();
     Eigen::Vector3d vel_body(state_->vel()(0), -state_->vel()(1), -state_->vel()(2));
     vel_body = quat_body_.rotate_reverse(vel_body);
     x_[U] = vel_body(0);
     x_[V] = vel_body(1);
     x_[W] = vel_body(2);
     Eigen::Vector3d local_ang_vel(state_->ang_vel()(0), -state_->ang_vel()(1), -state_->ang_vel()(2));
     local_ang_vel = quat_body_.rotate_reverse(local_ang_vel);
     x_[P] = local_ang_vel(0);
     x_[Q] = local_ang_vel(1);
     x_[R] = local_ang_vel(2);
     x_[Uw] = state_->vel()(0);
     x_[Vw] = state_->vel()(1);
     x_[Ww] = state_->vel()(2);
     x_[Xw] = state_->pos()(0);
     x_[Yw] = state_->pos()(1);
     x_[Zw] = state_->pos()(2);
     x_[q0] = quat_body_.w();
     x_[q1] = quat_body_.x();
     x_[q2] = quat_body_.y();
     x_[q3] = quat_body_.z();
     x_[U_dot] = 0;
     x_[V_dot] = 0;
     x_[W_dot] = 0;
     x_[P_dot] = 0;
     x_[Q_dot] = 0;
     x_[R_dot] = 0;
     // catapault parameters
     launch_accel_ = sc::get<double>("launch_accel", params, launch_accel_);
     launch_speed_ = sc::get<double>("launch_speed", params, launch_speed_);
     launch_time_  = sc::get<double>("launch_time",  params, launch_time_);
     bool use_launcher = sc::get<bool>("use_launcher", params, false);
     if (true == use_launcher)
         launch_state_ = PRELAUNCH;
     use_ground_model_ = sc::get<double>("use_ground_model", params, true);
     // Parse XML parameters
     g_ = sc::get<double>("gravity_magnitude", params, 9.81);
     mass_ = sc::get<double>("mass", params, 1.2);
     // Get the inertia matrix
     std::vector<std::vector<std::string>> vecs;
     std::string inertia_matrix = sc::get<std::string>("inertia_matrix",
                                                       params, "");
     // If the inertia matrix is described using slug_ft_sq, it has priority
     bool convert_slug = false;
     if (params.count("inertia_matrix_slug_ft_sq")) {
         convert_slug = true;
         inertia_matrix = sc::get<std::string>("inertia_matrix_slug_ft_sq",
                                               params, "");
     }
     // Parse inertia matrix
     bool valid_inertia = false;
     if (!sc::get_vec_of_vecs(inertia_matrix, vecs)) {
         cout << "Failed to parse inertia_matrix:" << inertia_matrix << endl;
     } else {
         int row = 0;
         for (std::vector<std::string> vec : vecs) {
             if (vec.size() != 3) {
                 cout << "Invalid vector size in: " << inertia_matrix << endl;
                 break;
             }
             for (int i = 0; i < 3; i++) {
                 I_(row, i) = std::stod(vec[i]);
                 // If the matrix was defined in slug*ft^2, convert it to SI
                 if (convert_slug) {
                     I_(row, i) *= 1.35581795; // slug*ft^2 to kg*m^2
                 }
             }
             row++;
         }
         if (row == 3) {
             valid_inertia = true;
         }
     }
     if (!valid_inertia) {
         cout << "Using identity matrix for inertia." << endl;
         I_ = Eigen::Matrix3d::Identity();
     }
     I_inv_ = I_.inverse();
     // Drawing
     draw_vel_ = sc::get<bool>("draw_vel", params, false);
     draw_ang_vel_ = sc::get<bool>("draw_ang_vel", params, false);
     // Should we write a CSV file? What values should be written?
     write_csv_ = sc::get<bool>("write_csv", params, false);
     if (write_csv_) {
         csv_.open_output(parent_->mp()->log_dir() + "/"
                          + std::to_string(parent_->id().id())
                          + "-states.csv");
         cout << "Writing log to " + parent_->mp()->log_dir() + "/"
                          + std::to_string(parent_->id().id())
                          + "-states.csv" << endl;
         csv_.set_column_headers(sc::CSV::Headers{"t",
                     "x", "y", "z",
                     "U", "V", "W", "alpha", "alpha_dot", "beta",
                     "P", "Q", "R",
                     "Ax_b", "Ay_b", "Az_b",
                     "AngAccelx_b", "AngAccely_b", "AngAccelz_b",
                     "roll", "pitch", "yaw",
                     "throttle", "thrust", "elevator", "aileron", "rudder"});
     }
     rho_ = sc::get<double>("air_density", params, rho_); // air density
     // thrust and dimensional specs
     throttle_input_min_ = sc::get<double>("throttle_input_min", params, throttle_input_min_);
     throttle_input_max_ = sc::get<double>("throttle_input_max", params, throttle_input_max_);
     thrust_min_ = sc::get<double>("thrust_min", params, thrust_min_);
     thrust_max_ = sc::get<double>("thrust_max", params, thrust_max_);
     delta_elevator_min_ = sc::get<double>("delta_elevator_min", params, delta_elevator_min_);
     delta_elevator_max_ = sc::get<double>("delta_elevator_max", params, delta_elevator_max_);
     delta_aileron_min_ = sc::get<double>("delta_aileron_min", params, delta_aileron_min_);
     delta_aileron_max_ = sc::get<double>("delta_aileron_max", params, delta_aileron_max_);
     delta_rudder_min_ = sc::get<double>("delta_rudder_min", params, delta_rudder_min_);
     delta_rudder_max_ = sc::get<double>("delta_rudder_max", params, delta_rudder_max_);
     // Aircraft dimensional specs
     b_ = sc::get<double>("wing_span", params, b_);
     S_ = sc::get<double>("surface_area_of_wing", params, S_);
     c_ = sc::get<double>("chord_length", params, c_);
     e_ = sc::get<double>("efficiency_factor", params, e_);
     AR_ = b_/c_;
     // Drag coefficients
     C_D0_ = sc::get<double>("C_D0", params, C_D0_);
     C_D_alpha_ = sc::get<double>("C_D_alpha", params, C_D_alpha_);
     C_D_delta_elevator_ = sc::get<double>("C_D_delta_elevator_", params, C_D_delta_elevator_);
     // Lift coefficients
     C_L0_ = sc::get<double>("C_L0", params, C_L0_);
     C_L_alpha_ = sc::get<double>("C_L_alpha", params, C_L_alpha_);
     C_LQ_ = sc::get<double>("C_LQ", params, C_LQ_);
     C_L_alpha_dot_ = sc::get<double>("C_L_alpha_dot", params, C_L_alpha_dot_);
     C_L_delta_elevator_ = sc::get<double>("C_L_delta_elevator", params, C_L_delta_elevator_);
     // Side force coefficients
     C_Y_beta_ = sc::get<double>("C_Y_beta", params, C_Y_beta_);
     C_Y_delta_rudder_ = sc::get<double>("C_Y_delta_rudder", params, C_Y_delta_rudder_);
     // Roll moment coefficients
     C_L_beta_ = sc::get<double>("C_L_beta", params, C_L_beta_);
     C_LP_ = sc::get<double>("C_LP", params, C_LP_);
     C_LR_ = sc::get<double>("C_LR", params, C_LR_);
     C_L_delta_aileron_ = sc::get<double>("C_L_delta_aileron", params, C_L_delta_aileron_);
     C_L_delta_rudder_ = sc::get<double>("C_L_delta_rudder", params, C_L_delta_rudder_);
     // Pitch moment coefficients
     C_M0_ = sc::get<double>("C_M0", params, C_M0_);
     C_MQ_ = sc::get<double>("C_MQ", params, C_MQ_);
     C_M_alpha_ = sc::get<double>("C_M_alpha", params, C_M_alpha_);
     C_M_alpha_dot_ = sc::get<double>("C_M_alpha_dot", params, C_M_alpha_dot_);
     C_M_delta_elevator_ = sc::get<double>("C_M_delta_elevator", params, C_M_delta_elevator_);
     // Yaw moment coefficients
     C_N_beta_ = sc::get<double>("C_N_beta", params, C_N_beta_);
     C_NP_ = sc::get<double>("C_NP", params, C_NP_);
     C_NR_ = sc::get<double>("C_NR", params, C_NR_);
     C_N_delta_aileron_ = sc::get<double>("C_N_delta_aileron", params, C_N_delta_aileron_);
     C_N_delta_rudder_ = sc::get<double>("C_N_delta_rudder", params, C_N_delta_rudder_);
     return true;
 }
bool scrimmage::motion::FixedWing6DOF::step (double time, double dt) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 267 of file FixedWing6DOF.cpp.
References scrimmage::Angles::angle_pi(), scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::set(), scrimmage::motion::U, scrimmage::motion::Uw, scrimmage::motion::V, scrimmage::motion::Vw, scrimmage::motion::W, scrimmage::motion::Ww, scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     // Get inputs and saturate
     throttle_ = clamp(vars_.input(throttle_idx_), -1.0, 1.0);
     thrust_ = scale<double>(throttle_, throttle_input_min_,
                             throttle_input_max_, thrust_min_, thrust_max_);
     delta_elevator_ = clamp(vars_.input(elevator_idx_), delta_elevator_min_, delta_elevator_max_);
     delta_aileron_ = clamp(vars_.input(aileron_idx_), delta_aileron_min_, delta_aileron_max_);
     delta_rudder_ = clamp(vars_.input(rudder_idx_), delta_rudder_min_, delta_rudder_max_);
     quat_body_ = rot_180_x_axis_ * state_->quat();
     quat_body_.set(sc::Angles::angle_pi(quat_body_.roll()+M_PI),
                    quat_body_.pitch(), quat_body_.yaw());
     quat_body_.normalize();
     Eigen::Vector3d local_lin_vel(state_->vel()(0), -state_->vel()(1), -state_->vel()(2));
     local_lin_vel = quat_body_.rotate_reverse(local_lin_vel);
     x_[U] = local_lin_vel(0);
     x_[V] = local_lin_vel(1);
     x_[W] = local_lin_vel(2);
     Eigen::Vector3d local_ang_vel(state_->ang_vel()(0), -state_->ang_vel()(1), -state_->ang_vel()(2));
     local_ang_vel = quat_body_.rotate_reverse(local_ang_vel);
     x_[P] = local_ang_vel(0);
     x_[Q] = local_ang_vel(1);
     x_[R] = local_ang_vel(2);
     x_[Uw] = state_->vel()(0);
     x_[Vw] = state_->vel()(1);
     x_[Ww] = state_->vel()(2);
     x_[Xw] = state_->pos()(0);
     x_[Yw] = state_->pos()(1);
     x_[Zw] = state_->pos()(2);
     x_[q0] = quat_body_.w();
     x_[q1] = quat_body_.x();
     x_[q2] = quat_body_.y();
     x_[q3] = quat_body_.z();
     x_[U_dot] = linear_accel_body_(0);
     x_[V_dot] = linear_accel_body_(1);
     x_[W_dot] = linear_accel_body_(2);
     x_[P_dot] = ang_accel_body_(0);
     x_[Q_dot] = ang_accel_body_(1);
     x_[R_dot] = ang_accel_body_(2);
     // Cache values to calculate changes:
     Eigen::Vector3d prev_linear_vel_ENU(x_[Uw], x_[Vw], x_[Ww]);
     Eigen::Vector3d prev_angular_vel(x_[P], x_[Q], x_[R]);
     alpha_ = atan2(x_[W], x_[U]); // angle of attack
     // TODO: Need to compute alpha_dot without using alpha_prev_
     alpha_dot_ = 0;
     // alpha_dot_ = (alpha_ - alpha_prev_) / dt;
     // alpha_prev_ = alpha_;
     if (time > launch_time_)
         launch_command_ = 1;
     // Eigen::Vector3d F_catapult_NED(0, 0, 0);
     Eigen::Vector3d F_catapult(0, 0, 0);
     double launch_duration = launch_speed_/launch_accel_;
     switch (launch_state_) {
     case PRELAUNCH:
         if (launch_command_) {
             launch_state_ = LAUNCH;
             launch_start_t_ = time;
         }
         break;
     case LAUNCH:
         F_catapult(0) = launch_accel_ * mass_;
         if (launch_duration < time - launch_start_t_) {
             launch_state_ = POSTLAUNCH;
         }
         break;
     case POSTLAUNCH:
         // normal operation
         break;
     }
     // Apply any external forces (todo)
     // force_ext_body_ = quat_body_.rotate_reverse(ext_force_);
     // ext_force_ = Eigen::Vector3d::Zero(); // reset ext_force_ member variable
     force_ext_body_ = F_catapult;
     ode_step(dt);
     quat_body_.set(x_[q0], x_[q1], x_[q2], x_[q3]);
     quat_body_.normalize();
     linear_vel_body_ << x_[U], x_[V], x_[W];
     ang_vel_body_ << x_[P], x_[Q], x_[R];
     // Calculate change in velocity to populate acceleration elements
     Eigen::Vector3d linear_vel_ENU(x_[Uw], x_[Vw], x_[Ww]);
     Eigen::Vector3d linear_acc_ENU = (linear_vel_ENU - prev_linear_vel_ENU) / dt;
     Eigen::Vector3d angular_vel(x_[P], x_[Q], x_[R]);
     Eigen::Vector3d angular_acc = (angular_vel - prev_angular_vel) / dt;
     Eigen::Vector3d angular_acc_FLU(angular_acc(0), -angular_acc(1), -angular_acc(2));
     // Rotate back to Z-axis pointing up
     state_->quat() = rot_180_x_axis_ * quat_body_;
     state_->quat().set(sc::Angles::angle_pi(state_->quat().roll()+M_PI),
                        state_->quat().pitch(), state_->quat().yaw());
     state_->quat().normalize();
     Eigen::Vector3d angvel_b_e_bodyRef = quat_body_.rotate(angular_vel);
     Eigen::Vector3d angvel_b_e_ENU;
     angvel_b_e_ENU << angvel_b_e_bodyRef(0), -angvel_b_e_bodyRef(1), -angvel_b_e_bodyRef(2);
     state_->pos() = Eigen::Vector3d(x_[Xw], x_[Yw], x_[Zw]);
     state_->vel() = linear_vel_ENU;
     state_->ang_vel() = angvel_b_e_ENU;
     linear_accel_body_ = state_->quat().rotate_reverse(linear_acc_ENU);
     ang_accel_body_ = angular_acc_FLU;
     // draw velocity
     if (draw_vel_) {
         sc::ShapePtr line(new sp::Shape());
         line->set_opacity(1.0);
         sc::set(line->mutable_color(), 255, 0, 0);
         sc::set(line->mutable_line()->mutable_start(), state_->pos());
         sc::set(line->mutable_line()->mutable_end(), state_->pos() + state_->vel());
         draw_shape(line);
     }
     // draw angular velocity
     if (draw_ang_vel_) {
         sc::ShapePtr line(new sp::Shape());
         line->set_opacity(1.0);
         sc::set(line->mutable_color(), 0, 255, 0);
         sc::set(line->mutable_line()->mutable_start(), state_->pos());
         sc::set(line->mutable_line()->mutable_end(), state_->pos() + state_->ang_vel());
         draw_shape(line);
     }
     if (write_csv_) {
         double beta = atan2(x_[V], x_[U]); // side slip
         // Log state to CSV
         csv_.append(sc::CSV::Pairs{
                 {"t", time},
                 {"x", x_[Xw]},
                 {"y", x_[Yw]},
                 {"z", x_[Zw]},
                 {"U", x_[U]},
                 {"V", x_[V]},
                 {"W", x_[W]},
                 {"alpha", alpha_},
                 {"alpha_dot", alpha_dot_},
                 {"beta", beta},
                 {"P", x_[P]},
                 {"Q", x_[Q]},
                 {"R", x_[R]},
                 {"Ax_b", linear_accel_body_(0)},
                 {"Ay_b", linear_accel_body_(1)},
                 {"Az_b", linear_accel_body_(2)},
                 {"AngAccelx_b", ang_accel_body_(0)},
                 {"AngAccely_b", ang_accel_body_(1)},
                 {"AngAccelz_b", ang_accel_body_(2)},
                 {"roll", quat_body_.roll()},
                 {"pitch", quat_body_.pitch()},
                 {"yaw", quat_body_.yaw()},
                 {"throttle", throttle_},
                 {"thrust", thrust_},
                 {"elevator", delta_elevator_},
                 {"aileron", delta_aileron_},
                 {"rudder", delta_rudder_}});
     }
     return true;
 }
void scrimmage::motion::FixedWing6DOF::teleport (StatePtr & state) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 559 of file FixedWing6DOF.cpp.
{
     state_ = state;
 }
void scrimmage::motion::FixedWing6DOF::model (const vector_t & x, vector_t & dxdt, double t) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 443 of file FixedWing6DOF.cpp.
References scrimmage::motion::P, scrimmage::motion::Q, scrimmage::motion::q0, scrimmage::motion::q1, scrimmage::motion::q2, scrimmage::motion::q3, scrimmage::motion::R, scrimmage::Quaternion::rotate(), scrimmage::motion::U, scrimmage::motion::Uw, scrimmage::motion::V, scrimmage::motion::Vw, scrimmage::motion::W, scrimmage::motion::Ww, scrimmage::motion::Xw, scrimmage::motion::Yw, and scrimmage::motion::Zw.
{
     // Calculate velocity magnitude (handle zero velocity)
     double V_tau = sqrt(pow(x_[U], 2) + pow(x_[V], 2) + pow(x_[W], 2));
     if (std::abs(V_tau) < std::numeric_limits<double>::epsilon()) {
         V_tau = 0.00001;
     }
     // Calculate commonly used quantities
     double beta = atan2(x_[V], x_[U]); // side slip
     // double delta_Ve = 0.05*V_tau; // wind velocity across tail of aircraft (approximation)
     // double VtauVe = pow((V_tau + delta_Ve)/V_tau, 2);
     double pVtS = rho_ * pow(V_tau, 2) * S_ / 2.0;
     // Calculate lift, drag, and side_force magnitudes
     double CL = (C_L0_ + C_L_alpha_*alpha_ + C_LQ_*x_[Q] * c_ / (2*V_tau) +
                    C_L_alpha_dot_ * alpha_dot_ * c_ / (2*V_tau) +
                    C_L_delta_elevator_ * delta_elevator_);
     double lift = CL * pVtS;
     double drag = (C_D0_ + C_D_alpha_*std::abs(alpha_) + CL*CL/(M_PI*AR_*e_) +
                    C_D_delta_elevator_*std::abs(delta_elevator_)) * pVtS;
     double side_force = (C_Y_beta_*beta + C_Y_delta_rudder_*delta_rudder_) * pVtS;
     // Bring lift, drag, side_force magnitudes into body frame
     Eigen::Vector3d F_aero(lift*sin(alpha_) - drag*cos(alpha_) - side_force*sin(beta),
                            side_force*cos(beta),
                            -lift*cos(alpha_) - drag*sin(alpha_));
     // Calculate force from weight in body frame:
     Eigen::Vector3d gravity_vector(0, 0, +mass_*g_);
     Eigen::Vector3d F_weight = quat_body_.rotate_reverse(gravity_vector);
     Eigen::Vector3d F_thrust(thrust_, 0, 0);
     Eigen::Vector3d F_total = F_weight + F_thrust + F_aero;
     // simple ground contact model
     Eigen::Vector3d F_ground_W(0, 0, 0);
     Eigen::Vector3d F_ground(0, 0, 0);
     if (x_[Zw] < 0 && use_ground_model_) {
         double wn = 20;
         double Kp = wn*wn*mass_;
         double Kd = 2*wn;
         F_ground_W[2] = std::max(0.0, -Kp*(x_[Zw] - 0.0) - Kd*(x_[Ww] - 0.0));
         F_ground(0) =  F_ground_W(0);
         F_ground(1) = -F_ground_W(1);
         F_ground(2) = -F_ground_W(2);
         F_ground = quat_body_.rotate_reverse(F_ground);
         F_total += F_ground;
     }
     if (POSTLAUNCH != launch_state_) {
         F_total = force_ext_body_;
     }
     // Calculate body frame linear velocities
     dxdt[U] = x[V]*x[R] - x[W]*x[Q] + F_total(0) / mass_;
     dxdt[V] = x[W]*x[P] - x[U]*x[R] + F_total(1) / mass_;
     dxdt[W] = x[U]*x[Q] - x[V]*x[P] + F_total(2) / mass_;
     // Calculate moments;
     Eigen::Vector3d Moments_thrust(0, 0, 0); // no moment from thrust
     Eigen::Vector3d Moments_torque(0, 0, 0); // no moment from torque
     Eigen::Vector3d Moments_gyro(0, 0, 0);   // no moment from gyro effect
     // Calculate moments from aerodynamic forces
     Eigen::Vector3d Moments_aero((C_L_beta_*beta + C_LP_*x_[P]*b_/(2*V_tau) + C_LR_*x_[R]*b_/(2*V_tau) + C_L_delta_aileron_*delta_aileron_ + C_L_delta_rudder_*delta_rudder_) * pVtS*b_,
                                  (C_M0_ + C_M_alpha_*alpha_ + C_MQ_*x_[Q]*c_/(2*V_tau) + C_M_alpha_dot_*alpha_dot_*c_/(2*V_tau) + C_M_delta_elevator_*delta_elevator_) * pVtS*c_,
                                  (C_N_beta_*beta + C_NP_*x_[P]*b_/(2*V_tau) + C_NR_*x_[R]*b_/(2*V_tau) + C_N_delta_aileron_*delta_aileron_ + C_N_delta_rudder_*delta_rudder_) * pVtS*b_);
     // Sum moments
     Eigen::Vector3d Moments_total = Moments_aero + Moments_thrust +
         Moments_torque + Moments_gyro;
     if (POSTLAUNCH != launch_state_) {
         Moments_total == Eigen::Vector3d::Zero();
     }
     // Calculate rotational velocites
     Eigen::Vector3d pqr(x_[P], x_[Q], x_[R]);
     Eigen::Vector3d pqr_dot = I_inv_ * (Moments_total - pqr.cross(I_*pqr));
     dxdt[P] = pqr_dot(0);
     dxdt[Q] = pqr_dot(1);
     dxdt[R] = pqr_dot(2);
     // Compute quaternion derivatives
     double lambda = 1 - (pow(x[q0], 2) + pow(x[q1], 2) + pow(x[q2], 2) + pow(x[q3], 2));
     dxdt[q0] = -0.5 * (x[q1]*x[P] + x[q2]*x[Q] + x[q3]*x[R]) + lambda * x[q0];
     dxdt[q1] = +0.5 * (x[q0]*x[P] + x[q2]*x[R] - x[q3]*x[Q]) + lambda * x[q1];
     dxdt[q2] = +0.5 * (x[q0]*x[Q] + x[q3]*x[P] - x[q1]*x[R]) + lambda * x[q2];
     dxdt[q3] = +0.5 * (x[q0]*x[R] + x[q1]*x[Q] - x[q2]*x[P]) + lambda * x[q3];
     // Normalize quaternion
     sc::Quaternion quat(x[q0], x[q1], x[q2], x[q3]);
     quat.normalize();
     // Integrate local velocities to compute local positions
     Eigen::Vector3d vel_local(x[U], x[V], x[W]);
     Eigen::Vector3d vel_world = quat.rotate(vel_local); // rot * vel_local;
     dxdt[Xw] = vel_world(0);
     dxdt[Yw] = -vel_world(1); // Due to rotated frame
     dxdt[Zw] = -vel_world(2); // Due to rotated frame
     // Integrate local accelerations to compute global velocities
     Eigen::Vector3d acc_local = F_total / mass_;
     Eigen::Vector3d acc_world = quat.rotate(acc_local); // rot * acc_local;
     dxdt[Uw] = acc_world(0);
     dxdt[Vw] = -acc_world(1); // Due to rotated frame
     dxdt[Ww] = -acc_world(2); // Due to rotated frame
 }
Member Data Documentation
int scrimmage::motion::FixedWing6DOF::throttle_idx_ = 0 protected
Definition at line 96 of file FixedWing6DOF.h.
int scrimmage::motion::FixedWing6DOF::elevator_idx_ = 0 protected
Definition at line 97 of file FixedWing6DOF.h.
int scrimmage::motion::FixedWing6DOF::aileron_idx_ = 0 protected
Definition at line 98 of file FixedWing6DOF.h.
int scrimmage::motion::FixedWing6DOF::rudder_idx_ = 0 protected
Definition at line 99 of file FixedWing6DOF.h.
scrimmage::PID scrimmage::motion::FixedWing6DOF::heading_pid_ protected
Definition at line 101 of file FixedWing6DOF.h.
scrimmage::PID scrimmage::motion::FixedWing6DOF::alt_pid_ protected
Definition at line 102 of file FixedWing6DOF.h.
scrimmage::PID scrimmage::motion::FixedWing6DOF::vel_pid_ protected
Definition at line 103 of file FixedWing6DOF.h.
Eigen::VectorXd scrimmage::motion::FixedWing6DOF::ctrl_u_ protected
Definition at line 105 of file FixedWing6DOF.h.
Eigen::Matrix3d scrimmage::motion::FixedWing6DOF::I_ protected
Definition at line 107 of file FixedWing6DOF.h.
Eigen::Matrix3d scrimmage::motion::FixedWing6DOF::I_inv_ protected
Definition at line 108 of file FixedWing6DOF.h.
bool scrimmage::motion::FixedWing6DOF::draw_vel_ = false protected
Definition at line 111 of file FixedWing6DOF.h.
bool scrimmage::motion::FixedWing6DOF::draw_ang_vel_ = false protected
Definition at line 112 of file FixedWing6DOF.h.
bool scrimmage::motion::FixedWing6DOF::write_csv_ = false protected
Definition at line 115 of file FixedWing6DOF.h.
CSV scrimmage::motion::FixedWing6DOF::csv_ protected
Definition at line 116 of file FixedWing6DOF.h.
scrimmage::Quaternion scrimmage::motion::FixedWing6DOF::quat_body_ protected
Definition at line 118 of file FixedWing6DOF.h.
Eigen::Vector3d scrimmage::motion::FixedWing6DOF::force_ext_body_ protected
Definition at line 119 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::thrust_ = 0 protected
Definition at line 121 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::throttle_ = 0 protected
Definition at line 122 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_elevator_ = 0 protected
Definition at line 123 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_aileron_ = 0 protected
Definition at line 124 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_rudder_ = 0 protected
Definition at line 125 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::launch_command_ = 0 protected
Definition at line 126 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::alpha_ = 0 protected
Definition at line 128 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::alpha_dot_ = 0 protected
Definition at line 130 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::rho_ = 1.2250 protected
Definition at line 132 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::throttle_input_min_ = 0.0 protected
Definition at line 135 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::throttle_input_max_ = 1.0 protected
Definition at line 136 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::thrust_min_ = -100.0e3 protected
Definition at line 137 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::thrust_max_ = 100.0e3 protected
Definition at line 138 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_elevator_min_ = -0.5236 protected
Definition at line 139 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_elevator_max_ = 0.5236 protected
Definition at line 140 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_aileron_min_ = -0.5236 protected
Definition at line 141 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_aileron_max_ = 0.5236 protected
Definition at line 142 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_rudder_min_ = -0.2618 protected
Definition at line 143 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::delta_rudder_max_ = 0.2618 protected
Definition at line 144 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::b_ = 8.382 protected
Definition at line 146 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::S_ = 24.1548 protected
Definition at line 147 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::c_ = 3.29184 protected
Definition at line 148 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::e_ = .995 protected
Definition at line 149 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::AR_ = 2.5 protected
Definition at line 150 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_D0_ = 0.03 protected
Definition at line 152 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_D_alpha_ = 0.3 protected
Definition at line 153 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_D_delta_elevator_ = 0.01 protected
Definition at line 154 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L0_ = 0.28 protected
Definition at line 156 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_alpha_ = 3.45 protected
Definition at line 157 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_LQ_ = 0.0 protected
Definition at line 158 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_alpha_dot_ = 0.72 protected
Definition at line 159 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_delta_elevator_ = 0.36 protected
Definition at line 160 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_M0_ = 0.0 protected
Definition at line 162 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_MQ_ = -3.6 protected
Definition at line 163 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_M_alpha_ = -0.38 protected
Definition at line 164 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_M_alpha_dot_ = -1.1 protected
Definition at line 165 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_M_delta_elevator_ = -0.5 protected
Definition at line 166 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_Y_beta_ = -0.98 protected
Definition at line 168 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_Y_delta_rudder_ = 0.17 protected
Definition at line 169 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_beta_ = -0.12 protected
Definition at line 171 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_LP_ = -0.26 protected
Definition at line 172 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_LR_ = 0.14 protected
Definition at line 173 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_delta_aileron_ = 0.08 protected
Definition at line 174 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_L_delta_rudder_ = -0.105 protected
Definition at line 175 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_N_beta_ = 0.25 protected
Definition at line 177 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_NP_ = 0.022 protected
Definition at line 178 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_NR_ = -0.35 protected
Definition at line 179 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_N_delta_aileron_ = 0.06 protected
Definition at line 180 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::C_N_delta_rudder_ = 0.032 protected
Definition at line 181 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::launch_accel_ = 200 protected
Definition at line 183 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::launch_speed_ = 20 protected
Definition at line 184 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::launch_start_t_ = 0 protected
Definition at line 185 of file FixedWing6DOF.h.
double scrimmage::motion::FixedWing6DOF::launch_time_ = 30 protected
Definition at line 186 of file FixedWing6DOF.h.
LaunchState scrimmage::motion::FixedWing6DOF::launch_state_ = POSTLAUNCH protected
Definition at line 187 of file FixedWing6DOF.h.
Eigen::Vector3d scrimmage::motion::FixedWing6DOF::launch_dir_NED_ protected
Definition at line 188 of file FixedWing6DOF.h.
bool scrimmage::motion::FixedWing6DOF::use_ground_model_ = true protected
Definition at line 190 of file FixedWing6DOF.h.
Eigen::Quaterniond scrimmage::motion::FixedWing6DOF::rot_180_x_axis_ protected
Definition at line 192 of file FixedWing6DOF.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/FixedWing6DOF/FixedWing6DOF.h
/root/scrimmage/scrimmage/src/plugins/motion/FixedWing6DOF/FixedWing6DOF.cpp