SCRIMMAGE: scrimmage::External Class Reference
scrimmage::External Class Reference
#include <External.h>
Public Types
using ShapeQueue = std::queue< scrimmage_proto::ShapePtr >
Public Member Functions
External ()
EntityPtr & entity ()
bool create_entity (const std::string &mission_file, const std::string &entity_tag, const std::string &plugin_tags_str, int entity_id, int max_entities, double init_time, double init_dt, const std::string &log_dir, std::function< void(std::map< std::string, std::string > &)> param_override_func=[](std::map< std::string, std::string > &){}, const std::string &mission_file_overrides="", const int &debug_level=0)
void close ()
bool create_interactions ()
std::size_t & shape_queue_max_size ()
ShapeQueue & shape_queue ()
MissionParsePtr mp ()
bool send_messages ()
void print_plugins (std::ostream &out) const
ParameterServerPtr param_server ()
bool enable_outgoing_interface (const std::string &ip, const int &port)
bool disable_outgoing_interfaces ()
void set_time (const double &t, const double &dt)
bool step (double t)
PubSubPtr pubsub ()
Public Attributes
double motion_dt_ = 1
VariableIO vars
std::mutex mutex
DelayedTask update_contacts_task
Protected Member Functions
void setup_logging (const std::string &log_dir)
void update_ents ()
bool call_update_contacts (double t)
void update_time (double t)
Protected Attributes
EntityPtr entity_
bool enable_motion_ = false
std::list< EntityInteractionPtr > ent_inters_
std::list< MetricsPtr > metrics_
NetworkMapPtr networks_
PluginManagerPtr plugin_manager_
std::shared_ptr< Log > log_
double last_t_
PubSubPtr pubsub_
TimePtr time_
ParameterServerPtr param_server_
GlobalServicePtr global_services_
MissionParsePtr mp_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
std::list< EntityPtr > ents_
std::size_t shape_queue_max_size_
ShapeQueue shape_queue_
std::list< InterfacePtr > outgoing_interfaces_
Detailed Description
Definition at line 73 of file External.h.
Member Typedef Documentation
using scrimmage::External::ShapeQueue = std::queue<scrimmage_proto::ShapePtr>
Definition at line 94 of file External.h.
Constructor & Destructor Documentation
scrimmage::External::External ()
Definition at line 75 of file External.cpp.
                    :
     entity_(std::make_shared<Entity>()),
     plugin_manager_(std::make_shared<PluginManager>()),
     log_(std::make_shared<Log>()),
     last_t_(NAN),
     pubsub_(std::make_shared<PubSub>()),
     time_(std::make_shared<Time>()),
     param_server_(std::make_shared<ParameterServer>()),
     global_services_(std::make_shared<GlobalService>()),
     mp_(std::make_shared<MissionParse>()),
     id_to_team_map_(std::make_shared<std::unordered_map<int, int>>()),
     id_to_ent_map_(std::make_shared<std::unordered_map<int, EntityPtr>>()),
     shape_queue_max_size_(0) {}
Member Function Documentation
EntityPtr & scrimmage::External::entity ()
Definition at line 359 of file External.cpp.
References entity_.
{
     return entity_;
 }
bool scrimmage::External::create_entity (const std::string & mission_file, const std::string & entity_tag, const std::string & plugin_tags_str, int entity_id, int max_entities, double init_time, double init_dt, const std::string & log_dir, std::function< void(std::map< std::string, std::string > &)> param_override_func = [](std::map<std::string, std::string>&){}, const std::string & mission_file_overrides = "", const int & debug_level = 0)
Definition at line 106 of file External.cpp.
References scrimmage::VariableIO::add_input_variable(), call_update_contacts(), scrimmage::connect(), scrimmage::create_ent_inters(), scrimmage::create_metrics(), scrimmage::create_networks(), ent_inters_, entity_, scrimmage::SimUtilsInfo::file_search, scrimmage::FileSearch::find_mission(), global_services_, scrimmage::SimUtilsInfo::id_to_ent_map, id_to_ent_map_, scrimmage::SimUtilsInfo::id_to_team_map, id_to_team_map_, scrimmage::VariableIO::input_variable_index(), log_, metrics_, motion_dt_, scrimmage::SimUtilsInfo::mp, mp_, networks_, param_server_, scrimmage::SimUtilsInfo::plugin_manager, plugin_manager_, scrimmage::print_io_error(), scrimmage::SimUtilsInfo::pubsub, pubsub_, scrimmage::SimUtilsInfo::random, scrimmage::SimUtilsInfo::rtree, set_time(), setup_logging(), scrimmage::SimUtilsInfo::time, time_, vars, and scrimmage::verify_io_connection().
{
     // Find the mission file
     auto found_mission_file = FileSearch().find_mission(mission_file);
     if (not found_mission_file) {
         cout << "Failed to load mission file: " << mission_file << endl;
         return false;
     }
     // Parse the mission file
     mp_ = std::make_shared<MissionParse>();
     mp_->set_overrides(mission_file_overrides);
     if (not mp_->parse(*found_mission_file)) {
         cout << "Failed to parse mission file: " << *found_mission_file << endl;
         return false;
     }
     log_ = std::make_shared<Log>();
     setup_logging(log_dir);
     // Parse the entity name and find the entity block ID for the associated
     // entity name
     auto it_name_id = mp_->entity_tag_to_id().find(entity_tag);
     if (it_name_id == mp_->entity_tag_to_id().end()) {
         cout << "Entity name (" << entity_tag << ") not found in mission file"
              << endl;
         return false;
     }
     // If there aren't any networks defined, define the GlobalNetwork by
     // default.
     if (mp_->network_names().size() == 0) {
         mp_->network_names().push_back("GlobalNetwork");
     }
     set_time(init_time, init_dt);
     ContactMapPtr contacts = std::make_shared<ContactMap>();
     std::shared_ptr<RTree> rtree = std::make_shared<RTree>();
     rtree->init(max_entities);
     FileSearchPtr file_search = std::make_shared<FileSearch>();
     RandomPtr random = std::make_shared<Random>();
     random->seed();
     std::list<scrimmage_proto::ShapePtr> shapes;
     SimUtilsInfo sim_info;
     sim_info.mp = mp_;
     sim_info.plugin_manager = plugin_manager_;
     sim_info.file_search = file_search;
     sim_info.rtree = rtree;
     sim_info.pubsub = pubsub_;
     sim_info.time = time_;
     sim_info.random = random;
     sim_info.id_to_team_map = id_to_team_map_;
     sim_info.id_to_ent_map = id_to_ent_map_;
     auto plugin_tags = str2container<std::set<std::string>>(plugin_tags_str, ", ");
     networks_ = std::make_shared<NetworkMap>();
     if (!create_networks(sim_info, *networks_, plugin_tags, param_override_func)) {
         std::cout << "External::create_entity() failed on create_networks()" << std::endl;
         return false;
     }
     metrics_.clear();
     if (!create_metrics(sim_info, contacts, metrics_, plugin_tags, param_override_func)) {
         std::cout << "External::create_entity() failed on create_metrics()" << std::endl;
         return false;
     }
     ent_inters_.clear();
     if (!create_ent_inters(sim_info, contacts, shapes, ent_inters_, global_services_, plugin_tags, param_override_func)) {
         std::cout << "External::create_entity() failed on create_ent_inters()" << std::endl;
         return false;
     }
     entity_ = std::make_shared<Entity>();
     entity_->set_random(random);
     entity_->contacts() = contacts;
     entity_->rtree() = rtree;
     entity_->state() = std::make_shared<State>();
     call_update_contacts(time_->t());
     auto it = entity_->contacts()->find(entity_id);
     if (it != entity_->contacts()->end()) {
         mp_->entity_descriptions()[it_name_id->second]["team_id"] = std::to_string(it->second.id().team_id());
     }
     std::map<std::string, std::string> info =
         mp_->entity_descriptions()[it_name_id->second];
     AttributeMap &attr_map = mp_->entity_attributes()[it_name_id->second];
     bool ent_success =
         entity_->init(
             attr_map, info, id_to_team_map_, id_to_ent_map_, contacts, mp_,
             mp_->projection(), entity_id,
             it_name_id->second, plugin_manager_, file_search, rtree, pubsub_,
             time_, param_server_, global_services_, plugin_tags,
             param_override_func, debug_level);
     if (!ent_success) {
         std::cout << "External::create_entity() failed on entity_->init()" << std::endl;
         return false;
     }
     motion_dt_ = mp_->dt() * 1.0 / mp_->motion_multiplier();
     if (entity_->controllers().size() > 0) {
         // if vars is not set then we assume it should match the last controller.
         // we need to make sure we do not mess up the order of the indexes
         // because the controller outputs have already been declared
         auto &ctrl = entity_->controllers().back();
         auto &var_idx = ctrl->vars().output_variable_index();
         if (vars.input_variable_index().empty()) {
             int idx = 0;
             auto matches_idx = [&](auto &kv) {return kv.second == idx;};
             auto it = br::find_if(var_idx, matches_idx);
             while (it != var_idx.end()) {
                 vars.add_input_variable(it->first);
                 // cppcheck-suppress unreadVariable
                 idx++;
                 it = br::find_if(var_idx, matches_idx);
             }
         }
         connect(ctrl->vars(), vars);
         if (!verify_io_connection(entity_->controllers().back()->vars(), vars)) {
             std::cout << "VariableIO Error: "
                       << ctrl->name()
                       << " does not provide inputs required by the External class."
                       << std::endl;
             print_io_error("External", vars);
             std::cout << ctrl->name() << " currently provides the following: ";
             br::copy(var_idx | ba::map_keys,
                      std::ostream_iterator<std::string>(std::cout, ", "));
             return false;
         }
     }
     return true;
 }
void scrimmage::External::close ()
Definition at line 445 of file External.cpp.
References ent_inters_, entity_, metrics_, mutex, and time_.
                      {
     mutex.lock();
     entity_->close(time_->t());
     entity_ = std::make_shared<Entity>();
     auto close = [&](auto p) {p->close(time_->t());};
     br::for_each(ent_inters_, close);
     br::for_each(metrics_, close);
     mutex.unlock();
 }
bool scrimmage::External::create_interactions ()
std::size_t& scrimmage::External::shape_queue_max_size () inline
Definition at line 93 of file External.h.
References shape_queue_max_size_.
Referenced by step().
 { return shape_queue_max_size_; }
ShapeQueue& scrimmage::External::shape_queue () inline
Definition at line 95 of file External.h.
References shape_queue_.
 { return shape_queue_; }
MissionParsePtr scrimmage::External::mp ()
Definition at line 416 of file External.cpp.
References mp_.
{
     return mp_;
 }
bool scrimmage::External::send_messages ()
Definition at line 363 of file External.cpp.
References scrimmage::Publisher::callback, ent_inters_, entity_, metrics_, networks_, pubsub_, and scrimmage::run_callbacks().
Referenced by pubsub(), and step().
{
     // Send messages that are published by a SCRIMMAGE plugin to the external
     // network (e.g., ROS, MOOS)
     auto to_publisher = [&](auto &network_device) {return std::dynamic_pointer_cast<Publisher>(network_device);};
     auto has_callback = [&](auto &pub) {return pub && pub->callback;};
     for (auto &topic_device_kv : pubsub_->pubs() | ba::map_values) {
         for (auto &dev_list : topic_device_kv | ba::map_values) {
             for (auto pub : dev_list |
                             ba::transformed(to_publisher) |
                             ba::filtered(has_callback)) {
                 for (auto msg : pub->pop_msgs()) {
                     pub->callback(msg);
                 }
             }
         }
     }
     // any messages that are not linked to the external network can now
     // be sent via the internal scrimmage messaging system
     auto &pubs = pubsub_->pubs();
     auto &subs = pubsub_->subs();
     for (auto &network : *networks_ | ba::map_values) {
         auto name = network->name();
         if (!network->step(pubs[name], subs[name])) {
             std::cout << "Network failed: " << name << std::endl;
             return false;
         }
     }
     br::for_each(entity_->autonomies(), run_callbacks);
     br::for_each(entity_->controllers(), run_callbacks);
     br::for_each(ent_inters_, run_callbacks);
     br::for_each(metrics_, run_callbacks);
     br::for_each(entity_->sensors() | ba::map_values, run_callbacks);
     return true;
 }
void scrimmage::External::print_plugins (std::ostream & out) const
Definition at line 89 of file External.cpp.
References ent_inters_, entity_, metrics_, and networks_.
{
     out << "====== SCRIMMAGE Plugins Loaded =======" << endl;
     out << "----------- Network ------------" << endl;
     for (auto &kv : *networks_) {
         out << kv.first << endl;
     }
     out << "------ Entity Interaction ------" << endl;
     for (EntityInteractionPtr ei:  ent_inters_) {
         out << ei->name() << endl;
     }
     out << "----------- Metrics ------------" << endl;
     for (MetricsPtr m : metrics_) {
         out << m->name() << endl;
     }
     entity_->print_plugins(out);
 }
ParameterServerPtr scrimmage::External::param_server () inline
Definition at line 105 of file External.h.
References disable_outgoing_interfaces(), enable_outgoing_interface(), param_server_, set_time(), setup_logging(), and update_ents().
 { return param_server_; }
bool scrimmage::External::enable_outgoing_interface (const std::string & ip, const int & port)
Definition at line 456 of file External.cpp.
References scrimmage::Interface::client, entity_, and outgoing_interfaces_.
Referenced by param_server().
{
     InterfacePtr interface = std::make_shared<Interface>();
     interface->init_network(Interface::client, ip, port);
     interface->send_contact_visual(entity_->contact_visual());
     outgoing_interfaces_.push_back(interface);
     return true;
 }
bool scrimmage::External::disable_outgoing_interfaces ()
Definition at line 465 of file External.cpp.
References outgoing_interfaces_.
Referenced by param_server().
{
     outgoing_interfaces_.clear();
     return true;
 }
void scrimmage::External::set_time (const double & t, const double & dt)
Definition at line 470 of file External.cpp.
References time_.
Referenced by create_entity(), and param_server().
{
     time_->set_t(t);
     time_->set_dt(dt);
 }
void scrimmage::External::setup_logging (const std::string & log_dir) protected
Definition at line 257 of file External.cpp.
References log_, mp_, and scrimmage::Log::WRITE.
Referenced by create_entity(), and param_server().
{
     mp_->set_log_dir(log_dir);
     std::string output_type = get("output_type", mp_->params(), std::string("all"));
     mp_->create_log_dir();
     bool enable_log =
         output_type.find("all") != std::string::npos ||
         output_type.find("frames") != std::string::npos;
     log_->set_enable_log(enable_log);
     log_->init(mp_->log_dir(), Log::WRITE);
 }
void scrimmage::External::update_ents () protected
Definition at line 420 of file External.cpp.
References ent_inters_, entity_, ents_, scrimmage::ID::id(), id_to_ent_map_, id_to_team_map_, and metrics_.
Referenced by call_update_contacts(), param_server(), and step().
{
     if (ent_inters_.empty() && !metrics_.empty()) return;
     auto &contacts = *entity_->contacts();
     id_to_team_map_->clear();
     id_to_ent_map_->clear();
     ents_.clear();
     for (auto &kv : contacts) {
         ID &id = kv.second.id();
         (*id_to_team_map_)[id.id()] = id.team_id();
         auto ent = id.id() == entity_->id().id() ? entity_ : std::make_shared<Entity>();
         ent->id() = id;
         if (ent->state()) {
             *ent->state() = *kv.second.state();
         } else {
             ent->state() = kv.second.state();
         }
         ents_.push_back(ent);
         (*id_to_ent_map_)[id.id()] = ent;
     }
 }
bool scrimmage::External::step (double t)
Definition at line 271 of file External.cpp.
References call_update_contacts(), scrimmage::create_frame(), enable_motion_, ent_inters_, entity_, ents_, last_t_, log_, metrics_, motion_dt_, mutex, outgoing_interfaces_, send_messages(), shape_queue_, shape_queue_max_size(), time_, and update_ents().
{
     mutex.lock();
     double dt = std::isnan(last_t_) ? 0 : t - last_t_;
     time_->set_t(t);
     time_->set_dt(dt);
     last_t_ = t;
     mutex.unlock();
     if (!this->call_update_contacts(t)) return false;
     mutex.lock();
     // run main loops of plugins
     for (AutonomyPtr autonomy : entity_->autonomies()) {
         autonomy->step_autonomy(t, dt);
     }
     for (const auto &kv : entity_->sensors()) {
         SensorPtr sensor = kv.second;
         sensor->step();
     }
     entity_->setup_desired_state();
     int num_steps = std::max(1.0, std::round(dt / motion_dt_));
     double temp_t = t - dt;
     for (int i = 0; i < num_steps; i++) {
         for (ControllerPtr controller : entity_->controllers()) {
             controller->step(temp_t, motion_dt_);
         }
         if (enable_motion_) {
             entity_->motion()->step(temp_t, motion_dt_);
         }
         temp_t += motion_dt_;
     }
     if (!ent_inters_.empty()) {
         update_ents();
         for (EntityInteractionPtr ent_inter : ent_inters_) {
             ent_inter->step_entity_interaction(ents_, t, dt);
         }
     }
     for (MetricsPtr metrics : metrics_) {
         metrics->step_metrics(t, dt);
     }
     if (!send_messages()) {mutex.unlock(); return false;}
     // shapes
     scrimmage_proto::Shapes shapes;
     shapes.set_time(t);
     auto add_clear_shapes = [&](auto p) {
         auto add_shape = [&](auto &shape) {
             *shapes.add_shape() = *shape;
             shape_queue_.push(shape);
             auto max_size = this->shape_queue_max_size();
             if (shape_queue_.size() > max_size) {
                 shape_queue_.pop();
             }
         };
         br::for_each(p->shapes(), add_shape);
         p->shapes().clear(); // don't let shapes build up
     };
     br::for_each(entity_->autonomies(), add_clear_shapes);
     br::for_each(entity_->controllers(), add_clear_shapes);
     br::for_each(entity_->sensors() | ba::map_values, add_clear_shapes);
     br::for_each(ent_inters_, add_clear_shapes);
     br::for_each(metrics_, add_clear_shapes);
     log_->save_frame(create_frame(t, entity_->contacts()));
     log_->save_shapes(shapes);
     // Send shapes over configured grpc network interfaces
     for (auto interface : outgoing_interfaces_) {
         interface->send_shapes(shapes);
         interface->send_frame(t, entity_->contacts());
     }
     mutex.unlock();
     return true;
 }
PubSubPtr scrimmage::External::pubsub () inline
Definition at line 138 of file External.h.
References scrimmage::SubscriberBase::accept(), call_update_contacts(), scrimmage::Publisher::callback, pubsub_, send_messages(), and update_time().
{
         return pubsub_;
     }
bool scrimmage::External::call_update_contacts (double t) protected
Definition at line 401 of file External.cpp.
References entity_, mutex, scrimmage::DelayedTask::update(), update_contacts_task, and update_ents().
Referenced by create_entity(), pubsub(), and step().
{
     mutex.lock();
     if (update_contacts_task.update(t).first) {
         auto rtree = entity_->rtree(); // rtree is a shared_ptr
         if (!rtree) {mutex.unlock(); return false;}
         rtree->init(entity_->contacts()->size());
         for (auto &kv : *entity_->contacts()) {
             rtree->add(kv.second.state()->pos(), kv.second.id());
         }
         update_ents();
     }
     mutex.unlock();
     return true;
 }
void scrimmage::External::update_time (double t) protected
Referenced by pubsub().
Member Data Documentation
double scrimmage::External::motion_dt_ = 1
Definition at line 91 of file External.h.
Referenced by create_entity(), and step().
VariableIO scrimmage::External::vars
Definition at line 97 of file External.h.
Referenced by create_entity().
std::mutex scrimmage::External::mutex
Definition at line 98 of file External.h.
Referenced by call_update_contacts(), close(), and step().
DelayedTask scrimmage::External::update_contacts_task
Definition at line 99 of file External.h.
Referenced by call_update_contacts().
EntityPtr scrimmage::External::entity_ protected
Definition at line 115 of file External.h.
Referenced by call_update_contacts(), close(), create_entity(), enable_outgoing_interface(), entity(), print_plugins(), send_messages(), step(), and update_ents().
bool scrimmage::External::enable_motion_ = false protected
Definition at line 116 of file External.h.
Referenced by step().
std::list<EntityInteractionPtr> scrimmage::External::ent_inters_ protected
Definition at line 117 of file External.h.
Referenced by close(), create_entity(), print_plugins(), send_messages(), step(), and update_ents().
std::list<MetricsPtr> scrimmage::External::metrics_ protected
Definition at line 118 of file External.h.
Referenced by close(), create_entity(), print_plugins(), send_messages(), step(), and update_ents().
NetworkMapPtr scrimmage::External::networks_ protected
Definition at line 119 of file External.h.
Referenced by create_entity(), print_plugins(), and send_messages().
PluginManagerPtr scrimmage::External::plugin_manager_ protected
Definition at line 121 of file External.h.
Referenced by create_entity().
std::shared_ptr<Log> scrimmage::External::log_ protected
Definition at line 122 of file External.h.
Referenced by create_entity(), setup_logging(), and step().
double scrimmage::External::last_t_ protected
Definition at line 123 of file External.h.
Referenced by step().
PubSubPtr scrimmage::External::pubsub_ protected
Definition at line 124 of file External.h.
Referenced by create_entity(), pubsub(), and send_messages().
TimePtr scrimmage::External::time_ protected
Definition at line 125 of file External.h.
Referenced by close(), create_entity(), set_time(), and step().
ParameterServerPtr scrimmage::External::param_server_ protected
Definition at line 126 of file External.h.
Referenced by create_entity(), and param_server().
GlobalServicePtr scrimmage::External::global_services_ protected
Definition at line 127 of file External.h.
Referenced by create_entity().
MissionParsePtr scrimmage::External::mp_ protected
Definition at line 128 of file External.h.
Referenced by create_entity(), mp(), and setup_logging().
std::shared_ptr<std::unordered_map<int, int> > scrimmage::External::id_to_team_map_ protected
Definition at line 129 of file External.h.
Referenced by create_entity(), and update_ents().
std::shared_ptr<std::unordered_map<int, EntityPtr> > scrimmage::External::id_to_ent_map_ protected
Definition at line 130 of file External.h.
Referenced by create_entity(), and update_ents().
std::list<EntityPtr> scrimmage::External::ents_ protected
Definition at line 131 of file External.h.
Referenced by step(), and update_ents().
std::size_t scrimmage::External::shape_queue_max_size_ protected
Definition at line 133 of file External.h.
Referenced by shape_queue_max_size().
ShapeQueue scrimmage::External::shape_queue_ protected
Definition at line 134 of file External.h.
Referenced by shape_queue(), and step().
std::list<InterfacePtr> scrimmage::External::outgoing_interfaces_ protected
Definition at line 348 of file External.h.
Referenced by disable_outgoing_interfaces(), enable_outgoing_interface(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/entity/External.h
/root/scrimmage/scrimmage/src/entity/External.cpp