SCRIMMAGE: scrimmage::interaction::MapGen2D Class Reference
scrimmage::interaction::MapGen2D Class Reference
#include <MapGen2D.h>
Public Member Functions
bool init (std::map< std::string, std::string > &mission_params, std::map< std::string, std::string > &plugin_params) override
bool step_entity_interaction (std::list< scrimmage::EntityPtr > &ents, double t, double dt) override
Public Member Functions inherited from scrimmage::EntityInteraction
virtual bool collision_exists (std::list< EntityPtr > &, Eigen::Vector3d &)
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Member Functions
std::shared_ptr< scrimmage_proto::Shape > connect_points (Eigen::Vector3d &p, Eigen::Vector3d &prev_p)
std::list< cv::Rect > find_rectangles (cv::Mat &img, int threshold)
Eigen::Vector3d img_xy_to_xyz (int x, int y, cv::Mat &img)
Protected Attributes
bool show_map_debug_
bool enable_map_boundary_
double wall_bottom_z_
double wall_height_
double resolution_
double occupied_thresh_
double x_origin_
double y_origin_
double z_origin_
scrimmage::PublisherPtr pub_shape_gen_
scrimmage::PublisherPtr pub_map_2d_info_
bool map_info_published_ = false
cv::Mat map_img_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 50 of file MapGen2D.h.
Member Function Documentation
bool scrimmage::interaction::MapGen2D::init (std::map< std::string, std::string > & mission_params, std::map< std::string, std::string > & plugin_params) override virtual
Reimplemented from scrimmage::EntityInteraction.
Definition at line 64 of file MapGen2D.cpp.
References scrimmage::set(), scrimmage::ConfigParse::set_required(), and scrimmage::str2container().
{
     pub_shape_gen_ = advertise("GlobalNetwork", "ShapeGenerated");
     pub_map_2d_info_ = advertise("GlobalNetwork", "Map2DInfo");
     show_map_debug_ = sc::get<bool>("show_map_debug", plugin_params,
                                     false);
     // Find the map params
     sc::ConfigParse map_parse;
     map_parse.set_required("filename");
     map_parse.set_required("resolution");
     sc::FileSearch file_search;
     std::map<std::string, std::string> overrides; // empty, no overrides
     if (!map_parse.parse(overrides, plugin_params["map"],
                             "SCRIMMAGE_DATA_PATH", file_search)) {
         cout << "Failed to find map: " << plugin_params["map"] << endl;
         return false;
     }
     resolution_ = sc::get<double>("resolution", map_parse.params(), 1.0);
     wall_bottom_z_ = sc::get<double>("wall_bottom_z", map_parse.params(), 0.0);
     wall_height_ = sc::get<double>("wall_height", map_parse.params(), 5.0);
     enable_map_boundary_ = sc::get<bool>("enable_map_boundary",
                                          map_parse.params(), false);
     occupied_thresh_ = sc::get<double>("occupied_thresh", map_parse.params(),
                                        0.65);
     x_origin_ = sc::get<double>("x_origin", map_parse.params(), 0);
     y_origin_ = sc::get<double>("y_origin", map_parse.params(), 0);
     z_origin_ = sc::get<double>("z_origin", map_parse.params(), 0);
     // Parse wall_color (default to blue)
     std::string color_str = sc::get<std::string>("wall_color",
                                                  map_parse.params(),
                                                  "0 0 255");
     // Parse wall color
     std::vector<int> color;
     bool color_status = sc::str2container(color_str, " ", color, 3);
     if (!color_status) {
         cout << "Warning: Failed to parse wall color." << endl;
         color = {0, 0, 255};
     }
     std::string filename = map_parse.params()["XML_DIR"] + "/" +
         map_parse.params()["filename"];
     map_img_ = cv::imread(filename, cv::IMREAD_COLOR);
     if (!map_img_.data) {
         cout << "Failed to open file: " << filename << endl;
         return false;
     }
     auto msg = std::make_shared<sc::Message<sp::Shapes>>();
     std::list<cv::Rect> rects = find_rectangles(map_img_, occupied_thresh_);
     for (cv::Rect rect : rects) {
         double x = rect.x * resolution_;
         double y = (map_img_.rows - rect.y) * resolution_;
         double width = rect.width * resolution_;
         double height = rect.height * resolution_;
         // Convert rectangle into cube shape
         Eigen::Vector3d center(x + width/2.0 + x_origin_,
                                y - height/2.0 + y_origin_,
                                wall_bottom_z_ + wall_height_ / 2.0 + z_origin_);
         sc::Quaternion quat(0, 0, 0);
         std::shared_ptr<sp::Shape> wall(new sp::Shape);
         sc::set(wall->mutable_color(), color[0], color[1], color[2]);
         wall->set_opacity(1.0);
         wall->set_persistent(true);
         sc::set(wall->mutable_cuboid()->mutable_center(), center);
         wall->mutable_cuboid()->set_x_length(width);
         wall->mutable_cuboid()->set_y_length(height);
         wall->mutable_cuboid()->set_z_length(wall_height_);
         sc::set(wall->mutable_cuboid()->mutable_quat(), quat);
         draw_shape(wall);
         sp::Shape *shape = msg->data.add_shape();
         *shape = *wall;
     }
     // Publish the shapes for visualization and physics
     cout << "Publishing shapes: " << msg->data.shape_size() << endl;
     pub_shape_gen_->publish(msg);
     return true;
 }
bool scrimmage::interaction::MapGen2D::step_entity_interaction (std::list< scrimmage::EntityPtr > & ents, double t, double dt) override virtual
Reimplemented from scrimmage::EntityInteraction.
Definition at line 159 of file MapGen2D.cpp.
{
     if (!map_info_published_) {
         map_info_published_ = true;
         // Populate and publish the map information
         auto msg_map2d = std::make_shared<sc::Message<Map2DInfo>>();
         msg_map2d->data.img = map_img_;
         msg_map2d->data.occupied_thresh = occupied_thresh_;
         msg_map2d->data.resolution = resolution_;
         msg_map2d->data.origin = Eigen::Vector3d(x_origin_, y_origin_, z_origin_);
         pub_map_2d_info_->publish(msg_map2d);
     }
     return true;
 }
std::shared_ptr<scrimmage_proto::Shape> scrimmage::interaction::MapGen2D::connect_points (Eigen::Vector3d & p, Eigen::Vector3d & prev_p) protected
std::list< cv::Rect > scrimmage::interaction::MapGen2D::find_rectangles (cv::Mat & img, int threshold) protected
Definition at line 177 of file MapGen2D.cpp.
{
     // Make sure image is gray and apply threshold
     cv::Mat gray;
     cv::cvtColor(img, gray, cv::COLOR_BGRA2GRAY);
     cv::Mat thresh;
     cv::threshold(gray, thresh, std::floor(threshold*255), 255,
                   cv::THRESH_BINARY_INV);
     cv::Mat img_rects = img.clone();
     std::list<cv::Rect> rects;
     cv::Mat I = thresh.clone();
     // Scan image looking for non-zero pixel
     for (int i = 0; i < I.rows; i++) {
         for (int j = 0; j < I.cols; j++) {
             if (I.at<uchar>(i, j) > 0) {
                 // Non-zero pixel found, search for largest rectangle of
                 // non-zero pixels
                 bool end_c_found = false;
                 int end_c = I.cols;
                 int end_r = I.rows;
                 // Scan rows and columns looking for a zero-valued pixel
                 for (int r = i; r < end_r; r++) {
                     for (int c = j; c < end_c; c++) {
                         if (I.at<uchar>(r, c) == 0) {
                             // Zero pixel found
                             if (!end_c_found) {
                                 // Use this column number as end column of
                                 // rectangle
                                 end_c_found = true;
                                 end_c = c;
                             } else {
                                 // Use this row number as end row of rectangle
                                 end_r = r;
                             }
                         }
                     }
                     if (end_c == I.cols) {
                         // If end_c is still the same as I.cols, then the
                         // rectangle extended to the end of the image.
                         end_c_found = true;
                     }
                 }
                 cv::Rect rect(j, i, end_c-j, end_r-i);
                 cv::rectangle(img_rects, rect, cv::Scalar(0, 0, 255), 1, 8, 0);
                 cv::Mat roi = I(rect);
                 roi.setTo(0);
                 rects.push_back(rect);
             }
         }
     }
     if (enable_map_boundary_) {
         rects.push_back(cv::Rect(0, 0, img.cols, 1)); // top rect
         rects.push_back(cv::Rect(0, 0, 1, img.rows)); // left rect
         rects.push_back(cv::Rect(img.cols, 0, 1, img.rows)); // right rect
         rects.push_back(cv::Rect(0, img.rows, img.cols, 1)); // bottom rect
     }
     if (show_map_debug_) {
         cout << "Number of rectangles: " << rects.size() << endl;
         cv::imshow("Original", img);
         cv::imshow("Gray", gray);
         cv::imshow("Thresh", thresh);
         cv::imshow("Rects", img_rects);
         cv::waitKey(0);
     }
     return rects;
 }
Eigen::Vector3d scrimmage::interaction::MapGen2D::img_xy_to_xyz (int x, int y, cv::Mat & img) protected
Member Data Documentation
bool scrimmage::interaction::MapGen2D::show_map_debug_ protected
Definition at line 65 of file MapGen2D.h.
bool scrimmage::interaction::MapGen2D::enable_map_boundary_ protected
Definition at line 66 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::wall_bottom_z_ protected
Definition at line 68 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::wall_height_ protected
Definition at line 69 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::resolution_ protected
Definition at line 70 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::occupied_thresh_ protected
Definition at line 71 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::x_origin_ protected
Definition at line 73 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::y_origin_ protected
Definition at line 74 of file MapGen2D.h.
double scrimmage::interaction::MapGen2D::z_origin_ protected
Definition at line 75 of file MapGen2D.h.
scrimmage::PublisherPtr scrimmage::interaction::MapGen2D::pub_shape_gen_ protected
Definition at line 77 of file MapGen2D.h.
scrimmage::PublisherPtr scrimmage::interaction::MapGen2D::pub_map_2d_info_ protected
Definition at line 78 of file MapGen2D.h.
bool scrimmage::interaction::MapGen2D::map_info_published_ = false protected
Definition at line 80 of file MapGen2D.h.
cv::Mat scrimmage::interaction::MapGen2D::map_img_ protected
Definition at line 82 of file MapGen2D.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/interaction/MapGen2D/MapGen2D.h
/root/scrimmage/scrimmage/src/plugins/interaction/MapGen2D/MapGen2D.cpp