SCRIMMAGE: scrimmage::DelayedTask Class Reference
scrimmage::DelayedTask Class Reference
repeats a task after a delay and some condition (if set) are met. The task can be set to repeat a finite number of times.
#include <DelayedTask.h>
Public Member Functions
DelayedTask ()
DelayedTask (double _delay, int repeats)
void set_delay_from_freq (double freq)
bool done () const
void set_repeats (int repeats_left)
void set_repeat_infinitely (bool repeat_infinitely)
std::pair< bool, bool > update (double t)
Public Attributes
bool disable
double delay
double last_updated_time
double end_time
double eps
std::function< bool(double)> condition
std::function< bool(double)> task
Protected Attributes
bool repeat_infinitely_
int repeats_left_
Detailed Description
repeats a task after a delay and some condition (if set) are met. The task can be set to repeat a finite number of times.
Definition at line 43 of file DelayedTask.h.
Constructor & Destructor Documentation
DelayedTask() [1/2]
scrimmage::DelayedTask::DelayedTask ()
Definition at line 39 of file DelayedTask.cpp.
 : DelayedTask(0, -1) {}
DelayedTask() [2/2]
scrimmage::DelayedTask::DelayedTask (double _delay, int repeats)
Definition at line 41 of file DelayedTask.cpp.
                                                    :
         disable(false),
         delay(_delay),
         last_updated_time(-std::numeric_limits<double>::infinity()),
         end_time(std::numeric_limits<double>::infinity()),
         eps(0.0),
         condition(nullptr),
         task(nullptr),
         repeat_infinitely_(true),
         repeats_left_(-1) {
     set_repeats(repeats);
 }
References set_repeats().
Member Function Documentation
set_delay_from_freq()
void scrimmage::DelayedTask::set_delay_from_freq (double freq)
Definition at line 54 of file DelayedTask.cpp.
{
     delay = freq > 0 ? 1 / freq : 0;
 }
References delay.
done()
bool scrimmage::DelayedTask::done () const
Definition at line 77 of file DelayedTask.cpp.
{
     return !repeat_infinitely_ && repeats_left_ < 0;
 }
References repeat_infinitely_, and repeats_left_.
Referenced by update().
set_repeats()
void scrimmage::DelayedTask::set_repeats (int repeats_left)
Definition at line 81 of file DelayedTask.cpp.
{
     repeats_left_ = repeats_left;
     repeat_infinitely_ = repeats_left_ < 0;
 }
References repeat_infinitely_, and repeats_left_.
Referenced by DelayedTask().
set_repeat_infinitely()
void scrimmage::DelayedTask::set_repeat_infinitely (bool repeat_infinitely)
Definition at line 86 of file DelayedTask.cpp.
{
     repeat_infinitely_ = repeat_infinitely;
     repeats_left_ = -1;
 }
References repeat_infinitely_, and repeats_left_.
Referenced by scrimmage::SimControl::start().
update()
std::pair< bool, bool > scrimmage::DelayedTask::update (double t)
Definition at line 58 of file DelayedTask.cpp.
{
     bool updated = false, task_success = true;
     const bool condition_satisfied = condition ? condition(t) : true;
     const bool time_good = t >= last_updated_time + delay - eps && t <= end_time + eps;
     if (!disable && !done() && condition_satisfied && time_good) {
         last_updated_time = t;
         if (task) {
             task_success = task(t);
         }
         if (!repeat_infinitely_) {
             repeats_left_--;
         }
         updated = true;
     }
     return std::make_pair(updated, task_success);
 }
References condition, delay, disable, done(), end_time, eps, last_updated_time, repeat_infinitely_, repeats_left_, and task.
Referenced by scrimmage::External::call_update_contacts(), scrimmage::SimControl::run_single_step(), and scrimmage::SimControl::start().
Member Data Documentation
disable
bool scrimmage::DelayedTask::disable
Definition at line 55 of file DelayedTask.h.
Referenced by scrimmage::SimControl::start(), and update().
delay
double scrimmage::DelayedTask::delay
Definition at line 56 of file DelayedTask.h.
Referenced by set_delay_from_freq(), scrimmage::SimControl::start(), and update().
last_updated_time
double scrimmage::DelayedTask::last_updated_time
Definition at line 57 of file DelayedTask.h.
Referenced by scrimmage::SimControl::start(), and update().
end_time
double scrimmage::DelayedTask::end_time
Definition at line 58 of file DelayedTask.h.
Referenced by scrimmage::SimControl::start(), and update().
eps
double scrimmage::DelayedTask::eps
Definition at line 59 of file DelayedTask.h.
Referenced by scrimmage::SimControl::start(), and update().
condition
std::function<bool(double)> scrimmage::DelayedTask::condition
Definition at line 60 of file DelayedTask.h.
Referenced by update().
task
std::function<bool(double)> scrimmage::DelayedTask::task
Definition at line 61 of file DelayedTask.h.
Referenced by scrimmage::SimControl::start(), and update().
repeat_infinitely_
bool scrimmage::DelayedTask::repeat_infinitely_ protected
Definition at line 64 of file DelayedTask.h.
Referenced by done(), set_repeat_infinitely(), set_repeats(), and update().
repeats_left_
int scrimmage::DelayedTask::repeats_left_ protected
Definition at line 65 of file DelayedTask.h.
Referenced by done(), set_repeat_infinitely(), set_repeats(), and update().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/common/DelayedTask.h
/root/scrimmage/scrimmage/src/common/DelayedTask.cpp