SCRIMMAGE: scrimmage::motion::JSBSimControl Class Reference
scrimmage::motion::JSBSimControl Class Reference
#include <JSBSimControl.h>
Public Member Functions
JSBSimControl ()
virtual std::tuple< int, int, int > version ()
bool init (std::map< std::string, std::string > &info, std::map< std::string, std::string > &params) override
bool step (double time, double dt) override
Public Member Functions inherited from scrimmage::motion::RigidBody6DOFBase
RigidBody6DOFBase ()
Eigen::Vector3d & linear_vel_body ()
Eigen::Vector3d & ang_vel_body ()
Eigen::Vector3d & linear_accel_body ()
Eigen::Vector3d & ang_accel_body ()
Public Member Functions inherited from scrimmage::MotionModel
MotionModel ()
std::string type () override
virtual bool posthumous (double t)
virtual StatePtr & state ()
virtual void set_state (StatePtr &state)
virtual void teleport (StatePtr &state)
virtual void set_external_force (const Eigen::Vector3d &force)
virtual void set_external_moment (const Eigen::Vector3d &moment)
virtual void set_mass (double mass)
virtual double mass ()
virtual double gravity_magnitude ()
virtual std::vector< double > & full_state_vector ()
void close (double t) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Additional Inherited Members
Public Types inherited from scrimmage::MotionModel
typedef std::vector< double > vector_t
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Protected Member Functions inherited from scrimmage::MotionModel
void ode_step (double dt)
virtual void model (const vector_t &x, vector_t &dxdt, double t)
Protected Attributes inherited from scrimmage::motion::RigidBody6DOFBase
Eigen::Vector3d linear_vel_body_
Eigen::Vector3d ang_vel_body_
Eigen::Vector3d linear_accel_body_
Eigen::Vector3d ang_accel_body_
Protected Attributes inherited from scrimmage::MotionModel
StatePtr state_
vector_t x_
Eigen::Vector3d ext_force_
Eigen::Vector3d ext_moment_
double mass_
double g_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Detailed Description
Definition at line 61 of file JSBSimControl.h.
Constructor & Destructor Documentation
scrimmage::motion::JSBSimControl::JSBSimControl ()
Definition at line 75 of file JSBSimControl.cpp.
References scrimmage::Angles::CCW, scrimmage::Angles::CW, scrimmage::Angles::Pos_X, scrimmage::Angles::Pos_Y, and scrimmage::Angles::set_input_clock_direction().
{
     angles_from_jsbsim_.set_input_clock_direction(ang::Rotate::CW);
     angles_from_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_Y);
     angles_from_jsbsim_.set_output_clock_direction(ang::Rotate::CCW);
     angles_from_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_input_clock_direction(ang::Rotate::CCW);
     angles_to_jsbsim_.set_input_zero_axis(ang::HeadingZero::Pos_X);
     angles_to_jsbsim_.set_output_clock_direction(ang::Rotate::CW);
     angles_to_jsbsim_.set_output_zero_axis(ang::HeadingZero::Pos_Y);
 }
Member Function Documentation
std::tuple< int, int, int > scrimmage::motion::JSBSimControl::version () virtual
Definition at line 87 of file JSBSimControl.cpp.
{
     return std::tuple<int, int, int>(0, 0, 1);
 }
bool scrimmage::motion::JSBSimControl::init (std::map< std::string, std::string > & info, std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 91 of file JSBSimControl.cpp.
References scrimmage::Angles::deg2rad(), feet2meters, meters2feet, and scrimmage::Angles::rad2deg().
{
     draw_vel_ = sc::get<double>("drawVel", params, 1.0);
     draw_ang_vel_ = sc::get<double>("drawAngVel", params, 10.0);
     draw_acc_ = sc::get<double>("drawAcc", params, 1.0);
     // Setup variable index for controllers
     throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::In);
     elevator_idx_ = vars_.declare(VariableIO::Type::elevator, VariableIO::Direction::In);
     aileron_idx_ = vars_.declare(VariableIO::Type::aileron, VariableIO::Direction::In);
     rudder_idx_ = vars_.declare(VariableIO::Type::rudder, VariableIO::Direction::In);
     exec_ = std::make_shared<JSBSim::FGFDMExec>();
     fg_out_enable_ = get<bool>("flightgear_output_enable", params, false);
     if (fg_out_enable_) {
         output_fg_ = new JSBSim::FGOutputFGMod(&(*exec_));
         std::string ip = get<std::string>("flightgear_ip", params, "localhost");
         std::string port = get<std::string>("flightgear_port", params, "5600");
         std::string protocol = get<std::string>("flightgear_protocol", params, "UDP");
         std::string name = ip + ":" + protocol + "/" + port; // localhost:UDP/5600
         output_fg_->SetIdx(0);
         output_fg_->SetOutputName(name);
         output_fg_->SetRateHz(60);
         output_fg_->InitModel();
     }
     exec_->SetDebugLevel(0);
     std::string jsbsim_root_dir = get<std::string>("jsbsim_root", params, info["JSBSIM_ROOT"]);
     if (jsbsim_root_dir == "") {
         exec_->SetRootDir(SGPath(info["JSBSIM_ROOT"]));
     } else {
         exec_->SetRootDir(SGPath(jsbsim_root_dir));
     }
     exec_->SetAircraftPath(SGPath("aircraft"));
     exec_->SetEnginePath(SGPath("engine"));
     exec_->SetSystemsPath(SGPath("systems"));
     exec_->LoadScript(SGPath("scripts/"+info["script_name"]));
     JSBSim::FGInitialCondition *ic = exec_->GetIC();
     Quaternion q_ned_enu(M_PI, 0.0, M_PI/2.0);
     Quaternion q_flu_frd(M_PI, 0.0, 0.0);
     Quaternion q_frd_enu(q_ned_enu * state_->quat() * q_flu_frd);
     ic->SetPsiRadIC(q_frd_enu.yaw());
     ic->SetThetaRadIC(q_frd_enu.pitch());
     ic->SetPhiRadIC(q_frd_enu.roll());
     ic->SetVEastFpsIC(state_->vel()[0] * meters2feet);
     ic->SetVNorthFpsIC(state_->vel()[1] * meters2feet);
     ic->SetVDownFpsIC(-state_->vel()[2] * meters2feet);
     ic->SetTerrainElevationFtIC(parent_->projection()->HeightOrigin() * meters2feet);
     Eigen::Vector3d lla;
     parent_->projection()->Reverse(state_->pos()[0], state_->pos()[1], state_->pos()[2], lla[0], lla[1], lla[2]);
     ic->SetLatitudeDegIC(lla[0]);
     ic->SetLongitudeDegIC(lla[1]);
     ic->SetAltitudeASLFtIC(lla[2] * meters2feet);
 #if 0
     cout << "--------------------------------------------------------" << endl;
     cout << "  State information in JSBSImControl" << endl;
     cout << "--------------------------------------------------------" << endl;
     int prec = 5;
     cout << std::setprecision(prec) << "state_->quat(): " << state_->quat() << endl;
     cout << std::setprecision(prec) << "lla[0]: " << lla[0] << endl;
     cout << std::setprecision(prec) << "lla[1]: " << lla[1] << endl;
     cout << std::setprecision(prec) << "lla[2]: " << lla[2] << endl;
     cout << std::setprecision(prec) << "lla[0]: " << lla[0] << endl;
     cout << std::setprecision(prec) << "lla[1]: " << lla[1] << endl;
     cout << std::setprecision(prec) << "lla[2]: " << lla[2] << endl;
     cout << std::setprecision(prec) << "GetVEastFpsIC: " << ic->GetVEastFpsIC() << endl;
     cout << std::setprecision(prec) << "GetVNorthFpsIC: " << ic->GetVNorthFpsIC() << endl;
     cout << std::setprecision(prec) << "GetVDownFpsIC: " << ic->GetVDownFpsIC() << endl;
     cout << std::setprecision(prec) << "GetPsiRadIC: " << ic->GetPsiRadIC() << endl;
     cout << std::setprecision(prec) << "GetThetaRadIC: " << ic->GetThetaRadIC() << endl;
     cout << std::setprecision(prec) << "GetPhiRadIC: " << ic->GetPhiRadIC() << endl;
     cout << std::setprecision(prec) << "GetLatitudeDegIC: " << ic->GetLatitudeDegIC() << endl;
     cout << std::setprecision(prec) << "GetLongitudeDegIC: " << ic->GetLongitudeDegIC() << endl;
     cout << std::setprecision(prec) << "GetAltitudeASLFtIC: " << ic->GetAltitudeASLFtIC() << endl;
 #endif
     if (info.count("latitude") > 0) {
         ic->SetLatitudeDegIC(std::stod(info["latitude"]));
     }
     if (info.count("longitude") > 0) {
         ic->SetLongitudeDegIC(std::stod(info["longitude"]));
     }
     if (info.count("heading") > 0) {
         angles_to_jsbsim_.set_angle(std::stod(info["heading"]));
         ic->SetPsiDegIC(angles_to_jsbsim_.angle());
     }
     if (info.count("altitude") > 0) {
         double alt_asl_meters = std::stod(info["altitude"]);
         ic->SetAltitudeASLFtIC(alt_asl_meters * meters2feet);
     }
     exec_->RunIC();
     exec_->Setdt(std::stod(info["dt"])/std::stod(info["motion_multiplier"]));
     exec_->Run();
     // Get references to each of the nodes that hold properties that we
     // care about
     JSBSim::FGPropertyManager* mgr = exec_->GetPropertyManager();
     longitude_node_ = mgr->GetNode("position/long-gc-deg");
     latitude_node_ = mgr->GetNode("position/lat-gc-deg");
     altitude_node_ = mgr->GetNode("position/h-sl-ft");
     altitudeAGL_node_ = mgr->GetNode("position/h-agl-ft");
     roll_node_ = mgr->GetNode("attitude/roll-rad");
     pitch_node_ = mgr->GetNode("attitude/pitch-rad");
     yaw_node_ = mgr->GetNode("attitude/heading-true-rad");
     ap_aileron_cmd_node_ = mgr->GetNode("fcs/aileron-cmd-norm");
     ap_elevator_cmd_node_ = mgr->GetNode("fcs/elevator-cmd-norm");
     ap_rudder_cmd_node_ = mgr->GetNode("fcs/rudder-cmd-norm");
     ap_throttle_cmd_node_ = mgr->GetNode("fcs/throttle-cmd-norm");
     vel_north_node_ = mgr->GetNode("velocities/v-north-fps");
     vel_east_node_ = mgr->GetNode("velocities/v-east-fps");
     vel_down_node_ = mgr->GetNode("velocities/v-down-fps");
     u_vel_node_ = mgr->GetNode("velocities/u-fps");
     // angular velocity in ECEF frame
     p_node_ = mgr->GetNode("velocities/p-rad_sec");
     q_node_ = mgr->GetNode("velocities/q-rad_sec");
     r_node_ = mgr->GetNode("velocities/r-rad_sec");
     // acceleration at pilot location in body frame
     ax_pilot_node_ = mgr->GetNode("accelerations/a-pilot-x-ft_sec2");
     ay_pilot_node_ = mgr->GetNode("accelerations/a-pilot-y-ft_sec2");
     az_pilot_node_ = mgr->GetNode("accelerations/a-pilot-z-ft_sec2");
     // Save state
     parent_->projection()->Forward(latitude_node_->getDoubleValue(),
                                   longitude_node_->getDoubleValue(),
                                   altitude_node_->getDoubleValue() * feet2meters,
                                   state_->pos()(0), state_->pos()(1), state_->pos()(2));
     angles_from_jsbsim_.set_angle(ang::rad2deg(yaw_node_->getDoubleValue()));
     state_->quat().set(roll_node_->getDoubleValue(),
                       -pitch_node_->getDoubleValue(),
                       ang::deg2rad(angles_from_jsbsim_.angle()));
     state_->vel() << vel_east_node_->getDoubleValue() * feet2meters,
         vel_north_node_->getDoubleValue() * feet2meters,
         -vel_down_node_->getDoubleValue() * feet2meters;
     Eigen::Vector3d ang_vel_FLU(p_node_->getDoubleValue(),
                                -q_node_->getDoubleValue(),
                                -r_node_->getDoubleValue());
     state_->ang_vel() = state_->quat().rotate(ang_vel_FLU);
     Eigen::Vector3d a_FLU(ax_pilot_node_->getDoubleValue(),
                          -ay_pilot_node_->getDoubleValue(),
                          -az_pilot_node_->getDoubleValue());
     linear_accel_body_ = state_->quat().rotate(a_FLU);
     return true;
 }
bool scrimmage::motion::JSBSimControl::step (double time, double dt) override virtual
Reimplemented from scrimmage::MotionModel.
Definition at line 261 of file JSBSimControl.cpp.
References scrimmage::Angles::deg2rad(), feet2meters, scrimmage::Angles::rad2deg(), and scrimmage::set().
{
     throttle_       = ba::clamp(vars_.input(throttle_idx_), -1.0, 1.0);
     delta_elevator_ = ba::clamp(vars_.input(elevator_idx_), -1.0, 1.0);
     delta_aileron_  = ba::clamp(vars_.input(aileron_idx_),  -1.0, 1.0);
     delta_rudder_   = ba::clamp(vars_.input(rudder_idx_),   -1.0, 1.0);
     // TODO: for some reason, jsb sim does not like it when there is an immediate thottle input
     if (time < .05)
         throttle_ = 0;
     ap_aileron_cmd_node_->setDoubleValue(delta_aileron_);
     ap_elevator_cmd_node_->setDoubleValue(delta_elevator_);
     ap_rudder_cmd_node_->setDoubleValue(delta_rudder_);
     ap_throttle_cmd_node_->setDoubleValue(throttle_);
     exec_->Setdt(dt);
     exec_->Run();
     // Save state
     parent_->projection()->Forward(latitude_node_->getDoubleValue(),
                                   longitude_node_->getDoubleValue(),
                                   altitude_node_->getDoubleValue() * feet2meters,
                                   state_->pos()(0), state_->pos()(1), state_->pos()(2));
     angles_from_jsbsim_.set_angle(ang::rad2deg(yaw_node_->getDoubleValue()));
     state_->quat().set(roll_node_->getDoubleValue(),
                       -pitch_node_->getDoubleValue(),
                       ang::deg2rad(angles_from_jsbsim_.angle()));
     state_->vel() << vel_east_node_->getDoubleValue() * feet2meters,
         vel_north_node_->getDoubleValue() * feet2meters,
         -vel_down_node_->getDoubleValue() * feet2meters;
     Eigen::Vector3d ang_vel_FLU(p_node_->getDoubleValue(),
                                -q_node_->getDoubleValue(),
                                -r_node_->getDoubleValue());
     state_->ang_vel() = state_->quat().rotate(ang_vel_FLU);
     Eigen::Vector3d a_FLU(ax_pilot_node_->getDoubleValue() * feet2meters,
                          -ay_pilot_node_->getDoubleValue() * feet2meters,
                          -az_pilot_node_->getDoubleValue() * feet2meters);
     // TODO: jsbsim returns specific force, but need to populate this value with
     // acceleration. Need to make gravity not a hard-coded value or find a better
     // way to handle this.
     a_FLU = a_FLU + state_->quat().rotate_reverse(Eigen::Vector3d(0, 0, -9.81));
     linear_accel_body_ = a_FLU;
     Eigen::Vector3d a_ENU = state_->quat().rotate(a_FLU);
     // draw velocity
     if (draw_vel_) {
         sc::ShapePtr line(new sp::Shape());
         line->set_opacity(1.0);
         sc::set(line->mutable_color(), 255, 0, 0);
         sc::set(line->mutable_line()->mutable_start(), state_->pos());
         sc::set(line->mutable_line()->mutable_end(), state_->pos() + state_->vel());
         draw_shape(line);
     }
     // draw angular velocity
     if (draw_ang_vel_) {
         sc::ShapePtr line(new sp::Shape());
         line->set_opacity(1.0);
         sc::set(line->mutable_color(), 0, 255, 0);
         sc::set(line->mutable_line()->mutable_start(), state_->pos());
         sc::set(line->mutable_line()->mutable_end(), state_->pos() + state_->ang_vel());
         draw_shape(line);
     }
     // draw acceleration
     if (draw_acc_) {
         sc::ShapePtr line(new sp::Shape());
         line->set_opacity(1.0);
         sc::set(line->mutable_color(), 0, 0, 255);
         sc::set(line->mutable_line()->mutable_start(), state_->pos());
         sc::set(line->mutable_line()->mutable_end(), state_->pos() + a_ENU);
         draw_shape(line);
     }
 #if 0
     JSBSim::FGPropertyManager* mgr = exec_->GetPropertyManager();
     cout << "--------------------------------------------------------" << endl;
     cout << "  State information in JSBSImControl" << endl;
     cout << "--------------------------------------------------------" << endl;
     int prec = 5;
     // std::cout << "processing time, ms: " << ((double)time_diff.total_microseconds())/1000 << std::endl;
     cout << std::setprecision(prec) << "dt: " << dt << endl;
     cout << std::setprecision(prec) << "time: " << time << endl;
     cout << std::setprecision(prec) << "Altitude AGL: " << altitudeAGL_node_->getDoubleValue() * feet2meters << endl;
     // cout << std::setprecision(prec) << "WOW[0]: " << mgr->GetNode("gear/unit/WOW")->getDoubleValue() << endl;
     // cout << std::setprecision(prec) << "WOW[1]: " << mgr->GetNode("gear/unit[1]/WOW")->getDoubleValue() << endl;
     // cout << std::setprecision(prec) << "WOW[2]: " << mgr->GetNode("gear/unit[2]/WOW")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "xAccel: " << linear_accel_body_(0) << endl;
     cout << std::setprecision(prec) << "yAccel: " << linear_accel_body_(1) << endl;
     cout << std::setprecision(prec) << "zAccel: " << linear_accel_body_(2) << endl;
     cout << std::setprecision(prec) << "aileron cmd: " << delta_aileron_ << endl;
     cout << std::setprecision(prec) << "elevator cmd: " << delta_elevator_ << endl;
     cout << std::setprecision(prec) << "rudder cmd: " << delta_rudder_ << endl;
     cout << std::setprecision(prec) << "throttle cmd: " << throttle_ << endl;
     cout << std::setprecision(prec) << "aileron jsb: " << mgr->GetNode("fcs/right-aileron-pos-rad")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "elevator jsb: " << mgr->GetNode("fcs/elevator-pos-rad")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "rudder jsb: " << mgr->GetNode("fcs/rudder-pos-rad")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "throttle jsb: " << mgr->GetNode("fcs/throttle-cmd-norm")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "thrust (N): " << mgr->GetNode("propulsion/engine/thrust-lbs")->getDoubleValue()*4.44 << endl;
     cout << std::setprecision(prec) << "alpha: " << mgr->GetNode("aero/alpha-rad")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "drag: " << mgr->GetNode("forces/fwx-aero-lbs")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "lift: " << -mgr->GetNode("forces/fwz-aero-lbs")->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "lat:   " << latitude_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "lon:   " << longitude_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "alt:   " << altitude_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "ve:    " << vel_east_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "vn:    " << vel_north_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "nd:    " << vel_down_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "phi:   " << roll_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "theta: " << pitch_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "psi:   " << yaw_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "p:     " << p_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "q:     " << q_node_->getDoubleValue() << endl;
     cout << std::setprecision(prec) << "r:     " << r_node_->getDoubleValue() << endl;
 #endif
     return true;
 }
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/motion/JSBSimControl/JSBSimControl.h
/root/scrimmage/scrimmage/src/plugins/motion/JSBSimControl/JSBSimControl.cpp