SCRIMMAGE: scrimmage::Contact Class Reference
scrimmage::Contact Class Reference
#include <Contact.h>
Public Types
enum Type {
Type::AIRCRAFT = 0, Type::QUADROTOR, Type::SPHERE, Type::MESH,
Type::UNKNOWN
}
Public Member Functions
Contact ()
Contact (const ID &id, const StatePtr &state)
Contact (ID &id, double radius, StatePtr &state, Type type, scrimmage_proto::ContactVisualPtr cv, const std::unordered_map< std::string, MessageBasePtr > &properties)
template<class T >
std::unordered_map< std::string, MessagePtr< T > > get_properties (std::string name="")
std::unordered_map< std::string, MessageBasePtr > & properties ()
void set_id (const ID &id)
ID & id ()
void set_state (StatePtr &state)
StatePtr & state ()
std::shared_ptr< const State > state_const () const
void set_type (Type type)
Type type ()
scrimmage_proto::ContactVisualPtr & contact_visual ()
void set_active (bool active)
bool active ()
void set_radius (double radius)
double radius ()
Protected Attributes
ID id_
StatePtr state_
Type type_ = Type::AIRCRAFT
scrimmage_proto::ContactVisualPtr contact_visual_
bool active_ = true
double radius_ = 0
std::unordered_map< std::string, MessageBasePtr > properties_
Friends
std::ostream & operator<< (std::ostream &os, const Contact &c)
Detailed Description
Definition at line 54 of file Contact.h.
Member Enumeration Documentation
enum scrimmage::Contact::Type strong
Enumerator
AIRCRAFT
QUADROTOR
SPHERE
MESH
UNKNOWN
Definition at line 56 of file Contact.h.
 {AIRCRAFT = 0, QUADROTOR, SPHERE, MESH, UNKNOWN};
Constructor & Destructor Documentation
scrimmage::Contact::Contact ()
Definition at line 42 of file Contact.cpp.
 : state_(std::make_shared<State>()) {}
scrimmage::Contact::Contact (const ID & id, const StatePtr & state)
Definition at line 44 of file Contact.cpp.
                                                     :
     id_(id), state_(state) {
 }
scrimmage::Contact::Contact (ID & id, double radius, StatePtr & state, Type type, scrimmage_proto::ContactVisualPtr cv, const std::unordered_map< std::string, MessageBasePtr > & properties)
Definition at line 48 of file Contact.cpp.
                                                                                 :
     id_(id), state_(state), type_(type), contact_visual_(cv),
     active_(true), radius_(radius), properties_(properties) {}
Member Function Documentation
template<class T > std::unordered_map<std::string, MessagePtr<T> > scrimmage::Contact::get_properties (std::string name = "") inline
Definition at line 66 of file Contact.h.
{
         std::unordered_map<std::string, MessagePtr<T>> out;
         for (auto &kv : properties_) {
             if (name == "" || kv.first.find(name) != std::string::npos) {
                 auto property_cast =
                     std::dynamic_pointer_cast<Message<T>>(kv.second);
                 if (property_cast) {
                     out[kv.first] = property_cast;
                 }
             }
         }
         return out;
     }
std::unordered_map<std::string, MessageBasePtr>& scrimmage::Contact::properties () inline
Definition at line 80 of file Contact.h.
 {return properties_;}
void scrimmage::Contact::set_id (const ID & id)
Definition at line 54 of file Contact.cpp.
References id(), and id_.
 { id_ = id; }
ID & scrimmage::Contact::id ()
Definition at line 56 of file Contact.cpp.
References id_.
Referenced by scrimmage::autonomy::PyAutonomy::contact2py(), scrimmage::proto_2_contact(), REGISTER_PLUGIN(), and set_id().
 { return id_; }
void scrimmage::Contact::set_state (StatePtr & state)
Definition at line 58 of file Contact.cpp.
References state(), and state_.
Referenced by scrimmage::proto_2_contact().
 { state_ = state; }
StatePtr & scrimmage::Contact::state ()
Definition at line 60 of file Contact.cpp.
References state_.
Referenced by scrimmage::autonomy::PyAutonomy::contact2py(), REGISTER_PLUGIN(), and set_state().
 { return state_; }
std::shared_ptr< const State > scrimmage::Contact::state_const () const
Definition at line 62 of file Contact.cpp.
References state_.
 { return state_; }
void scrimmage::Contact::set_type (Contact::Type type)
Definition at line 64 of file Contact.cpp.
References type(), and type_.
Referenced by scrimmage::proto_2_contact().
 { type_ = type; }
Contact::Type scrimmage::Contact::type ()
Definition at line 66 of file Contact.cpp.
References type_.
Referenced by scrimmage::autonomy::PyAutonomy::contact2py(), and set_type().
 { return type_; }
scrimmage_proto::ContactVisualPtr & scrimmage::Contact::contact_visual ()
Definition at line 68 of file Contact.cpp.
References contact_visual_.
 { return contact_visual_; }
void scrimmage::Contact::set_active (bool active)
Definition at line 71 of file Contact.cpp.
References active(), and active_.
 { active_ = active; }
bool scrimmage::Contact::active ()
Definition at line 75 of file Contact.cpp.
References active_.
Referenced by set_active().
 { return active_; }
void scrimmage::Contact::set_radius (double radius)
Definition at line 73 of file Contact.cpp.
References radius(), and radius_.
 { radius_ = radius; }
double scrimmage::Contact::radius () inline
Definition at line 97 of file Contact.h.
References scrimmage::operator<<().
Referenced by set_radius().
 { return radius_; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Contact & c) friend
Definition at line 77 of file Contact.cpp.
{
     os << c.id_ << ": " << *c.state_;
     return os;
 }
Member Data Documentation
ID scrimmage::Contact::id_ protected
Definition at line 102 of file Contact.h.
Referenced by id(), scrimmage::operator<<(), and set_id().
StatePtr scrimmage::Contact::state_ protected
Definition at line 103 of file Contact.h.
Referenced by scrimmage::operator<<(), set_state(), state(), and state_const().
Type scrimmage::Contact::type_ = Type::AIRCRAFT protected
Definition at line 104 of file Contact.h.
Referenced by set_type(), and type().
scrimmage_proto::ContactVisualPtr scrimmage::Contact::contact_visual_ protected
Definition at line 105 of file Contact.h.
Referenced by contact_visual().
bool scrimmage::Contact::active_ = true protected
Definition at line 106 of file Contact.h.
Referenced by active(), and set_active().
double scrimmage::Contact::radius_ = 0 protected
Definition at line 107 of file Contact.h.
Referenced by set_radius().
std::unordered_map<std::string, MessageBasePtr> scrimmage::Contact::properties_ protected
Definition at line 108 of file Contact.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/entity/Contact.h
/root/scrimmage/scrimmage/src/entity/Contact.cpp