SCRIMMAGE: scrimmage::PubSub Class Reference
scrimmage::PubSub Class Reference
#include <PubSub.h>
Public Types
using TopicMap = std::map< std::string, std::map< std::string, std::list< NetworkDevicePtr > >>
Public Member Functions
PubSub ()
TopicMap & pubs ()
TopicMap & subs ()
void add_network_name (const std::string &str)
boost::optional< std::list< NetworkDevicePtr > > find_devices (const std::string &network_name, const std::string &topic_name, TopicMap &devs)
boost::optional< std::list< NetworkDevicePtr > > find_pubs (const std::string &network_name, const std::string &topic_name)
boost::optional< std::list< NetworkDevicePtr > > find_subs (const std::string &network_name, const std::string &topic_name)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size, bool enable_queue_size, EntityPluginPtr plugin)
PublisherPtr advertise (const std::string &network_name, const std::string &topic, const unsigned int &max_queue_size, const bool &enable_queue_size, EntityPluginPtr plugin)
Protected Member Functions
void print_str (const std::string &s)
Protected Attributes
TopicMap pub_map_
TopicMap sub_map_
Detailed Description
Definition at line 55 of file PubSub.h.
Member Typedef Documentation
TopicMap
using scrimmage::PubSub::TopicMap = std::map<std::string, std::map<std::string, std::list<NetworkDevicePtr> >>
Definition at line 62 of file PubSub.h.
Constructor & Destructor Documentation
PubSub()
scrimmage::PubSub::PubSub ()
Definition at line 46 of file PubSub.cpp.
                {
 }
Member Function Documentation
pubs()
TopicMap& scrimmage::PubSub::pubs () inline
Definition at line 64 of file PubSub.h.
 { return pub_map_; }
References pub_map_.
Referenced by auction_assign.AuctionAssign::step_autonomy().
subs()
TopicMap& scrimmage::PubSub::subs () inline
Definition at line 65 of file PubSub.h.
 { return sub_map_; }
References sub_map_.
add_network_name()
void scrimmage::PubSub::add_network_name (const std::string & str)
Definition at line 49 of file PubSub.cpp.
{
     pub_map_[network_name] = std::map<std::string, std::list<NetworkDevicePtr>>();
     sub_map_[network_name] = std::map<std::string, std::list<NetworkDevicePtr>>();
 }
References pub_map_, and sub_map_.
find_devices()
boost::optional< std::list< NetworkDevicePtr > > scrimmage::PubSub::find_devices (const std::string & network_name, const std::string & topic_name, TopicMap & devs)
Definition at line 71 of file PubSub.cpp.
{
     auto it_network = devs.find(network_name);
     if (it_network == devs.end()) {
          cout << "Failed to find network while setting up device." << endl;
          cout << "Network name: " << network_name << endl;
          cout << "Topic name: " << topic_name << endl;
     } else {
         auto it_topic_pub = it_network->second.find(topic_name);
         if (it_topic_pub == it_network->second.end()) {
             cout << "Failed to find topic while setting up device." << endl;
             cout << "Network name: " << network_name << endl;
             cout << "Topic name: " << topic_name << endl;
         } else {
             return boost::optional<std::list<NetworkDevicePtr>>(it_topic_pub->second);
         }
     }
     return boost::none;
 }
Referenced by find_pubs(), and find_subs().
find_pubs()
boost::optional< std::list< NetworkDevicePtr > > scrimmage::PubSub::find_pubs (const std::string & network_name, const std::string & topic_name)
Definition at line 92 of file PubSub.cpp.
{
     return find_devices(network_name, topic_name, pub_map_);
 }
References find_devices(), and pub_map_.
find_subs()
boost::optional< std::list< NetworkDevicePtr > > scrimmage::PubSub::find_subs (const std::string & network_name, const std::string & topic_name)
Definition at line 97 of file PubSub.cpp.
{
     return find_devices(network_name, topic_name, sub_map_);
 }
References find_devices(), and sub_map_.
subscribe()
template<class T , class CallbackFunc > SubscriberBasePtr scrimmage::PubSub::subscribe (const std::string & network_name, const std::string & topic, CallbackFunc callback, unsigned int max_queue_size, bool enable_queue_size, EntityPluginPtr plugin) inline
Definition at line 80 of file PubSub.h.
{
         if (sub_map_.count(network_name) == 0) {
             print_str(std::string("WARNING: Subscriber unable to connect to network (")
                 + network_name + ") on topic (" + topic + ")");
         }
         SubscriberBasePtr sub =
             std::make_shared<Subscriber<T, CallbackFunc>>(
                 topic, max_queue_size, enable_queue_size, plugin, callback);
         sub_map_[network_name][topic].push_back(sub);
         return sub;
     }
References print_str(), and sub_map_.
advertise()
PublisherPtr scrimmage::PubSub::advertise (const std::string & network_name, const std::string & topic, const unsigned int & max_queue_size, const bool & enable_queue_size, EntityPluginPtr plugin)
Definition at line 54 of file PubSub.cpp.
{
     if (pub_map_.count(network_name) == 0) {
         cout << "WARNING: " << plugin->name()
              << " - Publisher unable to connect to network ("
              << network_name << ") on topic (" << topic << ")" << endl;
     }
     PublisherPtr pub = std::make_shared<Publisher>(topic, max_queue_size,
                                                    enable_queue_size, plugin);
     pub_map_[network_name][topic].push_back(pub);
     return pub;
 }
References pub_map_.
print_str()
void scrimmage::PubSub::print_str (const std::string & s) protected
Definition at line 102 of file PubSub.cpp.
{
     std::cout << s << std::endl;
 }
Referenced by subscribe().
Member Data Documentation
pub_map_
TopicMap scrimmage::PubSub::pub_map_ protected
Definition at line 102 of file PubSub.h.
Referenced by add_network_name(), advertise(), find_pubs(), and pubs().
sub_map_
TopicMap scrimmage::PubSub::sub_map_ protected
Definition at line 103 of file PubSub.h.
Referenced by add_network_name(), find_subs(), subs(), and subscribe().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/pubsub/PubSub.h
/root/scrimmage/scrimmage/src/pubsub/PubSub.cpp