SCRIMMAGE: scrimmage::Publisher Class Reference
scrimmage::Publisher Class Reference
#include <Publisher.h>
Public Member Functions
Publisher ()
Publisher (const std::string &topic, const unsigned int &max_queue_size, const bool &enable_queue_size, EntityPluginPtr plugin)
template<class T >
void publish (const std::shared_ptr< T > &msg, bool add_debug_info=true)
Public Member Functions inherited from scrimmage::NetworkDevice
NetworkDevice ()
NetworkDevice (NetworkDevice &rhs)
NetworkDevice (NetworkDevice &&rhs)
virtual ~NetworkDevice ()=default
NetworkDevice (const std::string &topic, const unsigned int &max_queue_size, const bool &enable_queue_size, EntityPluginPtr plugin)
std::string get_topic () const
void set_topic (const std::string &topic)
void set_msg_list (const std::list< MessageBasePtr > &msg_list)
void clear_msg_list ()
unsigned int msg_list_size ()
unsigned int undelivered_msg_list_size ()
void set_max_queue_size (const unsigned int &size)
unsigned int max_queue_size ()
void enable_queue_size (const bool &enforce)
bool enable_queue_size ()
void enforce_queue_size ()
void add_msg (MessageBasePtr msg)
void add_undelivered_msg (MessageBasePtr msg, const bool &is_stochastic_delay=false)
auto deliver_undelivered_msg (std::list< MessageBasePtr >::iterator it)
int deliver_undelivered_msg (const double &time_now, const bool &is_stochastic_delay=false)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
std::list< MessageBasePtr > pop_msgs ()
template<class T , class = std::enable_if_t<!std::is_same<T, MessageBase>::value && std::is_base_of<MessageBase, T>::value, void>>
std::list< std::shared_ptr< T > > pop_msgs ()
template<class T , class = std::enable_if_t<!std::is_same<T, MessageBase>::value && !std::is_base_of<MessageBase, T>::value, void>>
std::list< std::shared_ptr< Message< T > > > pop_msgs ()
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
std::list< MessageBasePtr > msgs (bool pop_msgs=true)
The msgs() method is no longer supported. Please use the new subscriber callback interface.
template<class T , class = std::enable_if_t<!std::is_same<T, MessageBase>::value && std::is_base_of<MessageBase, T>::value, void>>
std::list< std::shared_ptr< T > > msgs (bool pop_msgs=true)
The msgs() method is no longer supported. Please use the new subscriber callback interface.
template<class T , class = std::enable_if_t<!std::is_same<T, MessageBase>::value && !std::is_base_of<MessageBase, T>::value, void>>
std::list< std::shared_ptr< Message< T > > > msgs (bool pop_msgs=true)
The msgs() method is no longer supported. Please use the new subscriber callback interface.
EntityPluginPtr & plugin ()
Public Attributes
std::function< void(MessageBasePtr)> callback
Protected Member Functions
void set_debug_info (MessageBasePtr msg, const std::string &type)
Protected Member Functions inherited from scrimmage::NetworkDevice
void print_str (const std::string &msg)
Additional Inherited Members
Protected Attributes inherited from scrimmage::NetworkDevice
std::string topic_ = ""
unsigned int max_queue_size_ = 1
bool enable_queue_size_ = false
EntityPluginPtr plugin_
std::list< MessageBasePtr > msg_list_
std::mutex mutex_
std::list< MessageBasePtr > undelivered_msg_list_
Detailed Description
Definition at line 49 of file Publisher.h.
Constructor & Destructor Documentation
Publisher() [1/2]
scrimmage::Publisher::Publisher ()
Definition at line 39 of file Publisher.cpp.
                      {
 }
Publisher() [2/2]
scrimmage::Publisher::Publisher (const std::string & topic, const unsigned int & max_queue_size, const bool & enable_queue_size, EntityPluginPtr plugin)
Definition at line 42 of file Publisher.cpp.
                                                                             :
     NetworkDevice(topic, max_queue_size, enable_queue_size, plugin) {}
Member Function Documentation
publish()
template<class T > void scrimmage::Publisher::publish (const std::shared_ptr< T > & msg, bool add_debug_info = true) inline
Definition at line 55 of file Publisher.h.
{
         if (add_debug_info) {
             set_debug_info(msg, boost::typeindex::type_id<T>().pretty_name());
         }
         add_msg(msg);
     }
References scrimmage::NetworkDevice::add_msg(), and set_debug_info().
set_debug_info()
void scrimmage::Publisher::set_debug_info (MessageBasePtr msg, const std::string & type) protected
Definition at line 46 of file Publisher.cpp.
{
       msg->debug_info = std::string("  publisher:  ")
         + "type (" + type
         + "), plugin (" + plugin_->name() + ")"
         + "), id (" + std::to_string(plugin_->parent()->id().id()) + ")";
 }
References scrimmage::NetworkDevice::plugin_.
Referenced by publish().
Member Data Documentation
callback
std::function<void(MessageBasePtr)> scrimmage::Publisher::callback
Definition at line 61 of file Publisher.h.
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/pubsub/Publisher.h
/root/scrimmage/scrimmage/src/pubsub/Publisher.cpp