SCRIMMAGE: scrimmage::metrics::SimpleCollisionScore Class Reference
scrimmage::metrics::SimpleCollisionScore Class Reference
#include <SimpleCollisionScore.h>
Public Member Functions
bool set_weights (std::map< std::string, std::string > &params)
void set_flight_time_start (double t)
void set_flight_time_end (double t)
void increment_non_team_collisions ()
void increment_team_collisions ()
void increment_ground_collisions ()
void add_non_team_collisions (int c)
void add_team_collisions (int c)
void add_ground_collisions (int c)
void add_flight_time (double t)
int non_team_collisions ()
int team_collisions ()
int ground_collisions ()
void set_max_flight_time (double t)
void increment_entity_count ()
int entity_count ()
void set_entity_count (int entity_count)
void set_non_team_collisions (int non_team_collisions)
void set_team_collisions (int team_collisions)
void set_ground_collisions (int ground_collisions)
double flight_time ()
double flight_time_end ()
double flight_time_start ()
double flight_time_norm ()
double score ()
Protected Attributes
double flight_time_start_ = 0
double flight_time_end_ = 0
int non_team_collisions_ = 0
int team_collisions_ = 0
int ground_collisions_ = 0
double flight_time_w_ = 0
double non_team_collisions_w_ = 0
double team_collisions_w_ = 0
double max_flight_time_ = 0
int entity_count_ = 0
Detailed Description
Definition at line 41 of file SimpleCollisionScore.h.
Member Function Documentation
bool scrimmage::metrics::SimpleCollisionScore::set_weights (std::map< std::string, std::string > & params)
Definition at line 42 of file SimpleCollisionScore.cpp.
References flight_time_w_, non_team_collisions_w_, and team_collisions_w_.
{
     flight_time_w_ = sc::get<double>("flight_time_w", params, 0.0);
     team_collisions_w_ = sc::get<double>("team_collisions_w", params, 0.0);
     non_team_collisions_w_ = sc::get<double>("non_team_collisions_w", params, 0.0);
     return true;
 }
void scrimmage::metrics::SimpleCollisionScore::set_flight_time_start (double t) inline
Definition at line 45 of file SimpleCollisionScore.h.
References flight_time_start_.
 { flight_time_start_ = t; }
void scrimmage::metrics::SimpleCollisionScore::set_flight_time_end (double t) inline
Definition at line 46 of file SimpleCollisionScore.h.
References flight_time_end_.
 { flight_time_end_ = t; }
void scrimmage::metrics::SimpleCollisionScore::increment_non_team_collisions () inline
Definition at line 47 of file SimpleCollisionScore.h.
References non_team_collisions_.
 { non_team_collisions_++; }
void scrimmage::metrics::SimpleCollisionScore::increment_team_collisions () inline
Definition at line 48 of file SimpleCollisionScore.h.
References team_collisions_.
 { team_collisions_++; }
void scrimmage::metrics::SimpleCollisionScore::increment_ground_collisions () inline
Definition at line 49 of file SimpleCollisionScore.h.
References ground_collisions_.
 { ground_collisions_++; }
void scrimmage::metrics::SimpleCollisionScore::add_non_team_collisions (int c) inline
Definition at line 51 of file SimpleCollisionScore.h.
References non_team_collisions_.
 { non_team_collisions_ += c; }
void scrimmage::metrics::SimpleCollisionScore::add_team_collisions (int c) inline
Definition at line 52 of file SimpleCollisionScore.h.
References team_collisions_.
 { team_collisions_ += c; }
void scrimmage::metrics::SimpleCollisionScore::add_ground_collisions (int c) inline
Definition at line 53 of file SimpleCollisionScore.h.
References ground_collisions_.
 { ground_collisions_ += c; }
void scrimmage::metrics::SimpleCollisionScore::add_flight_time (double t) inline
Definition at line 54 of file SimpleCollisionScore.h.
References flight_time_end_.
 { flight_time_end_ += t; }
int scrimmage::metrics::SimpleCollisionScore::non_team_collisions () inline
Definition at line 56 of file SimpleCollisionScore.h.
References non_team_collisions_.
Referenced by score(), and set_non_team_collisions().
 { return non_team_collisions_; }
int scrimmage::metrics::SimpleCollisionScore::team_collisions () inline
Definition at line 57 of file SimpleCollisionScore.h.
References team_collisions_.
Referenced by score(), and set_team_collisions().
 { return team_collisions_; }
int scrimmage::metrics::SimpleCollisionScore::ground_collisions () inline
Definition at line 58 of file SimpleCollisionScore.h.
References ground_collisions_.
Referenced by set_ground_collisions().
 { return ground_collisions_; }
void scrimmage::metrics::SimpleCollisionScore::set_max_flight_time (double t) inline
Definition at line 60 of file SimpleCollisionScore.h.
References max_flight_time_.
 { max_flight_time_ = t; }
void scrimmage::metrics::SimpleCollisionScore::increment_entity_count () inline
Definition at line 61 of file SimpleCollisionScore.h.
References entity_count_.
 { entity_count_++; }
int scrimmage::metrics::SimpleCollisionScore::entity_count () inline
Definition at line 63 of file SimpleCollisionScore.h.
References entity_count_.
Referenced by set_entity_count().
 { return entity_count_; }
void scrimmage::metrics::SimpleCollisionScore::set_entity_count (int entity_count) inline
Definition at line 64 of file SimpleCollisionScore.h.
References entity_count(), and entity_count_.
 {entity_count_ = entity_count;}
void scrimmage::metrics::SimpleCollisionScore::set_non_team_collisions (int non_team_collisions) inline
Definition at line 65 of file SimpleCollisionScore.h.
References non_team_collisions(), and non_team_collisions_.
 {non_team_collisions_ = non_team_collisions;}
void scrimmage::metrics::SimpleCollisionScore::set_team_collisions (int team_collisions) inline
Definition at line 66 of file SimpleCollisionScore.h.
References team_collisions(), and team_collisions_.
 {team_collisions_ = team_collisions;}
void scrimmage::metrics::SimpleCollisionScore::set_ground_collisions (int ground_collisions) inline
Definition at line 67 of file SimpleCollisionScore.h.
References ground_collisions(), and ground_collisions_.
 {ground_collisions_ = ground_collisions;}
double scrimmage::metrics::SimpleCollisionScore::flight_time () inline
Definition at line 69 of file SimpleCollisionScore.h.
References flight_time_end_, and flight_time_start_.
Referenced by flight_time_norm().
 {return (flight_time_end_ - flight_time_start_);}
double scrimmage::metrics::SimpleCollisionScore::flight_time_end () inline
Definition at line 70 of file SimpleCollisionScore.h.
References flight_time_end_.
 {return flight_time_end_;}
double scrimmage::metrics::SimpleCollisionScore::flight_time_start () inline
Definition at line 71 of file SimpleCollisionScore.h.
References flight_time_start_.
 {return flight_time_start_;}
double scrimmage::metrics::SimpleCollisionScore::flight_time_norm () inline
Definition at line 72 of file SimpleCollisionScore.h.
References flight_time(), max_flight_time_, and score().
Referenced by score().
 {return (flight_time() / max_flight_time_);}
double scrimmage::metrics::SimpleCollisionScore::score ()
Definition at line 50 of file SimpleCollisionScore.cpp.
References flight_time_norm(), flight_time_w_, non_team_collisions(), non_team_collisions_w_, team_collisions(), and team_collisions_w_.
Referenced by flight_time_norm().
{
     double s = flight_time_norm() * flight_time_w_
         + non_team_collisions() * non_team_collisions_w_
         + team_collisions() * team_collisions_w_;
     return s;
 }
Member Data Documentation
double scrimmage::metrics::SimpleCollisionScore::flight_time_start_ = 0 protected
Definition at line 78 of file SimpleCollisionScore.h.
Referenced by flight_time(), flight_time_start(), and set_flight_time_start().
double scrimmage::metrics::SimpleCollisionScore::flight_time_end_ = 0 protected
Definition at line 79 of file SimpleCollisionScore.h.
Referenced by add_flight_time(), flight_time(), flight_time_end(), and set_flight_time_end().
int scrimmage::metrics::SimpleCollisionScore::non_team_collisions_ = 0 protected
Definition at line 80 of file SimpleCollisionScore.h.
Referenced by add_non_team_collisions(), increment_non_team_collisions(), non_team_collisions(), and set_non_team_collisions().
int scrimmage::metrics::SimpleCollisionScore::team_collisions_ = 0 protected
Definition at line 81 of file SimpleCollisionScore.h.
Referenced by add_team_collisions(), increment_team_collisions(), set_team_collisions(), and team_collisions().
int scrimmage::metrics::SimpleCollisionScore::ground_collisions_ = 0 protected
Definition at line 82 of file SimpleCollisionScore.h.
Referenced by add_ground_collisions(), ground_collisions(), increment_ground_collisions(), and set_ground_collisions().
double scrimmage::metrics::SimpleCollisionScore::flight_time_w_ = 0 protected
Definition at line 84 of file SimpleCollisionScore.h.
Referenced by score(), and set_weights().
double scrimmage::metrics::SimpleCollisionScore::non_team_collisions_w_ = 0 protected
Definition at line 85 of file SimpleCollisionScore.h.
Referenced by score(), and set_weights().
double scrimmage::metrics::SimpleCollisionScore::team_collisions_w_ = 0 protected
Definition at line 86 of file SimpleCollisionScore.h.
Referenced by score(), and set_weights().
double scrimmage::metrics::SimpleCollisionScore::max_flight_time_ = 0 protected
Definition at line 88 of file SimpleCollisionScore.h.
Referenced by flight_time_norm(), and set_max_flight_time().
int scrimmage::metrics::SimpleCollisionScore::entity_count_ = 0 protected
Definition at line 89 of file SimpleCollisionScore.h.
Referenced by entity_count(), increment_entity_count(), and set_entity_count().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/metrics/SimpleCollisionMetrics/SimpleCollisionScore.h
/root/scrimmage/scrimmage/src/plugins/metrics/SimpleCollisionMetrics/SimpleCollisionScore.cpp