SCRIMMAGE: scrimmage::sensor::RayTrace Class Reference
scrimmage::sensor::RayTrace Class Reference
#include <RayTrace.h>
Classes
class PCPoint
class PCRay
class PointCloud
class PointCloudWithId
Public Member Functions
RayTrace ()
std::string type () override
void init (std::map< std::string, std::string > &params) override
bool step () override
bool automatic_ray_tracing ()
std::vector< PCRay > rays ()
double max_range ()
double min_range ()
double max_sample_rate ()
Public Member Functions inherited from scrimmage::Sensor
std::string type () override
virtual scrimmage::MessageBasePtr sensor_msg (double t)
template<class T = MessageBase, class = std::enable_if_t<std::is_same<T, MessageBase>::value, void>>
MessageBasePtr sense (double t)
version when T = MessageBase (calls sensor_msg without casting)
template<class T >
std::shared_ptr< scrimmage::Message< T > > sense (double t)
default version
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void close (double)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
Protected Attributes
std::shared_ptr< std::default_random_engine > gener_
std::vector< std::shared_ptr< std::normal_distribution< double > > > pos_noise_
std::vector< PCRay > rays_
uint32_t ray_id_counter_ {0}
double max_range_
double min_range_
double max_sample_rate_
bool auto_ray_tracing_ {true}
PublisherPtr pub_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 46 of file RayTrace.h.
Constructor & Destructor Documentation
scrimmage::sensor::RayTrace::RayTrace ()
Definition at line 62 of file RayTrace.cpp.
 : max_range_(0), min_range_(0), max_sample_rate_(0) {}
Member Function Documentation
std::string scrimmage::sensor::RayTrace::type () inline override virtual
Reimplemented from scrimmage::Plugin.
Definition at line 93 of file RayTrace.h.
References init(), and step().
 { return "Ray"; }
void scrimmage::sensor::RayTrace::init (std::map< std::string, std::string > & params) override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 64 of file RayTrace.cpp.
References scrimmage::EntityPlugin::advertise(), auto_ray_tracing_, scrimmage::Angles::deg2rad(), gener_, scrimmage::get_vec(), max_range_, max_sample_rate_, min_range_, scrimmage::EntityPlugin::parent_, pos_noise_, pub_, and rays_.
Referenced by scrimmage::sensor::LOSSensor::init(), and type().
{
     // Use the same generator as the parent so that the simulation is
     // completely deterministic with respect to the simulation seed.
     gener_ = parent_->random()->gener();
     // Create three independent gaussian noise generators. They will use the
     // same generator seed.
     for (int i = 0; i < 3; i++) {
         std::string tag_name = "pos_noise_" + std::to_string(i);
         std::vector<double> vec;
         bool status = sc::get_vec(tag_name, params, " ", vec, 2);
         if (status) {
             pos_noise_.push_back(parent_->random()->make_rng_normal(vec[0], vec[1]));
         } else {
             pos_noise_.push_back(parent_->random()->make_rng_normal(0, 1));
         }
     }
     max_range_ = sc::get<double>("max_range", params, 1);
     min_range_ = sc::get<double>("min_range", params, 1);
     max_sample_rate_ = sc::get<double>("max_sample_rate", params, 1);
     auto_ray_tracing_ = sc::get<bool>("auto_ray_tracing", params, true);
     // Create the ray definitions
     double angle_res_vert = sc::Angles::deg2rad(sc::get<double>("angle_res_vert", params, 1));
     double angle_res_horiz = sc::Angles::deg2rad(sc::get<double>("angle_res_horiz", params, 1));
     int num_rays_vert = sc::get<int>("num_rays_vert", params, 1);
     int num_rays_horiz = sc::get<int>("num_rays_horiz", params, 1);
     rays_.clear();
     double fov_horiz = angle_res_horiz * (num_rays_horiz - 1);
     double fov_vert = angle_res_vert * (num_rays_vert - 1);
     double start_angle_horiz = -fov_horiz / 2.0;
     double start_angle_vert = -fov_vert / 2.0;
     double angle_vert = start_angle_vert;
     for (int v = 0; v < num_rays_vert; v++) {
         double angle_horiz = start_angle_horiz;
         for (int h = 0; h < num_rays_horiz; h++) {
             rays_.push_back(PCRay(angle_horiz, angle_vert));
             angle_horiz += angle_res_horiz;
         }
         angle_vert += angle_res_vert;
     }
     // Create the publisher
     pub_ = advertise("LocalNetwork", "RayTrace");
 }
bool scrimmage::sensor::RayTrace::step () override virtual
Reimplemented from scrimmage::Sensor.
Definition at line 114 of file RayTrace.cpp.
Referenced by scrimmage::sensor::LOSSensor::step(), and type().
                     {
     // pub_->publish(std::make_shared<MessageBase>());
     return true;
 }
bool scrimmage::sensor::RayTrace::automatic_ray_tracing () inline
Whether to have the bullet collision plugin automatically run ray tracing for this sensor and send associated messages
Definition at line 98 of file RayTrace.h.
References auto_ray_tracing_, and rays().
 { return auto_ray_tracing_; }
std::vector< RayTrace::PCRay > scrimmage::sensor::RayTrace::rays ()
Returns a copy of the rays
Definition at line 119 of file RayTrace.cpp.
References rays_.
Referenced by automatic_ray_tracing().
{
     std::vector<RayTrace::PCRay> return_rays;
     for (auto &ray : rays_) {
         // Make a copy so can be used cleanly
         return_rays.push_back(RayTrace::PCRay(ray.azimuth_rad, ray.elevation_rad));
     }
     return return_rays;
 }
double scrimmage::sensor::RayTrace::max_range () inline
Sensor ranges and update rates
Definition at line 102 of file RayTrace.h.
References max_range_.
Referenced by scrimmage::interaction::BulletCollision::init(), and scrimmage::sensor::LOSSensor::step().
 { return max_range_; }
double scrimmage::sensor::RayTrace::min_range () inline
Definition at line 103 of file RayTrace.h.
References min_range_.
Referenced by scrimmage::sensor::LOSSensor::step().
 { return min_range_; }
double scrimmage::sensor::RayTrace::max_sample_rate () inline
Definition at line 104 of file RayTrace.h.
References max_sample_rate_.
Referenced by scrimmage::sensor::LOSSensor::step().
 { return max_sample_rate_; }
Member Data Documentation
std::shared_ptr<std::default_random_engine> scrimmage::sensor::RayTrace::gener_ protected
Definition at line 107 of file RayTrace.h.
Referenced by init().
std::vector<std::shared_ptr<std::normal_distribution<double> > > scrimmage::sensor::RayTrace::pos_noise_ protected
Definition at line 108 of file RayTrace.h.
Referenced by init().
std::vector<PCRay> scrimmage::sensor::RayTrace::rays_ protected
Definition at line 111 of file RayTrace.h.
Referenced by init(), and rays().
uint32_t scrimmage::sensor::RayTrace::ray_id_counter_ {0} protected
Definition at line 112 of file RayTrace.h.
double scrimmage::sensor::RayTrace::max_range_ protected
Definition at line 114 of file RayTrace.h.
Referenced by init(), and max_range().
double scrimmage::sensor::RayTrace::min_range_ protected
Definition at line 115 of file RayTrace.h.
Referenced by init(), and min_range().
double scrimmage::sensor::RayTrace::max_sample_rate_ protected
Definition at line 117 of file RayTrace.h.
Referenced by init(), and max_sample_rate().
bool scrimmage::sensor::RayTrace::auto_ray_tracing_ {true} protected
Definition at line 119 of file RayTrace.h.
Referenced by automatic_ray_tracing(), and init().
PublisherPtr scrimmage::sensor::RayTrace::pub_ protected
Definition at line 121 of file RayTrace.h.
Referenced by init().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/sensor/RayTrace/RayTrace.h
/root/scrimmage/scrimmage/src/plugins/sensor/RayTrace/RayTrace.cpp