SCRIMMAGE: scrimmage::interaction::Sphere Class Reference
scrimmage::interaction::Sphere Class Reference
#include <Sphere.h>
Public Member Functions
Sphere ()
Sphere (const double &radius, const Eigen::Vector3d &center)
Sphere (const scrimmage_proto::Shape &shape)
void set_radius (const double &radius)
void set_center (const Eigen::Vector3d &center)
double radius ()
Eigen::Vector3d center () override
bool contains (Eigen::Vector3d p) override
void set_visual (int R, int G, int B, double opacity) override
const std::vector< std::tuple< double, double > > & extents () override
Public Member Functions inherited from scrimmage::interaction::BoundaryBase
BoundaryBase ()
virtual ~BoundaryBase ()
BoundaryBase (const Eigen::Vector3d &center)
const sc::ShapePtr shape () const
void set_shape (const sc::ShapePtr &shape)
Protected Attributes
double radius_
Protected Attributes inherited from scrimmage::interaction::BoundaryBase
sc::ShapePtr shape_
std::list< sc::ShapePtr > shapes_
Eigen::Vector3d center_
std::vector< std::tuple< double, double > > extents_
Detailed Description
Definition at line 53 of file Sphere.h.
Constructor & Destructor Documentation
Sphere() [1/3]
scrimmage::interaction::Sphere::Sphere () inline
Definition at line 55 of file Sphere.h.
              : BoundaryBase(Eigen::Vector3d(0, 0, 0)), radius_(1.0) {
     }
Sphere() [2/3]
scrimmage::interaction::Sphere::Sphere (const double & radius, const Eigen::Vector3d & center) inline
Definition at line 58 of file Sphere.h.
                                                               :
     BoundaryBase(center), radius_(radius) {}
Sphere() [3/3]
scrimmage::interaction::Sphere::Sphere (const scrimmage_proto::Shape & shape) inline explicit
Definition at line 61 of file Sphere.h.
                                                        :
     Sphere(shape.sphere().radius(), proto_2_vector3d(shape.sphere().center())) {
     }
Member Function Documentation
set_radius()
void scrimmage::interaction::Sphere::set_radius (const double & radius) inline
Definition at line 65 of file Sphere.h.
 { radius_ = radius; }
References radius(), and radius_.
set_center()
void scrimmage::interaction::Sphere::set_center (const Eigen::Vector3d & center) inline
Definition at line 66 of file Sphere.h.
 { center_ = center; }
References center(), and scrimmage::interaction::BoundaryBase::center_.
radius()
double scrimmage::interaction::Sphere::radius () inline
Definition at line 68 of file Sphere.h.
 { return radius_; }
References radius_.
Referenced by set_radius().
center()
Eigen::Vector3d scrimmage::interaction::Sphere::center () inline override virtual
Reimplemented from scrimmage::interaction::BoundaryBase.
Definition at line 69 of file Sphere.h.
 { return center_; }
References scrimmage::interaction::BoundaryBase::center_.
Referenced by set_center().
contains()
bool scrimmage::interaction::Sphere::contains (Eigen::Vector3d p) inline override virtual
Implements scrimmage::interaction::BoundaryBase.
Definition at line 71 of file Sphere.h.
{
         return (p-center_).norm() < radius_;
     }
References scrimmage::interaction::BoundaryBase::center_, and radius_.
set_visual()
void scrimmage::interaction::Sphere::set_visual (int R, int G, int B, double opacity) inline override virtual
Implements scrimmage::interaction::BoundaryBase.
Definition at line 75 of file Sphere.h.
{
         sc::ShapePtr sphere(new sp::Shape);
         sphere->set_opacity(opacity);
         sc::set(sphere->mutable_color(), R, G, B);
         sphere->set_persistent(true);
         sc::set(sphere->mutable_sphere()->mutable_center(), center_);
         sphere->mutable_sphere()->set_radius(radius_);
         shapes_.push_back(sphere);
     }
References scrimmage::interaction::BoundaryBase::center_, scrimmage::motion::R, radius_, scrimmage::set(), and scrimmage::interaction::BoundaryBase::shapes_.
extents()
const std::vector<std::tuple<double, double> >& scrimmage::interaction::Sphere::extents () inline override virtual
Reimplemented from scrimmage::interaction::BoundaryBase.
Definition at line 85 of file Sphere.h.
{
         // Find the smallest cube that covers the entire sphere
         extents_.clear();
         for (unsigned int i = 0; i < 3; i++) {
             extents_.push_back(std::tuple<double, double>(center_(i)+radius_,
                                                           center_(i)-radius_));
         }
         return extents_;
     }
References scrimmage::interaction::BoundaryBase::center_, scrimmage::interaction::BoundaryBase::extents_, and radius_.
Member Data Documentation
radius_
double scrimmage::interaction::Sphere::radius_ protected
Definition at line 96 of file Sphere.h.
Referenced by contains(), extents(), radius(), set_radius(), and set_visual().
The documentation for this class was generated from the following file:
/root/scrimmage/scrimmage/include/scrimmage/plugins/interaction/Boundary/Sphere.h