SCRIMMAGE: scrimmage::controller::SimpleCarControllerHeading Class Reference
scrimmage::controller::SimpleCarControllerHeading Class Reference
#include <SimpleCarControllerHeading.h>
Public Member Functions
virtual void init (std::map< std::string, std::string > &params)
virtual bool step (double t, double dt)
Public Member Functions inherited from scrimmage::Controller
void set_state (StatePtr &state)
void set_desired_state (StatePtr &desired_state)
void close (double) override
Public Member Functions inherited from scrimmage::EntityPlugin
EntityPlugin ()
virtual ~EntityPlugin ()
virtual bool ready ()
void close_plugin (const double &t)
virtual void set_parent (EntityPtr parent)
virtual EntityPtr parent ()
void set_scoped_property (const std::string &property_name, const MessageBasePtr &property)
MessageBasePtr get_scoped_property_helper (const std::string &property_name)
StatePtr transform ()
virtual void set_id_to_team_map (std::shared_ptr< std::unordered_map< int, int >> lookup)
virtual void set_id_to_ent_map (std::shared_ptr< std::unordered_map< int, EntityPtr >> lookup)
std::list< scrimmage_proto::ShapePtr > & shapes ()
VariableIO & vars ()
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback)
template<class T , class CallbackFunc >
SubscriberBasePtr subscribe (const std::string &network_name, const std::string &topic, CallbackFunc callback, unsigned int max_queue_size)
PublisherPtr advertise (std::string network_name, std::string topic)
PublisherPtr advertise (std::string network_name, std::string topic, unsigned int max_queue_size)
void set_pubsub (PubSubPtr pubsub)
PubSubPtr pubsub ()
std::list< SubscriberBasePtr > subs ()
void set_time (const std::shared_ptr< Time > &time)
void set_time (std::shared_ptr< const Time > time)
void draw_shape (scrimmage_proto::ShapePtr s)
void set_param_server (const ParameterServerPtr &param_server)
template<class T >
bool register_param (const std::string &name, T &variable, std::function< void(const T &value)> callback=[](const T &value){})
template<class T >
bool set_param (const std::string &name, const T &value)
template<class T >
bool unregister_param (const std::string &name)
const double & loop_rate () const
const double & loop_timer () const
void set_loop_rate (const double &loop_rate)
void set_loop_timer (const double &loop_timer)
bool step_loop_timer (double dt)
Public Member Functions inherited from scrimmage::Plugin
Plugin ()
virtual ~Plugin ()
void set_name (std::string name)
std::string name ()
virtual std::string type ()
Protected Attributes
PID pid_
uint8_t input_vel_idx_ = 0
uint8_t input_heading_idx_ = 0
uint8_t output_vel_idx_ = 0
uint8_t output_turn_rate_idx_ = 0
Protected Attributes inherited from scrimmage::Controller
StatePtr state_
StatePtr desired_state_
Protected Attributes inherited from scrimmage::EntityPlugin
EntityPtr parent_
StatePtr transform_
std::shared_ptr< std::unordered_map< int, int > > id_to_team_map_
std::shared_ptr< std::unordered_map< int, EntityPtr > > id_to_ent_map_
VariableIO vars_
PubSubPtr pubsub_
std::list< SubscriberBasePtr > subs_
std::shared_ptr< const Time > time_
Protected Attributes inherited from scrimmage::Plugin
std::string name_ = "Unset"
bool name_set_ = false
Additional Inherited Members
Public Attributes inherited from scrimmage::EntityPlugin
bool print_err_on_exit = true
Detailed Description
Definition at line 44 of file SimpleCarControllerHeading.h.
Member Function Documentation
init()
void scrimmage::controller::SimpleCarControllerHeading::init (std::map< std::string, std::string > & params) virtual
Reimplemented from scrimmage::Controller.
Definition at line 44 of file SimpleCarControllerHeading.cpp.
{
     double p_gain = get<double>("p_gain", params, 1);
     double i_gain = get<double>("i_gain", params, 1);
     double d_gain = get<double>("d_gain", params, 1);
     double i_lim = get<double>("i_lim", params, 1);
     pid_.set_parameters(p_gain, i_gain, d_gain);
     pid_.set_integral_band(i_lim);
     pid_.set_is_angle(true);
     input_vel_idx_ = vars_.declare(VariableIO::Type::desired_speed, VariableIO::Direction::In);
     input_heading_idx_ = vars_.declare(VariableIO::Type::desired_heading, VariableIO::Direction::In);
     output_vel_idx_ = vars_.declare(VariableIO::Type::speed, VariableIO::Direction::Out);
     output_turn_rate_idx_ = vars_.declare(VariableIO::Type::turn_rate, VariableIO::Direction::Out);
 }
References scrimmage::VariableIO::declare(), scrimmage::VariableIO::desired_heading, scrimmage::VariableIO::desired_speed, scrimmage::VariableIO::In, input_heading_idx_, input_vel_idx_, scrimmage::VariableIO::Out, output_turn_rate_idx_, output_vel_idx_, pid_, scrimmage::PID::set_integral_band(), scrimmage::PID::set_is_angle(), scrimmage::PID::set_parameters(), scrimmage::VariableIO::speed, scrimmage::VariableIO::turn_rate, and scrimmage::EntityPlugin::vars_.
step()
bool scrimmage::controller::SimpleCarControllerHeading::step (double t, double dt) virtual
Reimplemented from scrimmage::Controller.
Definition at line 60 of file SimpleCarControllerHeading.cpp.
{
     vars_.output(output_vel_idx_, vars_.input(input_vel_idx_));
     pid_.set_setpoint(vars_.input(input_heading_idx_));
     const double turn_rate = pid_.step(dt, state_->quat().yaw());
     vars_.output(output_turn_rate_idx_, turn_rate);
     return true;
 }
References scrimmage::VariableIO::input(), input_heading_idx_, input_vel_idx_, scrimmage::VariableIO::output(), output_turn_rate_idx_, output_vel_idx_, pid_, scrimmage::PID::set_setpoint(), scrimmage::Controller::state_, scrimmage::PID::step(), and scrimmage::EntityPlugin::vars_.
Member Data Documentation
pid_
PID scrimmage::controller::SimpleCarControllerHeading::pid_ protected
Definition at line 50 of file SimpleCarControllerHeading.h.
Referenced by init(), and step().
input_vel_idx_
uint8_t scrimmage::controller::SimpleCarControllerHeading::input_vel_idx_ = 0 protected
Definition at line 52 of file SimpleCarControllerHeading.h.
Referenced by init(), and step().
input_heading_idx_
uint8_t scrimmage::controller::SimpleCarControllerHeading::input_heading_idx_ = 0 protected
Definition at line 53 of file SimpleCarControllerHeading.h.
Referenced by init(), and step().
output_vel_idx_
uint8_t scrimmage::controller::SimpleCarControllerHeading::output_vel_idx_ = 0 protected
Definition at line 55 of file SimpleCarControllerHeading.h.
Referenced by init(), and step().
output_turn_rate_idx_
uint8_t scrimmage::controller::SimpleCarControllerHeading::output_turn_rate_idx_ = 0 protected
Definition at line 56 of file SimpleCarControllerHeading.h.
Referenced by init(), and step().
The documentation for this class was generated from the following files:
/root/scrimmage/scrimmage/include/scrimmage/plugins/controller/SimpleCarControllerHeading/SimpleCarControllerHeading.h
/root/scrimmage/scrimmage/src/plugins/controller/SimpleCarControllerHeading/SimpleCarControllerHeading.cpp