SCRIMMAGE: /root/scrimmage/scrimmage/src/plugins/network/LocalNetwork/LocalNetwork.cpp File Reference
LocalNetwork.cpp File Reference
Brief file description.
#include <scrimmage/plugins/network/LocalNetwork/LocalNetwork.h>
#include <scrimmage/common/ID.h>
#include <scrimmage/common/Time.h>
#include <scrimmage/common/Random.h>
#include <scrimmage/common/RTree.h>
#include <scrimmage/entity/Entity.h>
#include <scrimmage/math/State.h>
#include <scrimmage/plugin_manager/RegisterPlugin.h>
#include <scrimmage/plugins/network/SphereNetwork/SphereNetwork.h>
#include <scrimmage/pubsub/Publisher.h>
#include <scrimmage/pubsub/Subscriber.h>
#include <scrimmage/pubsub/Message.h>
#include <memory>
#include <limits>
#include <iostream>
Functions
REGISTER_PLUGIN (scrimmage::Network, scrimmage::network::LocalNetwork, LocalNetwork_plugin) namespace scrimmage
Detailed Description
Brief file description.
LICENSE
Copyright (C) 2017 by the Georgia Tech Research Institute (GTRI)
This file is part of SCRIMMAGE.
SCRIMMAGE is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SCRIMMAGE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with SCRIMMAGE. If not, see http://www.gnu.org/licenses/.
Author
Kevin DeMarco kevin.nosp@m..dem.nosp@m.arco@.nosp@m.gtri.nosp@m..gate.nosp@m.ch.e.nosp@m.du
Eric Squires eric..nosp@m.squi.nosp@m.res@g.nosp@m.tri..nosp@m.gatec.nosp@m.h.ed.nosp@m.u
Date
31 July 2017
Version
0.1.0
DESCRIPTION
A Long description goes here.
Definition in file LocalNetwork.cpp.
Function Documentation
REGISTER_PLUGIN()
REGISTER_PLUGIN (scrimmage::Network , scrimmage::network::LocalNetwork , LocalNetwork_plugin)
Definition at line 56 of file LocalNetwork.cpp.
                     {
 namespace network {
 LocalNetwork::LocalNetwork() {
 }
 bool LocalNetwork::init(std::map<std::string, std::string> &mission_params,
                         std::map<std::string, std::string> &plugin_params) {
     network_init(mission_params, plugin_params);
     return true;
 }
 bool LocalNetwork::is_reachable(const scrimmage::EntityPluginPtr &pub_plugin,
                                 const scrimmage::EntityPluginPtr &sub_plugin) {
     // Never reachable if plugin's entity was destroyed
     if (pub_plugin->parent() == nullptr || sub_plugin->parent() == nullptr) return false;
     // If the publisher and subscriber have the same parent, it is reachable
     return (pub_plugin->parent() == sub_plugin->parent());
 }
 bool LocalNetwork::is_successful_transmission(const scrimmage::EntityPluginPtr &pub_plugin,
                                               const scrimmage::EntityPluginPtr &sub_plugin) {
     return true;
 }
 } // namespace network
 } // namespace scrimmage
References scrimmage::network::LocalNetwork::init(), scrimmage::network::LocalNetwork::is_reachable(), scrimmage::network::LocalNetwork::is_successful_transmission(), scrimmage::network::LocalNetwork::LocalNetwork(), and scrimmage::Network::network_init().