var namespacescrimmage_1_1controller =
[
    [ "AircraftPIDController", "classscrimmage_1_1controller_1_1AircraftPIDController.html", "classscrimmage_1_1controller_1_1AircraftPIDController" ],
    [ "AircraftToSingleIntegratorController", "classscrimmage_1_1controller_1_1AircraftToSingleIntegratorController.html", "classscrimmage_1_1controller_1_1AircraftToSingleIntegratorController" ],
    [ "AxisScale", "classscrimmage_1_1controller_1_1AxisScale.html", "classscrimmage_1_1controller_1_1AxisScale" ],
    [ "DirectController", "classscrimmage_1_1controller_1_1DirectController.html", "classscrimmage_1_1controller_1_1DirectController" ],
    [ "DoubleIntegratorControllerVelYaw", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerVelYaw.html", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerVelYaw" ],
    [ "DoubleIntegratorControllerWaypoint", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerWaypoint.html", "classscrimmage_1_1controller_1_1DoubleIntegratorControllerWaypoint" ],
    [ "FixedWing6DOFControllerPID", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerPID.html", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerPID" ],
    [ "FixedWing6DOFControllerROS", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerROS.html", "classscrimmage_1_1controller_1_1FixedWing6DOFControllerROS" ],
    [ "HarmonicOscillatorConstController", "classscrimmage_1_1controller_1_1HarmonicOscillatorConstController.html", "classscrimmage_1_1controller_1_1HarmonicOscillatorConstController" ],
    [ "Joystick", "classscrimmage_1_1controller_1_1Joystick.html", "classscrimmage_1_1controller_1_1Joystick" ],
    [ "JoystickController", "classscrimmage_1_1controller_1_1JoystickController.html", "classscrimmage_1_1controller_1_1JoystickController" ],
    [ "JSBSimControlControllerHeadingPID", "classscrimmage_1_1controller_1_1JSBSimControlControllerHeadingPID.html", "classscrimmage_1_1controller_1_1JSBSimControlControllerHeadingPID" ],
    [ "JSBSimModelControllerDirect", "classscrimmage_1_1controller_1_1JSBSimModelControllerDirect.html", "classscrimmage_1_1controller_1_1JSBSimModelControllerDirect" ],
    [ "JSBSimModelControllerHeadingPID", "classscrimmage_1_1controller_1_1JSBSimModelControllerHeadingPID.html", "classscrimmage_1_1controller_1_1JSBSimModelControllerHeadingPID" ],
    [ "MotionBattery", "classscrimmage_1_1controller_1_1MotionBattery.html", "classscrimmage_1_1controller_1_1MotionBattery" ],
    [ "MultirotorControllerOmega", "classscrimmage_1_1controller_1_1MultirotorControllerOmega.html", "classscrimmage_1_1controller_1_1MultirotorControllerOmega" ],
    [ "MultirotorControllerPID", "classscrimmage_1_1controller_1_1MultirotorControllerPID.html", "classscrimmage_1_1controller_1_1MultirotorControllerPID" ],
    [ "RigidBody6DOFControllerPID", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerPID.html", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerPID" ],
    [ "RigidBody6DOFControllerROS", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerROS.html", "classscrimmage_1_1controller_1_1RigidBody6DOFControllerROS" ],
    [ "SimpleAircraftControllerPID", "classscrimmage_1_1controller_1_1SimpleAircraftControllerPID.html", "classscrimmage_1_1controller_1_1SimpleAircraftControllerPID" ],
    [ "SimpleCarControllerHeading", "classscrimmage_1_1controller_1_1SimpleCarControllerHeading.html", "classscrimmage_1_1controller_1_1SimpleCarControllerHeading" ],
    [ "SimpleQuadrotorControllerLQR", "classscrimmage_1_1controller_1_1SimpleQuadrotorControllerLQR.html", "classscrimmage_1_1controller_1_1SimpleQuadrotorControllerLQR" ],
    [ "SingleIntegratorControllerSimple", "classscrimmage_1_1controller_1_1SingleIntegratorControllerSimple.html", "classscrimmage_1_1controller_1_1SingleIntegratorControllerSimple" ],
    [ "SingleIntegratorControllerWaypoint", "classscrimmage_1_1controller_1_1SingleIntegratorControllerWaypoint.html", "classscrimmage_1_1controller_1_1SingleIntegratorControllerWaypoint" ],
    [ "UnicycleControllerPoint", "classscrimmage_1_1controller_1_1UnicycleControllerPoint.html", "classscrimmage_1_1controller_1_1UnicycleControllerPoint" ],
    [ "UnicyclePID", "classscrimmage_1_1controller_1_1UnicyclePID.html", "classscrimmage_1_1controller_1_1UnicyclePID" ],
    [ "UUV6DOFLinearEnergy", "classscrimmage_1_1controller_1_1UUV6DOFLinearEnergy.html", "classscrimmage_1_1controller_1_1UUV6DOFLinearEnergy" ],
    [ "UUV6DOFPIDController", "classscrimmage_1_1controller_1_1UUV6DOFPIDController.html", "classscrimmage_1_1controller_1_1UUV6DOFPIDController" ]
];