SCRIMMAGE: scrimmage::interaction Namespace Reference
scrimmage::interaction Namespace Reference
Classes
class Boundary
class BoundaryBase
class BulletCollision
class CaptureInBoundaryInteraction
class Cuboid
class EnforceBoundaryInteraction
class ExternalForceField
class FlagCaptureInteraction
class GraphInteraction
class GroundCollision
class GRPCCommandString
class Map2DInfo
class MapGen2D
class Plane
class Polyhedron
class RandomAttrit
class ROSClockServer
class ROSShapeViz
class SimpleCapture
class SimpleCollision
class Sphere
class TerrainGenerator
class TerrainMap
Typedefs
using NodePair = std::pair< uint64_t, uint64_t >
using NodePairColorMap = std::unordered_map< NodePair, std::vector< int >, boost::hash< NodePair > >
using NodePairShapeMap = std::unordered_map< NodePair, std::shared_ptr< scrimmage_proto::Shape >, boost::hash< NodePair > >
using NodeShapeMap = std::unordered_map< uint64_t, std::shared_ptr< scrimmage_proto::Shape > >
Enumerations
enum DrawNodeLabels { DrawNodeLabels::NO, DrawNodeLabels::YES }
Functions
std::tuple< std::shared_ptr< scrimmage_proto::Shape >, NodePairShapeMap, NodeShapeMap > draw_graph (scrimmage_msgs::Graph &graph, const std::unordered_map< uint64_t, scrimmage_proto::Vector3d > &node_idx_to_pos, DrawNodeLabels draw_node_labels, EntityPluginPtr plugin)
std::unordered_map< uint64_t, scrimmage_proto::Vector3d > nodes_idxs_to_pos_map (const scrimmage_msgs::Graph &graph)
Typedef Documentation
NodePair
using scrimmage::interaction::NodePair = typedef std::pair<uint64_t, uint64_t>
Definition at line 64 of file GraphUtils.h.
NodePairColorMap
using scrimmage::interaction::NodePairColorMap = typedef std::unordered_map<NodePair, std::vector<int>, boost::hash<NodePair> >
Definition at line 65 of file GraphUtils.h.
NodePairShapeMap
using scrimmage::interaction::NodePairShapeMap = typedef std::unordered_map<NodePair, std::shared_ptr<scrimmage_proto::Shape>, boost::hash<NodePair> >
Definition at line 66 of file GraphUtils.h.
NodeShapeMap
using scrimmage::interaction::NodeShapeMap = typedef std::unordered_map<uint64_t, std::shared_ptr<scrimmage_proto::Shape> >
Definition at line 67 of file GraphUtils.h.
Enumeration Type Documentation
DrawNodeLabels
enum scrimmage::interaction::DrawNodeLabels strong
Enumerator
NO
YES
Definition at line 63 of file GraphUtils.h.
 {NO, YES};
Function Documentation
draw_graph()
std::tuple< std::shared_ptr< scrimmage_proto::Shape >, NodePairShapeMap, NodeShapeMap > scrimmage::interaction::draw_graph (scrimmage_msgs::Graph & graph, const std::unordered_map< uint64_t, scrimmage_proto::Vector3d > & node_idx_to_pos, DrawNodeLabels draw_node_labels, EntityPluginPtr plugin)
Definition at line 54 of file GraphUtils.cpp.
{
     const std::vector<int> black {0, 0, 0};
     const std::vector<int> white {255, 255, 255};
     const std::vector<int> blue {0, 0, 255};
     NodePairShapeMap edge_shapes;
     for (auto &e : graph.edges()) {
         auto edge_shape = std::make_shared<sp::Shape>();
         set(edge_shape->mutable_color(), black);
         edge_shape->set_opacity(1.0);
         edge_shape->set_persistent(true);
         auto &p1 = node_idx_to_pos.at(e.start_node_id());
         auto &p2 = node_idx_to_pos.at(e.end_node_id());
         set(edge_shape->mutable_line()->mutable_start(), p1.x(), p1.y(), p1.z());
         set(edge_shape->mutable_line()->mutable_end(), p2.x(), p2.y(), p2.z());
         plugin->draw_shape(edge_shape);
         edge_shapes[{e.start_node_id(), e.end_node_id()}] = edge_shape;
     }
     auto node_shape = std::make_shared<sp::Shape>();
     node_shape->set_persistent(true);
     auto to_pt = [&](auto &n) {return n.point();};
     for (const auto &pt : graph.nodes() | ba::transformed(to_pt)) {
         set(node_shape->mutable_pointcloud()->add_point(), pt.x(), pt.y(), pt.z());
         set(node_shape->mutable_pointcloud()->add_color(), blue);
     }
     node_shape->mutable_pointcloud()->set_size(6);
     plugin->draw_shape(node_shape);
     NodeShapeMap text_shapes;
     for (const auto &node : graph.nodes()) {
         auto text_shape = std::make_shared<sp::Shape>();
         text_shape->set_persistent(true);
         text_shape->set_opacity(1.0);
         set(text_shape->mutable_color(), white);
         if (draw_node_labels == DrawNodeLabels::YES) {
             Eigen::Vector3d pos(node.point().x(), node.point().y(), node.point().z());
             pos(0) += 5;
             set(text_shape->mutable_text()->mutable_center(), pos);
             text_shape->mutable_text()->set_scale(200);
             text_shape->mutable_text()->set_text(std::to_string(node.id()));
             plugin->draw_shape(text_shape);
             text_shapes[node.id()] = text_shape;
         }
     }
     return std::make_tuple(node_shape, edge_shapes, text_shapes);
 }
References scrimmage::set(), and YES.
Referenced by REGISTER_PLUGIN().
nodes_idxs_to_pos_map()
std::unordered_map< uint64_t, scrimmage_proto::Vector3d > scrimmage::interaction::nodes_idxs_to_pos_map (const scrimmage_msgs::Graph & graph)
Definition at line 115 of file GraphUtils.cpp.
{
     auto to_pos = [&](auto &node) {return std::make_pair(node.id(), node.point());};
     std::unordered_map<uint64_t, scrimmage_proto::Vector3d> out;
     br::transform(graph.nodes(), std::inserter(out, out.begin()), to_pos);
     return out;
 }
Referenced by REGISTER_PLUGIN().