SCRIMMAGE: scrimmage Namespace Reference
scrimmage Namespace Reference
Namespaces
anonymous_namespace{SimUtils.cpp}
autonomy
common
controller
interaction
metrics
motion
network
sensor
shape
Classes
class ActorContact
class Angles
class Autonomy
class Battery
class CameraInterface
struct CameraResetParams
struct Color_t
class ConfigParse
class Contact
class Controller
class CSV
class DelayedTask
repeats a task after a delay and some condition (if set) are met. The task can be set to repeat a finite number of times.
class Entity
class EntityInteraction
class EntityPlugin
struct EnvParams
struct EnvValues
class ExponentialFilter
class External
class FileSearch
class Frame
class FrameUpdateClient
struct GenerateInfo
class GlobalService
class Grid
class ID
class Interface
class Log
class Message
class MessageBase
class Metrics
class MissionParse
class MotionModel
class Network
class NetworkDevice
class OriginAxes
class Parameter
class ParameterBase
class ParameterServer
class PID
class Plugin
struct PluginAndConfig
class PluginInfo
class PluginManager
struct PluginOverrides
class PluginStatus
class Publisher
class PubSub
class Quaternion
class Random
class RTree
class ScrimmageMsgServiceImpl
class Sensor
class SimControl
struct SimUtilsInfo
class State
class StateWithCovariance
class Subscriber
class SubscriberBase
struct TeamInfo
class Time
class Timer
class Updater
class VariableIO
class Viewer
Typedefs
using FileSearchPtr = std::shared_ptr< FileSearch >
using Service = std::function< bool(scrimmage::MessageBasePtr, scrimmage::MessageBasePtr &)>
using GlobalServicePtr = std::shared_ptr< GlobalService >
using PluginPtr = std::shared_ptr< Plugin >
using ParameterBasePtr = std::shared_ptr< ParameterBase >
using ParameterServerPtr = std::shared_ptr< ParameterServer >
using RandomPtr = std::shared_ptr< Random >
typedef boost::geometry::model::point< double, 3, boost::geometry::cs::cartesian > point
typedef std::pair< point, ID > point_id_t
typedef boost::geometry::index::rtree< point_id_t, boost::geometry::index::dynamic_rstar, boost::geometry::index::indexable< point_id_t >, std::equal_to< point_id_t >, std::allocator< point_id_t > > rtree_t
typedef std::shared_ptr< rtree_t > rtreePtr
using RTreePtr = std::shared_ptr< RTree >
using TimePtr = std::shared_ptr< Time >
using StatePtr = std::shared_ptr< State >
using ContactMap = std::unordered_map< int, Contact >
using ContactMapPtr = std::shared_ptr< ContactMap >
typedef std::map< std::string, std::map< std::string, std::string > > AttributeMap
using EntityPtr = std::shared_ptr< Entity >
using PublisherPtr = std::shared_ptr< Publisher >
using EntityPluginPtr = std::shared_ptr< EntityPlugin >
using ShapePtr = std::shared_ptr< scrimmage_proto::Shape >
using AutonomyPtr = std::shared_ptr< Autonomy >
using VariableIOPtr = std::shared_ptr< VariableIO >
using NetworkPtr = std::shared_ptr< Network >
using NetworkMap = std::map< std::string, NetworkPtr >
using NetworkMapPtr = std::shared_ptr< NetworkMap >
using NetworkDevicePtr = std::shared_ptr< NetworkDevice >
using PubSubPtr = std::shared_ptr< PubSub >
using PublisherBasePtr = std::shared_ptr< PublisherBase >
using SubscriberBasePtr = std::shared_ptr< SubscriberBase >
using MessageBasePtr = std::shared_ptr< MessageBase >
template<class T >
using MessagePtr = std::shared_ptr< Message< T > >
using PluginManagerPtr = std::shared_ptr< PluginManager >
using MissionParsePtr = std::shared_ptr< MissionParse >
using MotionModelPtr = std::shared_ptr< MotionModel >
using ControllerPtr = std::shared_ptr< Controller >
using SensorPtr = std::shared_ptr< Sensor >
using InterfacePtr = std::shared_ptr< Interface >
using EntityInteractionPtr = std::shared_ptr< EntityInteraction >
using MetricsPtr = std::shared_ptr< Metrics >
using StateWithCovariancePtr = std::shared_ptr< StateWithCovariance >
typedef std::map< int, std::map< std::string, std::string > > EntityDesc_t
typedef std::shared_ptr< scrimmage_proto::ContactVisual > ContactVisualPtr
Enumerations
enum EndConditionFlags { EndConditionFlags::TIME = 1, EndConditionFlags::ONE_TEAM = 2, EndConditionFlags::NONE = 3, EndConditionFlags::ALL_DEAD = 4 }
Functions
template<class ContainerType , class Predicate >
void remove_if (ContainerType &container, Predicate pred)
std::remove_if does not work with associative containers.
template<class T = std::unordered_set<int>>
std::unordered_set< T > set_difference (const std::unordered_set< T > &container1, const std::unordered_set< T > &container2)
Returns container1 minus container2.
template<class T = std::unordered_set<int>>
std::unordered_set< T > set_union (const std::unordered_set< T > &container1, const std::unordered_set< T > &container2)
template<class T = std::unordered_set<int>>
std::unordered_set< T > set_intersection (const std::unordered_set< T > &container1, const std::unordered_set< T > &container2)
Color_t GetColor_matlab (double v, double vmin, double vmax)
double GetGray_matlab (Color_t c, double vmin, double vmax)
Color_t GetColor (double v, double vmin, double vmax)
int GetGray (Color_t c, double vmin, double vmax)
void display_progress (float progress)
int next_available_id (std::string name, std::map< std::string, std::string > &info, std::map< int, int > &id_map)
std::string get_sha (std::string &path)
std::string get_version ()
void filter_line (int downsampling_factor, int num_points, std::vector< Eigen::Vector3d > &path, std::vector< Eigen::Vector3d > &filtered_path)
std::string generate_chars (const std::string &symbol, int num)
std::string eigen_str (const Eigen::VectorXd &vec, uint8_t precision=2)
std::vector< double > linspace (double low, double high, uint32_t n)
template<class T >
T interp (const T &low, const T &high, double pct)
template<class T >
T scale (const T &input, const T &in_min, const T &in_max, const T &out_min, const T &out_max)
template<class T >
Eigen::VectorXd scale (const Eigen::VectorXd &input, const T &in_min, const T &in_max, const T &out_min, const T &out_max)
void print_io_error (const std::string &in_name, VariableIO &v)
bool verify_io_connection (VariableIO &output_plugin, VariableIO &input_plugin)
template<class T >
boost::optional< std::shared_ptr< T > > make_autonomy (const std::string &autonomy_name, PluginManagerPtr plugin_manager, std::map< std::string, std::string > &overrides, EntityPtr parent, StatePtr state, std::shared_ptr< std::unordered_map< int, int >> &id_to_team_map, std::shared_ptr< std::unordered_map< int, EntityPtr >> &id_to_ent_map, std::shared_ptr< GeographicLib::LocalCartesian > proj, ContactMapPtr &contacts, FileSearchPtr &file_search, RTreePtr &rtree, PubSubPtr &pubsub, const std::shared_ptr< const Time > &time, const ParameterServerPtr &param_server, const std::set< std::string > &plugin_tags={}, std::function< void(std::map< std::string, std::string > &)> param_override_func=[](std::map< std::string, std::string > &params){}, std::vector< ControllerPtr > controllers={}, const int &debug_level=0)
scrimmage::Quaternion operator* (const scrimmage::Quaternion &q1, const scrimmage::Quaternion &q2)
std::string expand_user (std::string path)
bool str2bool (std::string str)
template<class T >
std::enable_if_t<!std::is_pointer< T >::value, T > convert (const std::string &str)
template<class T >
std::enable_if_t< std::is_pointer< T >::value, T > convert (const std::string &str)
template<>
bool convert< bool > (const std::string &str)
template<>
const char * convert< const char * > (const std::string &str)
template<>
std::string convert< std::string > (const std::string &str)
template<class T1 , class T2 = T1>
T2 get (const std::string &key, const std::map< std::string, std::string > &map, T1 default_val)
void split (std::vector< std::string > &tokens, const std::string &str, const std::string &delims)
std::string remove_whitespace (const std::string &str)
template<typename T >
T str2container (const std::string &str, const std::string &delims)
template<typename T >
bool str2container (const std::string &str, const std::string &delims, T &result, int size=-1)
template<typename T >
std::vector< T > str2vec (const std::string &str, const std::string &delims)
template<typename T >
bool str2vec (const std::string &str, const std::string &delims, std::vector< T > &vec, int size=-1)
template<typename T >
bool get_vec (const std::string &str, const std::map< std::string, std::string > &params, const std::string &delims, std::vector< T > &vec, int size=-1)
bool get_vec (const std::string &str, std::map< std::string, std::string > &params, std::vector< std::string > &vec)
Eigen::Vector3d vec2eigen (std::vector< double > &vec)
bool find_terrain_files (std::string terrain_name, ConfigParse &terrain_parse, std::shared_ptr< scrimmage_proto::UTMTerrain > &utm_terrain)
bool find_model_properties (std::string model_name, ConfigParse &cv_parse, FileSearch &file_search, std::map< std::string, std::string > &overrides, std::shared_ptr< scrimmage_proto::ContactVisual > &cv, bool &mesh_found, bool &texture_found)
bool parse_autonomy_data (std::map< std::string, std::string > &params, std::map< std::string, std::string > &data_params)
bool get_vec_of_vecs (const std::string &str, std::vector< std::vector< std::string >> &out, const std::string &delims=" ,")
bool set_pid_gains (PID &pid, std::string str, bool is_angle=false)
unsigned int parse_plugin_vector (const std::string &key, std::map< std::string, std::string > &params, std::list< PluginOverrides > &plugin_overrides_list)
void remove_leading_spaces (std::string &s)
void remove_trailing_spaces (std::string &s)
template<class T >
bool load_plugins (const std::list< PluginOverrides > &plugin_names_overrides, const std::string &parent_class_name, std::map< std::string, PluginAndConfig< T >> &plugins_and_configs, const std::set< std::string > &plugin_tags={}, PluginManagerPtr mgr=std::make_shared< PluginManager >(), FileSearchPtr file_search=std::make_shared< FileSearch >())
void set (scrimmage_proto::Vector3d *dst, Eigen::Vector3d src)
void set (scrimmage_proto::Vector3d *dst, double x, double y, double z)
void set (scrimmage_proto::Color *dst, const std::vector< int > &src)
void set (Eigen::Vector3d &dst, const scrimmage_proto::Color &src)
void set (std::vector< int > &dst, const scrimmage_proto::Color &src)
void set (scrimmage_proto::Color &dst, const scrimmage_proto::Color &src)
void set (Eigen::Vector3d &dst, const scrimmage_proto::Vector3d *src)
void set (scrimmage_proto::Color &dst, scrimmage_proto::Color &src)
void set (scrimmage_proto::Color &dst, int r, int g, int b)
void set (scrimmage_proto::Color *dst, const Eigen::Vector3d &color)
void set (scrimmage_proto::Color *dst, scrimmage_proto::Color *src)
void set (scrimmage_proto::Color *dst, scrimmage_proto::Color src)
void set (scrimmage_proto::Color *dst, const scrimmage::Color_t &src)
void set (scrimmage_proto::Color *color, int r, int g, int b)
void set (scrimmage_proto::Color *color, int grayscale)
void set (scrimmage_proto::Quaternion *dst, const Quaternion &src)
void set (scrimmage_proto::Quaternion *dst, const double &w, const double &x, const double &y, const double &z)
void set (scrimmage_proto::State *dst, const scrimmage::StatePtr &state)
void set (scrimmage_proto::State *dst, const scrimmage::State &state)
void set (scrimmage::State &dst, const scrimmage_proto::State &state)
void set (scrimmage::Quaternion &dst, const scrimmage_proto::Quaternion &quat)
Eigen::Vector3d eigen (const scrimmage_proto::Vector3d &src)
void add_point_color (std::shared_ptr< scrimmage_proto::Shape > s, const scrimmage::Color_t &c)
void add_point_color (scrimmage_proto::ShapePtr s, const int &r, const int &g, const int &b)
void add_point_color (scrimmage_proto::ShapePtr s, const int &grayscale)
void set (scrimmage::ID &id, const scrimmage_proto::ID &proto_id)
Quaternion proto_2_quat (const scrimmage_proto::Quaternion &proto_quat)
void set (Eigen::Vector3d &dst, const scrimmage_proto::Vector3d &proto_vector3d)
Eigen::Vector3d proto_2_vector3d (const scrimmage_proto::Vector3d &proto_vector3d)
StatePtr proto_2_state (const scrimmage_proto::State &proto_state)
void path_to_lines (std::vector< Eigen::Vector3d > &path, std::shared_ptr< scrimmage_proto::Shape > sample_line, std::shared_ptr< EntityPlugin > p)
std::list< scrimmage_proto::Line > points_to_lines (const std::list< Eigen::Vector3d > &points)
Contact proto_2_contact (const scrimmage_proto::Contact &proto_contact)
Frame proto_2_frame (const scrimmage_proto::Frame &proto_frame)
std::shared_ptr< scrimmage_proto::Frame > create_frame (double time, std::shared_ptr< ContactMap > &contacts)
bool create_ent_inters (const SimUtilsInfo &info, ContactMapPtr contacts, std::list< scrimmage_proto::ShapePtr > &shapes, std::list< EntityInteractionPtr > &ent_inters, const GlobalServicePtr global_services, const std::set< std::string > &plugin_tags={}, std::function< void(std::map< std::string, std::string > &)> param_override_func=[](std::map< std::string, std::string > &){}, const int &debug_level=0)
bool create_metrics (const SimUtilsInfo &info, ContactMapPtr contacts, std::list< MetricsPtr > &metrics_list, const std::set< std::string > &plugin_tags={}, std::function< void(std::map< std::string, std::string > &)> param_override_func=[](std::map< std::string, std::string > &){}, const int &debug_level=0)
bool create_networks (const SimUtilsInfo &info, NetworkMap &networks, const std::set< std::string > &plugin_tags={}, std::function< void(std::map< std::string, std::string > &)> param_override_func=[](std::map< std::string, std::string > &){}, const int &debug_level=0)
void run_callbacks (EntityPluginPtr plugin)
boost::optional< std::string > run_test (const std::string &mission, const bool &init_python=true, const bool &shutdown_python=true)
std::ostream & operator<< (std::ostream &os, const CSV &csv)
std::ostream & operator<< (std::ostream &os, const ID &id)
void results_to_neighbors (std::list< point_id_t > &results, std::vector< ID > &neighbors, int self_id)
void connect (VariableIO &output, VariableIO &input)
std::ostream & operator<< (std::ostream &os, const Contact &c)
std::ostream & operator<< (std::ostream &os, const Quaternion &q)
std::ostream & operator<< (std::ostream &os, const State &s)
std::ostream & operator<< (std::ostream &os, ConfigParse &cp)
void set (Eigen::Vector3d &dst, scrimmage_proto::Vector3d *src)
void set (scrimmage_proto::State *dst, scrimmage::State &state)
void add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const scrimmage::Color_t &c)
void add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const int &r, const int &g, const int &b)
void add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const int &grayscale)
void print_err (EntityPluginPtr p)
void fpsCallbackFunction (vtkObject *caller, long unsigned int vtkNotUsed(eventId), void *vtkNotUsed(clientData), void *vtkNotUsed(callData))
Variables
double fps = 0
Typedef Documentation
FileSearchPtr
typedef std::shared_ptr< FileSearch > scrimmage::FileSearchPtr
Definition at line 73 of file FileSearch.h.
Service
typedef std::function< bool(scrimmage::MessageBasePtr, scrimmage::MessageBasePtr &)> scrimmage::Service
Definition at line 48 of file GlobalService.h.
GlobalServicePtr
typedef std::shared_ptr< GlobalService > scrimmage::GlobalServicePtr
Definition at line 91 of file GlobalService.h.
PluginPtr
typedef std::shared_ptr< Plugin > scrimmage::PluginPtr
Definition at line 43 of file Parameter.h.
ParameterBasePtr
typedef std::shared_ptr< ParameterBase > scrimmage::ParameterBasePtr
Definition at line 69 of file Parameter.h.
ParameterServerPtr
typedef std::shared_ptr< ParameterServer > scrimmage::ParameterServerPtr
Definition at line 115 of file ParameterServer.h.
RandomPtr
typedef std::shared_ptr< Random > scrimmage::RandomPtr
Definition at line 72 of file Random.h.
point
typedef boost::geometry::model::point<double, 3, boost::geometry::cs::cartesian> scrimmage::point
Definition at line 61 of file RTree.h.
point_id_t
typedef std::pair<point, ID> scrimmage::point_id_t
Definition at line 62 of file RTree.h.
rtree_t
typedef boost::geometry::index::rtree< point_id_t, boost::geometry::index::dynamic_rstar, boost::geometry::index::indexable<point_id_t>, std::equal_to<point_id_t>, std::allocator<point_id_t> > scrimmage::rtree_t
Definition at line 68 of file RTree.h.
rtreePtr
typedef std::shared_ptr<rtree_t> scrimmage::rtreePtr
Definition at line 70 of file RTree.h.
RTreePtr
typedef std::shared_ptr< RTree > scrimmage::RTreePtr
Definition at line 91 of file RTree.h.
TimePtr
typedef std::shared_ptr< Time > scrimmage::TimePtr
Definition at line 70 of file Time.h.
StatePtr
typedef std::shared_ptr< State > scrimmage::StatePtr
Definition at line 52 of file Contact.h.
ContactMap
typedef std::unordered_map< int, Contact > scrimmage::ContactMap
Definition at line 111 of file Contact.h.
ContactMapPtr
typedef std::shared_ptr< ContactMap > scrimmage::ContactMapPtr
Definition at line 112 of file Contact.h.
AttributeMap
typedef std::map< std::string, std::map< std::string, std::string > > scrimmage::AttributeMap
Definition at line 61 of file Entity.h.
EntityPtr
typedef std::shared_ptr< Entity > scrimmage::EntityPtr
Definition at line 246 of file Entity.h.
PublisherPtr
typedef std::shared_ptr< Publisher > scrimmage::PublisherPtr
Definition at line 62 of file EntityPlugin.h.
EntityPluginPtr
typedef std::shared_ptr< EntityPlugin > scrimmage::EntityPluginPtr
Definition at line 192 of file EntityPlugin.h.
ShapePtr
using scrimmage::ShapePtr = typedef std::shared_ptr<scrimmage_proto::Shape>
Definition at line 53 of file fwd_decl.h.
AutonomyPtr
using scrimmage::AutonomyPtr = typedef std::shared_ptr<Autonomy>
Definition at line 56 of file fwd_decl.h.
VariableIOPtr
using scrimmage::VariableIOPtr = typedef std::shared_ptr<VariableIO>
Definition at line 74 of file fwd_decl.h.
NetworkPtr
typedef std::shared_ptr< Network > scrimmage::NetworkPtr
Definition at line 92 of file fwd_decl.h.
NetworkMap
typedef std::map< std::string, NetworkPtr > scrimmage::NetworkMap
Definition at line 93 of file fwd_decl.h.
NetworkMapPtr
typedef std::shared_ptr< NetworkMap > scrimmage::NetworkMapPtr
Definition at line 94 of file fwd_decl.h.
NetworkDevicePtr
typedef std::shared_ptr< NetworkDevice > scrimmage::NetworkDevicePtr
Definition at line 97 of file fwd_decl.h.
PubSubPtr
typedef std::shared_ptr< PubSub > scrimmage::PubSubPtr
Definition at line 100 of file fwd_decl.h.
PublisherBasePtr
using scrimmage::PublisherBasePtr = typedef std::shared_ptr<PublisherBase>
Definition at line 103 of file fwd_decl.h.
SubscriberBasePtr
typedef std::shared_ptr< SubscriberBase > scrimmage::SubscriberBasePtr
Definition at line 109 of file fwd_decl.h.
MessageBasePtr
typedef std::shared_ptr< MessageBase > scrimmage::MessageBasePtr
Definition at line 112 of file fwd_decl.h.
MessagePtr
template<class T > using scrimmage::MessagePtr = typedef std::shared_ptr<Message<T> >
Definition at line 118 of file fwd_decl.h.
PluginManagerPtr
typedef std::shared_ptr< PluginManager > scrimmage::PluginManagerPtr
Definition at line 129 of file fwd_decl.h.
MissionParsePtr
typedef std::shared_ptr< MissionParse > scrimmage::MissionParsePtr
Definition at line 132 of file fwd_decl.h.
MotionModelPtr
typedef std::shared_ptr< MotionModel > scrimmage::MotionModelPtr
Definition at line 135 of file fwd_decl.h.
ControllerPtr
typedef std::shared_ptr< Controller > scrimmage::ControllerPtr
Definition at line 138 of file fwd_decl.h.
SensorPtr
typedef std::shared_ptr< Sensor > scrimmage::SensorPtr
Definition at line 141 of file fwd_decl.h.
InterfacePtr
typedef std::shared_ptr< Interface > scrimmage::InterfacePtr
Definition at line 146 of file fwd_decl.h.
EntityInteractionPtr
typedef std::shared_ptr< EntityInteraction > scrimmage::EntityInteractionPtr
Definition at line 149 of file fwd_decl.h.
MetricsPtr
typedef std::shared_ptr< Metrics > scrimmage::MetricsPtr
Definition at line 152 of file fwd_decl.h.
StateWithCovariancePtr
using scrimmage::StateWithCovariancePtr = typedef std::shared_ptr<StateWithCovariance>
Definition at line 55 of file StateWithCovariance.h.
EntityDesc_t
typedef std::map<int, std::map<std::string, std::string> > scrimmage::EntityDesc_t
Definition at line 58 of file MissionParse.h.
ContactVisualPtr
typedef std::shared_ptr<scrimmage_proto::ContactVisual> scrimmage::ContactVisualPtr
Definition at line 61 of file SimControl.h.
Enumeration Type Documentation
EndConditionFlags
enum scrimmage::EndConditionFlags strong
Enumerator
TIME
ONE_TEAM
NONE
ALL_DEAD
Definition at line 63 of file SimControl.h.
 {TIME = 1, ONE_TEAM = 2, NONE = 3, ALL_DEAD = 4};
Function Documentation
remove_if()
template<class ContainerType , class Predicate > void scrimmage::remove_if (ContainerType & container, Predicate pred)
std::remove_if does not work with associative containers.
This implementation assumes the first argument has an erase method.
Definition at line 46 of file Algorithm.h.
{
     auto it = container.begin();
     while (it != container.end()) {
         it = pred(*it) ? container.erase(it) : std::next(it);
     }
 }
Referenced by scrimmage::FileSearch::find_files(), scrimmage::SimControl::generate_entities(), scrimmage::CSV::get_csv_line_elements(), get_vec_of_vecs(), parse_plugin_vector(), REGISTER_PLUGIN(), remove_whitespace(), and str2bool().
set_difference()
template<class T = std::unordered_set<int>> std::unordered_set<T> scrimmage::set_difference (const std::unordered_set< T > & container1, const std::unordered_set< T > & container2)
Returns container1 minus container2.
std::set_difference does not work on unordered_sets
Definition at line 59 of file Algorithm.h.
{
     std::unordered_set<T> out;
     std::copy_if(container1.begin(), container1.end(), std::inserter(out, out.end()),
         [&](const T &val) {return container2.count(val) == 0;});
     return out;
 }
Referenced by verify_io_connection().
set_union()
template<class T = std::unordered_set<int>> std::unordered_set<T> scrimmage::set_union (const std::unordered_set< T > & container1, const std::unordered_set< T > & container2)
Definition at line 68 of file Algorithm.h.
{
     std::unordered_set<T> out = container1;
     out.insert(container2.begin(), container2.end());
     return out;
 }
set_intersection()
template<class T = std::unordered_set<int>> std::unordered_set<T> scrimmage::set_intersection (const std::unordered_set< T > & container1, const std::unordered_set< T > & container2)
Definition at line 76 of file Algorithm.h.
{
     std::unordered_set<T> out;
     std::copy_if(container1.begin(), container1.end(), std::inserter(out, out.end()),
         [&](const T &val) {return container2.count(val) != 0;});
     return out;
 }
GetColor_matlab()
Color_t scrimmage::GetColor_matlab (double v, double vmin, double vmax)
Definition at line 40 of file ColorMaps.cpp.
{
      Color_t c = {255.0, 255.0, 255.0}; // white
      double dv;
      if (v < vmin) {
           v = vmin;
      } else if (v > vmax) {
           v = vmax;
      }
      dv = vmax - vmin;
      double mx = v*0.5*vmax / (0.125*vmax - vmin);
      if (v < (vmin + 0.125 * dv)) {
           c.r = vmin;
           c.g = vmin;
           c.b = mx + 0.5*vmax;
      } else if (v < (vmin + 0.375 * dv)) {
           c.r = vmin;
           c.g = mx - 0.5*vmax;
           c.b = vmax;
      } else if (v < (vmin + 0.625 * dv)) {
           c.r = mx - 1.5*vmax;
           c.g = vmax;
           c.b = -mx + (vmax - 1.5*(vmin-vmax));
      } else if (v < (vmin + 0.875 * dv)) {
           c.r = vmax;
           c.g = -mx + (vmax - 2.5*(vmin-vmax));
           c.b = vmin;
      } else {
           c.r = -mx + 4.5*vmax;
           c.g = vmin;
           c.b = vmin;
      }
      return(c);
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, and scrimmage::Color_t::r.
Referenced by set().
GetGray_matlab()
double scrimmage::GetGray_matlab (Color_t c, double vmin, double vmax)
Definition at line 78 of file ColorMaps.cpp.
{
      double v = 0;
      // double slope = 0.5*vmax / (0.125*vmax - vmin);
      // double slope = (vmax - 0.5*(vmax-vmin)) / (0.125*(vmax-vmin)-vmin);
      // double slope = 0.5*(vmax-vmin) / (0.125*(vmax-vmin)-vmin);
      // double slope = 0.5*(vmax-vmin) / (0.125*vmax - 1.125*vmin);
      double slope = 4;
      if (c.g == vmin && c.r == vmin) {
           // v = (c.b - 0.5*vmax) / slope;
           v = (c.b - 0.5*(vmax-vmin)) / slope;
      } else if (c.b == vmax && c.r == vmin) {
           // v = (c.g + 0.5*vmax) / slope;
           v = (c.g + 0.5*(vmax-vmin) - vmin) / slope;
      } else if (c.g == vmax) {
           v = (c.r + 1.5*(vmax-vmin) - vmin) / slope;
           // v = (c.r - vmax + 5.0/2.0*(vmax-vmin)) / slope;
      } else if (c.b == vmin && c.r == vmax) {
           // v = (c.g - ((vmax - 2.5*(vmin-vmax)))) / (-slope);
           v = (c.g - 3.5*(vmax-vmin) - vmin) / -slope;
      } else if (c.g == vmin && c.b == vmin) {
           // v = (c.r - 4.5*vmax) / (-slope);
           v = (c.r - 4.5*(vmax) + 0.5*vmin) / -slope;
      }
      return v;
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, and scrimmage::Color_t::r.
GetColor()
Color_t scrimmage::GetColor (double v, double vmin, double vmax)
Definition at line 106 of file ColorMaps.cpp.
{
      Color_t c = {255.0, 255.0, 255.0}; // white
      // Color_t c = {1.0,1.0,1.0}; // white
      double dv;
      if (v < vmin) {
           v = vmin;
      } else if (v > vmax) {
           v = vmax;
      }
      dv = vmax - vmin;
      if (v < (vmin + 0.25 * dv)) {
           c.r = vmin;
           c.g = 4.0*v*(vmax-vmin)/vmax;
           c.b = vmax;
      } else if (v < (vmin + 0.5 * dv)) {
           c.r = vmin;
           c.g = vmax;
           c.b = 4.0*v*(vmin-vmax)/vmax-2*(vmin-vmax);
      } else if (v < (vmin + 0.75 * dv)) {
           c.r = 4.0*v*(vmax-vmin)/vmax-2*(vmax-vmin);
           c.g = vmax;
           c.b = vmin;
      } else {
           c.r = vmax;
           c.g = 4.0*v*(vmin-vmax)/vmax-4.0*(vmin-vmax);
           c.b = vmin;
      }
      return(c);
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, and scrimmage::Color_t::r.
GetGray()
int scrimmage::GetGray (Color_t c, double vmin, double vmax)
Definition at line 140 of file ColorMaps.cpp.
{
      int v = 0;
      if (c.r == vmin && c.b == vmax) {
           v = c.g * vmax / (4.0*(vmax-vmin));
      } else if (c.r == vmin && c.g == vmax) {
           v = (c.b + 2*(vmin-vmax)) / (4.0*(vmin-vmax)/vmax);
      } else if (c.g == vmax && c.b == vmin) {
           v = (c.r + 2*(vmax-vmin)) / (4.0*(vmax-vmin)/vmax);
      } else {
           v = (c.g + 4.0*(vmin-vmax)) / (4.0*(vmin-vmax)/vmax);
      }
      return v;
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, and scrimmage::Color_t::r.
display_progress()
void scrimmage::display_progress (float progress)
Definition at line 71 of file Utilities.cpp.
{
     int bar_width = 70;
     std::cout << "[";
     int pos = bar_width * progress;
     for (int i = 0; i < bar_width; ++i) {
         if (i < pos) {
             std::cout << "=";
         } else if (i == pos) {
             std::cout << ">";
         } else {
             std::cout << " ";
         }
     }
     std::cout << "] " << int(progress * 100.0) << " %\r";
     std::cout.flush();
 }
Referenced by scrimmage::SimControl::run_single_step().
next_available_id()
int scrimmage::next_available_id (std::string name, std::map< std::string, std::string > & info, std::map< int, int > & id_map)
Definition at line 52 of file Utilities.cpp.
{
     int id;
     if (info.count(name) > 0) {
         id = std::stoi(info[name]);
     } else {
         id = 1;
     }
     // Find the next available ID:
     while (id_map.count(id) > 0) id++;
     // Save the id in the map:
     id_map[id] = id;
     return id;
 }
get_sha()
std::string scrimmage::get_sha (std::string & path)
Definition at line 88 of file Utilities.cpp.
{
     std::string cd_cmd = "cd " + path + " && ";
     std::string sha_cmd = cd_cmd + "git rev-parse HEAD | tr -d '\n'";
     std::string status_cmd = cd_cmd + "git status --porcelain | wc -l";
     FILE *sha_file = popen(sha_cmd.c_str(), "r");
     FILE *status_file = popen(status_cmd.c_str(), "r");
     char sha[41], status[3];
     bool success =
         fgets(sha, 40, sha_file) != NULL &&
         fgets(status, 2, status_file) != NULL;
     pclose(sha_file);
     pclose(status_file);
     if (!success) {
         return "";
     } else if (status[0] == '0') {
         return std::string(sha);
     } else {
         return std::string(sha) + "-dirty";
     }
 }
Referenced by scrimmage::PluginManager::get_commits(), and get_version().
get_version()
std::string scrimmage::get_version ()
Definition at line 113 of file Utilities.cpp.
{
     const char *env = std::getenv("SCRIMMAGE_ROOT");
     if (env == NULL) {
         return std::string("");
     } else {
         std::string env_path(env);
         return get_sha(env_path);
     }
 }
References get_sha().
Referenced by scrimmage::SimControl::output_git_summary().
filter_line()
void scrimmage::filter_line (int downsampling_factor, int num_points, std::vector< Eigen::Vector3d > & path, std::vector< Eigen::Vector3d > & filtered_path)
Definition at line 123 of file Utilities.cpp.
{
     int curvature_sz = path.size() / downsampling_factor;
     std::list<std::pair<int, double>> curvature;
     auto idx = [=](int i) {return downsampling_factor * i;};
     for (int i = 1; i < curvature_sz - 1; i++) {
         Eigen::Vector3d &pt_prev = path[idx(i - 1)];
         Eigen::Vector3d &pt = path[idx(i)];
         Eigen::Vector3d &pt_next = path[idx(i + 1)];
         double curv = (pt_next - 2 * pt + pt_prev).squaredNorm();
         curvature.push_back(std::make_pair(idx(i), curv));
     }
     using Pair = std::pair<int, double>;
     curvature.sort([](Pair &a, Pair &b) {return a.second > b.second;});
     curvature.erase(std::next(curvature.begin(), num_points), curvature.end());
     curvature.sort([](Pair &a, Pair &b) {return a.first < b.first;});
     filtered_path.clear();
     filtered_path.reserve(curvature.size() + 2);
     filtered_path.push_back(path[0]);
     for (Pair &p : curvature) {
         filtered_path.push_back(path[p.first]);
     }
     filtered_path.push_back(path.back());
 }
generate_chars()
std::string scrimmage::generate_chars (const std::string & symbol, int num)
Definition at line 157 of file Utilities.cpp.
{
     std::string out = "";
     for (int i = 0; i < num; i++) {
         out += symbol;
     }
     return out;
 }
Referenced by scrimmage::SimControl::output_summary(), and REGISTER_PLUGIN().
eigen_str()
std::string scrimmage::eigen_str (const Eigen::VectorXd & vec, uint8_t precision = 2)
Definition at line 165 of file Utilities.cpp.
{
     if (vec.size() == 0) {
         return "";
     } else {
         std::stringstream ss;
         for (int i = 0; i < vec.size() - 1; i++) {
             ss << std::setprecision(precision) << vec(i) << ", ";
         }
         ss << std::setprecision(precision) << vec(vec.size() - 1);
         return ss.str();
     }
 }
Referenced by operator<<().
linspace()
std::vector< double > scrimmage::linspace (double low, double high, uint32_t n)
Definition at line 178 of file Utilities.cpp.
{
     std::vector<double> out;
     if (n > 0) {
         out.reserve(n);
         out.push_back(low);
         if (n > 1) {
             const double step = (high - low) / (n - 1);
             for (uint32_t i = 1; i < n - 1; i++) {
                 out.push_back(low + step * i);
             }
             out.push_back(high);
         }
     }
     return out;
 }
interp()
template<class T > T scrimmage::interp (const T & low, const T & high, double pct)
Definition at line 66 of file Utilities.h.
{
     return low + pct * (high - low);
 }
scale() [1/2]
template<class T > T scrimmage::scale (const T & input, const T & in_min, const T & in_max, const T & out_min, const T & out_max)
Definition at line 71 of file Utilities.h.
{
     T result = input;
     // Check for input/output min/max bounds
     if (in_min > in_max || out_min > out_max) {
         // cout << "Error: in_min > in_max || out_min > out_max" << endl;
         return 0;
     }
     // Saturate input
     if (result < in_min) {
         result = in_min;
     } else if (result > in_max) {
         result = in_max;
     }
     double scale_factor = (out_max - out_min) / (in_max - in_min);
     return (result - in_min) * scale_factor + out_min;
 }
Referenced by scrimmage::Updater::draw_mesh(), scrimmage::shape::make_mesh(), REGISTER_PLUGIN(), and scale().
scale() [2/2]
template<class T > Eigen::VectorXd scrimmage::scale (const Eigen::VectorXd & input, const T & in_min, const T & in_max, const T & out_min, const T & out_max)
Definition at line 92 of file Utilities.h.
{
     Eigen::VectorXd result = input;
     for (int i = 0; i < input.size(); i++) {
         result(i) = scale(input(i), in_min, in_max, out_min, out_max);
     }
     return result;
 }
References scale().
print_io_error()
void scrimmage::print_io_error (const std::string & in_name, VariableIO & v)
Definition at line 204 of file VariableIO.cpp.
{
     auto keys = v.input_variable_index() | ba::map_keys;
     std::cout << "First, include the VariableIO class in the cpp file: "
               << "#include <scrimmage/common/VariableIO.h>" << std::endl;
     std::cout << "Second, place the following in its initializer: " << std::endl;
     for (const std::string &key : keys) {
         std::cout << "    " << key << "_idx_ = vars_.declare("
                   << std::quoted(key) << ", scrimmage::VariableIO::Direction::Out);"
                   << std::endl;
     }
     std::cout << "Third, place the following in its step function: " << std::endl;
     for (const std::string &key : keys) {
         std::cout << "    vars_.output(" << key << "_idx_, value_to_output);" << std::endl;
     }
     std::cout << "where value_to_output is what you want " << in_name
               << " to receive as its input." << std::endl;
     std::cout << "Third, place following in the class declaration: " << std::endl;
     for (const std::string &key : keys) {
         std::cout << "    uint8_t " << key << "_idx_ = 0;" << std::endl;
     }
 }
References scrimmage::VariableIO::input_variable_index().
Referenced by scrimmage::External::create_entity(), and scrimmage::Entity::init().
verify_io_connection()
bool scrimmage::verify_io_connection (VariableIO & output_plugin, VariableIO & input_plugin)
Definition at line 194 of file VariableIO.cpp.
{
     std::vector<std::string> mismatched_keys;
     br::set_difference(
         input.declared_input_variables(),
         output.declared_output_variables(),
         std::back_inserter(mismatched_keys));
     return mismatched_keys.empty();
 }
References scrimmage::VariableIO::declared_input_variables(), scrimmage::VariableIO::declared_output_variables(), and set_difference().
Referenced by scrimmage::External::create_entity(), and scrimmage::Entity::init().
make_autonomy()
template<class T > boost::optional<std::shared_ptr<T> > scrimmage::make_autonomy (const std::string & autonomy_name, PluginManagerPtr plugin_manager, std::map< std::string, std::string > & overrides, EntityPtr parent, StatePtr state, std::shared_ptr< std::unordered_map< int, int >> & id_to_team_map, std::shared_ptr< std::unordered_map< int, EntityPtr >> & id_to_ent_map, std::shared_ptr< GeographicLib::LocalCartesian > proj, ContactMapPtr & contacts, FileSearchPtr & file_search, RTreePtr & rtree, PubSubPtr & pubsub, const std::shared_ptr< const Time > & time, const ParameterServerPtr & param_server, const std::set< std::string > & plugin_tags = {}, std::function< void(std::map< std::string, std::string > &)> param_override_func = [](std::map<std::string, std::string>& params){}, std::vector< ControllerPtr > controllers = {}, const int & debug_level = 0)
Definition at line 55 of file EntityPluginHelper.h.
                                            {},
     std::function<void(std::map<std::string, std::string>&)> param_override_func = [](std::map<std::string, std::string>& params){},
     std::vector<ControllerPtr> controllers = {},
     const int& debug_level = 0) {
     ConfigParse config_parse;
     PluginStatus<T> status =
             plugin_manager->make_plugin<T>(
                 "scrimmage::Autonomy", autonomy_name, *file_search,
                 config_parse, overrides, plugin_tags);
     if (status.status == PluginStatus<T>::cast_failed) {
         std::cout << "Failed to open autonomy plugin: " << autonomy_name << std::endl;
     } else if (status.status == PluginStatus<T>::parse_failed) {
         std::cout << "Parsing of plugin failed: " << autonomy_name << std::endl;
     } else if (status.status == PluginStatus<T>::loaded) {
         std::shared_ptr<T> autonomy = status.plugin;
         // Connect the autonomy to the first controller
         if (not controllers.empty()) {
             connect(autonomy->vars(), controllers.front()->vars());
         }
         autonomy->set_rtree(rtree);
         autonomy->set_parent(parent);
         autonomy->set_projection(proj);
         autonomy->set_pubsub(pubsub);
         autonomy->set_time(time);
         autonomy->set_id_to_team_map(id_to_team_map);
         autonomy->set_id_to_ent_map(id_to_ent_map);
         autonomy->set_param_server(param_server);
         autonomy->set_state(state);
         autonomy->set_contacts(contacts);
         autonomy->set_is_controlling(true);
         autonomy->set_name(autonomy_name);
         param_override_func(config_parse.params());
         if (debug_level > 1) {
             std::cout << "--------------------------------" << std::endl;
             std::cout << "Autonomy plugin params: " << autonomy_name << std::endl;
             std::cout << config_parse;
         }
         autonomy->init(config_parse.params());
         // get loop rate from plugin's params
         auto it_loop_rate = config_parse.params().find("loop_rate");
         if (it_loop_rate != config_parse.params().end()) {
             const double loop_rate = std::stod(it_loop_rate->second);
             autonomy->set_loop_rate(loop_rate);
         }
         return boost::optional<std::shared_ptr<T>>{autonomy};
     }
     return boost::none;
 }
operator*()
scrimmage::Quaternion scrimmage::operator* (const scrimmage::Quaternion & q1, const scrimmage::Quaternion & q2)
Definition at line 139 of file Quaternion.cpp.
{
     const Eigen::Quaternion<double, Eigen::DontAlign>& ep = p;
     const Eigen::Quaternion<double, Eigen::DontAlign>& eq = q;
     return scrimmage::Quaternion(ep * eq);
 }
expand_user()
std::string scrimmage::expand_user (std::string path)
Definition at line 180 of file ParseUtils.cpp.
{
     if (not path.empty() and path[0] == '~') {
         assert(path.size() == 1 or path[1] == '/');  // or other error handling
         char const* home = std::getenv("HOME");
         if (home or
             (home = std::getenv("USERPROFILE"))) {
             path.replace(0, 1, home);
         } else {
             char const *hdrive = std::getenv("HOMEDRIVE"),
                 *hpath = std::getenv("HOMEPATH");
             assert(hdrive);  // or other error handling
             assert(hpath);
             path.replace(0, 1, std::string(hdrive) + hpath);
         }
     }
     return path;
 }
Referenced by scrimmage::FileSearch::find_mission(), scrimmage::autonomy::MOOSAutonomy::init(), and scrimmage::MissionParse::parse().
str2bool()
bool scrimmage::str2bool (std::string str)
Definition at line 198 of file ParseUtils.cpp.
{
     // Remove spaces
     str.erase(std::remove_if(str.begin(), str.end(), ::isspace),
               str.end());
     if (boost::to_upper_copy(str) == "TRUE") {
         return true;
     }
     // Maybe it's a "1" or "0"
     int num;
     if (!(std::istringstream(str) >> num)) {
         num = 0;
     }
     return (num == 1);
 }
References remove_if().
Referenced by convert< bool >(), scrimmage::MissionParse::create_log_dir(), scrimmage::controller::JSBSimModelControllerDirect::init(), scrimmage::autonomy::AuctionAssign::init(), scrimmage::motion::DoubleIntegrator::init(), scrimmage::controller::SimpleAircraftControllerPID::init(), scrimmage::motion::JSBSimModel::init(), scrimmage::autonomy::RLSimple::init_helper(), scrimmage::MissionParse::parse(), scrimmage::MissionParse::parse_terrain(), REGISTER_PLUGIN(), and scrimmage::SimControl::start().
convert() [1/2]
template<class T > std::enable_if_t<!std::is_pointer<T>::value, T> scrimmage::convert (const std::string & str)
Definition at line 61 of file ParseUtils.h.
{
     T num;
     if (!(std::istringstream(str) >> num)) {
         num = 0;
     }
     return num;
 }
convert() [2/2]
template<class T > std::enable_if_t<std::is_pointer<T>::value, T> scrimmage::convert (const std::string & str)
Definition at line 71 of file ParseUtils.h.
{
     return nullptr;
 }
convert< bool >()
template<> bool scrimmage::convert< bool > (const std::string & str) inline
Definition at line 75 of file ParseUtils.h.
 {return str2bool(str);}
References str2bool().
convert< const char * >()
template<> const char* scrimmage::convert< const char * > (const std::string & str) inline
Definition at line 76 of file ParseUtils.h.
 {return str.c_str();}
convert< std::string >()
template<> std::string scrimmage::convert< std::string > (const std::string & str) inline
Definition at line 77 of file ParseUtils.h.
 {return str;}
get()
template<class T1 , class T2 = T1> T2 scrimmage::get (const std::string & key, const std::map< std::string, std::string > & map, T1 default_val)
Definition at line 80 of file ParseUtils.h.
{
     auto it = map.find(key);
     return it == map.end() ? default_val : convert<T2>(it->second);
 }
Referenced by scrimmage::SimControl::add_tasks(), scrimmage::SimControl::generate_entity(), get_vec(), scrimmage::motion::SingleIntegrator::init(), scrimmage::controller::SimpleQuadrotorControllerLQR::init(), scrimmage::autonomy::Boids::init(), scrimmage::controller::JSBSimModelControllerHeadingPID::init(), scrimmage::interaction::SimpleCollision::init(), scrimmage::interaction::GroundCollision::init(), scrimmage::motion::RigidBody6DOF::init(), scrimmage::motion::SimpleAircraft::init(), scrimmage::interaction::BulletCollision::init(), scrimmage::Entity::init(), scrimmage::autonomy::ScrimmageOpenAIAutonomy::init(), scrimmage::autonomy::init_actor_func(), scrimmage::MissionParse::parse_terrain(), REGISTER_PLUGIN(), scrimmage::Viewer::run(), scrimmage::External::setup_logging(), and scrimmage::SimControl::start().
split()
void scrimmage::split (std::vector< std::string > & tokens, const std::string & str, const std::string & delims)
Definition at line 343 of file ParseUtils.cpp.
{
     boost::split(tokens, str, boost::is_any_of(delims));
 }
Referenced by scrimmage::CSV::get_csv_line_elements(), get_vec_of_vecs(), scrimmage::PID::init(), scrimmage::sensor::AirSimSensor::parse_camera_configs(), scrimmage::sensor::AirSimSensor::parse_imu_configs(), scrimmage::sensor::AirSimSensor::parse_lidar_configs(), parse_plugin_vector(), scrimmage::CSV::read_csv_from_string(), REGISTER_PLUGIN(), scrimmage::MissionParse::set_overrides(), scrimmage::controller::set_pid(), set_pid_gains(), str2container(), and str2vec().
remove_whitespace()
std::string scrimmage::remove_whitespace (const std::string & str)
Definition at line 248 of file ParseUtils.cpp.
{
     std::string result = str;
     result.erase(
         std::remove_if(result.begin(),
                        result.end(),
                        [](unsigned char x){return std::isspace(x);}),
         result.end());
     return result;
 }
References remove_if().
Referenced by scrimmage::CSV::read_csv_from_string(), and scrimmage::MissionParse::set_overrides().
str2container() [1/2]
template<typename T > T scrimmage::str2container (const std::string & str, const std::string & delims)
Definition at line 92 of file ParseUtils.h.
{
     T out;
     std::vector<std::string> tokens;
     split(tokens, str, delims);
     for (std::string &t : tokens) {
         if (t.length() > 0) {
             out.insert(out.end(), convert<typename T::value_type>(t));
         }
     }
     return out;
 }
References split().
Referenced by find_model_properties(), scrimmage::Updater::get_model_texture(), get_vec(), scrimmage::controller::DoubleIntegratorControllerWaypoint::init(), scrimmage::interaction::MapGen2D::init(), scrimmage::sensor::GPS::init(), scrimmage::Entity::init(), scrimmage::MissionParse::parse(), scrimmage::Entity::parse_visual(), REGISTER_PLUGIN(), and scrimmage::Viewer::run().
str2container() [2/2]
template<typename T > bool scrimmage::str2container (const std::string & str, const std::string & delims, T & result, int size = -1)
Definition at line 106 of file ParseUtils.h.
{
     T tmp = str2container<T>(str, delims);
     if (size >= 0 && (unsigned int)size != tmp.size()) {
         return false;
     } else {
         // Only modify vec if it was a valid conversion
         result = tmp;
         return true;
     }
 }
str2vec() [1/2]
template<typename T > std::vector<T> scrimmage::str2vec (const std::string & str, const std::string & delims)
Definition at line 120 of file ParseUtils.h.
{
     std::vector<T> out;
     std::vector<std::string> tokens;
     split(tokens, str, delims);
     for (std::string &t : tokens) {
         if (t.length() > 0) {
             out.push_back(convert<T>(t));
         }
     }
     return out;
 }
References split().
str2vec() [2/2]
template<typename T > bool scrimmage::str2vec (const std::string & str, const std::string & delims, std::vector< T > & vec, int size = -1)
Definition at line 135 of file ParseUtils.h.
{
     std::vector<T> tmp_vec;
     std::vector<std::string> tokens;
     split(tokens, str, delims);
     for (std::string &t : tokens) {
         if (t.length() > 0) {
             tmp_vec.push_back(convert<T>(t));
         }
     }
     if (size >= 0 && (unsigned int)size != tmp_vec.size()) {
         return false;
     } else {
         // Only modify vec if it was a valid conversion
         vec = tmp_vec;
         return true;
     }
 }
References split().
get_vec() [1/2]
template<typename T > bool scrimmage::get_vec (const std::string & str, const std::map< std::string, std::string > & params, const std::string & delims, std::vector< T > & vec, int size = -1)
Definition at line 157 of file ParseUtils.h.
{
     auto it = params.find(str);
     return it == params.end() ? false : str2container(it->second, delims, vec, size);
 }
References str2container().
Referenced by scrimmage::autonomy::motor_schemas::BehaviorBase::configure_contacts(), scrimmage::sensor::NoisyState::init(), scrimmage::sensor::SimpleINS::init(), scrimmage::sensor::ContactBlobCamera::init(), scrimmage::sensor::RayTrace::init(), and REGISTER_PLUGIN().
get_vec() [2/2]
bool scrimmage::get_vec (const std::string & str, std::map< std::string, std::string > & params, std::vector< std::string > & vec)
Definition at line 215 of file ParseUtils.cpp.
{
     vec.clear();
     // Determine if the string name is a list
     int count = get(str+":size", params, 0);
     if (count <= 0) return false;
     for (int i = 0; i < count; i++) {
         std::string name = str;
         if (i > 0) {
             name += "_" + std::to_string(i);
         }
         if (params.count(name) == 0) {
             cout << "Invalid name in params: " << str << endl;
             return false;
         }
         vec.push_back(params[name]);
     }
     return true;
 }
References get().
vec2eigen()
Eigen::Vector3d scrimmage::vec2eigen (std::vector< double > & vec)
Definition at line 238 of file ParseUtils.cpp.
{
     Eigen::Vector3d v(0, 0, 0);
     if (vec.size() <= 3) {
         for (unsigned int i = 0; i < vec.size(); i++) {
             v(i) = vec[i];
         }
     }
     return v;
 }
Referenced by scrimmage::autonomy::Boids::init(), and REGISTER_PLUGIN().
find_terrain_files()
bool scrimmage::find_terrain_files (std::string terrain_name, ConfigParse & terrain_parse, std::shared_ptr< scrimmage_proto::UTMTerrain > & utm_terrain)
Definition at line 61 of file ParseUtils.cpp.
{
     if (utm_terrain == nullptr) {
         cout << "utm_terrain is null." << endl;
         return false;
     }
     utm_terrain->set_terrain_name(terrain_name);
     // Parse the motion model xml file
     terrain_parse.set_required("polydata");
     terrain_parse.set_required("texture");
     terrain_parse.set_required("system");
     terrain_parse.set_required("hemisphere");
     terrain_parse.set_required("zone");
     FileSearch file_search;
     std::map<std::string, std::string> overrides; // empty, no overrides
     if (terrain_parse.parse(overrides, terrain_name, "SCRIMMAGE_DATA_PATH", file_search)) {
         std::string polydata_file = terrain_parse.directory() + "/" + terrain_parse.params()["polydata"];
         std::string texture_file = terrain_parse.directory() + "/" + terrain_parse.params()["texture"];
         std::string extrusion_file = terrain_parse.directory() + "/" + terrain_parse.params()["extrusion"];
         std::string extrusion_property = terrain_parse.params()["extrusion_property"];
         if (fs::exists(extrusion_file) && fs::is_regular_file(extrusion_file) &&
                 !extrusion_property.empty()) {
             utm_terrain->set_extrusion_file(extrusion_file);
             utm_terrain->set_extrusion_property(extrusion_property);
             utm_terrain->set_enable_extrusion(true);
         }
         if (fs::exists(polydata_file) && fs::exists(texture_file) &&
             fs::is_regular_file(polydata_file) && fs::is_regular_file(texture_file)) {
             utm_terrain->set_texture_file(texture_file);
             utm_terrain->set_poly_data_file(polydata_file);
             return true;
         }
     }
     return false;
 }
References scrimmage::ConfigParse::directory(), scrimmage::ConfigParse::params(), scrimmage::ConfigParse::parse(), and scrimmage::ConfigParse::set_required().
Referenced by scrimmage::MissionParse::parse_terrain(), and scrimmage::Updater::update_utm_terrain().
find_model_properties()
bool scrimmage::find_model_properties (std::string model_name, ConfigParse & cv_parse, FileSearch & file_search, std::map< std::string, std::string > & overrides, std::shared_ptr< scrimmage_proto::ContactVisual > & cv, bool & mesh_found, bool & texture_found)
Definition at line 101 of file ParseUtils.cpp.
{
     if (cv == nullptr) {
         cout << "Contact Visual is null." << endl;
         return false;
     }
     mesh_found = texture_found = false;
     cv->set_name(model_name);
     cv_parse.set_required("model");
     if (cv_parse.parse(overrides, model_name, "SCRIMMAGE_DATA_PATH", file_search)) {
         std::string model_file = cv_parse.directory() + "/" + cv_parse.params()["model"];
         std::string texture_file = cv_parse.directory() + "/" + cv_parse.params()["texture"];
         if (fs::exists(model_file) && fs::is_regular_file(model_file)) {
             cv->set_model_file(model_file);
             mesh_found = true;
         }
         if (fs::exists(texture_file) && fs::is_regular_file(texture_file)) {
             cv->set_texture_file(texture_file);
             texture_found = true;
         }
     }
     auto it_info = cv_parse.params().find("visual_scale");
     if (it_info != cv_parse.params().end()) {
         cv->set_scale(std::stod(it_info->second));
     } else {
         cv->set_scale(1.0);
     }
     bool valid_rotate = false;
     it_info = cv_parse.params().find("visual_rpy");
     if (it_info != cv_parse.params().end()) {
         std::vector<double> temp_rotate;
         if (str2container(it_info->second, " ", temp_rotate, 3)) {
             valid_rotate = true;
             for (auto it = temp_rotate.begin(); it != temp_rotate.end(); it++) {
                 cv->add_rotate(*it);
             }
         } else {
             cout << "Error parsing: visual_rpy" << endl;
         }
     }
     if (!valid_rotate) {
         for (int i = 0; i < 3; i++) {
             cv->add_rotate(0);
         }
     }
     return (mesh_found && texture_found);
 }
References scrimmage::ConfigParse::directory(), scrimmage::ConfigParse::params(), scrimmage::ConfigParse::parse(), scrimmage::ConfigParse::set_required(), and str2container().
Referenced by scrimmage::Entity::parse_visual(), and scrimmage::Updater::update_contact_visual().
parse_autonomy_data()
bool scrimmage::parse_autonomy_data (std::map< std::string, std::string > & params, std::map< std::string, std::string > & data_params)
Definition at line 160 of file ParseUtils.cpp.
{
     if (params.count("data") == 0) {
         cout << "Missing data tag in params" << endl;
         return false;
     }
     ConfigParse data;
     FileSearch file_search;
     std::map<std::string, std::string> overrides; // empty, no overrides
     if (data.parse(overrides, params["data"], "SCRIMMAGE_DATA_PATH",
                    file_search)) {
         data_params = data.params();
     } else {
         cout << "Failed to find data file: " << params["data"] << endl;
         return false;
     }
     return true;
 }
References scrimmage::ConfigParse::params(), and scrimmage::ConfigParse::parse().
Referenced by REGISTER_PLUGIN().
get_vec_of_vecs()
bool scrimmage::get_vec_of_vecs (const std::string & str, std::vector< std::vector< std::string >> & out, const std::string & delims = " ,")
Definition at line 258 of file ParseUtils.cpp.
{
     // Of the form...
     // [a b c d]
     // [e f g h]
     // [h i j k]
     out.clear();
     std::string str_copy(str);
     remove_leading_spaces(str_copy);
     remove_trailing_spaces(str_copy);
     // First split based on user defined delimiters (typically ", ")
     std::vector<std::string> tokens;
     boost::algorithm::split(tokens, str_copy, boost::is_any_of(delims),
                             boost::token_compress_on);
     // The tokens vector consists of the delimited items. Break up each vector
     // based on the start "[" and stop "]" delimiters. However, we will allow
     // one-level of nested start and stop delimiters.
     std::vector<std::string> items;
     int open_bracket_count = 0;
     std::string item = "";
     for (std::string token : tokens) {
         // Remove whitespace
         token.erase(
             std::remove_if(token.begin(),
                            token.end(),
                            [](unsigned char x){return std::isspace(x);}),
             token.end());
         // cout << token << endl;
         for (unsigned int i = 0; i < token.size(); i++) {
             if (token[i] == '[') {
                 if (open_bracket_count > 0) {
                     item += "[";
                 }
                 ++open_bracket_count;
             } else if (token[i] == ']') {
                 if (open_bracket_count > 1) {
                     item += "]";
                 }
                 --open_bracket_count;
                 if (open_bracket_count == 0) {
                     items.push_back(item);
                     out.push_back(items);
                     items.clear();
                     item = "";
                 }
             } else if (open_bracket_count == 2) {
                 item += std::string(1, token[i]);
             } else if (open_bracket_count > 0) {
                 item += std::string(1, token[i]);
             }
         }
         if (open_bracket_count == 1) {
             items.push_back(item);
             item.clear();
         } else if (open_bracket_count == 0) {
             out.push_back(items);
             item.clear();
             items.clear();
         }
     }
     // Remove any empty strings from the individual vectors
     for (auto &vec : out) {
         vec.erase(std::remove_if(vec.begin(), vec.end(), [] (auto &str) {
             return str.empty();
         }), vec.end());
     }
     // Remove any empty vectors from the out vector of vectors
     out.erase(std::remove_if(out.begin(), out.end(), [] (auto &vec) {
         return vec.empty();
     }), out.end());
     return true;
 }
References remove_if(), remove_leading_spaces(), remove_trailing_spaces(), and split().
Referenced by scrimmage::sensor::ContactBlobCamera::init(), scrimmage::controller::Joystick::init(), scrimmage::motion::FixedWing6DOF::init(), parse_plugin_vector(), and REGISTER_PLUGIN().
set_pid_gains()
bool scrimmage::set_pid_gains (sc::PID & pid, std::string str, bool is_angle = false)
Definition at line 348 of file ParseUtils.cpp.
{
     std::vector<std::string> str_vals;
     boost::split(str_vals, str, boost::is_any_of(","));
     if (str_vals.size() != 4) {
         return false;
     } else {
         double p = std::stod(str_vals[0]);
         double i = std::stod(str_vals[1]);
         double d = std::stod(str_vals[2]);
         pid.set_parameters(p, i, d);
         if (is_angle) {
             double i_lim = sc::Angles::deg2rad(std::stod(str_vals[3]));
             pid.set_integral_band(i_lim);
             pid.set_is_angle(true);
         } else {
             double i_lim = std::stod(str_vals[3]);
             pid.set_integral_band(i_lim);
         }
     }
     return true;
 }
References scrimmage::Angles::deg2rad(), scrimmage::PID::set_integral_band(), scrimmage::PID::set_is_angle(), scrimmage::PID::set_parameters(), and split().
Referenced by scrimmage::controller::DoubleIntegratorControllerVelYaw::init(), and REGISTER_PLUGIN().
parse_plugin_vector()
unsigned int scrimmage::parse_plugin_vector (const std::string & key, std::map< std::string, std::string > & params, std::list< PluginOverrides > & plugin_overrides_list)
Definition at line 372 of file ParseUtils.cpp.
{
     // Parse the behavior plugins
     std::string plugins_str = sc::get<std::string>(key, params, "");
     std::vector<std::vector<std::string>> vecs_of_vecs;
     if (not sc::get_vec_of_vecs(plugins_str, vecs_of_vecs, " ")) {
         cout << "Failed to parse vector of vectors" << endl;
         return 0;
     }
     for (std::vector<std::string> vecs : vecs_of_vecs) {
         if (vecs.size() < 1) {
             std::cout << "Plugin name missing." << std::endl;
             continue;
         }
         std::string plugin_name = "";
         std::map<std::string, std::string> plugin_overrides;
         int i = 0;
         for (std::string str : vecs) {
             if (i == 0) {
                 plugin_name = str;
             } else {
                 // Parse the plugin parameters (e.g., param_name="value")
                 // Split the param_name and value, with equals sign in betweenn
                 std::vector<std::string> tokens;
                 boost::split(tokens, str, boost::is_any_of("="));
                 if (tokens.size() == 2) {
                     // Remove the quotes from the value
                     tokens[1].erase(
                         std::remove_if(tokens[1].begin(),
                                        tokens[1].end(),
                                        [](unsigned char x){
                                            return (x == '\"') || (x == '\'');
                                        }),
                         tokens[1].end());
                     plugin_overrides[tokens[0]] = tokens[1];
                 }
             }
             ++i;
         }
         plugin_overrides_list.push_back(PluginOverrides(plugin_name, plugin_overrides));
     }
     // for (auto &plugin_override : plugin_overrides_list) {
     //     cout << "Plugin name: " << plugin_override.name << endl;
     //     for (auto &kv : plugin_override.overrides) {
     //         cout << "\t" << kv.first << "=" << kv.second << endl;
     //     }
     // }
     return plugin_overrides_list.size();
 }
References get_vec_of_vecs(), remove_if(), and split().
Referenced by REGISTER_PLUGIN().
remove_leading_spaces()
void scrimmage::remove_leading_spaces (std::string & s)
Definition at line 426 of file ParseUtils.cpp.
{
     auto it = std::find_if(s.begin(), s.end(),
                            [](char c) {
                                return !std::isspace<char>(c, std::locale::classic());
                            });
     s.erase(s.begin(), it);
 }
Referenced by get_vec_of_vecs().
remove_trailing_spaces()
void scrimmage::remove_trailing_spaces (std::string & s)
Definition at line 434 of file ParseUtils.cpp.
{
     auto it = std::find_if(s.rbegin(), s.rend(),
                            [](char c) {
                                return !std::isspace<char>(c, std::locale::classic());
                            });
     s.erase(it.base(), s.end());
 }
Referenced by get_vec_of_vecs().
load_plugins()
template<class T > bool scrimmage::load_plugins (const std::list< PluginOverrides > & plugin_names_overrides, const std::string & parent_class_name, std::map< std::string, PluginAndConfig< T >> & plugins_and_configs, const std::set< std::string > & plugin_tags = {}, PluginManagerPtr mgr = std::make_shared<PluginManager>(), FileSearchPtr file_search = std::make_shared<FileSearch>())
Definition at line 63 of file PluginHelper.h.
                                                          {},
                   PluginManagerPtr mgr = std::make_shared<PluginManager>(),
                   FileSearchPtr file_search = std::make_shared<FileSearch>()
                   ) {
     bool all_loaded = true;
     for (const auto &plugin : plugin_names_overrides) {
         ConfigParse config_parse;
         PluginStatus<T> status =
                 mgr->make_plugin<T>(parent_class_name,
                                     plugin.name, *file_search, config_parse,
                                     plugin.overrides, plugin_tags);
         if (status.status == PluginStatus<T>::cast_failed) {
             cout << "Failed to open: " << parent_class_name  << ": " << plugin.name << endl;
             all_loaded = false;
         } else if (status.status == PluginStatus<T>::parse_failed) {
             cout << "Failed to parse: " << parent_class_name  << ": " << plugin.name << endl;
             all_loaded = false;
         } else if (status.status == PluginStatus<T>::loaded) {
             auto it_name = config_parse.params().find("name");
             std::string plugin_name = it_name == config_parse.params().end() ?
                     plugin.name : it_name->second;
             plugins_and_configs[plugin_name] = PluginAndConfig<T>(status.plugin, config_parse);
         }
         all_loaded &= (status.status == PluginStatus<T>::loaded);
     }
     return all_loaded;
 }
set() [1/25]
void scrimmage::set (scrimmage_proto::Vector3d * dst, Eigen::Vector3d src)
Definition at line 47 of file ProtoConversions.cpp.
{
     dst->set_x(src(0));
     dst->set_y(src(1));
     dst->set_z(src(2));
 }
Referenced by add_point_color(), create_frame(), scrimmage::sensor::ContactBlobCamera::draw_frustum(), scrimmage::interaction::draw_graph(), scrimmage::interaction::MapGen2D::init(), scrimmage::sensor::ContactBlobCamera::init(), scrimmage::interaction::BulletCollision::init(), scrimmage::autonomy::Waypoint::lla_proto(), scrimmage::shape::make_arc(), scrimmage::shape::make_arrow(), scrimmage::shape::make_circle(), scrimmage::shape::make_cone(), scrimmage::shape::make_cuboid(), scrimmage::shape::make_ellipse(), scrimmage::shape::make_line(), scrimmage::shape::make_mesh(), scrimmage::shape::make_plane(), scrimmage::shape::make_pointcloud(), scrimmage::shape::make_polydata(), scrimmage::shape::make_polygon(), scrimmage::shape::make_polyhedron(), scrimmage::shape::make_polyline(), scrimmage::shape::make_shape(), scrimmage::shape::make_sphere(), scrimmage::shape::make_spline(), scrimmage::shape::make_text(), scrimmage::shape::make_triangle(), scrimmage::MissionParse::parse_terrain(), scrimmage::Entity::parse_visual(), path_to_lines(), points_to_lines(), scrimmage::interaction::TerrainMap::proto(), proto_2_contact(), proto_2_state(), REGISTER_PLUGIN(), scrimmage::interaction::BulletCollision::remove_object(), set(), scrimmage::interaction::Sphere::set_visual(), scrimmage::interaction::Polyhedron::set_visual(), scrimmage::interaction::Cuboid::set_visual(), scrimmage::interaction::Plane::set_visual(), scrimmage::interaction::TerrainMap::shape(), scrimmage::SimControl::start(), scrimmage::sensor::ContactBlobCamera::step(), scrimmage::motion::JSBSimControl::step(), scrimmage::motion::FixedWing6DOF::step(), scrimmage::autonomy::Boids::step_autonomy(), scrimmage::interaction::BulletCollision::step_entity_interaction(), scrimmage::interaction::TerrainMap::TerrainMap(), scrimmage::Updater::update_contact_visual(), scrimmage::Updater::update_contacts(), scrimmage::autonomy::Waypoint::Waypoint(), and scrimmage::Updater::world_point_clicked().
set() [2/25]
void scrimmage::set (scrimmage_proto::Vector3d * dst, double x, double y, double z)
Definition at line 53 of file ProtoConversions.cpp.
{
     dst->set_x(x);
     dst->set_y(y);
     dst->set_z(z);
 }
set() [3/25]
void scrimmage::set (scrimmage_proto::Color * dst, const std::vector< int > & src)
Definition at line 67 of file ProtoConversions.cpp.
{
     dst->set_r(src[0]);
     dst->set_g(src[1]);
     dst->set_b(src[2]);
 }
set() [4/25]
void scrimmage::set (Eigen::Vector3d & dst, const scrimmage_proto::Color & src)
Definition at line 59 of file ProtoConversions.cpp.
{
     dst << src.r(), src.g(), src.b();
 }
set() [5/25]
void scrimmage::set (std::vector< int > & dst, const scrimmage_proto::Color & src)
Definition at line 63 of file ProtoConversions.cpp.
{
     dst = {src.r(), src.g(), src.b()};
 }
set() [6/25]
void scrimmage::set (scrimmage_proto::Color & dst, const scrimmage_proto::Color & src)
Definition at line 79 of file ProtoConversions.cpp.
{
     dst.set_r(src.r());
     dst.set_g(src.g());
     dst.set_b(src.b());
 }
set() [7/25]
void scrimmage::set (Eigen::Vector3d & dst, const scrimmage_proto::Vector3d * src)
set() [8/25]
void scrimmage::set (scrimmage_proto::Color & dst, scrimmage_proto::Color & src)
Definition at line 89 of file ProtoConversions.cpp.
{
     dst.set_r(src.r());
     dst.set_g(src.g());
     dst.set_b(src.b());
 }
set() [9/25]
void scrimmage::set (scrimmage_proto::Color & dst, int r, int g, int b)
Definition at line 95 of file ProtoConversions.cpp.
{
     scrimmage_proto::Color src;
     src.set_r(r);
     src.set_g(g);
     src.set_b(b);
     set(dst, src);
 }
References set().
set() [10/25]
void scrimmage::set (scrimmage_proto::Color * dst, const Eigen::Vector3d & color)
Definition at line 85 of file ProtoConversions.cpp.
{
      set(dst, color(0), color(1), color(2));
 }
References set().
set() [11/25]
void scrimmage::set (scrimmage_proto::Color * dst, scrimmage_proto::Color * src)
Definition at line 103 of file ProtoConversions.cpp.
{
     *dst = *src;
 }
set() [12/25]
void scrimmage::set (scrimmage_proto::Color * dst, scrimmage_proto::Color src)
Definition at line 107 of file ProtoConversions.cpp.
{
     dst->set_r(src.r());
     dst->set_g(src.g());
     dst->set_b(src.b());
 }
set() [13/25]
void scrimmage::set (scrimmage_proto::Color * dst, const scrimmage::Color_t & src)
Definition at line 113 of file ProtoConversions.cpp.
{
     dst->set_r(src.r);
     dst->set_g(src.g);
     dst->set_b(src.b);
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, and scrimmage::Color_t::r.
set() [14/25]
void scrimmage::set (scrimmage_proto::Color * color, int r, int g, int b)
Definition at line 119 of file ProtoConversions.cpp.
{
     scrimmage::Color_t c;
     c.r = r;
     c.g = g;
     c.b = b;
     set(color, c);
 }
References scrimmage::Color_t::b, scrimmage::Color_t::g, scrimmage::Color_t::r, and set().
set() [15/25]
void scrimmage::set (scrimmage_proto::Color * color, int grayscale)
Definition at line 128 of file ProtoConversions.cpp.
{
     Color_t c = GetColor_matlab(grayscale, 0, 255);
     set(color, c);
 }
References GetColor_matlab(), and set().
set() [16/25]
void scrimmage::set (scrimmage_proto::Quaternion * dst, const Quaternion & src)
Definition at line 133 of file ProtoConversions.cpp.
{
     dst->set_x(src.x());
     dst->set_y(src.y());
     dst->set_z(src.z());
     dst->set_w(src.w());
 }
set() [17/25]
void scrimmage::set (scrimmage_proto::Quaternion * dst, const double & w, const double & x, const double & y, const double & z)
Definition at line 140 of file ProtoConversions.cpp.
{
     dst->set_x(x);
     dst->set_y(y);
     dst->set_z(z);
     dst->set_w(w);
 }
set() [18/25]
void scrimmage::set (scrimmage_proto::State * dst, const scrimmage::StatePtr & state)
Definition at line 148 of file ProtoConversions.cpp.
{
     set(dst->mutable_position(), state->pos());
     set(dst->mutable_linear_velocity(), state->vel());
     set(dst->mutable_angular_velocity(), state->ang_vel());
     set(dst->mutable_orientation(), state->quat());
 }
References set().
set() [19/25]
void scrimmage::set (scrimmage_proto::State * dst, const scrimmage::State & state)
Definition at line 155 of file ProtoConversions.cpp.
{
     set(dst->mutable_position(), state.pos_const());
     set(dst->mutable_linear_velocity(), state.vel_const());
     set(dst->mutable_angular_velocity(), state.ang_vel_const());
     set(dst->mutable_orientation(), state.quat_const());
 }
References scrimmage::State::ang_vel_const(), scrimmage::State::pos_const(), scrimmage::State::quat_const(), set(), and scrimmage::State::vel_const().
set() [20/25]
void scrimmage::set (scrimmage::State & dst, const scrimmage_proto::State & state)
Definition at line 166 of file ProtoConversions.cpp.
{
     set(dst.pos(), state.position());
     set(dst.vel(), state.linear_velocity());
     set(dst.ang_vel(), state.angular_velocity());
     set(dst.quat(), state.orientation());
 }
References scrimmage::State::ang_vel(), scrimmage::State::pos(), scrimmage::State::quat(), set(), and scrimmage::State::vel().
set() [21/25]
void scrimmage::set (scrimmage::Quaternion & dst, const scrimmage_proto::Quaternion & quat)
Definition at line 162 of file ProtoConversions.cpp.
{
     dst.set(quat.w(), quat.x(), quat.y(), quat.z());
 }
References scrimmage::Quaternion::set().
eigen()
Eigen::Vector3d scrimmage::eigen (const scrimmage_proto::Vector3d & src)
Definition at line 180 of file ProtoConversions.cpp.
{
     Eigen::Vector3d dst;
     dst(0) = src.x();
     dst(1) = src.y();
     dst(2) = src.z();
     return dst;
 }
Referenced by scrimmage::Updater::draw_cone().
add_point_color() [1/6]
void scrimmage::add_point_color (std::shared_ptr< scrimmage_proto::Shape > s, const scrimmage::Color_t & c)
add_point_color() [2/6]
void scrimmage::add_point_color (scrimmage_proto::ShapePtr s, const int & r, const int & g, const int & b)
add_point_color() [3/6]
void scrimmage::add_point_color (scrimmage_proto::ShapePtr s, const int & grayscale)
set() [22/25]
void scrimmage::set (scrimmage::ID & id, const scrimmage_proto::ID & proto_id)
Definition at line 206 of file ProtoConversions.cpp.
{
     id.set_id(proto_id.id());
     id.set_sub_swarm_id(proto_id.sub_swarm_id());
     id.set_team_id(proto_id.team_id());
 }
proto_2_quat()
Quaternion scrimmage::proto_2_quat (const scrimmage_proto::Quaternion & proto_quat)
Definition at line 216 of file ProtoConversions.cpp.
{
     const Quaternion quat(proto_quat.w(), proto_quat.x(), proto_quat.y(), proto_quat.z());
     return quat;
 }
Referenced by proto_2_state(), and scrimmage::Updater::set_quat().
set() [23/25]
void scrimmage::set (Eigen::Vector3d & dst, const scrimmage_proto::Vector3d & proto_vector3d)
Definition at line 221 of file ProtoConversions.cpp.
{
     dst << proto_vector3d.x(), proto_vector3d.y(), proto_vector3d.z();
 }
proto_2_vector3d()
Eigen::Vector3d scrimmage::proto_2_vector3d (const scrimmage_proto::Vector3d & proto_vector3d)
Definition at line 212 of file ProtoConversions.cpp.
{
     return Eigen::Vector3d(proto_vector3d.x(), proto_vector3d.y(), proto_vector3d.z());
 }
proto_2_state()
StatePtr scrimmage::proto_2_state (const scrimmage_proto::State & proto_state)
Definition at line 225 of file ProtoConversions.cpp.
{
     State state;
     set(state.pos(), proto_state.position());
     set(state.vel(), proto_state.linear_velocity());
     set(state.ang_vel(), proto_state.angular_velocity());
     state.quat() = proto_2_quat(proto_state.orientation());
     return std::make_shared<State>(state);
 }
References scrimmage::State::ang_vel(), scrimmage::State::pos(), proto_2_quat(), scrimmage::State::quat(), set(), and scrimmage::State::vel().
Referenced by proto_2_contact().
path_to_lines()
void scrimmage::path_to_lines (std::vector< Eigen::Vector3d > & path, std::shared_ptr< scrimmage_proto::Shape > sample_line, std::shared_ptr< EntityPlugin > p)
Definition at line 234 of file ProtoConversions.cpp.
{
     for (size_t i = 0; i < path.size() - 1; i++) {
         auto ln = std::make_shared<scrimmage_proto::Shape>();
         ln->CopyFrom(*sample_line);
         scrimmage::set(ln->mutable_line()->mutable_start(), path[i]);
         scrimmage::set(ln->mutable_line()->mutable_end(), path[i + 1]);
         p->draw_shape(ln);
     }
 }
References scrimmage::EntityPlugin::draw_shape(), and set().
Referenced by scrimmage::sensor::ContactBlobCamera::draw_frustum().
points_to_lines()
std::list< scrimmage_proto::Line > scrimmage::points_to_lines (const std::list< Eigen::Vector3d > & points)
Definition at line 246 of file ProtoConversions.cpp.
{
     // Stop one item before the end of the points list
     auto stop = std::prev(points.end());
     std::list<scrimmage_proto::Line> lines;
     for (auto it = points.begin(); it != stop; ++it) {
         scrimmage_proto::Line line;
         set(line.mutable_start(), *it);
         set(line.mutable_end(), *std::next(it));
         lines.push_back(line);
     }
     return lines;
 }
References set().
proto_2_contact()
Contact scrimmage::proto_2_contact (const scrimmage_proto::Contact & proto_contact)
Definition at line 318 of file ProtoConversions.cpp.
{
     Contact contact;
     set(contact.id(), proto_contact.id());
     if (proto_contact.type() == scrimmage_proto::AIRCRAFT) {
         contact.set_type(Contact::Type::AIRCRAFT);
     } else if (proto_contact.type() == scrimmage_proto::QUADROTOR) {
         contact.set_type(Contact::Type::QUADROTOR);
     } else if (proto_contact.type() == scrimmage_proto::SPHERE) {
         contact.set_type(Contact::Type::SPHERE);
     } else if (proto_contact.type() == scrimmage_proto::MESH) {
         contact.set_type(Contact::Type::MESH);
     } else {
         contact.set_type(Contact::Type::UNKNOWN);
     }
     StatePtr state = proto_2_state(proto_contact.state());
     contact.set_state(state);
     return contact;
 }
References scrimmage::Contact::AIRCRAFT, scrimmage::ID::id(), scrimmage::Contact::id(), scrimmage::Contact::MESH, proto_2_state(), scrimmage::Contact::QUADROTOR, set(), scrimmage::Contact::set_state(), scrimmage::Contact::set_type(), scrimmage::Contact::SPHERE, and scrimmage::Contact::UNKNOWN.
Referenced by proto_2_frame().
proto_2_frame()
Frame scrimmage::proto_2_frame (const scrimmage_proto::Frame & proto_frame)
Definition at line 263 of file ProtoConversions.cpp.
{
     Frame frame;
     frame.contacts_ = std::make_shared<ContactMap>();
     frame.time_ = proto_frame.time();
     ContactMap &contacts = *(frame.contacts_);
     for (int i = 0; i < proto_frame.contact_size(); i++) {
         contacts[proto_frame.contact(i).id().id()] =
                 proto_2_contact(proto_frame.contact(i));
     }
     return frame;
 }
References scrimmage::Frame::contacts_, proto_2_contact(), and scrimmage::Frame::time_.
Referenced by scrimmage::Log::parse_frames().
create_frame()
std::shared_ptr< scrimmage_proto::Frame > scrimmage::create_frame (double time, std::shared_ptr< ContactMap > & contacts)
Definition at line 277 of file ProtoConversions.cpp.
{
     std::shared_ptr<scrimmage_proto::Frame> frame(new scrimmage_proto::Frame());
     frame->set_time(time);
     for (auto &kv : *contacts) {
         StatePtr &state = kv.second.state();
         Contact::Type type = kv.second.type();
         const ID &id = kv.second.id();
         scrimmage_proto::Contact *contact = frame->add_contact();
         scrimmage_proto::ID *sp_id = contact->mutable_id();
         set(contact->mutable_state(), state);
         switch (type) {
         case Contact::Type::AIRCRAFT:
             contact->set_type(scrimmage_proto::AIRCRAFT);
             break;
         case Contact::Type::QUADROTOR:
             contact->set_type(scrimmage_proto::QUADROTOR);
             break;
         case Contact::Type::SPHERE:
             contact->set_type(scrimmage_proto::SPHERE);
             break;
         case Contact::Type::MESH:
             contact->set_type(scrimmage_proto::MESH);
             break;
         default:
             contact->set_type(scrimmage_proto::UNKNOWN);
             break;
         }
         contact->set_active(kv.second.active());
         sp_id->set_id(id.id());
         sp_id->set_sub_swarm_id(id.sub_swarm_id());
         sp_id->set_team_id(id.team_id());
     }
     return frame;
 }
References scrimmage::Contact::AIRCRAFT, scrimmage::ID::id(), scrimmage::Contact::MESH, scrimmage::Contact::QUADROTOR, set(), and scrimmage::Contact::SPHERE.
Referenced by scrimmage::SimControl::run_logging(), and scrimmage::External::step().
create_ent_inters()
bool scrimmage::create_ent_inters (const SimUtilsInfo & info, ContactMapPtr contacts, std::list< scrimmage_proto::ShapePtr > & shapes, std::list< EntityInteractionPtr > & ent_inters, const GlobalServicePtr global_services, const std::set< std::string > & plugin_tags = {}, std::function< void(std::map< std::string, std::string > &)> param_override_func = [](std::map<std::string, std::string>&){}, const int & debug_level = 0)
Definition at line 58 of file SimUtils.cpp.
{
     for (std::string ent_inter_name : info.mp->entity_interactions()) {
         ConfigParse config_parse;
         std::map<std::string, std::string> &overrides =
             info.mp->attributes()[ent_inter_name];
         PluginStatus<EntityInteraction> status =
             info.plugin_manager->make_plugin<EntityInteraction>(
                 "scrimmage::EntityInteraction",
                 ent_inter_name, *info.file_search,
                 config_parse, overrides, plugin_tags);
         if (status.status == PluginStatus<EntityInteraction>::cast_failed) {
             cout << "Failed to load entity interaction plugin: "
                       << ent_inter_name << endl;
         } else if (status.status == PluginStatus<EntityInteraction>::loaded) {
             EntityInteractionPtr ent_inter = status.plugin;
             // If the name was overridden, use the override.
             std::string name = get<std::string>("name", config_parse.params(),
                                                 ent_inter_name);
             // Parent specific members
             ent_inter->parent()->set_random(info.random);
             ent_inter->parent()->set_mp(info.mp);
             ent_inter->parent()->set_projection(info.mp->projection());
             ent_inter->parent()->rtree() = info.rtree;
             ent_inter->parent()->contacts() = contacts;
             ent_inter->parent()->set_global_services(global_services);
             // Plugin specific members
             ent_inter->set_name(name);
             ent_inter->set_pubsub(info.pubsub);
             ent_inter->set_time(info.time);
             ent_inter->set_param_server(info.param_server);
             ent_inter->set_id_to_team_map(info.id_to_team_map);
             ent_inter->set_id_to_ent_map(info.id_to_ent_map);
             param_override_func(config_parse.params());
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Entity interaction plugin params: " << name << endl;
                 cout << config_parse;
             }
             ent_inter->init(info.mp->params(), config_parse.params());
             // Get shapes from plugin
             shapes.insert(
                 shapes.end(), ent_inter->shapes().begin(), ent_inter->shapes().end());
             ent_inter->shapes().clear();
             ent_inters.push_back(ent_inter);
         }
     }
     return true;
 }
References scrimmage::SimUtilsInfo::file_search, scrimmage::SimUtilsInfo::id_to_ent_map, scrimmage::SimUtilsInfo::id_to_team_map, scrimmage::SimUtilsInfo::mp, scrimmage::SimUtilsInfo::param_server, scrimmage::ConfigParse::params(), scrimmage::PluginStatus< T >::plugin, scrimmage::SimUtilsInfo::plugin_manager, scrimmage::SimUtilsInfo::pubsub, scrimmage::SimUtilsInfo::random, scrimmage::SimUtilsInfo::rtree, scrimmage::PluginStatus< T >::status, and scrimmage::SimUtilsInfo::time.
Referenced by scrimmage::External::create_entity(), and scrimmage::SimControl::start().
create_metrics()
bool scrimmage::create_metrics (const SimUtilsInfo & info, ContactMapPtr contacts, std::list< MetricsPtr > & metrics_list, const std::set< std::string > & plugin_tags = {}, std::function< void(std::map< std::string, std::string > &)> param_override_func = [](std::map<std::string, std::string>&){}, const int & debug_level = 0)
Definition at line 123 of file SimUtils.cpp.
{
     for (std::string metrics_name : info.mp->metrics()) {
         ConfigParse config_parse;
         std::map<std::string, std::string> &overrides =
             info.mp->attributes()[metrics_name];
         PluginStatus<Metrics> status =
             info.plugin_manager->make_plugin<Metrics>(
                 "scrimmage::Metrics", metrics_name,
                 *info.file_search, config_parse, overrides,
                 plugin_tags);
         if (status.status == PluginStatus<Metrics>::cast_failed) {
             cout << "Failed to load metrics: " << metrics_name << endl;
             return false;
         } else if (status.status == PluginStatus<Metrics>::loaded) {
             MetricsPtr metrics = status.plugin;
             // Parent specific members
             metrics->parent()->set_random(info.random);
             metrics->parent()->set_mp(info.mp);
             metrics->parent()->set_projection(info.mp->projection());
             metrics->parent()->rtree() = info.rtree;
             metrics->parent()->contacts() = contacts;
             // Plugin specific members
             metrics->set_name(metrics_name);
             metrics->set_pubsub(info.pubsub);
             metrics->set_time(info.time);
             metrics->set_param_server(info.param_server);
             metrics->set_id_to_team_map(info.id_to_team_map);
             metrics->set_id_to_ent_map(info.id_to_ent_map);
             param_override_func(config_parse.params());
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Metrics plugin params: " << metrics_name << endl;
                 cout << config_parse;
             }
             metrics->init(config_parse.params());
             metrics_list.push_back(metrics);
         }
     }
     return true;
 }
References scrimmage::SimUtilsInfo::file_search, scrimmage::SimUtilsInfo::id_to_ent_map, scrimmage::SimUtilsInfo::id_to_team_map, scrimmage::SimUtilsInfo::mp, scrimmage::SimUtilsInfo::param_server, scrimmage::ConfigParse::params(), scrimmage::PluginStatus< T >::plugin, scrimmage::SimUtilsInfo::plugin_manager, scrimmage::SimUtilsInfo::pubsub, scrimmage::SimUtilsInfo::random, scrimmage::SimUtilsInfo::rtree, scrimmage::PluginStatus< T >::status, and scrimmage::SimUtilsInfo::time.
Referenced by scrimmage::External::create_entity(), and scrimmage::SimControl::start().
create_networks()
bool scrimmage::create_networks (const SimUtilsInfo & info, NetworkMap & networks, const std::set< std::string > & plugin_tags = {}, std::function< void(std::map< std::string, std::string > &)> param_override_func = [](std::map<std::string, std::string>&){}, const int & debug_level = 0)
Definition at line 229 of file SimUtils.cpp.
{
     for (std::string network_name : info.mp->network_names()) {
         ConfigParse config_parse;
         std::map<std::string, std::string> &overrides =
             info.mp->attributes()[network_name];
         PluginStatus<Network> status =
             info.plugin_manager->make_plugin<Network>(
                 "scrimmage::Network", network_name, *info.file_search,
                 config_parse, overrides, plugin_tags);
         if (status.status == PluginStatus<Network>::cast_failed) {
             cout << "Failed to load network plugin: "
                 << network_name << endl;
             return false;
         } else if (status.status == PluginStatus<Network>::loaded) {
             NetworkPtr network = status.plugin;
             // If the name was overridden, use the override.
             std::string name =
                 get<std::string>("name", config_parse.params(), network_name);
             network->set_name(name);
             network->set_mission_parse(info.mp);
             network->set_time(info.time);
             network->set_param_server(info.param_server);
             network->set_pubsub(info.pubsub);
             network->set_random(info.random);
             network->set_rtree(info.rtree);
             network->set_id_to_team_map(info.id_to_team_map);
             network->set_id_to_ent_map(info.id_to_ent_map);
             // Seed the pubsub with network names
             info.pubsub->add_network_name(name);
             param_override_func(config_parse.params());
             if (debug_level > 1) {
                 cout << "--------------------------------" << endl;
                 cout << "Network plugin params: " << name << endl;
                 cout << config_parse;
             }
             network->init(info.mp->params(), config_parse.params());
             networks[name] = network;
         }
     }
     return true;
 }
References scrimmage::SimUtilsInfo::file_search, scrimmage::SimUtilsInfo::id_to_ent_map, scrimmage::SimUtilsInfo::id_to_team_map, scrimmage::SimUtilsInfo::mp, scrimmage::SimUtilsInfo::param_server, scrimmage::ConfigParse::params(), scrimmage::PluginStatus< T >::plugin, scrimmage::SimUtilsInfo::plugin_manager, scrimmage::SimUtilsInfo::pubsub, scrimmage::SimUtilsInfo::random, scrimmage::SimUtilsInfo::rtree, scrimmage::PluginStatus< T >::status, and scrimmage::SimUtilsInfo::time.
Referenced by scrimmage::External::create_entity(), and scrimmage::SimControl::start().
run_callbacks()
void scrimmage::run_callbacks (EntityPluginPtr plugin)
Definition at line 176 of file SimUtils.cpp.
{
     for (auto &sub : plugin->subs()) {
         for (auto msg : sub->pop_msgs<MessageBase>()) {
             sub->accept(msg);
         }
     }
 }
Referenced by scrimmage::SimControl::run_entities(), scrimmage::SimControl::run_interaction_detection(), scrimmage::SimControl::run_metrics(), scrimmage::SimControl::run_sensors(), scrimmage::SimControl::run_single_step(), scrimmage::External::send_messages(), and scrimmage::SimControl::worker().
run_test()
boost::optional< std::string > scrimmage::run_test (const std::string & mission, const bool & init_python = true, const bool & shutdown_python = true)
Definition at line 190 of file SimUtils.cpp.
{
     SimControl simcontrol;
     if (not simcontrol.init(mission, init_python)) {
         cout << "Failed to initialize SimControl." << endl;
         return boost::none;
     }
     // Handle kill signals
     struct sigaction sa;
     memset( &sa, 0, sizeof(sa) );
     shutdown_handler = [&](int /*s*/){
         cout << endl << "Exiting gracefully" << endl;
         simcontrol.force_exit();
     };
     sa.sa_handler = signal_handler;
     sigfillset(&sa.sa_mask);
     sigaction(SIGINT, &sa, NULL);
     sigaction(SIGTERM, &sa, NULL);
     simcontrol.mp()->set_time_warp(-1);
     simcontrol.mp()->set_enable_gui(false);
     simcontrol.pause(false);
     if (not simcontrol.run()) {
         return boost::none;
     }
     // Extract the log directory
     auto out = boost::optional<std::string>{simcontrol.mp()->log_dir()};
     // Shutdown SimControl
     if (not simcontrol.shutdown(shutdown_python)) {
         return boost::none;
     }
     return out;
 }
References scrimmage::SimControl::force_exit(), scrimmage::SimControl::init(), scrimmage::SimControl::mp(), scrimmage::SimControl::pause(), scrimmage::SimControl::run(), scrimmage::SimControl::shutdown(), scrimmage::anonymous_namespace{SimUtils.cpp}::shutdown_handler, and scrimmage::anonymous_namespace{SimUtils.cpp}::signal_handler().
operator<<() [1/6]
std::ostream& scrimmage::operator<< (std::ostream & os, const CSV & csv)
Definition at line 119 of file CSV.cpp.
{
     os << csv.to_string();
     return os;
 }
References scrimmage::CSV::to_string().
operator<<() [2/6]
std::ostream& scrimmage::operator<< (std::ostream & os, const ID & id)
Definition at line 74 of file ID.cpp.
{
     os << id.id_ << ", " << id.sub_swarm_id_ << ", " << id.team_id_;
     return os;
 }
results_to_neighbors()
void scrimmage::results_to_neighbors (std::list< point_id_t > & results, std::vector< ID > & neighbors, int self_id)
Definition at line 74 of file RTree.cpp.
{
     neighbors.clear();
     neighbors.reserve(results.size());
     if (self_id >= 0) {
         for (point_id_t &pt_id : results) {
             if (pt_id.second.id() != self_id) {
                 neighbors.push_back(pt_id.second);
             }
         }
     } else {
         for (point_id_t &pt_id : results) {
             neighbors.push_back(pt_id.second);
         }
     }
 }
Referenced by scrimmage::RTree::nearest_n_neighbors(), and scrimmage::RTree::neighbors_in_range().
connect()
void scrimmage::connect (VariableIO & output, VariableIO & input)
Definition at line 158 of file VariableIO.cpp.
{
     output.output_variable_index() = input.input_variable_index();
     output.output_ = input.input_;
 }
References scrimmage::VariableIO::input_, scrimmage::VariableIO::input_variable_index(), scrimmage::VariableIO::output_, and scrimmage::VariableIO::output_variable_index().
Referenced by scrimmage::External::create_entity(), and scrimmage::Entity::init().
operator<<() [3/6]
std::ostream& scrimmage::operator<< (std::ostream & os, const Contact & c)
Definition at line 77 of file Contact.cpp.
{
     os << c.id_ << ": " << *c.state_;
     return os;
 }
References scrimmage::Contact::id_, and scrimmage::Contact::state_.
operator<<() [4/6]
std::ostream& scrimmage::operator<< (std::ostream & os, const Quaternion & q)
Definition at line 131 of file Quaternion.cpp.
{
     os << "w: " << std::setprecision(q.output_precision) << q.w()
        << ", x: " << std::setprecision(q.output_precision) << q.x()
        << ", y: " << std::setprecision(q.output_precision) << q.y()
        << ", z: " << std::setprecision(q.output_precision) << q.z();
     return os;
 }
References scrimmage::Quaternion::output_precision.
operator<<() [5/6]
std::ostream& scrimmage::operator<< (std::ostream & os, const State & s)
Definition at line 115 of file State.cpp.
{
     const Quaternion &q = s.quat();
     os << "(" << eigen_str(s.pos_, s.output_precision)
         << "), (" << eigen_str(s.vel_, s.output_precision)
         << "), (" << eigen_str(s.ang_vel_, s.output_precision)
         << "), ("
         << std::setprecision(s.output_precision) << q.roll() << ", "
         << std::setprecision(s.output_precision) << q.pitch() << ", "
         << std::setprecision(s.output_precision) << q.yaw() << ")";
     return os;
 }
References scrimmage::State::ang_vel_, eigen_str(), scrimmage::State::output_precision, scrimmage::Quaternion::pitch(), scrimmage::State::pos_, scrimmage::State::quat(), scrimmage::Quaternion::roll(), scrimmage::State::vel_, and scrimmage::Quaternion::yaw().
operator<<() [6/6]
std::ostream& scrimmage::operator<< (std::ostream & os, ConfigParse & cp)
Definition at line 192 of file ConfigParse.cpp.
{
     for (auto &kv : cp.params()) {
         os << kv.first << "=" << kv.second << endl;
     }
     return os;
 }
References scrimmage::ConfigParse::params().
set() [24/25]
void scrimmage::set (Eigen::Vector3d & dst, scrimmage_proto::Vector3d * src)
Definition at line 73 of file ProtoConversions.cpp.
{
     dst(0) = src->x();
     dst(1) = src->y();
     dst(2) = src->z();
 }
set() [25/25]
void scrimmage::set (scrimmage_proto::State * dst, scrimmage::State & state)
Definition at line 173 of file ProtoConversions.cpp.
{
     set(dst->mutable_position(), state.pos());
     set(dst->mutable_linear_velocity(), state.vel());
     set(dst->mutable_angular_velocity(), state.ang_vel());
     set(dst->mutable_orientation(), state.quat());
 }
References scrimmage::State::ang_vel(), scrimmage::State::pos(), scrimmage::State::quat(), set(), and scrimmage::State::vel().
add_point_color() [4/6]
void scrimmage::add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const scrimmage::Color_t & c)
Definition at line 188 of file ProtoConversions.cpp.
{
     scrimmage_proto::Color *color = s->add_color();
     set(color, c);
 }
References set().
add_point_color() [5/6]
void scrimmage::add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const int & r, const int & g, const int & b)
Definition at line 194 of file ProtoConversions.cpp.
{
     scrimmage_proto::Color *color = s->add_color();
     set(color, r, g, b);
 }
References set().
add_point_color() [6/6]
void scrimmage::add_point_color (std::shared_ptr< scrimmage_proto::PointCloud > s, const int & grayscale)
Definition at line 200 of file ProtoConversions.cpp.
{
     scrimmage_proto::Color *color = s->add_color();
     set(color, grayscale);
 }
References set().
print_err()
void scrimmage::print_err (EntityPluginPtr p)
Definition at line 1440 of file SimControl.cpp.
{
     if (p->print_err_on_exit) {
         std::cout << "failed to update entity " << p->parent()->id().id()
             << ", plugin type \"" << p->type() << "\""
             << ", plugin name \"" << p->name() << "\"" << std::endl;
     }
 }
Referenced by scrimmage::SimControl::run_entities(), and scrimmage::SimControl::run_sensors().
fpsCallbackFunction()
void scrimmage::fpsCallbackFunction (vtkObject * caller, long unsigned int vtkNotUsedeventId, void * vtkNotUsedclientData, void * vtkNotUsedcallData)
Definition at line 112 of file Updater.cpp.
{
     vtkRenderer* renderer = static_cast<vtkRenderer*>(caller);
     double timeInSeconds = renderer->GetLastRenderTimeInSeconds();
     fps = 1.0/timeInSeconds;
 }
References fps.
Referenced by scrimmage::Updater::enable_fps().
Variable Documentation
fps
double scrimmage::fps = 0
Definition at line 111 of file Updater.cpp.
Referenced by fpsCallbackFunction(), and scrimmage::Updater::update_text_display().