SCRIMMAGE: scrimmage::anonymous_namespace{SimUtils.cpp} Namespace Reference
scrimmage::anonymous_namespace{SimUtils.cpp} Namespace Reference
Functions
void signal_handler (int signal)
Variables
std::function< void(int)> shutdown_handler
Function Documentation
signal_handler()
void scrimmage::anonymous_namespace{SimUtils.cpp}::signal_handler (int signal)
Definition at line 187 of file SimUtils.cpp.
 { shutdown_handler(signal); }
References shutdown_handler.
Referenced by scrimmage::run_test().
Variable Documentation
shutdown_handler
std::function<void(int)> scrimmage::anonymous_namespace{SimUtils.cpp}::shutdown_handler
Definition at line 186 of file SimUtils.cpp.
Referenced by scrimmage::run_test(), and signal_handler().