SCRIMMAGE: scrimmage::controller Namespace Reference
scrimmage::controller Namespace Reference
Classes
class AircraftPIDController
class AircraftToSingleIntegratorController
class AxisScale
class DirectController
class DoubleIntegratorControllerVelYaw
class DoubleIntegratorControllerWaypoint
class FixedWing6DOFControllerPID
class FixedWing6DOFControllerROS
class HarmonicOscillatorConstController
class Joystick
class JoystickController
class JSBSimControlControllerHeadingPID
class JSBSimModelControllerDirect
class JSBSimModelControllerHeadingPID
class MotionBattery
class MultirotorControllerOmega
class MultirotorControllerPID
class RigidBody6DOFControllerPID
class RigidBody6DOFControllerROS
class SimpleAircraftControllerPID
class SimpleCarControllerHeading
class SimpleQuadrotorControllerLQR
class SingleIntegratorControllerSimple
class SingleIntegratorControllerWaypoint
class UnicycleControllerPoint
implementation of [olfati2002near]
class UnicyclePID
class UUV6DOFLinearEnergy
class UUV6DOFPIDController
Typedefs
using ang = scrimmage::Angles
Functions
void set_pid (sc::PID &pid, std::string str, bool is_angle)
Typedef Documentation
ang
typedef scrimmage::Angles scrimmage::controller::ang
Definition at line 49 of file JSBSimControlControllerHeadingPID.cpp.
Function Documentation
set_pid()
void scrimmage::controller::set_pid (sc::PID & pid, std::string str, bool is_angle)
Definition at line 48 of file RigidBody6DOFControllerPID.cpp.
{
     std::vector<std::string> str_vals;
     boost::split(str_vals, str, boost::is_any_of(","));
     if (str_vals.size() != 4) {
         std::cout << "error parsing in RigidBody6DOFControllerPID" << std::endl;
     } else {
         double p = std::stod(str_vals[0]);
         double i = std::stod(str_vals[1]);
         double d = std::stod(str_vals[2]);
         pid.set_parameters(p, i, d);
         if (is_angle) {
             double i_lim = sc::Angles::deg2rad(std::stod(str_vals[3]));
             pid.set_integral_band(i_lim);
             pid.set_is_angle(true);
         } else {
             double i_lim = std::stod(str_vals[3]);
             pid.set_integral_band(i_lim);
         }
     }
 }
References scrimmage::Angles::deg2rad(), scrimmage::PID::set_integral_band(), scrimmage::PID::set_is_angle(), scrimmage::PID::set_parameters(), and scrimmage::split().
Referenced by scrimmage::controller::RigidBody6DOFControllerPID::init(), and REGISTER_PLUGIN().