SCRIMMAGE: scrimmage::shape Namespace Reference
scrimmage::shape Namespace Reference
Typedefs
using ShapePtr = std::shared_ptr< scrimmage_proto::Shape >
Functions
ShapePtr make_shape (const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_arc (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &radius=1.0, const double &angle=M_PI/2.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_arrow (const Eigen::Vector3d &pos=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &length=10.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_circle (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &radius=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_cone (const Eigen::Vector3d &direction=Eigen::Vector3d(0, 0, 1), const Eigen::Vector3d &apex=Eigen::Vector3d(0, 0, 1), const double &height=1.0, const double &base_radius=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_cuboid (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &x_length=1.0, const double &y_length=1.0, const double &z_length=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_ellipse (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &x_radius=2.0, const double &y_radius=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_line (const Eigen::Vector3d &start=Eigen::Vector3d(0, 0, 0), const Eigen::Vector3d &stop=Eigen::Vector3d(1, 0, 0), const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_mesh (const std::string &name="volkswagen", const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &scale=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_plane (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion &quat=scrimmage::Quaternion(0, 0, 0), const double &x_length=10.0, const double &y_length=10.0, const std::string &texture="", const bool &diffuse_lighting=false, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_pointcloud (const std::list< Eigen::Vector3d > &points, const std::list< Eigen::Vector3d > &point_colors, const double &size=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_polydata (const std::list< Eigen::Vector3d > &points, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_polygon (const std::list< Eigen::Vector3d > &points, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_polyhedron (const std::list< Eigen::Vector3d > &points, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_polyline (const std::list< Eigen::Vector3d > &points, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_sphere (const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const double &radius=1.0, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_spline (const std::list< Eigen::Vector3d > &points, const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_text (const std::string &text, const Eigen::Vector3d &center=Eigen::Vector3d(0, 0, 0), const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
ShapePtr make_triangle (const Eigen::Vector3d &point0=Eigen::Vector3d(1, 0, 0), const Eigen::Vector3d &point1=Eigen::Vector3d(0, 1, 0), const Eigen::Vector3d &point2=Eigen::Vector3d(-1, 0, 0), const Eigen::Vector3d &color=Eigen::Vector3d(0, 0, 255), const double &opacity=1.0)
Typedef Documentation
using scrimmage::shape::ShapePtr = typedef std::shared_ptr<scrimmage_proto::Shape>
Definition at line 49 of file Shape.h.
Function Documentation
ShapePtr scrimmage::shape::make_shape (const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 46 of file Shape.cpp.
References scrimmage::set().
Referenced by make_arc(), make_arrow(), make_circle(), make_cone(), make_cuboid(), make_ellipse(), make_line(), make_mesh(), make_plane(), make_pointcloud(), make_polydata(), make_polygon(), make_polyhedron(), make_polyline(), make_sphere(), make_spline(), make_text(), and make_triangle().
{
     auto shape = std::make_shared<scrimmage_proto::Shape>();
     sc::set(shape->mutable_color(), color);
     shape->set_opacity(opacity);
     shape->set_persistent(true);
     shape->set_ttl(0);
     return shape;
 }
ShapePtr scrimmage::shape::make_arc (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & radius = 1.0, const double & angle = M_PI / 2.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 56 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_arc()->mutable_circle()->mutable_center(), center);
     sc::set(shape->mutable_arc()->mutable_circle()->mutable_quat(), quat);
     shape->mutable_arc()->mutable_circle()->set_radius(radius);
     shape->mutable_arc()->set_angle(angle);
     return shape;
 }
ShapePtr scrimmage::shape::make_arrow (const Eigen::Vector3d & pos = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & length = 10.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 70 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     Eigen::Vector3d head = pos + quat * (Eigen::Vector3d::UnitX() * length);
     sc::set(shape->mutable_arrow()->mutable_tail(), pos);
     sc::set(shape->mutable_arrow()->mutable_head(), head);
     return shape;
 }
ShapePtr scrimmage::shape::make_circle (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & radius = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 82 of file Shape.cpp.
References make_shape(), and scrimmage::set().
Referenced by REGISTER_PLUGIN().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_circle()->mutable_center(), center);
     sc::set(shape->mutable_circle()->mutable_quat(), quat);
     shape->mutable_circle()->set_radius(radius);
     shape->mutable_circle()->set_solid(true);
     return shape;
 }
ShapePtr scrimmage::shape::make_cone (const Eigen::Vector3d & direction = Eigen::Vector3d(0, 0, 1), const Eigen::Vector3d & apex = Eigen::Vector3d(0, 0, 1), const double & height = 1.0, const double & base_radius = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 95 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_cone()->mutable_direction(), direction);
     sc::set(shape->mutable_cone()->mutable_apex(), apex);
     shape->mutable_cone()->set_height(height);
     shape->mutable_cone()->set_base_radius(base_radius);
     return shape;
 }
ShapePtr scrimmage::shape::make_cuboid (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & x_length = 1.0, const double & y_length = 1.0, const double & z_length = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 109 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     shape->mutable_cuboid()->set_x_length(x_length);
     shape->mutable_cuboid()->set_y_length(y_length);
     shape->mutable_cuboid()->set_z_length(z_length);
     sc::set(shape->mutable_cuboid()->mutable_center(), center);
     sc::set(shape->mutable_cuboid()->mutable_quat(), quat);
     return shape;
 }
ShapePtr scrimmage::shape::make_ellipse (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & x_radius = 2.0, const double & y_radius = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 125 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_ellipse()->mutable_center(), center);
     sc::set(shape->mutable_ellipse()->mutable_quat(), quat);
     shape->mutable_ellipse()->set_x_radius(x_radius);
     shape->mutable_ellipse()->set_y_radius(y_radius);
     return shape;
 }
ShapePtr scrimmage::shape::make_line (const Eigen::Vector3d & start = Eigen::Vector3d(0, 0, 0), const Eigen::Vector3d & stop = Eigen::Vector3d(1, 0, 0), const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 139 of file Shape.cpp.
References make_shape(), and scrimmage::set().
Referenced by REGISTER_PLUGIN().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_line()->mutable_start(), start);
     sc::set(shape->mutable_line()->mutable_end(), stop);
     return shape;
 }
ShapePtr scrimmage::shape::make_mesh (const std::string & name = "volkswagen", const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & scale = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 149 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     shape->mutable_mesh()->set_name(name);
     sc::set(shape->mutable_mesh()->mutable_center(), center);
     sc::set(shape->mutable_mesh()->mutable_quat(), quat);
     shape->mutable_mesh()->set_scale(scale);
     return shape;
 }
ShapePtr scrimmage::shape::make_plane (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const scrimmage::Quaternion & quat = scrimmage::Quaternion(0, 0, 0), const double & x_length = 10.0, const double & y_length = 10.0, const std::string & texture = "", const bool & diffuse_lighting = false, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 163 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_plane()->mutable_center(), center);
     sc::set(shape->mutable_plane()->mutable_quat(), quat);
     shape->mutable_plane()->set_x_length(x_length);
     shape->mutable_plane()->set_y_length(y_length);
     shape->mutable_plane()->set_texture(texture);
     shape->mutable_plane()->set_diffuse_lighting(diffuse_lighting);
     return shape;
 }
ShapePtr scrimmage::shape::make_pointcloud (const std::list< Eigen::Vector3d > & points, const std::list< Eigen::Vector3d > & point_colors, const double & size = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 181 of file Shape.cpp.
References make_shape(), and scrimmage::set().
Referenced by REGISTER_PLUGIN().
{
     auto shape = make_shape(color, opacity);
     shape->mutable_pointcloud()->set_size(size);
     for (const Eigen::Vector3d &p : points) {
         auto *point = shape->mutable_pointcloud()->add_point();
         sc::set(point, p);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_polydata (const std::list< Eigen::Vector3d > & points, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 195 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     for (auto &point : points) {
         auto p = shape->mutable_polydata()->add_point();
         sc::set(p, point);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_polygon (const std::list< Eigen::Vector3d > & points, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 206 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     for (auto &point : points) {
         auto p = shape->mutable_polygon()->add_point();
         sc::set(p, point);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_polyhedron (const std::list< Eigen::Vector3d > & points, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 217 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     for (auto point : points) {
         auto p = shape->mutable_polyhedron()->add_point();
         sc::set(p, point);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_polyline (const std::list< Eigen::Vector3d > & points, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 228 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     for (auto &point : points) {
         auto p = shape->mutable_polyline()->add_point();
         sc::set(p, point);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_sphere (const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const double & radius = 1.0, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 239 of file Shape.cpp.
References make_shape(), and scrimmage::set().
Referenced by scrimmage::interaction::BulletCollision::init(), and REGISTER_PLUGIN().
{
     auto shape = make_shape(color, opacity);
     shape->mutable_sphere()->set_radius(radius);
     sc::set(shape->mutable_sphere()->mutable_center(), center);
     return shape;
 }
ShapePtr scrimmage::shape::make_spline (const std::list< Eigen::Vector3d > & points, const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 249 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     for (auto point : points) {
         auto p = shape->mutable_spline()->add_point();
         sc::set(p, point);
     }
     return shape;
 }
ShapePtr scrimmage::shape::make_text (const std::string & text, const Eigen::Vector3d & center = Eigen::Vector3d(0, 0, 0), const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 260 of file Shape.cpp.
References make_shape(), and scrimmage::set().
Referenced by REGISTER_PLUGIN().
{
     auto shape = make_shape(color, opacity);
     shape->mutable_text()->set_text(text);
     shape->mutable_text()->set_scale(1.0);
     sc::set(shape->mutable_text()->mutable_center(), center);
     return shape;
 }
ShapePtr scrimmage::shape::make_triangle (const Eigen::Vector3d & point0 = Eigen::Vector3d(1, 0, 0), const Eigen::Vector3d & point1 = Eigen::Vector3d(0, 1, 0), const Eigen::Vector3d & point2 = Eigen::Vector3d(-1, 0, 0), const Eigen::Vector3d & color = Eigen::Vector3d(0, 0, 255), const double & opacity = 1.0)
Definition at line 271 of file Shape.cpp.
References make_shape(), and scrimmage::set().
{
     auto shape = make_shape(color, opacity);
     sc::set(shape->mutable_triangle()->mutable_point0(), point0);
     sc::set(shape->mutable_triangle()->mutable_point1(), point1);
     sc::set(shape->mutable_triangle()->mutable_point2(), point2);
     return shape;
 }