SCRIMMAGE: scrimmage::autonomy Namespace Reference
scrimmage::autonomy Namespace Reference
Namespaces
motor_schemas
Classes
class APITester
class ArduPilot
class AuctionAssign
class AutonomyExecutor
class AvoidWalls
class Boids
class BoundaryDefense
class CommandStringRelay
class Control3D
class FlightGearMultiplayer
class Follow
class GoToWaypoint
class GraphvizFSM
class JoystickAutonomy
class MOOSAutonomy
class MOOSNode
class MotorSchemas
class OpenAIActions
class OpenAIObservations
class Predator
class PyAutonomy
class RLConsensus
class RLSimple
class ROSAirSim
class ROSAutonomy
class ROSControl
class ScrimmageOpenAIAutonomy
class ShapeDraw
class Straight
class TakeFlag
class TrailMS
class TrajectoryPoint
class TrajectoryRecordPlayback
class Waypoint
class WaypointDispatcher
class WaypointGenerator
class WaypointList
class WaypointListProcessor
Enumerations
enum CombineActors { CombineActors::NO, CombineActors::YES }
enum UseGlobalSensor { UseGlobalSensor::NO, UseGlobalSensor::YES }
enum StaticObsSpace { StaticObsSpace::NO, StaticObsSpace::YES }
Functions
std::tuple< OpenAIActions, OpenAIObservations, pybind11::object > DLL_PUBLIC init_actor_func (std::vector< std::shared_ptr< ScrimmageOpenAIAutonomy >> autonomies, const std::map< std::string, std::string > &params, CombineActors combine_actors, UseGlobalSensor global_sensor, bool grpc_mode)
pybind11::object DLL_PUBLIC get_gym_space (const std::string &type)
void DLL_PUBLIC to_continuous (std::vector< std::pair< double, double >> &p, pybind11::list &minima, pybind11::list &maxima)
void DLL_PUBLIC to_discrete (std::vector< int > &p, pybind11::list &maxima)
pybind11::object DLL_PUBLIC create_space (pybind11::list discrete_maxima, pybind11::list continuous_minima, pybind11::list continuous_maxima)
std::ostream & operator<< (std::ostream &os, Waypoint &wp)
bool operator== (const Waypoint &lhs, const Waypoint &rhs)
void to_discrete (std::vector< int > &p, py::list &maxima)
Enumeration Type Documentation
CombineActors
enum scrimmage::autonomy::CombineActors strong
Enumerator
NO
YES
Definition at line 54 of file ActorFunc.h.
 {NO, YES};
UseGlobalSensor
enum scrimmage::autonomy::UseGlobalSensor strong
Enumerator
NO
YES
Definition at line 55 of file ActorFunc.h.
 {NO, YES};
StaticObsSpace
enum scrimmage::autonomy::StaticObsSpace strong
Enumerator
NO
YES
Definition at line 56 of file ActorFunc.h.
 {NO, YES};
Function Documentation
init_actor_func()
std::tuple< OpenAIActions, OpenAIObservations, pybind11::object > scrimmage::autonomy::init_actor_func (std::vector< std::shared_ptr< ScrimmageOpenAIAutonomy >> autonomies, const std::map< std::string, std::string > & params, CombineActors combine_actors, UseGlobalSensor global_sensor, bool grpc_mode)
Definition at line 57 of file ActorFunc.cpp.
{
     if (autonomies.empty()) {
         return std::make_tuple(OpenAIActions(), OpenAIObservations(), pybind11::none());
     }
     OpenAIActions actions;
     br::copy(autonomies, std::back_inserter(actions.ext_ctrl_vec()));
     actions.create_action_space(combine_actors == CombineActors::YES);
     OpenAIObservations observations;
     observations.set_combine_actors(combine_actors == CombineActors::YES);
     observations.set_global_sensor(global_sensor == UseGlobalSensor::YES);
     for (auto autonomy : autonomies) {
         observations.add_sensors(autonomy->parent()->sensors());
         if (global_sensor == UseGlobalSensor::YES) break;
     }
     observations.create_observation_space(autonomies.size(), true);
     py::object actor_func = py::none();
     py::object actor_init_func = py::none();
     if (!grpc_mode) {
         // get the actor func
         const std::string module_str = get("module", params, "");
         if (module_str == "") {
             std::cout << "ERROR: ActorFunc: Missing parameter: module" << std::endl;
         }
         const std::string actor_init_func_str = get("actor_init_func", params, "");
         if (actor_init_func_str == "") {
             std::cout << "ERROR: ActorFunc: Missing parameter: actor_init_func" << std::endl;
         }
         py::object m = py::module::import(module_str.c_str());
         actor_init_func = m.attr(actor_init_func_str.c_str());
         actor_func = actor_init_func(
             actions.action_space, observations.observation, params);
     }
     return std::make_tuple(actions, observations, actor_func);
 }
References scrimmage::autonomy::OpenAIActions::action_space, scrimmage::autonomy::OpenAIObservations::add_sensors(), scrimmage::autonomy::OpenAIActions::create_action_space(), scrimmage::autonomy::OpenAIObservations::create_observation_space(), scrimmage::autonomy::OpenAIActions::ext_ctrl_vec(), scrimmage::get(), scrimmage::autonomy::OpenAIObservations::observation, scrimmage::autonomy::OpenAIObservations::set_combine_actors(), scrimmage::autonomy::OpenAIObservations::set_global_sensor(), and YES.
Referenced by scrimmage::autonomy::ScrimmageOpenAIAutonomy::step_autonomy().
get_gym_space()
pybind11::object scrimmage::autonomy::get_gym_space (const std::string & type)
Definition at line 99 of file OpenAIUtils.cpp.
{
     return pybind11::module::import("gym.spaces").attr(type.c_str());
 }
Referenced by scrimmage::autonomy::OpenAIActions::create_action_space(), scrimmage::autonomy::OpenAIObservations::create_observation_space(), and create_space().
to_continuous()
void scrimmage::autonomy::to_continuous (std::vector< std::pair< double, double >> & p, pybind11::list & minima, pybind11::list & maxima)
Definition at line 42 of file OpenAIUtils.cpp.
{
     for (auto &value : p) {
         py::list min_max;
         minima.append(value.first);
         maxima.append(value.second);
     }
 }
Referenced by scrimmage::autonomy::OpenAIActions::create_action_space(), and scrimmage::autonomy::OpenAIObservations::create_observation_space().
to_discrete() [1/2]
void DLL_PUBLIC scrimmage::autonomy::to_discrete (std::vector< int > & p, pybind11::list & maxima)
Referenced by scrimmage::autonomy::OpenAIActions::create_action_space(), and scrimmage::autonomy::OpenAIObservations::create_observation_space().
create_space()
pybind11::object scrimmage::autonomy::create_space (pybind11::list discrete_maxima, pybind11::list continuous_minima, pybind11::list continuous_maxima)
Definition at line 58 of file OpenAIUtils.cpp.
{
     py::module np = py::module::import("numpy");
     py::object np_array = np.attr("array");
     py::object np_float32 = np.attr("float32");
     py::object gym_discrete_space = get_gym_space("Discrete");
     py::object gym_multidiscrete_space = get_gym_space("MultiDiscrete");
     py::object gym_box_space = get_gym_space("Box");
     py::object gym_tuple_space = get_gym_space("Tuple");
     py::object discrete_space = py::len(discrete_count) == 1 ?
         gym_discrete_space(discrete_count[0]) :
         gym_multidiscrete_space(discrete_count);
     py::object continuous_space = gym_box_space(
         np_array(continuous_minima),
         np_array(continuous_maxima),
         py::none(),
         np_float32);
     int len_discrete = py::len(discrete_count);
     int len_continuous = py::len(continuous_minima);
     if (len_discrete != 0 && len_continuous != 0) {
         py::list spaces;
         spaces.append(discrete_space);
         spaces.append(continuous_space);
         return gym_tuple_space(spaces);
     } else if (len_discrete != 0) {
         return discrete_space;
     } else if (len_continuous != 0) {
         return continuous_space;
     } else {
         throw std::runtime_error(
             "discrete and continuous space do not have maxima set");
     }
 }
References get_gym_space().
Referenced by scrimmage::autonomy::OpenAIActions::create_action_space(), and scrimmage::autonomy::OpenAIObservations::create_observation_space().
operator<<()
std::ostream& scrimmage::autonomy::operator<< (std::ostream & os, Waypoint & wp)
Definition at line 127 of file Waypoint.cpp.
{
     os << std::setprecision(10)
        << wp.time() << ", "
        << wp.latitude() << ", " << wp.longitude() << ", " << wp.altitude()
        << wp.quat() << ", "
        << wp.position_tolerance() << ", "
        << wp.quat_tolerance();
     return os;
 }
References scrimmage::autonomy::Waypoint::altitude(), scrimmage::autonomy::Waypoint::latitude(), scrimmage::autonomy::Waypoint::longitude(), scrimmage::autonomy::Waypoint::position_tolerance(), scrimmage::autonomy::Waypoint::quat(), scrimmage::autonomy::Waypoint::quat_tolerance(), and scrimmage::autonomy::Waypoint::time().
operator==()
bool scrimmage::autonomy::operator== (const Waypoint & lhs, const Waypoint & rhs)
Definition at line 137 of file Waypoint.cpp.
{
     auto far = [&](double a, double b) {return std::abs(a - b) > 1.0e-6;};
     return !far(lhs.altitude(), rhs.latitude()) &&
            !far(lhs.longitude(), rhs.longitude()) &&
            !far(lhs.altitude(), rhs.altitude());
 }
References scrimmage::autonomy::Waypoint::altitude(), scrimmage::autonomy::Waypoint::latitude(), and scrimmage::autonomy::Waypoint::longitude().
to_discrete() [2/2]
void scrimmage::autonomy::to_discrete (std::vector< int > & p, py::list & maxima)
Definition at line 52 of file OpenAIUtils.cpp.
{
     for (auto &value : p) {
         maxima.append(value);
     }
 }