SCRIMMAGE: /root/scrimmage/scrimmage/src/plugins/controller/UUV6DOFLinearEnergy/UUV6DOFLinearEnergy.cpp File Reference
UUV6DOFLinearEnergy.cpp File Reference
Brief file description.
#include <scrimmage/plugins/controller/UUV6DOFLinearEnergy/UUV6DOFLinearEnergy.h>
#include <scrimmage/plugin_manager/RegisterPlugin.h>
#include <scrimmage/entity/Entity.h>
#include <scrimmage/math/State.h>
#include <scrimmage/common/Utilities.h>
#include <scrimmage/parse/ParseUtils.h>
#include <iostream>
#include <limits>
Functions
REGISTER_PLUGIN (scrimmage::Controller, scrimmage::controller::UUV6DOFLinearEnergy, UUV6DOFLinearEnergy_plugin) namespace scrimmage
Detailed Description
Brief file description.
LICENSE
Copyright (C) 2017 by the Georgia Tech Research Institute (GTRI)
This file is part of SCRIMMAGE.
SCRIMMAGE is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SCRIMMAGE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with SCRIMMAGE. If not, see http://www.gnu.org/licenses/.
Author
Kevin DeMarco kevin.nosp@m..dem.nosp@m.arco@.nosp@m.gtri.nosp@m..gate.nosp@m.ch.e.nosp@m.du
Eric Squires eric..nosp@m.squi.nosp@m.res@g.nosp@m.tri..nosp@m.gatec.nosp@m.h.ed.nosp@m.u
Date
31 July 2017
Version
0.1.0
DESCRIPTION
A Long description goes here.
Definition in file UUV6DOFLinearEnergy.cpp.
Function Documentation
REGISTER_PLUGIN()
REGISTER_PLUGIN (scrimmage::Controller , scrimmage::controller::UUV6DOFLinearEnergy , UUV6DOFLinearEnergy_plugin)
Definition at line 49 of file UUV6DOFLinearEnergy.cpp.
                     {
 namespace controller {
 void UUV6DOFLinearEnergy::init(std::map<std::string, std::string> &params) {
     energy_ = sc::get<double>("energy_initial", params, energy_);
     energy_max_ = sc::get<double>("energy_max", params, energy_max_);
     energy_min_ = sc::get<double>("energy_min", params, energy_min_);
     in_throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::In);
     in_elevator_idx_ = vars_.declare(VariableIO::Type::elevator, VariableIO::Direction::In);
     in_rudder_idx_ = vars_.declare(VariableIO::Type::rudder, VariableIO::Direction::In);
     out_throttle_idx_ = vars_.declare(VariableIO::Type::throttle, VariableIO::Direction::Out);
     out_elevator_idx_ = vars_.declare(VariableIO::Type::elevator, VariableIO::Direction::Out);
     out_rudder_idx_ = vars_.declare(VariableIO::Type::rudder, VariableIO::Direction::Out);
 }
 bool UUV6DOFLinearEnergy::step(double t, double dt) {
     double throttle = vars_.input(in_throttle_idx_);
     energy_ -= throttle * dt;
     if (energy_ <= energy_min_) {
         energy_ = energy_min_;
         throttle = 0;
     }
     vars_.output(out_throttle_idx_, throttle);
     vars_.output(out_elevator_idx_, vars_.input(in_elevator_idx_));
     vars_.output(out_rudder_idx_, vars_.input(in_rudder_idx_));
     return true;
 }
 } // namespace controller
 } // namespace scrimmage
References scrimmage::VariableIO::declare(), scrimmage::VariableIO::elevator, scrimmage::controller::UUV6DOFLinearEnergy::energy_, scrimmage::controller::UUV6DOFLinearEnergy::energy_max_, scrimmage::controller::UUV6DOFLinearEnergy::energy_min_, scrimmage::VariableIO::In, scrimmage::controller::UUV6DOFLinearEnergy::in_elevator_idx_, scrimmage::controller::UUV6DOFLinearEnergy::in_rudder_idx_, scrimmage::controller::UUV6DOFLinearEnergy::in_throttle_idx_, scrimmage::controller::UUV6DOFLinearEnergy::init(), scrimmage::VariableIO::input(), scrimmage::VariableIO::Out, scrimmage::controller::UUV6DOFLinearEnergy::out_elevator_idx_, scrimmage::controller::UUV6DOFLinearEnergy::out_rudder_idx_, scrimmage::controller::UUV6DOFLinearEnergy::out_throttle_idx_, scrimmage::VariableIO::output(), scrimmage::VariableIO::rudder, scrimmage::controller::UUV6DOFLinearEnergy::step(), scrimmage::VariableIO::throttle, and scrimmage::EntityPlugin::vars_.