add_subdirectory(Boundary)
add_subdirectory(BulletCollision)
add_subdirectory(CaptureInBoundaryInteraction)
add_subdirectory(EnforceBoundaryInteraction)
add_subdirectory(ExternalForceField)
add_subdirectory(FlagCaptureInteraction)
add_subdirectory(GraphInteraction)
add_subdirectory(GroundCollision)
add_subdirectory(GRPCCommandString)
add_subdirectory(MapGen2D)
add_subdirectory(RandomAttrit)
add_subdirectory(ROSClockServer)
add_subdirectory(ROSShapeViz)
add_subdirectory(SimpleCapture)
add_subdirectory(SimpleCollision)
add_subdirectory(SpatialCollision)
add_subdirectory(TerrainGenerator)

set(PROJECT_PLUGINS ${PROJECT_PLUGINS} PARENT_SCOPE)
