add_subdirectory(AircraftPIDController)
# add_subdirectory(AircraftToSingleIntegratorController)
add_subdirectory(DirectController)
add_subdirectory(DoubleIntegratorControllerVelYaw)
add_subdirectory(DoubleIntegratorControllerWaypoint)
add_subdirectory(FixedWing6DOFControllerPID)
add_subdirectory(FixedWing6DOFControllerROS)
add_subdirectory(HarmonicOscillatorConstController)
add_subdirectory(JoystickController)
add_subdirectory(JSBSimControlControllerHeadingPID)
add_subdirectory(JSBSimModelControllerDirect)
add_subdirectory(JSBSimModelControllerHeadingPID)
add_subdirectory(MotionBattery)
add_subdirectory(MultirotorControllerOmega)
add_subdirectory(MultirotorControllerPID)
add_subdirectory(RigidBody6DOFControllerPID)
add_subdirectory(RigidBody6DOFControllerROS)
add_subdirectory(SimpleAircraftControllerPID)
add_subdirectory(SimpleCarControllerHeading)
add_subdirectory(SimpleQuadrotorControllerLQR)
add_subdirectory(SingleIntegratorControllerSimple)
add_subdirectory(SingleIntegratorControllerWaypoint)
add_subdirectory(UnicycleControllerPoint)
add_subdirectory(UnicyclePID)
add_subdirectory(UUV6DOFLinearEnergy)
add_subdirectory(UUV6DOFPIDController)

set(PROJECT_PLUGINS ${PROJECT_PLUGINS} PARENT_SCOPE)
