#ifndef GPU_KERNELS_SCRIMMAGE_DEFS_H
#define GPU_KERNELS_SCRIMMAGE_DEFS_H

enum StateParams {
  STATE_X = 0,
  STATE_Y,
  STATE_Z,
  STATE_X_VEL,
  STATE_Y_VEL,
  STATE_Z_VEL,
  STATE_X_ANG_VEL,
  STATE_Y_ANG_VEL,
  STATE_Z_ANG_VEL,
  STATE_QUAT_W,
  STATE_QUAT_X,
  STATE_QUAT_Y,
  STATE_QUAT_Z,
  STATE_NUM_PARAMS
};

#endif //GPU_KERNELS_SCRIMMAGE_DEFS_H
