add_subdirectory(APITester)
add_subdirectory(RuntimeOverrideSpawner)
add_subdirectory(ArduPilot)
add_subdirectory(AuctionAssign)
add_subdirectory(AutonomyExecutor)
add_subdirectory(AvoidEntityMS)
add_subdirectory(AvoidWalls)
add_subdirectory(Boids)
add_subdirectory(BoundaryDefense)
add_subdirectory(CommandStringRelay)
add_subdirectory(Control3D)
add_subdirectory(FlightGearMultiplayer)
add_subdirectory(GoToWaypoint)
add_subdirectory(GraphvizFSM)
add_subdirectory(JoystickAutonomy)
add_subdirectory(MOOSAutonomy)
add_subdirectory(MotorSchemas)
add_subdirectory(MoveToGoalMS)
add_subdirectory(Predator)
add_subdirectory(ROSAirSim)
add_subdirectory(ROSAutonomy)
add_subdirectory(ROSControl)
add_subdirectory(ShapeDraw)
add_subdirectory(Straight)
add_subdirectory(TakeFlag)
add_subdirectory(TrailMS)
add_subdirectory(TrajectoryRecordPlayback)
add_subdirectory(WaypointDispatcher)
add_subdirectory(WaypointGenerator)
add_subdirectory(follow)

# if (GRPC_FOUND AND EXTERNAL)
#     add_subdirectory(ExternalControl)
#     add_subdirectory(TutorialOpenAIAutonomy)
# endif()

set(PROJECT_PLUGINS ${PROJECT_PLUGINS} PARENT_SCOPE)
