###############################################################################
# Dockerfile to build SCRIMMAGE
###############################################################################
FROM ubuntu:16.04

MAINTAINER Kevin DeMarco

# Copy repo code into image
RUN mkdir -p /root/scrimmage
COPY ./ /root/scrimmage/

WORKDIR /root/scrimmage

# Install dependencies provided by package manager
RUN ./setup/install-binaries.sh

# Build 3rd-party dependencies
RUN /bin/bash -c "cd 3rd-party && \
    mkdir -p build && \
    cd build && \
    cmake .. && \
    source ~/.scrimmage/setup.bash && \
    make"

RUN /bin/bash -c "mkdir -p build && \
    cd build && \
    cmake .. -DBUILD_TESTS=ON && \
    source ~/.scrimmage/setup.bash && \
    make"

# Run tests (TODO: this will eventually be in Jenkins workflow when a plugin
# bug is fixed
RUN /bin/bash -c "cd build && \
    source ~/.scrimmage/setup.bash && \
    make test && \
    scrimmage ../missions/straight-no-gui.xml"
