name: Deploy Sphinx Docs to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: ["Ubuntu-24.04"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build website in docker container
        run: |
          docker build -t scrimmage:noble-${GITHUB_SHA} -f ./ci/dockerfiles/ubuntu --target website .
          docker create --name mycontainer scrimmage:noble-${GITHUB_SHA}
          docker cp mycontainer:/root/scrimmage/scrimmage/build/docs ./doc_output
          mkdir website/
          cp -r ./doc_output/jekyll/* ./website
          cp -r ./doc_output/sphinx ./website
          cp -r ./doc_output/doxygen ./website
          touch ./website/.nojekyll # Disable Jekyll
          rm ./website/index.html
          # just redirect the to sphinx in the top level index.html
          # Could potentially add a page that directs to doxygen here as well
          echo -e "<!DOCTYPE html>\n<html>\n\t<head>\n\t\t<meta http-equiv=\"refresh\" content=\"0; url=./sphinx/html/index.html\">\n\t</head>\n</html>" >> ./website/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website # The folder the action should deploy.


      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./website
      #     publish_branch: gh-pages # Or your chosen publishing branch
